<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Reactor;

/** Browser transaction, exact rollback, scoped offline replay, and SSE runtime. */
final class ReactorTransactionClientAssets {
	public static function javascript(): string {
		return <<<'JS'

/* Dataphyre Reactor transactional state runtime. */
(function(window,document){
if(window.DataphyreReactorTransactions){return;}
var SCHEMA=1,inflight=new WeakMap(),streams=new Map(),offlinePrefix="dp-reactor-offline:v1:",cursorPrefix="dp-reactor-cursor:v1:",legacyPrefix="dp-reactor-offline:";
var limits={ttl:86400000,maxTtl:604800000,maxItems:100,maxBytes:2097152,maxItemBytes:65536};
function clone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value));}
function normalizePath(path){return String(path||"").replace(/^\//,"").replace(/~1/g,"/").replace(/~0/g,"~").split(/[./]/).filter(Boolean);}
function read(state,path){var cursor=state,parts=normalizePath(path);for(var i=0;i<parts.length;i++){if(!cursor||typeof cursor!=="object"||!(parts[i] in cursor)){return {exists:false,value:null};}cursor=cursor[parts[i]];}return {exists:true,value:clone(cursor)};}
function write(state,path,value){var parts=normalizePath(path),cursor=state;parts.forEach(function(part,index){if(index===parts.length-1){cursor[part]=clone(value);return;}if(!cursor[part]||typeof cursor[part]!=="object"){cursor[part]={};}cursor=cursor[part];});}
function remove(state,path){var parts=normalizePath(path),cursor=state;parts.forEach(function(part,index){if(!cursor||typeof cursor!=="object"){return;}if(index===parts.length-1){delete cursor[part];return;}cursor=cursor[part];});}
function applyPatch(state,patch){var before=read(state,patch.path),inverse={operation:before.exists?"set":"remove",path:patch.path,value:before.value},op=patch.operation||patch.op||"set";state=clone(state||{});if(op==="set"){write(state,patch.path,patch.value);}else if(op==="remove"){remove(state,patch.path);}else if(op==="merge"){write(state,patch.path,Object.assign({},before.exists&&before.value||{},clone(patch.value||{})));}else if(op==="increment"){write(state,patch.path,(before.exists?Number(before.value):0)+Number(patch.value||0));}else if(op==="append"){var list=before.exists&&Array.isArray(before.value)?before.value:[];list.push(clone(patch.value));write(state,patch.path,list);}else if(op==="test"&&(!before.exists||JSON.stringify(before.value)!==JSON.stringify(patch.value))){throw new Error("State precondition failed at "+patch.path);}return {state:state,inverse:inverse};}
function apply(state,patches){var inverse=[];(patches||[]).forEach(function(patch){var result=applyPatch(state,patch);state=result.state;inverse.unshift(result.inverse);});return {state:state,inverse:inverse};}
function randomId(){return "rtx_"+(window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));}
function stateOf(root){try{return JSON.parse(root.getAttribute("data-dp-reactor-transaction-state")||root.getAttribute("data-dp-reactor-state")||"{}");}catch(error){return {};}}
function versionOf(root){return Math.max(0,parseInt(root.getAttribute("data-dp-reactor-version")||"0",10)||0);}
function publish(root,state,version,detail){root.setAttribute("data-dp-reactor-transaction-state",JSON.stringify(state||{}));root.setAttribute("data-dp-reactor-version",String(version||0));root.dispatchEvent(new CustomEvent("dp:reactor-state",{bubbles:true,detail:Object.assign({state:state,version:version},detail||{})}));}
function emit(root,name,detail){if(root&&root.dispatchEvent){root.dispatchEvent(new CustomEvent("dp:reactor-transaction-"+name,{bubbles:true,detail:detail||{}}));}}
function delay(ms){return new Promise(function(resolve){setTimeout(resolve,ms);});}
function option(root,options,key,attribute){if(options&&options[key]!=null&&String(options[key])!==""){return String(options[key]);}return root&&root.getAttribute?String(root.getAttribute(attribute)||""):"";}
function scopeOf(root,options){options=options||{};var scope={tenant:option(root,options,"tenant","data-dp-reactor-tenant"),user:option(root,options,"user","data-dp-reactor-user"),session:option(root,options,"session","data-dp-reactor-session"),contract:option(root,options,"contractVersion","data-dp-reactor-contract-version")||"1"};return scope.tenant&&scope.user&&scope.session&&scope.contract?scope:null;}
function scopeToken(scope){return [scope.tenant,scope.user,scope.session,scope.contract].map(function(value){return encodeURIComponent(value);}).join(":");}
function componentOf(root,options,tx){return String(tx&&tx.component||(options&&options.component)||(root&&root.getAttribute&&root.getAttribute("data-dp-reactor-component"))||"");}
function offlineKey(root,options,tx){var scope=scopeOf(root,options),component=componentOf(root,options,tx);return scope&&component?offlinePrefix+scopeToken(scope)+":"+encodeURIComponent(component):null;}
function cursorKey(root,options,component){var scope=scopeOf(root,options);return scope&&component?cursorPrefix+scopeToken(scope)+":"+encodeURIComponent(component):null;}
function numberOption(root,options,key,attribute,fallback,min,max){var value=parseInt(option(root,options,key,attribute),10);if(!isFinite(value)){value=fallback;}return Math.max(min,Math.min(max,value));}
function bytes(value){var text=JSON.stringify(value);return window.TextEncoder?new TextEncoder().encode(text).length:text.length*2;}
function expiryOf(tx,root,options){var now=Date.now(),ttl=numberOption(root,options,"offlineTtlMs","data-dp-reactor-offline-ttl",limits.ttl,60000,limits.maxTtl),expires=tx.expires_at==null?now+ttl:Number(tx.expires_at);if(expires<1000000000000){expires*=1000;}return Math.min(now+ttl,expires);}
function sameScope(a,b){return !!a&&!!b&&a.tenant===b.tenant&&a.user===b.user&&a.session===b.session&&a.contract===b.contract;}
function loadEnvelope(key,scope){var empty={schema_version:SCHEMA,scope:scope,updated_at:Date.now(),items:[]};if(!key){return empty;}try{var value=JSON.parse(localStorage.getItem(key)||"null");if(!value||value.schema_version!==SCHEMA||!sameScope(value.scope,scope)||!Array.isArray(value.items)){return empty;}value.items=value.items.filter(function(item){return item&&item.transaction&&Number(item.expires_at||0)>Date.now();});return value;}catch(error){return empty;}}
function saveEnvelope(key,envelope){try{if(envelope.items.length){envelope.updated_at=Date.now();localStorage.setItem(key,JSON.stringify(envelope));}else{localStorage.removeItem(key);}return {ok:true};}catch(error){return {ok:false,reason:"storage_unavailable"};}}
function purgeLegacy(component){try{localStorage.removeItem(legacyPrefix+component);}catch(error){}}
function queue(root,tx,options){var scope=scopeOf(root,options),key=offlineKey(root,options,tx);if(!scope||!key){return {ok:false,reason:"scope_required"};}purgeLegacy(tx.component);var expires=expiryOf(tx,root,options);if(expires<=Date.now()){return {ok:false,reason:"expired"};}var item={transaction:clone(tx),queued_at:Date.now(),expires_at:expires},itemBytes=bytes(item),maxItem=numberOption(root,options,"offlineMaxItemBytes","data-dp-reactor-offline-max-item-bytes",limits.maxItemBytes,1024,limits.maxItemBytes);if(itemBytes>maxItem){return {ok:false,reason:"item_too_large",bytes:itemBytes,limit:maxItem};}var envelope=loadEnvelope(key,scope);envelope.items=envelope.items.filter(function(entry){return entry.transaction.id!==tx.id;});var maxItems=numberOption(root,options,"offlineMaxItems","data-dp-reactor-offline-max-items",limits.maxItems,1,250);if(envelope.items.length>=maxItems){return {ok:false,reason:"queue_full",limit:maxItems};}envelope.items.push(item);var maxBytes=numberOption(root,options,"offlineMaxBytes","data-dp-reactor-offline-max-bytes",limits.maxBytes,16384,limits.maxBytes);if(bytes(envelope)>maxBytes){return {ok:false,reason:"quota_exceeded",limit:maxBytes};}var saved=saveEnvelope(key,envelope);return saved.ok?{ok:true,key:key,expires_at:expires}:saved;}
function dequeue(root,tx,options){var scope=scopeOf(root,options),key=offlineKey(root,options,tx);if(!scope||!key){return false;}var envelope=loadEnvelope(key,scope),before=envelope.items.length;envelope.items=envelope.items.filter(function(item){return item.transaction.id!==tx.id;});saveEnvelope(key,envelope);return envelope.items.length!==before;}
function rollback(root,tx,inverse){try{publish(root,apply(stateOf(root),inverse).state,versionOf(root),{rollback:true,transaction:tx});}catch(error){emit(root,"rollback-failed",{transaction:tx,error:error});}}
function transaction(root,patches,options){options=options||{};var id=options.id||randomId();return {id:id,component:options.component||root.getAttribute("data-dp-reactor-component")||"",base_version:options.baseVersion==null?versionOf(root):options.baseVersion,idempotency_key:options.idempotencyKey||id,conflict_strategy:options.conflictStrategy||"reject",optimistic:options.optimistic!==false,offline_capable:options.offlineCapable===true,expires_at:options.expiresAt||null,patches:patches||[],retry:options.retry||{attempts:3,initial_delay_ms:150,maximum_delay_ms:5000,multiplier:2,jitter:.15},metadata:options.metadata||{}};}
async function dispatch(root,tx,options){options=options||{};var endpoint=options.endpoint||root.getAttribute("data-dp-reactor-transaction-endpoint")||root.getAttribute("data-dp-reactor-endpoint")||location.href,previous=stateOf(root),inverse=[],optimistic=tx.optimistic!==false;if(optimistic){try{var optimisticResult=apply(previous,tx.patches);inverse=optimisticResult.inverse;publish(root,optimisticResult.state,versionOf(root),{optimistic:true,transaction:tx});emit(root,"optimistic",{transaction:tx,state:optimisticResult.state});}catch(error){emit(root,"invalid",{transaction:tx,error:error});throw error;}}
if(!navigator.onLine&&tx.offline_capable){var queued=queue(root,tx,options);if(queued.ok){emit(root,"queued",{transaction:tx,queue:queued});return {schema_version:SCHEMA,status:"queued",ok:false,transaction_id:tx.id,offline:true};}if(optimistic){rollback(root,tx,inverse);}emit(root,"queue-rejected",{transaction:tx,queue:queued});return {schema_version:SCHEMA,status:"offline_rejected",ok:false,transaction_id:tx.id,error:{code:queued.reason,message:"The offline transaction could not be queued."}};}
var active=inflight.get(root);if(active&&options.cancelPrevious!==false){active.abort();}var controller=new AbortController();inflight.set(root,controller);var retry=tx.retry||{},attempts=Math.max(1,retry.attempts||3),lastError=null;
for(var attempt=1;attempt<=attempts;attempt++){try{emit(root,"sending",{transaction:tx,attempt:attempt});var headers={"Content-Type":"application/json","Accept":"application/json","X-Dataphyre-Reactor":"DataphyreReactor","X-Dataphyre-Reactor-Transaction":"1","X-Dataphyre-Reactor-Contract-Version":option(root,options,"contractVersion","data-dp-reactor-contract-version")||"1"},csrf=option(root,options,"csrfToken","data-dp-reactor-csrf");if(csrf){headers["X-CSRF-Token"]=csrf;}var response=await fetch(endpoint,{method:"POST",credentials:"same-origin",headers:headers,body:JSON.stringify({reactor_transaction:tx}),signal:controller.signal});var payload;try{payload=await response.json();}catch(parseError){payload={schema_version:SCHEMA,status:"failed",ok:false,error:{code:"invalid_response",message:"The Reactor endpoint returned invalid JSON."}};}if(!response.ok&&response.status>=500){throw new Error(payload.error&&payload.error.message||("HTTP "+response.status));}if(payload.ok||payload.status==="duplicate"||payload.status==="committed"){dequeue(root,tx,options);publish(root,payload.state||stateOf(root),payload.version==null?versionOf(root):payload.version,{transaction:tx,receipt:payload});emit(root,"committed",{transaction:tx,receipt:payload});return payload;}if(optimistic){rollback(root,tx,inverse);}emit(root,payload.status||"rejected",{transaction:tx,receipt:payload});return payload;}catch(error){lastError=error;if(error&&error.name==="AbortError"){emit(root,"cancelled",{transaction:tx});throw error;}if(attempt<attempts){var initial=Math.max(0,retry.initial_delay_ms||150),maximum=Math.max(initial,retry.maximum_delay_ms||5000),multiplier=Math.max(1,retry.multiplier||2),wait=Math.min(maximum,initial*Math.pow(multiplier,attempt-1));await delay(wait);}}}
var fallback=tx.offline_capable?queue(root,tx,options):{ok:false,reason:"not_offline_capable"};if(fallback.ok){emit(root,"queued",{transaction:tx,queue:fallback,after_failure:true});}else if(tx.offline_capable){emit(root,"queue-rejected",{transaction:tx,queue:fallback,after_failure:true});}if(optimistic&&!fallback.ok){rollback(root,tx,inverse);}emit(root,"failed",{transaction:tx,error:lastError,queue:fallback});if(fallback.ok){return {schema_version:SCHEMA,status:"queued",ok:false,transaction_id:tx.id,offline:true};}throw lastError||new Error("Reactor transaction failed.");}
async function drain(root,options){options=options||{};var scope=scopeOf(root,options),component=componentOf(root,options);if(!scope||!component){emit(root,"queue-scope-required",{});return [];}purgeLegacy(component);var key=offlineKey(root,options,{component:component}),envelope=loadEnvelope(key,scope),results=[];for(var i=0;i<envelope.items.length&&navigator.onLine;i++){var tx=envelope.items[i].transaction;if(Number(envelope.items[i].expires_at||0)<=Date.now()){dequeue(root,tx,options);continue;}try{var result=await dispatch(root,tx,Object.assign({},options,{cancelPrevious:false}));results.push(result);if(["denied","invalid","expired","offline_rejected","server_wins"].indexOf(result.status)!==-1){dequeue(root,tx,options);}if(result.status==="conflict"){break;}}catch(error){results.push({schema_version:SCHEMA,status:"failed",ok:false,transaction_id:tx.id,error:{code:"replay_failed",message:String(error&&error.message||error)}});break;}}return results;}
function withCursor(url,param,cursor){if(!cursor){return url;}try{var parsed=new URL(url,document.baseURI);if(!parsed.searchParams.has(param)){parsed.searchParams.set(param,String(cursor));}return parsed.toString();}catch(error){return url;}}
function subscribe(root,url,options){options=options||{};var component=componentOf(root,options),scope=scopeOf(root,options);if(!scope||!component){emit(root,"stream-scope-required",{});return function(){};}var token=scopeToken(scope),key=token+"|"+component+"|"+url,storedKey=cursorKey(root,options,component),cursor=Math.max(0,Number(options.cursor||0));try{cursor=Math.max(cursor,Number(sessionStorage.getItem(storedKey)||0));}catch(error){}if(streams.has(key)){streams.get(key).close();}var source=new EventSource(withCursor(url,options.cursorParam||"after_sequence",cursor),{withCredentials:true}),seen=[],eventTypes=["transaction.committed","transaction.rejected","transaction.conflict","transaction.denied","transaction.invalid","transaction.expired","transaction.failed","transaction.server_wins","reactor.error"].concat(Array.isArray(options.eventTypes)?options.eventTypes:[]);
function remember(id){if(!id){return false;}if(seen.indexOf(id)!==-1){return true;}seen.push(id);if(seen.length>512){seen.shift();}return false;}
function handle(event){var payload;try{payload=JSON.parse(event.data);}catch(error){emit(root,"stream-invalid",{error:error});return;}var sequence=Math.max(0,Number(event.lastEventId||payload.sequence||0)),transactionId=String(payload.transaction_id||"");if((sequence&&sequence<=cursor)||remember(transactionId)){emit(root,"stream-duplicate",{event:payload,sequence:sequence});return;}var currentVersion=versionOf(root),nextVersion=Math.max(0,Number(payload.version||0));if(payload.state&&typeof payload.state==="object"){publish(root,payload.state,nextVersion||currentVersion,{stream:true,event:payload});}else if(Array.isArray(payload.patches)&&nextVersion===currentVersion+1){try{publish(root,apply(stateOf(root),payload.patches).state,nextVersion,{stream:true,event:payload});}catch(error){emit(root,"stream-invalid",{event:payload,error:error});}}else if(nextVersion>currentVersion+1){emit(root,"stream-gap",{event:payload,expected_version:currentVersion+1,actual_version:nextVersion});if(typeof options.onGap==="function"){options.onGap(payload,root);}}if(sequence){cursor=sequence;try{sessionStorage.setItem(storedKey,String(cursor));}catch(error){}}emit(root,"stream",{type:payload.type||event.type,event:payload,sequence:sequence});}
source.onmessage=handle;eventTypes.filter(function(type,index,list){return type&&list.indexOf(type)===index;}).forEach(function(type){source.addEventListener(type,handle);});source.onopen=function(){emit(root,"stream-open",{cursor:cursor});};source.onerror=function(error){emit(root,"stream-error",{error:error,cursor:cursor});};streams.set(key,source);return function(){source.close();streams.delete(key);};}
function queued(rootOrComponent,options){options=options||{};var root=typeof rootOrComponent==="string"?null:rootOrComponent,component=typeof rootOrComponent==="string"?rootOrComponent:componentOf(root,options),scope=scopeOf(root,options),key=scope&&component?offlinePrefix+scopeToken(scope)+":"+encodeURIComponent(component):null;return key?loadEnvelope(key,scope).items.map(function(item){return clone(item.transaction);}):[];}
function purge(options){options=options||{};var root=options.root||null,scope=scopeOf(root,options);if(!scope){return {ok:false,reason:"scope_required",removed:0};}var token=scopeToken(scope),prefixes=[offlinePrefix+token+":",cursorPrefix+token+":"],removed=0;[localStorage,sessionStorage].forEach(function(storage){try{for(var i=storage.length-1;i>=0;i--){var key=storage.key(i)||"";if(prefixes.some(function(prefix){return key.indexOf(prefix)===0;})){storage.removeItem(key);removed++;}}}catch(error){}});streams.forEach(function(source,key){if(key.indexOf(token+"|")===0){source.close();streams.delete(key);}});return {ok:true,removed:removed};}
window.addEventListener("online",function(){document.querySelectorAll("[data-dp-reactor-component]").forEach(function(root){drain(root).catch(function(){});});});
window.addEventListener("dataphyre:reactor-logout",function(event){purge(event.detail||{});});
window.DataphyreReactorTransactions={schemaVersion:SCHEMA,transaction:transaction,apply:apply,dispatch:dispatch,drain:drain,subscribe:subscribe,state:stateOf,version:versionOf,scope:scopeOf,purge:purge,cancel:function(root){var active=inflight.get(root);if(active){active.abort();}},queued:queued};
})(window,document);
JS;
	}
}
