<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Instance-owned service facade over Panel's production platform domains. */
final class PanelPlatform implements \JsonSerializable {
	/** @var array<string,mixed> */ private array $services=[];
	/** @var array<string,array{factory:\Closure,singleton:bool}> */ private array $factories=[];
	/** @var array<string,bool> */ private array $resolving=[];
	/** @var array<string,mixed> */ private array $metadata=[];
	private int $revision=0;
	/** @var array{operation:string,service:?string,revision:int} */
	private array $lastMutation=['operation'=>'initialized','service'=>null,'revision'=>0];

	/** @param array<string,mixed> $services */
	public function __construct(array $services=[]){foreach($services as$name=>$service){$this->register((string)$name,$service);}}
	/** @param array<string,mixed> $services */ public static function make(array $services=[]):self{return new self($services);}

	/** Builds filesystem-backed local defaults. Sensitive domains require explicit keys or must be disabled. @param array<string,mixed> $config */
	public static function defaults(array $config):self{
		$root=self::stateRoot($config['state_root']??null);$platform=new self();$enabled=[];
		$operations=self::domain($config,'operations');if($operations!==false){self::classes('operations',[PanelFilesystemOperationStore::class,PanelOperationHandlerRegistry::class,PanelLocalOperationQueue::class,PanelSynchronousOperationRunner::class,PanelOperationControl::class]);$store=new PanelFilesystemOperationStore($root.'/operations');$handlers=new PanelOperationHandlerRegistry();$queue=new PanelLocalOperationQueue($store);$runner=new PanelSynchronousOperationRunner($store,$handlers,$queue);$platform->register('operations.store',$store)->register('operations.handlers',$handlers)->register('operations.queue',$queue)->register('operations.runner',$runner)->register('operations.control',new PanelOperationControl($store));$enabled[]='operations';}
		$distributed=array_key_exists('distributed_operations',$config)?self::domain($config,'distributed_operations'):false;if($distributed!==false){self::classes('distributed_operations',[PanelAtomicSnapshotStore::class,PanelAtomicLeasedOperationStore::class,PanelOperationHandlerRegistry::class,PanelLeasedOperationRunner::class,PanelOperationControl::class]);$store=new PanelAtomicLeasedOperationStore($root.'/distributed-operations',(int)($distributed['snapshot_retention']??512));$handlers=new PanelOperationHandlerRegistry();$runner=new PanelLeasedOperationRunner($store,$handlers,(int)($distributed['lease_ttl_seconds']??60));$platform->register('distributed_operations.store',$store)->register('distributed_operations.handlers',$handlers)->register('distributed_operations.runner',$runner)->register('distributed_operations.control',new PanelOperationControl($store));$enabled[]='distributed_operations';}
		$migrations=array_key_exists('migrations',$config)?self::domain($config,'migrations'):false;if($migrations!==false){self::classes('migrations',[PanelAtomicSnapshotStore::class,PanelMigrationStore::class,PanelAtomicMigrationStore::class,PanelPdoMigrationStore::class,PanelMigrationRegistry::class,PanelMigrationRunner::class]);$store=$migrations['store']??new PanelAtomicMigrationStore($root.'/migrations',(int)($migrations['snapshot_retention']??512));if(!$store instanceof PanelMigrationStore){throw new \InvalidArgumentException('Panel platform migrations.store must implement PanelMigrationStore.');}$registry=new PanelMigrationRegistry();foreach(is_array($migrations['definitions']??null)?$migrations['definitions']:[]as$definition){if(!$definition instanceof PanelMigrationDefinition){throw new \InvalidArgumentException('Panel platform migration definitions must be PanelMigrationDefinition instances.');}$registry->register($definition);}$runner=new PanelMigrationRunner($store,$registry,is_callable($migrations['authorize']??null)?$migrations['authorize']:null);$platform->register('migrations.store',$store)->register('migrations.registry',$registry)->register('migrations.runner',$runner);$enabled[]='migrations';}
		$observability=array_key_exists('observability',$config)?self::domain($config,'observability'):false;if($observability!==false){self::classes('observability',[PanelTelemetryExporter::class,PanelTelemetryRuntime::class,PanelTelemetryHub::class,PanelTelemetryBridge::class]);$runtime=PanelTelemetryRuntime::fromConfig($observability);$platform->register('observability.runtime',$runtime)->register('observability.exporter',$runtime->exporter())->register('observability.hub',$runtime->hub())->register('observability.bridge',$runtime->bridge());$enabled[]='observability';}
		$data=self::domain($config,'data');if($data!==false){self::classes('data',[PanelDataSourceRegistry::class,PanelMutableDataSource::class,PanelDataMutation::class,PanelDataMutationReceipt::class,PanelDataMutationBatch::class,PanelDataMutationBatchResult::class,PanelDataMutationCapabilities::class]);$platform->register('data.registry',new PanelDataSourceRegistry());$enabled[]='data';}
		$workflows=self::domain($config,'workflows');if($workflows!==false){self::classes('workflows',[FilesystemWorkflowStore::class,WorkflowEngine::class]);$store=new FilesystemWorkflowStore($root.'/workflows');$engine=new WorkflowEngine($store,is_array($workflows['definitions']??null)?$workflows['definitions']:[]);$platform->register('workflows.store',$store)->register('workflows.engine',$engine);$enabled[]='workflows';}
		$automation=self::domain($config,'automation');if($automation!==false){self::classes('automation',[FilesystemAutomationStore::class,AutomationRegistry::class,AutomationExecutor::class]);$registry=new AutomationRegistry(is_array($automation['actions']??null)?$automation['actions']:[]);$store=new FilesystemAutomationStore($root.'/automation');$platform->register('automation.registry',$registry)->register('automation.store',$store)->register('automation.executor',new AutomationExecutor($registry,$store));$enabled[]='automation';}
		$authentication=self::domain($config,'authentication');if($authentication!==false){self::classes('authentication',[PanelFilesystemAuthenticationStore::class,PanelAuthenticationCipher::class,PanelLocalOneTimeChallengeAdapter::class,PanelAuthenticationManager::class]);$encryption=self::secret($authentication['encryption_key']??$config['authentication_encryption_key']??null,'authentication.encryption_key');$pepper=self::secret($authentication['pepper']??$config['authentication_pepper']??null,'authentication.pepper');$challengeKey=self::secret($authentication['challenge_key']??$pepper,'authentication.challenge_key');$store=new PanelFilesystemAuthenticationStore($root.'/authentication');$adapter=new PanelLocalOneTimeChallengeAdapter($challengeKey,(int)($authentication['challenge_digits']??6));$manager=new PanelAuthenticationManager($store,new PanelAuthenticationCipher($encryption),$adapter,$pepper);$platform->register('authentication.store',$store)->register('authentication.challenge_adapter',$adapter)->register('authentication.manager',$manager);$enabled[]='authentication';}
		$iam=array_key_exists('iam',$config)?self::domain($config,'iam'):false;if($iam!==false){self::classes('iam',[PanelIamStore::class,PanelAtomicIamStore::class,PanelIamManager::class,PanelIamManifest::class]);$configuredAuditKeys=$iam['audit_keys']??$config['iam_audit_keys']??$iam['audit_key']??$config['iam_audit_key']??null;$auditKeys=is_array($configuredAuditKeys)?$configuredAuditKeys:self::secret($configuredAuditKeys,'iam.audit_key');$store=new PanelAtomicIamStore($root.'/iam',(int)($iam['snapshot_retention']??512));$manager=new PanelIamManager($store,$auditKeys,is_callable($iam['authorize']??null)?$iam['authorize']:null,$iam);$platform->register('iam.store',$store)->register('iam.manager',$manager);$enabled[]='iam';}
		$studio=array_key_exists('studio',$config)?self::domain($config,'studio'):false;if($studio!==false){
			self::classes('studio',[PanelStudioStore::class,PanelFilesystemStudioStore::class,PanelStudioManager::class,PanelStudioCompiler::class,PanelStudioSchemaRegistry::class,PanelStudioMaterializer::class,PanelStudioPolicy::class,PanelStudioPreviewSigner::class,PanelStudioEditor::class,PanelStudioEditorSession::class,PanelStudioEditorCommand::class,PanelStudioEditorOptions::class,PanelStudioEditorRenderer::class,PanelStudioEditorAssets::class,PanelStudioCollaborationIntent::class,PanelStudioCollaborationIntentVerification::class,PanelStudioCollaborationIntentSigner::class,PanelStudioCollaborationTransport::class,PanelStudioCollaborationEndpoint::class,PanelStudioCollaborationEndpointResult::class,PanelStudioCollaborationTransportException::class,PanelStudioVisualRuntime::class,PanelStudioVisualDataset::class,PanelStudioVisualPreview::class,PanelStudioVisualSurface::class]);
			$store=$studio['store']??new PanelFilesystemStudioStore($root.'/studio',(int)($studio['snapshot_retention']??512));if(!$store instanceof PanelStudioStore){throw new \InvalidArgumentException('Panel platform studio.store must implement PanelStudioStore.');}
			$authorization=$studio['authorization']??$studio['authorize']??null;if($authorization===null){$authorization=PanelStudioPolicy::denyAll();}elseif(is_callable($authorization)){$authorization=PanelStudioPolicy::permit($authorization,'platform_host');}elseif(!$authorization instanceof PanelStudioAuthorization){throw new \InvalidArgumentException('Panel platform studio authorization must implement PanelStudioAuthorization or be callable.');}
			$compiler=$studio['compiler']??new PanelStudioCompiler();if(!$compiler instanceof PanelStudioCompiler){throw new \InvalidArgumentException('Panel platform studio.compiler must be a PanelStudioCompiler.');}
			$registry=$studio['registry']??null;if($registry===null){$registryVersion=$studio['registry_version']??'1.0.0';if(!is_string($registryVersion)){throw new \InvalidArgumentException('Panel platform studio.registry_version must be a safe string.');}$registry=PanelStudioSchemaRegistry::defaults($registryVersion);}if(!$registry instanceof PanelStudioSchemaRegistry){throw new \InvalidArgumentException('Panel platform studio.registry must be a PanelStudioSchemaRegistry.');}$extensions=$studio['schemas']??[];if(!is_array($extensions)||($extensions!==[]&&!array_is_list($extensions))){throw new \InvalidArgumentException('Panel platform studio.schemas must be a list of typed component schemas.');}foreach($extensions as$extension){if($extension instanceof PanelStudioComponentSchema){$registry=$registry->withSchema($extension);continue;}if(!is_array($extension)||!($extension['schema']??null)instanceof PanelStudioComponentSchema){throw new \InvalidArgumentException('Panel platform studio.schemas entries must contain typed component schemas.');}$provider=$extension['provider']??'host';$providerVersion=$extension['provider_version']??'1.0.0';$conflict=$extension['conflict']??'reject';if(!is_string($provider)||!is_string($providerVersion)||!is_string($conflict)){throw new \InvalidArgumentException('Panel platform studio schema provenance and conflict metadata must be strings.');}$registry=$registry->withSchema($extension['schema'],$provider,$providerVersion,$conflict);}
			$materializer=$studio['materializer']??new PanelStudioMaterializer();if(!$materializer instanceof PanelStudioMaterializer){throw new \InvalidArgumentException('Panel platform studio.materializer must be a PanelStudioMaterializer.');}
			$signer=$studio['preview_signer']??null;if($signer!==null&&!$signer instanceof PanelStudioPreviewSigner){throw new \InvalidArgumentException('Panel platform studio.preview_signer must be a PanelStudioPreviewSigner.');}
			$keys=$studio['preview_keys']??$config['studio_preview_keys']??null;if($signer===null&&$keys!==null){if(!is_array($keys)){throw new \InvalidArgumentException('Panel platform studio.preview_keys must be a private key map.');}$signer=new PanelStudioPreviewSigner($keys,(string)($studio['current_preview_key']??$config['studio_current_preview_key']??''),is_callable($studio['preview_clock']??null)?$studio['preview_clock']:null,is_callable($studio['nonce_factory']??null)?$studio['nonce_factory']:null);}
			$visual=$studio['visual_runtime']??false;if($visual===true){$visual=new PanelStudioVisualRuntime();}elseif($visual===false||$visual===null){$visual=null;}elseif(!$visual instanceof PanelStudioVisualRuntime){throw new \InvalidArgumentException('Panel platform studio.visual_runtime must be true, false, or a PanelStudioVisualRuntime.');}
			$manager=new PanelStudioManager($store,$authorization,$compiler,$signer,(int)($studio['required_publish_approvals']??0),is_callable($studio['clock']??null)?$studio['clock']:null,$registry,$materializer,$visual);$platform->register('studio.store',$store)->register('studio.compiler',$compiler)->register('studio.registry',$registry)->register('studio.materializer',$materializer)->register('studio.manager',$manager);if($visual instanceof PanelStudioVisualRuntime){$platform->register('studio.visual_runtime',$visual);}$enabled[]='studio';
		}
		$notifications=self::domain($config,'notifications');if($notifications!==false){self::classes('notifications',[PanelFilesystemNotificationAdapter::class,PanelNotificationActivityStore::class]);$adapter=new PanelFilesystemNotificationAdapter($root.'/notifications/inbox',[],is_array($notifications['channels']??null)?$notifications['channels']:['database'],is_array($notifications['handlers']??null)?$notifications['handlers']:[],(int)($notifications['snapshot_retention']??512),(int)($notifications['delivery_retention']??5000));$activity=new PanelNotificationActivityStore($root.'/notifications/activity',(int)($notifications['snapshot_retention']??512),(int)($notifications['activity_retention']??25000));$platform->register('notifications.adapter',$adapter)->register('notifications.activity',$activity);$enabled[]='notifications';}
		$media=self::domain($config,'media');if($media!==false){self::classes('media',[PanelMediaManager::class]);$signing=self::secret($media['signing_key']??$config['media_signing_key']??null,'media.signing_key');$manager=PanelMediaManager::local($root.'/media',$signing,$media);$platform->register('media.manager',$manager);$enabled[]='media';}
		$localization=self::domain($config,'localization');if($localization!==false){self::classes('localization',[PanelTranslationCatalogueLoader::class,PanelLocalizationRuntime::class]);$loader=new PanelTranslationCatalogueLoader(($localization['strict']??true)!==false);foreach(is_array($localization['sources']??null)?$localization['sources']:[]as$source){if(is_string($source)){$loader->addPath($source);continue;}if(is_array($source)){$loader->addPath((string)($source['path']??''),(string)($source['namespace']??''),(int)($source['priority']??0),($source['trusted_php']??false)===true);}}$runtime=new PanelLocalizationRuntime($loader,(string)($localization['locale']??'en'),isset($localization['fallback'])?(string)$localization['fallback']:'en',(string)($localization['timezone']??'UTC'));$platform->register('localization.loader',$loader)->register('localization.runtime',$runtime);$enabled[]='localization';}
		$preferences=self::domain($config,'preferences');if($preferences!==false){self::classes('preferences',[PanelFilesystemPreferenceStore::class,PanelWorkspacePreferences::class,PanelWorkspacePreferencesFactory::class]);$store=new PanelFilesystemPreferenceStore($root.'/preferences',(int)($preferences['snapshot_retention']??512),(int)($preferences['version_retention']??100));$platform->register('preferences.store',$store)->register('preferences.workspace_factory',new PanelWorkspacePreferencesFactory($store));$enabled[]='preferences';}
		$collaboration=self::domain($config,'collaboration');if($collaboration!==false){self::classes('collaboration',[PanelCollaborationStore::class,PanelFilesystemCollaborationStore::class,PanelPdoCollaborationStore::class,PanelCollaborationStorageException::class,PanelCollaborationManager::class]);$store=$collaboration['store']??new PanelFilesystemCollaborationStore($root.'/collaboration',(int)($collaboration['snapshot_retention']??512));if(!$store instanceof PanelCollaborationStore){throw new \InvalidArgumentException('Panel platform collaboration.store must implement PanelCollaborationStore.');}$manager=new PanelCollaborationManager($store,is_callable($collaboration['policy']??null)?$collaboration['policy']:null);$platform->register('collaboration.store',$store)->register('collaboration.manager',$manager);$enabled[]='collaboration';}
		$packages=array_key_exists('packages',$config)?self::domain($config,'packages'):false;if($packages!==false){self::classes('packages',[PanelFilesystemPackageRegistry::class,PanelPackageRegistryPublisher::class,PanelPackageRegistryCatalog::class,PanelPackageTransport::class]);$registry=$packages['registry']??new PanelFilesystemPackageRegistry($root.'/package-registry',(string)($packages['registry_id']??'panel_packages'),(string)($packages['publisher']??'host'),(int)($packages['snapshot_retention']??256));if(!$registry instanceof PanelFilesystemPackageRegistry){throw new \InvalidArgumentException('Panel platform packages.registry must be a PanelFilesystemPackageRegistry.');}$platform->register('packages.registry',$registry)->register('packages.transport',$registry);$enabled[]='packages';}
		$relations=self::domain($config,'relations');if($relations!==false){self::classes('relations',[PanelArrayRelationAdapter::class,PanelRelationWorkspace::class]);$platform->register('relations.adapter_factory',static fn(array $records=[],array $links=[]):PanelArrayRelationAdapter=>new PanelArrayRelationAdapter($records,$links))->register('relations.workspace_factory',static fn(string $name,string|int $parent,PanelRelationAdapter $adapter):PanelRelationWorkspace=>PanelRelationWorkspace::make($name,$parent,$adapter));$enabled[]='relations';}
		$security=self::domain($config,'security');if($security!==false){self::classes('security',[PanelSecurityAuditTrail::class,PanelSecurityContext::class,PanelSecurityPolicy::class]);$auditKey=array_key_exists('audit_key',$security)?self::secret($security['audit_key'],'security.audit_key'):null;$platform->register('security.audit',new PanelSecurityAuditTrail($root.'/security/audit.json',$auditKey))->register('security.context_factory',static fn(string|int $actor,array $options=[]):PanelSecurityContext=>PanelSecurityContext::make($actor,$options))->register('security.policy_factory',static fn(string $ability):PanelSecurityPolicy=>PanelSecurityPolicy::make($ability));$enabled[]='security';}
		$development=self::domain($config,'development');if($development!==false){self::classes('development',[PanelDeveloperToolkit::class]);$platform->register('development.toolkit',new PanelDeveloperToolkit());$enabled[]='development';}
		$extensions=self::domain($config,'extensions');if($extensions!==false){self::classes('extensions',[PanelExtensionRegistry::class,PanelExtensionRuntime::class]);$registry=new PanelExtensionRegistry();foreach(is_array($extensions['items']??null)?$extensions['items']:[]as$extension){$registry=$registry->register($extension);}$platform->register('extensions.registry',$registry)->register('extensions.runtime',new PanelExtensionRuntime());$enabled[]='extensions';}
		$operationsOs=array_key_exists('operations_os',$config)?self::domain($config,'operations_os'):false;
		if($operationsOs!==false){
			self::classes('operations_os',[PanelOperationsOs::class,PanelOperationsConsole::class,PanelOperationsOsFabricHandler::class,PanelDomainCompiler::class,PanelDomainActivationRuntime::class,PanelDomainRuntimeHost::class,PanelDomainMaterializer::class,PanelFilesystemDomainActivationStore::class,PanelCommandFabric::class,PanelCommandRegistry::class,PanelFilesystemCommandFabricStore::class,PanelLeasedCommandFabricStore::class,PanelPdoCommandFabricStore::class,PanelCommandFabricSubscriberLease::class,PanelCommandFabricStorageException::class,PanelCommandFabricLeaseLost::class,PanelEncryptedCommandPayloadCodec::class,PanelAttestedCommandObligationVerifier::class,PanelCommandApprovalAttestation::class,PanelClosedLoopIntelligence::class,PanelIntelligenceSignal::class,PanelIntelligenceProposal::class,PanelIntelligenceApproval::class,PanelIntelligenceFeedback::class,PanelReleaseExecutionEngine::class,PanelReleaseDeploymentAdapter::class,PanelCallbackReleaseDeploymentAdapter::class,PanelReleaseExecutionInterrupted::class,PanelFederationMessage::class,PanelFederationGateway::class,PanelFederationTransport::class,PanelCallbackFederationTransport::class,PanelWorkflowFabricHandler::class,PanelAutomationFabricHandler::class,PanelOperationFabricHandler::class,PanelIamFabricHandler::class,PanelAgentFabricHandler::class,PanelTenantFabricHandler::class,PanelTenantFabricRequestResolver::class,PanelNotificationFabricProjector::class,PanelComplianceFabricProjector::class,PanelWorkGraph::class,PanelPolicyControlPlane::class,PanelOperatorRuntime::class,PanelSemanticCatalog::class,PanelLineageGraph::class,PanelProcessIntelligence::class,PanelCounterfactualLab::class,PanelComplianceLedger::class,PanelComplianceAutomation::class,PanelComplianceCollector::class,PanelComplianceCollectorRegistry::class,PanelComplianceFrameworkCatalog::class,PanelComplianceFrameworkPack::class,PanelComplianceCollectionPlan::class,PanelComplianceCollectionRun::class,PanelComplianceCoverageReport::class,PanelFederationControlPlane::class,PanelReleaseControlPlane::class,PanelMarketplaceGovernance::class,PanelStudioBranchManager::class,PanelLocalReplica::class]);
			self::classes('operations_os',[PanelReleaseDeploymentTransport::class,PanelCallbackReleaseDeploymentTransport::class,PanelReleaseDeploymentProfile::class,PanelDeclarativeReleaseDeploymentAdapter::class]);
			$operationsOs['master_key']=self::secret($operationsOs['master_key']??$config['operations_os_master_key']??null,'operations_os.master_key');
			if($platform->has('workflows.engine')){$operationsOs['workflow_engine']=$platform->get('workflows.engine');}
			if($platform->has('automation.registry')){$operationsOs['automation_registry']=$platform->get('automation.registry');}
			if($platform->has('automation.executor')){$operationsOs['automation_executor']=$platform->get('automation.executor');}
			if($platform->has('operations.runner')){$operationsOs['operation_runner']=$platform->get('operations.runner');}
			elseif($platform->has('distributed_operations.runner')){$operationsOs['operation_runner']=$platform->get('distributed_operations.runner');}
			if($platform->has('realtime.broker')&&$platform->get('realtime.broker') instanceof PanelRealtimePublisher){$operationsOs['realtime_publisher']=$platform->get('realtime.broker');}
			if($platform->has('agents.catalog')){$operationsOs['agent_tool_catalog']=$platform->get('agents.catalog');}
			if($platform->has('agents.runtime')){$operationsOs['agent_runtime']=$platform->get('agents.runtime');}
			if($platform->has('iam.manager')){$operationsOs['iam_manager']=$platform->get('iam.manager');}
			if($platform->has('notifications.adapter')){$operationsOs['notification_adapter']=$platform->get('notifications.adapter');}
			$runtime=PanelOperationsOs::fromConfig($root.'/operations-os',$operationsOs);
			$platform->register('operations_os.runtime',$runtime)
				->register('operations_os.domain_compiler',$runtime->domainCompiler())
				->register('operations_os.activation',$runtime->activation())
				->register('operations_os.command_fabric',$runtime->commandFabric())
				->register('operations_os.intelligence',$runtime->intelligence())
				->register('operations_os.work_graph',$runtime->workGraph())
				->register('operations_os.policy',$runtime->policy())
				->register('operations_os.operator',$runtime->operator())
				->register('operations_os.semantics',$runtime->semantics())
				->register('operations_os.lineage',$runtime->lineage())
				->register('operations_os.process_intelligence',$runtime->processIntelligence())
				->register('operations_os.counterfactuals',$runtime->counterfactuals())
				->register('operations_os.compliance',$runtime->compliance())
				->register('operations_os.compliance_automation',$runtime->complianceAutomation())
				->register('operations_os.federation',$runtime->federation())
				->register('operations_os.federation_gateway',$runtime->federationGateway())
				->register('operations_os.releases',$runtime->releases())
				->register('operations_os.release_execution',$runtime->releaseExecution())
					->register('operations_os.marketplace',$runtime->marketplace())
					->register('operations_os.studio_branches',$runtime->studioBranches())
					->register('operations_os.console',new PanelOperationsConsole($runtime,(int)($operationsOs['console_maximum_limit']??PanelOperationsConsole::MAX_LIMIT)))
					->register('operations_os.local_replica_factory',static fn(string|int $actorId):PanelLocalReplica=>$runtime->replica($actorId));
			if($runtime->hasMarketplaceTrustNetwork()){$platform->register('operations_os.marketplace_trust_network',$runtime->marketplaceTrustNetwork())->register('operations_os.marketplace_revocations',$runtime->marketplace()->revocationRegistry())->register('operations_os.marketplace_publishers',$runtime->marketplace()->publisherTrustRegistry());}
			$enabled[]='operations_os';
		}
		$ui=self::domain($config,'platform');if($ui!==false){self::classes('platform',[PanelPlatformController::class,PanelPlatformTemplate::class]);$controller=new PanelPlatformController();if($security!==false){$contextResolver=is_callable($security['context_resolver']??null)?$security['context_resolver']:null;$policyResolver=is_callable($security['policy_resolver']??null)?$security['policy_resolver']:null;$controller=$controller->securityBoundary($platform->securityAudit(),$contextResolver,$policyResolver);}if(is_callable($ui['authorize']??null)){$controller=$controller->authorize($ui['authorize']);}if(is_callable($ui['csrf']??null)){$controller=$controller->csrf($ui['csrf']);}$platform->register('platform.controller',$controller)->register('platform.template',PanelPlatformTemplate::class);$enabled[]='platform';}
		$platform->metadata=['state_root'=>$root,'defaults'=>true,'enabled_domains'=>$enabled];return$platform;
	}

	public function register(string $name,mixed $service,bool $replace=false):self{$name=self::serviceName($name);if(!$replace&&$this->has($name)){throw new \LogicException("Panel platform service '{$name}' is already registered.");}$this->services[$name]=$service;unset($this->factories[$name]);$this->mutated($replace?'service.replaced':'service.registered',$name);return$this;}
	public function factory(string $name,callable $factory,bool $singleton=true,bool $replace=false):self{$name=self::serviceName($name);if(!$replace&&$this->has($name)){throw new \LogicException("Panel platform service '{$name}' is already registered.");}$this->factories[$name]=['factory'=>\Closure::fromCallable($factory),'singleton'=>$singleton];unset($this->services[$name]);$this->mutated($replace?'factory.replaced':'factory.registered',$name);return$this;}
	public function forget(string $name):self{$name=self::serviceName($name);$present=$this->has($name);unset($this->services[$name],$this->factories[$name],$this->resolving[$name]);if($present){$this->mutated('service.forgotten',$name);}return$this;}
	public function has(string $name):bool{$name=self::serviceName($name);return array_key_exists($name,$this->services)||isset($this->factories[$name]);}
	public function get(string $name):mixed{$name=self::serviceName($name);if(array_key_exists($name,$this->services)){return$this->services[$name];}$definition=$this->factories[$name]??null;if($definition===null){throw new \OutOfBoundsException("Panel platform service '{$name}' is not registered.");}if(isset($this->resolving[$name])){throw new \LogicException("Circular Panel platform service resolution at '{$name}'.");}$this->resolving[$name]=true;try{$value=($definition['factory'])($this,$name);if($definition['singleton']){$this->services[$name]=$value;unset($this->factories[$name]);$this->mutated('factory.resolved',$name);}return$value;}finally{unset($this->resolving[$name]);}}
	public function optional(string $name,mixed $default=null):mixed{return$this->has($name)?$this->get($name):$default;}
	public function service(string $name,string $expectedClass):object{$value=$this->has($name)?$this->get($name):null;if($value===null){throw new \LogicException("Panel platform service '{$name}' is not configured.");}if(!is_a($value,$expectedClass)){throw new \UnexpectedValueException("Panel platform service '{$name}' must implement {$expectedClass}; received ".get_debug_type($value).'.');}return$value;}

	/**
	 * Captures an internal plugin-boot rollback unit. Service values are never
	 * serialized publicly; mutable first-party registries contribute their own
	 * exact nested checkpoints so restoring the container is not a shallow lie.
	 *
	 * @return array<string,mixed>
	 */
	public function checkpoint():array{
		$nested=[];
		foreach($this->services as$name=>$service){if($service instanceof PanelCheckpointableService){$nested[$name]=['type'=>$service->checkpointType(),'class'=>$service::class,'checkpoint'=>$service->checkpoint()];}}
		return['services'=>$this->services,'factories'=>$this->factories,'metadata'=>$this->metadata,'revision'=>$this->revision,'last_mutation'=>$this->lastMutation,'nested'=>$nested];
	}

	/** Restores a trusted in-process checkpoint created by {@see checkpoint()}. @param array<string,mixed> $checkpoint */
	public function restore(array $checkpoint):self{
		if(array_keys($checkpoint)!==['services','factories','metadata','revision','last_mutation','nested']||!is_array($checkpoint['services'])||!is_array($checkpoint['factories'])||!is_array($checkpoint['metadata'])||!is_int($checkpoint['revision'])||$checkpoint['revision']<0||!is_array($checkpoint['last_mutation'])||!is_array($checkpoint['nested'])){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}
		if(count($checkpoint['services'])>1024||count($checkpoint['factories'])>1024||array_intersect_key($checkpoint['services'],$checkpoint['factories'])!==[]){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}
		foreach($checkpoint['services']as$name=>$service){if(!is_string($name)||self::serviceName($name)!==$name){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}}
		foreach($checkpoint['factories']as$name=>$definition){if(!is_string($name)||self::serviceName($name)!==$name||!is_array($definition)||array_keys($definition)!==['factory','singleton']||!($definition['factory']??null)instanceof \Closure||!is_bool($definition['singleton']??null)){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}}
		$mutation=$checkpoint['last_mutation'];if(array_keys($mutation)!==['operation','service','revision']||!is_string($mutation['operation']??null)||trim($mutation['operation'])===''||strlen($mutation['operation'])>128||(!is_null($mutation['service']??null)&&!is_string($mutation['service']))||!is_int($mutation['revision']??null)||$mutation['revision']<0||$mutation['revision']>$checkpoint['revision']){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}
		if(is_string($mutation['service'])&&self::serviceName($mutation['service'])!==$mutation['service']){throw new \InvalidArgumentException('Invalid Panel platform checkpoint.');}
		$expectedNested=[];foreach($checkpoint['services']as$name=>$service){if($service instanceof PanelCheckpointableService){$expectedNested[]=$name;}}$actualNested=array_keys($checkpoint['nested']);sort($expectedNested,SORT_STRING);sort($actualNested,SORT_STRING);if($expectedNested!==$actualNested){throw new \InvalidArgumentException('Invalid nested Panel platform checkpoint.');}
		$nestedRestores=[];
		foreach($checkpoint['nested']as$name=>$nested){
			$service=$checkpoint['services'][$name]??null;
			if(!is_array($nested)||array_keys($nested)!==['type','class','checkpoint']||!is_string($nested['type']??null)||!is_string($nested['class']??null)||!is_array($nested['checkpoint']??null)||!$service instanceof PanelCheckpointableService||$service::class!==$nested['class']||$service->checkpointType()!==$nested['type']){throw new \InvalidArgumentException('Invalid nested Panel platform checkpoint.');}
			try{$probe=clone$service;$probe->restore($nested['checkpoint']);}catch(\Throwable $error){throw new \InvalidArgumentException('Invalid nested Panel platform checkpoint.',0,$error);}$nestedRestores[$name]=$nested['checkpoint'];
		}
		$this->services=$checkpoint['services'];$this->factories=$checkpoint['factories'];$this->metadata=$checkpoint['metadata'];$this->revision=$checkpoint['revision'];$this->lastMutation=$checkpoint['last_mutation'];$this->resolving=[];
		foreach($nestedRestores as$name=>$nested){$this->services[$name]->restore($nested);}
		return$this;
	}

	public function operationStore():PanelOperationStore{return $this->service('operations.store',PanelOperationStore::class);}
	public function operationHandlers():PanelOperationHandlerRegistry{return $this->service('operations.handlers',PanelOperationHandlerRegistry::class);}
	public function operationQueue():PanelOperationQueue{return $this->service('operations.queue',PanelOperationQueue::class);}
	public function operationRunner():PanelOperationRunner{return $this->service('operations.runner',PanelOperationRunner::class);}
	public function operationControl():PanelOperationControl{return $this->service('operations.control',PanelOperationControl::class);}
	public function distributedOperationStore():PanelLeasedOperationStore{return $this->service('distributed_operations.store',PanelLeasedOperationStore::class);}
	public function distributedOperationHandlers():PanelOperationHandlerRegistry{return $this->service('distributed_operations.handlers',PanelOperationHandlerRegistry::class);}
	public function distributedOperationRunner():PanelLeasedOperationRunner{return $this->service('distributed_operations.runner',PanelLeasedOperationRunner::class);}
	public function distributedOperationControl():PanelOperationControl{return $this->service('distributed_operations.control',PanelOperationControl::class);}
	public function migrationStore():PanelMigrationStore{return $this->service('migrations.store',PanelMigrationStore::class);}
	public function migrationRegistry():PanelMigrationRegistry{return $this->service('migrations.registry',PanelMigrationRegistry::class);}
	public function migrationRunner():PanelMigrationRunner{return $this->service('migrations.runner',PanelMigrationRunner::class);}
	public function observability():PanelTelemetryRuntime{return $this->service('observability.runtime',PanelTelemetryRuntime::class);}
	public function telemetryExporter():PanelTelemetryExporter{return $this->service('observability.exporter',PanelTelemetryExporter::class);}
	public function telemetry():PanelTelemetryHub{return $this->service('observability.hub',PanelTelemetryHub::class);}
	public function telemetryBridge():PanelTelemetryBridge{return $this->service('observability.bridge',PanelTelemetryBridge::class);}
	public function dataSources():PanelDataSourceRegistry{return $this->service('data.registry',PanelDataSourceRegistry::class);}
	public function dataSurfaces():PanelDataSurfaceRegistry{return $this->service('data_surfaces.registry',PanelDataSurfaceRegistry::class);}
	public function realtimeBroker():PanelRealtimeBroker{return $this->service('realtime.broker',PanelRealtimeBroker::class);}
	public function realtimeSigner():PanelRealtimeIntentSigner{return $this->service('realtime.signer',PanelRealtimeIntentSigner::class);}
	public function realtime():PanelRealtimeEndpoint{return $this->service('realtime.endpoint',PanelRealtimeEndpoint::class);}
	public function workflowStore():WorkflowStore{return $this->service('workflows.store',WorkflowStore::class);}
	public function workflowEngine():WorkflowEngine{return $this->service('workflows.engine',WorkflowEngine::class);}
	public function automationRegistry():AutomationRegistry{return $this->service('automation.registry',AutomationRegistry::class);}
	public function automationStore():AutomationStore{return $this->service('automation.store',AutomationStore::class);}
	public function automationExecutor():AutomationExecutor{return $this->service('automation.executor',AutomationExecutor::class);}
	public function agentTools():PanelAgentToolCatalog{return $this->service('agents.catalog',PanelAgentToolCatalog::class);}
	public function agentPolicy():PanelAgentPolicyEngine{return $this->service('agents.policy',PanelAgentPolicyEngine::class);}
	public function agentSigner():PanelAgentIntentSigner{return $this->service('agents.signer',PanelAgentIntentSigner::class);}
	public function agentStore():PanelAgentWorkflowStore{return $this->service('agents.store',PanelAgentWorkflowStore::class);}
	public function agents():PanelAgentRuntime{return $this->service('agents.runtime',PanelAgentRuntime::class);}
	public function authenticationStore():PanelAuthenticationStore{return$this->service('authentication.store',PanelAuthenticationStore::class);}
	public function authenticationChallengeAdapter():PanelOneTimeChallengeAdapter{return$this->service('authentication.challenge_adapter',PanelOneTimeChallengeAdapter::class);}
	public function authentication():PanelAuthenticationManager{return $this->service('authentication.manager',PanelAuthenticationManager::class);}
	public function iamStore():PanelIamStore{return $this->service('iam.store',PanelIamStore::class);}
	public function iam():PanelIamManager{return $this->service('iam.manager',PanelIamManager::class);}
	public function studioStore():PanelStudioStore{return $this->service('studio.store',PanelStudioStore::class);}
	public function studioCompiler():PanelStudioCompiler{return $this->service('studio.compiler',PanelStudioCompiler::class);}
	public function studioRegistry():PanelStudioSchemaRegistry{return $this->service('studio.registry',PanelStudioSchemaRegistry::class);}
	public function studioMaterializer():PanelStudioMaterializer{return $this->service('studio.materializer',PanelStudioMaterializer::class);}
	public function studio():PanelStudioManager{return $this->service('studio.manager',PanelStudioManager::class);}
	public function studioVisualRuntime():PanelStudioVisualRuntime{return $this->service('studio.visual_runtime',PanelStudioVisualRuntime::class);}
	public function openStudioEditor(PanelStudioDocument $document,string $principalId,?PanelStudioDefinition $initial=null):PanelStudioEditorSession{return PanelStudioEditor::open($this->studio(),$document,$principalId,$initial);}
	/** @param array<string,mixed> $checkpoint */ public function resumeStudioEditor(PanelStudioDocument $document,string $principalId,array $checkpoint):PanelStudioEditorSession{return PanelStudioEditor::resume($this->studio(),$document,$principalId,$checkpoint);}
	public function renderStudioEditor(PanelStudioEditorSession $session,PanelStudioEditorOptions $options):string{return PanelStudioEditor::render($session,$options);}
	public function renderStudioVisualPreview(PanelStudioEditorSession $session,?PanelStudioVisualDataset $dataset=null,?PanelRequest $request=null):PanelStudioVisualPreview{return PanelStudioEditor::visualPreview($session,$dataset,$request);}
	public function notificationAdapter():PanelNotificationAdapter{return $this->service('notifications.adapter',PanelNotificationAdapter::class);}
	public function notificationActivity():PanelNotificationActivityStore{return $this->service('notifications.activity',PanelNotificationActivityStore::class);}
	public function media():PanelMediaManager{return $this->service('media.manager',PanelMediaManager::class);}
	public function localizationLoader():PanelTranslationCatalogueLoader{return$this->service('localization.loader',PanelTranslationCatalogueLoader::class);}
	public function localization():PanelLocalizationRuntime{return $this->service('localization.runtime',PanelLocalizationRuntime::class);}
	public function preferenceStore():PanelPreferenceStore{return $this->service('preferences.store',PanelPreferenceStore::class);}
	public function preferenceFactory():PanelWorkspacePreferencesFactory{return$this->service('preferences.workspace_factory',PanelWorkspacePreferencesFactory::class);}
	public function preferences(string $userId,string $profile='default',?string $device=null):PanelWorkspacePreferences{return($this->preferenceFactory())($userId,$profile,$device);}
	public function collaborationStore():PanelCollaborationStore{return $this->service('collaboration.store',PanelCollaborationStore::class);}
	public function collaboration():PanelCollaborationManager{return $this->service('collaboration.manager',PanelCollaborationManager::class);}
	public function packageRegistry():PanelFilesystemPackageRegistry{return $this->service('packages.registry',PanelFilesystemPackageRegistry::class);}
	public function packageTransport():PanelPackageTransport{return $this->service('packages.transport',PanelPackageTransport::class);}
	public function packageCatalog():PanelPackageRegistryCatalog{return $this->packageRegistry()->catalog();}
	public function securityAudit():PanelSecurityAuditTrail{return $this->service('security.audit',PanelSecurityAuditTrail::class);}
	public function development():PanelDeveloperToolkit{return $this->service('development.toolkit',PanelDeveloperToolkit::class);}
	public function extensions():PanelExtensionRegistry{return $this->service('extensions.registry',PanelExtensionRegistry::class);}
	public function extensionRuntime():PanelExtensionRuntime{return $this->service('extensions.runtime',PanelExtensionRuntime::class);}
	public function operationsOs():PanelOperationsOs{return$this->service('operations_os.runtime',PanelOperationsOs::class);}
	public function operationsConsole():PanelOperationsConsole{return$this->service('operations_os.console',PanelOperationsConsole::class);}
	public function operationsDomainCompiler():PanelDomainCompiler{return$this->service('operations_os.domain_compiler',PanelDomainCompiler::class);}
	public function domainActivation():PanelDomainActivationRuntime{return$this->service('operations_os.activation',PanelDomainActivationRuntime::class);}
	public function commandFabric():PanelCommandFabric{return$this->service('operations_os.command_fabric',PanelCommandFabric::class);}
	public function closedLoopIntelligence():PanelClosedLoopIntelligence{return$this->service('operations_os.intelligence',PanelClosedLoopIntelligence::class);}
	public function workGraph():PanelWorkGraph{return$this->service('operations_os.work_graph',PanelWorkGraph::class);}
	public function policyControlPlane():PanelPolicyControlPlane{return$this->service('operations_os.policy',PanelPolicyControlPlane::class);}
	public function operatorRuntime():PanelOperatorRuntime{return$this->service('operations_os.operator',PanelOperatorRuntime::class);}
	public function semanticCatalog():PanelSemanticCatalog{return$this->service('operations_os.semantics',PanelSemanticCatalog::class);}
	public function lineageGraph():PanelLineageGraph{return$this->service('operations_os.lineage',PanelLineageGraph::class);}
	public function processIntelligence():PanelProcessIntelligence{return$this->service('operations_os.process_intelligence',PanelProcessIntelligence::class);}
	public function counterfactualLab():PanelCounterfactualLab{return$this->service('operations_os.counterfactuals',PanelCounterfactualLab::class);}
	public function complianceLedger():PanelComplianceLedger{return$this->service('operations_os.compliance',PanelComplianceLedger::class);}
	public function complianceAutomation():PanelComplianceAutomation{return$this->service('operations_os.compliance_automation',PanelComplianceAutomation::class);}
	public function federationControlPlane():PanelFederationControlPlane{return$this->service('operations_os.federation',PanelFederationControlPlane::class);}
	public function federationGateway():PanelFederationGateway{return$this->service('operations_os.federation_gateway',PanelFederationGateway::class);}
	public function releaseControlPlane():PanelReleaseControlPlane{return$this->service('operations_os.releases',PanelReleaseControlPlane::class);}
	public function releaseExecution():PanelReleaseExecutionEngine{return$this->service('operations_os.release_execution',PanelReleaseExecutionEngine::class);}
	public function marketplaceGovernance():PanelMarketplaceGovernance{return$this->service('operations_os.marketplace',PanelMarketplaceGovernance::class);}
	public function marketplaceTrustNetwork():PanelPackageMarketplaceTrustNetwork{return$this->service('operations_os.marketplace_trust_network',PanelPackageMarketplaceTrustNetwork::class);}
	public function marketplaceRevocations():PanelPackageRevocationRegistry{return$this->service('operations_os.marketplace_revocations',PanelPackageRevocationRegistry::class);}
	public function marketplacePublishers():PanelPackagePublisherTrustRegistry{return$this->service('operations_os.marketplace_publishers',PanelPackagePublisherTrustRegistry::class);}
	public function studioBranches():PanelStudioBranchManager{return$this->service('operations_os.studio_branches',PanelStudioBranchManager::class);}
	public function localReplica(string|int $actorId):PanelLocalReplica {$factory=$this->optional('operations_os.local_replica_factory');if(!is_callable($factory)){throw new \LogicException('Panel Operations OS local replica factory is not configured.');}$replica=$factory($actorId);if(!$replica instanceof PanelLocalReplica){throw new \UnexpectedValueException('Panel Operations OS local replica factory returned an invalid replica.');}return$replica;}
	public function controller():PanelPlatformController{return $this->service('platform.controller',PanelPlatformController::class);}
	public function templateClass():string{$value=$this->optional('platform.template');if(!is_string($value)||!is_a($value,PanelPlatformTemplate::class,true)){throw new \LogicException('Panel platform template is not configured.');}return$value;}

	public function registerOperationHandler(string $type,callable $handler,bool $replace=false):self{$this->assertReadyDomain('operations');$this->operationHandlers()->register($type,$handler,$replace);$this->mutated('service.contributed','operations.handlers');return$this;}
	public function registerDistributedOperationHandler(string $type,callable $handler,bool $replace=false):self{$this->assertReadyDomain('distributed_operations');$this->distributedOperationHandlers()->register($type,$handler,$replace);$this->mutated('service.contributed','distributed_operations.handlers');return$this;}
	public function registerMigration(PanelMigrationDefinition $definition,bool $replace=false):self{$this->assertReadyDomain('migrations');$this->migrationRegistry()->register($definition,$replace);$this->mutated('service.contributed','migrations.registry');return$this;}
	public function migrationPlan(string $scope,?string $tenant,PanelMigrationVersion $target,mixed $createdAt=null):PanelMigrationPlan{return$this->migrationRunner()->plan($scope,$tenant,$target,$createdAt);}
	public function registerDataSource(string $name,PanelDataSource $source,bool $replace=false):self{$this->dataSources()->register($name,$source,$replace);$this->mutated('service.contributed','data.registry');return$this;}
	public function registerDataSurface(PanelDataSurfaceDefinition $definition,bool $replace=false):self{$this->dataSurfaces()->register($definition,$replace);$this->mutated('service.contributed','data_surfaces.registry');return$this;}
	public function registerAgentTool(PanelAgentTool $tool,PanelAgentToolExecutor $executor,string $contributor='application',int $priority=0):self{$this->assertReadyDomain('agent_workflows');$this->agentTools()->register($tool,$executor,$contributor,$priority);$this->mutated('service.contributed','agents.catalog');return$this;}
	public function registerWorkflow(WorkflowDefinition $definition):self{$this->assertReadyDomain('workflows');$this->workflowEngine()->register($definition);$this->mutated('service.contributed','workflows.engine');return$this;}
	public function registerAutomation(AutomationAction $action,bool $replace=false):self{$this->assertReadyDomain('automation');$this->automationRegistry()->register($action,$replace);$this->mutated('service.contributed','automation.registry');return$this;}
	public function registerExtension(PanelExtensionDescriptor|array $extension):self{$this->register('extensions.registry',$this->extensions()->register($extension),true);return$this;}
	public function onExtension(string $event,callable $listener,int $priority=0,array|string $scopes=['*']):self{$this->register('extensions.runtime',$this->extensionRuntime()->on($event,$listener,$priority,$scopes),true);return$this;}
	public function relation(string $name,string|int $parentKey,PanelRelationAdapter $adapter):PanelRelationWorkspace{return PanelRelationWorkspace::make($name,$parentKey,$adapter);}
	public function arrayRelation(array $records=[],array $links=[]):PanelArrayRelationAdapter{return new PanelArrayRelationAdapter($records,$links);}
	public function securityContext(string|int $actor,array $options=[]):PanelSecurityContext{return PanelSecurityContext::make($actor,$options);}
	public function securityPolicy(string $ability):PanelSecurityPolicy{return PanelSecurityPolicy::make($ability);}
	public function inspect(mixed $manifest):PanelManifestInspector{return PanelDeveloperToolkit::inspect($manifest);}
	public function operationsOsPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->operationsOs($this->operationsConsole(),$options,$request);}
	public function operationsPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->operations($this->operationStore(),$options,$request);}
	public function workflowsPage(?string $definition=null,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->workflows($this->workflowStore()->all($definition),$options,$request);}
	public function automationPage(?string $action=null,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->automation($this->automationRegistry(),$this->automationStore()->all($action),$options,$request);}
	public function relationsPage(PanelRelationWorkspace $workspace,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->relations($workspace,$options,$request);}
	public function preferencesPage(string $userId,string $profile='default',?string $device=null,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->preferences($this->preferences($userId,$profile,$device),$options,$request);}
	public function collaborationPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->collaboration($this->collaboration(),$options,$request);}
	public function packagesPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->packages($this->packageCatalog(),$options,$request);}
	public function authenticationPage(string|int $userId,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->authentication($this->authentication(),$userId,$options,$request);}
	public function notificationInbox():PanelNotificationInbox{return PanelNotificationInbox::using($this->notificationAdapter());}
	public function notificationsPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{$recipient=array_key_exists('recipient',$options)&&$options['recipient']!==null?(string)$options['recipient']:null;if($recipient!==null){$includeDismissed=($options['include_dismissed']??false)===true;$notifications=$this->notificationAdapter()->forRecipient($recipient,$includeDismissed);if(($options['include_global']??true)!==false){$notifications=array_merge($notifications,$this->notificationAdapter()->forRecipient(null,$includeDismissed));}$unique=[];foreach($notifications as$notification){$unique[$notification->id()]=$notification;}$inbox=array_map(static fn(PanelInboxNotification $notification):array=>$notification->toArray(),array_values($unique));}else{$inbox=$this->notificationInbox();}return$this->controller()->notifications($inbox,$options+['activity'=>$this->notificationActivity()->manifest()],$request);}
	public function mediaPage(array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->media($this->media(),$options,$request);}
	public function securityPage(array $reports=[],array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->security($reports!==[]?$reports:[$this->securityAudit()->jsonSerialize()],$options,$request);}
	public function developerPage(mixed $manifest,array $options=[],PanelRequest|array|null $request=null):PanelPageResult{return$this->controller()->developer($this->inspect($manifest),null,null,$options,$request);}

	/**
	 * Builds opt-in first-party pages backed by this exact platform instance.
	 *
	 * Read requests render domain pages. Non-read requests are delegated to the
	 * existing controller mutation methods, retaining their method, CSRF,
	 * authorization, tenant, and audit boundaries.
	 *
	 * @param array<string,mixed> $options Page naming, navigation, and domain options.
	 * @return array<string,PanelPage>
	 */
	public function pages(array $options=[]):array{
		$manifest=$this->manifest();
		if(!$manifest->ready('platform')){throw new \LogicException('Panel platform pages require a ready platform controller and template.');}
		$prefix=Resource::normalizeName((string)($options['prefix']??'platform'))?:'platform';
		$group=trim((string)($options['group']??'Platform'))?:'Platform';
		$hidden=($options['hidden']??false)===true;
		$allowed=array_values(array_filter(array_map(static fn(mixed $domain):string=>Resource::normalizeName((string)$domain),is_array($options['domains']??null)?$options['domains']:[])));
		$catalogue=[
			'operations_os'=>['label'=>'Operations OS','description'=>'Work, commands, policy, domains, compliance, fleet, and releases in one governed console.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->operationsOsPage($domainOptions,$request):$this->controller()->operateOperationsOs($this->operationsConsole(),$request,$domainOptions);}],
			'operations'=>['label'=>'Operations','description'=>'Durable jobs, queues, progress, retries, and control.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->operationsPage($domainOptions,$request):$this->controller()->operate($this->operationControl(),$request,$domainOptions);}],
			'workflows'=>['label'=>'Workflows','description'=>'Definitions, transitions, approvals, assignments, and audit history.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->workflowsPage(isset($domainOptions['definition'])?(string)$domainOptions['definition']:null,$domainOptions,$request):$this->controller()->workflow($this->workflowEngine(),$request,$domainOptions);}],
			'automation'=>['label'=>'Automation','description'=>'Registered actions, execution plans, receipts, and rollback.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{if(self::readRequest($request)){return$this->automationPage(isset($domainOptions['action'])?(string)$domainOptions['action']:null,$domainOptions,$request);}$action=trim((string)$request->input('action',$domainOptions['action']??''));return$action!==''?$this->controller()->automate($this->automationExecutor(),$action,$request,$domainOptions):PanelPageResult::json(['ok'=>false,'status'=>'invalid','errors'=>['An automation action is required.']],422);}],
			'notifications'=>['label'=>'Notifications','description'=>'Inbox state, delivery, mentions, assignments, and activity.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{$recipient=self::pageUserId($request,$domainOptions);if($recipient===null){return self::missingUser();}$domainOptions['recipient']=$recipient;if(self::readRequest($request)){return$this->notificationsPage($domainOptions,$request);}$id=trim((string)$request->input('id',''));$notification=$id!==''?$this->notificationAdapter()->get($id):null;if($notification instanceof PanelInboxNotification&&$notification->recipient()!==null&&$notification->recipient()!==$recipient){return PanelPageResult::json(['ok'=>false,'status'=>'not_found'],404);}return$this->controller()->notify($this->notificationInbox(),$request,$domainOptions);}],
			'media'=>['label'=>'Media','description'=>'Uploads, processing, variants, delivery, and cleanup.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->mediaPage($domainOptions,$request):PanelPageResult::json(['ok'=>false,'status'=>'method_not_allowed'],405,['Allow'=>'GET, HEAD']);}],
			'preferences'=>['label'=>'Preferences','description'=>'Appearance, saved views, recents, pins, and device overrides.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{$userId=self::pageUserId($request,$domainOptions);if($userId===null){return self::missingUser();}$profile=(string)($domainOptions['profile']??'default');$device=isset($domainOptions['device'])?(string)$domainOptions['device']:null;$workspace=$this->preferences($userId,$profile,$device);return self::readRequest($request)?$this->controller()->preferences($workspace,$domainOptions,$request):$this->controller()->prefer($workspace,$request,$domainOptions);}],
			'collaboration'=>['label'=>'Collaboration','description'=>'Threads, comments, assignments, watchers, and presence.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->collaborationPage($domainOptions,$request):$this->controller()->collaborate($this->collaboration(),$request,$domainOptions);}],
			'packages'=>['label'=>'Packages','description'=>'Signed package discovery, publisher trust, availability, and version history.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->packagesPage($domainOptions,$request):PanelPageResult::json(['ok'=>false,'status'=>'method_not_allowed'],405,['Allow'=>'GET, HEAD']);}],
			'authentication'=>['label'=>'Authentication','description'=>'MFA, step-up challenges, trusted devices, and sessions.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{$userId=self::pageUserId($request,$domainOptions);if($userId===null){return self::missingUser();}return self::readRequest($request)?$this->authenticationPage($userId,$domainOptions,$request):$this->controller()->authenticate($this->authentication(),$request,$domainOptions);}],
			'security'=>['label'=>'Security','description'=>'Policy decisions, permission simulation, impersonation, and audit.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->securityPage(is_array($domainOptions['reports']??null)?$domainOptions['reports']:[],$domainOptions,$request):PanelPageResult::json(['ok'=>false,'status'=>'method_not_allowed'],405,['Allow'=>'GET, HEAD']);}],
			'development'=>['label'=>'Developer','description'=>'Manifest inspection, diffs, schema blueprints, and quality plans.','render'=>function(PanelRequest $request,array $domainOptions):PanelPageResult{return self::readRequest($request)?$this->developerPage($domainOptions['manifest']??$this->manifest(),$domainOptions,$request):PanelPageResult::json(['ok'=>false,'status'=>'method_not_allowed'],405,['Allow'=>'GET, HEAD']);}],
		];
		$pages=[];$sort=(int)($options['sort']??800);
		foreach($catalogue as$domain=>$definition){
			if(($allowed!==[]&&!in_array($domain,$allowed,true))||!$manifest->ready($domain)){continue;}
			$domainOptions=is_array($options[$domain]??null)?$options[$domain]:[];
			$name=$prefix.'_'.$domain;$renderer=$definition['render'];$allowGuest=($domainOptions['allow_guest']??$options['allow_guest']??false)===true;
			$page=PanelPage::make($name)->label((string)$definition['label'])->group($group)->navigationDescription((string)$definition['description'])->sort($sort++)->meta(['platform_domain'=>$domain,'platform_page'=>true])->renderUsing(static function(PanelRequest $request)use($renderer,$domainOptions,$allowGuest):PanelPageResult{if(!$allowGuest&&self::pageUserId($request,$domainOptions)===null){return self::missingUser();}return$renderer($request,$domainOptions);});
			$authorizer=$domainOptions['authorize']??$options['authorize']??null;if(is_callable($authorizer)){$page=$page->authorize($authorizer);}
			if($hidden||($domainOptions['hidden']??false)===true){$page=$page->hideFromNavigation();}
			$pages[$name]=$page;
		}
		return$pages;
	}

	public function manifest():PanelPlatformManifest{return PanelPlatformManifest::inspect($this);}
	public function revision():int{return$this->revision;}
	/** @return array{operation:string,service:?string,revision:int} */ public function lifecycle():array{return$this->lastMutation;}
	/** @return list<string> */ public function names():array{$names=array_values(array_unique(array_merge(array_keys($this->services),array_keys($this->factories))));sort($names,SORT_STRING);return$names;}
	/** @return array<string,array{type:string,factory:bool,resolved:bool,singleton:bool}> */
	public function serviceDescriptors():array{$descriptors=[];foreach($this->names()as$name){$resolved=array_key_exists($name,$this->services);$value=$resolved?$this->services[$name]:null;$descriptors[$name]=['type'=>$resolved?(is_object($value)?$value::class:get_debug_type($value)):'factory','factory'=>isset($this->factories[$name]),'resolved'=>$resolved,'singleton'=>$resolved||($this->factories[$name]['singleton']??false)];}return$descriptors;}
	/** @return array{service:string,expected:string,present:bool,valid:bool,state:string,actual:?string} */
	public function serviceStatus(string $name,string $expected):array{$name=self::serviceName($name);$expected=trim($expected);if(isset($this->factories[$name])&&!array_key_exists($name,$this->services)){return['service'=>$name,'expected'=>$expected,'present'=>true,'valid'=>false,'state'=>'unresolved_factory','actual'=>'factory'];}if(!array_key_exists($name,$this->services)){return['service'=>$name,'expected'=>$expected,'present'=>false,'valid'=>false,'state'=>'missing','actual'=>null];}$value=$this->services[$name];$valid=match(true){$expected==='callable'=>is_callable($value),str_starts_with($expected,'class-string:')=>is_string($value)&&is_a($value,substr($expected,13),true),$expected==='' => true,default=>is_object($value)&&is_a($value,$expected)};return['service'=>$name,'expected'=>$expected,'present'=>true,'valid'=>$valid,'state'=>$valid?'ready':'invalid','actual'=>is_object($value)?$value::class:get_debug_type($value)];}
	/** @return array<string,mixed> */ public function diagnostics():array{$manifest=$this->manifest()->jsonSerialize();return['type'=>'panel_platform_diagnostics','revision'=>$this->revision,'lifecycle'=>$this->lastMutation,'counts'=>$manifest['counts']??[],'domains'=>$manifest['domains']??[],'services'=>$this->serviceDescriptors(),'security'=>$manifest['security']??[],'transactions'=>['container_checkpoint'=>true,'checkpointable_nested_services'=>true,'nested_data_registry_checkpoint'=>true,'arbitrary_service_object_mutations_rolled_back'=>false]];}
	public function jsonSerialize():array{return['type'=>'panel_platform','version'=>1,'metadata'=>['defaults'=>($this->metadata['defaults']??false)===true,'state_root_configured'=>isset($this->metadata['state_root']),'enabled_domains'=>is_array($this->metadata['enabled_domains']??null)?array_values($this->metadata['enabled_domains']):[]],'manifest'=>$this->manifest()->jsonSerialize()];}

	/** @param array<string,mixed> $config @return array<string,mixed>|false */ private static function domain(array $config,string $name):array|false{$value=$config[$name]??[];if($value===false){return false;}if($value===true||$value===null){return[];}if(!is_array($value)){throw new \InvalidArgumentException("Panel platform domain '{$name}' configuration must be an array, true, or false.");}return$value;}
	private static function stateRoot(mixed $root):string{$root=rtrim(trim((string)$root),'/\\');if($root===''){throw new \InvalidArgumentException('PanelPlatform::defaults requires state_root.');}if(is_link($root)){throw new \InvalidArgumentException('Panel platform state_root cannot be a symbolic link.');}if(!is_dir($root)&&!@mkdir($root,0770,true)&&!is_dir($root)){throw new \RuntimeException('Unable to create Panel platform state_root.');}$real=realpath($root);if($real===false||!is_writable($real)){throw new \RuntimeException('Panel platform state_root is not writable.');}return str_replace('\\','/',$real);}
	private static function secret(mixed $value,string $name):string{$value=is_string($value)?$value:'';if(strlen($value)<32){throw new \InvalidArgumentException("Panel platform {$name} must be explicitly configured with at least 32 bytes.");}return$value;}
	/** @param list<class-string> $classes */ private static function classes(string $domain,array $classes):void{foreach($classes as$class){try{$available=class_exists($class)||interface_exists($class);}catch(\Throwable $error){throw new \LogicException("Panel platform domain '{$domain}' could not load {$class}: ".$error->getMessage(),0,$error);}if(!$available){throw new \LogicException("Panel platform domain '{$domain}' requires unavailable class {$class}.");}}}
	private static function serviceName(string $name):string{$name=strtolower(trim($name));$name=preg_replace('/[^a-z0-9_.-]+/','.',$name)??'';$name=trim(preg_replace('/\.{2,}/','.',$name)??'','.');if($name===''){throw new \InvalidArgumentException('Panel platform service name cannot be blank.');}return substr($name,0,190);}
	private function mutated(string $operation,string $service):void{$this->revision++;$this->lastMutation=['operation'=>$operation,'service'=>$service,'revision'=>$this->revision];}
	private function assertReadyDomain(string $domain):void{if(!$this->manifest()->ready($domain)){throw new \LogicException("Panel platform domain '{$domain}' is incomplete or has a split dependency graph.");}}
	private static function readRequest(PanelRequest $request):bool{return in_array(strtoupper($request->method()),['GET','HEAD'],true);}
	/** @param array<string,mixed> $options */ private static function pageUserId(PanelRequest $request,array $options):?string{$resolved=$options['user_id']??null;if(is_callable($resolved)){try{$resolved=$resolved($request);}catch(\Throwable){return null;}}if($resolved===null){$resolved=$request->user();}if(is_scalar($resolved)){$resolved=trim((string)$resolved);return$resolved!==''?$resolved:null;}if(is_array($resolved)){foreach(['id','user_id','key']as$key){if(isset($resolved[$key])&&is_scalar($resolved[$key])&&trim((string)$resolved[$key])!==''){return(string)$resolved[$key];}}}if(is_object($resolved)){foreach(['id','user_id','key']as$key){if(isset($resolved->{$key})&&is_scalar($resolved->{$key})&&trim((string)$resolved->{$key})!==''){return(string)$resolved->{$key};}}foreach(['getId','id','key']as$method){if(method_exists($resolved,$method)){try{$value=$resolved->{$method}();if(is_scalar($value)&&trim((string)$value)!==''){return(string)$value;}}catch(\Throwable){return null;}}}}return null;}
	private static function missingUser():PanelPageResult{return PanelPageResult::json(['ok'=>false,'status'=>'unauthenticated','errors'=>['An authenticated user is required.']],401);}
}
