<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/**
 * Coordinates panel UI rendering, localized shell text, and renderer traits.
 *
 * PanelRenderer is the central renderer facade for panel pages, tables, actions,
 * imports, record sections, forms, assets, and shell chrome. It keeps shared text
 * defaults and client translation export in one place while delegating focused
 * rendering behavior to the included renderer traits.
 */
final class PanelRenderer {

	private const TABLE_PREF_SESSION_KEY='dataphyre_panel_table_preferences';
	private const FLASH_SESSION_KEY='dataphyre_panel_flash_notifications';
	private const TEXT_DEFAULTS=[
			'common.all'=>'All',
			'common.any'=>'Any',
			'common.none'=>'None',
			'common.no'=>'No',
			'common.untitled'=>'Untitled',
			'common.yes'=>'Yes',
		'common.cancel'=>'Cancel',
		'common.clear'=>'Clear',
		'common.clear_all'=>'Clear all',
		'common.close'=>'Close',
		'common.copy'=>'Copy',
		'common.copied'=>'Copied',
		'common.remove'=>'Remove',
		'copy.unable'=>'Unable to copy',
		'copy.value'=>'Copy value',
		'copy.current_url'=>'Copy current URL',
		'copy.current_url_done'=>'Copied current URL',
		'copy.rows'=>'Copied {count} {row}',
		'copy.focused_row'=>'Copied focused row',
		'copy.selected_rows'=>'Copied selected rows',
		'copy.visible_rows'=>'Copied visible rows',
		'copy.no_rows'=>'No rows to copy',
		'copy.no_row_data'=>'No row data to copy',
		'nav.clear_pinned'=>'Clear pinned navigation',
		'nav.pinned_cleared'=>'Pinned navigation cleared',
		'common.default_slice'=>'Default slice',
		'common.current_view'=>'Current view',
		'common.record'=>'record',
		'common.records'=>'records',
		'common.search'=>'Search',
		'common.reset'=>'Reset',
		'common.apply'=>'Apply',
		'common.up'=>'Up',
		'common.down'=>'Down',
		'common.back'=>'Back',
		'common.previous'=>'Previous',
		'common.next'=>'Next',
		'common.refresh'=>'Refresh',
		'common.export'=>'Export',
		'common.import'=>'Import',
		'common.snapshot'=>'Snapshot',
		'common.restore'=>'Restore',
		'common.open'=>'Open',
		'common.save'=>'Save',
		'common.send'=>'Send',
		'common.confirm'=>'Confirm',
		'common.run'=>'Run',
		'common.view'=>'View',
		'common.edit'=>'Edit',
		'common.show'=>'Show',
		'common.duplicate'=>'Duplicate',
		'common.delete'=>'Delete',
		'common.delete_forever'=>'Delete forever',
		'modal.unsaved_close'=>'Unsaved modal changes. Close again to discard.',
		'modal.unsaved_back'=>'Unsaved modal changes. Back again to discard.',
		'modal.back'=>'Back',
		'modal.open_full_page'=>'Open full page',
		'modal.copy_link'=>'Copy link',
		'modal.expand'=>'Expand',
		'modal.normal'=>'Normal',
		'modal.action'=>'Action',
		'modal.link_copied'=>'Modal link copied',
		'modal.saving_changes'=>'Saving changes...',
		'modal.done_refreshing_workspace'=>'Done. Refreshing the workspace...',
		'modal.done_updating_workspace'=>'Done. Updating the workspace...',
		'modal.unexpected_response_retry'=>'The action returned an unexpected response. Please retry or open the full page.',
		'modal.submit_failed_retry'=>'The action could not complete in the dialog. Please retry or open the full page.',
		'modal.opening'=>'Opening...',
		'modal.running_action'=>'Running action...',
		'modal.refresh_failed'=>'The action could not refresh in place.',
		'modal.confirm_action'=>'Confirm action',
		'modal.run_action'=>'Run this action?',
		'modal.working'=>'Working...',
		'modal.loading_action'=>'Loading action',
		'modal.loading_action_context'=>'Preparing the form and current record context.',
		'modal.review_highlighted'=>'Review the highlighted fields and try again.',
		'modal.unexpected_response'=>'The action returned an unexpected response.',
		'modal.unexpected_response_refresh'=>'The action returned an unexpected response. Refreshing the panel is safest.',
		'common.loading_section'=>'Loading this section...',
		'common.load_section'=>'Load section',
		'search.workspace_placeholder'=>'Search across this workspace',
		'search.records_aria'=>'Search records',
		'table.search_placeholder'=>'Search',
		'table.search_table_placeholder'=>'Search {table}',
		'table.search_board_placeholder'=>'Search board',
		'table.search_resource_aria'=>'Search {resource}',
		'table.filters'=>'Filters',
		'table.board_filters'=>'Board filters',
		'table.board_filters_description'=>'Narrow the board without moving the toolbar.',
		'table.filters_description'=>'Narrow this table without losing your place.',
		'table.columns'=>'Columns',
		'table.columns_compact'=>'Cols',
		'table.column'=>'Column',
		'table.rows'=>'Rows',
		'table.row'=>'row',
		'table.row_plural'=>'rows',
		'table.table'=>'Table',
		'table.views_aria'=>'{table} views',
		'table.grouping_aria'=>'{table} grouping',
		'table.ungrouped'=>'Ungrouped',
		'table.other'=>'Other',
		'table.view_title'=>'View: {view}',
		'table.aria_suffix'=>'{resource} table',
		'table.actions'=>'Actions',
		'table.more'=>'More',
		'table.more_actions_for'=>'More actions for {record}',
		'table.select_record'=>'Select record {record}',
		'table.select_this_record'=>'Select this record',
		'table.find_columns'=>'Find columns',
		'table.select_all_visible'=>'Select all visible records',
		'table.record_count'=>'{count} {record}',
		'table.preview'=>'Preview',
		'table.density'=>'Table density',
		'table.density_compact'=>'Compact',
		'table.density_normal'=>'Normal',
		'table.density_comfortable'=>'Roomy',
		'table.page_count'=>'Page {page} of {pages}',
		'table.save_view'=>'Save view',
		'table.remove_saved_view'=>'Remove saved view',
		'table.saved_views'=>'Saved views',
		'table.no_saved_views'=>'No saved views yet.',
		'table.selected'=>'selected',
		'table.visible_records'=>'Visible records',
		'table.inline_live'=>'Live',
		'table.inline_hidden'=>'Hidden',
		'table.view_hint_saved'=>'A saved perspective is shaping this list.',
		'table.view_hint_all'=>'The complete resource table is in view.',
		'table.search_hint_active'=>'Text search is narrowing the table.',
		'table.search_hint_empty'=>'Search when you need a specific record.',
		'table.filters_hint_empty'=>'No filter constraints are active.',
			'table.filters_hint_active'=>'Active filters are narrowing this slice.',
			'table.filter_from'=>'From',
			'table.filter_to'=>'To',
		'table.group'=>'Group',
		'table.grouped_hint'=>'Rows are sectioned by a table group.',
		'table.ungrouped_hint'=>'Rows are rendered as one continuous list.',
		'table.visible_slice'=>'Visible slice',
		'table.visible_slice_supplied'=>'Supplied by the caller.',
		'table.visible_slice_current'=>'Current page inside {total} total records.',
		'table.import_title'=>'Import {resource}',
		'table.import_description'=>'Upload or paste rows, then preview the mapping before saving anything.',
		'select.empty'=>'Select...',
		'select.search_placeholder'=>'Search options',
		'select.search_relation_placeholder'=>'Search {label}',
		'select.no_results'=>'No matching options',
		'range.start'=>'Start',
		'range.end'=>'End',
		'slider.current_value'=>'Current value',
		'filter.active_filters'=>'Active filters',
		'import.expected_columns'=>'The importer will look for: {columns}',
		'import.csv'=>'CSV import',
		'import.csv_description'=>'Upload a file or paste rows. The preview will check shape before anything is saved.',
		'import.csv_submit'=>'Import CSV',
		'import.download_template'=>'Download template',
		'import.unable_export'=>'Unable to prepare export.',
		'import.unable_template'=>'Unable to prepare import template.',
		'import.pass_through'=>'Every CSV column will be passed through to the import handler.',
		'import.csv_file'=>'CSV file',
		'import.csv_rows'=>'CSV rows',
		'import.csv_rows_help'=>'Paste a header row and a few records to test mapping quickly.',
		'import.delimiter'=>'Delimiter',
		'import.delimiter_auto'=>'Auto',
		'import.delimiter_comma'=>'Comma',
		'import.delimiter_semicolon'=>'Semicolon',
		'import.delimiter_tab'=>'Tab',
		'import.delimiter_pipe'=>'Pipe',
		'import.has_header'=>'First row contains column names',
		'import.page_title'=>'Import {resource}',
		'client.command_palette'=>'Command palette',
		'client.jump_to_panel_item'=>'Jump to a panel item',
		'client.jump_to_placeholder'=>'Jump to...',
		'client.no_results'=>'No results',
		'client.no_results_for'=>'No results for {query}',
		'client.command'=>'Command',
		'client.panel'=>'Panel',
		'client.opens_link'=>'Opens link',
		'client.runs_command'=>'Runs command',
		'client.run'=>'Run',
		'client.shortcut'=>'Shortcut',
		'client.enter'=>'Enter',
		'client.esc'=>'Esc',
		'client.toolbar'=>'Toolbar',
		'client.bulk_action'=>'Bulk action',
		'client.filter'=>'Filter',
		'client.columns'=>'Columns',
		'client.pagination'=>'Pagination',
		'client.action_menu'=>'Action menu',
		'client.record_action'=>'Record action',
		'client.navigation'=>'Navigation',
		'client.view'=>'View',
		'client.search'=>'Search',
		'client.action'=>'Action',
		'client.breadcrumb'=>'Breadcrumb',
		'client.pinned_category'=>'Pinned',
		'client.recent'=>'Recent',
		'client.saved_view'=>'Saved view',
		'client.selection'=>'Selection',
		'client.focused_row'=>'Focused row',
		'client.filters'=>'Filters',
		'client.no_selectable_rows'=>'No selectable rows here',
		'client.row_selected'=>'1 row selected',
		'client.rows_selected'=>'{count} rows selected',
		'client.selection_inverted'=>'Selection inverted',
		'client.no_selected_rows'=>'No selected rows to clear',
		'client.no_focused_row'=>'No row is focused',
		'client.no_primary_action'=>'No primary action on this row',
		'client.focused_row_action'=>'Focused the row action',
		'client.no_row_actions'=>'No actions on this row',
		'client.record'=>'Record',
		'client.field'=>'Field',
		'client.steps'=>'Steps',
		'client.copy_json'=>'Copy JSON',
		'client.copy_csv'=>'Copy CSV',
		'client.preview_position'=>'{index} of {total}',
		'client.no_filters'=>'No filters on this view',
		'client.no_columns'=>'No column controls on this view',
		'client.review_highlighted_fields'=>'Review the highlighted fields',
		'client.column_resize_hint'=>'Drag to resize. Double-click to reset.',
		'client.column_width_reset'=>'Column width reset',
		'client.navigation_pinned'=>'Navigation pinned',
		'client.navigation_unpinned'=>'Navigation unpinned',
		'client.no_active_navigation'=>'No navigation item is active',
		'client.navigation_already_pinned'=>'Navigation is already pinned',
		'client.navigation_not_pinned'=>'Navigation is not pinned',
		'client.recent_navigation_cleared'=>'Recent navigation cleared',
		'client.no_navigation_matches'=>'No navigation matches',
		'client.navigation_groups_expanded'=>'Navigation groups expanded',
		'client.navigation_groups_collapsed'=>'Navigation groups collapsed',
		'client.action_in_progress'=>'Let the current action finish first',
		'client.action_refresh_failed'=>'That action could not refresh in place',
		'client.action_complete_failed'=>'That action could not complete',
		'client.already_working'=>'Already working on that request',
		'client.inline_save_failed'=>'Inline save failed',
		'client.workspace_snapshot_prompt'=>'Paste workspace snapshot JSON',
		'client.workspace_snapshot_restored'=>'Workspace snapshot restored',
		'client.workspace_snapshot_invalid'=>'Workspace snapshot JSON was not valid',
		'client.link_url_prompt'=>'Link URL',
		'import.no_preview_columns'=>'No importable columns to preview.',
		'import.row'=>'Row',
		'import.status'=>'Status',
		'import.ready'=>'Ready',
		'import.needs_attention'=>'Needs attention',
		'template.empty_title'=>'Nothing to show yet.',
		'template.empty_live_data'=>'Live data will appear here when records exist.',
		'template.no_conversations'=>'No conversations yet.',
		'template.no_messages'=>'No messages yet.',
		'template.conversations'=>'Conversations',
		'template.conversation'=>'Conversation',
		'template.no_records'=>'No records available.',
		'template.search_options'=>'Search options',
		'template.no_matching_options'=>'No matching options',
		'template.search_field'=>'{label} search',
		'template.no_document_content'=>'No document content available.',
		'record.tags'=>'Tags',
		'record.tag'=>'tag',
		'record.tag_plural'=>'tags',
		'record.links'=>'Links',
		'record.link'=>'link',
		'record.link_plural'=>'links',
		'record.contacts'=>'Contacts',
		'record.contact'=>'contact',
		'record.contact_plural'=>'contacts',
		'record.locations'=>'Locations',
		'record.location'=>'location',
		'record.location_plural'=>'locations',
		'record.items'=>'Items',
		'record.item'=>'item',
		'record.item_plural'=>'items',
		'record.totals'=>'Totals',
		'record.line'=>'line',
		'record.line_plural'=>'lines',
		'record.approvals'=>'Approvals',
		'record.pending'=>'pending',
		'record.activity'=>'Activity',
		'record.event'=>'event',
		'record.event_plural'=>'events',
		'record.changes'=>'Changes',
		'record.change'=>'change',
		'record.change_plural'=>'changes',
		'record.before'=>'Before',
		'record.after'=>'After',
		'record.payments'=>'Payments',
		'record.entry'=>'entry',
		'record.entries'=>'entries',
		'record.shipments'=>'Shipments',
		'record.shipment'=>'shipment',
		'record.shipment_plural'=>'shipments',
		'record.needs_attention'=>'Needs attention',
		'record.open'=>'Open',
		'record.insight'=>'Insight',
		'record.link_default'=>'Link',
		'record.contact_default'=>'Contact',
		'record.location_default'=>'Location',
		'record.item_default'=>'Item',
		'record.total_default'=>'Total',
		'record.payment_default'=>'Payment',
		'record.shipment_default'=>'Shipment',
		'record.tags_empty'=>'No tags yet. Add tags to make this record easier to segment, find, and triage.',
		'record.add_tag'=>'Add tag',
		'record.remove_tag'=>'Remove tag',
		'record.remove_tag_title'=>'Remove {label}',
		'record.remove_tag_confirm'=>'Remove {label}?',
		'record.remove_tag_body'=>'Remove {label} from this record?',
		'record.notes'=>'Internal Notes',
		'record.note'=>'note',
		'record.note_plural'=>'notes',
		'record.notes_empty'=>'No internal notes yet. Add context so the next person understands what happened and why.',
		'record.add_note'=>'Add note',
		'record.add_note_body'=>'Capture internal context for the next operator.',
		'record.notes_unavailable'=>'Notes unavailable',
		'record.notes_unavailable_body'=>'This resource does not define a note handler.',
		'record.note_requires_submission'=>'Note requires submission',
		'record.note_requires_submission_body'=>'Use the generated note form to add an internal note.',
		'record.note_empty'=>'Note is empty',
		'record.note_empty_body'=>'Write a note before saving it.',
		'record.note_added'=>'Note added.',
		'record.attachments'=>'Attachments',
		'record.file'=>'file',
		'record.file_plural'=>'files',
		'record.attachments_empty'=>'No attachments yet. Upload files that help explain, verify, or resolve this record.',
		'record.add_attachment'=>'Add attachment',
		'record.upload_attachment'=>'Upload attachment',
		'record.upload_attachment_body'=>'Attach evidence, files, or context to this record.',
		'record.upload'=>'Upload',
		'record.messages'=>'Messages',
		'record.message'=>'message',
		'record.message_plural'=>'messages',
		'record.messages_empty'=>'No messages yet. Send updates from here when the record needs a communication trail.',
		'record.send_message'=>'Send message',
		'record.send_message_body'=>'Send an update while preserving this record context.',
		'record.messages_unavailable'=>'Messages unavailable',
		'record.messages_unavailable_body'=>'This resource does not define a message handler.',
		'record.message_requires_submission'=>'Message requires submission',
		'record.message_requires_submission_body'=>'Use the generated message form to send a message.',
		'record.message_empty'=>'Message is empty',
		'record.message_empty_body'=>'Write a message before sending it.',
		'record.message_sent'=>'Message sent.',
		'record.channel'=>'Channel',
		'record.email'=>'Email',
		'record.sms'=>'SMS',
		'record.chat'=>'Chat',
		'record.system'=>'System',
		'record.recipient'=>'Recipient',
		'record.subject'=>'Subject',
		'record.message_body'=>'Message',
		'record.tasks'=>'Tasks',
		'record.task'=>'Task',
		'record.tasks_empty'=>'No tasks yet. Add the next concrete step to keep ownership clear.',
		'record.add_task'=>'Add task',
		'record.add_task_body'=>'Create the next concrete step for this record.',
		'record.tags_unavailable'=>'Tags unavailable',
		'record.tags_unavailable_body'=>'This resource does not define a tag handler.',
		'record.tag_requires_submission'=>'Tag requires submission',
		'record.tag_requires_submission_body'=>'Use the generated tag form to update tags.',
		'record.tag_not_selected'=>'Tag not selected',
		'record.tag_not_selected_body'=>'Choose a tag and action before updating it.',
		'record.tag_added'=>'Tag added.',
		'record.tag_removed'=>'Tag removed.',
		'record.attachments_unavailable'=>'Attachments unavailable',
		'record.attachments_unavailable_body'=>'This resource does not define an attachment handler.',
		'record.attachment_requires_upload'=>'Attachment requires upload',
		'record.attachment_requires_upload_body'=>'Use the generated attachment form to upload a file.',
		'record.no_file_selected'=>'No file selected',
		'record.no_file_selected_body'=>'Choose a file before uploading.',
		'record.attachment_added'=>'Attachment added.',
		'record.tasks_unavailable'=>'Tasks unavailable',
		'record.tasks_unavailable_body'=>'This resource does not define a task handler.',
		'record.task_requires_submission'=>'Task requires submission',
		'record.task_requires_submission_body'=>'Use the generated task button to update a checklist item.',
		'record.task_not_selected'=>'Task not selected',
		'record.task_not_selected_body'=>'Select a task before updating it.',
		'record.task_completed'=>'Task completed.',
		'record.task_reopened'=>'Task reopened.',
		'record.task_creation_unavailable'=>'Task creation unavailable',
		'record.task_creation_unavailable_body'=>'This resource does not define a task creation handler.',
		'record.task_title_empty'=>'Task title is empty',
		'record.task_title_empty_body'=>'Write a task title before adding it.',
		'record.task_added'=>'Task added.',
		'record.reopen'=>'Reopen',
		'record.complete'=>'Complete',
		'record.task_status'=>'{completed} of {total} complete',
		'record.details'=>'Details',
		'record.due'=>'Due',
		'record.assignee'=>'Assignee',
		'record.approval'=>'Approval',
		'record.approve'=>'Approve',
		'record.reject'=>'Reject',
		'record.approval_action_title'=>'{action} approval',
		'record.approval_action_confirm'=>'{action} {title}?',
		'record.approvals_empty'=>'No approvals are waiting. New approval work will appear here when a decision is needed.',
		'record.approval_unavailable'=>'Approval unavailable',
		'record.approval_unavailable_body'=>'This resource does not define an approval handler.',
		'record.approval_requires_submission'=>'Approval requires submission',
		'record.approval_requires_submission_body'=>'Use the generated approval button to resolve a review item.',
		'record.approval_not_selected'=>'Approval not selected',
		'record.approval_not_selected_body'=>'Select an approval and decision before resolving it.',
		'record.approval_accepted'=>'Approval accepted.',
		'record.approval_rejected'=>'Approval rejected.',
		'record.task_action_title'=>'{action} task',
		'record.task_action_confirm'=>'{action} {title}?',
		'action.confirm_action'=>'Confirm action',
		'action.run_action_confirm'=>'Run {action}?',
		'action.selected_records_will_update'=>'{count} selected {record} will be updated.',
		'action.field_issue_summary'=>'{count} field {issue} need attention.',
		'action.issue'=>'issue',
		'action.issues'=>'issues',
		'action.field'=>'field',
		'action.fields'=>'fields',
		'action.validation'=>'Validation',
		'action.validation_ready'=>'Ready',
		'action.validation_issue_count'=>'{count} {issue}',
		'action.validation_ready_hint'=>'No validation issues are currently present.',
		'action.validation_attention_hint'=>'{count} {field} need attention.',
		'action.update_selected'=>'Update selected',
		'action.bulk_update_title'=>'Bulk update {resource}',
		'action.selected_records_update'=>'{count} selected {record} will be updated.',
		'action.this_record'=>'this record',
		'action.duplicate_record'=>'Duplicate record',
		'action.restore_record'=>'Restore record',
		'action.delete_record'=>'Delete record',
		'action.force_delete_record'=>'Permanently delete record',
		'action.force_delete'=>'Force delete',
		'action.duplicate_record_confirm'=>'Duplicate {record}?',
		'action.restore_record_confirm'=>'Restore {record}?',
		'action.delete_record_confirm'=>'Delete {record}?',
		'action.force_delete_record_confirm'=>'Permanently delete {record}?',
		'action.bulk_confirm'=>'{action} selected records?',
		'action.bulk_title'=>'{action} selected records',
		'action.bulk_label'=>'{action} selected',
		'action.bulk_update_description'=>'Apply generated bulk fields to the selected records without leaving the table.',
		'action.duplicate_selected'=>'Duplicate selected',
		'action.restore_selected'=>'Restore selected',
		'action.delete_selected'=>'Delete selected',
		'action.force_delete_selected'=>'Force delete selected',
		'action.duplicate_selected_confirm'=>'Duplicate selected records?',
		'action.restore_selected_confirm'=>'Restore selected records?',
		'action.delete_selected_confirm'=>'Delete selected records?',
		'action.force_delete_selected_confirm'=>'Permanently delete selected records?',
		'action.duplicate_selected_body'=>'Duplicate every selected record?',
		'action.restore_selected_body'=>'Restore every selected record?',
		'action.delete_selected_body'=>'Delete every selected record?',
		'action.force_delete_selected_body'=>'Permanently delete every selected record?',
		'action.delete_unavailable'=>'Delete unavailable',
		'action.delete_unavailable_body'=>'This resource does not define a delete handler.',
		'action.delete_requires_confirmation'=>'Delete requires confirmation',
		'action.delete_requires_confirmation_body'=>'Use the generated delete button to confirm this operation.',
		'action.force_delete_unavailable'=>'Permanent delete unavailable',
		'action.force_delete_unavailable_body'=>'This resource does not define a permanent delete handler.',
		'action.force_delete_requires_confirmation'=>'Permanent delete requires confirmation',
		'action.force_delete_requires_confirmation_body'=>'Use the generated permanent delete button to confirm this operation.',
		'action.duplicate_unavailable'=>'Duplicate unavailable',
		'action.duplicate_unavailable_body'=>'This resource does not define a duplicate handler.',
		'action.duplicate_requires_confirmation'=>'Duplicate requires confirmation',
		'action.duplicate_requires_confirmation_body'=>'Use the generated duplicate button to confirm this operation.',
		'action.restore_unavailable'=>'Restore unavailable',
		'action.restore_unavailable_body'=>'This resource does not define a restore handler.',
		'action.restore_requires_confirmation'=>'Restore requires confirmation',
		'action.restore_requires_confirmation_body'=>'Use the generated restore button to confirm this operation.',
		'action.deleted'=>'Deleted.',
		'action.duplicated'=>'Duplicated.',
		'action.restored'=>'Restored.',
		'action.permanently_deleted'=>'Permanently deleted.',
		'record.not_found'=>'Record not found',
		'record.not_found_body'=>'The requested record could not be found.',
		'page.not_found'=>'Page not found',
		'page.not_found_body'=>'The requested page is not registered for this panel.',
		'relation.not_found'=>'Relation not found',
		'relation.not_found_body'=>'The requested relation is not registered.',
		'relation.parent_not_found_body'=>'The parent record for this relation could not be found.',
		'relation.action_not_found'=>'Relation action not found',
		'relation.action_not_found_body'=>'The requested relation action is not available.',
		'relation.unavailable'=>'{action} unavailable',
		'relation.unavailable_body'=>'This relation does not define a {action} handler.',
		'relation.choose_record'=>'Choose a record',
		'relation.choose_record_body'=>'Select the related record before submitting.',
		'relation.choose_row'=>'Choose a row',
		'relation.choose_row_body'=>'The relation row was not included in the request.',
		'relation.choose_order'=>'Choose row order',
		'relation.choose_order_body'=>'The relation row order was not included in the request.',
		'relation.reorder_unavailable'=>'Reorder unavailable',
		'relation.reorder_unavailable_body'=>'This relation does not define a reorder handler.',
		'relation.pivot_unavailable'=>'Pivot update unavailable',
		'relation.pivot_unavailable_body'=>'This relation does not define pivot fields and an update handler.',
		'relation.attached'=>'Related record attached.',
		'relation.associated'=>'Related record associated.',
		'relation.detached'=>'Related record detached.',
		'relation.dissociated'=>'Related record dissociated.',
		'relation.reordered'=>'Related records reordered.',
		'relation.pivot_updated'=>'Pivot fields updated.',
		'action.not_found'=>'Action not found',
		'action.not_found_body'=>'The requested action is not registered.',
		'action.not_found_state_body'=>'The requested action is not registered for this record state.',
		'action.page_not_found_body'=>'The requested page action is not registered.',
		'action.page_not_found_state_body'=>'The requested page action is not registered for this page state.',
		'action.unavailable'=>'Action unavailable',
		'action.unavailable_now'=>'This action is not available right now.',
		'action.empty_selection'=>'No records selected',
		'action.empty_selection_run_body'=>'Select at least one record before running this action.',
		'action.no_details'=>'No action details are available.',
		'action.completed'=>'Action completed',
		'action.completed_body'=>'Action completed.',
		'export.csv'=>'Export CSV',
		'export.json'=>'Export JSON',
		'export.selected_requires_selection'=>'Export selected requires selection',
		'export.selected_requires_selection_body'=>'Select records from the table before exporting them.',
		'export.no_records_body'=>'Select at least one record before exporting.',
		'import.unavailable'=>'Import unavailable',
		'import.unavailable_body'=>'This resource does not define an import or save handler.',
		'import.template_unavailable'=>'Import template unavailable',
		'import.template_unavailable_body'=>'This resource does not define importable fields.',
		'import.choose_csv'=>'Choose a CSV file or paste CSV rows before importing.',
		'import.no_rows'=>'No importable rows were found in the CSV.',
		'import.resolve_rows'=>'Resolve the highlighted row issues before importing.',
		'import.preview'=>'Import preview',
		'import.preview_title'=>'Preview import',
		'import.preview_summary'=>'{rows} {row} parsed, {invalid} with issues.',
		'import.refresh_preview'=>'Refresh preview',
		'import.import_rows'=>'Import {rows} {row}',
		'import.change_csv'=>'Change CSV',
		'import.imported'=>'{count} {row} imported.',
		'import.failed'=>'{count} {row} could not be imported.',
		'import.none_imported'=>'No rows were imported.',
		'transition.unavailable'=>'Transition unavailable',
		'transition.unavailable_body'=>'This resource does not define status transitions.',
		'transition.requires_confirmation'=>'Transition requires confirmation',
		'transition.requires_confirmation_body'=>'Use the generated transition button to confirm this operation.',
		'transition.not_found'=>'Transition not found',
		'transition.not_found_body'=>'The requested transition is not registered.',
		'transition.not_available'=>'Transition not available',
		'transition.not_available_body'=>'This transition is not available for the current record status.',
		'transition.completed'=>'{transition} completed.',
		'transition.bulk_unavailable'=>'Bulk transition unavailable',
		'transition.bulk_requires_selection'=>'Bulk transition requires selection',
		'transition.bulk_requires_selection_body'=>'Select records from the table before changing their status.',
		'transition.no_records_body'=>'Select at least one record before changing status.',
		'transition.bulk_changed'=>'{count} {record} changed to {status}.',
		'transition.bulk_unavailable_records'=>'{count} selected {record} could not use this transition.',
		'transition.bulk_failed'=>'{count} selected {record} could not be changed.',
		'transition.bulk_denied'=>'{count} selected {record} did not allow this transition.',
		'transition.bulk_none'=>'No selected records were changed.',
		'data.column_mapping'=>'Column mapping',
		'data.column_mapping_description'=>'Map CSV columns to resource fields before importing.',
		'data.no_rows_preview'=>'No rows to preview.',
		'data.rows'=>'Rows',
		'data.showing_records'=>'Showing {start} to {end} of {total}',
		'data.page_count'=>'Page {page} of {pages}',
		'data.record'=>'Record',
		'data.no_records_available'=>'No records available',
		'data.no_related_records'=>'No related records to show.',
		'data.update_pivot'=>'Update pivot',
		'data.previous'=>'Previous',
		'data.next'=>'Next',
		'data.preview_limit'=>'Showing 20 of {count} rows.',
		'data.view'=>'View',
		'data.view_record_title'=>'View {record}',
		'data.view_record_description'=>'Review this related record without leaving the parent record.',
		'data.relation_attach_description'=>'{action} an existing record without leaving the parent context.',
		'data.create_record_title'=>'Create {resource}',
		'data.create_record_description'=>'Create the related record without leaving this relationship view.',
		'data.reorder_description'=>'Update the order of related records without leaving the parent context.',
		'data.row_not_importable'=>'Row is not importable.',
		'data.relation_unauthorized'=>'Current user is not authorized for this relation operation.',
		'data.relation_unavailable_operation'=>'Operation is not available for this relation.',
		'data.edit_join_metadata'=>'Edit join metadata for this related record.',
		'uploader.browse'=>'Choose files',
		'uploader.drop_title'=>'Drop files here',
		'uploader.drop_help'=>'Uploads show transfer status, errors, chunk progress, and retry recovery.',
		'uploader.status_empty'=>'No files queued.',
		'uploader.policy_types'=>'Types',
		'uploader.policy_max'=>'Max',
		'uploader.policy_max_value'=>'{size} per file',
		'uploader.policy_files'=>'Files',
		'uploader.files_at_least'=>'At least {count}',
		'uploader.files_optional'=>'Optional',
		'uploader.files_up_to'=>'up to {count}',
		'uploader.policy_transfer'=>'Transfer',
		'uploader.policy_transfer_value'=>'{chunk_size} chunks, {retries} retries, {concurrency} at a time',
		'uploader.policy_storage'=>'Storage',
		'uploader.storage_default'=>'local',
		'uploader.accepted_wildcard'=>'{type} files',
		'uploader.accepted_extension'=>'{extension}',
		'uploader.accepted_mime'=>'{mime}',
		'uploader.status_complete'=>'{complete} of {total} complete',
		'uploader.status_failed'=>'{failed} failed',
		'uploader.status_uploading'=>'uploading',
		'uploader.constraint_min'=>'Add at least {count} {file}.',
		'uploader.constraint_max'=>'Remove files until only {count} {remain}.',
		'uploader.file_singular'=>'file',
		'uploader.file_plural'=>'files',
		'uploader.remain_singular'=>'remains',
		'uploader.remain_plural'=>'remain',
		'uploader.delete_failed_http'=>'Delete failed with HTTP {status}',
		'uploader.delete_network_error'=>'Delete network error.',
		'uploader.uploaded_file'=>'Uploaded file',
		'uploader.queued'=>'Queued',
		'uploader.move_up'=>'Move up',
		'uploader.move_down'=>'Move down',
		'uploader.up'=>'Up',
		'uploader.down'=>'Down',
		'uploader.retry'=>'Retry',
		'uploader.remove'=>'Remove',
		'uploader.stored_file'=>'Stored file',
		'uploader.file_removed'=>'File removed.',
		'uploader.removing'=>'Removing',
		'uploader.remove_failed'=>'Remove failed.',
		'uploader.upload_no_endpoint'=>'No upload endpoint configured.',
		'uploader.uploading_percent'=>'Uploading {percent}%',
		'uploader.upload_failed_http'=>'Upload failed with HTTP {status}',
		'uploader.upload_network_error'=>'Upload network error.',
		'uploader.upload_cancelled'=>'Upload cancelled.',
		'uploader.upload_aborted'=>'Upload aborted.',
		'uploader.retry_of'=>'Retry {attempt} of {retries}',
		'uploader.uploading_file'=>'Uploading {file}.',
		'uploader.waiting_slot'=>'Waiting for transfer slot.',
		'uploader.chunk_stored'=>'Chunk {index} of {total} stored.',
		'uploader.complete'=>'Complete',
		'uploader.stored_at'=>'Stored at {path}',
		'uploader.stored_ready'=>'Stored and ready to submit.',
		'uploader.cancelled'=>'Cancelled',
		'uploader.cancel_detail'=>'Transfer cancelled before completion.',
		'uploader.upload_failed'=>'Upload failed',
		'uploader.retry_available'=>'Retry is available if the file still matches policy.',
		'uploader.too_large'=>'Too large',
		'uploader.too_large_detail'=>'{size} exceeds the {limit} limit.',
		'uploader.too_large_status'=>'{file} is too large. Accepted: {policy}.',
		'uploader.configured_policy'=>'configured policy',
		'uploader.type_not_accepted'=>'Type not accepted',
		'uploader.type_not_accepted_detail'=>'Accepted types: {types}.',
		'uploader.type_not_accepted_status'=>'{file} is not an accepted file type.',
		'uploader.remove_before_add'=>'Remove a file before adding another.',
		'uploader.only_more'=>'Only {count} more {file} can be added.',
		'uploader.transfer_detail'=>'{sent} of {size} - chunk {index} of {total}{speed}',
		'uploader.transfer_speed'=>' at {speed}/s',
		'search.no_chart_data'=>'No chart data',
		'search.no_matches_title'=>'No matches yet.',
		'search.no_matches_body'=>'Try a broader term, check another resource, or clear the search to return to the full workspace.',
		'search.clear'=>'Clear search',
		'search.results'=>'Search results',
		'search.result'=>'result',
		'search.ready_headline'=>'Search is ready to follow.',
		'search.empty_headline'=>'No records surfaced for this search.',
		'search.ready_message'=>'Open a result directly, or refine the term to narrow the workspace.',
		'search.empty_message'=>'Try a broader term or jump into a resource from the navigation below.',
		'search.view_title'=>'View {record}',
		'search.view_description'=>'Review this search result without leaving the workspace.',
		'search.open_workspace'=>'Open this workspace',
		'panel.ready_title'=>'This panel is ready.',
		'panel.ready_body'=>'Register pages and resources to turn it into a working operations surface.',
		'panel.custom_blocks_title'=>'This surface is assembled from reusable panel blocks.',
		'panel.custom_blocks_body'=>'Use the actions, widgets, tables, and content sections together instead of sending operators across separate screens.',
		'panel.widget'=>'widget',
		'panel.widgets'=>'widgets',
		'panel.table'=>'table',
		'panel.tables'=>'tables',
		'page.ready_title'=>'This page is ready for content.',
		'page.ready_body'=>'Add sections, widgets, tables, or custom HTML to make this surface useful.',
		'page.focused_workspace_title'=>'Use this surface as a focused workspace.',
		'page.focused_workspace_body'=>'Pages can combine actions, widgets, scoped tables, and custom content without depending on a hardcoded route.',
		'table.ready_title'=>'This table is ready for focused work.',
		'table.first_records_title'=>'This table is ready for its first records.',
		'table.ready_body'=>'Use views, filters, columns, and bulk actions to turn the dataset into a working queue.',
		'table.first_records_body'=>'Create or import records and the table controls will become useful immediately.',
		'table.view_detail'=>'View: {view}',
		'table.all_records'=>'All records',
		'table.board_pulse'=>'Board pulse',
		'table.board_records'=>'Records',
		'table.board_lanes'=>'Lanes',
		'table.board_largest_lane'=>'Largest lane',
		'table.board_movable_cards'=>'Movable cards',
		'table.board_records_supplied'=>'Supplied to this board by the caller.',
		'table.board_records_visible'=>'Records currently visible after search and filters.',
		'table.board_lane_empty'=>'{count} lane empty.',
		'table.board_lanes_empty'=>'{count} lanes empty.',
		'table.board_every_lane_busy'=>'Every lane has work in it.',
		'table.board_largest_lane_busy'=>'This is where the board is most concentrated.',
		'table.board_no_lane_records'=>'No lane has records yet.',
		'table.board_movable_cards_available'=>'These cards expose allowed transitions.',
		'table.board_no_movable_cards'=>'No visible card can move from this board.',
		'table.board_no_cards_match_title'=>'No cards match this board slice.',
		'table.board_no_cards_match_body'=>'Clear the search or filters to see whether work is hidden outside this narrowed view.',
		'table.board_first_cards_title'=>'This board is ready for its first cards.',
		'table.board_first_cards_body'=>'Create a record or adjust the resource states when work should start flowing through these lanes.',
		'table.board_move_cards_title'=>'Move the cards that can progress.',
		'table.board_move_cards_body'=>'Cards with available transitions can be dragged into allowed lanes or moved with their action buttons.',
		'table.board_quiet_lanes_title'=>'Some lanes are quiet.',
		'table.board_quiet_lanes_body'=>'Compare the full lanes with the empty ones to see where workflow pressure is collecting.',
		'table.board_focused_title'=>'You are viewing a focused board.',
		'table.board_focused_body'=>'Use this narrowed lane picture for triage, then reset filters before judging overall flow.',
		'table.board_balanced_title'=>'The board is balanced for review.',
		'table.board_balanced_body'=>'Open cards for detail, or switch back to the table when you need sorting and bulk actions.',
		'table.export_csv'=>'Export CSV',
		'table.export_json'=>'Export JSON',
		'table.previous'=>'Previous',
		'table.next'=>'Next',
		'table.pages'=>'Pages',
		'table.empty_filtered_title'=>'No records fit this view.',
		'table.empty_filtered_body'=>'Broaden the search, loosen a filter, or reset the view to let more records surface.',
		'table.reset_view'=>'Reset view',
		'table.empty_ready_title'=>'The table is ready.',
		'table.empty_create_first'=>'Create the first record and this surface will begin filling itself with sortable, searchable data.',
		'table.empty_records_available'=>'You can view this resource once records are available.',
		'table.create_resource_title'=>'Create {resource}',
		'table.create_resource_body'=>'Add the details, then save when you are ready.',
		'table.create'=>'Create',
		'table.save_field'=>'Save {field}',
		'table.update_record_context'=>'Update this record without losing the table context.',
		'table.review_record_context'=>'Review this record without losing the table context.',
		'table.update_record_same_view'=>'Update this record in place, then return to the same view.',
		'table.update_record_same_table'=>'Update this record in place, then return to the same table view.',
		'page.table_empty_filtered_custom_body'=>'Adjust this table search, filters, or view to bring records back into focus.',
		'page.table_empty_filtered_title'=>'No records match this table view.',
		'page.table_empty_filtered_body'=>'Broaden the search, loosen a filter, or switch views to widen the signal.',
		'page.table_empty_ready_title'=>'This table is ready.',
		'page.table_empty_ready_body'=>'Once records arrive, this section will inherit search, filters, views, and summaries automatically.',
		'page.board_view_record_body'=>'Review this record without losing the board context.',
		'page.board_no_records'=>'No records',
		'page.board_unmatched_status'=>'Unmatched status',
		'page.record_pulse'=>'Record pulse',
		'page.record_identity'=>'Identity',
		'page.record_identity_hint'=>'Stable reference for this record.',
		'page.record_state'=>'State',
		'page.record_not_labelled'=>'Not labelled',
		'page.record_state_hint'=>'Current lifecycle signal.',
		'page.record_state_missing_hint'=>'Add a status field when this resource needs visible workflow state.',
		'page.record_owner'=>'Owner',
		'page.record_unassigned'=>'Unassigned',
		'page.record_owner_hint'=>'Best person or party to contact first.',
		'page.record_owner_missing_hint'=>'Ownership will appear here when the resource exposes it.',
		'page.record_last_movement'=>'Last movement',
		'page.record_no_timestamp'=>'No timestamp',
		'page.record_last_movement_hint'=>'Most recent timestamp found on the record.',
		'page.record_last_movement_missing_hint'=>'Expose updated_at or activity to make freshness obvious.',
		'page.update_record'=>'Update record',
		'page.edit_record_title'=>'Edit {record}',
		'page.edit_record_from_show'=>'Update this record without leaving the read-only view.',
		'page.pulse_alert_title'=>'Start with the active attention item.',
		'page.pulse_alert_body'=>'This record has an alert, so resolve or acknowledge that before polishing the rest of the details.',
		'page.pulse_approval_title'=>'Review the approval path.',
		'page.pulse_approval_body'=>'A decision surface is present. Confirm what changed, then approve or reject from the record itself.',
		'page.pulse_task_title'=>'Work the next task.',
		'page.pulse_task_body'=>'Tasks are already attached, so the cleanest move is to complete or refine the next visible step.',
		'page.pulse_message_title'=>'Check the communication trail.',
		'page.pulse_message_body'=>'Messages are close to the record, making it easy to continue the conversation with context intact.',
		'page.pulse_activity_title'=>'Read the recent movement.',
		'page.pulse_activity_body'=>'Activity and changes are available here, so you can understand what shifted before taking action.',
		'page.pulse_relations_title'=>'Inspect the related records.',
		'page.pulse_relations_body'=>'Relationship tables are attached. Use them to understand the record in its surrounding workflow.',
		'page.pulse_ready_title'=>'The record is ready for review.',
		'page.pulse_ready_body'=>'Core details are visible. Add notes, tasks, messages, or attachments as the workflow becomes clearer.',
		'page.action_group'=>'Actions',
		'page.action_stopped'=>'The action was stopped.',
		'page.action_lifecycle_completed'=>'The action lifecycle completed.',
		'page.action_stopped_title'=>'Action stopped',
		'page.action_lifecycle_title'=>'Action lifecycle',
		'form.pulse'=>'Form pulse',
		'form.mode'=>'Mode',
		'form.mode_edit'=>'Edit existing',
		'form.mode_create'=>'Create new',
		'form.mode_edit_hint'=>'Changes will update this record.',
		'form.mode_create_hint'=>'Saving will create a new record.',
		'form.fields'=>'Fields',
		'form.fields_visible'=>'{count} visible',
		'form.fields_hidden'=>'{count} hidden by schema or operation.',
		'form.required'=>'Required',
		'form.conditional_one'=>'{count} conditional field can react while editing.',
		'form.conditional_many'=>'{count} conditional fields can react while editing.',
		'form.fix_highlighted_title'=>'Fix the highlighted fields first.',
		'form.fix_highlighted_body'=>'The form is already telling you where save would fail, so resolve those issues before changing anything else.',
		'form.reactive_title'=>'This form can respond as you edit.',
		'form.reactive_body'=>'Some fields are conditional, so choices may reveal, hide, or require more details before saving.',
		'form.dynamic_title'=>'Some values are resolved dynamically.',
		'form.dynamic_body'=>'Field options, hydration, dehydration, or validation may adapt to the current record and request.',
		'form.review_save_title'=>'Review, adjust, and save.',
		'form.review_save_body'=>'Only change what needs to move; record context remains available after saving.',
		'form.create_essentials_title'=>'Fill the essentials, then create the record.',
		'form.create_essentials_body'=>'Required fields define the minimum shape. Optional sections can be completed when the workflow needs them.',
		'form.create_title'=>'Create a clean {resource}.',
		'form.create_body'=>'Required fields are marked, dependent fields adjust as you work, and file inputs will be included automatically.',
		'form.update_title'=>'Update this {resource} with context.',
		'form.update_body'=>'Unsaved changes are tracked, validation points to the field that needs attention, and the save action will protect against duplicate submits.',
		'form.no_repeater_fields'=>'No repeater fields are defined.',
		'form.no_fields'=>'No fields are defined for this resource.',
		'form.no_visible_fields'=>'No visible fields are defined for this resource.',
		'form.no_items'=>'No items',
		'show.review_title'=>'Review the record before acting.',
		'show.review_body'=>'Record actions, related sections, attachments, messages, notes, and activity all stay close to the thing being reviewed.',
		'import.guidance_title'=>'Import {resource} without guessing.',
		'import.guidance_body'=>'Upload a file or paste rows; the preview checks shape and mapping before anything is saved.',
		'import.resolve_title'=>'Resolve import issues before saving.',
		'import.clean_title'=>'The import preview is clean.',
		'import.resolve_body'=>'Review the highlighted rows, adjust the CSV, then refresh the preview.',
		'import.clean_body'=>'Confirm the import when the parsed rows match what you expect.',
		'action.context_title'=>'Confirm the operation with the right context.',
		'action.context_body'=>'Panel actions keep selection, validation, confirmation, and return paths together so operators can move quickly.',
		'action.saved'=>'Saved.',
		'action.save_failed'=>'The record could not be saved.',
		'action.created'=>'Created',
		'action.updated'=>'Updated',
		'action.inline_requires_post'=>'Inline updates require POST.',
		'action.column_not_editable'=>'This column is not editable.',
		'action.default_label'=>'Action',
		'action.not_available_now'=>'This action is not available right now.',
		'action.failed_title'=>'{action} failed',
		'action.failed_body'=>'The action could not be completed.',
		'action.operation_stopped'=>'The operation was stopped.',
		'action.lifecycle_completed'=>'The lifecycle completed.',
		'action.operation_stopped_title'=>'Operation stopped',
		'action.lifecycle_result_title'=>'Lifecycle result',
		'bulk.duplicate_unavailable'=>'Bulk duplicate unavailable',
		'bulk.duplicate_requires_confirmation'=>'Bulk duplicate requires confirmation',
		'bulk.duplicate_requires_confirmation_body'=>'Use the generated bulk duplicate button to confirm this operation.',
		'bulk.duplicate_no_records_body'=>'Select at least one record before duplicating.',
		'bulk.restore_unavailable'=>'Bulk restore unavailable',
		'bulk.restore_requires_confirmation'=>'Bulk restore requires confirmation',
		'bulk.restore_requires_confirmation_body'=>'Use the generated bulk restore button to confirm this operation.',
		'bulk.restore_no_records_body'=>'Select at least one record before restoring.',
		'bulk.update_unavailable'=>'Bulk update unavailable',
		'bulk.update_unavailable_body'=>'This resource does not define bulk update fields or a save handler.',
		'bulk.update_requires_selection'=>'Bulk update requires selection',
		'bulk.update_requires_selection_body'=>'Select records from the table before updating them.',
		'bulk.update_no_records_body'=>'Select at least one record before updating.',
		'bulk.delete_unavailable'=>'Bulk delete unavailable',
		'bulk.delete_requires_confirmation'=>'Bulk delete requires confirmation',
		'bulk.delete_requires_confirmation_body'=>'Use the generated bulk delete button to confirm this operation.',
		'bulk.delete_no_records_body'=>'Select at least one record before deleting.',
		'bulk.force_delete_unavailable'=>'Bulk permanent delete unavailable',
		'bulk.force_delete_requires_confirmation'=>'Bulk permanent delete requires confirmation',
		'bulk.force_delete_requires_confirmation_body'=>'Use the generated bulk permanent delete button to confirm this operation.',
		'bulk.force_delete_no_records_body'=>'Select at least one record before permanently deleting.',
		'bulk.duplicated'=>'{count} {record} duplicated.',
		'bulk.duplicate_failed'=>'{count} selected {record} could not be duplicated.',
		'bulk.duplicate_denied'=>'{count} selected {record} did not allow duplicate.',
		'bulk.duplicate_none'=>'No selected records were duplicated.',
		'bulk.restored'=>'{count} {record} restored.',
		'bulk.restore_failed'=>'{count} selected {record} could not be restored.',
		'bulk.restore_denied'=>'{count} selected {record} did not allow restore.',
		'bulk.restore_none'=>'No selected records were restored.',
		'bulk.updated'=>'{count} {record} updated.',
		'bulk.deleted'=>'{count} {record} deleted.',
		'bulk.delete_failed'=>'{count} selected {record} could not be deleted.',
		'bulk.delete_denied'=>'{count} selected {record} did not allow delete.',
		'bulk.delete_none'=>'No selected records were deleted.',
		'bulk.force_deleted'=>'{count} {record} permanently deleted.',
		'bulk.force_delete_failed'=>'{count} selected {record} could not be permanently deleted.',
		'bulk.force_delete_denied'=>'{count} selected {record} did not allow permanent delete.',
		'bulk.force_delete_none'=>'No selected records were permanently deleted.',
		'forbidden.title'=>'Forbidden',
		'forbidden.body'=>'You do not have access to this panel resource.',
		'table.board'=>'Board',
		'table.board_unavailable'=>'Board unavailable',
		'client.selection_cleared'=>'Selection cleared',
		'client.selected_record'=>'1 selected record',
		'client.selected_records'=>'{count} selected records',
		'client.visible_suffix'=>' of {total} visible',
		'client.active_filter'=>'1 active filter',
		'client.active_filters'=>'{count} active filters',
		'client.saved_prefix'=>'Saved: {label}',
		'client.no_saved_views'=>'No saved views yet.',
		'client.save_view'=>'Save view',
		'client.save_view_description'=>'Name the current filters, columns, sorting, grouping, and density.',
		'client.view_name'=>'View name',
		'client.saved_locally'=>'Saved locally for this browser and workspace.',
		'client.name_this_view'=>'Name this view',
		'client.unable_save_view'=>'Unable to save view',
		'client.saved_view_needs_name'=>'Saved view needs a name',
		'client.saved_view_added'=>'Saved view added',
		'client.this_view_not_saved'=>'This view is not saved',
		'client.saved_view_removed'=>'Saved view removed',
		'client.unable_remove_saved_view'=>'Unable to remove saved view',
		'client.no_saved_views_export'=>'No saved views to export',
		'client.saved_views_copied'=>'Saved views copied',
		'client.paste_saved_views_json'=>'Paste saved views JSON',
		'client.no_saved_views_found'=>'No saved views found',
		'client.saved_views_imported'=>'Saved views imported',
		'client.saved_views_json_invalid'=>'Saved views JSON was not valid',
		'client.keyboard_shortcuts'=>'Keyboard shortcuts',
		'client.preview_row'=>'Preview row',
		'client.pin'=>'Pin',
		'client.pinned'=>'Pinned',
		'client.paused'=>'Paused',
		'client.live'=>'Live',
		'client.resume'=>'Resume',
		'client.pause'=>'Pause',
		'client.auto_refresh'=>'Auto refresh',
		'client.live_refresh_failed'=>'Live refresh failed with status {status}',
		'client.live_updates'=>'Live updates',
		'client.refresh_panel_now'=>'Refresh this panel now',
		'client.pause_live_updates'=>'Pause live updates',
		'client.resume_live_updates'=>'Resume live updates',
		'client.ready'=>'Ready',
		'client.updated_now'=>'Updated now',
		'client.updated_at'=>'Updated {time}',
		'client.retry_seconds'=>'Retrying in {seconds}s',
		'client.retry_minutes'=>'Retrying in {minutes}m',
		'client.editing_paused'=>'Editing paused',
		'client.resuming_updates'=>'Resuming updates',
		'client.no_changes'=>'No changes',
		'client.back_online'=>'Back online',
		'client.offline'=>'Offline',
		'client.live_updates_label'=>'Live updates: {label}',
		'client.resume_region'=>'Resume this region',
		'client.pause_region'=>'Pause this region',
		'client.leave_unsaved_title'=>'Leave with unsaved changes?',
		'client.leave_unsaved_description'=>'Your current changes have not been saved. Stay here to keep editing, or leave and discard them.',
		'client.stay_here'=>'Stay here',
		'client.leave_anyway'=>'Leave anyway',
		'client.working'=>'Working...',
		'client.record_selected'=>'record selected',
		'client.records_selected'=>'records selected',
		'client.all_visible_records'=>'All visible records',
		'client.visible_records'=>'Visible records',
		'client.no_tags'=>'No tags',
		'client.no_pairs'=>'No pairs',
		'client.more_count'=>'+{count} more',
		'client.editor_preview_empty'=>'Preview appears after content is entered.',
		'client.editor_status'=>'{mode} | {words} words | {chars} chars',
		'client.heading'=>'Heading',
		'client.paragraph'=>'Paragraph',
		'editor.bold'=>'Bold',
		'editor.undo'=>'Undo',
		'editor.redo'=>'Redo',
		'editor.heading'=>'Heading',
		'editor.paragraph'=>'Paragraph',
		'editor.italic'=>'Italic',
		'editor.underline'=>'Underline',
		'editor.strikethrough'=>'Strikethrough',
		'editor.link'=>'Link',
		'editor.unlink'=>'Unlink',
		'editor.bulleted_list'=>'Bulleted list',
		'editor.list'=>'List',
		'editor.numbered_list'=>'Numbered list',
		'editor.quote'=>'Quote',
		'editor.code'=>'Code',
		'editor.divider'=>'Divider',
		'editor.clear_formatting'=>'Clear formatting',
		'editor.visual'=>'Visual',
		'editor.source'=>'Source',
		'editor.write'=>'Write',
		'editor.preview'=>'Preview',
		'editor.heading_1'=>'Heading 1',
		'editor.heading_2'=>'Heading 2',
		'editor.heading_3'=>'Heading 3',
		'editor.code_block'=>'Code block',
		'editor.live_preview'=>'Live preview',
		'editor.start_writing'=>'Start writing...',
		'client.wait_uploads'=>'Wait for uploads to finish before saving.',
		'client.accessibility_title'=>'Dataphyre Panel Accessibility',
		'client.accessibility_why'=>'Why this happened',
		'client.accessibility_carry_code'=>'Carry into code',
		'client.accessibility_production'=>'Accessibility remains silently enforced in production.',
		'client.accessibility_nested_card'=>'Nested card wrapper',
		'client.accessibility_table'=>'Table',
		'client.a11y_width_expanded'=>'Field expanded to satisfy usable width policy.',
		'client.a11y_width_constrained'=>'Usable width {usable}px is below required {required}px{source}.',
		'client.a11y_char_policy_source'=>' from the configured character policy',
		'client.a11y_contrast_fail'=>'Contrast ratio {ratio} is below the configured contrast policy.',
		'client.a11y_touch_target_one'=>'{count} touch target is below the configured minimum size.',
		'client.a11y_touch_target_many'=>'{count} touch targets are below the configured minimum size.',
		'client.a11y_adornment_expanded'=>'Field expanded to reduce adornment pressure.',
		'client.a11y_adornment_stacked'=>'Input adornments stacked to preserve usable control width.',
		'client.a11y_adornment_pressure'=>'Input adornments still exceed the configured pressure ratio.',
		'client.a11y_label_expanded'=>'Field expanded to reduce label pressure.',
		'client.a11y_label_stacked'=>'Label stacked to preserve usable control width.',
		'client.a11y_row_reflowed'=>'Field stayed in its row and was resized after a sibling moved out for accessibility.',
		'client.a11y_dom_reordered'=>'Field moved in DOM order after the siblings it displaced.',
		'client.a11y_card_flattened'=>'Redundant wrapper card flattened because it only contained another card surface.',
		'client.a11y_table_columns_optimized'=>'Table column widths optimized from measured header and cell content.',
		'client.a11y_table_columns_compacted'=>'Some table columns were compacted so high-value columns keep usable width.',
		'client.a11y_table_scroll_preserved'=>'Horizontal table scrolling was preserved because the table cannot fit without losing readability.',
		'client.a11y_title_width_constrained'=>'Width constrained',
		'client.a11y_title_width_expanded'=>'Width expanded',
		'client.a11y_title_contrast_fail'=>'Contrast failed',
		'client.a11y_title_touch_target_fail'=>'Touch target failed',
		'client.a11y_title_adornment_expanded'=>'Adornment expanded',
		'client.a11y_title_adornment_stacked'=>'Adornment stacked',
		'client.a11y_title_adornment_pressure'=>'Adornment pressure',
		'client.a11y_title_label_expanded'=>'Label expanded',
		'client.a11y_title_label_stacked'=>'Label stacked',
		'client.a11y_title_row_reflowed'=>'Row reflowed',
		'client.a11y_title_dom_reordered'=>'DOM reordered',
		'client.a11y_title_card_flattened'=>'Card flattened',
		'client.a11y_title_table_columns_optimized'=>'Table columns optimized',
		'client.a11y_title_table_columns_compacted'=>'Table columns compacted',
		'client.a11y_title_table_scroll_preserved'=>'Table scroll preserved',
		'client.a11y_fix_width_constrained'=>'Code fix: increase this field column span, reduce label/adornment/button pressure, or lower the configured min usable width/chars if the policy is too strict.',
		'client.a11y_fix_width_expanded'=>'Code fix: give this field more planned column span in the schema if this expansion is expected.',
		'client.a11y_fix_contrast_fail'=>'Code fix: adjust theme tokens, field colors, or contrast policy so text and control backgrounds meet the configured ratio.',
		'client.a11y_fix_touch_target_fail'=>'Code fix: increase icon button/control padding, use larger controls, or mark a deliberate compact-control exception.',
		'client.a11y_fix_adornment_expanded'=>'Code fix: plan a wider field span or simplify prepend/append controls.',
		'client.a11y_fix_adornment_stacked'=>'Code fix: replace secondary text buttons with icons or reduce adornments if the stacked layout feels noisy.',
		'client.a11y_fix_adornment_pressure'=>'Code fix: reduce adornments/buttons or increase the field span; the automatic recovery still could not satisfy the policy.',
		'client.a11y_fix_label_expanded'=>'Code fix: give this field more span or shorten/split the label/hint.',
		'client.a11y_fix_label_stacked'=>'Code fix: shorten the label/hint or accept stacked label layout for this field.',
		'client.a11y_fix_row_reflowed'=>'Code fix: rebalance the row in the schema so sibling fields have room after expanded fields move out.',
		'client.a11y_fix_dom_reordered'=>'Code fix: move this field to its own row or later schema position if that order is preferred permanently.',
		'client.a11y_fix_card_flattened'=>'Code fix: remove the extra wrapper card or move meaningful heading/actions/content into it.',
		'client.a11y_fix_table_columns_optimized'=>'Code fix: define table column width priorities, min/max widths, or responsive visibility rules if this optimized layout should become the default.',
		'client.a11y_fix_table_columns_compacted'=>'Code fix: shorten table labels/cell copy, hide lower-priority columns, or configure tighter min widths for compact columns.',
		'client.a11y_fix_table_scroll_preserved'=>'Code fix: reduce visible columns or add responsive column hiding if this table should fit without horizontal scroll.',
		'client.a11y_fix_default'=>'Code fix: encode the preferred layout or exception in the field/schema policy.',
		'nav.workspace'=>'Workspace',
		'nav.overview'=>'Overview',
		'nav.toggle_sidebar'=>'Toggle sidebar',
		'nav.open_navigation'=>'Open navigation',
		'nav.close_navigation'=>'Close navigation',
		'nav.panel_navigation'=>'Panel navigation',
		'nav.find'=>'Find in panel',
		'nav.find_aria'=>'Find in panel navigation',
		'nav.current'=>'Current',
		'nav.open'=>'Open {label}',
		'nav.next_step'=>'Next step',
		'theme.light'=>'Light',
		'theme.dark'=>'Dark',
		'theme.system'=>'System',
		'theme.mode'=>'Theme mode',
		'theme.selector'=>'Theme',
	];
	private const CLIENT_TEXT_KEYS=[
		'common.cancel',
		'common.clear',
		'common.close',
		'common.copy',
		'common.copied',
		'common.clear_all',
		'common.remove',
		'common.run',
		'copy.unable',
		'copy.value',
		'copy.current_url',
		'copy.current_url_done',
		'copy.rows',
		'copy.focused_row',
		'copy.selected_rows',
		'copy.visible_rows',
		'copy.no_rows',
		'copy.no_row_data',
		'nav.clear_pinned',
		'nav.pinned_cleared',
		'common.current_view',
		'common.default_slice',
		'common.reset',
		'common.apply',
		'common.previous',
		'common.next',
		'common.refresh',
		'common.export',
		'common.import',
		'common.snapshot',
		'common.restore',
		'modal.unsaved_close',
		'modal.unsaved_back',
		'modal.back',
		'modal.open_full_page',
		'modal.copy_link',
		'modal.expand',
		'modal.normal',
		'modal.action',
		'modal.link_copied',
		'modal.saving_changes',
		'modal.done_refreshing_workspace',
		'modal.done_updating_workspace',
		'modal.unexpected_response_retry',
		'modal.submit_failed_retry',
		'modal.opening',
		'modal.running_action',
		'modal.refresh_failed',
		'modal.confirm_action',
		'modal.run_action',
		'modal.working',
		'modal.loading_action',
		'modal.loading_action_context',
		'modal.review_highlighted',
		'modal.unexpected_response',
		'modal.unexpected_response_refresh',
		'search.workspace_placeholder',
		'search.records_aria',
		'client.command_palette',
		'client.jump_to_panel_item',
		'client.jump_to_placeholder',
		'client.no_results',
		'client.no_results_for',
		'client.command',
		'client.panel',
		'client.opens_link',
		'client.runs_command',
		'client.run',
		'client.shortcut',
		'client.enter',
		'client.esc',
		'client.toolbar',
		'client.bulk_action',
		'client.filter',
		'client.columns',
		'client.pagination',
		'client.action_menu',
		'client.record_action',
		'client.navigation',
		'client.view',
		'client.search',
		'client.action',
		'client.breadcrumb',
		'client.pinned_category',
		'client.recent',
		'client.saved_view',
		'client.selection',
		'client.focused_row',
		'client.filters',
		'table.filters',
		'table.filters_description',
		'client.no_selectable_rows',
		'client.row_selected',
		'client.rows_selected',
		'client.selection_inverted',
		'client.no_selected_rows',
		'client.no_focused_row',
		'client.no_primary_action',
		'client.focused_row_action',
		'client.no_row_actions',
		'client.record',
		'client.field',
		'client.steps',
		'client.copy_json',
		'client.copy_csv',
		'client.preview_position',
		'client.no_filters',
		'client.no_columns',
		'client.review_highlighted_fields',
		'client.column_resize_hint',
		'client.column_width_reset',
		'client.navigation_pinned',
		'client.navigation_unpinned',
		'client.no_active_navigation',
		'client.navigation_already_pinned',
		'client.navigation_not_pinned',
		'client.recent_navigation_cleared',
		'client.no_navigation_matches',
		'client.navigation_groups_expanded',
		'client.navigation_groups_collapsed',
		'client.action_in_progress',
		'client.action_refresh_failed',
		'client.action_complete_failed',
		'client.already_working',
		'client.inline_save_failed',
		'client.workspace_snapshot_prompt',
		'client.workspace_snapshot_restored',
		'client.workspace_snapshot_invalid',
		'client.link_url_prompt',
		'client.selection_cleared',
		'client.selected_record',
		'client.selected_records',
		'client.visible_suffix',
		'client.active_filter',
		'client.active_filters',
		'client.saved_prefix',
		'client.no_saved_views',
		'client.save_view',
		'client.save_view_description',
		'client.view_name',
		'client.saved_locally',
		'client.name_this_view',
		'client.unable_save_view',
		'client.saved_view_needs_name',
		'client.saved_view_added',
		'client.this_view_not_saved',
		'client.saved_view_removed',
		'client.unable_remove_saved_view',
		'client.no_saved_views_export',
		'client.saved_views_copied',
		'client.paste_saved_views_json',
		'client.no_saved_views_found',
		'client.saved_views_imported',
		'client.saved_views_json_invalid',
		'client.keyboard_shortcuts',
		'client.preview_row',
		'client.pin',
		'client.pinned',
		'client.paused',
		'client.live',
		'client.resume',
		'client.pause',
		'client.auto_refresh',
		'client.live_refresh_failed',
		'client.live_updates',
		'client.refresh_panel_now',
		'client.pause_live_updates',
		'client.resume_live_updates',
		'client.ready',
		'client.updated_now',
		'client.updated_at',
		'client.retry_seconds',
		'client.retry_minutes',
		'client.editing_paused',
		'client.resuming_updates',
		'client.no_changes',
		'client.back_online',
		'client.offline',
		'client.live_updates_label',
		'client.resume_region',
		'client.pause_region',
		'client.leave_unsaved_title',
		'client.leave_unsaved_description',
		'client.stay_here',
		'client.leave_anyway',
		'client.working',
		'client.record_selected',
		'client.records_selected',
		'client.all_visible_records',
		'client.visible_records',
		'client.no_tags',
		'client.no_pairs',
		'client.more_count',
		'client.editor_preview_empty',
		'client.editor_status',
		'client.heading',
		'client.paragraph',
		'editor.write',
		'editor.preview',
		'editor.source',
		'client.wait_uploads',
		'uploader.status_empty',
		'uploader.status_complete',
		'uploader.status_failed',
		'uploader.status_uploading',
		'uploader.files_up_to',
		'uploader.constraint_min',
		'uploader.constraint_max',
		'uploader.file_singular',
		'uploader.file_plural',
		'uploader.remain_singular',
		'uploader.remain_plural',
		'uploader.delete_failed_http',
		'uploader.delete_network_error',
		'uploader.uploaded_file',
		'uploader.queued',
		'uploader.move_up',
		'uploader.move_down',
		'uploader.up',
		'uploader.down',
		'uploader.retry',
		'uploader.remove',
		'uploader.stored_file',
		'uploader.file_removed',
		'uploader.removing',
		'uploader.remove_failed',
		'uploader.upload_no_endpoint',
		'uploader.uploading_percent',
		'uploader.upload_failed_http',
		'uploader.upload_network_error',
		'uploader.upload_cancelled',
		'uploader.upload_aborted',
		'uploader.retry_of',
		'uploader.uploading_file',
		'uploader.waiting_slot',
		'uploader.chunk_stored',
		'uploader.complete',
		'uploader.stored_at',
		'uploader.stored_ready',
		'uploader.cancelled',
		'uploader.cancel_detail',
		'uploader.upload_failed',
		'uploader.retry_available',
		'uploader.too_large',
		'uploader.too_large_detail',
		'uploader.too_large_status',
		'uploader.configured_policy',
		'uploader.type_not_accepted',
		'uploader.type_not_accepted_detail',
		'uploader.type_not_accepted_status',
		'uploader.remove_before_add',
		'uploader.only_more',
		'uploader.transfer_detail',
		'uploader.transfer_speed',
		'client.accessibility_title',
		'client.accessibility_why',
		'client.accessibility_carry_code',
		'client.accessibility_production',
		'client.accessibility_nested_card',
		'client.accessibility_table',
		'client.a11y_width_expanded',
		'client.a11y_width_constrained',
		'client.a11y_char_policy_source',
		'client.a11y_contrast_fail',
		'client.a11y_touch_target_one',
		'client.a11y_touch_target_many',
		'client.a11y_adornment_expanded',
		'client.a11y_adornment_stacked',
		'client.a11y_adornment_pressure',
		'client.a11y_label_expanded',
		'client.a11y_label_stacked',
		'client.a11y_row_reflowed',
		'client.a11y_dom_reordered',
		'client.a11y_card_flattened',
		'client.a11y_table_columns_optimized',
		'client.a11y_table_columns_compacted',
		'client.a11y_table_scroll_preserved',
		'client.a11y_title_width_constrained',
		'client.a11y_title_width_expanded',
		'client.a11y_title_contrast_fail',
		'client.a11y_title_touch_target_fail',
		'client.a11y_title_adornment_expanded',
		'client.a11y_title_adornment_stacked',
		'client.a11y_title_adornment_pressure',
		'client.a11y_title_label_expanded',
		'client.a11y_title_label_stacked',
		'client.a11y_title_row_reflowed',
		'client.a11y_title_dom_reordered',
		'client.a11y_title_card_flattened',
		'client.a11y_title_table_columns_optimized',
		'client.a11y_title_table_columns_compacted',
		'client.a11y_title_table_scroll_preserved',
		'client.a11y_fix_width_constrained',
		'client.a11y_fix_width_expanded',
		'client.a11y_fix_contrast_fail',
		'client.a11y_fix_touch_target_fail',
		'client.a11y_fix_adornment_expanded',
		'client.a11y_fix_adornment_stacked',
		'client.a11y_fix_adornment_pressure',
		'client.a11y_fix_label_expanded',
		'client.a11y_fix_label_stacked',
		'client.a11y_fix_row_reflowed',
		'client.a11y_fix_dom_reordered',
		'client.a11y_fix_card_flattened',
		'client.a11y_fix_table_columns_optimized',
		'client.a11y_fix_table_columns_compacted',
		'client.a11y_fix_table_scroll_preserved',
		'client.a11y_fix_default',
	];

	use PanelRendererPages;
	use PanelRendererImports;
	use PanelRendererActions;
	use PanelRendererBulkOperations;
	use PanelRendererShell;
	use PanelRendererRecordSections;
	use PanelRendererTables;
	use PanelRendererData;
	use PanelRendererForms;
	use PanelRendererAssets;

	/**
	 * Resolves localized panel copy with a deterministic fallback.
	 *
	 * @param string $key Translation key.
	 * @param array<string,string|int|float|bool|null> $parameters Placeholder parameters for translation.
	 * @param string|\Stringable|null $default Optional fallback text.
	 * @return string Localized panel text.
	 */
	private static function panelText(string $key, array $parameters=[], string|\Stringable|null $default=null): string {
		$fallback=$default ?? (self::TEXT_DEFAULTS[$key] ?? $key);
		try{
			$localization=PanelConfig::config('localization');
			if($localization!==null){
				return PanelLocalization::from($localization)->translate($key, $parameters, null, $fallback);
			}
			return Panel::trans($key, $parameters, null, $fallback);
		}
		catch(\Throwable){
			return PanelLocalization::make()->translate($key, $parameters, null, $fallback);
		}
	}

	/**
	 * Builds a simple localized empty-state panel page.
	 *
	 * @param string $titleKey Translation key for the page title.
	 * @param string $bodyKey Translation key for the empty-state body.
	 * @param array<string,mixed> $data Additional page data.
	 * @param int $status HTTP status associated with the page result.
	 * @param array<string,string|int|float|bool|null> $parameters Translation parameters shared by title and body.
	 * @return PanelPageResult Renderable panel page result.
	 */
	private static function panelEmptyPage(string $titleKey, string $bodyKey, array $data=[], int $status=200, array $parameters=[]): PanelPageResult {
		return self::page(self::panelText($titleKey, $parameters), '<p class="dp-panel-empty">'.self::e(self::panelText($bodyKey, $parameters)).'</p>', $data, $status);
	}

	/**
	 * Exports the client-side translation bundle used by panel JavaScript.
	 *
	 * @return array Locale, fallback locale, and translation key/value payload.
	 */
	private static function panelClientTranslations(): array {
		$translations=[];
		foreach(self::CLIENT_TEXT_KEYS as $key){
			$translations[$key]=self::panelText($key);
		}
		$localization=PanelLocalization::from(PanelConfig::config('localization'));
		return [
			'locale'=>$localization->locale(),
			'fallback_locale'=>$localization->fallbackLocale(),
			'translations'=>$translations,
		];
	}

}
