<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Access;

/**
 * Repository adapter for local access identities.
 *
 * AccessIdentityRepository bridges framework authentication flows to the project's
 * configured user store. Callback hooks can own every operation; otherwise the
 * repository falls back to configured SQL table/column names. The class normalizes
 * email identity, hashes passwords before persistence, and avoids trusting dynamic
 * table or column names unless they match conservative identifier patterns.
 */
final class AccessIdentityRepository {

	private static ?self $instance=null;

	/**
	 * Returns the shared identity repository instance.
	 *
	 * @return self Singleton repository using the current DP_ACCESS_CFG identity configuration.
	 */
	public static function instance(): self {
		return self::$instance ??= new self();
	}

	/**
	 * Clears the cached repository instance.
	 *
	 * @return void
	 */
	public static function flush(): void {
		self::$instance=null;
	}

	/**
	 * Finds a local user by normalized email address.
	 *
	 * Invalid emails are rejected before callback or SQL lookup. Callback results
	 * take precedence; SQL fallback uses configured table and email column only when
	 * both names pass identifier validation.
	 *
	 * @param string $email Candidate email address.
	 * @return mixed User record/model, or null when none is found.
	 */
	public function findByEmail(string $email): mixed {
		$email=strtolower(trim($email));
		if($email==='' || !filter_var($email, FILTER_VALIDATE_EMAIL)){
			return null;
		}
		if(null!==$result=$this->callback('find_by_email', [$email])){
			return $result;
		}
		$table=$this->usersTable();
		$column=$this->column('email_column', 'email');
		if($table===null || $column===null || function_exists('sql_select')===false){
			return null;
		}
		return sql_select('*', $table, 'WHERE '.$column.'=?', [$email], false, false) ?: null;
	}

	/**
	 * Finds a local user by application identifier.
	 *
	 * @param int|string $id Local user identifier.
	 * @return mixed User record/model, or null when none is found.
	 */
	public function findById(int|string $id): mixed {
		if(null!==$result=$this->callback('find_by_id', [$id])){
			return $result;
		}
		$table=$this->usersTable();
		$column=$this->column('id_column', 'id');
		if($table===null || $column===null || function_exists('sql_select')===false){
			return null;
		}
		return sql_select('*', $table, 'WHERE '.$column.'=?', [$id], false, false) ?: null;
	}

	/**
	 * Creates a local user identity from normalized registration attributes.
	 *
	 * The SQL fallback writes only configured identity fields. Passwords are hashed
	 * with password_hash() before storage, and created_at is generated by PHP when
	 * the configured column is available.
	 *
	 * @param array<string, mixed> $attributes Registration attributes such as email, name, and password.
	 * @return mixed Created/reloaded user record, or null when creation is unavailable or fails.
	 */
	public function create(array $attributes): mixed {
		if(null!==$result=$this->callback('create', [$attributes])){
			return $result;
		}
		$table=$this->usersTable();
		if($table===null || function_exists('sql_insert')===false){
			return null;
		}
		$emailColumn=$this->column('email_column', 'email');
		$nameColumn=$this->column('name_column', 'name');
		$passwordColumn=$this->passwordColumn();
		$createdAtColumn=$this->column('created_at_column', 'created_at');
		$fields=[];
		if($emailColumn!==null){
			$fields[$emailColumn]=strtolower(trim((string)($attributes['email'] ?? '')));
		}
		if($nameColumn!==null && array_key_exists('name', $attributes)){
			$fields[$nameColumn]=trim((string)$attributes['name']);
		}
		if($passwordColumn!==null && isset($attributes['password'])){
			$fields[$passwordColumn]=password_hash((string)$attributes['password'], PASSWORD_DEFAULT);
		}
		if($createdAtColumn!==null){
			$fields[$createdAtColumn]=date('Y-m-d H:i:s');
		}
		if($fields===[] || sql_insert($table, $fields, null, true)===false){
			return null;
		}
		return isset($fields[$emailColumn]) ? $this->findByEmail((string)$fields[$emailColumn]) : null;
	}

	/**
	 * Verifies a plaintext password against the local identity.
	 *
	 * Callback verification can implement external providers or custom hash schemes.
	 * The SQL/default path reads the configured password hash field and uses
	 * password_verify().
	 *
	 * @param mixed $user User record/model to verify.
	 * @param string $password Plaintext password supplied by the login attempt.
	 * @return bool True when the password matches the stored credential.
	 */
	public function verifyPassword(mixed $user, string $password): bool {
		if(null!==$result=$this->callback('verify_password', [$user, $password])){
			return (bool)$result;
		}
		$hash=$this->value($user, $this->passwordColumn());
		return is_string($hash) && $hash!=='' && password_verify($password, $hash);
	}

	/**
	 * Replaces the user's stored password hash.
	 *
	 * The SQL fallback requires a configured users table, password column, id column,
	 * resolved identifier, and sql_update(). The plaintext password is never stored.
	 *
	 * @param mixed $user User record/model whose password should change.
	 * @param string $password New plaintext password to hash.
	 * @return bool True when the password hash is persisted.
	 */
	public function setPassword(mixed $user, string $password): bool {
		if(null!==$result=$this->callback('set_password', [$user, $password])){
			return (bool)$result;
		}
		$table=$this->usersTable();
		$passwordColumn=$this->passwordColumn();
		$idColumn=$this->column('id_column', 'id');
		$id=$this->identifier($user);
		if($table===null || $passwordColumn===null || $idColumn===null || $id===null || function_exists('sql_update')===false){
			return false;
		}
		return sql_update($table, [$passwordColumn=>password_hash($password, PASSWORD_DEFAULT)], 'WHERE '.$idColumn.'=?', [$id], true)!==false;
	}

	/**
	 * Marks a user's email identity as verified.
	 *
	 * The SQL fallback updates whichever verification columns are configured:
	 * boolean email_verified, timestamp email_verified_at, or both.
	 *
	 * @param mixed $user User record/model to mark as verified.
	 * @return bool True when verification state is persisted.
	 */
	public function markEmailVerified(mixed $user): bool {
		if(null!==$result=$this->callback('mark_email_verified', [$user])){
			return (bool)$result;
		}
		$table=$this->usersTable();
		$idColumn=$this->column('id_column', 'id');
		$id=$this->identifier($user);
		if($table===null || $idColumn===null || $id===null || function_exists('sql_update')===false){
			return false;
		}
		$fields=[];
		if(null!==$column=$this->column('email_verified_column', 'email_verified')){
			$fields[$column]=true;
		}
		if(null!==$column=$this->column('email_verified_at_column', 'email_verified_at')){
			$fields[$column]=date('Y-m-d H:i:s');
		}
		return $fields!==[] && sql_update($table, $fields, 'WHERE '.$idColumn.'=?', [$id], true)!==false;
	}

	/**
	 * Extracts the local authentication identifier from a user value.
	 *
	 * @param mixed $user User array/object/model.
	 * @return int|string|null Identifier accepted by guard/session code, or null when unavailable.
	 */
	public function identifier(mixed $user): int|string|null {
		if(null!==$result=$this->callback('identifier', [$user])){
			return is_int($result) || is_string($result) ? $result : null;
		}
		$value=$this->value($user, $this->column('id_column', 'id'));
		return is_int($value) || is_string($value) ? $value : null;
	}

	/**
	 * Extracts and normalizes the user's email address.
	 *
	 * @param mixed $user User array/object/model.
	 * @return string|null Lowercase valid email, or null when unavailable.
	 */
	public function email(mixed $user): ?string {
		$value=$this->value($user, $this->column('email_column', 'email'));
		return is_string($value) && filter_var($value, FILTER_VALIDATE_EMAIL) ? strtolower($value) : null;
	}

	/**
	 * Extracts the user's display name.
	 *
	 * @param mixed $user User array/object/model.
	 * @return string Trimmed display name, or an empty string when unavailable.
	 */
	public function name(mixed $user): string {
		$value=$this->value($user, $this->column('name_column', 'name'));
		return is_scalar($value) ? trim((string)$value) : '';
	}

	/**
	 * Checks whether a user's email identity is verified.
	 *
	 * Truthy boolean-style values or a non-empty verification timestamp both count
	 * as verified.
	 *
	 * @param mixed $user User array/object/model.
	 * @return bool True when local identity data says the email is verified.
	 */
	public function emailVerified(mixed $user): bool {
		if(null!==$result=$this->callback('email_verified', [$user])){
			return (bool)$result;
		}
		$verified=$this->value($user, $this->column('email_verified_column', 'email_verified'));
		$verifiedAt=$this->value($user, $this->column('email_verified_at_column', 'email_verified_at'));
		return in_array($verified, [true, 1, '1', 'true', 't', 'yes'], true)
			|| (is_string($verifiedAt) && trim($verifiedAt)!=='');
	}

	/**
	 * Reports whether local registration has a configured creation path.
	 *
	 * @return bool True when a create callback exists or a valid users table is configured.
	 */
	public function canRegister(): bool {
		return is_callable($this->config('callbacks.create')) || $this->usersTable()!==null;
	}

	/**
	 * Resolves the configured password hash column.
	 *
	 * @return string|null Password hash column name, or null when disabled/invalid.
	 */
	private function passwordColumn(): ?string {
		$hashColumn=$this->column('password_hash_column', null);
		return $hashColumn ?? $this->column('password_column', 'password');
	}

	/**
	 * Resolves and validates the configured users table name.
	 *
	 * @return string|null SQL table name, optionally schema-qualified, or null when invalid.
	 */
	private function usersTable(): ?string {
		$table=trim((string)$this->config('users_table', ''));
		return $table!=='' && preg_match('/^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)?$/', $table)===1 ? $table : null;
	}

	/**
	 * Resolves and validates a configured SQL column name.
	 *
	 * @param string $key Identity config key.
	 * @param string|null $default Default column name when the config key is absent.
	 * @return string|null Safe SQL column identifier, or null when disabled/invalid.
	 */
	private function column(string $key, ?string $default): ?string {
		$value=$this->config($key, $default);
		if($value===null){
			return null;
		}
		$value=trim((string)$value);
		return $value!=='' && preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $value)===1 ? $value : null;
	}

	/**
	 * Reads a configured field from arrays, public object properties, or getters.
	 *
	 * @param mixed $user User array/object/model.
	 * @param string|null $key Field name to read.
	 * @return mixed Field value, or null when unavailable.
	 */
	private function value(mixed $user, ?string $key): mixed {
		if($key===null || $key===''){
			return null;
		}
		if(is_array($user)){
			return $user[$key] ?? null;
		}
		if(is_object($user)){
			if(isset($user->{$key})){
				return $user->{$key};
			}
			$method='get'.str_replace(' ', '', ucwords(str_replace('_', ' ', $key)));
			if(method_exists($user, $method)){
				return $user->{$method}();
			}
		}
		return null;
	}

	/**
	 * Invokes a configured identity callback when present.
	 *
	 * @param string $name Callback name under identity.callbacks.
	 * @param array<int, mixed> $arguments Arguments passed to the callback.
	 * @return mixed Callback result, or null when no callback is configured.
	 */
	private function callback(string $name, array $arguments): mixed {
		$callback=$this->config('callbacks.'.$name);
		if(is_callable($callback)){
			return $callback(...$arguments);
		}
		return null;
	}

	/**
	 * Reads a dotted key from DP_ACCESS_CFG identity configuration.
	 *
	 * @param string $key Dotted identity config key.
	 * @param mixed $default Value returned when the key is absent.
	 * @return mixed identity configuration value from the dotted path, or the caller default when absent.
	 */
	private function config(string $key, mixed $default=null): mixed {
		$config=\defined('DP_ACCESS_CFG') && \is_array(\DP_ACCESS_CFG) ? (DP_ACCESS_CFG['identity'] ?? []) : [];
		$current=$config;
		foreach(explode('.', $key) as $segment){
			if(!is_array($current) || !array_key_exists($segment, $current)){
				return $default;
			}
			$current=$current[$segment];
		}
		return $current;
	}
}
