<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);
namespace Dataphyre\Panel;

/** Instance-scoped deterministic registry of trusted data-only Studio schemas. */
final class PanelStudioSchemaRegistry implements \JsonSerializable {
	public const REGISTRY_CONTRACT_VERSION=3;
	/** @var array<string,array{schema:PanelStudioComponentSchema,provider:string,provider_version:string}> */ private array $entries=[];
	private ?string $fingerprintCache=null;
	public function __construct(private readonly string $version='1.0.0'){
		if(preg_match('/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$/',$version)!==1){throw new \InvalidArgumentException('Studio registry versions must be safe identifiers.');}
	}
	public static function defaults(string $version='1.0.0'):self{
		$registry=new self($version);foreach(self::defaultSchemas()as$schema){$registry=$registry->withSchema($schema,'dataphyre.panel','3.0.0');}return$registry;
	}
	public function withSchema(PanelStudioComponentSchema $schema,string $provider='host',string $providerVersion='1.0.0',string $conflict='reject'):self{
		self::provider($provider,'provider');self::provider($providerVersion,'provider version');if(!in_array($conflict,['reject','replace_same_provider'],true)){throw new \InvalidArgumentException('Studio schema conflict policy is invalid.');}
		$existing=$this->entries[$schema->kind()]??null;if($existing!==null){if($conflict==='reject'){throw new \LogicException("Studio component schema '{$schema->kind()}' is already registered.");}if($existing['provider']!==$provider||$schema->schemaVersion()<=$existing['schema']->schemaVersion()){throw new \LogicException('Studio schemas may only replace an older schema from the same provider.');}}
		$clone=clone$this;$clone->entries[$schema->kind()]=['schema'=>$schema,'provider'=>$provider,'provider_version'=>$providerVersion];ksort($clone->entries,SORT_STRING);$clone->fingerprintCache=null;if(count($clone->entries)>count(PanelStudioDefinition::KINDS)||strlen(self::canonical($clone->baseManifest()))>PanelStudioDefinition::MAX_JSON_BYTES){throw new \LengthException('Studio schema registry exceeds its deterministic schema budget.');}return$clone;
	}
	public function schema(string $kind):?PanelStudioComponentSchema{return$this->entries[$kind]['schema']??null;}
	public function kinds():array{return array_keys($this->entries);}
	public function version():string{return$this->version;}
	public function fingerprint():string{return$this->fingerprintCache??=hash('sha256',self::canonical($this->baseManifest()));}
	public function validate(PanelStudioDefinition|array $definition):PanelStudioValidation{
		if(is_array($definition)&&!array_is_list($definition)){$security=[];$securityNodes=0;self::credentialDiagnostics($definition,'root',$security,0,$securityNodes);if($security!==[]){return new PanelStudioValidation(null,null,$security,$this->version,$this->fingerprint());}}
		try{$definition=$definition instanceof PanelStudioDefinition?$definition:PanelStudioDefinition::from($definition);}catch(\Throwable $error){$diagnostic=new PanelStudioDiagnostic('root',$error instanceof \LengthException?'limit_exceeded':'invalid_definition',$error->getMessage());return new PanelStudioValidation(null,null,[$diagnostic],$this->version,$this->fingerprint());}
		$security=[];$securityNodes=0;self::credentialDiagnostics($definition->root(),'root',$security,0,$securityNodes);if($security!==[]){return new PanelStudioValidation($definition,null,$security,$this->version,$this->fingerprint());}
		$diagnostics=[];$identities=[];$normalized=$this->validateNode($definition->root(),'root',$diagnostics,$identities);$normalizedDefinition=null;if($diagnostics===[]){try{$normalizedDefinition=PanelStudioDefinition::from($normalized);}catch(\Throwable $error){$diagnostics[]=new PanelStudioDiagnostic('root','normalization_failed',$error->getMessage());}}
		return new PanelStudioValidation($definition,$normalizedDefinition,$diagnostics,$this->version,$this->fingerprint());
	}
	/** @return list<PanelStudioDiagnostic> */ public function diagnose(PanelStudioDefinition|array $definition):array{return$this->validate($definition)->diagnostics();}
	public function manifest():array{return$this->baseManifest()+['fingerprint'=>$this->fingerprint()];}
	public function jsonSerialize():array{return$this->manifest();}

	/** @param list<PanelStudioDiagnostic> $diagnostics @param array<string,string> $identities */
	private function validateNode(array $node,string $path,array &$diagnostics,array &$identities):array{
		$kind=(string)$node['kind'];$schema=$this->schema($kind);if(!$schema instanceof PanelStudioComponentSchema){$diagnostics[]=new PanelStudioDiagnostic($path.'.kind','schema_missing',"Studio component kind '{$kind}' has no trusted executable schema.");foreach($node['children']as$index=>$child){$this->validateNode($child,$path.'.children['.$index.']',$diagnostics,$identities);}return$node;}
		$key=(string)$node['key'];$parentPath=(string)preg_replace('/\.children\[\d+\]$/','',$path);$identity=match($schema->identityScope()){'document'=>$key,'document_kind'=>$kind."\0".$key,'sibling'=>'sibling'."\0".$parentPath."\0".$key};if(isset($identities[$identity])){$diagnostics[]=new PanelStudioDiagnostic($path.'.key','duplicate_identity',"Studio component identity conflicts with {$identities[$identity]}.");}else{$identities[$identity]=$path.'.key';}
		$properties=$node['properties'];foreach($properties as$name=>$value){$property=$schema->property((string)$name);if(!$property instanceof PanelStudioPropertySchema){$diagnostics[]=new PanelStudioDiagnostic($path.'.properties.'.(string)$name,'property_not_allowed',"Studio property '{$name}' is not allowed for {$kind}.");continue;}$diagnostic=$property->diagnostic($value,$path.'.properties.'.(string)$name);if($diagnostic){$diagnostics[]=$diagnostic;}}
		foreach($schema->properties()as$name=>$property){if(!array_key_exists($name,$properties)){if($property->hasDefault()){$properties[$name]=$property->defaultValue();}elseif($property->required()){$diagnostics[]=new PanelStudioDiagnostic($path.'.properties.'.$name,'required_property_missing',"Studio property '{$name}' is required for {$kind}.");}}}ksort($properties,SORT_STRING);
		$children=$node['children'];$total=count($children);if($total<$schema->minimumChildren()||$total>$schema->maximumChildren()){$diagnostics[]=new PanelStudioDiagnostic($path.'.children','child_cardinality_violation',"Studio {$kind} child count is outside its trusted bounds.");}
		$counts=[];foreach($children as$index=>$child){$childKind=(string)$child['kind'];$counts[$childKind]=($counts[$childKind]??0)+1;if(!$schema->childRule($childKind)instanceof PanelStudioChildRule){$diagnostics[]=new PanelStudioDiagnostic($path.'.children['.$index.'].kind','child_kind_not_allowed',"Studio {$childKind} components are not allowed under {$kind}.");}$children[$index]=$this->validateNode($child,$path.'.children['.$index.']',$diagnostics,$identities);}
		foreach($schema->childRules()as$childKind=>$rule){$count=$counts[$childKind]??0;if($count<$rule->minimum()||$count>$rule->maximum()){$diagnostics[]=new PanelStudioDiagnostic($path.'.children','child_kind_cardinality_violation',"Studio {$kind} requires {$rule->minimum()}..{$rule->maximum()} {$childKind} children; {$count} found.");}}
		return['kind'=>$kind,'key'=>$key,'properties'=>$properties,'children'=>$children];
	}
	private function baseManifest():array{
		$schemas=[];foreach($this->entries as$kind=>$entry){$schemas[$kind]=['provider'=>$entry['provider'],'provider_version'=>$entry['provider_version'],'schema'=>$entry['schema']->jsonSerialize()];}$executable=array_keys($schemas);$portableOnly=array_values(array_diff(PanelStudioDefinition::KINDS,$executable));sort($portableOnly,SORT_STRING);return['type'=>'panel_studio_schema_registry_manifest','version'=>self::REGISTRY_CONTRACT_VERSION,'registry_version'=>$this->version,'schemas'=>$schemas,'executable_kinds'=>$executable,'portable_only_envelope_kinds'=>$portableOnly,'complete_definition_kind_coverage'=>$portableOnly===[],'conflict_policy'=>['default'=>'reject','replacement'=>'same_provider_higher_schema_version_only'],'security'=>['data_only'=>true,'raw_html'=>false,'php'=>false,'class_names'=>false,'callbacks'=>false,'secrets'=>false],'visual_editor_runtime'=>false];
	}
	/** @return list<PanelStudioComponentSchema> */
	private static function defaultSchemas():array{
		$p=static fn(string $name,string $type='string',array $options=[]):PanelStudioPropertySchema=>PanelStudioPropertySchema::make($name,$type,$options);$c=static fn(string $kind,int $min=0,int $max=512):PanelStudioChildRule=>PanelStudioChildRule::make($kind,$min,$max);$s=static fn(string $kind,array $properties=[],array $children=[],int $min=0,int $max=512):PanelStudioComponentSchema=>PanelStudioComponentSchema::make($kind,$properties,$children,$min,$max,'sibling');
		$label=$p('label','string',['max_length'=>160]);$description=$p('description','string',['max_length'=>1024]);$layout=$p('layout','string',['default'=>'stack','enum'=>['inline','stack','grid','brick','masonry']]);$columns=$p('columns','integer',['default'=>1,'min'=>1,'max'=>12]);$url=$p('url','string',['pattern'=>'~^/[A-Za-z0-9._!$&\'()*+,;=:@%/?#-]*$~D','max_length'=>2048]);$tone=$p('tone','string',['default'=>'neutral','enum'=>['neutral','primary','success','warning','danger','info']]);
		$boardLayout=$p('layout','string',['default'=>'grid','enum'=>['inline','stack','grid','brick','masonry']]);$boardColumns=$p('columns','integer',['default'=>3,'min'=>1,'max'=>12]);$gap=$p('gap','string',['default'=>'normal','enum'=>['none','compact','normal','roomy']]);$fit=$p('fit','string',['default'=>'fill','enum'=>['auto','fill','fixed']]);$masonry=$p('masonry','string',['default'=>'rows','enum'=>['columns','rows']]);$minimumWidth=$p('min_width','integer',['default'=>220,'min'=>96,'max'=>480]);$finalRow=$p('final_row','string',['default'=>'fill','enum'=>['fill','preserve','center','end']]);
		return[
			$s('page',[$label,$description,$layout,$url,$p('group','string',['max_length'=>120]),$p('icon','string',['max_length'=>120]),$p('sort','integer',['default'=>100,'min'=>-100000,'max'=>100000]),$p('hidden_from_navigation','boolean',['default'=>false])],[$c('form',0,16),$c('table',0,16),$c('data_surface',0,16),$c('show',0,16),$c('infolist',0,16),$c('board',0,16),$c('workflow',0,16),$c('actions',0,8),$c('widget_grid',0,8),$c('tabs',0,8),$c('toolbar',0,8),$c('navigation',0,4)],0,64),
			$s('form',[$columns,$layout],[$c('field',0,128),$c('form_section',0,64),$c('tabs',0,16)],1,128),
			$s('form_section',[$label,$description,$columns,$p('collapsible','boolean',['default'=>false]),$p('collapsed','boolean',['default'=>false])],[$c('field',1,128)],1,128),
			$s('field',[$label,$p('type','string',['default'=>'text','enum'=>['text','email','number','integer','textarea','select','radio','checkbox','toggle','date','datetime','time','password']]),$p('required','boolean',['default'=>false]),$p('readonly','boolean',['default'=>false]),$p('disabled','boolean',['default'=>false]),$p('placeholder','string',['max_length'=>512]),$p('help','string',['max_length'=>1024]),$p('default','scalar',['nullable'=>true]),$p('options','scalar_map'),$p('minimum','number'),$p('maximum','number'),$p('step','number'),$p('rows','integer',['default'=>5,'min'=>1,'max'=>100]),$p('searchable','boolean',['default'=>false]),$p('multiple','boolean',['default'=>false]),$p('column_span','integer',['min'=>1,'max'=>12])],[],0,0),
			$s('table',[$p('per_page','integer',['default'=>25,'min'=>1,'max'=>1000]),$p('density','string',['default'=>'normal','enum'=>['compact','normal','roomy']]),$p('default_sort','string',['max_length'=>128]),$p('default_sort_direction','string',['default'=>'asc','enum'=>['asc','desc']])],[$c('column',1,128),$c('filter',0,32),$c('table_view',0,32),$c('filters',0,1),$c('table_views',0,1)],1,194),
			$s('column',[$label,$p('type','string',['default'=>'text','enum'=>['text','badge','money','date','datetime','boolean']]),$p('sortable','boolean',['default'=>false]),$p('searchable','boolean',['default'=>false]),$p('toggleable','boolean',['default'=>false]),$p('hidden_by_default','boolean',['default'=>false]),$p('currency','string',['default'=>'','max_length'=>8]),$p('limit','integer',['min'=>1,'max'=>4096]),$p('wrap','boolean',['default'=>false])],[],0,0),
			$s('data_surface',[
				$label,$description,
				$p('resource','string',['default'=>'records','pattern'=>'~^[a-z][a-z0-9_.-]{0,99}$~D']),
				$p('source','string',['default'=>'studio_data','pattern'=>'~^[a-z][a-z0-9_.-]{0,99}$~D']),
				$p('surface','string',['default'=>'table','enum'=>PanelDataSurfaceType::values()]),
				$p('fields','string_list',['default'=>['id','title','description','parent_id','source_id','target_id','row','column','value','group','start','end','progress','latitude','longitude','x','y','width','height','color','status'],'min_length'=>1,'max_length'=>64]),
				$p('stable_key','string',['default'=>'id','pattern'=>'~^[A-Za-z_][A-Za-z0-9_.-]{0,127}$~D']),
				$p('slots','scalar_map',['default'=>['title'=>'title','description'=>'description','parent'=>'parent_id','source'=>'source_id','target'=>'target_id','row'=>'row','column'=>'column','value'=>'value','group'=>'group','start'=>'start','end'=>'end','progress'=>'progress','latitude'=>'latitude','longitude'=>'longitude','x'=>'x','y'=>'y','width'=>'width','height'=>'height','color'=>'color','cross_filter'=>'status'],'max_length'=>64]),
				$p('labels','scalar_map',['default'=>[],'max_length'=>64]),$p('roles','scalar_map',['default'=>[],'max_length'=>64]),
				$p('window_length','integer',['default'=>50,'min'=>1,'max'=>500]),$p('overscan_before','integer',['default'=>20,'min'=>0,'max'=>250]),$p('overscan_after','integer',['default'=>40,'min'=>0,'max'=>250]),
				$p('estimated_item_size','integer',['default'=>52,'min'=>20,'max'=>2000]),$p('virtualize','boolean',['default'=>true]),
				$p('empty_message','string',['default'=>'No records to display.','max_length'=>256]),$p('aria_label','string',['max_length'=>256]),$p('endpoint','string',['pattern'=>'~^/[A-Za-z0-9._!$&\'()*+,;=:@%/?#-]*$~D','max_length'=>2048]),
				$p('aggregate','string',['default'=>'sum','enum'=>['count','sum','average','minimum','maximum','first']]),$p('selection','string',['default'=>'none','enum'=>['none','single','multiple']]),
				$p('cross_filter_group','string',['pattern'=>'~^[a-z][a-z0-9_.-]{0,95}$~D']),$p('cross_filter_field','string',['pattern'=>'~^[A-Za-z_][A-Za-z0-9_.-]{0,127}$~D']),
				$p('drill_url','string',['pattern'=>'~^/[A-Za-z0-9._!$&\'()*+,;=:@%/?#-]*$~D','max_length'=>2048]),$p('drill_parameter','string',['default'=>'record','pattern'=>'~^[a-z][a-z0-9_]{0,63}$~D']),
				$p('editable','boolean',['default'=>false]),$p('frozen_fields','integer',['default'=>0,'min'=>0,'max'=>16]),$p('show_labels','boolean',['default'=>true]),$p('show_legend','boolean',['default'=>true]),$p('snap_to_grid','boolean',['default'=>false]),$p('zoom','boolean',['default'=>false]),
			],[],0,0),
			$s('filter',[$label,$p('type','string',['default'=>'text','enum'=>['text','select','boolean','range','date_range','number_range']]),$p('column','string',['max_length'=>128]),$p('options','scalar_map'),$p('default','scalar',['nullable'=>true]),$p('indicator','string',['max_length'=>160]),$tone],[],0,0),
			$s('filters',[$layout],[$c('filter',1,32)],1,32),
			$s('table_view',[$label,$p('default','boolean',['default'=>false]),$tone,$p('search','string',['max_length'=>512]),$p('columns','string_list',['max_length'=>128]),$p('filters','scalar_map'),$p('sort_column','string',['max_length'=>128]),$p('sort_direction','string',['default'=>'asc','enum'=>['asc','desc']]),$p('per_page','integer',['min'=>1,'max'=>1000]),$p('density','string',['enum'=>['compact','normal','roomy']])],[],0,0),
			$s('table_views',[$layout],[$c('table_view',1,32)],1,32),
			$s('board',[$label,$p('plural_label','string',['max_length'=>160]),$description,$url,$p('group','string',['max_length'=>120]),$p('icon','string',['max_length'=>120]),$p('sort','integer',['default'=>100,'min'=>-100000,'max'=>100000]),$p('hidden_from_navigation','boolean',['default'=>false]),$p('status_field','string',['default'=>'status','pattern'=>'~^[a-z][a-z0-9_.-]{0,127}$~D']),$p('record_key_field','string',['pattern'=>'~^[a-z][a-z0-9_.-]{0,127}$~D']),$p('record_title_field','string',['pattern'=>'~^[a-z][a-z0-9_.-]{0,127}$~D']),$p('record_subtitle_field','string',['pattern'=>'~^[a-z][a-z0-9_.-]{0,127}$~D']),$p('status_widgets','boolean',['default'=>false]),$boardLayout,$boardColumns,$gap,$fit,$masonry,$minimumWidth,$finalRow,$p('card_layout','string',['default'=>'stack','enum'=>['stack','grid','brick','masonry']]),$p('card_columns','integer',['default'=>1,'min'=>1,'max'=>12]),$p('card_gap','string',['default'=>'normal','enum'=>['none','compact','normal','roomy']]),$p('card_fit','string',['default'=>'fill','enum'=>['auto','fill','fixed']]),$p('card_masonry','string',['default'=>'rows','enum'=>['columns','rows']]),$p('card_min_width','integer',['default'=>220,'min'=>96,'max'=>480]),$p('card_final_row','string',['default'=>'fill','enum'=>['fill','preserve','center','end']])],[$c('board_column',1,64)],1,64),
			$s('board_column',[$label,$p('status','string',['max_length'=>128,'pattern'=>'~^[A-Za-z0-9][A-Za-z0-9 _.-]{0,127}$~D']),$tone,$p('accepts_moves','boolean',['default'=>true]),$p('from','string_list',['max_length'=>64]),$p('transition','string',['pattern'=>'~^[a-z][a-z0-9_.-]{0,127}$~D','max_length'=>128]),$p('transition_label','string',['max_length'=>160]),$p('confirmation','string',['max_length'=>1024]),$p('column_span','integer',['min'=>1,'max'=>12]),$p('basis','string',['max_length'=>32]),$p('min_width','string',['max_length'=>32]),$p('max_width','string',['max_length'=>32]),$p('grow','number',['min'=>0,'max'=>12]),$p('order','integer',['min'=>-100,'max'=>100]),$p('break_before','boolean',['default'=>false]),$p('fill_remainder','boolean',['default'=>false])],[],0,0),
			$s('show',[$columns,$layout],[$c('infolist_entry',0,128),$c('show_section',0,64),$c('tabs',0,16)],1,128),
			$s('infolist',[$columns,$layout],[$c('infolist_entry',0,128),$c('show_section',0,64),$c('tabs',0,16)],1,128),
			$s('show_section',[$label,$description,$columns,$p('collapsible','boolean',['default'=>false]),$p('collapsed','boolean',['default'=>false])],[$c('infolist_entry',1,128)],1,128),
			$s('infolist_entry',[$label,$p('type','string',['default'=>'text','enum'=>['text','badge','image']]),$p('icon','string',['max_length'=>120]),$p('prefix','string',['max_length'=>256]),$p('suffix','string',['max_length'=>256]),$p('copyable','boolean',['default'=>false]),$p('empty_label','string',['max_length'=>256]),$description,$p('column_span','integer',['min'=>1,'max'=>12])],[],0,0),
			$s('actions',[$label,$p('icon','string',['max_length'=>120]),$tone,$p('style','string',['default'=>'default','enum'=>['default','outline','ghost','subtle','link']]),$p('size','string',['default'=>'md','enum'=>['xs','sm','md','lg']])],[$c('action',1,64)],1,64),
			$s('action',[$label,$p('icon','string',['max_length'=>120]),$tone,$p('style','string',['default'=>'default','enum'=>['default','outline','ghost','subtle','link']]),$p('size','string',['default'=>'md','enum'=>['xs','sm','md','lg']]),$p('requires_confirmation','boolean',['default'=>false]),$p('confirmation','string',['max_length'=>1024]),$p('disabled','boolean',['default'=>false]),$p('redirect_to','string',['pattern'=>'~^/[A-Za-z0-9._!$&\'()*+,;=:@%/?#-]*$~D','max_length'=>2048]),$p('success_message','string',['max_length'=>512])],[],0,0),
			$s('widget_grid',[$columns,$layout],[$c('widget',1,64)],1,64),
			$s('widget',[$label,$p('type','string',['default'=>'stat','enum'=>['stat','chart']]),$p('value','scalar',['nullable'=>true]),$description,$tone,$p('icon','string',['max_length'=>120]),$url,$p('group','string',['max_length'=>120]),$p('sort','integer',['default'=>100,'min'=>-100000,'max'=>100000]),$p('unit','string',['max_length'=>32]),$p('height','integer',['min'=>80,'max'=>2000]),$p('chart_type','string',['default'=>'line','enum'=>['line','bar','area','pie','doughnut']]),$p('labels','string_list',['max_length'=>128]),$p('data','number_list',['max_length'=>128])],[],0,0),
			$s('tabs',[$layout],[$c('tab',1,32)],1,32),
			$s('tab',[$label,$columns],[$c('field',0,128),$c('form_section',0,64),$c('infolist_entry',0,128),$c('show_section',0,64)],1,128),
			$s('toolbar',[$label,$layout],[$c('action',0,64),$c('actions',0,16)],1,80),
			$s('navigation',[$label],[$c('navigation_group',0,32),$c('navigation_item',0,128)],1,160),
			$s('navigation_group',[$label,$p('icon','string',['max_length'=>120]),$description,$p('sort','integer',['default'=>100,'min'=>-100000,'max'=>100000])],[$c('navigation_item',1,128)],1,128),
			$s('navigation_item',[$label,$url,$p('icon','string',['max_length'=>120]),$description,$p('sort','integer',['default'=>100,'min'=>-100000,'max'=>100000]),$p('badge','scalar',['nullable'=>true]),$tone,$p('new_tab','boolean',['default'=>false]),$p('hidden','boolean',['default'=>false])],[$c('navigation_item',0,64)],0,64),
			$s('workflow',[$label,$description,$p('initial_state','string',['pattern'=>'~^[a-z][a-z0-9_]{0,127}$~D']),$p('require_terminal','boolean',['default'=>true]),$p('metadata','scalar_map',['default'=>[],'max_length'=>128])],[$c('workflow_state',1,128),$c('workflow_transition',0,256)],1,384),
			$s('workflow_state',[$label,$description,$p('draft','boolean',['default'=>false]),$p('terminal','boolean',['default'=>false]),$p('sla_seconds','integer',['min'=>1,'max'=>31536000]),$p('assignment_roles','string_list',['default'=>[],'max_length'=>64]),$p('queue','string',['max_length'=>128]),$tone,$p('metadata','scalar_map',['default'=>[],'max_length'=>128])],[],0,0),
			$s('workflow_transition',[$label,$description,$p('from_states','string_list',['default'=>['draft'],'min_length'=>1,'max_length'=>128]),$p('to_state','string',['default'=>'done','pattern'=>'~^[a-z][a-z0-9_]{0,127}$~D']),$p('roles','string_list',['default'=>[],'max_length'=>64]),$p('permissions','string_list',['default'=>[],'max_length'=>64]),$p('requires_approval','boolean',['default'=>false]),$p('approval_quorum','integer',['default'=>1,'min'=>1,'max'=>100]),$p('approval_roles','string_list',['default'=>[],'max_length'=>64]),$p('approval_permissions','string_list',['default'=>[],'max_length'=>64]),$p('distinct_actors','boolean',['default'=>true]),$p('allow_requester','boolean',['default'=>false]),$p('rejection_threshold','integer',['default'=>1,'min'=>1,'max'=>100]),$p('expires_after_seconds','integer',['min'=>1,'max'=>31536000]),$p('assigned_actor','string',['max_length'=>256]),$p('assignment_roles','string_list',['default'=>[],'max_length'=>64]),$p('sla_seconds','integer',['min'=>1,'max'=>31536000]),$p('reversible','boolean',['default'=>false]),$tone,$p('metadata','scalar_map',['default'=>[],'max_length'=>128])],[],0,0),
		];
	}
	private static function provider(string $value,string $label):void{if(preg_match('/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}$/',$value)!==1){throw new \InvalidArgumentException("Studio schema {$label} is invalid.");}}
	/** @param list<PanelStudioDiagnostic> $diagnostics */ private static function credentialDiagnostics(array $node,string $path,array &$diagnostics,int $depth,int &$nodes):void{if($depth>PanelStudioDefinition::MAX_DEPTH||++$nodes>PanelStudioDefinition::MAX_NODES){return;}$properties=is_array($node['properties']??null)?$node['properties']:[];$type=is_string($properties['type']??null)?strtolower($properties['type']):'';if(($node['kind']??null)==='field'&&preg_match('/(?:^|[_-])(?:password|secret|token|credential)(?:[_-]|$)/',$type)===1){foreach(['default','value','initial_value']as$key){if(array_key_exists($key,$properties)){$diagnostics[]=new PanelStudioDiagnostic($path.'.properties.'.$key,'secret_default_forbidden','Studio password or secret-like fields cannot persist default values.');}}}foreach(is_array($node['children']??null)?$node['children']:[]as$index=>$child){if(is_array($child)){self::credentialDiagnostics($child,$path.'.children['.$index.']',$diagnostics,$depth+1,$nodes);}}}
	private static function canonical(array $value):string{return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);}
}
