<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);
namespace Dataphyre\Panel;

/** Authorized Studio composition, preview, approval, promotion, and rollback facade. */
final class PanelStudioManager implements \JsonSerializable {
	private readonly PanelStudioAuthorization $authorization;
	private readonly PanelStudioCompiler $compiler;
	private readonly PanelStudioSchemaRegistry $registry;
	private readonly PanelStudioMaterializer $materializer;
	private readonly \Closure $clock;
	public function __construct(private readonly PanelStudioStore $store,?PanelStudioAuthorization $authorization=null,?PanelStudioCompiler $compiler=null,private readonly ?PanelStudioPreviewSigner $previewSigner=null,private readonly int $requiredPublishApprovals=0,?callable $clock=null,?PanelStudioSchemaRegistry $registry=null,?PanelStudioMaterializer $materializer=null,private readonly ?PanelStudioVisualRuntime $visualRuntime=null){
		if($requiredPublishApprovals<0||$requiredPublishApprovals>10){throw new \InvalidArgumentException('Studio publish approvals must be between zero and ten.');}
		$this->authorization=$authorization??PanelStudioPolicy::denyAll();$this->compiler=$compiler??new PanelStudioCompiler();$this->registry=$registry??PanelStudioSchemaRegistry::defaults();$this->materializer=$materializer??new PanelStudioMaterializer();$this->clock=$clock!==null?$clock(...):static fn():string=>gmdate('c');
	}
	/** Explicitly returns a maintenance-authorized clone; the original remains fail-closed. @param list<string> $principals */
	public function trustedMaintenance(array $principals):self{return new self($this->store,PanelStudioPolicy::trustedMaintenance($principals),$this->compiler,$this->previewSigner,$this->requiredPublishApprovals,$this->clock,$this->registry,$this->materializer,$this->visualRuntime);}
	public function head(string $tenantId,string $documentId,string $principalId):?PanelStudioRevision{$this->authorize('read',$tenantId,$principalId,$documentId);return$this->store->head($tenantId,$documentId);}
	public function draft(string $tenantId,string $documentId,string $principalId):?PanelStudioDraft{$this->authorize('read',$tenantId,$principalId,$documentId);return$this->store->draft($tenantId,$documentId);}
	public function published(string $tenantId,string $documentId,string $principalId):?PanelStudioRevision{$this->authorize('read',$tenantId,$principalId,$documentId);return$this->store->published($tenantId,$documentId);}
	/** @return list<PanelStudioRevision> */ public function history(string $tenantId,string $documentId,string $principalId,int $limit=100):array{$this->authorize('read',$tenantId,$principalId,$documentId);return$this->store->history($tenantId,$documentId,$limit);}
	public function saveDraft(PanelStudioDocument $document,PanelStudioDefinition|array $definition,int $expectedRevision,string $idempotencyKey,string $principalId):PanelStudioReceipt{
		$this->authorize('save',$document->tenantId(),$principalId,$document->id());$validation=$this->registry->validate($definition)->assertValid();$definition=$validation->definition();if(!$definition instanceof PanelStudioDefinition){throw new \LogicException('Studio validation lost its source definition.');}$this->compiler->compile($definition);$materialization=$this->materializer->materialize($definition,$this->registry);return$this->store->save($document,$definition,$expectedRevision,$idempotencyKey,$principalId,$this->now(),$materialization->artifact());
	}
	public function approve(string $tenantId,string $documentId,int $expectedRevision,string $idempotencyKey,string $principalId):PanelStudioReceipt{$this->authorize('approve',$tenantId,$principalId,$documentId);$this->assertCompatible($this->revision($tenantId,$documentId,$expectedRevision));return$this->store->approve($tenantId,$documentId,$expectedRevision,$idempotencyKey,$principalId,$this->now());}
	public function publish(string $tenantId,string $documentId,int $expectedRevision,string $idempotencyKey,string $principalId):PanelStudioReceipt{$this->authorize('publish',$tenantId,$principalId,$documentId);$this->assertCompatible($this->revision($tenantId,$documentId,$expectedRevision));return$this->store->publish($tenantId,$documentId,$expectedRevision,$idempotencyKey,$principalId,$this->requiredPublishApprovals,$this->now());}
	public function rollback(string $tenantId,string $documentId,int $targetRevision,int $expectedRevision,string $idempotencyKey,string $principalId):PanelStudioReceipt{$this->authorize('rollback',$tenantId,$principalId,$documentId);$this->assertCompatible($this->revision($tenantId,$documentId,$targetRevision));return$this->store->rollback($tenantId,$documentId,$targetRevision,$expectedRevision,$idempotencyKey,$principalId,$this->now());}
	public function preview(string $tenantId,string $documentId,int $expectedRevision,string $principalId,int $ttlSeconds=300,string $audience='panel_studio_preview'):PanelStudioPreviewIntent{
		$this->authorize('preview',$tenantId,$principalId,$documentId);if(!$this->previewSigner instanceof PanelStudioPreviewSigner){throw new \LogicException('Studio preview signing is not configured.');}$revision=$this->store->head($tenantId,$documentId);if(!$revision instanceof PanelStudioRevision||$revision->number()!==$expectedRevision){throw new \RuntimeException('Studio preview revision conflict.');}$this->assertCompatible($revision);return$this->previewSigner->issue($tenantId,$principalId,$documentId,$revision,$ttlSeconds,$audience);
	}
	public function verifyPreview(string $token,string $tenantId,string $documentId,string $principalId,?int $revision=null,string $audience='panel_studio_preview'):PanelStudioPreviewIntent{$this->authorize('preview',$tenantId,$principalId,$documentId);if(!$this->previewSigner instanceof PanelStudioPreviewSigner){throw new \LogicException('Studio preview signing is not configured.');}$intent=$this->previewSigner->verify($token,$tenantId,$principalId,$documentId,$revision,$audience);$head=$this->store->head($tenantId,$documentId);if(!$head instanceof PanelStudioRevision||$head->number()!==$intent->claims()['revision']||!hash_equals($head->contentHash(),(string)$intent->claims()['content_hash'])){throw new \RuntimeException('Studio preview no longer matches the current revision.');}$this->assertCompatible($head);return$intent;}
	public function impact(string $tenantId,string $documentId,string $principalId):PanelStudioImpactPlan{
		$this->authorize('read',$tenantId,$principalId,$documentId);$head=$this->store->head($tenantId,$documentId);if(!$head instanceof PanelStudioRevision){throw new \OutOfBoundsException('Studio document does not exist.');}$published=$this->store->published($tenantId,$documentId);$before=$published?$this->compiler->compile($published->definition()):[];return new PanelStudioImpactPlan($before,$this->compiler->compile($head->definition()));
	}
	public function materialize(string $tenantId,string $documentId,string $principalId,?int $revision=null):PanelStudioMaterialization{$this->authorize('read',$tenantId,$principalId,$documentId);$selected=$revision===null?$this->store->head($tenantId,$documentId):$this->revision($tenantId,$documentId,$revision);if(!$selected instanceof PanelStudioRevision){throw new \OutOfBoundsException('Studio document does not exist.');}$artifact=$this->assertCompatible($selected);$materialization=$this->materializer->materialize($selected->definition(),$this->registry);if(!hash_equals($artifact->fingerprint(),$materialization->artifact()->fingerprint())){throw new PanelStudioSchemaException('Studio materialization no longer reproduces the approved artifact.',[new PanelStudioDiagnostic('artifact.fingerprint','artifact_reproduction_mismatch','Studio artifact cannot be reproduced by the active trusted compiler and materializer.')]);}return$materialization;}
	public function materializePublished(string $tenantId,string $documentId,string $principalId):PanelStudioMaterialization{$this->authorize('read',$tenantId,$principalId,$documentId);$published=$this->store->published($tenantId,$documentId);if(!$published){throw new \OutOfBoundsException('Studio document has no published revision.');}return$this->materialize($tenantId,$documentId,$principalId,$published->number());}
	/** @return list<PanelStudioDiagnostic> */ public function compatibilityDiagnostics(PanelStudioRevision $revision):array{$artifact=$revision->artifact();if(!$artifact){return[new PanelStudioDiagnostic('artifact.binding_status','unbound_legacy_revision','Legacy Studio revision is unbound and must be re-saved through the trusted compiler before promotion.')];}try{$artifact->assertDefinition($revision->definition());}catch(\Throwable){return[new PanelStudioDiagnostic('artifact.definition_hash','artifact_definition_mismatch','Studio artifact does not bind its revision definition.')];}return$artifact->compatibilityDiagnostics($this->registry,$this->materializer,$this->compiler);}
	public function compiler():PanelStudioCompiler{return$this->compiler;}
	public function registry():PanelStudioSchemaRegistry{return$this->registry;}
	public function materializer():PanelStudioMaterializer{return$this->materializer;}
	public function hasVisualRuntime():bool{return$this->visualRuntime instanceof PanelStudioVisualRuntime;}
	public function visualRuntime():PanelStudioVisualRuntime{if(!$this->visualRuntime instanceof PanelStudioVisualRuntime){throw new \LogicException('Studio visual runtime is not configured.');}return$this->visualRuntime;}
	public function store():PanelStudioStore{return$this->store;}
	public function manifest():array{return['type'=>'panel_studio_manifest','version'=>4,'required_publish_approvals'=>$this->requiredPublishApprovals,'two_person_publish'=>$this->requiredPublishApprovals>0,'store'=>$this->store->manifest(),'compiler'=>$this->compiler->manifest(),'registry'=>$this->registry->manifest(),'materializer'=>$this->materializer->manifest(),'authorization'=>$this->authorization->manifest(),'preview'=>$this->previewSigner?->manifest(),'visual_runtime'=>$this->visualRuntime?->manifest(),'capabilities'=>['structured_schema_composition'=>true,'portable_blueprints'=>true,'visual_editor_runtime'=>$this->hasVisualRuntime(),'kind_specific_schema_registry'=>true,'trusted_materialization'=>true,'complete_definition_kind_coverage'=>$this->registry->manifest()['complete_definition_kind_coverage']===true&&$this->materializer->manifest()['complete_definition_kind_coverage']===true,'read_only_boards_without_mutation_handlers'=>true,'host_bound_board_mutations'=>true,'first_class_infolists'=>true,'artifact_bound_publication'=>true,'optimistic_drafts'=>true,'idempotent_commands'=>true,'independent_approvals'=>true,'preview_intents'=>true,'impact_plans'=>true,'hash_chained_history'=>true,'rollback'=>true,'action_builders_execute_mutations'=>false],'security'=>['fail_closed_authorization'=>true,'arbitrary_php'=>false,'raw_html'=>false,'user_classes'=>false,'callbacks'=>false,'secret_serialization'=>false,'stale_registry_fails_closed'=>true,'visual_runtime_routes_registered'=>false,'visual_runtime_mutation_authority'=>false]];}
	public function jsonSerialize():array{return$this->manifest();}
	private function authorize(string $action,string $tenantId,string $principalId,string $documentId):void{if(!$this->authorization->allows($action,$tenantId,$principalId,$documentId)){throw new \RuntimeException('Studio action is not authorized.');}}
	private function revision(string $tenantId,string $documentId,int $number):PanelStudioRevision{foreach($this->store->history($tenantId,$documentId,1000)as$revision){if($revision->number()===$number){return$revision;}}throw new \OutOfBoundsException('Studio revision does not exist.');}
	private function assertCompatible(PanelStudioRevision $revision):PanelStudioArtifact{$diagnostics=$this->compatibilityDiagnostics($revision);if($diagnostics!==[]){throw new PanelStudioSchemaException('Studio revision is stale, unbound, or requires an explicit migration.',$diagnostics);}$artifact=$revision->artifact();if(!$artifact){throw new \LogicException('Compatible Studio revisions must have an artifact.');}return$artifact;}
	private function now():string{$value=($this->clock)();if(!is_string($value)||preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/',$value)!==1){throw new \UnexpectedValueException('Studio clocks must return ISO timestamp strings.');}try{return(new \DateTimeImmutable($value))->format(DATE_ATOM);}catch(\Throwable){throw new \UnexpectedValueException('Studio clocks must return valid ISO timestamp strings.');}}
}
