<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);
namespace Dataphyre\Panel;

/** Audited hard-coded conversion from trusted schemas to actual callback-free Panel builders. */
final class PanelStudioMaterializer implements \JsonSerializable {
	public const MATERIALIZER_VERSION=3;
	public function version():int{return self::MATERIALIZER_VERSION;}
	public function validate(PanelStudioDefinition|array $definition,PanelStudioSchemaRegistry $registry):PanelStudioValidation{return$registry->validate($definition);}
	/** @return list<PanelStudioDiagnostic> */ public function diagnose(PanelStudioDefinition|array $definition,PanelStudioSchemaRegistry $registry):array{$validation=$this->validate($definition,$registry);if(!$validation->valid()){return$validation->diagnostics();}$diagnostics=[];$checked=[];$this->auditSchemaContracts($validation->normalized()->root(),'root',$registry,$diagnostics,$checked,null);return$diagnostics;}
	public function materialize(PanelStudioDefinition|array $definition,PanelStudioSchemaRegistry $registry):PanelStudioMaterialization{
		$validation=$registry->validate($definition)->assertValid();$source=$validation->definition();if(!$source instanceof PanelStudioDefinition){throw new \LogicException('Studio materialization lost its source definition.');}$normalized=$validation->normalized();$contractDiagnostics=[];$checked=[];$this->auditSchemaContracts($normalized->root(),'root',$registry,$contractDiagnostics,$checked,null);if($contractDiagnostics!==[]){throw new PanelStudioSchemaException('Studio registry schemas do not match the audited materializer contract.',$contractDiagnostics);}$builders=[];$symbols=[];$identities=[];$this->build($normalized->root(),'root',$builders,$symbols,$identities);$artifact=PanelStudioArtifact::trusted($source,$normalized,$registry,new PanelStudioCompiler(),$this,$symbols);return new PanelStudioMaterialization($artifact,$builders,$symbols,$identities);
	}
	public function fingerprint():string{return hash('sha256',json_encode($this->baseManifest(),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));}
	public function manifest():array{return$this->baseManifest()+['fingerprint'=>$this->fingerprint()];}
	public function jsonSerialize():array{return$this->manifest();}

	/** @param array<string,object|array> $builders @param array<string,string> $symbols @param array<string,list<string>> $identities */
	private function build(array $node,string $path,array &$builders,array &$symbols,array &$identities):object|array{
		$kind=(string)$node['kind'];$properties=$node['properties'];$builder=match($kind){
			'field'=>$this->field($node),
			'form_section'=>$this->section($node,$path,$builders,$symbols,$identities,'field'),
			'form'=>$this->form($node,$path,$builders,$symbols,$identities),
			'column'=>$this->column($node),
			'data_surface'=>$this->dataSurface($node),
			'filter'=>$this->filter($node),
			'filters'=>$this->collection($node,$path,$builders,$symbols,$identities),
			'table_view'=>$this->tableView($node),
			'table_views'=>$this->collection($node,$path,$builders,$symbols,$identities),
			'table'=>$this->table($node,$path,$builders,$symbols,$identities),
			'board_column'=>$this->boardColumn($node),
			'board'=>$this->board($node,$path,$builders,$symbols,$identities),
			'infolist_entry'=>$this->entry($node),
			'show_section'=>$this->section($node,$path,$builders,$symbols,$identities,'infolist_entry'),
			'show','infolist'=>$this->show($node,$path,$builders,$symbols,$identities),
			'action'=>$this->action($node),
			'actions'=>$this->actionGroup($node,$path,$builders,$symbols,$identities),
			'toolbar'=>$this->toolbar($node,$path,$builders,$symbols,$identities),
			'widget'=>$this->widget($node),
			'widget_grid'=>$this->collection($node,$path,$builders,$symbols,$identities),
			'tab'=>$this->tab($node,$path,$builders,$symbols,$identities),
			'tabs'=>$this->tabs($node,$path,$builders,$symbols,$identities),
			'navigation_item'=>$this->navigationItem($node,$path,$builders,$symbols,$identities,false),
			'navigation_group'=>$this->navigationItem($node,$path,$builders,$symbols,$identities,true),
			'navigation'=>$this->collection($node,$path,$builders,$symbols,$identities),
			'workflow_state'=>$this->workflowState($node),
			'workflow_transition'=>$this->workflowTransition($node),
			'workflow'=>$this->workflow($node,$path,$builders,$symbols,$identities),
			'page'=>$this->page($node,$path,$builders,$symbols,$identities),
			default=>throw new PanelStudioSchemaException('Studio kind has no audited materializer.',[new PanelStudioDiagnostic($path.'.kind','materializer_missing',"Studio component kind '{$kind}' is not materializable.")]),
		};
		$symbol=match($kind){'field'=>'field','form_section','show_section'=>'form_section','form'=>'resource_form','column'=>'column','data_surface'=>'data_surface_definition','filter'=>'table_filter','filters'=>'table_filter_collection','table_view'=>'table_view','table_views'=>'table_view_collection','table'=>'resource_table','board_column'=>'board_column','board'=>'resource_board','infolist_entry'=>'infolist_entry','show','infolist'=>'infolist','action'=>'action','actions','toolbar'=>'action_group','widget'=>'widget','widget_grid'=>'widget_collection','tab'=>'schema_component','tabs'=>'schema','navigation_item','navigation_group'=>'navigation_item','navigation'=>'navigation_collection','workflow_state'=>'workflow_state','workflow_transition'=>'workflow_transition','workflow'=>'workflow_definition','page'=>'panel_page_bundle',default=>'unsupported'};
		$builders[$path]=$builder;$symbols[$path]=$symbol;$identity=$kind.':'.(string)$node['key'];$identities[$identity]??=[];$identities[$identity][]=$path;return$builder;
	}
	private function field(array $node):Field{
		$p=$node['properties'];$type=(string)$p['type'];$field=Field::make((string)$node['key']);$field=match($type){'email'=>$field->email(),'number'=>$field->number(),'integer'=>$field->integer(),'textarea'=>$field->textarea((int)$p['rows']),'select'=>$field->select(is_array($p['options']??null)?$p['options']:[]),'radio'=>$field->radio(is_array($p['options']??null)?$p['options']:[]),'checkbox'=>$field->checkbox(),'toggle'=>$field->toggle(),'date'=>$field->date(),'datetime'=>$field->dateTime(),'time'=>$field->time(),'password'=>$field->password(),default=>$field->type($type)};
		if(isset($p['label'])){$field=$field->label((string)$p['label']);}if($p['required']){$field=$field->required();}if($p['readonly']){$field=$field->readonly();}if($p['disabled']){$field=$field->disabled();}if(isset($p['placeholder'])){$field=$field->placeholder((string)$p['placeholder']);}if(isset($p['help'])){$field=$field->help((string)$p['help']);}if(array_key_exists('default',$p)){$field=$field->default($p['default']);}if(isset($p['options'])&&!in_array($type,['select','radio'],true)){$field=$field->options($p['options']);}if(array_key_exists('minimum',$p)){$field=$field->min($p['minimum']);}if(array_key_exists('maximum',$p)){$field=$field->max($p['maximum']);}if(array_key_exists('step',$p)){$field=$field->step($p['step']);}if($p['searchable']){$field=$field->searchable();}if($p['multiple']){$field=$field->multiple();}if(isset($p['column_span'])){$field=$field->columnSpan((int)$p['column_span']);}return$field;
	}
	private function section(array $node,string $path,array &$builders,array &$symbols,array &$identities,string $childKind):FormSection{
		foreach($node['children']as$index=>$child){$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);}$p=$node['properties'];$section=FormSection::make((string)$node['key']);if(isset($p['label'])){$section=$section->label((string)$p['label']);}if(isset($p['description'])){$section=$section->description((string)$p['description']);}$section=$section->columns((int)$p['columns']);if($p['collapsible']){$section=$section->collapsible();}if($p['collapsed']){$section=$section->collapsed();}return$section;
	}
	private function form(array $node,string $path,array &$builders,array &$symbols,array &$identities):ResourceForm{
		$components=[];foreach($node['children']as$index=>$child){$childPath=$path.'.children['.$index.']';$builder=$this->build($child,$childPath,$builders,$symbols,$identities);foreach($this->schemaComponents($child,$childPath,$builder,$builders)as$component){$components[]=$component;}}$schema=Schema::make($components)->columns((int)$node['properties']['columns'])->meta(['studio_layout'=>$node['properties']['layout']]);return$schema->toForm();
	}
	private function column(array $node):Column{
		$p=$node['properties'];$type=(string)$p['type'];$column=Column::make((string)$node['key'],$type);if(isset($p['label'])){$column=$column->label((string)$p['label']);}$column=match($type){'badge'=>$column->badge(),'money'=>$column->money((string)$p['currency']),'date'=>$column->date(),'datetime'=>$column->datetime(),'boolean'=>$column->booleanLabels(),default=>$column};if($p['sortable']){$column=$column->sortable();}if($p['searchable']){$column=$column->searchable();}if($p['toggleable']){$column=$column->toggleable();}if($p['hidden_by_default']){$column=$column->hiddenByDefault();}if(isset($p['limit'])){$column=$column->limit((int)$p['limit']);}if($p['wrap']){$column=$column->meta(['wrap'=>true]);}return$column;
	}
	private function dataSurface(array $node):PanelDataSurfaceDefinition{
		$p=$node['properties'];$projection=PanelDataSurfaceProjection::make($p['fields'],(string)$p['stable_key'],$p['slots'],$p['labels']);$surface=PanelDataSurfaceType::normalize((string)$p['surface']);$options=[];
		foreach(['label'=>'title','description'=>'description','empty_message'=>'empty_message','aria_label'=>'aria_label','endpoint'=>'endpoint','estimated_item_size'=>'estimated_item_size','virtualize'=>'virtualize']as$property=>$option){if(array_key_exists($property,$p)){$options[$option]=$p[$property];}}
		if($surface->advanced()){$canvas=[];foreach(['roles','aggregate','selection','cross_filter_group','cross_filter_field','drill_url','drill_parameter','editable','frozen_fields','show_labels','show_legend','snap_to_grid','zoom']as$property){if(array_key_exists($property,$p)){$canvas[$property]=$p[$property];}}$options['canvas']=PanelDataCanvasSpec::make($surface,$projection,$canvas);}
		return PanelDataSurfaceDefinition::make((string)$node['key'],(string)$p['resource'],(string)$p['source'],$surface,$projection,PanelDataSurfaceRange::make(0,(int)$p['window_length'],(int)$p['overscan_before'],(int)$p['overscan_after']),null,$options);
	}
	private function filter(array $node):TableFilter{
		$p=$node['properties'];$type=(string)$p['type'];$filter=TableFilter::make((string)$node['key'],$type);$filter=match($type){'date_range'=>$filter->dateRange(),'number_range'=>$filter->numberRange(),'range'=>$filter->range(),default=>$filter};if(isset($p['label'])){$filter=$filter->label((string)$p['label']);}if(isset($p['column'])){$filter=$filter->column((string)$p['column']);}if(isset($p['options'])){$filter=$filter->options($p['options']);}if(array_key_exists('default',$p)){$filter=$filter->default($p['default']);}if(isset($p['indicator'])){$filter=$filter->indicator((string)$p['indicator']);}$filter=$filter->indicatorTone((string)$p['tone']);return$filter;
	}
	private function tableView(array $node):TableView{
		$p=$node['properties'];$view=TableView::make((string)$node['key']);if(isset($p['label'])){$view=$view->label((string)$p['label']);}if($p['default']){$view=$view->default();}$view=$view->tone((string)$p['tone']);if(isset($p['search'])){$view=$view->search((string)$p['search']);}if(isset($p['columns'])){$view=$view->columns($p['columns']);}if(isset($p['filters'])){$view=$view->filters($p['filters']);}if(isset($p['sort_column'])){$view=$view->sort((string)$p['sort_column'],(string)$p['sort_direction']);}if(isset($p['per_page'])){$view=$view->perPage((int)$p['per_page']);}if(isset($p['density'])){$view=$view->density((string)$p['density']);}return$view;
	}
	private function table(array $node,string $path,array &$builders,array &$symbols,array &$identities):ResourceTable{
		$columns=[];$filters=[];$views=[];$filterPresentation=null;$viewPresentation=null;foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof PanelStudioBuilderCollection){$items=$builder->items();if($builder->kind()==='filters'){$filterPresentation=$builder->presentation();}if($builder->kind()==='table_views'){$viewPresentation=$builder->presentation();}}else{$items=[$builder];}foreach($items as$item){if($item instanceof Column){$columns[]=$item;}elseif($item instanceof TableFilter){$filters[]=$item;}elseif($item instanceof TableView){$views[]=$item;}}}$p=$node['properties'];$table=ResourceTable::make()->columns($columns)->filters($filters)->views($views)->perPage((int)$p['per_page'])->meta(['density'=>$p['density']]);if($filterPresentation!==null){$table=$table->filtersPresentation($filterPresentation);}if($viewPresentation!==null){$table=$table->viewsPresentation($viewPresentation);}if(isset($p['default_sort'])){$table=$table->defaultSort((string)$p['default_sort'],(string)$p['default_sort_direction']);}return$table;
	}
	private function boardColumn(array $node):PanelStudioBoardColumn{
		$p=$node['properties'];$name=(string)$node['key'];$status=trim((string)($p['status']??$name));$transition=trim((string)($p['transition']??('move_to_'.$name)));$presentation=[];foreach(['column_span'=>'span','basis'=>'basis','min_width'=>'min_width','max_width'=>'max_width','grow'=>'grow','order'=>'order','break_before'=>'break_before','fill_remainder'=>'fill_remainder']as$property=>$target){if(array_key_exists($property,$p)){$presentation[$target]=$p[$property];}}
		return new PanelStudioBoardColumn($name,$status,trim((string)($p['label']??''))?:ucwords(str_replace(['_','-','.'],' ',$status)),(string)$p['tone'],(bool)$p['accepts_moves'],$transition,(string)($p['transition_label']??''),array_key_exists('from',$p)?$p['from']:null,(string)($p['confirmation']??''),$presentation);
	}
	private function board(array $node,string $path,array &$builders,array &$symbols,array &$identities):Resource{
		$columns=[];foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof PanelStudioBoardColumn){$columns[]=$builder;}}
		$statuses=array_map(static fn(PanelStudioBoardColumn $column):string=>$column->status(),$columns);$columnDefinitions=[];$transitions=[];foreach($columns as$column){$columnDefinitions[]=$column->resourceDefinition();$transition=$column->transition($statuses);if($transition!==null){$transitions[]=$transition;}}
		$p=$node['properties'];$resource=Resource::make((string)$node['key'])->statusField((string)$p['status_field'])->statusBoardColumns($columnDefinitions)->statusTransitions($transitions)->statusWidgets((bool)$p['status_widgets']);if(isset($p['label'])){$resource=$resource->label((string)$p['label']);}if(isset($p['plural_label'])){$resource=$resource->pluralLabel((string)$p['plural_label']);}if(isset($p['description'])){$resource=$resource->navigationDescription((string)$p['description']);}if(isset($p['url'])){$resource=$resource->url((string)$p['url']);}if(isset($p['group'])){$resource=$resource->group((string)$p['group']);}if(isset($p['icon'])){$resource=$resource->icon((string)$p['icon']);}$resource=$resource->sort((int)$p['sort']);
		if(isset($p['record_key_field'])){$resource=$resource->recordKeyUsing((string)$p['record_key_field']);}if(isset($p['record_title_field'])){$resource=$resource->recordTitleUsing((string)$p['record_title_field']);}if(isset($p['record_subtitle_field'])){$resource=$resource->recordSubtitleUsing((string)$p['record_subtitle_field']);}if($p['hidden_from_navigation']){$resource=$resource->hideFromNavigation();}
		$resource=$resource->boardColumnsPresentation(['display'=>$p['layout'],'columns'=>$p['columns'],'gap'=>$p['gap'],'fit'=>$p['fit'],'masonry'=>$p['masonry'],'min_width'=>$p['min_width'],'final_row'=>$p['final_row']])->boardCardsPresentation(['display'=>$p['card_layout'],'columns'=>$p['card_columns'],'gap'=>$p['card_gap'],'fit'=>$p['card_fit'],'masonry'=>$p['card_masonry'],'min_width'=>$p['card_min_width'],'final_row'=>$p['card_final_row']]);foreach($columns as$column){if($column->presentation()!==[]){$resource=$resource->boardColumnItemPresentation($column->name(),$column->presentation());}}return$resource;
	}
	private function entry(array $node):InfolistEntry{
		$p=$node['properties'];$entry=InfolistEntry::make((string)$node['key'],(string)$p['type']);if(isset($p['label'])){$entry=$entry->label((string)$p['label']);}if(isset($p['icon'])){$entry=$entry->icon((string)$p['icon']);}if((string)$p['type']==='badge'){$entry=$entry->badge();}if(isset($p['prefix'])){$entry=$entry->prefix((string)$p['prefix']);}if(isset($p['suffix'])){$entry=$entry->suffix((string)$p['suffix']);}if($p['copyable']){$entry=$entry->copyable();}if(isset($p['empty_label'])){$entry=$entry->emptyLabel((string)$p['empty_label']);}if(isset($p['description'])){$entry=$entry->description((string)$p['description']);}if(isset($p['column_span'])){$entry=$entry->columnSpan((int)$p['column_span']);}return$entry;
	}
	private function show(array $node,string $path,array &$builders,array &$symbols,array &$identities):Infolist{
		$components=[];foreach($node['children']as$index=>$child){$childPath=$path.'.children['.$index.']';$builder=$this->build($child,$childPath,$builders,$symbols,$identities);foreach($this->schemaComponents($child,$childPath,$builder,$builders)as$component){$components[]=$component;}}return Infolist::make($components)->columns((int)$node['properties']['columns'])->meta(['studio_layout'=>$node['properties']['layout']]);
	}
	private function action(array $node):Action{
		$p=$node['properties'];$action=Action::make((string)$node['key']);if(isset($p['label'])){$action=$action->label((string)$p['label']);}if(isset($p['icon'])){$action=$action->icon((string)$p['icon']);}$action=$action->tone((string)$p['tone'])->style((string)$p['style'])->size((string)$p['size']);if($p['requires_confirmation']){$action=$action->requiresConfirmation();}if(isset($p['confirmation'])){$action=$action->confirmation((string)$p['confirmation']);}if($p['disabled']){$action=$action->disabled();}if(isset($p['redirect_to'])){$action=$action->redirectTo((string)$p['redirect_to']);}if(isset($p['success_message'])){$action=$action->successMessage((string)$p['success_message']);}return$action;
	}
	private function actionGroup(array $node,string $path,array &$builders,array &$symbols,array &$identities):ActionGroup{
		$actions=[];foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof Action){$actions[]=$builder;}}$p=$node['properties'];$group=ActionGroup::make((string)$node['key'])->actions($actions);if(isset($p['label'])){$group=$group->label((string)$p['label']);}if(isset($p['icon'])){$group=$group->icon((string)$p['icon']);}$group=$group->tone((string)$p['tone'])->style((string)$p['style'])->size((string)$p['size']);return$group;
	}
	private function toolbar(array $node,string $path,array &$builders,array &$symbols,array &$identities):ActionGroup{
		$actions=[];foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof Action){$actions[]=$builder;}elseif($builder instanceof ActionGroup){foreach($builder->actionsList()as$action){$actions[]=$action;}}}$group=ActionGroup::make((string)$node['key'])->actions($actions)->meta(['studio_layout'=>$node['properties']['layout']]);if(isset($node['properties']['label'])){$group=$group->label((string)$node['properties']['label']);}return$group;
	}
	private function widget(array $node):Widget{
		$p=$node['properties'];$widget=Widget::make((string)$node['key'],(string)$p['type']);if(isset($p['label'])){$widget=$widget->label((string)$p['label']);}if(array_key_exists('value',$p)){$widget=$widget->value($p['value']);}if(isset($p['description'])){$widget=$widget->description((string)$p['description']);}$widget=$widget->tone((string)$p['tone'])->sort((int)$p['sort']);if(isset($p['icon'])){$widget=$widget->icon((string)$p['icon']);}if(isset($p['url'])){$widget=$widget->url((string)$p['url']);}if(isset($p['group'])){$widget=$widget->group((string)$p['group']);}if(isset($p['unit'])){$widget=$widget->unit((string)$p['unit']);}if(isset($p['height'])){$widget=$widget->height((int)$p['height']);}if((string)$p['type']==='chart'){$widget=$widget->chart((string)$p['chart_type']);if(isset($p['labels'])){$widget=$widget->labels($p['labels']);}if(isset($p['data'])){$widget=$widget->data($p['data']);}}return$widget;
	}
	private function tab(array $node,string $path,array &$builders,array &$symbols,array &$identities):SchemaComponent{
		$children=[];foreach($node['children']as$index=>$child){$childPath=$path.'.children['.$index.']';$builder=$this->build($child,$childPath,$builders,$symbols,$identities);foreach($this->schemaComponents($child,$childPath,$builder,$builders)as$component){$children[]=$component;}}$tab=SchemaComponent::tab((string)$node['key'],$children);if(isset($node['properties']['label'])){$tab=$tab->label((string)$node['properties']['label']);}return$tab->meta(['columns'=>$node['properties']['columns']]);
	}
	private function tabs(array $node,string $path,array &$builders,array &$symbols,array &$identities):Schema{
		$tabs=[];foreach($node['children']as$index=>$child){$tab=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($tab instanceof SchemaComponent){$tabs[]=$tab;}}return Schema::make($tabs)->meta(['studio_layout'=>$node['properties']['layout']]);
	}
	private function navigationItem(array $node,string $path,array &$builders,array &$symbols,array &$identities,bool $group):NavigationItem{
		$children=[];foreach($node['children']as$index=>$child){$built=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($built instanceof NavigationItem){$children[]=$built;}}$p=$node['properties'];$item=NavigationItem::make((string)$node['key']);if(isset($p['label'])){$item=$item->label((string)$p['label']);}if(isset($p['url'])){$item=$item->url((string)$p['url']);}if(isset($p['icon'])){$item=$item->icon((string)$p['icon']);}if(isset($p['description'])){$item=$item->description((string)$p['description']);}$item=$item->sort((int)$p['sort']);if(array_key_exists('badge',$p)&&$p['badge']!==null){$item=$item->badge($p['badge']);}$item=$item->badgeTone((string)($p['tone']??'neutral'));if(($p['new_tab']??false)===true){$item=$item->newTab();}if(($p['hidden']??false)===true){$item=$item->hide();}if($group){$item=$item->folderOnly();}if($children!==[]){$item=$item->children($children);}return$item;
	}
	private function workflowState(array $node):WorkflowState{
		$p=$node['properties'];$metadata=$p['metadata'];foreach(['description','queue','tone']as$key){if(array_key_exists($key,$p)){$metadata[$key]=$p[$key];}}
		$options=['draft'=>$p['draft'],'terminal'=>$p['terminal'],'assignment_roles'=>$p['assignment_roles'],'metadata'=>$metadata];if(isset($p['label'])){$options['label']=$p['label'];}if(isset($p['sla_seconds'])){$options['sla_seconds']=$p['sla_seconds'];}return WorkflowState::make((string)$node['key'],$options);
	}
	private function workflowTransition(array $node):WorkflowTransition{
		$p=$node['properties'];$transition=WorkflowTransition::fromStates((string)$node['key'],$p['from_states'],(string)$p['to_state'])->roles($p['roles'])->permissions($p['permissions']);
		if($p['requires_approval']){$transition=$transition->approval(new WorkflowApprovalPolicy((int)$p['approval_quorum'],$p['approval_roles'],$p['approval_permissions'],(bool)$p['distinct_actors'],(bool)$p['allow_requester'],(int)$p['rejection_threshold'],isset($p['expires_after_seconds'])?(int)$p['expires_after_seconds']:null));}
		if(isset($p['assigned_actor'])||$p['assignment_roles']!==[]){$transition=$transition->assign(isset($p['assigned_actor'])?(string)$p['assigned_actor']:null,$p['assignment_roles']);}if(isset($p['sla_seconds'])){$transition=$transition->sla((int)$p['sla_seconds']);}if($p['reversible']){$transition=$transition->reversible();}
		$metadata=$p['metadata'];foreach(['label','description','tone']as$key){if(array_key_exists($key,$p)){$metadata[$key]=$p[$key];}}return$transition->metadata($metadata);
	}
	private function workflow(array $node,string $path,array &$builders,array &$symbols,array &$identities):WorkflowDefinition{
		$states=[];$transitions=[];foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof WorkflowState){$states[]=$builder;}elseif($builder instanceof WorkflowTransition){$transitions[]=$builder;}}
		$p=$node['properties'];$workflow=WorkflowDefinition::make((string)$node['key'],isset($p['label'])?(string)$p['label']:null);foreach($states as$state){$workflow=$workflow->state($state);}if(isset($p['initial_state'])){$workflow=$workflow->initial((string)$p['initial_state']);}foreach($transitions as$transition){$workflow=$workflow->transition($transition);}$metadata=$p['metadata'];if(isset($p['description'])){$metadata['description']=$p['description'];}$metadata['studio_require_terminal']=$p['require_terminal'];return$workflow->metadata($metadata)->assertValid();
	}
	private function page(array $node,string $path,array &$builders,array &$symbols,array &$identities):PanelStudioPageBundle{
		$surfacePaths=[];$surfaces=[];$actions=[];$widgets=[];$widgetPresentation=null;foreach($node['children']as$index=>$child){$childPath=$path.'.children['.$index.']';$builder=$this->build($child,$childPath,$builders,$symbols,$identities);$surfacePaths[]=$childPath;$surfaces[$childPath]=$builder;if($builder instanceof Action||$builder instanceof ActionGroup){$actions[]=$builder;}if($builder instanceof PanelStudioBuilderCollection&&$builder->kind()==='widget_grid'){$widgetPresentation=$builder->presentation();foreach($builder->items()as$item){if($item instanceof Widget){$widgets[]=$item;}}}}$p=$node['properties'];$page=PanelPage::make((string)$node['key']);if(isset($p['label'])){$page=$page->label((string)$p['label']);}if(isset($p['description'])){$page=$page->navigationDescription((string)$p['description']);}$page=$page->content((string)($p['description']??$p['label']??''));if(isset($p['url'])){$page=$page->url((string)$p['url']);}if(isset($p['group'])){$page=$page->group((string)$p['group']);}if(isset($p['icon'])){$page=$page->icon((string)$p['icon']);}$page=$page->sort((int)$p['sort'])->actions($actions)->widgets($widgets)->formsPresentation((string)$p['layout'])->tablesPresentation((string)$p['layout'])->meta(['studio_layout'=>$p['layout'],'studio_surface_paths'=>$surfacePaths]);if($widgetPresentation!==null){$page=$page->widgetsPresentation($widgetPresentation);}if($p['hidden_from_navigation']){$page=$page->hideFromNavigation();}return new PanelStudioPageBundle($page,$surfaces);
	}
	private function collection(array $node,string $path,array &$builders,array &$symbols,array &$identities):PanelStudioBuilderCollection{$items=[];foreach($node['children']as$index=>$child){$builder=$this->build($child,$path.'.children['.$index.']',$builders,$symbols,$identities);if($builder instanceof PanelStudioBuilderCollection){foreach($builder->items()as$item){$items[]=$item;}}elseif(is_object($builder)){$items[]=$builder;}}$p=$node['properties'];return new PanelStudioBuilderCollection((string)$node['kind'],(string)$node['key'],$items,(string)($p['layout']??'stack'),isset($p['columns'])?(int)$p['columns']:null);}
	/** @param object|array $builder @param array<string,object|array> $builders @return list<SchemaComponent> */
	private function schemaComponents(array $node,string $path,object|array $builder,array $builders):array{
		return match($node['kind']){
			'field'=>[$builder instanceof Field?SchemaComponent::field($builder):throw new \LogicException('Studio field builder mismatch.')],
			'infolist_entry'=>[$builder instanceof InfolistEntry?SchemaComponent::field($builder):throw new \LogicException('Studio entry builder mismatch.')],
			'form_section','show_section'=>[$builder instanceof FormSection?SchemaComponent::section($builder,$this->directChildren($node,$path,$builders)):throw new \LogicException('Studio section builder mismatch.')],
			'tabs'=>$builder instanceof Schema?$builder->componentsList():throw new \LogicException('Studio tabs builder mismatch.'),
			default=>[],
		};
	}
	/** @param array<string,object|array> $builders @return list<object> */ private function directChildren(array $node,string $path,array $builders):array{$items=[];foreach($node['children']as$index=>$_child){$builder=$builders[$path.'.children['.$index.']']??null;if(is_object($builder)){$items[]=$builder;}}return$items;}
	/** @param list<PanelStudioDiagnostic> $diagnostics @param array<string,bool> $checked */
	private function auditSchemaContracts(array $node,string $path,PanelStudioSchemaRegistry $registry,array &$diagnostics,array &$checked,?string $surfaceContext):void{
		static $auditedRegistry=null;$auditedRegistry??=PanelStudioSchemaRegistry::defaults();$kind=(string)$node['kind'];if($kind==='form'){$surfaceContext='form';}elseif(in_array($kind,['show','infolist'],true)){$surfaceContext='show';}if(($surfaceContext==='form'&&in_array($kind,['infolist_entry','show_section'],true))||($surfaceContext==='show'&&in_array($kind,['field','form_section'],true))){$diagnostics[]=new PanelStudioDiagnostic($path.'.kind','materializer_context_mismatch',"Studio component kind '{$kind}' is not compatible with the surrounding {$surfaceContext} surface.");}if($kind==='board'){$this->auditBoard($node,$path,$diagnostics);}if($kind==='data_surface'){$this->auditDataSurface($node,$path,$diagnostics);}if($kind==='workflow'){$this->auditWorkflow($node,$path,$diagnostics);}if(!isset($checked[$kind])){$checked[$kind]=true;$active=$registry->schema($kind);$audited=$auditedRegistry->schema($kind);if($active instanceof PanelStudioComponentSchema&&$audited instanceof PanelStudioComponentSchema){$activeContract=$active->jsonSerialize();$auditedContract=$audited->jsonSerialize();unset($activeContract['schema_version'],$auditedContract['schema_version']);if($activeContract!==$auditedContract){$diagnostics[]=new PanelStudioDiagnostic($path.'.kind','materializer_schema_contract_mismatch',"Studio component kind '{$kind}' uses a schema contract that is not supported by this audited materializer.");}}}foreach($node['children']as$index=>$child){$this->auditSchemaContracts($child,$path.'.children['.$index.']',$registry,$diagnostics,$checked,$surfaceContext);}
	}
	/** @param list<PanelStudioDiagnostic> $diagnostics */
	private function auditDataSurface(array $node,string $path,array &$diagnostics):void{
		try{$this->dataSurface($node);}catch(\Throwable$error){$diagnostics[]=new PanelStudioDiagnostic($path.'.properties','data_surface_contract_invalid',$error->getMessage());}
	}
	/** @param list<PanelStudioDiagnostic> $diagnostics */
	private function auditWorkflow(array $node,string $path,array &$diagnostics):void{
		try{$p=$node['properties'];$workflow=WorkflowDefinition::make((string)$node['key'],isset($p['label'])?(string)$p['label']:null);$statePaths=[];foreach($node['children']as$index=>$child){if($child['kind']==='workflow_state'){$state=$this->workflowState($child);$workflow=$workflow->state($state);$statePaths[$state->name()]=$path.'.children['.$index.']';}}if(isset($p['initial_state'])){$workflow=$workflow->initial((string)$p['initial_state']);}foreach($node['children']as$child){if($child['kind']==='workflow_transition'){$workflow=$workflow->transition($this->workflowTransition($child));}}$workflow->assertValid();$analysis=(new PanelWorkflowSimulator())->analyze($workflow);if($p['require_terminal']&&$analysis->terminalStates()===[]){$diagnostics[]=new PanelStudioDiagnostic($path.'.children','workflow_terminal_state_missing','Studio workflows configured to require completion need at least one terminal state.');}foreach($analysis->unreachableStates()as$state){$diagnostics[]=new PanelStudioDiagnostic(($statePaths[$state]??$path).'.key','workflow_state_unreachable',"Workflow state '{$state}' cannot be reached from the initial state.");}foreach($analysis->statesWithoutTerminalPath()as$state){$diagnostics[]=new PanelStudioDiagnostic(($statePaths[$state]??$path).'.key','workflow_terminal_path_missing',"Workflow state '{$state}' has no path to a terminal state.");}}
		catch(\Throwable$error){$diagnostics[]=new PanelStudioDiagnostic($path.'.children','workflow_contract_invalid',$error->getMessage());}
	}
	/** @param list<PanelStudioDiagnostic> $diagnostics */
	private function auditBoard(array $node,string $path,array &$diagnostics):void{
		$statuses=[];$declared=[];$transitions=[];foreach($node['children']as$index=>$child){$properties=$child['properties'];$status=trim((string)($properties['status']??$child['key']));$normalized=Resource::normalizeName($status);$childPath=$path.'.children['.$index.']';if($normalized===''||isset($statuses[$normalized])){$diagnostics[]=new PanelStudioDiagnostic($childPath.'.properties.status','duplicate_board_status',isset($statuses[$normalized])?'Studio board columns must resolve to unique status values.':'Studio board-column status cannot normalize to an empty value.');}else{$statuses[$normalized]=$childPath;$declared[$status]=true;}if(($properties['accepts_moves']??true)===true){$transition=Resource::normalizeName((string)($properties['transition']??('move_to_'.$child['key'])));if($transition===''||isset($transitions[$transition])){$diagnostics[]=new PanelStudioDiagnostic($childPath.'.properties.transition','duplicate_board_transition',isset($transitions[$transition])?'Studio board move transitions must have unique names.':'Studio board move transition cannot normalize to an empty value.');}else{$transitions[$transition]=$childPath;}}}
		foreach($node['children']as$index=>$child){$properties=$child['properties'];if(!array_key_exists('from',$properties)){continue;}foreach($properties['from']as$sourceIndex=>$source){if(!isset($declared[(string)$source])){$diagnostics[]=new PanelStudioDiagnostic($path.'.children['.$index.'].properties.from['.$sourceIndex.']','board_transition_source_missing','Studio board transition sources must name another declared board status.');}}}
	}
	private function baseManifest():array{$supported=PanelStudioSchemaRegistry::defaults()->kinds();$portableOnly=array_values(array_diff(PanelStudioDefinition::KINDS,$supported));sort($portableOnly,SORT_STRING);return['type'=>'panel_studio_materializer_manifest','version'=>self::MATERIALIZER_VERSION,'implementation_sha256'=>hash_file('sha256',__FILE__),'registry_contract_version'=>PanelStudioSchemaRegistry::REGISTRY_CONTRACT_VERSION,'compiler_version'=>PanelStudioCompiler::COMPILER_VERSION,'output'=>'actual_panel_builder_index','action_output'=>'declarative_builder_definition_only','supported_kinds'=>$supported,'portable_only_envelope_kinds'=>$portableOnly,'complete_definition_kind_coverage'=>$portableOnly===[],'board_output'=>'read_only_resource_with_host_bound_mutations','infolist_output'=>'first_class_infolist_builder','data_surface_output'=>'typed_callback_free_definition_with_host_bound_source','workflow_output'=>'validated_callback_free_workflow_definition','security'=>['registry_validation_required'=>true,'schema_contract_preflight'=>true,'surface_context_preflight'=>true,'data_surface_contract_preflight'=>true,'workflow_graph_preflight'=>true,'mutation_handlers'=>false,'host_mutation_binding_required'=>true,'data_source_binding_required'=>true,'query_resolvers'=>false,'workflow_callbacks'=>false,'user_callbacks'=>false,'framework_owned_field_resolvers'=>true,'user_classes'=>false,'raw_html'=>false,'php'=>false,'secrets'=>false,'stored_executable_objects'=>false],'visual_editor_runtime'=>false];}
}
