<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);
namespace Dataphyre\Panel;

/** Pure deterministic state transition engine shared by Studio store adapters. */
final class PanelStudioStateEngine {
	public const STATE_VERSION=1;
	private function __construct(){}
	public static function initialState():array{return['version'=>self::STATE_VERSION,'documents'=>[]];}
	public static function head(array $state,string $tenantId,string $documentId):?PanelStudioRevision{$entry=self::entry($state,$tenantId,$documentId);if($entry===null){return null;}$number=count($entry['revisions']);return PanelStudioRevision::hydrate($entry['revisions'][$number]);}
	public static function draft(array $state,string $tenantId,string $documentId):?PanelStudioDraft{$head=self::head($state,$tenantId,$documentId);if($head===null||$head->state()!=='draft'){return null;}$entry=self::entry($state,$tenantId,$documentId);return new PanelStudioDraft(self::document($entry['document']),$head);}
	public static function published(array $state,string $tenantId,string $documentId):?PanelStudioRevision{$entry=self::entry($state,$tenantId,$documentId);if($entry===null){return null;}$number=(int)($entry['published_revision']??0);$payload=$entry['revisions'][$number]??null;return is_array($payload)?PanelStudioRevision::hydrate($payload):null;}
	/** @return list<PanelStudioRevision> */ public static function history(array $state,string $tenantId,string $documentId,int $limit=100):array{$entry=self::entry($state,$tenantId,$documentId);if($entry===null){return[];}$rows=[];for($number=count($entry['revisions']);$number>=1&&count($rows)<max(1,min(1000,$limit));$number--){$rows[]=PanelStudioRevision::hydrate($entry['revisions'][$number]);}return$rows;}

	public static function save(array &$state,PanelStudioDocument $document,PanelStudioDefinition $definition,int $expectedRevision,string $idempotencyKey,string $actor,string $createdAt,?PanelStudioArtifact $artifact=null):PanelStudioReceipt{
		self::validState($state);self::actor($actor);self::idempotency($idempotencyKey);$artifact??=PanelStudioArtifact::portable($definition);$artifact->assertDefinition($definition);$scope=self::key($document->tenantId(),$document->id());$entry=self::entry($state,$document->tenantId(),$document->id());$request=self::requestHash(['operation'=>'save','document'=>$document->jsonSerialize(),'definition_hash'=>$definition->hash(),'artifact_fingerprint'=>$artifact->fingerprint(),'expected_revision'=>$expectedRevision,'actor'=>$actor]);
		$replay=self::replay($state,$scope,$idempotencyKey,$request,'save',$document->tenantId(),$document->id());if($replay){return$replay;}
		$head=is_array($entry)?count($entry['revisions']):0;if($head!==$expectedRevision){throw new \RuntimeException("Studio revision conflict: expected {$expectedRevision}, current {$head}.");}
		$parent=$head>0?(string)$entry['revisions'][(string)$head]['hash']:'';$revision=PanelStudioRevision::make($head+1,'draft','save',$definition,$actor,$createdAt,$parent,$head>0?$head:null,[],$artifact);
		if(!is_array($entry)){$entry=['document'=>$document->jsonSerialize(),'revisions'=>[],'published_revision'=>null,'idempotency'=>[]];}else{$stored=self::document($entry['document']);if($stored->tenantId()!==$document->tenantId()||$stored->id()!==$document->id()){throw new \UnexpectedValueException('Studio document scope integrity failed.');}$entry['document']=$document->jsonSerialize();}
		$entry['revisions'][(string)$revision->number()]=$revision->jsonSerialize();$receipt=PanelStudioReceipt::make('save',$document->tenantId(),$document->id(),$revision,$request);self::remember($entry,$idempotencyKey,$request,$receipt);$state['documents'][$scope]=$entry;return$receipt;
	}
	public static function approve(array &$state,string $tenantId,string $documentId,int $expectedRevision,string $idempotencyKey,string $actor,string $createdAt):PanelStudioReceipt{
		return self::transition($state,'approve',$tenantId,$documentId,$expectedRevision,$idempotencyKey,$actor,$createdAt,static function(PanelStudioRevision $head):array{
			if($head->state()!=='draft'){throw new \LogicException('Only Studio drafts can be approved.');}
			return['state'=>'draft','definition'=>$head->definition(),'source'=>$head->number(),'approvals'=>$head->approvals(),'artifact'=>$head->artifact()];
		},true);
	}
	public static function publish(array &$state,string $tenantId,string $documentId,int $expectedRevision,string $idempotencyKey,string $actor,int $requiredApprovals,string $createdAt):PanelStudioReceipt{
		if($requiredApprovals<0||$requiredApprovals>10){throw new \InvalidArgumentException('Studio publication approvals must be between zero and ten.');}$scope=self::key($tenantId,$documentId);return self::transition($state,'publish',$tenantId,$documentId,$expectedRevision,$idempotencyKey,$actor,$createdAt,static function(PanelStudioRevision $head)use($actor,$requiredApprovals):array{
			if($head->state()!=='draft'){throw new \LogicException('Only Studio drafts can be published.');}
			$approvals=array_values(array_diff($head->approvals(),[$actor]));if(count($approvals)<$requiredApprovals){throw new \LogicException('Studio publication does not have the required independent approvals.');}
			return['state'=>'published','definition'=>$head->definition(),'source'=>$head->number(),'approvals'=>$head->approvals(),'artifact'=>$head->artifact()];
		},false,static function(PanelStudioReceipt $receipt,array &$state)use($scope):void{$state['documents'][$scope]['published_revision']=$receipt->revision();},['required_approvals'=>$requiredApprovals]);
	}
	public static function rollback(array &$state,string $tenantId,string $documentId,int $targetRevision,int $expectedRevision,string $idempotencyKey,string $actor,string $createdAt):PanelStudioReceipt{
		$scope=self::key($tenantId,$documentId);$entry=self::entry($state,$tenantId,$documentId);$targetPayload=is_array($entry)?($entry['revisions'][(string)$targetRevision]??null):null;if(!is_array($targetPayload)){throw new \OutOfBoundsException('Studio rollback target does not exist.');}$target=PanelStudioRevision::hydrate($targetPayload);if($target->state()!=='published'){throw new \LogicException('Studio rollback targets must be published revisions.');}if(!$target->artifact()?->materializable()){throw new \LogicException('Only trusted materializable Studio revisions can be rollback targets.');}return self::transition($state,'rollback',$tenantId,$documentId,$expectedRevision,$idempotencyKey,$actor,$createdAt,static function(PanelStudioRevision $head,array $entry)use($targetRevision):array{
			$target=PanelStudioRevision::hydrate($entry['revisions'][(string)$targetRevision]);return['state'=>'published','definition'=>$target->definition(),'source'=>$target->number(),'approvals'=>[],'artifact'=>$target->artifact()];
		},false,static function(PanelStudioReceipt $receipt,array &$state)use($scope):void{$state['documents'][$scope]['published_revision']=$receipt->revision();},['target_revision'=>$targetRevision,'target_artifact_fingerprint'=>$target->artifactFingerprint()]);
	}
	public static function verify(array $state,string $tenantId,string $documentId):bool{
		try{self::entry($state,$tenantId,$documentId);return true;}catch(\Throwable){return false;}
	}
	public static function manifest(array $state):array{self::validState($state);$revisions=0;$published=0;$bound=0;$legacy=0;foreach($state['documents']as$scope=>$entry){if(!is_array($entry)||!is_array($entry['document']??null)){throw new \UnexpectedValueException('Studio document state is invalid.');}$document=self::document($entry['document']);if($scope!==self::key($document->tenantId(),$document->id())){throw new \UnexpectedValueException('Studio document storage scope is invalid.');}$entry=self::entry($state,$document->tenantId(),$document->id());$revisions+=count($entry['revisions']);foreach($entry['revisions']as$payload){$revision=PanelStudioRevision::hydrate($payload);$revision->artifact()?$bound++:$legacy++;}if($entry['published_revision']!==null){$published++;}}return['type'=>'panel_studio_store_state_manifest','version'=>self::STATE_VERSION,'documents'=>count($state['documents']),'revisions'=>$revisions,'artifact_bound_revisions'=>$bound,'unbound_legacy_revisions'=>$legacy,'published_documents'=>$published,'security'=>['definitions_json_only'=>true,'idempotency_keys_hashed'=>true,'hash_chained_history'=>true,'artifact_binding'=>true,'legacy_publication_fail_closed'=>true]];}

	/** @param callable(PanelStudioRevision,array<string,mixed>):array{state:string,definition:PanelStudioDefinition,source:int,approvals:list<string>,artifact:?PanelStudioArtifact} $build @param null|callable(PanelStudioReceipt,array<string,mixed>&):void $after */
	private static function transition(array &$state,string $operation,string $tenantId,string $documentId,int $expectedRevision,string $idempotencyKey,string $actor,string $createdAt,callable $build,bool $addActor=false,?callable $after=null,array $requestMeta=[]):PanelStudioReceipt{
		self::validState($state);self::actor($actor);self::idempotency($idempotencyKey);$scope=self::key($tenantId,$documentId);$entry=self::entry($state,$tenantId,$documentId);if(!is_array($entry)){throw new \OutOfBoundsException('Studio document does not exist.');}$sourcePayload=$entry['revisions'][(string)$expectedRevision]??null;$source=is_array($sourcePayload)?PanelStudioRevision::hydrate($sourcePayload):null;$sourceArtifact=$source?->artifact();if(!$sourceArtifact?->materializable()){throw new \LogicException('Only trusted materializable Studio revisions can be approved, published, or rolled back.');}$request=self::requestHash(['operation'=>$operation,'tenant_id'=>$tenantId,'document_id'=>$documentId,'expected_revision'=>$expectedRevision,'source_artifact_fingerprint'=>$sourceArtifact->fingerprint(),'actor'=>$actor]+$requestMeta);$replay=self::replay($state,$scope,$idempotencyKey,$request,$operation,$tenantId,$documentId);if($replay){return$replay;}
		$headNumber=count($entry['revisions']);if($headNumber!==$expectedRevision){throw new \RuntimeException("Studio revision conflict: expected {$expectedRevision}, current {$headNumber}.");}$head=PanelStudioRevision::hydrate($entry['revisions'][$headNumber]);$next=$build($head,$entry);$artifact=$next['artifact']??null;if(!$artifact instanceof PanelStudioArtifact){throw new \LogicException('Studio transitions cannot discard publication artifact bindings.');}$artifact->assertDefinition($next['definition']);$approvals=$next['approvals'];if($addActor){if(in_array($actor,$approvals,true)){throw new \LogicException('Studio draft is already approved by this principal.');}$approvals[]=$actor;}
		$revision=PanelStudioRevision::make($headNumber+1,$next['state'],$operation,$next['definition'],$actor,$createdAt,$head->hash(),$next['source'],$approvals,$artifact);$entry['revisions'][(string)$revision->number()]=$revision->jsonSerialize();$receipt=PanelStudioReceipt::make($operation,$tenantId,$documentId,$revision,$request);self::remember($entry,$idempotencyKey,$request,$receipt);$state['documents'][$scope]=$entry;if($after!==null){$after($receipt,$state);}return$receipt;
	}
	private static function entry(array $state,string $tenantId,string $documentId):?array{
		self::validState($state);$entry=$state['documents'][self::key($tenantId,$documentId)]??null;if(!is_array($entry)){return null;}if(!self::keys($entry,['document','revisions','published_revision','idempotency'])){throw new \UnexpectedValueException('Studio document entry shape is invalid.');}$document=self::document(is_array($entry['document']??null)?$entry['document']:[]);if($document->tenantId()!==$tenantId||$document->id()!==$documentId||!self::sameJson($entry['document'],$document->jsonSerialize())){throw new \UnexpectedValueException('Studio document scope integrity failed.');}
		$revisions=$entry['revisions']??null;if(!is_array($revisions)||$revisions===[]){throw new \UnexpectedValueException('Studio revision history is missing.');}$parent='';$published=[];$number=0;foreach($revisions as$key=>$payload){$number++;if(!is_array($payload)||(string)$key!==(string)$number){throw new \UnexpectedValueException('Studio revision ordering is invalid.');}$revision=PanelStudioRevision::hydrate($payload);if($revision->number()!==$number||$revision->parentHash()!==$parent||!self::sameJson($payload,$revision->jsonSerialize())){throw new \UnexpectedValueException('Studio revision chain is invalid.');}$parent=$revision->hash();if($revision->state()==='published'){$published[]=$number;}}
		$pointer=$entry['published_revision']??null;$latest=$published!==[]?$published[array_key_last($published)]:null;if($pointer!==$latest){throw new \UnexpectedValueException('Studio published revision pointer is invalid.');}
		if(!is_array($entry['idempotency'])){throw new \UnexpectedValueException('Studio idempotency state is invalid.');}foreach($entry['idempotency']as$digest=>$record){if(!is_string($digest)||preg_match('/^[a-f0-9]{64}$/',$digest)!==1||!is_array($record)||!self::keys($record,['request_hash','receipt'])||preg_match('/^[a-f0-9]{64}$/',(string)($record['request_hash']??''))!==1||!is_array($record['receipt']??null)){throw new \UnexpectedValueException('Studio idempotency state is invalid.');}$receipt=PanelStudioReceipt::hydrate($record['receipt']);$receiptRevision=$revisions[$receipt->revision()]??null;if(!self::sameJson($record['receipt'],$receipt->jsonSerialize())||$receipt->tenantId()!==$tenantId||$receipt->documentId()!==$documentId||$receipt->requestHash()!==$record['request_hash']||!is_array($receiptRevision)){throw new \UnexpectedValueException('Studio idempotency scope is invalid.');}$revision=PanelStudioRevision::hydrate($receiptRevision);if($revision->action()!==$receipt->operation()||$revision->hash()!==$receipt->revisionHash()||$revision->artifactFingerprint()!==$receipt->artifactFingerprint()){throw new \UnexpectedValueException('Studio idempotency revision is invalid.');}}
		return$entry;
	}
	private static function document(array $payload):PanelStudioDocument{return PanelStudioDocument::make((string)($payload['tenant_id']??''),(string)($payload['id']??''),(string)($payload['title']??''),is_array($payload['meta']??null)?$payload['meta']:[]);}
	private static function key(string $tenantId,string $documentId):string{PanelStudioDocument::scope($tenantId,'tenant');PanelStudioDocument::scope($documentId,'document');return hash('sha256',$tenantId."\0".$documentId);}
	private static function actor(string $actor):void{PanelStudioDocument::scope($actor,'principal');}
	private static function idempotency(string $key):void{if(trim($key)===''||strlen($key)>256||str_contains($key,"\0")){throw new \InvalidArgumentException('Studio idempotency keys must contain 1 to 256 safe bytes.');}}
	private static function requestHash(array $request):string{return hash('sha256',json_encode($request,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));}
	private static function replay(array $state,string $scope,string $idempotencyKey,string $requestHash,string $operation,string $tenantId,string $documentId):?PanelStudioReceipt{
		$record=$state['documents'][$scope]['idempotency'][hash('sha256',$idempotencyKey)]??null;if(!is_array($record)){return null;}if(!hash_equals((string)($record['request_hash']??''),$requestHash)){throw new \RuntimeException('Studio idempotency key was reused for a different request.');}
		$receipt=PanelStudioReceipt::hydrate(is_array($record['receipt']??null)?$record['receipt']:[]);$revisionPayload=$state['documents'][$scope]['revisions'][$receipt->revision()]??null;if($receipt->operation()!==$operation||$receipt->tenantId()!==$tenantId||$receipt->documentId()!==$documentId||$receipt->requestHash()!==$requestHash||!is_array($revisionPayload)){throw new \UnexpectedValueException('Stored Studio idempotency receipt is invalid.');}$revision=PanelStudioRevision::hydrate($revisionPayload);if($revision->action()!==$operation||!hash_equals($revision->hash(),$receipt->revisionHash())||$revision->artifactFingerprint()!==$receipt->artifactFingerprint()){throw new \UnexpectedValueException('Stored Studio idempotency receipt does not match revision history.');}return$receipt->replay();
	}
	private static function remember(array &$entry,string $idempotencyKey,string $requestHash,PanelStudioReceipt $receipt):void{$entry['idempotency'][hash('sha256',$idempotencyKey)]=['request_hash'=>$requestHash,'receipt'=>$receipt->jsonSerialize()];while(count($entry['idempotency'])>1000){array_shift($entry['idempotency']);}}
	private static function validState(array $state):void{if(!self::keys($state,['version','documents'])||($state['version']??null)!==self::STATE_VERSION||!is_array($state['documents']??null)){throw new \UnexpectedValueException('Studio store state schema is invalid.');}}
	private static function keys(array $value,array $expected):bool{$keys=array_keys($value);sort($keys,SORT_STRING);sort($expected,SORT_STRING);return$keys===$expected;}
	private static function sameJson(array $left,array $right):bool{self::sort($left);self::sort($right);return json_encode($left,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR)===json_encode($right,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);}
	private static function sort(array &$value):void{if(!array_is_list($value)){ksort($value,SORT_STRING);}foreach($value as&$item){if(is_array($item)){self::sort($item);}}}
}
