<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Signed durable outcome for an atomic domain activation state transition. */
final class PanelDomainActivationReceipt implements \JsonSerializable {
	private readonly string $digest;
	/** @param array<string,mixed> $migration */
	private function __construct(private readonly string $id,private readonly string $operation,private readonly string $domainId,private readonly ?string $fromDigest,private readonly ?string $toDigest,private readonly string $planFingerprint,private readonly string $actorId,private readonly int $revision,private readonly string $idempotencyHash,private readonly string $hostBefore,private readonly string $hostAfter,private readonly array $migration,private readonly string $committedAt,private readonly string $keyId,private readonly string $signature){
		PanelOperationsGuard::identifier($id,'domain activation receipt id');if(!in_array($operation,['activate','rollback','deactivate','reconcile'],true)){throw new \InvalidArgumentException('Domain activation receipt operation is invalid.');}PanelOperationsGuard::name($domainId,'domain activation receipt domain id');foreach([$fromDigest,$toDigest]as$digest){if($digest!==null&&preg_match('/^[a-f0-9]{64}$/D',$digest)!==1){throw new \InvalidArgumentException('Domain activation receipt compilation digest is invalid.');}}foreach([$planFingerprint,$idempotencyHash,$hostBefore,$hostAfter]as$digest){if(preg_match('/^[a-f0-9]{64}$/D',$digest)!==1){throw new \InvalidArgumentException('Domain activation receipt fingerprint is invalid.');}}PanelOperationsGuard::identifier($actorId,'domain activation receipt actor');if($revision<1){throw new \InvalidArgumentException('Domain activation receipt revision is invalid.');}PanelOperationsGuard::safeMetadata($migration,1024);PanelOperationsGuard::name($keyId,'domain activation receipt key id');if(preg_match('/^[a-f0-9]{64}$/D',$signature)!==1){throw new \InvalidArgumentException('Domain activation receipt signature is invalid.');}$this->digest=PanelOperationsGuard::digest($this->unsigned());
	}
	/** @param array<string,mixed> $migration */public static function sign(string $id,string $operation,string $domainId,?string $fromDigest,?string $toDigest,string $planFingerprint,string|int $actorId,int $revision,string $idempotencyHash,string $hostBefore,string $hostAfter,array $migration,string|int|\DateTimeInterface $committedAt,string $keyId,string $key):self {if(strlen($key)<32){throw new \InvalidArgumentException('Domain activation receipt keys require at least 32 bytes.');}$at=PanelOperationsGuard::instant($committedAt);$migration=PanelOperationsGuard::safeMetadata($migration,1024);$prototype=new self($id,$operation,$domainId,$fromDigest,$toDigest,$planFingerprint,(string)$actorId,$revision,$idempotencyHash,$hostBefore,$hostAfter,$migration,$at,$keyId,str_repeat('0',64));return new self($id,$operation,$domainId,$fromDigest,$toDigest,$planFingerprint,(string)$actorId,$revision,$idempotencyHash,$hostBefore,$hostAfter,$migration,$at,$keyId,hash_hmac('sha256',$prototype->digest,$key));}
	/** @param array<string,mixed> $payload */public static function hydrate(array $payload):self {$required=['type','schema_version','api_version','version','id','operation','domain_id','from_digest','to_digest','plan_fingerprint','actor_id','revision','idempotency_hash','host_before','host_after','migration','committed_at','digest','key_id','signature'];$keys=array_keys($payload);sort($keys,SORT_STRING);sort($required,SORT_STRING);if($keys!==$required||($payload['type']??null)!=='panel_domain_activation_receipt'||($payload['version']??null)!==1||!is_string($payload['id']??null)||!is_string($payload['operation']??null)||!is_string($payload['domain_id']??null)||(!is_string($payload['from_digest'])&&$payload['from_digest']!==null)||(!is_string($payload['to_digest'])&&$payload['to_digest']!==null)||!is_string($payload['plan_fingerprint']??null)||!is_string($payload['actor_id']??null)||!is_int($payload['revision']??null)||!is_string($payload['idempotency_hash']??null)||!is_string($payload['host_before']??null)||!is_string($payload['host_after']??null)||!is_array($payload['migration']??null)||!is_string($payload['committed_at']??null)||!is_string($payload['digest']??null)||!is_string($payload['key_id']??null)||!is_string($payload['signature']??null)){throw new \UnexpectedValueException('Stored domain activation receipt shape is invalid.');}$self=new self($payload['id'],$payload['operation'],$payload['domain_id'],$payload['from_digest'],$payload['to_digest'],$payload['plan_fingerprint'],$payload['actor_id'],$payload['revision'],$payload['idempotency_hash'],$payload['host_before'],$payload['host_after'],$payload['migration'],PanelOperationsGuard::instant($payload['committed_at']),$payload['key_id'],$payload['signature']);if(!hash_equals($self->digest,$payload['digest'])){throw new \UnexpectedValueException('Stored domain activation receipt digest is invalid.');}return$self;}
	/** @param array<string,string> $keys */public function verify(array $keys):bool {$key=$keys[$this->keyId]??null;return is_string($key)&&strlen($key)>=32&&hash_equals($this->signature,hash_hmac('sha256',$this->digest,$key));}
	public function id():string{return$this->id;}public function operation():string{return$this->operation;}public function domainId():string{return$this->domainId;}public function fromDigest():?string{return$this->fromDigest;}public function toDigest():?string{return$this->toDigest;}public function revision():int{return$this->revision;}public function digest():string{return$this->digest;}public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_domain_activation_receipt','version'=>1]+$this->unsigned()+['digest'=>$this->digest,'key_id'=>$this->keyId,'signature'=>$this->signature]);}/** @return array<string,mixed> */private function unsigned():array{return['id'=>$this->id,'operation'=>$this->operation,'domain_id'=>$this->domainId,'from_digest'=>$this->fromDigest,'to_digest'=>$this->toDigest,'plan_fingerprint'=>$this->planFingerprint,'actor_id'=>$this->actorId,'revision'=>$this->revision,'idempotency_hash'=>$this->idempotencyHash,'host_before'=>$this->hostBefore,'host_after'=>$this->hostAfter,'migration'=>$this->migration,'committed_at'=>$this->committedAt];}
}
