<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/**
 * Production UI templates for the new operations, workflow, relationship,
 * notification, media, security, and developer platform surfaces.
 *
 * Templates use the existing normalized Panel visual primitives so every page
 * inherits dark, glass, mobile, density, and accessibility behavior.
 */
final class PanelPlatformTemplate {
	/** @param array<string,mixed> $snapshot */
	public static function operationsOs(array $snapshot,array $options=[]):PanelPageResult {
		$status=is_array($snapshot['status']??null)?$snapshot['status']:[];$fabric=is_array($snapshot['fabric']??null)?$snapshot['fabric']:[];$work=is_array($snapshot['work']??null)?$snapshot['work']:[];$domains=is_array($snapshot['domains']??null)?$snapshot['domains']:[];$policy=is_array($snapshot['policy']??null)?$snapshot['policy']:[];$intelligence=is_array($snapshot['intelligence']??null)?$snapshot['intelligence']:[];$compliance=is_array($snapshot['compliance']??null)?$snapshot['compliance']:[];$fleet=is_array($snapshot['fleet']??null)?$snapshot['fleet']:[];
		$tenant=is_string($snapshot['tenant_id']??null)?$snapshot['tenant_id']:null;$actionUrl=(string)($options['action_url']??'');$controlTenant=trim((string)($options['control_tenant']??$tenant??''));
		$nav=[];foreach(['attention'=>'Attention','work'=>'Work','fabric'=>'Command fabric','domains'=>'Domains','policy'=>'Policy','intelligence'=>'Intelligence','compliance'=>'Compliance','fleet'=>'Fleet']as$id=>$label){$nav[]='<a href="#dp-ops-'.self::e($id).'">'.self::e($label).'</a>';}
		$body='<nav class="dp-ops-anchor-nav" aria-label="Operations OS sections">'.implode('',$nav).'</nav>';
		$body.='<dl class="dp-ops-strip" aria-label="Operations OS status">'
			.self::opsStat('Command chain',($fabric['integrity']['ok']??false)?'Verified':'Attention',($fabric['integrity']['ok']??false)?'success':'danger','Sequence '.(int)($fabric['sequence']??0))
			.self::opsStat('Compliance',($compliance['verified']??false)?'Verified':'Attention',($compliance['verified']??false)?'success':'danger',(int)($compliance['evidence_count']??0).' evidence records')
			.self::opsStat('Domains',(string)(int)($domains['active_count']??0),'neutral',(int)($domains['drifted_count']??0).' drifted')
			.self::opsStat('Commands',(string)(int)($fabric['commands']??0),(int)($fabric['executing']??0)>0?'info':'neutral',(int)($fabric['executing']??0).' executing')
			.self::opsStat('Tenant',$tenant??'Global control plane',$tenant!==null?'info':'neutral',$tenant!==null?'Scoped work queue':'No tenant work loaded')
			.'</dl>';

		$attention=is_array($snapshot['attention']??null)?$snapshot['attention']:[];$attentionItems=[];
		foreach($attention as$item){if(!is_array($item)){continue;}$section=(string)($item['section']??'attention');$attentionItems[]='<li data-severity="'.self::e((string)($item['severity']??'info')).'"><span class="dp-ops-signal" aria-hidden="true"></span><div><strong>'.self::e(self::humanize((string)($item['code']??'attention'))).'</strong><p>'.self::e((string)($item['message']??'')).'</p></div><a href="#dp-ops-'.self::e($section).'">Inspect</a></li>';}
		$body.='<section id="dp-ops-attention" aria-labelledby="dp-ops-attention-heading">'.self::sectionHeading('dp-ops-attention-heading','Attention',count($attentionItems).' signals').($attentionItems!==[]?'<ol class="dp-ops-attention-list">'.implode('',$attentionItems).'</ol>':self::empty('No active attention signals.','Integrity, policy, work, compliance, release, and fleet checks are clear.')).'</section>';

		$workRows=[];foreach((array)($work['queue']??[])as$item){if(!is_array($item)){continue;}$workRows[]='<tr><td data-label="Work item"><strong>'.self::e((string)($item['title']??$item['id']??'Work item')).'</strong><small>'.self::e((string)($item['id']??'')).'</small></td><td data-label="State">'.self::badge((string)($item['state']??'unknown'),self::statusTone((string)($item['state']??'unknown'))).'</td><td data-label="Priority">'.self::e((string)($item['priority']??0)).'</td><td data-label="Queue">'.self::e((string)($item['queue']??'Unqueued')).'</td><td data-label="Assignee">'.self::e((string)($item['assignee']??'Unassigned')).'</td><td data-label="Due"><time>'.self::e((string)($item['due_at']??'Not set')).'</time></td></tr>';}
		$workMeta=($work['scoped']??false)===true?(int)($work['sla']['total']??count($workRows)).' items, '.(int)($work['sla']['overdue']??0).' overdue':'Tenant context required';
		$body.='<section id="dp-ops-work" aria-labelledby="dp-ops-work-heading">'.self::sectionHeading('dp-ops-work-heading','Universal work queue',$workMeta);
		if(($work['scoped']??false)!==true){$body.=self::empty('No tenant work context.','Supply an authorized tenant context to inspect its queue, SLA, assignments, and audit chain.');}
		elseif($workRows===[]){$body.=self::empty('The tenant queue is empty.','Cases, incidents, approvals, and tasks will appear here when created.');}
		else{$body.='<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Work item</th><th>State</th><th>Priority</th><th>Queue</th><th>Assignee</th><th>Due</th></tr></thead><tbody>'.implode('',$workRows).'</tbody></table></div>';}
		$body.='</section>';

		$journalRows=[];foreach((array)($fabric['journal']??[])as$entry){if(!is_array($entry)){continue;}$journalRows[]='<tr><td data-label="Command"><strong>'.self::e(self::humanize((string)($entry['command']??''))).'</strong><small>'.self::e((string)($entry['id']??'')).'</small></td><td data-label="Tenant">'.self::e((string)($entry['tenant_id']??'')).'</td><td data-label="Risk">'.self::badge((string)($entry['risk']??'unknown'),in_array(($entry['risk']??''),['high','critical'],true)?'danger':'neutral').'</td><td data-label="Status">'.self::badge((string)($entry['status']??'unknown'),self::statusTone((string)($entry['status']??'unknown'))).'</td><td data-label="Attempts">'.self::e((string)($entry['attempts']??0)).'</td><td data-label="Updated"><time>'.self::e((string)($entry['updated_at']??'')).'</time></td></tr>';}
		$eventRows=[];foreach((array)($fabric['event_stream']??[])as$event){if(!is_array($event)){continue;}$eventRows[]='<tr><td data-label="Sequence">'.self::e((string)($event['sequence']??0)).'</td><td data-label="Event"><strong>'.self::e(self::humanize((string)($event['event_type']??''))).'</strong><small>'.self::e((string)($event['id']??'')).'</small></td><td data-label="Aggregate">'.self::e((string)($event['aggregate_type']??'')).' / '.self::e((string)($event['aggregate_id']??'')).'</td><td data-label="Tenant">'.self::e((string)($event['tenant_id']??'')).'</td><td data-label="Occurred"><time>'.self::e((string)($event['occurred_at']??'')).'</time></td></tr>';}
		$subscriberRows=[];foreach((array)($fabric['subscribers']??[])as$subscriber){if(!is_array($subscriber)){continue;}$name=(string)($subscriber['name']??'');$action=$actionUrl!==''?self::postButton($actionUrl,'','operation','drain_subscriber','Drain',self::consoleFormFields($options,['subscriber'=>$name,'limit'=>(string)($options['subscriber_limit']??100)])):'';$subscriberRows[]='<tr><td data-label="Subscriber"><strong>'.self::e(self::humanize($name)).'</strong><small>'.self::e($name).'</small></td><td data-label="Patterns">'.self::e(implode(', ',(array)($subscriber['patterns']??[]))).'</td><td data-label="Cursor">'.self::e((string)($subscriber['cursor']??0)).'</td><td data-label="Actions"><div class="dp-panel-actions">'.$action.'</div></td></tr>';}
		$recovery=$actionUrl!==''?self::postButton($actionUrl,'','operation','recover_stale','Recover stale commands',self::consoleFormFields($options,['stale_after_seconds'=>(string)($options['stale_after_seconds']??300),'limit'=>(string)($options['recovery_limit']??25)])):'';
		$body.='<section id="dp-ops-fabric" aria-labelledby="dp-ops-fabric-heading">'.self::sectionHeading('dp-ops-fabric-heading','Command fabric',(int)($fabric['commands']??0).' commands, '.(int)($fabric['events']??0).' events').'<div class="dp-ops-section-actions"><p>Inputs, idempotency keys, event payloads, signatures, and lease ownership are redacted.</p><div class="dp-panel-actions">'.$recovery.'</div></div><h3>Command journal</h3>'.($journalRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Command</th><th>Tenant</th><th>Risk</th><th>Status</th><th>Attempts</th><th>Updated</th></tr></thead><tbody>'.implode('',$journalRows).'</tbody></table></div>':self::empty('No commands have been journaled.','Governed mutations will appear here without their input payloads.')).'<h3>Signed event stream</h3>'.($eventRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Sequence</th><th>Event</th><th>Aggregate</th><th>Tenant</th><th>Occurred</th></tr></thead><tbody>'.implode('',$eventRows).'</tbody></table></div>':self::empty('No events after this cursor.','Committed command events will appear here as redacted metadata.')).'<h3>Projectors</h3>'.($subscriberRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Subscriber</th><th>Patterns</th><th>Cursor</th><th>Actions</th></tr></thead><tbody>'.implode('',$subscriberRows).'</tbody></table></div>':self::empty('No local projectors are registered.','Realtime, notifications, and compliance projectors appear here when attached.')).'</section>';

		$domainRows=[];foreach((array)($domains['items']??[])as$domain){if(!is_array($domain)){continue;}$state=($domain['active']??false)?(($domain['drifted']??false)?'Drifted':'Active'):'Installed';$domainRows[]='<tr><td data-label="Domain"><strong>'.self::e(self::humanize((string)($domain['id']??''))).'</strong><small>'.self::e((string)($domain['id']??'')).'</small></td><td data-label="Version">'.self::e((string)($domain['version']??'Unavailable')).'</td><td data-label="State">'.self::badge($state,$state==='Active'?'success':($state==='Drifted'?'danger':'neutral')).'</td><td data-label="Trust">'.self::badge(($domain['trusted']??false)?'Verified':'Untrusted',($domain['trusted']??false)?'success':'danger').'</td><td data-label="History">'.self::e((string)($domain['history_depth']??0)).'</td><td data-label="Drift channels">'.self::e(implode(', ',(array)($domain['drift_channels']??[]))?:'None').'</td></tr>';}
		$body.='<section id="dp-ops-domains" aria-labelledby="dp-ops-domains-heading">'.self::sectionHeading('dp-ops-domains-heading','Domain runtime',(int)($domains['active_count']??0).' active, '.(int)($domains['drifted_count']??0).' drifted').($domainRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Domain</th><th>Version</th><th>State</th><th>Trust</th><th>History</th><th>Drift channels</th></tr></thead><tbody>'.implode('',$domainRows).'</tbody></table></div>':self::empty('No domains are installed.','Signed domain applications will appear after compilation or activation.')).'</section>';

		$switchItems=[];foreach((array)($policy['kill_switches']??[])as$pattern){$release=$actionUrl!==''&&$controlTenant!==''?self::consoleCommandButton($actionUrl,$controlTenant,'operations_os.policy.release','operations_os.policy.release',['pattern'=>(string)$pattern],'Release',$options):'';$switchItems[]='<li><code>'.self::e((string)$pattern).'</code><div class="dp-panel-actions">'.$release.'</div></li>';}
		$body.='<section id="dp-ops-policy" aria-labelledby="dp-ops-policy-heading">'.self::sectionHeading('dp-ops-policy-heading','Portable policy','Revision '.(int)($policy['revision']??0)).'<dl class="dp-ops-detail-grid"><div><dt>Signed bundles</dt><dd>'.(int)($policy['bundle_count']??0).'</dd></div><div><dt>Default action</dt><dd>'.(($policy['default_deny']??false)?'Deny':'Unverified').'</dd></div><div><dt>Deny overrides</dt><dd>'.(($policy['deny_overrides']??false)?'Enabled':'Unavailable').'</dd></div><div><dt>Kill switches</dt><dd>'.count($switchItems).'</dd></div></dl>'.($switchItems!==[]?'<ul class="dp-ops-control-list">'.implode('',$switchItems).'</ul>':self::empty('No policy kill switches are engaged.','Emergency ability stops will appear here when active.')).'</section>';

		$operator=is_array($intelligence['operator']??null)?$intelligence['operator']:[];$closed=is_array($intelligence['closed_loop']??null)?$intelligence['closed_loop']:[];$modelRows=[];foreach((array)($operator['models']??[])as$model){if(!is_array($model)){continue;}$modelRows[]='<tr><td data-label="Model"><strong>'.self::e((string)($model['model']??$model['id']??'')).'</strong><small>'.self::e((string)($model['provider']??'')).'</small></td><td data-label="Health">'.self::badge((string)($model['health']??'unknown'),self::statusTone((string)($model['health']??'unknown'))).'</td><td data-label="Regions">'.self::e(implode(', ',(array)($model['regions']??[]))).'</td><td data-label="Classifications">'.self::e(implode(', ',(array)($model['classifications']??[]))).'</td></tr>';}
		$proposalRows=[];foreach((array)($closed['proposals']??[])as$proposal){if(!is_array($proposal)){continue;}$id=(string)($proposal['id']??'');$state=(string)($proposal['status']??'unknown');$tenantId=(string)($proposal['tenant_id']??'');$fields=self::consoleFormFields($options,['proposal_id'=>$id,'tenant_id'=>$tenantId,'expected_revision'=>(string)($proposal['revision']??0)]);$actions='';if($actionUrl!==''&&in_array($state,['awaiting_approval','ready'],true)){$actions.=self::postButton($actionUrl,'','operation','intelligence_approve','Approve',$fields);}if($actionUrl!==''&&$state==='ready'){$actions.=self::postButton($actionUrl,'','operation','intelligence_dispatch','Confirm & dispatch',$fields+['confirmed'=>'1']);}$proposalRows[]='<tr><td data-label="Proposal"><strong>'.self::e(self::humanize((string)($proposal['command']??''))).'</strong><small>'.self::e($id).'</small></td><td data-label="Risk">'.self::badge((string)($proposal['risk']??'unknown'),in_array(($proposal['risk']??''),['high','critical'],true)?'danger':'neutral').'</td><td data-label="Status">'.self::badge($state,self::statusTone($state)).'</td><td data-label="Approvals">'.(int)($proposal['approval_count']??0).' / '.(int)($proposal['required_approvals']??0).'</td><td data-label="Attempts">'.(int)($proposal['dispatch_attempts']??0).'</td><td data-label="Updated"><time>'.self::e((string)($proposal['updated_at']??'')).'</time></td><td data-label="Actions"><div class="dp-panel-actions">'.$actions.'</div></td></tr>';}
		$recoverIntelligence=$actionUrl!==''&&$controlTenant!==''?self::postButton($actionUrl,'','operation','intelligence_recover','Recover proposals',self::consoleFormFields($options,['tenant_id'=>$controlTenant,'stale_after_seconds'=>(string)($options['intelligence_stale_after_seconds']??300),'limit'=>(string)($options['intelligence_recovery_limit']??25)])):'';
		$body.='<section id="dp-ops-intelligence" aria-labelledby="dp-ops-intelligence-heading">'.self::sectionHeading('dp-ops-intelligence-heading','Governed intelligence',(int)($closed['proposal_count']??0).' proposals, '.(int)($closed['feedback_count']??0).' outcomes').'<dl class="dp-ops-detail-grid"><div><dt>Signals</dt><dd>'.(int)($closed['signal_count']??0).'</dd></div><div><dt>Awaiting approval</dt><dd>'.(int)($closed['proposal_statuses']['awaiting_approval']??0).'</dd></div><div><dt>Dispatching</dt><dd>'.(int)($closed['proposal_statuses']['dispatching']??0).'</dd></div><div><dt>Measured effectiveness</dt><dd>'.self::basisPoints((int)($closed['effectiveness']['average_effectiveness_basis_points']??0)).'</dd></div><div><dt>Operator tools</dt><dd>'.(int)($operator['tool_count']??0).'</dd></div><div><dt>Semantic metrics</dt><dd>'.(int)($intelligence['semantics']['metric_count']??0).'</dd></div><div><dt>Lineage</dt><dd>'.(int)($intelligence['lineage']['node_count']??0).' nodes / '.(int)($intelligence['lineage']['edge_count']??0).' edges</dd></div><div><dt>Executor</dt><dd>'.(($operator['executor_configured']??false)?'Configured':'Plan only').'</dd></div></dl><div class="dp-ops-section-actions"><p>Inputs, evidence, identities, idempotency material, and approval attestations remain encrypted or redacted.</p><div class="dp-panel-actions">'.$recoverIntelligence.'</div></div><h3>Recommendation proposals</h3>'.($proposalRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Proposal</th><th>Risk</th><th>Status</th><th>Approvals</th><th>Attempts</th><th>Updated</th><th>Actions</th></tr></thead><tbody>'.implode('',$proposalRows).'</tbody></table></div>':self::empty('No governed proposals.','Signed intelligence signals can open independently approved command proposals here.')).'<h3>Operator models</h3>'.($modelRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Model</th><th>Health</th><th>Regions</th><th>Classifications</th></tr></thead><tbody>'.implode('',$modelRows).'</tbody></table></div>':self::empty('No operator models are registered.','The governed operator can remain plan-only until a model adapter is attached.')).'</section>';

		$body.='<section id="dp-ops-compliance" aria-labelledby="dp-ops-compliance-heading">'.self::sectionHeading('dp-ops-compliance-heading','Continuous compliance',($compliance['verified']??false)?'Evidence chain verified':'Evidence chain needs attention').'<dl class="dp-ops-detail-grid"><div><dt>Controls</dt><dd>'.(int)($compliance['control_count']??0).'</dd></div><div><dt>Evidence records</dt><dd>'.(int)($compliance['evidence_count']??0).'</dd></div><div><dt>Active holds</dt><dd>'.(int)($compliance['active_hold_count']??0).'</dd></div><div><dt>Ledger sequence</dt><dd>'.(int)($compliance['sequence']??0).'</dd></div></dl><p class="dp-ops-redaction-note">Evidence contents and signing material remain inside the compliance ledger. This surface exposes chain state and bounded counts only.</p></section>';

		$federation=is_array($fleet['federation']??null)?$fleet['federation']:[];$nodeRows=[];foreach((array)($federation['nodes']??[])as$node){if(!is_array($node)){continue;}$nodeRows[]='<tr><td data-label="Node"><strong>'.self::e((string)($node['id']??'')).'</strong></td><td data-label="Environment">'.self::e(self::humanize((string)($node['environment']??''))).'</td><td data-label="Region">'.self::e((string)($node['region']??'')).'</td><td data-label="Capabilities">'.(int)($node['capability_count']??0).'</td><td data-label="Attestation expires"><time>'.self::e((string)($node['expires_at']??'')).'</time></td></tr>';}
		$gateway=is_array($federation['gateway']??null)?$federation['gateway']:[];$outboxRows=[];foreach((array)($gateway['recent_outbox']??[])as$message){if(!is_array($message)){continue;}$outboxRows[]='<tr><td data-label="Message"><strong>'.self::e(self::humanize((string)($message['kind']??''))).'</strong><small>'.self::e((string)($message['id']??'')).'</small></td><td data-label="Target">'.self::e((string)($message['target_node']??'')).'</td><td data-label="Sequence">'.(int)($message['sequence']??0).'</td><td data-label="Status">'.self::badge((string)($message['status']??'unknown'),self::statusTone((string)($message['status']??'unknown'))).'</td><td data-label="Attempts">'.(int)($message['attempts']??0).'</td><td data-label="Expires"><time>'.self::e((string)($message['expires_at']??'')).'</time></td></tr>';}
		$flushFederation=$actionUrl!==''&&$controlTenant!==''?self::consoleCommandButton($actionUrl,$controlTenant,'operations_os.federation.flush','federation.transport.flush',['stale_after_seconds'=>(int)($options['federation_stale_after_seconds']??300),'limit'=>(int)($options['federation_flush_limit']??25)],'Flush federation outbox',$options):'';
		$releases=is_array($fleet['releases']??null)?$fleet['releases']:[];$ringRows=[];foreach((array)($releases['rings']??[])as$ring){if(!is_array($ring)){continue;}$paused=($ring['paused']??false)===true;$action=$actionUrl!==''&&$controlTenant!==''?self::consoleCommandButton($actionUrl,$controlTenant,'operations_os.release.pause','release.ring.pause',['ring'=>(string)($ring['name']??''),'paused'=>!$paused],$paused?'Resume':'Pause',$options):'';$ringRows[]='<tr><td data-label="Ring"><strong>'.self::e(self::humanize((string)($ring['name']??''))).'</strong></td><td data-label="Traffic">'.self::e(self::basisPoints((int)($ring['traffic_basis_points']??0))).'</td><td data-label="Health gates">'.(int)($ring['health_gate_count']??0).'</td><td data-label="State">'.self::badge($paused?'Paused':'Active',$paused?'info':'success').'</td><td data-label="Actions"><div class="dp-panel-actions">'.$action.'</div></td></tr>';}
		$artifactRows=[];foreach((array)($releases['artifacts']??[])as$artifact){if(!is_array($artifact)){continue;}$artifactRows[]='<tr><td data-label="Artifact"><strong>'.self::e((string)($artifact['id']??'')).'</strong><small>'.self::e((string)($artifact['digest']??'')).'</small></td><td data-label="Version">'.self::e((string)($artifact['version']??'')).'</td><td data-label="Bound digests">'.(int)($artifact['bound_digest_count']??0).'</td><td data-label="SBOM components">'.(int)($artifact['sbom_component_count']??0).'</td><td data-label="Created"><time>'.self::e((string)($artifact['created_at']??'')).'</time></td></tr>';}
		$execution=is_array($releases['execution']??null)?$releases['execution']:[];$executionRows=[];foreach((array)($execution['executions']??[])as$item){if(!is_array($item)){continue;}$completed=0;foreach((array)($item['steps']??[])as$step){if(is_array($step)&&($step['status']??null)==='completed'){$completed++;}}$executionRows[]='<tr><td data-label="Execution"><strong>'.self::e((string)($item['artifact_id']??'')).'</strong><small>'.self::e((string)($item['id']??'')).'</small></td><td data-label="Ring">'.self::e((string)($item['ring']??'')).'</td><td data-label="Status">'.self::badge((string)($item['status']??'unknown'),self::statusTone((string)($item['status']??'unknown'))).'</td><td data-label="Phase">'.self::e(self::humanize((string)($item['phase']??'complete'))).'</td><td data-label="Steps">'.$completed.' / 4</td><td data-label="Lease">'.(($item['leased']??false)?self::badge('Fenced','info'):self::badge('Released','neutral')).'</td><td data-label="Updated"><time>'.self::e((string)($item['updated_at']??'')).'</time></td></tr>';}
		$recoverReleases=$actionUrl!==''&&$controlTenant!==''?self::consoleCommandButton($actionUrl,$controlTenant,'operations_os.release.recover','release.execute.recover',['stale_after_seconds'=>(int)($options['release_stale_after_seconds']??0),'limit'=>(int)($options['release_recovery_limit']??25)],'Recover release workers',$options):'';
		$marketplace=is_array($fleet['marketplace']??null)?$fleet['marketplace']:[];$reviewRows=[];foreach((array)($marketplace['reviews']??[])as$review){if(!is_array($review)){continue;}$reviewRows[]='<tr><td data-label="Package"><strong>'.self::e((string)($review['package_id']??'')).'</strong><small>'.self::e((string)($review['package_version']??'')).'</small></td><td data-label="Status">'.self::badge((string)($review['status']??'unknown'),self::statusTone((string)($review['status']??'unknown'))).'</td><td data-label="Risk">'.(int)($review['risk_score']??0).'</td><td data-label="Findings">'.(int)($review['finding_count']??0).'</td><td data-label="Approvals">'.(int)($review['approval_count']??0).' / '.(int)($review['required_approvals']??0).'</td></tr>';}
		$body.='<section id="dp-ops-fleet" aria-labelledby="dp-ops-fleet-heading">'.self::sectionHeading('dp-ops-fleet-heading','Fleet, releases, and marketplace',(int)($federation['node_count']??0).' nodes, '.(int)($releases['deployment_count']??0).' deployments')
			.'<h3>Federation transport</h3><div class="dp-ops-section-actions"><p>Local node '.self::e((string)($gateway['local_node_id']??'unavailable')).'. Transport '.(($gateway['transport_configured']??false)?'configured':'offline queue only').'. Journal '.(($gateway['integrity']['ok']??false)?'verified':'needs attention').'. Payloads, nonces, signatures, and callbacks remain private.</p><div class="dp-panel-actions">'.$flushFederation.'</div></div>'
			.($outboxRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Message</th><th>Target</th><th>Sequence</th><th>Status</th><th>Attempts</th><th>Expires</th></tr></thead><tbody>'.implode('',$outboxRows).'</tbody></table></div>':self::empty('The federation outbox is empty.','Signed desired-state, heartbeat, and reconciliation messages will appear here as redacted metadata.'))
			.'<h3>Federation nodes</h3>'.($nodeRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Node</th><th>Environment</th><th>Region</th><th>Capabilities</th><th>Attestation expires</th></tr></thead><tbody>'.implode('',$nodeRows).'</tbody></table></div>':self::empty('No federation nodes are attested.','Signed installation heartbeats will appear here when federation is configured.'))
			.'<h3>Signed release artifacts</h3>'.($artifactRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Artifact</th><th>Version</th><th>Bound digests</th><th>SBOM components</th><th>Created</th></tr></thead><tbody>'.implode('',$artifactRows).'</tbody></table></div>':self::empty('No release artifacts are registered.','Signed artifacts bind code, SBOM, provenance, and source digests before scheduling.'))
			.'<h3>Release rings</h3>'.($ringRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Ring</th><th>Traffic</th><th>Health gates</th><th>State</th><th>Actions</th></tr></thead><tbody>'.implode('',$ringRows).'</tbody></table></div>':self::empty('No release rings are configured.','Configure signed artifacts, health gates, and ordered promotion rings to begin.'))
			.'<div class="dp-ops-section-actions"><p>Adapter receipts, worker credentials, and deployment payloads remain redacted. Active means prepare, activate, and verify all committed.</p><div class="dp-panel-actions">'.$recoverReleases.'</div></div><h3>Release execution</h3>'.($executionRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Execution</th><th>Ring</th><th>Status</th><th>Phase</th><th>Steps</th><th>Lease</th><th>Updated</th></tr></thead><tbody>'.implode('',$executionRows).'</tbody></table></div>':self::empty(($execution['configured']??false)?'No release executions for this tenant.':'No deployment adapter is configured.',($execution['configured']??false)?'Governed deployments will appear when an artifact is scheduled.':'Attach a release deployment adapter to execute prepare, activate, verify, and rollback phases.'))
			.'<h3>Marketplace review</h3>'.($reviewRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Package</th><th>Status</th><th>Risk</th><th>Findings</th><th>Approvals</th></tr></thead><tbody>'.implode('',$reviewRows).'</tbody></table></div>':self::empty('No marketplace candidates are under review.','Governed package reviews will appear before activation.')).'</section>';

		return self::page('Operations OS','A governed control room for work, commands, policy, domains, intelligence, compliance, releases, and fleet state.',$body,['operations_os'=>$snapshot,'surface'=>'operations_os_console'],$options);
	}

	/** @param iterable<PanelOperationRecord|array<string,mixed>> $operations */
	public static function operations(iterable $operations, array $options=[]): PanelPageResult {
		$rows=[]; $records=[];
		foreach($operations as $operation){
			$record=$operation instanceof PanelOperationRecord ? $operation->jsonSerialize() : (is_array($operation) ? $operation : []);
			if($record===[]){ continue; }
			$records[]=$record;
			$id=(string)($record['id'] ?? ''); $status=(string)($record['status'] ?? 'unknown'); $percent=max(0, min(100, (int)($record['progress']['percent'] ?? $record['percent'] ?? 0)));
			$rows[]='<tr data-dp-operation-id="'.self::e($id).'">'
				.'<td data-label="Operation"><strong>'.self::e((string)($record['name'] ?? $record['type'] ?? 'Operation')).'</strong><small>'.self::e($id).'</small></td>'
				.'<td data-label="Status">'.self::badge($status, self::statusTone($status)).'</td>'
				.'<td data-label="Progress"><progress value="'.$percent.'" max="100" aria-label="'.self::e($percent.' percent complete').'">'.$percent.'%</progress><small>'.self::e((string)($record['progress_message'] ?? '')).'</small></td>'
				.'<td data-label="Attempts">'.self::e((string)($record['attempt'] ?? 0)).' / '.self::e((string)($record['max_attempts'] ?? 1)).'</td>'
				.'<td data-label="Updated"><time>'.self::e((string)($record['updated_at'] ?? '')).'</time></td>'
				.'<td data-label="Actions"><div class="dp-panel-actions">'.self::operationActions($record, $options).'</div></td>'
				.'</tr>';
		}
		$body='<section aria-labelledby="dp-operations-heading">'.self::sectionHeading('dp-operations-heading', 'Operations', count($records).' total')
			.($rows===[] ? self::empty('No operations yet.', 'Queued imports, exports, bulk actions, and media work will appear here.') : '<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Operation</th><th>Status</th><th>Progress</th><th>Attempts</th><th>Updated</th><th>Actions</th></tr></thead><tbody>'.implode('', $rows).'</tbody></table></div>')
			.'</section>';
		return self::page('Operations center', 'Persistent background work, progress, failures, artifacts, and recovery.', $body, ['operations'=>$records, 'surface'=>'operations_center'], $options);
	}

	/** @param iterable<array<string,mixed>|JsonSerializable> $workflows */
	public static function workflows(iterable $workflows, array $options=[]): PanelPageResult {
		$items=[]; $data=[];
		foreach($workflows as $workflow){
			$manifest=$workflow instanceof \JsonSerializable ? (array)$workflow->jsonSerialize() : (is_array($workflow) ? $workflow : []);
			if($manifest===[]){ continue; } $data[]=$manifest;
			$name=(string)($manifest['name'] ?? $manifest['definition']['name'] ?? 'Workflow'); $state=(string)($manifest['state'] ?? $manifest['current_state'] ?? 'unknown');
			$transitions=is_array($manifest['available_transitions'] ?? $manifest['transitions'] ?? null) ? $manifest['available_transitions'] ?? $manifest['transitions'] : [];
			$buttons=[]; foreach($transitions as $key=>$transition){ $transition=is_array($transition) ? $transition : ['name'=>is_string($key)?$key:$transition]; $transitionName=(string)($transition['name'] ?? $key); $buttons[]=self::postButton((string)($options['transition_url'] ?? ''), (string)($manifest['id'] ?? ''), 'transition', $transitionName, self::humanize($transitionName)); }
			$items[]='<article class="dp-panel-card" data-dp-workflow-id="'.self::e((string)($manifest['id'] ?? '')).'"><header><div><strong>'.self::e($name).'</strong><small>'.self::e((string)($manifest['description'] ?? '')).'</small></div>'.self::badge($state, self::statusTone($state)).'</header><div class="dp-panel-actions">'.implode('', $buttons).'</div>'.self::timeline(is_array($manifest['history'] ?? null) ? $manifest['history'] : []).'</article>';
		}
		$body='<section aria-labelledby="dp-workflows-heading">'.self::sectionHeading('dp-workflows-heading', 'Workflows', count($data).' active').'<div class="dp-panel-collection" data-dp-display="grid">'.($items!==[] ? implode('', $items) : self::empty('No workflows are active.', 'Approval and state-machine instances will appear here.')).'</div></section>';
		return self::page('Workflow center', 'Drafts, approvals, assignments, deadlines, transitions, and immutable history.', $body, ['workflows'=>$data, 'surface'=>'workflow_center'], $options);
	}

	public static function automation(AutomationRegistry $registry,iterable $receipts=[],array $options=[]):PanelPageResult{
		$actions=[];$manifests=[];foreach($registry->actions()as$action){$manifest=$action->jsonSerialize();$manifests[]=$manifest;$name=(string)$manifest['name'];$actions[]='<article class="dp-panel-card" data-dp-automation-action="'.self::e($name).'"><header><div><strong>'.self::e((string)$manifest['label']).'</strong><small>'.self::e((string)$manifest['description']).'</small></div>'.self::badge((string)$manifest['risk'],in_array($manifest['risk'],['high','critical'],true)?'danger':'info').'</header><dl class="dp-panel-infolist"><div><dt>Confirmation</dt><dd>'.self::e((string)$manifest['confirmation']['level']).'</dd></div><div><dt>Idempotency</dt><dd>'.(($manifest['idempotency_required']??false)?'Required':'Optional').'</dd></div><div><dt>Rollback</dt><dd>'.(($manifest['capabilities']['rollback']??false)?'Available':'Unavailable').'</dd></div></dl><details><summary>Input contract</summary><pre class="dp-panel-code"><code>'.self::e((string)json_encode($manifest['input_schema'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</code></pre></details><div class="dp-panel-actions">'.self::postButton((string)($options['action_url']??''),$name,'dry_run','1','Dry run').'</div></article>';}
		$receiptRows=[];$receiptData=[];foreach($receipts as$receipt){$payload=$receipt instanceof \JsonSerializable?(array)$receipt->jsonSerialize():(is_array($receipt)?$receipt:[]);if($payload===[]){continue;}$receiptData[]=$payload;$receiptRows[]='<tr><td data-label="Receipt"><code>'.self::e((string)($payload['id']??'')).'</code></td><td data-label="Action">'.self::e((string)($payload['action']??'')).'</td><td data-label="Status">'.self::badge((string)($payload['status']??'unknown'),self::statusTone((string)($payload['status']??'unknown'))).'</td><td data-label="Actor">'.self::e((string)($payload['actor']['id']??$payload['actor_id']??'')).'</td><td data-label="Created"><time>'.self::e((string)($payload['created_at']??'')).'</time></td></tr>';}
		$body='<section aria-labelledby="dp-automation-actions">'.self::sectionHeading('dp-automation-actions','Action graph',count($actions).' commands').'<div class="dp-panel-collection" data-dp-display="grid">'.($actions?implode('',$actions):self::empty('No machine-readable actions.','Register automation actions to expose safe plans and receipts.')).'</div></section><section aria-labelledby="dp-automation-receipts">'.self::sectionHeading('dp-automation-receipts','Execution receipts',count($receiptRows).' receipts').($receiptRows?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Receipt</th><th>Action</th><th>Status</th><th>Actor</th><th>Created</th></tr></thead><tbody>'.implode('',$receiptRows).'</tbody></table></div>':self::empty('No execution receipts.','Dry runs do not mutate state. Executions and rollbacks will appear here.')).'</section>';
		return self::page('Agent-safe action graph','Dry-run plans, policy explanations, confirmations, idempotency, receipts, handoffs, and rollback.',$body,['actions'=>$manifests,'receipts'=>$receiptData,'surface'=>'automation'],$options);
	}

	public static function relations(PanelRelationWorkspace $workspace, array $options=[]): PanelPageResult {
		$manifest=$workspace->manifest(); $rows=[];
		foreach($manifest['records'] as $record){
			$id=(string)($record['id'] ?? ''); $cells=[];
			foreach($record as $key=>$value){ if(str_starts_with((string)$key, '_') || is_array($value) || is_object($value)){ continue; } $cells[]='<dt>'.self::e(self::humanize((string)$key)).'</dt><dd>'.self::e((string)$value).'</dd>'; }
			$rows[]='<article class="dp-panel-card" data-dp-related-id="'.self::e($id).'"><dl>'.implode('', $cells).'</dl><div class="dp-panel-actions">'.self::postButton((string)($options['operation_url'] ?? ''), $id, 'operation', 'detach', 'Detach').'</div></article>';
		}
		$available=[]; foreach($manifest['available'] as $record){ $id=(string)($record['id'] ?? ''); $available[]='<option value="'.self::e($id).'">'.self::e((string)($record['name'] ?? $record['title'] ?? $id)).'</option>'; }
		$attach=$available!==[] ? '<form method="post" action="'.self::e(self::url((string)($options['operation_url'] ?? ''))).'" class="dp-panel-commandbar" data-dp-panel-ajax><input type="hidden" name="operation" value="attach"><label><span>Related record</span><select name="related_id">'.implode('', $available).'</select></label><button type="submit" class="dp-panel-button">Attach</button></form>' : '';
		$body='<nav aria-label="Breadcrumb"><ol class="dp-panel-breadcrumbs">'.implode('', array_map(static fn(array $item): string => '<li><a href="'.self::e(self::url((string)($item['url'] ?? '#'))).'">'.self::e((string)($item['label'] ?? '')).'</a></li>', $manifest['breadcrumbs'])).'</ol></nav>'
			.$attach.'<section aria-labelledby="dp-relations-heading">'.self::sectionHeading('dp-relations-heading', self::humanize((string)$manifest['name']), count($manifest['records']).' related').'<div class="dp-panel-collection" data-dp-display="brick">'.($rows!==[] ? implode('', $rows) : self::empty('No related records.', 'Attach a record to begin.')).'</div></section>';
		return self::page('Relationship workspace', 'Nested records, pivot data, ordering, bulk operations, and undo.', $body, ['workspace'=>$manifest, 'surface'=>'relation_workspace'], $options);
	}

	public static function notifications(array|\JsonSerializable $inbox, array $options=[]): PanelPageResult {
		$manifest=$inbox instanceof \JsonSerializable ? (array)$inbox->jsonSerialize() : $inbox;
		$notifications=$manifest['notifications'] ?? $manifest['items'] ?? $manifest;
		$items=[]; foreach(is_array($notifications) ? $notifications : [] as $notification){ if(!is_array($notification)){ continue; } $id=(string)($notification['id'] ?? ''); $read=($notification['read'] ?? $notification['read_at'] ?? false)!==false && ($notification['read'] ?? $notification['read_at'] ?? null)!==null; $items[]='<article class="dp-panel-notification-item" data-dp-notification-id="'.self::e($id).'"'.(!$read?' data-unread="1"':'').'><header><strong>'.self::e((string)($notification['title'] ?? 'Notification')).'</strong>'.self::badge($read?'Read':'Unread', $read?'neutral':'info').'</header><p>'.self::e((string)($notification['body'] ?? $notification['message'] ?? '')).'</p><footer><time>'.self::e((string)($notification['created_at'] ?? '')).'</time><div class="dp-panel-actions">'.(!$read?self::postButton((string)($options['action_url'] ?? ''),$id,'operation','read','Mark read'):'').self::postButton((string)($options['action_url'] ?? ''),$id,'operation','dismiss','Dismiss').'</div></footer></article>'; }
		$body='<section aria-labelledby="dp-notifications-heading">'.self::sectionHeading('dp-notifications-heading', 'Notifications', count($items).' messages').'<div class="dp-panel-notification-list">'.($items!==[] ? implode('', $items) : self::empty('You are all caught up.', 'New activity and mentions will appear here.')).'</div></section>';
		return self::page('Notification center', 'Durable activity, mentions, assignments, subscriptions, and delivery preferences.', $body, ['inbox'=>$manifest, 'surface'=>'notification_center'], $options);
	}

	public static function media(array|\JsonSerializable $library, array $options=[]): PanelPageResult {
		$manifest=$library instanceof \JsonSerializable ? (array)$library->jsonSerialize() : $library; $media=$manifest['items'] ?? $manifest['media'] ?? [];
		$items=[]; foreach(is_array($media) ? $media : [] as $item){ if(!is_array($item)){ continue; } $id=(string)($item['id'] ?? ''); $preview=self::url((string)($item['preview_url'] ?? $item['url'] ?? '')); $items[]='<article class="dp-panel-media-item" data-dp-media-id="'.self::e($id).'">'.($preview!==''?'<img src="'.self::e($preview).'" alt="'.self::e((string)($item['alt'] ?? $item['name'] ?? '')).'" loading="lazy">':'').'<strong>'.self::e((string)($item['name'] ?? $id)).'</strong><small>'.self::e((string)($item['mime'] ?? '')).' · '.self::e((string)($item['bytes'] ?? 0)).' bytes</small>'.self::badge((string)($item['status'] ?? 'ready'), self::statusTone((string)($item['status'] ?? 'ready'))).'</article>'; }
		$upload='<form method="post" enctype="multipart/form-data" action="'.self::e(self::url((string)($options['upload_url'] ?? ''))).'" class="dp-panel-uploader" data-dp-panel-upload><label><span>Upload media</span><input type="file" name="media[]" multiple></label><button type="submit" class="dp-panel-button">Upload</button></form>';
		$body=$upload.'<section aria-labelledby="dp-media-heading">'.self::sectionHeading('dp-media-heading','Media library',count($items).' assets').'<div class="dp-panel-collection" data-dp-display="masonry">'.($items!==[]?implode('',$items):self::empty('No media assets.','Upload files to scan, transform, and publish variants.')).'</div></section>';
		return self::page('Media studio', 'Resumable uploads, scanning, variants, metadata, private delivery, and cleanup.', $body, ['library'=>$manifest, 'surface'=>'media_studio'], $options);
	}

	public static function preferences(PanelWorkspacePreferences $workspace, array $options=[]): PanelPageResult {
		$manifest=$workspace->manifest();
		$resolved=is_array($manifest['resolved'] ?? null) ? $manifest['resolved'] : [];
		$appearance=is_array($resolved['appearance'] ?? null) ? $resolved['appearance'] : [];
		$actionUrl=self::url((string)($options['action_url'] ?? ''));
		$appearanceForm='<form method="post" action="'.self::e($actionUrl).'" class="dp-panel-commandbar dp-panel-form-grid" data-dp-panel-ajax>'
			.'<input type="hidden" name="operation" value="appearance"><input type="hidden" name="expected_revision" value="'.self::e((string)($manifest['revision'] ?? 0)).'">'
			.'<label><span>Theme</span><select name="theme">'.self::options(['default'=>'Default','glass'=>'Glass','flat_minimal'=>'Flat minimal','brutalist'=>'Brutalist'],(string)($appearance['theme'] ?? 'default')).'</select></label>'
			.'<label><span>Density</span><select name="density">'.self::options(['compact'=>'Compact','normal'=>'Normal','roomy'=>'Roomy'],(string)($appearance['density'] ?? 'normal')).'</select></label>'
			.'<label><span>Locale</span><input name="locale" value="'.self::e((string)($appearance['locale'] ?? 'en')).'" autocomplete="language"></label>'
			.'<label><span>Direction</span><select name="direction">'.self::options(['auto'=>'Automatic','ltr'=>'Left to right','rtl'=>'Right to left'],(string)($appearance['direction'] ?? 'auto')).'</select></label>'
			.'<button type="submit" class="dp-panel-button">Save appearance</button></form>';
		$viewRows=[];
		foreach((array)($resolved['table_views'] ?? []) as $resource=>$views){
			foreach((array)$views as $name=>$view){
				if(!is_array($view)){ continue; }
				$delete='<form method="post" action="'.self::e($actionUrl).'" data-dp-panel-ajax><input type="hidden" name="operation" value="delete_table_view"><input type="hidden" name="resource" value="'.self::e((string)$resource).'"><input type="hidden" name="name" value="'.self::e((string)$name).'"><button type="submit" class="dp-panel-button">Delete</button></form>';
				$viewRows[]='<tr><td data-label="Resource">'.self::e(self::humanize((string)$resource)).'</td><td data-label="View"><strong>'.self::e(self::humanize((string)$name)).'</strong></td><td data-label="Presentation">'.self::e(self::humanize((string)($view['presentation'] ?? 'table'))).'</td><td data-label="Updated"><time>'.self::e((string)($view['updated_at'] ?? '')).'</time></td><td data-label="Actions">'.$delete.'</td></tr>';
			}
		}
		$list=static function(array $items,string $emptyTitle,string $emptyCopy):string {
			if($items===[]){ return self::empty($emptyTitle,$emptyCopy); }
			$rows=[];
			foreach($items as $item){
				if(!is_array($item)){ continue; }
				$rows[]='<li><strong>'.self::e(self::humanize((string)($item['type'] ?? 'item'))).'</strong><span>'.self::e((string)($item['id'] ?? '')).'</span><time>'.self::e((string)($item['visited_at'] ?? $item['pinned_at'] ?? '')).'</time></li>';
			}
			return '<ol class="dp-panel-activity-list">'.implode('',$rows).'</ol>';
		};
		$body='<section aria-labelledby="dp-preferences-appearance">'.self::sectionHeading('dp-preferences-appearance','Appearance and device defaults','Revision '.(int)($manifest['revision'] ?? 0)).$appearanceForm.'</section>'
			.'<section aria-labelledby="dp-preferences-views">'.self::sectionHeading('dp-preferences-views','Saved table views',count($viewRows).' views').($viewRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Resource</th><th>View</th><th>Presentation</th><th>Updated</th><th>Actions</th></tr></thead><tbody>'.implode('',$viewRows).'</tbody></table></div>':self::empty('No saved views.','Named filters, sorts, groups, columns, and presentations will appear here.')).'</section>'
			.'<section aria-labelledby="dp-preferences-pinned">'.self::sectionHeading('dp-preferences-pinned','Pinned workspace items',count((array)($resolved['pinned'] ?? [])).' pinned').$list((array)($resolved['pinned'] ?? []),'Nothing pinned.','Pin frequently used records and pages for fast access.').'</section>'
			.'<section aria-labelledby="dp-preferences-recent">'.self::sectionHeading('dp-preferences-recent','Recent workspace activity',count((array)($resolved['recent'] ?? [])).' recent').$list((array)($resolved['recent'] ?? []),'No recent activity.','Visited records and pages will appear here.').'</section>';
		return self::page('Workspace preferences','Appearance, saved views, recent activity, pins, notifications, and device overrides.',$body,['preferences'=>$manifest,'surface'=>'workspace_preferences'],$options);
	}

	public static function collaboration(PanelCollaborationManager $manager, array $options=[]): PanelPageResult {
		$actionUrl=self::url((string)($options['action_url'] ?? ''));
		$subjectType=isset($options['subject_type']) ? (string)$options['subject_type'] : null;
		$subjectId=$options['subject_id'] ?? null;
		$status=isset($options['status']) ? (string)$options['status'] : null;
		$threads=$manager->threads($subjectType,$subjectId,$status); $items=[];
		foreach($threads as $thread){
			$id=(string)($thread['id'] ?? ''); $commentItems=[];
			foreach($manager->comments($id) as $comment){
				$commentItems[]='<li><header><strong>'.self::e((string)($comment['actor'] ?? 'Unknown')).'</strong><time>'.self::e((string)($comment['created_at'] ?? '')).'</time></header><p>'.self::e((string)($comment['body'] ?? '')).'</p></li>';
			}
			$items[]='<article class="dp-panel-card dp-panel-thread" data-dp-thread-id="'.self::e($id).'"><header><div><strong>'.self::e((string)($thread['title'] ?? 'Discussion')).'</strong><small>'.self::e((string)($thread['subject_type'] ?? '')).' / '.self::e((string)($thread['subject_id'] ?? '')).'</small></div>'.self::badge((string)($thread['status'] ?? 'open'),self::statusTone((string)($thread['status'] ?? 'open'))).'</header><ol class="dp-panel-comment-list">'.implode('',$commentItems).'</ol><form method="post" action="'.self::e($actionUrl).'" data-dp-panel-ajax><input type="hidden" name="operation" value="comment"><input type="hidden" name="thread_id" value="'.self::e($id).'"><label><span>Add comment</span><textarea name="body" rows="3" required></textarea></label><button type="submit" class="dp-panel-button">Post comment</button></form></article>';
		}
		$create='<form method="post" action="'.self::e($actionUrl).'" class="dp-panel-commandbar dp-panel-form-grid" data-dp-panel-ajax><input type="hidden" name="operation" value="create_thread"><label><span>Subject type</span><input name="subject_type" value="'.self::e((string)($subjectType ?? '')).'" required></label><label><span>Subject id</span><input name="subject_id" value="'.self::e((string)($subjectId ?? '')).'" required></label><label><span>Thread title</span><input name="title" required></label><button type="submit" class="dp-panel-button">Start thread</button></form>';
		$subscriptions=$manager->subscriptions(isset($options['user_id'])?(string)$options['user_id']:null); $subscriptionRows=[];
		foreach($subscriptions as $subscription){ $subscriptionRows[]='<tr><td data-label="Topic">'.self::e((string)($subscription['topic'] ?? '')).'</td><td data-label="User">'.self::e((string)($subscription['user_id'] ?? '')).'</td><td data-label="Channels">'.self::e(implode(', ',(array)($subscription['channels'] ?? []))).'</td><td data-label="Mode">'.self::e((string)($subscription['mode'] ?? 'immediate')).'</td></tr>'; }
		$manifest=$manager->manifest(); $chain=is_array($manifest['receipt_chain'] ?? null)?$manifest['receipt_chain']:[];
		$body='<section aria-labelledby="dp-collaboration-overview">'.self::sectionHeading('dp-collaboration-overview','Collaboration activity',count($threads).' threads').'<dl class="dp-panel-infolist"><div><dt>Comments</dt><dd>'.self::e((string)($manifest['counts']['comments'] ?? 0)).'</dd></div><div><dt>Presence</dt><dd>'.self::e((string)($manifest['counts']['presence'] ?? 0)).'</dd></div><div><dt>Receipt chain</dt><dd>'.self::badge(($chain['valid'] ?? false)?'Verified':'Attention',($chain['valid'] ?? false)?'success':'danger').'</dd></div><div><dt>Cursor</dt><dd>'.self::e((string)($manifest['cursor'] ?? 0)).'</dd></div></dl>'.$create.'<div class="dp-panel-collection" data-dp-display="grid">'.($items!==[]?implode('',$items):self::empty('No discussion threads.','Start a contextual thread for a record, assignment, or review.')).'</div></section>'
			.'<section aria-labelledby="dp-collaboration-subscriptions">'.self::sectionHeading('dp-collaboration-subscriptions','Subscriptions',count($subscriptionRows).' subscriptions').($subscriptionRows!==[]?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Topic</th><th>User</th><th>Channels</th><th>Mode</th></tr></thead><tbody>'.implode('',$subscriptionRows).'</tbody></table></div>':self::empty('No subscriptions.','Watchers and notification subscriptions will appear here.')).'</section>';
		return self::page('Collaboration workspace','Threads, comments, mentions, assignments, watchers, presence, typing, and immutable receipts.',$body,['collaboration'=>$manifest,'threads'=>$threads,'subscriptions'=>$subscriptions,'surface'=>'collaboration_workspace'],$options);
	}

	public static function security(array $reports, array $options=[]): PanelPageResult {
		$sections=[]; foreach($reports as $name=>$report){ $payload=$report instanceof \JsonSerializable ? (array)$report->jsonSerialize() : (is_array($report)?$report:['value'=>$report]); $passed=($payload['passed'] ?? $payload['allowed'] ?? $payload['verified'] ?? true)!==false; $sections[]='<section aria-labelledby="dp-security-'.self::e((string)$name).'"><header><h2 id="dp-security-'.self::e((string)$name).'">'.self::e(self::humanize((string)$name)).'</h2>'.self::badge($passed?'Pass':'Attention',$passed?'success':'danger').'</header><pre class="dp-panel-code"><code>'.self::e((string)json_encode($payload, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)).'</code></pre></section>'; }
		return self::page('Security console', 'Permissions, MFA, sessions, impersonation, tenant isolation, and audit evidence.', implode('', $sections), ['reports'=>$reports, 'surface'=>'security_console'], $options);
	}

	public static function authentication(PanelAuthenticationManager $manager,string|int $userId,array $options=[],?PanelAuthenticationAccess $access=null):PanelPageResult{
		$auth=$manager->scoped($access??PanelAuthenticationAccess::self($userId));$userId=$auth->targetUserId();$factors=$auth->factors();$devices=array_map(static fn(PanelTrustedDevice $device):array=>$device->jsonSerialize(),$auth->devices());$sessions=array_map(static fn(PanelAuthenticationSession $session):array=>$session->jsonSerialize(),$auth->sessions());$actionUrl=(string)($options['action_url']??'');$target=['user_id'=>$userId];
		$factorItems=[];foreach($factors as$factor){$factorItems[]='<article class="dp-panel-card"><header><div><strong>'.self::e((string)$factor['label']).'</strong><small>'.self::e((string)$factor['issuer']).'</small></div>'.self::badge(($factor['enabled']??false)?'Enabled':'Pending',($factor['enabled']??false)?'success':'info').'</header><p>'.self::e((string)$factor['recovery_codes_remaining']).' recovery codes remain.</p><div class="dp-panel-actions">'.self::postButton($actionUrl,(string)$factor['id'],'operation','disable_totp','Disable',$target).'</div></article>';}
		$deviceItems=[];foreach($devices as$device){$deviceItems[]='<article class="dp-panel-card"><header><div><strong>'.self::e((string)$device['label']).'</strong><small>Last seen '.self::e((string)$device['last_seen_at']).'</small></div>'.self::badge(($device['active']??false)?'Trusted':'Revoked',($device['active']??false)?'success':'neutral').'</header><div class="dp-panel-actions">'.(($device['active']??false)?self::postButton($actionUrl,(string)$device['id'],'operation','revoke_device','Revoke device',$target):'').'</div></article>';}
		$sessionRows=[];foreach($sessions as$session){$sessionRows[]='<tr><td data-label="Session"><code>'.self::e((string)$session['id']).'</code></td><td data-label="Device">'.self::e((string)($session['device_id']??'Unbound')).'</td><td data-label="Authentication">Level '.self::e((string)$session['authentication_level']).'</td><td data-label="Status">'.self::badge(($session['active']??false)?'Active':'Revoked',($session['active']??false)?'success':'neutral').'</td><td data-label="Actions"><div class="dp-panel-actions">'.(($session['active']??false)?self::postButton($actionUrl,(string)$session['id'],'operation','revoke_session','Revoke',$target):'').'</div></td></tr>';}
		$body='<section aria-labelledby="dp-auth-factors">'.self::sectionHeading('dp-auth-factors','Multi-factor authentication',count($factors).' factors').'<div class="dp-panel-actions">'.self::postButton($actionUrl,(string)$userId,'operation','provision_totp','Add authenticator',$target).'</div><div class="dp-panel-collection" data-dp-display="grid">'.($factorItems?implode('',$factorItems):self::empty('No authenticator configured.','Add a TOTP authenticator to protect sensitive operations.')).'</div></section>'
			.'<section aria-labelledby="dp-auth-devices">'.self::sectionHeading('dp-auth-devices','Trusted devices',count($devices).' devices').'<div class="dp-panel-collection" data-dp-display="grid">'.($deviceItems?implode('',$deviceItems):self::empty('No trusted devices.','Trusted devices will appear after successful verification.')).'</div></section>'
			.'<section aria-labelledby="dp-auth-sessions">'.self::sectionHeading('dp-auth-sessions','Sessions',count($sessions).' sessions').($sessionRows?'<div class="dp-panel-table-shell"><table class="dp-panel-table"><thead><tr><th>Session</th><th>Device</th><th>Authentication</th><th>Status</th><th>Actions</th></tr></thead><tbody>'.implode('',$sessionRows).'</tbody></table></div>':self::empty('No sessions.','Active and revoked sessions will appear here.')).'</section>';
		return self::page('Authentication and sessions','MFA, recovery, trusted devices, step-up challenges, and revocation.',$body,['authentication'=>$manager->jsonSerialize(),'authentication_access'=>$auth->access()->jsonSerialize(),'factors'=>$factors,'devices'=>$devices,'sessions'=>$sessions,'surface'=>'authentication'],$options);
	}

	public static function authenticationEnrollment(PanelTotpEnrollment $enrollment,array $options=[]):PanelPageResult{
		$codes=array_map(static fn(string $code):string=>'<li><code>'.self::e($code).'</code></li>',$enrollment->recoveryCodes());$target=isset($options['user_id'])?'<input type="hidden" name="user_id" value="'.self::e((string)$options['user_id']).'">':'';$body='<section aria-labelledby="dp-enroll-heading">'.self::sectionHeading('dp-enroll-heading','Set up authenticator','One-time material').'<div class="dp-panel-card"><p>Scan or enter this provisioning value in your authenticator, then confirm a generated code.</p><label><span>Provisioning URI</span><textarea readonly rows="4">'.self::e($enrollment->provisioningUri()).'</textarea></label><label><span>Secret</span><input readonly value="'.self::e($enrollment->secret()).'"></label><h3>Recovery codes</h3><p>Store these codes now. They cannot be displayed again.</p><ul class="dp-panel-recovery-codes">'.implode('',$codes).'</ul><form method="post" action="'.self::e(self::url((string)($options['action_url']??''))).'" data-dp-panel-ajax>'.$target.'<input type="hidden" name="operation" value="confirm_totp"><input type="hidden" name="id" value="'.self::e($enrollment->factorId()).'"><label><span>Authentication code</span><input name="code" inputmode="numeric" autocomplete="one-time-code" required></label><button type="submit" class="dp-panel-button">Confirm authenticator</button></form></div></section>';
		return self::page('Authenticator enrollment','Provisioning material is shown exactly once.',$body,['enrollment'=>$enrollment->jsonSerialize(),'surface'=>'authentication_enrollment'],$options);
	}

	/** @param array<string,mixed> $discovery */
	public static function packages(PanelPackageRegistryCatalog $catalog,array $discovery,array $options=[]):PanelPageResult{
		$manifest=$catalog->toArray();
		$filters=is_array($discovery['filters']??null)?$discovery['filters']:[];
		$facets=is_array($discovery['facets']??null)?$discovery['facets']:[];
		$base=self::url((string)($options['base_url']??$options['url']??''));
		$query=(string)($discovery['query']??'');
		$limit=max(1,min(100,(int)($discovery['limit']??$options['limit']??24)));
		$fieldLabels=['status'=>'Status','type'=>'Type','publisher'=>'Publisher','tag'=>'Tag','category'=>'Category','capability'=>'Capability'];
		$facetNames=['status'=>'status','type'=>'type','publisher'=>'publisher','tag'=>'tags','category'=>'categories','capability'=>'provides'];
		$fields=[];
		foreach($fieldLabels as$field=>$label){
			$selected=is_array($filters[$field]??null)?$filters[$field]:[];
			$values=is_array($facets[$facetNames[$field]]??null)?$facets[$facetNames[$field]]:[];
			foreach($selected as$value){if(is_string($value)&&$value!==''){$values[$value]=$values[$value]??0;}}
			ksort($values,SORT_STRING);
			$optionsHtml='<option value="">All '.self::e(strtolower($label)).'</option>';
			foreach($values as$value=>$count){
				if(!is_string($value)||$value===''){continue;}
				$optionsHtml.='<option value="'.self::e($value).'"'.(in_array($value,$selected,true)?' selected':'').'>'.self::e(self::humanize($value)).' ('.(int)$count.')</option>';
			}
			$fields[]='<label><span>'.self::e($label).'</span><select name="'.self::e($field).'">'.$optionsHtml.'</select></label>';
		}
		$toggles=[];
		foreach(['include_yanked'=>'Yanked','include_revoked'=>'Revoked','include_blocked'=>'Blocked publishers','all_versions'=>'All versions']as$name=>$label){
			$toggles[]='<label><input type="checkbox" name="'.self::e($name).'" value="1"'.(($filters[$name]??false)===true?' checked':'').'><span>'.self::e($label).'</span></label>';
		}
		$search='<form method="get" action="'.self::e($base).'" class="dp-panel-commandbar dp-package-catalog-filter" role="search">'
			.'<label class="dp-package-catalog-query"><span>Find packages</span><input type="search" name="q" value="'.self::e($query).'" placeholder="Name, capability, tag, or publisher" autocomplete="off"></label>'
			.implode('',$fields)
			.'<div class="dp-package-catalog-toggles" aria-label="Package availability">'.implode('',$toggles).'</div>'
			.'<input type="hidden" name="limit" value="'.self::e((string)$limit).'"><div class="dp-panel-actions"><button type="submit" class="dp-panel-button">Search catalog</button>'.($query!==''||array_filter($filters)?'<a class="dp-panel-button" href="'.self::e($base!==''?$base:'?').'">Clear</a>':'').'</div></form>';

		$registryMeta='<dl class="dp-package-catalog-meta">'
			.'<div><dt>Registry</dt><dd><code>'.self::e((string)($manifest['registry']??'')).'</code></dd></div>'
			.'<div><dt>Publication</dt><dd>'.(($manifest['published']??false)?'Sequence '.(int)($manifest['sequence']??0):'Awaiting first publication').'</dd></div>'
			.'<div><dt>Packages</dt><dd>'.(int)($manifest['package_count']??0).' packages / '.(int)($manifest['package_version_count']??0).' versions</dd></div>'
			.'<div><dt>Index</dt><dd>'.(is_string($manifest['index_digest']??null)?'<code>'.self::e(substr((string)$manifest['index_digest'],0,12)).'…</code>':'Not published').'</dd></div>'
			.'</dl>';

		$cards=[];
		foreach((array)($discovery['packages']??[])as$package){
			if(!is_array($package)){continue;}
			$listing=is_array($package['listing']??null)?$package['listing']:[];
			$id=(string)($package['id']??'');$version=(string)($package['version']??'');
			$availability=($package['revoked']??false)?'Revoked':(($package['publisher_blocked']??false)?'Publisher blocked':(($package['yanked']??false)?'Yanked':'Available'));
			$tone=$availability==='Available'?'success':'danger';
			$badges=[self::badge($availability,$tone)];
			foreach(['type','license']as$field){$value=(string)($listing[$field]??'');if($value!==''){$badges[]=self::badge($value,'neutral');}}
			$provides=[];foreach((array)($listing['provides']??[])as$value){if(is_string($value)&&$value!==''){$provides[]='<li><code>'.self::e($value).'</code></li>';}}
			$tags=[];foreach(array_merge((array)($listing['categories']??[]),(array)($listing['tags']??[]))as$value){if(is_string($value)&&$value!==''){$tags[]='<span>'.self::e(self::humanize($value)).'</span>';}}
			$links=[];foreach((array)($listing['links']??[])as$link){if(!is_array($link)){continue;}$target=self::url((string)($link['target']??''));if($target!==''){$links[]='<a href="'.self::e($target).'" rel="noopener noreferrer">'.self::e((string)($link['label']??'Package link')).'</a>';}}
			$artifact=is_array($package['artifact']??null)?$package['artifact']:[];
			$cards[]='<article class="dp-panel-card dp-package-card" data-dp-package="'.self::e($id).'" data-dp-package-version="'.self::e($version).'">'
				.'<header><div><strong>'.self::e((string)($listing['label']??self::humanize($id))).'</strong><small><code>'.self::e($id.'@'.$version).'</code></small></div><div class="dp-package-card-badges">'.implode('',$badges).'</div></header>'
				.'<p>'.self::e((string)($listing['description']??'No marketplace description supplied.')).'</p>'
				.($tags!==[]?'<div class="dp-package-card-tags" aria-label="Categories and tags">'.implode('',$tags).'</div>':'')
				.'<dl class="dp-package-card-details"><div><dt>Publisher</dt><dd>'.self::e((string)($package['publisher']??'Unknown')).'</dd></div><div><dt>Release</dt><dd>'.self::e(self::humanize((string)($package['status']??'unknown'))).'</dd></div><div><dt>Artifact</dt><dd>'.self::e(self::formatBytes((int)($artifact['bytes']??0))).'</dd></div><div><dt>Signing key</dt><dd><code>'.self::e((string)($package['key_id']??'Unknown')).'</code></dd></div></dl>'
				.($provides!==[]?'<div class="dp-package-card-provides"><span>Provides</span><ul>'.implode('',$provides).'</ul></div>':'')
				.($links!==[]?'<nav class="dp-package-card-links" aria-label="'.self::e((string)($listing['label']??$id)).' links">'.implode('',$links).'</nav>':'')
				.'</article>';
		}
		$count=(int)($discovery['total']??0);
		$meta=$count===1?'1 package':$count.' packages';
		$results='<section aria-labelledby="dp-packages-results">'.self::sectionHeading('dp-packages-results','Verified packages',$meta)
			.($cards!==[]?'<div class="dp-panel-collection dp-package-catalog-results" data-dp-display="brick">'.implode('',$cards).'</div>':self::empty(($manifest['published']??false)?'No packages match this catalog view.':'No registry publication yet.',($manifest['published']??false)?'Change the search or availability filters to broaden discovery.':'Commit a signed registry publication and verified packages will appear here.'));
		$next=$discovery['next_cursor']??null;
		if(is_string($next)&&$next!==''){
			$nextQuery=['q'=>$query,'limit'=>$limit,'cursor'=>$next];
			foreach($fieldLabels as$field=>$label){if(is_array($filters[$field]??null)&&$filters[$field]!==[]){$nextQuery[$field]=$filters[$field];}}
			foreach(['include_yanked','include_revoked','include_blocked','all_versions']as$name){if(($filters[$name]??false)===true){$nextQuery[$name]='1';}}
			$results.='<nav class="dp-package-catalog-pagination" aria-label="Package catalog pagination"><a class="dp-panel-button" href="'.self::e(self::queryUrl($base,$nextQuery)).'">Next packages</a></nav>';
		}
		$results.='</section>';
		$body='<section aria-labelledby="dp-packages-registry">'.self::sectionHeading('dp-packages-registry','Registry state',($manifest['published']??false)?'Signed index verified':'Unpublished').$registryMeta.$search.'</section>'.$results;
		return self::page('Package registry','Discover signed, policy-aware Panel extensions without exposing artifact locators or package bytes.',$body,['catalog'=>$manifest,'discovery'=>$discovery,'surface'=>'package_registry_catalog'],$options);
	}

	public static function developer(PanelManifestInspector $inspection, ?PanelManifestDiff $diff=null, ?PanelQualityMatrix $matrix=null, array $options=[]): PanelPageResult {
		$report=$inspection->jsonSerialize(); $body='<section aria-labelledby="dp-inspection-heading">'.self::sectionHeading('dp-inspection-heading','Manifest inspection',$inspection->passed()?'Passed':'Issues found').'<dl class="dp-panel-infolist"><div><dt>Hash</dt><dd><code>'.self::e($inspection->hash()).'</code></dd></div><div><dt>Nodes</dt><dd>'.self::e((string)$report['metrics']['nodes']).'</dd></div><div><dt>Maximum depth</dt><dd>'.self::e((string)$report['metrics']['maximum_depth']).'</dd></div></dl>'.self::issueList($report['issues']).'</section>';
		if($diff!==null){ $payload=$diff->jsonSerialize(); $body.='<section aria-labelledby="dp-diff-heading">'.self::sectionHeading('dp-diff-heading','Contract diff',$payload['summary']['total'].' changes').self::issueList(array_map(static fn(array $change): array => ['severity'=>'info','rule'=>$change['type'],'path'=>$change['path'],'message'=>self::scalar($change['before']).' → '.self::scalar($change['after'])], $payload['changes'])).'</section>'; }
		if($matrix!==null){ $payload=$matrix->jsonSerialize(); $body.='<section aria-labelledby="dp-quality-heading">'.self::sectionHeading('dp-quality-heading','Quality matrix',$payload['cases'].' browser cases').'<p>Keyboard, focus, contrast, zoom, direction, motion, network, locale, theme, and viewport plans are ready for execution.</p></section>'; }
		return self::page('Panel developer tools', 'Inspect contracts, generate resources, compare manifests, and execute quality matrices.', $body, ['inspection'=>$report, 'diff'=>$diff?->jsonSerialize(), 'quality'=>$matrix?->jsonSerialize(), 'surface'=>'developer_tools'], $options);
	}

	private static function opsStat(string $label,string $value,string $tone,string $detail):string{return'<div data-tone="'.self::e($tone).'"><dt>'.self::e($label).'</dt><dd>'.self::e($value).'</dd><small>'.self::e($detail).'</small></div>';}
	/** @param array<string,mixed> $input */
	private static function consoleCommandButton(string $url,string $tenant,string $command,string $ability,array $input,string $label,array $options=[]):string{
		$encoded=json_encode(PanelOperationsGuard::safeMetadata($input,64),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$risk=str_contains($command,'.policy.')?'critical':'high';$key='console:'.substr(hash('sha256',$tenant.'|'.$command.'|'.$encoded.'|'.bin2hex(random_bytes(12))),0,40);
		return self::postButton($url,'','operation','dispatch',$label,self::consoleFormFields($options,['command'=>$command,'ability'=>$ability,'tenant_id'=>$tenant,'idempotency_key'=>$key,'risk'=>$risk,'input'=>$encoded]));
	}
	/** @param array<string,mixed> $options @param array<string,mixed> $fields @return array<string,mixed> */
	private static function consoleFormFields(array $options,array $fields=[]):array{
		$name=trim((string)($options['csrf_name']??''));$token=$options['csrf_token']??null;
		if($name!==''&&is_scalar($token)&&preg_match('/^[A-Za-z_][A-Za-z0-9_.:-]{0,63}$/D',$name)===1){$fields[$name]=(string)$token;}
		return$fields;
	}
	private static function basisPoints(int $value):string{return number_format(max(0,min(10000,$value))/100,2,'.','').'%';}
	private static function page(string $title,string $description,string $body,array $data,array $options): PanelPageResult { $asset=self::url(PanelRenderer::assetUrl('panel-platform.css')); $html=($asset!==''?'<link rel="stylesheet" href="'.self::e($asset).'" data-dp-panel-platform-asset>':'').'<main class="dp-panel dp-panel-platform-page" data-dp-panel-kind="'.self::e((string)($data['surface']??'platform')).'"><header class="dp-panel-page-header"><div><p class="dp-panel-eyebrow">'.self::e((string)($options['eyebrow']??'DATAPHYRE PANEL')).'</p><h1>'.self::e($title).'</h1><p>'.self::e($description).'</p></div></header><div class="dp-panel-page-content">'.$body.'</div></main>'; return PanelPageResult::html($html,200,$data); }
	private static function sectionHeading(string $id,string $title,string $meta): string { return '<header class="dp-panel-section-header"><div><h2 id="'.self::e($id).'">'.self::e($title).'</h2><small>'.self::e($meta).'</small></div></header>'; }
	private static function empty(string $title,string $description): string { return '<div class="dp-panel-empty-state"><strong>'.self::e($title).'</strong><p>'.self::e($description).'</p></div>'; }
	private static function badge(string $label,string $tone): string { return '<span class="dp-panel-badge" data-tone="'.self::e($tone).'">'.self::e(self::humanize($label)).'</span>'; }
	private static function statusTone(string $status): string { $status=strtolower($status); return match(true){ in_array($status,['completed','committed','approved','ready','active','success','succeeded','passed','delivered','processed','rolled_back'],true)=>'success', in_array($status,['failed','rejected','denied','cancelled','error','attention','rollback_failed','blocked'],true)=>'danger', in_array($status,['running','processing','queued','pending','sending','draft','paused','retry_wait','awaiting_approval','dispatching'],true)=>'info', default=>'neutral' }; }
	private static function operationActions(array $record,array $options): string { $status=(string)($record['status']??''); $id=(string)($record['id']??''); $url=(string)($options['action_url']??''); $actions=[]; if($status==='running'){ $actions[]=self::postButton($url,$id,'operation','pause','Pause'); $actions[]=self::postButton($url,$id,'operation','cancel','Cancel'); } if($status==='paused'){ $actions[]=self::postButton($url,$id,'operation','resume','Resume'); } if(in_array($status,['failed','cancelled'],true)){ $actions[]=self::postButton($url,$id,'operation','retry','Retry'); } foreach($record['artifacts']??[] as $artifact){ if(is_array($artifact)&&isset($artifact['location'])){ $location=self::url((string)$artifact['location']);if($location!==''){$actions[]='<a class="dp-panel-button" href="'.self::e($location).'">'.self::e((string)($artifact['name']??'Artifact')).'</a>';} } } return implode('',$actions); }
	private static function postButton(string $url,string $id,string $name,string $value,string $label,array $hidden=[]): string { $fields='';foreach($hidden as$key=>$field){$fields.='<input type="hidden" name="'.self::e((string)$key).'" value="'.self::e((string)$field).'">';}return '<form method="post" action="'.self::e(self::url($url)).'" data-dp-panel-ajax>'.$fields.'<input type="hidden" name="id" value="'.self::e($id).'"><input type="hidden" name="'.self::e($name).'" value="'.self::e($value).'"><button type="submit" class="dp-panel-button">'.self::e($label).'</button></form>'; }
	private static function timeline(array $events): string { if($events===[]){return '';} $items=[]; foreach(array_slice($events,-20) as $event){ if(!is_array($event)){continue;} $items[]='<li><strong>'.self::e(self::humanize((string)($event['transition']??$event['type']??'Event'))).'</strong><time>'.self::e((string)($event['timestamp']??$event['at']??'')).'</time></li>'; } return '<ol class="dp-panel-timeline">'.implode('',$items).'</ol>'; }
	private static function issueList(array $issues): string { if($issues===[]){return self::empty('No issues detected.','The inspected contract satisfies the current gates.');} $items=[]; foreach($issues as $issue){ $items[]='<li data-severity="'.self::e((string)($issue['severity']??'info')).'"><strong>'.self::e((string)($issue['rule']??'issue')).'</strong><code>'.self::e((string)($issue['path']??'')).'</code><span>'.self::e((string)($issue['message']??'')).'</span></li>'; } return '<ul class="dp-panel-issue-list">'.implode('',$items).'</ul>'; }
	private static function humanize(string $value): string { return ucwords(str_replace(['_','-'], ' ', trim($value))); }
	/** @param array<string,string> $values */
	private static function options(array $values,string $selected):string { $html=[];foreach($values as$value=>$label){$html[]='<option value="'.self::e($value).'"'.($value===$selected?' selected':'').'>'.self::e($label).'</option>';}return implode('',$html); }
	private static function url(string $value):string { $value=trim($value);if($value===''||preg_match('/[\x00-\x1F\x7F]/',$value)===1||str_starts_with($value,'//')){return '';}if(preg_match('/^[a-z][a-z0-9+.-]*:/i',$value)===1&&preg_match('/^https?:/i',$value)!==1){return '';}return$value; }
	/** @param array<string,mixed> $query */
	private static function queryUrl(string $base,array $query):string {
		$query=array_filter($query,static fn(mixed$value):bool=>$value!==null&&$value!==''&&$value!==[]&&$value!==false);
		$encoded=http_build_query($query,'','&',PHP_QUERY_RFC3986);
		if($encoded===''){return$base!==''?$base:'?';}
		return($base!==''?$base:'').(str_contains($base,'?')?'&':'?').$encoded;
	}
	private static function formatBytes(int $bytes):string {
		if($bytes<1){return'Unknown';}
		$units=['B','KB','MB','GB'];$value=(float)$bytes;$unit=0;
		while($value>=1024&&$unit<count($units)-1){$value/=1024;$unit++;}
		return($unit===0?(string)$bytes:number_format($value,$value>=10?1:2,'.','')).' '.$units[$unit];
	}
	private static function scalar(mixed $value): string { return is_scalar($value)||$value===null ? var_export($value,true) : (json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:''); }
	private static function e(string $value): string { return htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
}
