<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Optional visual layer for first-party platform pages. */
final class PanelPlatformAssets {
	public static function stylesheet(): string { return <<<'CSS'
@layer dp-panel{
.dp-panel-platform-page{container-type:inline-size;display:grid;gap:clamp(1rem,2vw,1.75rem);min-inline-size:0;color:var(--dp-text,#172033)}
.dp-panel-platform-page>.dp-panel-page-header{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;padding-block:clamp(.5rem,1vw,1rem) clamp(1rem,2vw,1.5rem);border-block-end:1px solid var(--dp-border,#d8dee9);background:transparent}
.dp-panel-platform-page>.dp-panel-page-header h1{margin:.15rem 0;font-size:clamp(1.65rem,4vw,2.75rem);line-height:1;letter-spacing:-.035em}
.dp-panel-platform-page>.dp-panel-page-header p{max-inline-size:72ch;margin:.35rem 0 0;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-eyebrow{font-size:.72rem;font-weight:750;letter-spacing:.12em;text-transform:uppercase;color:var(--dp-accent,#2563eb)}
.dp-panel-platform-page>.dp-panel-page-content{display:grid;gap:clamp(1.25rem,3vw,2.5rem);min-inline-size:0}
.dp-panel-platform-page section{display:grid;gap:1rem;min-inline-size:0}
.dp-panel-platform-page .dp-panel-section-header{display:flex;align-items:end;justify-content:space-between;gap:1rem;padding-block-end:.7rem;border-block-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-panel-section-header h2{margin:0;font-size:clamp(1.1rem,2vw,1.45rem)}
.dp-panel-platform-page .dp-panel-section-header small{color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-collection{--dp-platform-min:17rem;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,var(--dp-platform-min)),1fr));gap:clamp(.75rem,1.5vw,1.1rem);min-inline-size:0}
.dp-panel-platform-page .dp-panel-collection[data-dp-display="brick"]{--dp-platform-min:15rem}
.dp-panel-platform-page .dp-panel-collection[data-dp-display="masonry"]:not([data-dp-masonry="rows"]){display:block;columns:auto 17rem;column-gap:1rem}
.dp-panel-platform-page .dp-panel-collection[data-dp-display="masonry"]:not([data-dp-masonry="rows"])>*{break-inside:avoid;margin-block-end:1rem}
.dp-panel-platform-page .dp-panel-collection[data-dp-display="masonry"][data-dp-masonry="rows"]{display:flex;flex-flow:row wrap;align-items:stretch;gap:1rem}.dp-panel-platform-page .dp-panel-collection[data-dp-display="masonry"][data-dp-masonry="rows"]>*{flex:1 1 min(100%,17rem);min-inline-size:min(100%,17rem)}
.dp-panel-platform-page .dp-panel-card{display:grid;gap:.85rem;min-inline-size:0;padding:1rem;border:1px solid var(--dp-border,#d8dee9);border-radius:var(--dp-radius,.75rem);background:var(--dp-surface,#fff);box-shadow:none}
.dp-panel-platform-page .dp-panel-card>header,.dp-panel-platform-page .dp-panel-notification-item>header,.dp-panel-platform-page .dp-panel-notification-item>footer{display:flex;align-items:center;justify-content:space-between;gap:.75rem}
.dp-panel-platform-page .dp-panel-card small,.dp-panel-platform-page .dp-panel-notification-item time{display:block;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-table-shell{max-inline-size:100%;min-inline-size:0;overflow-x:auto;overscroll-behavior-inline:contain}
.dp-panel-platform-page .dp-panel-table{inline-size:100%;border-collapse:collapse}
.dp-panel-platform-page .dp-panel-table th,.dp-panel-platform-page .dp-panel-table td{padding:.75rem;text-align:start;vertical-align:middle;border-block-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-panel-table td>small{display:block;max-inline-size:32ch;overflow-wrap:anywhere;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page progress{display:block;inline-size:min(13rem,100%);block-size:.55rem;margin-block-end:.35rem;accent-color:var(--dp-accent,#2563eb)}
.dp-panel-platform-page .dp-panel-actions{display:flex;align-items:center;flex-wrap:wrap;gap:.45rem;min-inline-size:0}
.dp-panel-platform-page .dp-panel-actions form{display:contents}
.dp-panel-platform-page .dp-panel-button{min-block-size:2.75rem;display:inline-flex;align-items:center;justify-content:center;padding:.55rem .85rem;border:1px solid var(--dp-border-strong,#aeb8c7);border-radius:var(--dp-radius-sm,.55rem);background:var(--dp-surface-raised,#f5f7fa);color:var(--dp-text,#172033);font:inherit;font-weight:650;text-decoration:none;cursor:pointer}
.dp-panel-platform-page .dp-panel-button:hover{border-color:var(--dp-accent,#2563eb);color:var(--dp-accent,#2563eb)}
.dp-panel-platform-page .dp-panel-badge{display:inline-flex;align-items:center;justify-self:start;min-block-size:1.6rem;padding:.15rem .5rem;border:1px solid currentColor;border-radius:999px;font-size:.72rem;font-weight:750;line-height:1;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-badge[data-tone="success"]{color:var(--dp-success,#16803d)}.dp-panel-platform-page .dp-panel-badge[data-tone="danger"]{color:var(--dp-danger,#c72c41)}.dp-panel-platform-page .dp-panel-badge[data-tone="info"]{color:var(--dp-accent,#2563eb)}
.dp-panel-platform-page .dp-panel-empty-state{display:grid;place-items:center;gap:.35rem;min-block-size:9rem;padding:1.25rem;text-align:center;border:1px dashed var(--dp-border-strong,#aeb8c7);border-radius:var(--dp-radius,.75rem);background:transparent}
.dp-panel-platform-page .dp-panel-empty-state p{max-inline-size:52ch;margin:0;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-notification-list{display:grid}.dp-panel-platform-page .dp-panel-notification-item{display:grid;gap:.5rem;padding:1rem 0;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-panel-notification-item[data-unread="1"]{border-inline-start:.2rem solid var(--dp-accent,#2563eb);padding-inline-start:.8rem}.dp-panel-platform-page .dp-panel-notification-item p{margin:0;max-inline-size:75ch}
.dp-panel-platform-page .dp-panel-media-item{display:grid;gap:.55rem;min-inline-size:0;padding:.75rem;border:1px solid var(--dp-border,#d8dee9);border-radius:var(--dp-radius,.75rem);background:var(--dp-surface,#fff)}.dp-panel-platform-page .dp-panel-media-item img{inline-size:100%;max-block-size:18rem;object-fit:cover;border-radius:calc(var(--dp-radius,.75rem) - .2rem)}.dp-panel-platform-page .dp-panel-media-item small{overflow-wrap:anywhere;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-panel-uploader,.dp-panel-platform-page .dp-panel-commandbar{display:flex;align-items:end;flex-wrap:wrap;gap:.75rem;padding:1rem;border:1px solid var(--dp-border,#d8dee9);border-radius:var(--dp-radius,.75rem);background:var(--dp-surface,#fff)}.dp-panel-platform-page .dp-panel-uploader label,.dp-panel-platform-page .dp-panel-commandbar label{display:grid;flex:1 1 14rem;gap:.35rem;min-inline-size:0}.dp-panel-platform-page :where(input,select){min-block-size:2.75rem;max-inline-size:100%;color:var(--dp-text,#172033);background:var(--dp-control-bg,#fff);border:1px solid var(--dp-border-strong,#aeb8c7);border-radius:var(--dp-radius-sm,.55rem)}
.dp-panel-platform-page .dp-panel-commandbar.dp-package-catalog-filter{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,11rem),1fr));align-items:end;overflow:visible}.dp-panel-platform-page .dp-package-catalog-filter>.dp-package-catalog-query{grid-column:span 2}.dp-panel-platform-page .dp-package-catalog-filter :where(input,select){inline-size:100%;padding-inline:.7rem;font:inherit}.dp-panel-platform-page .dp-package-catalog-filter>.dp-panel-actions{align-self:end}.dp-panel-platform-page .dp-package-catalog-filter>.dp-panel-actions>.dp-panel-button{flex:1 1 8rem}
.dp-panel-platform-page .dp-package-catalog-toggles{grid-column:1/-1;display:flex;align-items:center;flex-wrap:wrap;gap:.5rem 1rem;min-inline-size:0;padding-block:.25rem}.dp-panel-platform-page .dp-package-catalog-toggles label{display:inline-flex;align-items:center;flex:0 1 auto;gap:.45rem;min-inline-size:0}.dp-panel-platform-page .dp-package-catalog-toggles input{inline-size:1rem;block-size:1rem;min-block-size:1rem;margin:0;accent-color:var(--dp-accent,#2563eb)}.dp-panel-platform-page .dp-package-catalog-toggles span{white-space:nowrap}
.dp-panel-platform-page .dp-package-catalog-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,12rem),1fr));margin:0;border-block:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-package-catalog-meta>div{min-inline-size:0;padding:.75rem 1rem;border-inline-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-package-catalog-meta>div:last-child{border-inline-end:0}.dp-panel-platform-page .dp-package-catalog-meta dt,.dp-panel-platform-page .dp-package-card-details dt,.dp-panel-platform-page .dp-package-card-provides>span{font-size:.7rem;font-weight:750;letter-spacing:.06em;text-transform:uppercase;color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-package-catalog-meta dd,.dp-panel-platform-page .dp-package-card-details dd{margin:.2rem 0 0;overflow-wrap:anywhere}
.dp-panel-platform-page .dp-package-catalog-results{--dp-platform-min:21rem;align-items:stretch}.dp-panel-platform-page .dp-package-card{align-content:start;grid-template-rows:auto auto auto auto 1fr auto;overflow:hidden}.dp-panel-platform-page .dp-package-card>header{align-items:flex-start;flex-wrap:wrap}.dp-panel-platform-page .dp-package-card>p{margin:0;overflow-wrap:anywhere;color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-package-card-badges,.dp-panel-platform-page .dp-package-card-tags,.dp-panel-platform-page .dp-package-card-links{display:flex;align-items:center;flex-wrap:wrap;gap:.4rem}.dp-panel-platform-page .dp-package-card-tags>span{padding:.2rem .45rem;border-radius:999px;background:var(--dp-surface-raised,#f5f7fa);color:var(--dp-text-muted,#697386);font-size:.72rem;font-weight:650}.dp-panel-platform-page .dp-package-card-details{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin:0;padding-block:.75rem;border-block:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-package-card-details>div{min-inline-size:0}.dp-panel-platform-page .dp-package-card-provides{display:grid;gap:.4rem}.dp-panel-platform-page .dp-package-card-provides ul{display:flex;flex-wrap:wrap;gap:.35rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-package-card-provides li{min-inline-size:0;padding:.25rem .45rem;border:1px solid var(--dp-border,#d8dee9);border-radius:var(--dp-radius-sm,.55rem);overflow-wrap:anywhere}.dp-panel-platform-page .dp-package-card-links{align-self:end;padding-block-start:.35rem}.dp-panel-platform-page .dp-package-card-links a{display:inline-flex;align-items:center;min-block-size:2.75rem;color:var(--dp-accent,#2563eb);font-weight:700;text-decoration:none}.dp-panel-platform-page .dp-package-card-links a:hover{text-decoration:underline}.dp-panel-platform-page .dp-package-catalog-pagination{display:flex;justify-content:flex-end}
.dp-panel-platform-page .dp-panel-card>label,.dp-panel-platform-page .dp-panel-card>form>label{display:grid;gap:.35rem;min-inline-size:0}.dp-panel-platform-page textarea{max-inline-size:100%;padding:.7rem;color:var(--dp-text,#172033);background:var(--dp-control-bg,#fff);border:1px solid var(--dp-border-strong,#aeb8c7);border-radius:var(--dp-radius-sm,.55rem);font:inherit}.dp-panel-platform-page .dp-panel-recovery-codes{display:grid;grid-template-columns:repeat(auto-fit,minmax(8rem,1fr));gap:.5rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-panel-recovery-codes li{padding:.5rem;border:1px dashed var(--dp-border-strong,#aeb8c7);border-radius:var(--dp-radius-sm,.55rem);text-align:center}
.dp-panel-platform-page .dp-panel-timeline{display:grid;gap:.5rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-panel-timeline li{display:flex;justify-content:space-between;gap:1rem;padding-block:.4rem;border-block-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-panel-infolist{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,13rem),1fr));gap:.75rem;margin:0}.dp-panel-platform-page .dp-panel-infolist>div{min-inline-size:0}.dp-panel-platform-page .dp-panel-infolist dt{font-size:.75rem;font-weight:700;text-transform:uppercase;color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-panel-infolist dd{margin:.2rem 0 0;overflow-wrap:anywhere}
.dp-panel-platform-page .dp-panel-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,12rem),1fr));align-items:end}.dp-panel-platform-page .dp-panel-form-grid>.dp-panel-button{inline-size:100%}
.dp-panel-platform-page .dp-panel-activity-list,.dp-panel-platform-page .dp-panel-comment-list{display:grid;gap:.65rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-panel-activity-list li{display:grid;grid-template-columns:minmax(7rem,.3fr) minmax(0,1fr) auto;gap:.75rem;padding-block:.6rem;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-panel-activity-list time,.dp-panel-platform-page .dp-panel-comment-list time{color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-panel-comment-list li{display:grid;gap:.3rem;padding-block:.55rem;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-panel-comment-list header{display:flex;justify-content:space-between;gap:.75rem}.dp-panel-platform-page .dp-panel-comment-list p{margin:0;overflow-wrap:anywhere}.dp-panel-platform-page .dp-panel-thread>form{display:grid;gap:.6rem}.dp-panel-platform-page .dp-panel-thread>form>label{display:grid;gap:.35rem}
.dp-panel-platform-page .dp-panel-code{max-inline-size:100%;margin:0;padding:1rem;white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid var(--dp-border,#d8dee9);border-radius:var(--dp-radius,.75rem);background:var(--dp-code-bg,#101827);color:var(--dp-code-text,#e7edf7)}
.dp-panel-platform-page .dp-panel-issue-list{display:grid;gap:.5rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-panel-issue-list li{display:grid;grid-template-columns:minmax(7rem,.25fr) minmax(8rem,.3fr) minmax(0,1fr);gap:.75rem;align-items:start;padding:.7rem;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-panel-issue-list code,.dp-panel-platform-page .dp-panel-issue-list span{overflow-wrap:anywhere}.dp-panel-platform-page .dp-panel-issue-list li[data-severity="error"]{border-inline-start:.2rem solid var(--dp-danger,#c72c41)}
.dp-panel-platform-page .dp-panel-breadcrumbs{display:flex;flex-wrap:wrap;gap:.5rem;margin:0;padding:0;list-style:none}.dp-panel-platform-page .dp-panel-breadcrumbs li+li:before{content:"/";margin-inline-end:.5rem;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page[data-dp-panel-kind="operations_os_console"]{--dp-ops-critical:var(--dp-danger,#c72c41);--dp-ops-warning:var(--dp-warning,#b56800);--dp-ops-clear:var(--dp-success,#16803d)}
.dp-panel-platform-page .dp-ops-anchor-nav{display:flex;flex-wrap:wrap;gap:.35rem;padding-block-end:.85rem;border-block-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-anchor-nav a{display:inline-flex;align-items:center;min-block-size:2.75rem;padding:.4rem .7rem;border:1px solid transparent;border-radius:var(--dp-radius-sm,.55rem);color:var(--dp-text-muted,#697386);font-size:.82rem;font-weight:700;text-decoration:none}
.dp-panel-platform-page .dp-ops-anchor-nav a:hover,.dp-panel-platform-page .dp-ops-anchor-nav a:focus-visible{border-color:var(--dp-border-strong,#aeb8c7);color:var(--dp-text,#172033);outline:0}
.dp-panel-platform-page .dp-ops-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,10rem),1fr));margin:0;border-block:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-strip>div{position:relative;display:grid;align-content:start;gap:.15rem;min-inline-size:0;padding:.85rem 1rem;border-inline-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-strip>div:last-child{border-inline-end:0}.dp-panel-platform-page .dp-ops-strip>div:before{content:"";position:absolute;inset-block-start:-1px;inset-inline:0;block-size:2px;background:currentColor;opacity:.8}
.dp-panel-platform-page .dp-ops-strip>div[data-tone="success"]{color:var(--dp-ops-clear)}.dp-panel-platform-page .dp-ops-strip>div[data-tone="danger"]{color:var(--dp-ops-critical)}.dp-panel-platform-page .dp-ops-strip>div[data-tone="info"]{color:var(--dp-accent,#2563eb)}.dp-panel-platform-page .dp-ops-strip>div[data-tone="neutral"]{color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-ops-strip dt{font-size:.69rem;font-weight:750;letter-spacing:.08em;text-transform:uppercase}.dp-panel-platform-page .dp-ops-strip dd{margin:0;overflow-wrap:anywhere;color:var(--dp-text,#172033);font-size:1rem;font-weight:750}.dp-panel-platform-page .dp-ops-strip small{overflow-wrap:anywhere;color:var(--dp-text-muted,#697386);font-size:.75rem}
.dp-panel-platform-page .dp-ops-attention-list,.dp-panel-platform-page .dp-ops-control-list{display:grid;margin:0;padding:0;list-style:none;border-block-start:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-attention-list li{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:.75rem;padding:.8rem 0;border-block-end:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-attention-list p{margin:.15rem 0 0;overflow-wrap:anywhere;color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-ops-attention-list a{display:inline-flex;align-items:center;min-block-size:2.75rem;color:var(--dp-accent,#2563eb);font-weight:700;text-decoration:none}
.dp-panel-platform-page .dp-ops-signal{inline-size:.6rem;block-size:.6rem;border:2px solid currentColor;border-radius:50%}.dp-panel-platform-page .dp-ops-attention-list li[data-severity="critical"] .dp-ops-signal{color:var(--dp-ops-critical);background:var(--dp-ops-critical)}.dp-panel-platform-page .dp-ops-attention-list li[data-severity="warning"] .dp-ops-signal{color:var(--dp-ops-warning);background:var(--dp-ops-warning)}.dp-panel-platform-page .dp-ops-attention-list li[data-severity="info"] .dp-ops-signal{color:var(--dp-accent,#2563eb)}
.dp-panel-platform-page .dp-ops-section-actions{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:.75rem}.dp-panel-platform-page .dp-ops-section-actions p,.dp-panel-platform-page .dp-ops-redaction-note{max-inline-size:74ch;margin:0;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page[data-dp-panel-kind="operations_os_console"] h3{margin:1rem 0 0;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase;color:var(--dp-text-muted,#697386)}
.dp-panel-platform-page .dp-ops-detail-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,11rem),1fr));margin:0;border-block:1px solid var(--dp-border,#d8dee9)}
.dp-panel-platform-page .dp-ops-detail-grid>div{min-inline-size:0;padding:.8rem 1rem;border-inline-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-ops-detail-grid>div:last-child{border-inline-end:0}.dp-panel-platform-page .dp-ops-detail-grid dt{color:var(--dp-text-muted,#697386);font-size:.72rem;font-weight:750;text-transform:uppercase}.dp-panel-platform-page .dp-ops-detail-grid dd{margin:.2rem 0 0;overflow-wrap:anywhere;font-weight:700}
.dp-panel-platform-page .dp-ops-control-list li{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.65rem 0;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-ops-control-list code{overflow-wrap:anywhere}
@container (max-width:52rem){.dp-panel-platform-page .dp-panel-table-shell{overflow:clip}.dp-panel-platform-page .dp-panel-table thead{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%)}.dp-panel-platform-page .dp-panel-table,.dp-panel-platform-page .dp-panel-table tbody,.dp-panel-platform-page .dp-panel-table tr,.dp-panel-platform-page .dp-panel-table td{display:block;inline-size:100%}.dp-panel-platform-page .dp-panel-table tr{padding:.75rem 0;border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-panel-table td{display:grid;grid-template-columns:minmax(6.5rem,.35fr) minmax(0,1fr);gap:.65rem;padding:.4rem 0;border:0;overflow-wrap:anywhere}.dp-panel-platform-page .dp-panel-table td:before{content:attr(data-label);font-size:.72rem;font-weight:750;text-transform:uppercase;color:var(--dp-text-muted,#697386)}.dp-panel-platform-page .dp-panel-issue-list li,.dp-panel-platform-page .dp-panel-activity-list li{grid-template-columns:1fr}.dp-panel-platform-page .dp-panel-notification-item>footer{align-items:flex-start;flex-direction:column}.dp-panel-platform-page>.dp-panel-page-header{align-items:flex-start;flex-direction:column}.dp-panel-platform-page .dp-ops-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.dp-panel-platform-page .dp-ops-strip>div{border-block-end:1px solid var(--dp-border,#d8dee9)}.dp-panel-platform-page .dp-ops-attention-list li{grid-template-columns:auto minmax(0,1fr)}.dp-panel-platform-page .dp-ops-attention-list li>a{grid-column:2}.dp-panel-platform-page .dp-ops-control-list li{align-items:stretch;flex-direction:column}.dp-panel-platform-page .dp-ops-control-list .dp-panel-button{inline-size:100%}}
@container (max-width:26rem){.dp-panel-platform-page .dp-ops-strip{grid-template-columns:1fr}.dp-panel-platform-page .dp-panel-table td{grid-template-columns:1fr;gap:.2rem}.dp-panel-platform-page .dp-ops-anchor-nav a{flex:1 1 calc(50% - .35rem);justify-content:center}.dp-panel-platform-page .dp-ops-section-actions{align-items:stretch;flex-direction:column}.dp-panel-platform-page .dp-ops-section-actions .dp-panel-button{inline-size:100%}.dp-panel-platform-page .dp-package-catalog-filter>.dp-package-catalog-query{grid-column:auto}.dp-panel-platform-page .dp-package-catalog-toggles{align-items:stretch;flex-direction:column}.dp-panel-platform-page .dp-package-card-details{grid-template-columns:1fr}.dp-panel-platform-page .dp-package-catalog-pagination>.dp-panel-button{inline-size:100%}}
[dir="rtl"] .dp-panel-platform-page .dp-panel-notification-item[data-unread="1"]{border-inline-start:.2rem solid var(--dp-accent,#2563eb);border-left:0}
@media (prefers-reduced-motion:reduce){.dp-panel-platform-page *{scroll-behavior:auto;transition-duration:.01ms;animation-duration:.01ms;animation-iteration-count:1}}
@media (forced-colors:active){.dp-panel-platform-page :where(.dp-panel-card,.dp-panel-media-item,.dp-panel-button,.dp-panel-badge,.dp-panel-empty-state,.dp-ops-strip,.dp-ops-detail-grid,.dp-ops-attention-list,.dp-ops-control-list){forced-color-adjust:auto;border-color:CanvasText}.dp-panel-platform-page .dp-ops-signal{forced-color-adjust:auto}}
}
CSS; }
}
