<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Crash-safe append-only package event log with signed Merkle checkpoints. */
final class PanelPackageTransparencyLog implements \JsonSerializable {
	public const KINDS=['registry_index','package_release','package_yank','publisher_key','revocation','publisher_attestation'];
	private readonly PanelAtomicSnapshotStore $store;private readonly \Closure $signer;private readonly \Closure $clock;private readonly string $logId;private readonly string $keyId;private readonly int $maxEntries;
	public function __construct(string $root,string $logId,string $keyId,callable $signer,?callable $clock=null,int $maxEntries=100000){$this->logId=PanelOperationsGuard::name($logId,'transparency log id');$this->keyId=PanelOperationsGuard::identifier($keyId,'transparency signing key id',256);$this->signer=\Closure::fromCallable($signer);$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');$this->maxEntries=max(1,min(1000000,$maxEntries));$initial=['schema'=>'panel_package_transparency_log','version'=>1,'events'=>[],'leaves'=>[],'event_index'=>[]];$this->store=new PanelAtomicSnapshotStore($root,'panel.package-transparency.v1',$initial,512);$this->assertState($this->store->payload());}
	/** @param array<string,mixed> $subject @param array<string,mixed> $options */ public function append(string $kind,array $subject,array $options=[]):PanelPackageTransparencyReceipt {$kind=PanelOperationsGuard::name($kind,'transparency event kind');if(!in_array($kind,self::KINDS,true)){throw new \InvalidArgumentException('Transparency event kind is unsupported.');}$subject=PanelPackageTransparencyReceipt::publicSubject($subject);$publishedAt=PanelOperationsGuard::instant($options['published_at']??$this->now(),'transparency publication time');$commitment=PanelOperationsGuard::digest(['kind'=>$kind,'subject'=>$subject,'published_at'=>$publishedAt]);$eventId=isset($options['event_id'])?PanelOperationsGuard::name((string)$options['event_id'],'transparency event id'):'event_'.substr($commitment,0,40);
		$result=$this->store->transaction(function(array &$state)use($kind,$subject,$publishedAt,$eventId,$commitment):array{$this->assertState($state);if(isset($state['event_index'][$eventId])){$index=(int)$state['event_index'][$eventId];$existing=$state['events'][$index]??null;if(!is_array($existing)||!hash_equals($commitment,PanelOperationsGuard::digest(['kind'=>$existing['kind'],'subject'=>$existing['subject'],'published_at'=>$existing['published_at']]))){throw new \LogicException('Transparency event id was reused for different content.');}return['index'=>$index,'replayed'=>true];}if(count($state['events'])>=$this->maxEntries){throw new \LengthException('Transparency log reached its configured entry limit.');}$sequence=count($state['events'])+1;$event=['type'=>'panel_package_transparency_event','version'=>1,'event_id'=>$eventId,'sequence'=>$sequence,'kind'=>$kind,'subject'=>$subject,'published_at'=>$publishedAt];$leaf=PanelPackageTransparencyMerkle::leaf($event);$index=count($state['events']);$state['events'][]=$event;$state['leaves'][]=$leaf;$state['event_index'][$eventId]=$index;return['index'=>$index,'replayed'=>false];},'transparency.event.appended',['event_id'=>$eventId,'kind'=>$kind])['result'];
		return$this->receipt($result['index'],max(0,(int)($options['consistency_from_size']??0)));
	}
	public function receipt(int $index,int $consistencyFromSize=0):PanelPackageTransparencyReceipt {$state=$this->store->payload();$this->assertState($state);$size=count($state['events']);if($index<0||$index>=$size){throw new \OutOfBoundsException('Transparency receipt event does not exist.');}$root=PanelPackageTransparencyMerkle::root($state['leaves']);$checkpoint=PanelPackageTransparencyCheckpoint::sign($this->logId,$size,$root,$this->now(),$this->keyId,$this->signer);$consistency=null;if($consistencyFromSize>0){if($consistencyFromSize>$size){throw new \OutOfBoundsException('Transparency consistency origin exceeds the current tree.');}$consistency=PanelPackageTransparencyConsistencyProof::build($state['leaves'],$consistencyFromSize,$size);}return new PanelPackageTransparencyReceipt($state['events'][$index],$index,PanelPackageTransparencyMerkle::inclusionProof($state['leaves'],$index),$checkpoint,$consistency);}
	public function checkpoint():PanelPackageTransparencyCheckpoint {$state=$this->store->payload();$this->assertState($state);if($state['leaves']===[]){throw new \LogicException('Transparency log has no signed tree head yet.');}return PanelPackageTransparencyCheckpoint::sign($this->logId,count($state['leaves']),PanelPackageTransparencyMerkle::root($state['leaves']),$this->now(),$this->keyId,$this->signer);}
	public function consistency(int $oldSize,int $newSize=0):PanelPackageTransparencyConsistencyProof {$state=$this->store->payload();$this->assertState($state);return PanelPackageTransparencyConsistencyProof::build($state['leaves'],$oldSize,$newSize===0?count($state['leaves']):$newSize);}
	public function size():int{return count($this->store->payload()['events']);}
	/** @return array<string,mixed> */ public function jsonSerialize():array {$state=$this->store->payload();$this->assertState($state);$kinds=[];foreach($state['events']as$event){$kinds[$event['kind']]=($kinds[$event['kind']]??0)+1;}ksort($kinds,SORT_STRING);return PanelManifestContract::stamp(['type'=>'panel_package_transparency_log_manifest','version'=>1,'log_id'=>$this->logId,'tree_size'=>count($state['leaves']),'root_hash'=>$state['leaves']===[]?PanelPackageTransparencyMerkle::root([]):PanelPackageTransparencyMerkle::root($state['leaves']),'event_kinds'=>$kinds,'signing_key_id'=>$this->keyId,'max_entries'=>$this->maxEntries,'events_serialized'=>false,'signer_serialized'=>false,'capabilities'=>['append_only'=>true,'atomic_persistence'=>true,'inclusion_proofs'=>true,'consistency_proofs'=>true,'signed_checkpoints'=>true,'witness_signatures'=>true]]);}
	/** @param array<string,mixed> $state */ private function assertState(array $state):void {if(($state['schema']??null)!=='panel_package_transparency_log'||($state['version']??null)!==1||!is_array($state['events']??null)||!array_is_list($state['events'])||!is_array($state['leaves']??null)||!array_is_list($state['leaves'])||count($state['events'])!==count($state['leaves'])||!is_array($state['event_index']??null)){throw new \UnexpectedValueException('Transparency log state is invalid.');}foreach($state['events']as$index=>$event){if(!is_array($event)||($event['sequence']??null)!==$index+1||!isset($state['leaves'][$index])||!hash_equals((string)$state['leaves'][$index],PanelPackageTransparencyMerkle::leaf($event))||($state['event_index'][$event['event_id']]??null)!==$index){throw new \UnexpectedValueException('Transparency log append-only state does not verify.');}}}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Transparency log clock must return an instant.');}return PanelOperationsGuard::instant($value);}
}
