<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/**
 * Captures the trust evaluation result for one or more panel packages.
 *
 * Trust reports are immutable value objects returned by package policy checks.
 * They preserve the per-package decisions, aggregate counters, policy metadata,
 * and caller-supplied diagnostics in a shape that can be rendered in Flightdeck,
 * serialized to JSON, or consumed by install planning without re-running the
 * trust policy.
 */
final class PanelPackageTrustReport implements \JsonSerializable {

	private array $packages;
	private array $summary;
	private array $policy;
	private array $meta;

	/**
	 * Creates a trust report from evaluated package decisions.
	 *
	 * The constructor does not validate or mutate package decisions; callers are
	 * expected to pass the exact output of the trust policy so the report remains
	 * a faithful audit artifact. Summary counters are read by typed accessors and
	 * default to zero when omitted.
	 *
	 * @param array<int, array<string, mixed>> $packages Per-package trust decisions and reasons.
	 * @param array<string, int|float|string|bool|null> $summary Aggregate counts such as trusted and blocked.
	 * @param array<string, mixed> $policy Policy options or rule metadata used for the evaluation.
	 * @param array<string, mixed> $meta Caller diagnostics to preserve with the report.
	 */
	public function __construct(array $packages, array $summary, array $policy=[], array $meta=[]) {
		$this->packages=$packages;
		$this->summary=$summary;
		$this->policy=$policy;
		$this->meta=$meta;
	}

	/**
	 * Returns the per-package trust decisions.
	 *
	 * @return array<int, array<string, mixed>> Package identifiers, trust flags, reasons, and policy evidence.
	 */
	public function packages(): array {
		return $this->packages;
	}

	/**
	 * Returns aggregate counters and trust status metadata.
	 *
	 * @return array<string, mixed> Summary generated by the trust policy.
	 */
	public function summary(): array {
		return $this->summary;
	}

	/**
	 * Returns the number of packages accepted by the trust policy.
	 *
	 * @return int Trusted package count, or zero when the summary omits it.
	 */
	public function trusted(): int {
		return (int)($this->summary['trusted'] ?? 0);
	}

	/**
	 * Returns the number of packages rejected by the trust policy.
	 *
	 * @return int Blocked package count, or zero when the summary omits it.
	 */
	public function blocked(): int {
		return (int)($this->summary['blocked'] ?? 0);
	}

	/**
	 * Reports whether the package set is safe to proceed past trust checks.
	 *
	 * @return bool True when no packages were blocked by the policy.
	 */
	public function ok(): bool {
		return $this->blocked()===0;
	}

	/**
	 * Returns trust decisions, findings, and package metadata for this report.
	 *
	 * The `type` discriminator lets UI and diagnostics code distinguish trust
	 * reports from install manifests and apply results after serialization.
	 *
	 * @return array{type: string, ok: bool, summary: array<string, mixed>, policy: array<string, mixed>, packages: array<int, array<string, mixed>>, meta: array<string, mixed>}
	 */
	public function toArray(): array {
		return [
			'type'=>'panel_package_trust_report',
			'ok'=>$this->ok(),
			'summary'=>$this->summary,
			'policy'=>$this->policy,
			'packages'=>$this->packages,
			'meta'=>$this->meta,
		];
	}

	/**
	 * Serializes the report without losing its payload discriminator.
	 *
	 * @return array{type: string, ok: bool, summary: array<string, mixed>, policy: array<string, mixed>, packages: array<int, array<string, mixed>>, meta: array<string, mixed>}
	 */
	public function jsonSerialize(): array {
		return $this->toArray();
	}
}
