<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Inclusion receipt binding an exact public event to a witnessed tree head. */
final class PanelPackageTransparencyReceipt implements \JsonSerializable {
	private readonly string $leafHash;
	/** @param array<string,mixed> $event @param list<string> $proof */
	public function __construct(private readonly array $event,private readonly int $leafIndex,private readonly array $proof,private readonly PanelPackageTransparencyCheckpoint $checkpoint,private readonly ?PanelPackageTransparencyConsistencyProof $consistency=null){
		self::validateEvent($event);if($leafIndex<0||$leafIndex>=$checkpoint->treeSize()||($event['sequence']??null)!==$leafIndex+1||count($proof)>64){throw new \InvalidArgumentException('Transparency receipt index, sequence, or proof is invalid.');}foreach($proof as$hash){if(!is_string($hash)||preg_match('/^[a-f0-9]{64}$/D',$hash)!==1){throw new \InvalidArgumentException('Transparency receipt proof hash is invalid.');}}if($consistency!==null&&($consistency->newSize()!==$checkpoint->treeSize()||!hash_equals($consistency->newRoot(),$checkpoint->rootHash()))){throw new \InvalidArgumentException('Transparency receipt consistency proof does not terminate at its checkpoint.');}$this->leafHash=PanelPackageTransparencyMerkle::leaf($event);
	}
	/** @param array<string,mixed> $manifest */ public static function fromArray(array $manifest):self {$event=$manifest['event']??null;$checkpoint=$manifest['checkpoint']??null;if(!is_array($event)||!is_array($checkpoint)){throw new \InvalidArgumentException('Transparency receipt manifest is invalid.');}$consistency=is_array($manifest['consistency']??null)?PanelPackageTransparencyConsistencyProof::fromArray($manifest['consistency']):null;$receipt=new self($event,(int)($manifest['leaf_index']??-1),is_array($manifest['proof']??null)?array_values($manifest['proof']):[],PanelPackageTransparencyCheckpoint::fromArray($checkpoint),$consistency);if(isset($manifest['leaf_hash'])&&(!is_string($manifest['leaf_hash'])||!hash_equals($receipt->leafHash,$manifest['leaf_hash']))){throw new \UnexpectedValueException('Transparency receipt leaf hash does not verify.');}return$receipt;}
	public function checkpoint():PanelPackageTransparencyCheckpoint{return$this->checkpoint;}public function consistency():?PanelPackageTransparencyConsistencyProof{return$this->consistency;}public function leafHash():string{return$this->leafHash;}public function leafIndex():int{return$this->leafIndex;}/** @return list<string> */public function proof():array{return$this->proof;}/** @return array<string,mixed> */public function event():array{return$this->event;}
	/** Adds an independent witness signature without changing the committed event or proof. */
	public function witness(string $witnessId,callable $signer):self{return new self($this->event,$this->leafIndex,$this->proof,$this->checkpoint->witness($witnessId,$signer),$this->consistency);}
	public function verify(string $kind,array $subject,callable $signatureVerifier,int $requiredWitnesses=0,array $allowedWitnesses=[]):bool {try{$kind=PanelOperationsGuard::name($kind,'transparency event kind');$subject=self::publicSubject($subject);if($this->event['kind']!==$kind||PanelOperationsGuard::json($this->event['subject'])!==PanelOperationsGuard::json($subject)){return false;}return$this->checkpoint->verify($signatureVerifier,$requiredWitnesses,$allowedWitnesses)&&PanelPackageTransparencyMerkle::verifyInclusion($this->leafHash,$this->leafIndex,$this->checkpoint->treeSize(),$this->proof,$this->checkpoint->rootHash())&&($this->consistency===null||$this->consistency->verify());}catch(\Throwable){return false;}}
	/** @return array<string,mixed> */ public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_package_transparency_receipt','version'=>1,'event'=>$this->event,'leaf_index'=>$this->leafIndex,'leaf_hash'=>$this->leafHash,'proof'=>$this->proof,'checkpoint'=>$this->checkpoint->jsonSerialize(),'consistency'=>$this->consistency?->jsonSerialize()]);}
	/** @param array<string,mixed> $subject @return array<string,mixed> */ public static function publicSubject(array $subject):array {$canonical=PanelOperationsGuard::canonical($subject);if($canonical!==[]&&array_is_list($canonical)){throw new \InvalidArgumentException('Transparency event subjects must be object-like maps.');}if(count($canonical)>256){throw new \LengthException('Transparency event subject exceeds its limit.');}$sanitized=PanelSensitiveDataSanitizer::sanitize($canonical,['max_depth'=>12,'max_items'=>256,'max_string_bytes'=>16384]);if($sanitized!==$canonical){throw new \InvalidArgumentException('Transparency event subjects must not contain secret-shaped data.');}return$canonical;}
	/** @param array<string,mixed> $event */ private static function validateEvent(array $event):void {if(array_diff(array_keys($event),['type','version','event_id','sequence','kind','subject','published_at'])!==[]||($event['type']??null)!=='panel_package_transparency_event'||($event['version']??null)!==1){throw new \InvalidArgumentException('Transparency event schema is invalid.');}PanelOperationsGuard::name((string)($event['event_id']??''),'transparency event id');if(!is_int($event['sequence']??null)||$event['sequence']<1){throw new \InvalidArgumentException('Transparency event sequence is invalid.');}PanelOperationsGuard::name((string)($event['kind']??''),'transparency event kind');if(!is_array($event['subject']??null)||self::publicSubject($event['subject'])!==$event['subject']){throw new \InvalidArgumentException('Transparency event subject is invalid.');}PanelOperationsGuard::instant($event['published_at']??'','transparency event publication time');}
}
