<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Signed tree head with optional independent witness signatures. */
final class PanelPackageTransparencyCheckpoint implements \JsonSerializable {
	private readonly string $logId;private readonly int $treeSize;private readonly string $rootHash;private readonly string $issuedAt;private readonly string $keyId;private readonly string $signature;/** @var array<string,string> */private readonly array $witnesses;private readonly string $digest;
	/** @param array<string,string> $witnesses */ private function __construct(string $logId,int $treeSize,string $rootHash,string $issuedAt,string $keyId,string $signature,array $witnesses=[]){$this->logId=PanelOperationsGuard::name($logId,'transparency log id');if($treeSize<1||$treeSize>1000000){throw new \InvalidArgumentException('Transparency checkpoint tree size is invalid.');}$this->treeSize=$treeSize;$this->rootHash=self::hash($rootHash);$this->issuedAt=PanelOperationsGuard::instant($issuedAt,'transparency checkpoint issued at');$this->keyId=PanelOperationsGuard::identifier($keyId,'transparency signing key id',256);$this->signature=self::signature($signature);$normalized=[];foreach($witnesses as$id=>$value){$id=PanelOperationsGuard::identifier((string)$id,'transparency witness id',256);$normalized[$id]=self::signature((string)$value);}ksort($normalized,SORT_STRING);$this->witnesses=$normalized;$this->digest=PanelOperationsGuard::digest($this->payload());}
	public static function sign(string $logId,int $treeSize,string $rootHash,string $issuedAt,string $keyId,callable $signer):self {$payload=self::unsignedPayload($logId,$treeSize,$rootHash,$issuedAt,$keyId);$signature=$signer(PanelOperationsGuard::json($payload),$payload['key_id'],'primary');if(!is_string($signature)){throw new \UnexpectedValueException('Transparency signer must return a signature string.');}return new self($payload['log_id'],$payload['tree_size'],$payload['root_hash'],$payload['issued_at'],$payload['key_id'],$signature);}
	public function witness(string $witnessId,callable $signer):self {$witnessId=PanelOperationsGuard::identifier($witnessId,'transparency witness id',256);$signature=$signer(PanelOperationsGuard::json($this->signedPayload()),$witnessId,'witness');if(!is_string($signature)){throw new \UnexpectedValueException('Transparency witness signer must return a signature string.');}$witnesses=$this->witnesses;$witnesses[$witnessId]=$signature;return new self($this->logId,$this->treeSize,$this->rootHash,$this->issuedAt,$this->keyId,$this->signature,$witnesses);}
	/** @param list<string> $allowedWitnesses */ public function verify(callable $verifier,int $requiredWitnesses=0,array $allowedWitnesses=[]):bool {try{if($verifier(PanelOperationsGuard::json($this->signedPayload()),$this->keyId,$this->signature,'primary')!==true){return false;}$allowed=[];foreach($allowedWitnesses as$id){$allowed[PanelOperationsGuard::identifier((string)$id,'transparency witness id',256)]=true;}$valid=0;foreach($this->witnesses as$id=>$signature){if($allowed!==[]&&!isset($allowed[$id])){continue;}try{if($verifier(PanelOperationsGuard::json($this->signedPayload()),$id,$signature,'witness')===true){$valid++;}}catch(\Throwable){}}return$valid>=max(0,min(32,$requiredWitnesses));}catch(\Throwable){return false;}}
	/** @param array<string,mixed> $manifest */ public static function fromArray(array $manifest):self {$checkpoint=new self((string)($manifest['log_id']??''),(int)($manifest['tree_size']??0),(string)($manifest['root_hash']??''),(string)($manifest['issued_at']??''),(string)($manifest['key_id']??''),(string)($manifest['signature']??''),is_array($manifest['witnesses']??null)?$manifest['witnesses']:[]);if(isset($manifest['digest'])&&(!is_string($manifest['digest'])||!hash_equals($checkpoint->digest,$manifest['digest']))){throw new \UnexpectedValueException('Transparency checkpoint digest does not verify.');}return$checkpoint;}
	public function logId():string{return$this->logId;}public function treeSize():int{return$this->treeSize;}public function rootHash():string{return$this->rootHash;}public function issuedAt():string{return$this->issuedAt;}public function digest():string{return$this->digest;}/** @return array<string,string> */public function witnesses():array{return$this->witnesses;}
	/** @return array<string,mixed> */ public function jsonSerialize():array{return PanelManifestContract::stamp($this->payload()+['digest'=>$this->digest]);}
	/** @return array<string,mixed> */ private function signedPayload():array{return self::unsignedPayload($this->logId,$this->treeSize,$this->rootHash,$this->issuedAt,$this->keyId);}
	/** @return array<string,mixed> */ private static function unsignedPayload(string $logId,int $treeSize,string $rootHash,string $issuedAt,string $keyId):array{$logId=PanelOperationsGuard::name($logId,'transparency log id');if($treeSize<1||$treeSize>1000000){throw new \InvalidArgumentException('Transparency checkpoint tree size is invalid.');}return['type'=>'panel_package_transparency_checkpoint','version'=>1,'log_id'=>$logId,'tree_size'=>$treeSize,'root_hash'=>self::hash($rootHash),'issued_at'=>PanelOperationsGuard::instant($issuedAt,'transparency checkpoint issued at'),'key_id'=>PanelOperationsGuard::identifier($keyId,'transparency signing key id',256)];}
	/** @return array<string,mixed> */ private function payload():array{return$this->signedPayload()+['signature'=>$this->signature,'witnesses'=>$this->witnesses];}
	private static function hash(string $hash):string {$hash=strtolower(trim($hash));if(preg_match('/^[a-f0-9]{64}$/D',$hash)!==1){throw new \InvalidArgumentException('Transparency checkpoint root is invalid.');}return$hash;}
	private static function signature(string $signature):string {$signature=trim($signature);if($signature===''||strlen($signature)>16384||preg_match('/^[A-Za-z0-9+\/_=-]+$/D',$signature)!==1){throw new \InvalidArgumentException('Transparency signature is invalid.');}return$signature;}
}
