<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Universal governed case, queue, relationship, timeline, replay, and undo engine. */
final class PanelWorkGraph implements \JsonSerializable {
	private readonly \Closure $clock;
	private readonly ?\Closure $authorizer;

	public function __construct(private readonly PanelWorkGraphStore $store,?callable $authorizer=null,?callable $clock=null,private readonly int $eventRetention=50000,private readonly int $receiptRetention=10000){$this->authorizer=$authorizer!==null?\Closure::fromCallable($authorizer):null;$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');if($eventRetention<100||$receiptRetention<100){throw new \InvalidArgumentException('Work graph retention must be at least 100.');}}
	public function store():PanelWorkGraphStore{return$this->store;}

	/** @param array<string,mixed> $definition */
	public function create(string $tenantId,array $definition,string|int $actorId,string $idempotencyKey):PanelWorkReceipt {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$actorId=PanelOperationsGuard::identifier($actorId,'work actor id');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(['operation'=>'create','definition'=>$definition,'actor'=>$actorId]);return$this->commit($tenantId,$key,$fingerprint,'work.create',$actorId,(string)($definition['id']??''),function(array &$state,string $now,string $correlation)use($definition,$tenantId):array{$item=PanelWorkItem::make($tenantId,$definition,$now);if(isset($state['items'][$item->id()])){throw new \LogicException('Work item already exists.');}return[$item,null,['created'=>true],true];});}

	/** @param array<string,mixed> $patch @param array<string,mixed> $options */
	public function mutate(string $tenantId,string $itemId,string $operation,array $patch,string|int $actorId,int $expectedVersion,string $idempotencyKey,array $options=[]):PanelWorkReceipt {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$itemId=PanelOperationsGuard::identifier($itemId,'work item id');$operation=PanelOperationsGuard::name($operation,'work operation');$actorId=PanelOperationsGuard::identifier($actorId,'work actor id');$key=$this->idempotency($idempotencyKey);$reversible=($options['reversible']??true)===true;$details=PanelOperationsGuard::safeMetadata(is_array($options['details']??null)?$options['details']:[]);$fingerprint=PanelOperationsGuard::digest(['operation'=>$operation,'item'=>$itemId,'patch'=>$patch,'actor'=>$actorId,'expected_version'=>$expectedVersion,'reversible'=>$reversible,'details'=>$details]);return$this->commit($tenantId,$key,$fingerprint,'work.'.$operation,$actorId,$itemId,function(array &$state,string $now,string $correlation)use($itemId,$operation,$patch,$expectedVersion,$reversible,$details):array{$current=$this->required($state,$itemId);if($current->version()!==$expectedVersion){throw new \LogicException('Work item optimistic concurrency conflict.');}$next=$current->evolve($patch,$now);return[$next,$current,$details+['changed_fields'=>array_values(array_keys($patch))],$reversible];});}

	public function transition(string $tenantId,string $itemId,string $state,string|int $actorId,int $expectedVersion,string $idempotencyKey,array $options=[]):PanelWorkReceipt{return$this->mutate($tenantId,$itemId,'transition',['state'=>$state],$actorId,$expectedVersion,$idempotencyKey,$options);}
	public function assign(string $tenantId,string $itemId,?string $assignee,string|int $actorId,int $expectedVersion,string $idempotencyKey):PanelWorkReceipt{return$this->mutate($tenantId,$itemId,'assign',['assignee'=>$assignee],$actorId,$expectedVersion,$idempotencyKey);}
	public function move(string $tenantId,string $itemId,?string $queue,string|int $actorId,int $expectedVersion,string $idempotencyKey):PanelWorkReceipt{return$this->mutate($tenantId,$itemId,'move',['queue'=>$queue],$actorId,$expectedVersion,$idempotencyKey);}

	public function comment(string $tenantId,string $itemId,string $message,string|int $actorId,string $idempotencyKey):PanelWorkReceipt {$message=PanelOperationsGuard::label($message,'work comment',4096);$item=$this->get($tenantId,$itemId);if(!$item){throw new \OutOfBoundsException('Work item does not exist.');}return$this->mutate($tenantId,$itemId,'comment',[],$actorId,$item->version(),$idempotencyKey,['reversible'=>false,'details'=>['message'=>$message]]);}

	public function link(string $tenantId,string $from,string $to,string $type,string|int $actorId,string $idempotencyKey):PanelWorkReceipt {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$from=PanelOperationsGuard::identifier($from,'source work item id');$to=PanelOperationsGuard::identifier($to,'target work item id');if(hash_equals($from,$to)){throw new \InvalidArgumentException('Work graph self-links are not allowed.');}$type=PanelOperationsGuard::name($type,'work link type');$actorId=PanelOperationsGuard::identifier($actorId,'work actor id');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(compact('from','to','type','actorId'));return$this->commit($tenantId,$key,$fingerprint,'work.link',$actorId,$from,function(array &$state,string $now,string $correlation)use($from,$to,$type):array{$current=$this->required($state,$from);$this->required($state,$to);$edgeKey=$this->edgeKey($from,$to,$type);if(isset($state['edges'][$edgeKey])){throw new \LogicException('Work graph link already exists.');}$state['edges'][$edgeKey]=['from'=>$from,'to'=>$to,'type'=>$type,'created_at'=>$now];$next=$current->evolve([],$now);return[$next,$current,['edge'=>$state['edges'][$edgeKey]],true];});}

	public function unlink(string $tenantId,string $from,string $to,string $type,string|int $actorId,string $idempotencyKey):PanelWorkReceipt {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$from=PanelOperationsGuard::identifier($from,'source work item id');$to=PanelOperationsGuard::identifier($to,'target work item id');$type=PanelOperationsGuard::name($type,'work link type');$actorId=PanelOperationsGuard::identifier($actorId,'work actor id');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(compact('from','to','type','actorId'));return$this->commit($tenantId,$key,$fingerprint,'work.unlink',$actorId,$from,function(array &$state,string $now,string $correlation)use($from,$to,$type):array{$current=$this->required($state,$from);$edgeKey=$this->edgeKey($from,$to,$type);$edge=$state['edges'][$edgeKey]??null;if(!is_array($edge)){throw new \OutOfBoundsException('Work graph link does not exist.');}unset($state['edges'][$edgeKey]);$next=$current->evolve([],$now);return[$next,$current,['edge'=>$edge],true];});}

	public function undo(string $tenantId,string $eventId,string|int $actorId,int $expectedVersion,string $idempotencyKey):PanelWorkReceipt {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$eventId=PanelOperationsGuard::identifier($eventId,'work event id');$actorId=PanelOperationsGuard::identifier($actorId,'work actor id');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(compact('eventId','actorId','expectedVersion'));return$this->commit($tenantId,$key,$fingerprint,'work.undo',$actorId,'unknown',function(array &$state,string $now,string $correlation)use($eventId,$expectedVersion):array{$payload=$state['events'][$eventId]??null;if(!is_array($payload)){throw new \OutOfBoundsException('Work event does not exist.');}$target=PanelWorkEvent::restore($payload);if(!$target->reversible()||$target->before()===null){throw new \LogicException('Work event is not reversible.');}$current=$this->required($state,$target->itemId());if($current->version()!==$expectedVersion){throw new \LogicException('Work item optimistic concurrency conflict.');}$edge=$target->details()['edge']??null;if(in_array($target->operation(),['link','unlink'],true)){if(!is_array($edge)||!is_string($edge['from']??null)||!is_string($edge['to']??null)||!is_string($edge['type']??null)){throw new \UnexpectedValueException('Reversible work link event is missing its edge evidence.');}$edgeKey=$this->edgeKey($edge['from'],$edge['to'],$edge['type']);if($target->operation()==='link'){unset($state['edges'][$edgeKey]);}else{$this->required($state,$edge['to']);$state['edges'][$edgeKey]=$edge;}}$before=PanelWorkItem::restore($target->before());$restored=$current->evolve(['title'=>$before->title(),'state'=>$before->state(),'priority'=>$before->priority(),'queue'=>$before->queue(),'assignee'=>$before->assignee(),'due_at'=>$before->dueAt(),'tags'=>$before->tags(),'data'=>$before->data()],$now);return[$restored,$current,['undo_event_id'=>$eventId,'restored_edge'=>$target->operation()==='unlink'],false,$target->id()];});}

	public function get(string $tenantId,string $itemId):?PanelWorkItem {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$itemId=PanelOperationsGuard::identifier($itemId,'work item id');$payload=$this->store->read($tenantId)['items'][$itemId]??null;return is_array($payload)?PanelWorkItem::restore($payload):null;}

	/** @param array<string,mixed> $criteria @return list<PanelWorkItem> */
	public function queue(string $tenantId,array $criteria=[],int $limit=100):array {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$criteria=PanelOperationsGuard::canonical($criteria);$now=isset($criteria['at'])?PanelOperationsGuard::instant(is_int($criteria['at'])?$criteria['at']:(string)$criteria['at']):$this->now();$items=[];foreach($this->store->read($tenantId)['items']as$payload){$item=PanelWorkItem::restore($payload);if(isset($criteria['queue'])&&$item->queue()!==(string)$criteria['queue']){continue;}if(isset($criteria['type'])&&$item->type()!==(string)$criteria['type']){continue;}if(isset($criteria['state'])&&$item->state()!==(string)$criteria['state']){continue;}if(isset($criteria['states'])&&is_array($criteria['states'])&&!in_array($item->state(),$criteria['states'],true)){continue;}if(array_key_exists('assignee',$criteria)&&$item->assignee()!==($criteria['assignee']===null?null:(string)$criteria['assignee'])){continue;}if(isset($criteria['subject_type'])&&$item->subjectType()!==(string)$criteria['subject_type']){continue;}if(isset($criteria['subject_id'])&&$item->subjectId()!==(string)$criteria['subject_id']){continue;}if(isset($criteria['tags'])&&is_array($criteria['tags'])&&array_diff($criteria['tags'],$item->tags())!==[]){continue;}if(($criteria['overdue']??false)===true&&!$item->overdue($now)){continue;}if(isset($criteria['search'])&&!str_contains(strtolower($item->title().' '.$item->id()),strtolower((string)$criteria['search']))){continue;}$items[]=$item;}usort($items,static function(PanelWorkItem $a,PanelWorkItem $b):int{$priority=$b->priority()<=>$a->priority();if($priority!==0){return$priority;}$due=($a->dueAt()??'9999-12-31T23:59:59.999999Z')<=>($b->dueAt()??'9999-12-31T23:59:59.999999Z');return$due!==0?$due:([$a->createdAt(),$a->id()]<=>[$b->createdAt(),$b->id()]);});return array_slice($items,0,max(1,min(1000,$limit)));}

	/** @return list<PanelWorkEvent> */
	public function timeline(string $tenantId,?string $itemId=null,int $afterSequence=0,int $limit=100):array {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');if($itemId!==null){$itemId=PanelOperationsGuard::identifier($itemId,'work item id');}$events=[];foreach($this->store->read($tenantId)['events']as$payload){$event=PanelWorkEvent::restore($payload);if($event->sequence()<=max(0,$afterSequence)||($itemId!==null&&$event->itemId()!==$itemId)){continue;}$events[]=$event;if(count($events)>=max(1,min(1000,$limit))){break;}}return$events;}

	/** @return list<array<string,mixed>> */
	public function links(string $tenantId,string $itemId,string $direction='both',?string $type=null):array {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$itemId=PanelOperationsGuard::identifier($itemId,'work item id');if(!in_array($direction,['in','out','both'],true)){throw new \InvalidArgumentException('Work link direction is invalid.');}if($type!==null){$type=PanelOperationsGuard::name($type,'work link type');}$result=[];foreach($this->store->read($tenantId)['edges']as$edge){if(!is_array($edge)||($type!==null&&($edge['type']??null)!==$type)){continue;}$matches=($direction!=='in'&&($edge['from']??null)===$itemId)||($direction!=='out'&&($edge['to']??null)===$itemId);if($matches){$result[]=$edge;}}usort($result,static fn(array $a,array $b):int=>[$a['type'],$a['from'],$a['to']]<=>[$b['type'],$b['from'],$b['to']]);return$result;}

	public function at(string $tenantId,string $itemId,int $sequence):?PanelWorkItem {$tenantId=PanelOperationsGuard::identifier($tenantId,'work tenant id');$itemId=PanelOperationsGuard::identifier($itemId,'work item id');$projection=null;foreach($this->store->read($tenantId)['events']as$payload){$event=PanelWorkEvent::restore($payload);if($event->sequence()>$sequence){break;}if($event->itemId()===$itemId){$projection=$event->after();}}return is_array($projection)?PanelWorkItem::restore($projection):null;}
	public function verifyAudit(string $tenantId):bool {try{PanelWorkState::assert($this->store->read(PanelOperationsGuard::identifier($tenantId,'work tenant id')),$tenantId);return true;}catch(\Throwable){return false;}}

	/** @return array<string,mixed> */
	public function sla(string $tenantId,string|int|\DateTimeInterface|null $at=null):array {$at=$at===null?$this->now():PanelOperationsGuard::instant($at);$items=$this->queue($tenantId,[],1000);$overdue=array_values(array_filter($items,static fn(PanelWorkItem $item):bool=>$item->overdue($at)));$unassigned=array_values(array_filter($items,static fn(PanelWorkItem $item):bool=>$item->assignee()===null));return['at'=>$at,'total'=>count($items),'overdue'=>count($overdue),'unassigned'=>count($unassigned),'overdue_ids'=>array_map(static fn(PanelWorkItem $item):string=>$item->id(),$overdue)];}

	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_work_graph_manifest','version'=>1,'store'=>get_debug_type($this->store),'default_deny'=>$this->authorizer===null,'capabilities'=>['cases'=>true,'queues'=>true,'assignment'=>true,'sla'=>true,'relationships'=>true,'comments'=>true,'idempotency'=>true,'optimistic_concurrency'=>true,'tamper_evident_timeline'=>true,'temporal_replay'=>true,'undo'=>true,'change_feed'=>true]]);}

	/** @param callable(array<string,mixed>&,string,string):array{0:PanelWorkItem,1:?PanelWorkItem,2:array<string,mixed>,3:bool,4?:string} $mutation */
	private function commit(string $tenantId,string $key,string $fingerprint,string $ability,string $actorId,string $itemId,callable $mutation):PanelWorkReceipt {
		$this->authorize($ability,['tenant_id'=>$tenantId,'actor_id'=>$actorId,'item_id'=>$itemId,'fingerprint'=>$fingerprint]);$digest=hash('sha256',$tenantId.'|'.$key);
		return$this->store->transaction($tenantId,function(array &$state)use($tenantId,$digest,$fingerprint,$ability,$actorId,$itemId,$mutation):PanelWorkReceipt{$existing=$state['receipts'][$digest]??null;if(is_array($existing)){if(!hash_equals((string)($existing['fingerprint']??''),$fingerprint)){throw new \LogicException('Work graph idempotency key was reused for another command.');}$eventPayload=$state['events'][(string)$existing['event_id']]??null;if(!is_array($eventPayload)){throw new \UnexpectedValueException('Work graph replay receipt references a missing event.');}$event=PanelWorkEvent::restore($eventPayload);$itemPayload=$state['items'][$event->itemId()]??null;return new PanelWorkReceipt($event,is_array($itemPayload)?PanelWorkItem::restore($itemPayload):null,true);}$now=$this->now();$correlation='corr_'.substr(hash('sha256',$tenantId.'|'.$digest),0,40);$causation='cause_'.substr(hash('sha256',$fingerprint),0,40);$result=$mutation($state,$now,$correlation);[$next,$before,$details,$reversible]=$result;$causationId=(string)($result[4]??$causation);$state['sequence']++;$previous=$state['events']!==[]?(string)$state['events'][array_key_last($state['events'])]['hash']:(string)$state['anchor_hash'];$event=PanelWorkEvent::make($state['sequence'],$tenantId,$next->id(),str_starts_with($ability,'work.')?substr($ability,5):$ability,$actorId,$now,$before?->jsonSerialize(),$next->jsonSerialize(),$details,$reversible,$correlation,$causationId,$previous);$state['items'][$next->id()]=$next->jsonSerialize();$state['events'][$event->id()]=$event->jsonSerialize();$state['receipts'][$digest]=['fingerprint'=>$fingerprint,'event_id'=>$event->id()];$state['receipt_order'][]=$digest;$this->prune($state);return new PanelWorkReceipt($event,$next);},$ability,['actor_hash'=>hash('sha256',$actorId),'item_hash'=>hash('sha256',$itemId)]);
	}

	/** @param array<string,mixed> $state */ private function required(array $state,string $id):PanelWorkItem {$payload=$state['items'][$id]??null;if(!is_array($payload)){throw new \OutOfBoundsException('Work item does not exist.');}return PanelWorkItem::restore($payload);}
	/** @param array<string,mixed> $context */ private function authorize(string $ability,array $context):void {if($this->authorizer===null){throw new \LogicException('Work graph authorization is not configured.');}try{$decision=($this->authorizer)($ability,$context,$this);$allowed=$decision===true||($decision instanceof PanelSecurityDecision&&$decision->allowed())||($decision instanceof PanelPolicyDecision&&$decision->allowed())||(is_array($decision)&&($decision['allowed']??false)===true);}catch(\Throwable $error){throw new \LogicException('Work graph authorization failed closed.',0,$error);}if(!$allowed){throw new \LogicException('Work graph operation is not authorized.');}}
	/** @param array<string,mixed> $state */ private function prune(array &$state):void {$eventExcess=count($state['events'])-$this->eventRetention;if($eventExcess>0){$ids=array_slice(array_keys($state['events']),0,$eventExcess);foreach($ids as$id){$state['anchor_hash']=(string)$state['events'][$id]['hash'];unset($state['events'][$id]);}}$receiptExcess=count($state['receipt_order'])-$this->receiptRetention;if($receiptExcess>0){$removed=array_splice($state['receipt_order'],0,$receiptExcess);foreach($removed as$digest){unset($state['receipts'][$digest]);}}}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Work graph clock must return an instant.');}return PanelOperationsGuard::instant($value);}
	private function idempotency(string $key):string {$key=trim($key);if($key===''||strlen($key)>256){throw new \InvalidArgumentException('Work graph idempotency key is invalid.');}return$key;}
	private function edgeKey(string $from,string $to,string $type):string{return hash('sha256',$from.'|'.$type.'|'.$to);}
}
