<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Continuous tamper-evident controls, evidence, retention, and legal-hold ledger. */
final class PanelComplianceLedger implements \JsonSerializable {
	private readonly PanelAtomicSnapshotStore $store;private readonly \Closure $clock;/** @var array<string,string> */private array $keys;private readonly string $currentKeyId;private readonly ?\Closure $authorizer;private readonly int $evidenceRetention;
	/** @param array<string,string> $keys */public function __construct(string $root,array $keys,string $currentKeyId,?callable $authorizer=null,?callable $clock=null,int $retention=10000){if($keys===[]){throw new \InvalidArgumentException('Compliance ledger requires a signing keyring.');}$normalized=[];foreach($keys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'compliance key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Compliance keys require at least 32 bytes.');}$normalized[$id]=$key;}$currentKeyId=PanelOperationsGuard::name($currentKeyId,'current compliance key id');if(!isset($normalized[$currentKeyId])){throw new \InvalidArgumentException('Current compliance key is not trusted.');}$this->keys=$normalized;$this->currentKeyId=$currentKeyId;$this->evidenceRetention=max(100,$retention);$this->authorizer=$authorizer!==null?\Closure::fromCallable($authorizer):null;$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');$initial=['schema'=>'panel_compliance_ledger','version'=>1,'sequence'=>0,'anchor_hash'=>str_repeat('0',64),'controls'=>[],'evidence'=>[],'holds'=>[]];$this->store=new PanelAtomicSnapshotStore($root,'panel.compliance-ledger.v1',$initial,max(8,$retention));$this->assertState($this->store->payload());}
	/** @param array<string,mixed> $definition */public function registerControl(string $id,array $definition,string|int $actorId):array {$id=PanelOperationsGuard::name($id,'compliance control id');$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$this->authorize('compliance.control.register',['id'=>$id,'actor_id'=>$actorId]);$control=$this->normalizeControl($id,$definition,$actorId);return$this->store->transaction(function(array &$state)use($id,$control):array{if(isset($state['controls'][$id])){throw new \LogicException('Compliance control is already registered.');}$state['controls'][$id]=$control;return$control;},'compliance.control.registered',['control_id'=>$id])['result'];}
	/** Registers an exact control idempotently and rejects definition drift. @param array<string,mixed> $definition */
	public function ensureControl(string $id,array $definition,string|int $actorId):array {
		$id=PanelOperationsGuard::name($id,'compliance control id');$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$this->authorize('compliance.control.register',['id'=>$id,'actor_id'=>$actorId,'idempotent'=>true]);$control=$this->normalizeControl($id,$definition,$actorId);
		return$this->store->transaction(function(array &$state)use($id,$control):array{$existing=$state['controls'][$id]??null;if(is_array($existing)){if($existing!==$control){throw new \LogicException('Compliance control definition drift requires an explicit migration.');}return$existing;}$state['controls'][$id]=$control;return$control;},'compliance.control.ensured',['control_id'=>$id])['result'];
	}
	/** @param array<string,mixed> $evidence */public function record(string $controlId,string $status,array $evidence,string|int $actorId,string $source='panel'):array {$controlId=PanelOperationsGuard::name($controlId,'compliance control id');$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$status=PanelOperationsGuard::name($status,'compliance status');$source=PanelOperationsGuard::name($source,'compliance source');$this->authorize('compliance.evidence.record',['control_id'=>$controlId,'actor_id'=>$actorId,'status'=>$status]);return$this->store->transaction(function(array &$state)use($controlId,$status,$evidence,$actorId,$source):array{$this->assertState($state);if(!isset($state['controls'][$controlId])){throw new \OutOfBoundsException('Compliance control is not registered.');}$state['sequence']++;$previous=$state['evidence']!==[]?(string)$state['evidence'][array_key_last($state['evidence'])]['hash']:(string)$state['anchor_hash'];$event=['id'=>'evidence_'.substr(hash('sha256',$controlId.'|'.$state['sequence'].'|'.$previous),0,40),'sequence'=>$state['sequence'],'control_id'=>$controlId,'status'=>$status,'source'=>$source,'actor_hash'=>hash('sha256',$actorId),'occurred_at'=>$this->now(),'evidence'=>PanelOperationsGuard::safeMetadata($evidence,512),'previous_hash'=>$previous,'key_id'=>$this->currentKeyId];$event['hash']=hash_hmac('sha256',PanelOperationsGuard::json($event),$this->keys[$this->currentKeyId]);$state['evidence'][$event['id']]=$event;$this->prune($state);return$event;},'compliance.evidence.recorded',['control_id'=>$controlId,'status'=>$status])['result'];}
	/** Records a typed collector observation while preserving its trust bindings. @param array<string,mixed> $binding */
	public function recordObservation(string $controlId,PanelComplianceObservation $observation,string|int $actorId,string $collectorId,array $binding=[]):array {
		$collectorId=PanelOperationsGuard::name($collectorId,'compliance collector id');
		return$this->record($controlId,$observation->status(),['observation'=>$observation->jsonSerialize(),'binding'=>PanelOperationsGuard::safeMetadata($binding,128)],$actorId,$collectorId);
	}
	/** Signs a complete collection run with the ledger trust root. @param array<string,mixed> $payload */
	public function signCollectionRun(array $payload,string|int $actorId):PanelComplianceCollectionRun {
		$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$this->authorize('compliance.run.sign',['actor_id'=>$actorId,'plan_hash'=>$payload['plan_fingerprint']??null]);
		return PanelComplianceCollectionRun::sign($payload,$this->currentKeyId,$this->keys[$this->currentKeyId]);
	}
	/** @return array<string,array<string,mixed>> */ public function controls():array {$state=$this->store->payload();$this->assertState($state);return$state['controls'];}
	/** @return array<string,mixed>|null */ public function control(string $id):?array {$id=PanelOperationsGuard::name($id,'compliance control id');return$this->controls()[$id]??null;}
	/** @param list<string> $controlIds @return array<string,array<string,mixed>> */ public function latestEvidence(array $controlIds=[]):array {$state=$this->store->payload();$this->assertState($state);$ids=$controlIds===[]?array_keys($state['controls']):PanelOperationsGuard::names($controlIds,'compliance control id');if(array_diff($ids,array_keys($state['controls']))!==[]){throw new \OutOfBoundsException('Latest compliance evidence requested an unknown control.');}$latest=[];foreach($state['evidence']as$event){if(in_array($event['control_id'],$ids,true)){$latest[$event['control_id']]=$event;}}ksort($latest,SORT_STRING);return$latest;}
	public function hold(string $holdId,string $reason,string|int $actorId,?string $controlId=null):array {$holdId=PanelOperationsGuard::name($holdId,'legal hold id');$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$reason=PanelOperationsGuard::label($reason,'legal hold reason',2048);if($controlId!==null){$controlId=PanelOperationsGuard::name($controlId,'compliance control id');}$this->authorize('compliance.hold.place',['hold_id'=>$holdId,'actor_id'=>$actorId]);return$this->store->transaction(function(array &$state)use($holdId,$reason,$actorId,$controlId):array{if(isset($state['holds'][$holdId])){throw new \LogicException('Legal hold is already active.');}if($controlId!==null&&!isset($state['controls'][$controlId])){throw new \OutOfBoundsException('Compliance control is not registered.');}$hold=['id'=>$holdId,'reason'=>$reason,'control_id'=>$controlId,'placed_by_hash'=>hash('sha256',$actorId),'placed_at'=>$this->now(),'released_at'=>null];$state['holds'][$holdId]=$hold;return$hold;},'compliance.hold.placed',['hold_id'=>$holdId])['result'];}
	public function releaseHold(string $holdId,string|int $actorId):array {$holdId=PanelOperationsGuard::name($holdId,'legal hold id');$actorId=PanelOperationsGuard::identifier($actorId,'compliance actor id');$this->authorize('compliance.hold.release',['hold_id'=>$holdId,'actor_id'=>$actorId]);return$this->store->transaction(function(array &$state)use($holdId,$actorId):array{$hold=$state['holds'][$holdId]??null;if(!is_array($hold)||$hold['released_at']!==null){throw new \OutOfBoundsException('Active legal hold does not exist.');}$hold['released_at']=$this->now();$hold['released_by_hash']=hash('sha256',$actorId);$state['holds'][$holdId]=$hold;return$hold;},'compliance.hold.released',['hold_id'=>$holdId])['result'];}
	/** @param list<string> $controlIds */public function pack(array $controlIds=[]):PanelComplianceEvidencePack {$state=$this->store->payload();$this->assertState($state);$controlIds=$controlIds===[]?array_keys($state['controls']):PanelOperationsGuard::names($controlIds,'compliance control id');if(array_diff($controlIds,array_keys($state['controls']))!==[]){throw new \OutOfBoundsException('Compliance evidence pack requested an unknown control.');}$controls=array_intersect_key($state['controls'],array_fill_keys($controlIds,true));$evidence=array_values(array_filter($state['evidence'],static fn(array $event):bool=>in_array($event['control_id'],$controlIds,true)));$holds=array_values(array_filter($state['holds'],static fn(array $hold):bool=>$hold['released_at']===null&&($hold['control_id']===null||in_array($hold['control_id'],$controlIds,true))));$payload=['generated_at'=>$this->now(),'sequence'=>$state['sequence'],'controls'=>$controls,'evidence'=>$evidence,'active_holds'=>$holds,'ledger_verified'=>true,'latest_hash'=>$evidence!==[]?$evidence[array_key_last($evidence)]['hash']:$state['anchor_hash']];return PanelComplianceEvidencePack::sign($payload,$this->currentKeyId,$this->keys[$this->currentKeyId]);}
	public function verify():bool {try{$this->assertState($this->store->payload());return true;}catch(\Throwable){return false;}}public function jsonSerialize():array{$state=$this->store->payload();return PanelManifestContract::stamp(['type'=>'panel_compliance_ledger_manifest','version'=>1,'sequence'=>$state['sequence'],'control_count'=>count($state['controls']),'evidence_count'=>count($state['evidence']),'evidence_retention'=>$this->evidenceRetention,'active_hold_count'=>count(array_filter($state['holds'],static fn(array $hold):bool=>$hold['released_at']===null)),'key_ids'=>array_keys($this->keys),'current_key_id'=>$this->currentKeyId,'default_deny'=>$this->authorizer===null,'capabilities'=>['continuous_evidence'=>true,'typed_observations'=>true,'automated_collection_runs'=>true,'tamper_evident_chain'=>true,'signed_evidence_packs'=>true,'signed_collection_runs'=>true,'legal_holds'=>true,'hold_aware_retention'=>true,'atomic_persistence'=>true,'key_rotation'=>true]]);}
	/** @param array<string,mixed> $state */private function prune(array &$state):void {$held=[];$global=false;foreach($state['holds']as$hold){if(!is_array($hold)||($hold['released_at']??null)!==null){continue;}if(($hold['control_id']??null)===null){$global=true;break;}$held[(string)$hold['control_id']]=true;}while(!$global&&count($state['evidence'])>$this->evidenceRetention){$id=array_key_first($state['evidence']);$event=$state['evidence'][$id];if(isset($held[(string)$event['control_id']])){break;}$state['anchor_hash']=(string)$event['hash'];unset($state['evidence'][$id]);}}
	/** @param array<string,mixed> $state */private function assertState(array $state):void {if(($state['schema']??null)!=='panel_compliance_ledger'||($state['version']??null)!==1||!is_int($state['sequence']??null)||!is_array($state['controls']??null)||!is_array($state['evidence']??null)||!is_array($state['holds']??null)||!is_string($state['anchor_hash']??null)){throw new \UnexpectedValueException('Compliance ledger state is invalid.');}$previous=$state['anchor_hash'];$last=0;foreach($state['evidence']as$event){if(!is_array($event)||!is_int($event['sequence']??null)||$event['sequence']<=$last||($event['previous_hash']??null)!==$previous||!is_string($event['key_id']??null)||!isset($this->keys[$event['key_id']])||!is_string($event['hash']??null)){throw new \UnexpectedValueException('Compliance evidence chain is invalid.');}$hash=$event['hash'];unset($event['hash']);if(!hash_equals($hash,hash_hmac('sha256',PanelOperationsGuard::json($event),$this->keys[$event['key_id']]))){throw new \UnexpectedValueException('Compliance evidence signature is invalid.');}$previous=$hash;$last=$event['sequence'];}}
	/** @param array<string,mixed> $context */private function authorize(string $ability,array $context):void {if($this->authorizer===null){throw new \LogicException('Compliance ledger authorization is not configured.');}try{$result=($this->authorizer)($ability,$context,$this);$allowed=$result===true||($result instanceof PanelPolicyDecision&&$result->allowed())||($result instanceof PanelSecurityDecision&&$result->allowed());}catch(\Throwable $error){throw new \LogicException('Compliance authorization failed closed.',0,$error);}if(!$allowed){throw new \LogicException('Compliance operation is not authorized.');}}
	/** @param array<string,mixed> $definition @return array<string,mixed> */private function normalizeControl(string $id,array $definition,string $actorId):array {return['id'=>$id,'title'=>PanelOperationsGuard::label((string)($definition['title']??$id),'control title',512),'framework'=>PanelOperationsGuard::name((string)($definition['framework']??'custom'),'control framework'),'owner'=>PanelOperationsGuard::identifier((string)($definition['owner']??$actorId),'control owner'),'frequency'=>PanelOperationsGuard::name((string)($definition['frequency']??'continuous'),'control frequency'),'automated'=>($definition['automated']??false)===true,'metadata'=>PanelOperationsGuard::safeMetadata(is_array($definition['metadata']??null)?$definition['metadata']:[],256)];}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Compliance clock must return an instant.');}return PanelOperationsGuard::instant($value);}
}
