<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Emits a strict fetch-compatible TypeScript client from one SDK contract. */
final class PanelSdkTypeScriptGenerator {
	/** @return array<string,string> */
	public function files(PanelSdkContract $contract,string $package):array {
		$package=PanelSdkGuard::packageId($package);if(!str_starts_with($package,'@')||substr_count($package,'/')!==1){throw new \InvalidArgumentException('Panel TypeScript SDK package must use a scoped npm package id.');}
		return[
			'package.json'=>PanelSdkGuard::canonicalJson(['name'=>$package,'version'=>$contract->version(),'type'=>'module','private'=>false,'sideEffects'=>false,'files'=>['src'],'exports'=>['.'=>'./src/index.ts'],'types'=>'./src/index.ts','scripts'=>['check'=>'tsc --noEmit']]),
			'tsconfig.json'=>PanelSdkGuard::canonicalJson(['compilerOptions'=>['target'=>'ES2022','module'=>'ES2022','moduleResolution'=>'Bundler','lib'=>['ES2022','DOM','DOM.Iterable'],'strict'=>true,'noUncheckedIndexedAccess'=>true,'exactOptionalPropertyTypes'=>true,'useUnknownInCatchVariables'=>true,'verbatimModuleSyntax'=>true,'skipLibCheck'=>true,'noEmit'=>true],'include'=>['src/**/*.ts']]),
			'src/index.ts'=>$this->source($contract),
			'README.md'=>$this->readme($contract,$package),
		];
	}

	private function source(PanelSdkContract $contract):string {
		$contractJson=rtrim(PanelSdkGuard::canonicalJson($contract->jsonSerialize()));$types=[];$methods=[];
		foreach($contract->operations()as$operation){$name=self::typeName($operation->name());$method=self::methodName($operation->name());$pathType=$this->schemaType($operation->pathSchema()->definition());$queryType=$this->schemaType($operation->querySchema()->definition());$bodyType=$operation->bodySchema()!==null?$this->schemaType($operation->bodySchema()->definition()):'never';$responseType=$this->schemaType($operation->responseSchema()->definition());
			$types[]="export type {$name}Path = {$pathType};\nexport type {$name}Query = {$queryType};\nexport type {$name}Body = {$bodyType};\nexport type {$name}Response = {$responseType};";
			$fields=[];$required=false;if($operation->pathParameters()!==[]){$fields[]="  readonly path: {$name}Path;";$required=true;}else{$fields[]="  readonly path?: {$name}Path;";}$queryRequired=(array)($operation->querySchema()->definition()['required']??[])!==[];$fields[]='  readonly query'.($queryRequired?'':'?').": {$name}Query;";$required=$required||$queryRequired;if($operation->bodySchema()!==null){$fields[]="  readonly body: {$name}Body;";$required=true;}$fields[]='  readonly headers?: Readonly<Record<string, string>>;';$fields[]='  readonly signal?: AbortSignal;';$types[]="export interface {$name}Args {\n".implode("\n",$fields)."\n}";
			$argument=$required?"args: {$name}Args":"args: {$name}Args = {}";$methods[]="  public async {$method}({$argument}): Promise<{$name}Response> {\n    return this.request<{$name}Response>(".self::tsString($operation->name()).", args);\n  }";
		}
		foreach($contract->events()as$name=>$schema){$types[]='export type Event'.self::typeName($name).' = '.$this->schemaType($schema->definition()).';';}
		foreach($contract->artifacts()as$name=>$schema){$types[]='export type Artifact'.self::typeName($name).' = '.$this->schemaType($schema->definition()).';';}
		$typeBlock=implode("\n\n",$types);$methodBlock=implode("\n\n",$methods);$fingerprint=self::tsString($contract->fingerprint());$version=self::tsString($contract->version());
		$template=<<<'TS'
/* Generated by Dataphyre Panel. Do not edit by hand. */

export type JsonValue = null | boolean | number | string | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };
export type JsonObject = { readonly [key: string]: JsonValue };

export const PANEL_SDK_VERSION = __VERSION__;
export const PANEL_SDK_CONTRACT_FINGERPRINT = __FINGERPRINT__;
export const PANEL_SDK_CONTRACT = __CONTRACT__ as const;

__TYPES__

type RuntimeSchema = Readonly<Record<string, unknown>>;
type RuntimeOperation = {
  readonly method: string;
  readonly path: string;
  readonly request: { readonly path: RuntimeSchema; readonly query: RuntimeSchema; readonly body: RuntimeSchema | null };
  readonly response: RuntimeSchema;
  readonly errors: Readonly<Record<string, RuntimeSchema>>;
};

export interface PanelSdkTransportRequest {
  readonly method: string;
  readonly url: string;
  readonly headers: Readonly<Record<string, string>>;
  readonly body?: JsonValue;
  readonly signal?: AbortSignal;
}

export interface PanelSdkTransportResponse {
  readonly status: number;
  readonly headers?: Readonly<Record<string, string>>;
  readonly body: unknown;
}

export type PanelSdkTransport = (request: PanelSdkTransportRequest) => Promise<PanelSdkTransportResponse>;
export type PanelSdkHeaderProvider = () => Readonly<Record<string, string>> | Promise<Readonly<Record<string, string>>>;

export interface PanelClientOptions {
  readonly baseUrl?: string;
  readonly headers?: Readonly<Record<string, string>> | PanelSdkHeaderProvider;
  readonly transport?: PanelSdkTransport;
  readonly validateResponses?: boolean;
}

type PanelSdkRequestArgs = {
  readonly path?: Readonly<Record<string, unknown>>;
  readonly query?: Readonly<Record<string, unknown>>;
  readonly body?: unknown;
  readonly headers?: Readonly<Record<string, string>>;
  readonly signal?: AbortSignal;
};

export class PanelSdkError extends Error {
  public constructor(
    message: string,
    public readonly code: string,
    public readonly status: number,
    public readonly correlationId: string | null,
    public readonly body: unknown,
    public readonly validationErrors: ReadonlyArray<string> = [],
  ) {
    super(message);
    this.name = "PanelSdkError";
  }
}

const operations = PANEL_SDK_CONTRACT.operations as unknown as Readonly<Record<string, RuntimeOperation>>;

export class PanelClient {
  private readonly baseUrl: string;
  private readonly headers: Readonly<Record<string, string>> | PanelSdkHeaderProvider;
  private readonly transport: PanelSdkTransport;
  private readonly validateResponses: boolean;

  public constructor(options: PanelClientOptions = {}) {
    this.baseUrl = normalizeBaseUrl(options.baseUrl ?? "");
    this.headers = options.headers ?? {};
    this.transport = options.transport ?? fetchTransport;
    this.validateResponses = options.validateResponses ?? true;
  }

__METHODS__

  private async request<T>(name: string, args: PanelSdkRequestArgs): Promise<T> {
    const operation = operations[name];
    if (!operation) throw new PanelSdkError("SDK operation is unavailable.", "operation_unavailable", 0, null, null);
    const path = args.path ?? {};
    const query = args.query ?? {};
    const pathErrors = validateValue(path, operation.request.path, "$.path", "request");
    const queryErrors = validateValue(query, operation.request.query, "$.query", "request");
    const bodyErrors = operation.request.body === null
      ? (args.body === undefined ? [] : ["$.body: body is not accepted"])
      : validateValue(args.body, operation.request.body, "$.body", "request");
    const requestErrors = [...pathErrors, ...queryErrors, ...bodyErrors];
    if (requestErrors.length) throw new PanelSdkError("SDK request does not match its contract.", "request_contract_invalid", 0, null, null, requestErrors);
    const route = appendQuery(buildPath(operation.path, path), query);
    const provided = typeof this.headers === "function" ? await this.headers() : this.headers;
    const headers = normalizeHeaders({ Accept: "application/json", ...(operation.request.body === null ? {} : { "Content-Type": "application/json" }), ...provided, ...(args.headers ?? {}) });
    const request: PanelSdkTransportRequest = {
      method: operation.method,
      url: this.baseUrl + route,
      headers,
      ...(operation.request.body === null ? {} : { body: args.body as JsonValue }),
      ...(args.signal ? { signal: args.signal } : {}),
    };
    const response = await this.transport(request);
    if (!Number.isInteger(response.status) || response.status < 100 || response.status > 599) throw new PanelSdkError("Transport returned an invalid status.", "transport_invalid", 0, null, response.body);
    if (response.status < 200 || response.status >= 300) {
      const schema = operation.errors[String(response.status)] ?? operation.errors.default;
      const validation = schema ? validateValue(response.body, schema, "$.error", "response") : [];
      const details = publicError(response.body);
      throw new PanelSdkError(details.message, details.code, response.status, details.correlationId, response.body, validation);
    }
    if (this.validateResponses) {
      const validation = validateValue(response.body, operation.response, "$.response", "response");
      if (validation.length) throw new PanelSdkError("SDK response does not match its contract.", "response_contract_invalid", response.status, publicError(response.body).correlationId, response.body, validation);
    }
    return response.body as T;
  }
}

const fetchTransport: PanelSdkTransport = async (request) => {
  if (typeof fetch !== "function") throw new PanelSdkError("No fetch implementation is available.", "transport_unavailable", 0, null, null);
  const response = await fetch(request.url, {
    method: request.method,
    headers: request.headers,
    ...(request.body === undefined ? {} : { body: JSON.stringify(request.body) }),
    credentials: "same-origin",
    redirect: "error",
    ...(request.signal ? { signal: request.signal } : {}),
  });
  const text = await response.text();
  let body: unknown = null;
  if (text !== "") {
    try { body = JSON.parse(text) as unknown; }
    catch { throw new PanelSdkError("Transport returned malformed JSON.", "response_json_invalid", response.status, response.headers.get("x-correlation-id"), text); }
  }
  return { status: response.status, body, headers: Object.fromEntries(response.headers.entries()) };
};

function normalizeBaseUrl(value: string): string {
  const trimmed = value.trim();
  if (trimmed === "") return "";
  let url: URL;
  try { url = new URL(trimmed); } catch { throw new TypeError("Panel SDK baseUrl must be an absolute HTTP(S) URL or empty for same-origin requests."); }
  if (!/^https?:$/.test(url.protocol) || url.username || url.password || url.search || url.hash) throw new TypeError("Panel SDK baseUrl must not contain credentials, query, or fragment data.");
  return url.toString().replace(/\/$/, "");
}

function normalizeHeaders(headers: Readonly<Record<string, string>>): Readonly<Record<string, string>> {
  const output: Record<string, string> = {};
  for (const [name, value] of Object.entries(headers)) {
    if (!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(name) || /[\r\n]/.test(value)) throw new TypeError("Panel SDK header is invalid.");
    output[name] = value;
  }
  return output;
}

function buildPath(template: string, values: Readonly<Record<string, unknown>>): string {
  return template.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (_token, name: string) => {
    const value = values[name];
    if (typeof value !== "string" && typeof value !== "number") throw new TypeError(`Missing path parameter ${name}.`);
    return encodeURIComponent(String(value));
  });
}

function appendQuery(path: string, values: Readonly<Record<string, unknown>>): string {
  const query = new URLSearchParams();
  for (const [name, value] of Object.entries(values)) {
    if (value === undefined || value === null || value === "") continue;
    const items = Array.isArray(value) ? value : [value];
    for (const item of items) query.append(name, typeof item === "object" && item !== null ? JSON.stringify(item) : String(item));
  }
  const encoded = query.toString();
  return encoded ? `${path}?${encoded}` : path;
}

function publicError(body: unknown): { code: string; message: string; correlationId: string | null } {
  const object = isObject(body) ? body : {};
  const nested = isObject(object.error) ? object.error : {};
  const code = typeof nested.code === "string" ? nested.code : (typeof object.code === "string" ? object.code : "http_error");
  const message = typeof nested.message === "string" ? nested.message : (typeof object.message === "string" ? object.message : "Panel request failed.");
  const candidate = typeof nested.correlation_id === "string" ? nested.correlation_id : (typeof object.correlation_id === "string" ? object.correlation_id : null);
  return { code, message, correlationId: candidate };
}

function validateValue(value: unknown, schema: RuntimeSchema, path: string, mode: "request" | "response", depth = 0, budget: { count: number } = { count: 0 }): string[] {
  if (depth > 24 || ++budget.count > 20_000) return [`${path}: value exceeds validation bounds`];
  const anyOf = Array.isArray(schema.anyOf) ? schema.anyOf as RuntimeSchema[] : null;
  if (anyOf) return anyOf.some((member) => validateValue(value, member, path, mode, depth + 1, budget).length === 0) ? [] : [`${path}: union mismatch`];
  const type = typeof schema.type === "string" ? schema.type : null;
  if (type === null) return isJsonValue(value, new Set<object>(), 0, budget) ? [] : [`${path}: value is not bounded JSON`];
  if (!matchesType(value, type)) return [`${path}: expected ${type}`];
  const enumeration = Array.isArray(schema.enum) ? schema.enum : null;
  if (enumeration && !enumeration.some((item) => Object.is(item, value))) return [`${path}: enum mismatch`];
  const errors: string[] = [];
  if (type === "string") {
    const text = value as string;
    if (typeof schema.minLength === "number" && [...text].length < schema.minLength) errors.push(`${path}: shorter than minLength`);
    if (typeof schema.maxLength === "number" && [...text].length > schema.maxLength) errors.push(`${path}: longer than maxLength`);
    if (typeof schema.pattern === "string" && !(new RegExp(schema.pattern, "u")).test(text)) errors.push(`${path}: pattern mismatch`);
    if (typeof schema.format === "string" && !matchesFormat(text, schema.format)) errors.push(`${path}: format mismatch`);
  } else if (type === "number" || type === "integer") {
    const number = value as number;
    if (typeof schema.minimum === "number" && number < schema.minimum) errors.push(`${path}: below minimum`);
    if (typeof schema.maximum === "number" && number > schema.maximum) errors.push(`${path}: above maximum`);
  } else if (type === "array") {
    const items = value as unknown[];
    if (typeof schema.minItems === "number" && items.length < schema.minItems) errors.push(`${path}: fewer than minItems`);
    if (typeof schema.maxItems === "number" && items.length > schema.maxItems) errors.push(`${path}: more than maxItems`);
    if (schema.uniqueItems === true) {
      const unique = new Set(items.map((item) => canonicalJson(item)));
      if (unique.size !== items.length) errors.push(`${path}: duplicate items rejected`);
    }
    const itemSchema = schema.items as RuntimeSchema;
    items.forEach((item, index) => errors.push(...validateValue(item, itemSchema, `${path}[${index}]`, mode, depth + 1, budget)));
  } else if (type === "object") {
    const object = value as Record<string, unknown>;
    const properties = isObject(schema.properties) ? schema.properties as Record<string, RuntimeSchema> : {};
    const required = Array.isArray(schema.required) ? schema.required.filter((item): item is string => typeof item === "string") : [];
    required.forEach((name) => { if (!(name in object)) errors.push(`${path}.${name}: required property missing`); });
    for (const [name, item] of Object.entries(object)) {
      if (properties[name]) errors.push(...validateValue(item, properties[name], `${path}.${name}`, mode, depth + 1, budget));
      else if (mode === "request" && schema.additionalProperties === false) errors.push(`${path}.${name}: additional property rejected`);
      else if (isObject(schema.additionalProperties)) errors.push(...validateValue(item, schema.additionalProperties as RuntimeSchema, `${path}.${name}`, mode, depth + 1, budget));
    }
  }
  return errors.slice(0, 100);
}

function matchesType(value: unknown, type: string): boolean {
  if (type === "null") return value === null;
  if (type === "boolean") return typeof value === "boolean";
  if (type === "integer") return typeof value === "number" && Number.isInteger(value);
  if (type === "number") return typeof value === "number" && Number.isFinite(value);
  if (type === "string") return typeof value === "string";
  if (type === "array") return Array.isArray(value);
  if (type === "object") return isObject(value);
  return false;
}

function isObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value) as object | null;
  return prototype === Object.prototype || prototype === null;
}

function isJsonValue(value: unknown, seen: Set<object>, depth: number, budget: { count: number }): value is JsonValue {
  if (depth > 24 || ++budget.count > 20_000) return false;
  if (value === null || typeof value === "boolean" || typeof value === "string") return true;
  if (typeof value === "number") return Number.isFinite(value);
  if (typeof value !== "object" || (!Array.isArray(value) && !isObject(value))) return false;
  if (seen.has(value)) return false;
  seen.add(value);
  const valid = Array.isArray(value)
    ? value.every((item) => isJsonValue(item, seen, depth + 1, budget))
    : Object.values(value as Record<string, unknown>).every((item) => isJsonValue(item, seen, depth + 1, budget));
  seen.delete(value);
  return valid;
}

function matchesFormat(value: string, format: string): boolean {
  if (format === "email") return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
  if (format === "uuid") return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
  if (format === "date") {
    const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
    if (!match) return false;
    const date = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])));
    return date.toISOString().slice(0, 10) === value;
  }
  if (format === "date-time") return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && Number.isFinite(Date.parse(value));
  if (format === "uri") { try { new URL(value); return true; } catch { return false; } }
  return true;
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map((item) => canonicalJson(item)).join(",")}]`;
  if (isObject(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`;
  return JSON.stringify(value) ?? "undefined";
}
TS;
		return str_replace(['__VERSION__','__FINGERPRINT__','__CONTRACT__','__TYPES__','__METHODS__'],[$version,$fingerprint,$contractJson,$typeBlock,$methodBlock],$template)."\n";
	}

	/** @param array<string,mixed> $schema */
	private function schemaType(array $schema,int $depth=0):string {
		if($depth>24){return'JsonValue';}if(isset($schema['anyOf'])&&is_array($schema['anyOf'])){return implode(' | ',array_map(fn(array $member):string=>'('.$this->schemaType($member,$depth+1).')',$schema['anyOf']));}
		$type=$schema['type']??null;if($type===null){return'JsonValue';}if(isset($schema['enum'])&&is_array($schema['enum'])){return implode(' | ',array_map(static fn(mixed $value):string=>json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$schema['enum']));}
		return match($type){'null'=>'null','boolean'=>'boolean','integer','number'=>'number','string'=>'string','array'=>'ReadonlyArray<'.$this->schemaType((array)$schema['items'],$depth+1).'>','object'=>$this->objectType($schema,$depth+1),default=>'JsonValue'};
	}

	/** @param array<string,mixed> $schema */
	private function objectType(array $schema,int $depth):string {
		$properties=(array)($schema['properties']??[]);$required=array_flip((array)($schema['required']??[]));$members=[];foreach($properties as$name=>$child){$members[]=self::tsString((string)$name).(isset($required[$name])?'':'?').': '.$this->schemaType((array)$child,$depth+1).';';}
		$base=$members===[]?'Readonly<Record<string, never>>':'{ readonly '.implode(' readonly ',$members).' }';$additional=$schema['additionalProperties']??false;if($additional===true){return$members===[]?'Readonly<Record<string, JsonValue>>':'('.$base.' & Readonly<Record<string, JsonValue>>)';}if(is_array($additional)){return$members===[]?'Readonly<Record<string, '.$this->schemaType($additional,$depth+1).'>>':'('.$base.' & Readonly<Record<string, '.$this->schemaType($additional,$depth+1).'>>)';}return$base;
	}

	private function readme(PanelSdkContract $contract,string $package):string {return'# '.$contract->label()." TypeScript SDK\n\nGenerated from Panel SDK contract `".$contract->fingerprint()."`. Routes are host-bound. Authentication and CSRF headers must be supplied by the host through `headers`; no credentials are generated or embedded.\n\n```ts\nimport { PanelClient } from '".$package."';\n\nconst panel = new PanelClient({\n  headers: async () => ({ 'X-CSRF-Token': await csrfToken() }),\n});\n```\n\nRun `npm run check` before publishing the generated package.\n";}
	private static function typeName(string $value):string {$parts=preg_split('/[^A-Za-z0-9]+/',$value,-1,PREG_SPLIT_NO_EMPTY)?:[];$name=implode('',array_map(static fn(string $part):string=>ucfirst($part),$parts));return$name!==''?$name:'PanelValue';}
	private static function methodName(string $value):string {$name=self::typeName($value);return lcfirst($name);}
	private static function tsString(string $value):string{return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);}
}
