<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

use Dataphyre\Panel\PanelCallbackFederationTransport;
use Dataphyre\Panel\PanelEncryptedCommandPayloadCodec;
use Dataphyre\Panel\PanelFederationControlPlane;
use Dataphyre\Panel\PanelFederationGateway;
use Dataphyre\Panel\PanelFederationMessage;
use Dataphyre\Panel\PanelFederationNode;
use Dataphyre\Panel\PanelPolicyBundle;
use Dataphyre\Panel\PanelPolicyControlPlane;
use Dataphyre\Panel\PanelPolicyRequest;
use Dataphyre\Test\Context;
use function Dataphyre\Test\test;

require_once __DIR__.'/panel_test_harness_helpers.php';
dp_panel_unit_test_bootstrap();

function dp_panel_federation_transport_policy(bool $allow=true):PanelPolicyControlPlane {
	$policy=new PanelPolicyControlPlane([],false);if($allow){$policy->register(PanelPolicyBundle::from(['id'=>'federation_transport','version'=>'1.0.0','rules'=>['federation'=>['effect'=>'allow','abilities'=>['federation.*'],'priority'=>100,'reason'=>'Trusted federation transport.']]]));}return$policy;
}

function dp_panel_federation_transport_request(string $actor='Fleet:Operator'):PanelPolicyRequest {
	return new PanelPolicyRequest($actor,'federation.transport.send','Tenant:A',null,null,'high',['fleet_operator'],['federation.*']);
}

test('federation messages bind signature audience expiry encrypted payload and exact ciphertext while node metadata stays private',static function(Context $t):void {
	$key=str_repeat('F',48);$codec=new PanelEncryptedCommandPayloadCodec(str_repeat('E',48),static fn():string=>str_repeat("\x01",12));$secret='federation-payload-private';$issued='2026-07-16T12:00:00.000000Z';$message=PanelFederationMessage::sign('desired_state','node_a','node_b',1,['desired'=>['policy'=>hash('sha256','policy')],'diagnostic'=>$secret],$issued,'2026-07-16T12:05:00Z','primary',$key,$codec,null,str_repeat('a',32));
	$t->isTrue($message->verify(['primary'=>$key],$issued,'node_b'));$t->isFalse($message->verify(['primary'=>$key],$issued,'node_c'));$t->same($secret,$message->open($codec)['diagnostic']);$t->same($message->digest(),PanelFederationMessage::fromWire($message->wire())->digest());$t->notContains($secret,json_encode($message,JSON_THROW_ON_ERROR));$t->notContains($secret,json_encode($message->wire(),JSON_THROW_ON_ERROR));$t->notContains('ciphertext',json_encode($message,JSON_THROW_ON_ERROR));$t->isFalse($message->verify(['primary'=>$key],'2026-07-16T12:06:00Z','node_b'));
	$tampered=$message->wire();$tampered['sealed']['ciphertext']=strrev($tampered['sealed']['ciphertext']);$t->throws(static fn()=>PanelFederationMessage::fromWire($tampered),UnexpectedValueException::class);$wrongKey=$message->wire();$wrongKey['manifest']['signature']=str_repeat('0',64);$t->isFalse(PanelFederationMessage::fromWire($wrongKey)->verify(['primary'=>$key],$issued,'node_b'));
	$metadataSecret='node-metadata-private';$node=PanelFederationNode::sign('node_a','production','ca',1,'2026-07-16T11:59:00Z','2026-07-16T12:10:00Z',['deploy'],['policy'=>hash('sha256','policy')],['token'=>$metadataSecret],'primary',$key);$public=$node->jsonSerialize();$t->notContains($metadataSecret,json_encode($public,JSON_THROW_ON_ERROR));$t->isTrue($public['metadata_redacted']);$hydrated=PanelFederationNode::hydrate($public);$t->isFalse($hydrated->hasMetadataPayload());$t->isTrue($hydrated->verifyStored(['primary'=>$key]));
})->tag('panel','federation','transport','encryption','signature','redaction')->isolation('case')->maxMillis(8000);

test('durable federation gateways exchange heartbeat desired state and reconciliation with restart-safe exact acknowledgement replay',static function(Context $t):void {
	$key=str_repeat('F',48);$root=$t->tempDirectory('federation-gateway-e2e');$policy=dp_panel_federation_transport_policy();$request=dp_panel_federation_transport_request();$now='2026-07-16T12:00:00.000000Z';$clock=static function()use(&$now):string{return$now;};$codec=new PanelEncryptedCommandPayloadCodec(str_repeat('E',48));
	$controlB=new PanelFederationControlPlane(['primary'=>$key],$clock,$root.'/control-b','primary');$gatewayB=new PanelFederationGateway($root.'/gateway-b','node_b',$controlB,$policy,$codec,['primary'=>$key],'primary',null,$clock);$transport=new PanelCallbackFederationTransport('node_b_link',static fn(array $wire):array=>$gatewayB->receive($wire));$controlA=new PanelFederationControlPlane(['primary'=>$key],$clock,$root.'/control-a','primary');$gatewayA=new PanelFederationGateway($root.'/gateway-a','node_a',$controlA,$policy,$codec,['primary'=>$key],'primary',$transport,$clock);
	$metadataSecret='private-node-zone-token';$node=PanelFederationNode::sign('node_a','production','ca',1,'2026-07-16T11:59:00Z','2026-07-16T12:10:00Z',['deploy','sync'],['policy'=>hash('sha256','old-policy')],['zone_token'=>$metadataSecret],'primary',$key);$heartbeat=$gatewayA->heartbeat($node,'node_b',$request,'heartbeat-one');$t->same('delivered',$heartbeat['status']);$t->same(1,$controlB->revision());$t->same('node_a',$controlB->node('node_a')->id());$t->isFalse($controlB->node('node_a')->hasMetadataPayload());
	$t->same(['node_a'],array_keys($controlB->nodes()));$t->notNull($controlB->store());$t->isTrue($controlB->quorum('deploy',1)['met']);$checkpoint=$controlB->checkpoint();$checkpointClone=(new PanelFederationControlPlane(['primary'=>$key],$clock))->restore($checkpoint);$t->same($controlB->revision(),$checkpointClone->revision());$t->same(['node_a'],array_keys($checkpointClone->nodes()));
	$replay=$gatewayA->heartbeat($node,'node_b',$request,'heartbeat-one');$t->isTrue($replay['replayed']);$t->same(1,$controlB->revision());$desired=['domains'=>hash('sha256','domain-set'),'policy'=>hash('sha256','next-policy')];$pushed=$gatewayA->pushDesired('node_b',$desired,$request,'desired-one');$t->same('delivered',$pushed['status']);$t->same($desired,$controlB->desiredState());$reconciled=$gatewayA->requestReconciliation('node_b',$request,'reconcile-method-one');$t->same('delivered',$reconciled['status']);$diagnosticSecret='encrypted-wire-diagnostic';$diagnostic=$gatewayA->send('reconcile_request','node_b',['requested_revision'=>$controlA->revision(),'diagnostic'=>$diagnosticSecret],$request,'reconcile-one');$t->same('delivered',$diagnostic['status']);
	$state=$gatewayA->store()->payload();$heartbeatEntry=$state['outbox'][$heartbeat['id']];$wire=['manifest'=>$heartbeatEntry['manifest'],'sealed'=>$heartbeatEntry['sealed']];$ack=$gatewayB->receive($wire);$t->same('acknowledgement',$ack['manifest']['kind']);
	$reopenedControl=new PanelFederationControlPlane(['primary'=>$key],$clock,$root.'/control-b','primary');$reopenedGateway=new PanelFederationGateway($root.'/gateway-b','node_b',$reopenedControl,$policy,$codec,['primary'=>$key],'primary',null,$clock);$restartAck=$reopenedGateway->receive($wire);$t->same($ack['manifest']['digest'],$restartAck['manifest']['digest']);$t->same($desired,$reopenedControl->desiredState());$t->same('node_a',$reopenedControl->node('node_a')->id());$t->isTrue($reopenedControl->verifyIntegrity()['ok']);$t->isTrue($reopenedGateway->verifyIntegrity()['ok']);
	$encoded=json_encode([$gatewayA,$gatewayB,$controlA,$controlB],JSON_THROW_ON_ERROR);$t->notContains($metadataSecret,$encoded);$t->notContains($diagnosticSecret,$encoded);$contents='';foreach(glob($root.'/{control-a,control-b,gateway-a,gateway-b}/*.json',GLOB_BRACE)?:[]as$file){$contents.=(string)file_get_contents($file);}$t->notContains($metadataSecret,$contents);$t->notContains($diagnosticSecret,$contents);
})->tag('panel','federation','transport','heartbeat','desired-state','restart','idempotency','redaction')->isolation('case')->maxMillis(18000);

test('federation outbox recovers a lost acknowledgement and rejects sequence nonce expiry and signed-state attacks',static function(Context $t):void {
	$key=str_repeat('F',48);$root=$t->tempDirectory('federation-gateway-recovery');$policy=dp_panel_federation_transport_policy();$request=dp_panel_federation_transport_request();$now='2026-07-16T12:00:00.000000Z';$clock=static function()use(&$now):string{return$now;};$codec=new PanelEncryptedCommandPayloadCodec(str_repeat('E',48));$controlB=new PanelFederationControlPlane(['primary'=>$key],$clock,$root.'/control-b','primary');$gatewayB=new PanelFederationGateway($root.'/gateway-b','node_b',$controlB,$policy,$codec,['primary'=>$key],'primary',null,$clock);$loseAck=true;
	$transport=new PanelCallbackFederationTransport('lossy_link',static function(array $wire)use($gatewayB,&$loseAck):array{$ack=$gatewayB->receive($wire);if($loseAck){$loseAck=false;throw new RuntimeException('simulated acknowledgement loss');}return$ack;});$controlA=new PanelFederationControlPlane(['primary'=>$key],$clock,$root.'/control-a','primary');$gatewayA=new PanelFederationGateway($root.'/gateway-a','node_a',$controlA,$policy,$codec,['primary'=>$key],'primary',$transport,$clock);
	$desired=['policy'=>hash('sha256','policy-v2')];$t->throws(static fn()=>$gatewayA->pushDesired('node_b',$desired,$request,'lost-ack'),RuntimeException::class);$pending=$gatewayA->outbox()[0];$t->same('pending',$pending['status']);$t->same(1,$pending['attempts']);$revision=$controlB->revision();$flushed=$gatewayA->flush($request,10,0);$t->same([],$flushed['errors']);$t->same('delivered',$flushed['delivered'][0]['status']);$t->same(2,$flushed['delivered'][0]['attempts']);$t->same($revision,$controlB->revision());
	$message=PanelFederationMessage::sign('desired_state','node_c','node_b',1,['desired'=>['policy'=>hash('sha256','node-c-one')]],$now,'2026-07-16T12:05:00Z','primary',$key,$codec,null,str_repeat('b',32));$firstAck=$gatewayB->receive($message->wire());$t->same($firstAck['manifest']['digest'],$gatewayB->receive($message->wire())['manifest']['digest']);$sameSequence=PanelFederationMessage::sign('desired_state','node_c','node_b',1,['desired'=>['policy'=>hash('sha256','node-c-two')]],$now,'2026-07-16T12:05:00Z','primary',$key,$codec,null,str_repeat('c',32));$t->throws(static fn()=>$gatewayB->receive($sameSequence->wire()),LogicException::class);$sameNonce=PanelFederationMessage::sign('desired_state','node_c','node_b',2,['desired'=>['policy'=>hash('sha256','node-c-three')]],$now,'2026-07-16T12:05:00Z','primary',$key,$codec,null,str_repeat('b',32));$t->throws(static fn()=>$gatewayB->receive($sameNonce->wire()),LogicException::class);
	$invalidPayload=PanelFederationMessage::sign('desired_state','node_invalid','node_b',1,['desired'=>'not-a-digest-map'],$now,'2026-07-16T12:05:00Z','primary',$key,$codec);$rejectedAck=PanelFederationMessage::fromWire($gatewayB->receive($invalidPayload->wire()))->open($codec);$t->same('rejected',$rejectedAck['status']);$t->same('invalid_payload',$rejectedAck['error_code']);
	$queued=$gatewayA->requestReconciliation('node_b',$request,'stale-reconciliation',false);$gatewayInternals=$t->nonPublic($gatewayA);$gatewayInternals->invoke('mutate',static function(array&$state)use($queued):void{$state['outbox'][$queued['id']]['status']='sending';$state['outbox'][$queued['id']]['updated_at']='2026-07-16T11:59:00.000000Z';},'federation.test.stale-delivery',['message_id'=>$queued['id']]);$now='2026-07-16T12:00:31.000000Z';$stale=$gatewayA->flush($request,10,30);$t->same('delivered',$stale['delivered'][0]['status']);$t->throws(static fn()=>$gatewayInternals->invoke('epoch','not-an-instant'),UnexpectedValueException::class);$now='2026-07-16T12:00:00.000000Z';
	$expired=PanelFederationMessage::sign('reconcile_request','node_d','node_b',1,['requested_revision'=>0],$now,'2026-07-16T12:01:00Z','primary',$key,$codec);$now='2026-07-16T12:02:00.000000Z';$t->throws(static fn()=>$gatewayB->receive($expired->wire()),LogicException::class);
	$files=glob($root.'/gateway-a/*.json')?:[];sort($files,SORT_STRING);$latest=$files[array_key_last($files)];$snapshot=json_decode((string)file_get_contents($latest),true,512,JSON_THROW_ON_ERROR);$snapshot['payload']['outbound_sequence']++;file_put_contents($latest,json_encode($snapshot,JSON_THROW_ON_ERROR));$t->throws(static fn()=>new PanelFederationGateway($root.'/gateway-a','node_a',$controlA,$policy,$codec,['primary'=>$key],'primary',$transport,$clock),UnexpectedValueException::class);
	$deniedPolicy=dp_panel_federation_transport_policy(false);$denied=new PanelFederationGateway($root.'/gateway-denied','node_z',new PanelFederationControlPlane(['primary'=>$key],$clock),$deniedPolicy,$codec,['primary'=>$key],'primary',null,$clock);$blocked=PanelFederationMessage::sign('reconcile_request','node_y','node_z',1,['requested_revision'=>0],$now,'2026-07-16T12:05:00Z','primary',$key,$codec);$t->throws(static fn()=>$denied->receive($blocked->wire()),LogicException::class);
})->tag('panel','federation','transport','outbox','replay','nonce','expiry','tamper','policy')->isolation('case')->maxMillis(18000);
