<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

use Dataphyre\Panel\PanelAdapterConformanceCatalog;
use Dataphyre\Panel\PanelAdapterConformanceRunner;
use Dataphyre\Panel\PanelOperationConflict;
use Dataphyre\Panel\PanelOperationLease;
use Dataphyre\Panel\PanelOperationLeaseLost;
use Dataphyre\Panel\PanelOperationRecord;
use Dataphyre\Panel\PanelOperationReservation;
use Dataphyre\Panel\PanelOperationStatus;
use Dataphyre\Panel\PanelOperationStorageException;
use Dataphyre\Panel\PanelPdoLeasedOperationStore;
use Dataphyre\Test\Context;
use function Dataphyre\Test\framework;
use function Dataphyre\Test\suite;
use function Dataphyre\Test\test;

framework(['panel']);

function dp_panel_pdo_operations_connection(string $path,int $busyMilliseconds=5000):PDO{
	$pdo=new PDO('sqlite:'.$path);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('PRAGMA busy_timeout = '.max(0,$busyMilliseconds));return$pdo;
}

/** @param array<string,mixed> $options @return array{path:string,pdo:PDO,store:PanelPdoLeasedOperationStore,advance:Closure,clock:Closure} */
function dp_panel_pdo_operations_fixture(Context $t,string $name,array $options=[]):array{
	$path=$t->tempDirectory('panel-pdo-operations-'.$name).DIRECTORY_SEPARATOR.'operations.sqlite';$pdo=dp_panel_pdo_operations_connection($path);$now='2026-07-14T12:00:00+00:00';$token=0;
	$clock=static function()use(&$now):string{return$now;};$advance=static function(int $seconds)use(&$now):void{$now=(new DateTimeImmutable($now))->modify('+'.$seconds.' seconds')->format(DATE_ATOM);};$tokens=static function()use(&$token):string{$token++;return str_pad('pdo-operation-token-'.$token,64,'x');};
	$store=new PanelPdoLeasedOperationStore($pdo,$options,$clock,$tokens);return compact('path','pdo','store','advance','clock');
}

/** @param array<string,mixed> $options */
function dp_panel_pdo_operation_record(string $id,array $options=[]):PanelOperationRecord{return PanelOperationRecord::make((string)($options['type']??'job'),(string)($options['name']??$id),$options+['id'=>$id,'created_at'=>'2026-07-14T12:00:00Z']);}

function dp_panel_pdo_operation_error(Context $t,callable $callback,string $code):PanelOperationStorageException{
	try{$callback();}catch(PanelOperationStorageException $error){$t->same($code,$error->errorCode());return$error;}throw new RuntimeException("Expected PanelOperationStorageException {$code}.");
}

suite('Panel durable shared-SQL leased-operation store')
	->contract('panel.operations.pdo-leased-store',1)
	->layer('integration')
	->risk('critical')
	->watches('module:panel')
	->through('pdo','schema-migration','optimistic-revisions','idempotency','leases','fencing','expiry-recovery','cross-process')
	->isolation('case')
	->tag('panel','operations','pdo','distributed','security')
	->group('framework-coverage');

test('pdo leased-operation schema plans are explicit portable idempotent and connection-redacted',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'schema',['table_prefix'=>'op_schema','maximum_record_bytes'=>16384,'change_retention'=>32,'transaction_retries'=>2,'retry_delay_microseconds'=>0]);$store=$fixture['store'];$first=$store->installSchema();$second=$store->installSchema();
	$t->same('sqlite',$store->driver());$t->same(9,$first['statements']);$t->same($first,$second);$t->isTrue($first['idempotent']);$t->isFalse($first['destructive']);$t->same($store->schemaStatements(),PanelPdoLeasedOperationStore::schemaStatementsFor('sqlite','op_schema'));
	$sqlite=PanelPdoLeasedOperationStore::schemaStatementsFor('sqlite','op_plan');$mysql=PanelPdoLeasedOperationStore::schemaStatementsFor('mysql','op_plan');$pgsql=PanelPdoLeasedOperationStore::schemaStatementsFor('pgsql','op_plan');$t->same(9,count($sqlite));$t->same(5,count($mysql));$t->same(9,count($pgsql));$t->contains('AUTOINCREMENT',$sqlite[6]);$t->contains('ENGINE=InnoDB',$mysql[0]);$t->contains('SKIP LOCKED',PanelPdoLeasedOperationStore::dialectPlanFor('mysql')['reserve_suffix']);$t->contains('GENERATED BY DEFAULT AS IDENTITY',$pgsql[6]);$t->contains('REPEATABLE READ',PanelPdoLeasedOperationStore::dialectPlanFor('pgsql')['read_after'][0]);$t->same('BEGIN IMMEDIATE',PanelPdoLeasedOperationStore::dialectPlanFor('sqlite')['write_begin']);
	$manifest=$store->manifest();$encoded=json_encode($store,JSON_THROW_ON_ERROR);$t->same('panel_pdo_leased_operation_store',$manifest['type']);$t->isTrue($manifest['distributed']);$t->isTrue($manifest['fencing']);$t->isTrue($manifest['change_feed']);$t->isFalse($manifest['raw_lease_tokens_stored']);$t->isTrue($manifest['raw_idempotency_key_in_record']);foreach([$fixture['path'],'op_schema','sqlite:','password','token_hash','record_json']as$secret){$t->notContains($secret,$encoded);}
})->tag('panel','operations','pdo','schema','manifest')->maxMillis(5000);

test('pdo store passes optimistic and leased conformance across independent connections',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'conformance',['table_prefix'=>'op_conformance']);$store=$fixture['store'];$store->installSchema();$runner=new PanelAdapterConformanceRunner();
	$operations=$runner->run(PanelAdapterConformanceCatalog::operationStore(),$store,['allow_destructive'=>true]);$leases=$runner->run(PanelAdapterConformanceCatalog::leasedOperationStore(),$store,['allow_destructive'=>true]);$t->isTrue($operations->passed());$t->isTrue($leases->passed());$t->same(1,$operations->summary()['passed']);$t->same(1,$leases->summary()['passed']);$t->same([],$store->all());
	$first=$store->create(dp_panel_pdo_operation_record('durable-a',['idempotency_key'=>'durable-key','max_attempts'=>3]));$secondStore=new PanelPdoLeasedOperationStore(dp_panel_pdo_operations_connection($fixture['path']),['table_prefix'=>'op_conformance'],$fixture['clock'],static fn():string=>str_repeat('z',48));$replay=$secondStore->create(dp_panel_pdo_operation_record('durable-b',['idempotency_key'=>'durable-key']));$t->same($first->id(),$replay->id());$t->same($first->id(),$secondStore->findByIdempotencyKey(' durable-key ')?->id());
	$saved=$secondStore->save($first->log('info','persisted',[],'2026-07-14T12:00:01Z'),1);$t->same(2,$saved->revision());$t->same('persisted',$store->get('durable-a')?->logs()[0]['message']);$t->throws(static fn()=>$store->save($first,1),PanelOperationConflict::class);
	$data=$saved->jsonSerialize();$data['idempotency_key']='replacement-key';$rekeyed=$store->save(PanelOperationRecord::fromArray($data),2);$t->same('durable-a',$store->findByIdempotencyKey('replacement-key')?->id());$t->same(null,$store->findByIdempotencyKey('durable-key'));$t->same(null,$store->findByIdempotencyKey(''));
	$other=$store->create(dp_panel_pdo_operation_record('durable-c',['idempotency_key'=>'occupied-key']));$conflict=$rekeyed->jsonSerialize();$conflict['idempotency_key']='occupied-key';$t->throws(static fn()=>$store->save(PanelOperationRecord::fromArray($conflict),$rekeyed->revision()),PanelOperationConflict::class);$t->throws(static fn()=>$store->create(dp_panel_pdo_operation_record('durable-a')),PanelOperationConflict::class);
	$t->same(['durable-a'],array_map(static fn(PanelOperationRecord $record):string=>$record->id(),$store->all(['id'=>['durable-a','absent'],'type'=>'job','queue'=>'default','status'=>PanelOperationStatus::QUEUED,'idempotency_key'=>'replacement-key','worker'=>null],10)));$t->same([], $store->all(['id'=>[]]));$t->same([], $store->all(['id'=>7]));$t->throws(static fn()=>$store->all(['unsupported'=>'x']),InvalidArgumentException::class);$t->same('durable-c',$store->all([],1,1)[0]->id());
	$t->isTrue($store->delete($other->id()));$t->isTrue($store->delete($first->id()));$t->isFalse($store->delete($first->id()));
})->tag('panel','operations','pdo','conformance','durability','cross-connection')->maxMillis(12000);

test('pdo leases retain bearer secrecy advance fences and reject every stale ownership path',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'leases',['table_prefix'=>'op_leases']);$store=$fixture['store'];$store->installSchema();$store->create(dp_panel_pdo_operation_record('lease-job',['idempotency_key'=>'lease-key','total'=>2,'max_attempts'=>4]));$first=$store->acquireLease('lease-job','worker-a',5);$t->isTrue($first instanceof PanelOperationReservation);$t->same(1,$first?->lease()->fence());$t->same(null,$store->acquireLease('lease-job','worker-b'));
	$mutated=$store->mutateLease($first->lease(),static fn(PanelOperationRecord $current):PanelOperationRecord=>$current->progress(1,2,'Half',1,0));$t->same(1,$mutated->record()->processed());$t->same($first->lease()->expiresAt(),$mutated->lease()->expiresAt());$renewed=$store->renewLease($mutated->lease(),30);$t->same(1,count($store->activeLeaseManifests()));$active=json_encode($store->activeLeaseManifests(),JSON_THROW_ON_ERROR);$t->notContains($first->lease()->token(),$active);$t->notContains('token_hash',$active);
	$forged=PanelOperationLease::make('lease-job','worker-a',str_repeat('f',48),1,$first->lease()->acquiredAt(),$renewed->lease()->expiresAt());$t->throws(static fn()=>$store->inspectLease($forged),PanelOperationLeaseLost::class);$t->throws(static fn()=>$store->delete('lease-job'),PanelOperationConflict::class);$t->throws(static fn()=>$store->mutateLease($renewed->lease(),static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->complete()),LogicException::class);$t->throws(static fn()=>$store->finishLease($renewed->lease(),static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->heartbeat()),LogicException::class);
	$released=$store->releaseLease($renewed->lease(),0);$t->same(PanelOperationStatus::RETRY_WAIT,$released->status());$second=$store->reserveLease('Default Queue','worker-b',10);$t->same(null,$second);$second=$store->reserveLease('default','worker-b',10);$t->same(2,$second?->lease()->fence());$t->throws(static fn()=>$store->inspectLease($renewed->lease()),PanelOperationLeaseLost::class);$finished=$store->finishLease($second->lease(),static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->complete(['ok'=>true],PanelOperationStatus::COMPLETED,'2026-07-14T12:00:01Z'));$t->same(PanelOperationStatus::COMPLETED,$finished->status());$t->same([],$store->activeLeaseManifests());$t->same(null,$store->reserveLease());$t->isTrue($store->delete('lease-job'));
})->tag('panel','operations','pdo','leases','fencing','security')->maxMillis(7000);

test('pdo expiry recovery deterministically resolves retry exhaustion cancellation pause and dangling terminal ownership',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'recovery',['table_prefix'=>'op_recovery']);$store=$fixture['store'];$store->installSchema();foreach([
		'retry'=>['max_attempts'=>2],'exhausted'=>['max_attempts'=>1],'cancel'=>['max_attempts'=>2],'pause'=>['max_attempts'=>2],'terminal'=>['max_attempts'=>2],
	]as$id=>$options){$store->create(dp_panel_pdo_operation_record($id,$options));$store->acquireLease($id,'worker-'.$id,5);}
	$store->update('cancel',static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->requestCancel('2026-07-14T12:00:01Z'));$store->update('pause',static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->requestPause('2026-07-14T12:00:01Z'));$store->update('terminal',static fn(PanelOperationRecord $record):PanelOperationRecord=>$record->complete(null,PanelOperationStatus::COMPLETED,'2026-07-14T12:00:01Z'));
	$fixture['advance'](6);$t->same([],$store->activeLeaseManifests());$t->same(null,$store->acquireLease('retry','early-worker'));$first=$store->recoverExpiredLeases(2);$second=$store->recoverExpiredLeases(10);$t->same(4,count(array_merge($first,$second)));$t->same(PanelOperationStatus::RETRY_WAIT,$store->get('retry')?->status());$t->same(PanelOperationStatus::FAILED,$store->get('exhausted')?->status());$t->same(PanelOperationStatus::CANCELLED,$store->get('cancel')?->status());$t->same(PanelOperationStatus::PAUSED,$store->get('pause')?->status());$t->same(PanelOperationStatus::COMPLETED,$store->get('terminal')?->status());$t->same([],$store->recoverExpiredLeases());
	$next=$store->acquireLease('retry','worker-next',5);$t->same(2,$next?->lease()->fence());$fixture['advance'](6);$t->same(PanelOperationStatus::FAILED,$store->recoverExpiredLeases(1)[0]->status());foreach(['retry','exhausted','cancel','pause','terminal']as$id){$t->isTrue($store->delete($id));}
})->tag('panel','operations','pdo','recovery','lifecycle')->maxMillis(8000);

test('independent php workers reserve and finish one shared queue without duplicate ownership',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'process-race',['table_prefix'=>'op_process','change_retention'=>256,'transaction_retries'=>10]);$store=$fixture['store'];$store->installSchema();for($i=1;$i<=24;$i++){$store->create(dp_panel_pdo_operation_record('process-'.$i,['queue'=>'workers','created_at'=>'2020-01-01T00:00:00Z','max_attempts'=>2]));}$panelRoot=dirname(__DIR__);
	$code=<<<'PHP'
foreach(['PanelOperationStatus.php','PanelOperationRecord.php','PanelOperationStore.php','PanelLeasedOperationStore.php','PanelOperationConflict.php','PanelOperationLeaseLost.php','PanelOperationLease.php','PanelOperationReservation.php','PanelOperationStorageException.php','PanelPdoLeasedOperationStore.php'] as $source){require $argv[1].'/Framework/Operations/'.$source;}
$pdo=new PDO('sqlite:'.$argv[2]);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('PRAGMA busy_timeout = 5000');
$store=new \Dataphyre\Panel\PanelPdoLeasedOperationStore($pdo,['table_prefix'=>'op_process','change_retention'=>256,'transaction_retries'=>10],null,static fn():string=>bin2hex(random_bytes(32)));$count=0;
while(($reservation=$store->reserveLease('workers','worker-'.$argv[3],30))!==null){$store->finishLease($reservation->lease(),static fn(\Dataphyre\Panel\PanelOperationRecord $record):\Dataphyre\Panel\PanelOperationRecord=>$record->complete(['worker'=>$argv[3]]));$count++;}
echo $count;
PHP;
	$workers=[];foreach(['a','b','c']as$worker){$workers[]=$t->startPhpProcess(['-r',$code,$panelRoot,$fixture['path'],$worker],timeout_millis:20000);}$total=0;foreach($workers as$process){$result=$process->wait();if(!$result->succeeded()){throw new RuntimeException('Operation worker failed: '.$result->stderr().' '.$result->stdout());}$t->same('',trim($result->stderr()));$total+=(int)trim($result->stdout());}$t->same(24,$total);$records=$store->all(['status'=>PanelOperationStatus::COMPLETED],100);$t->same(24,count($records));$t->same([], $store->activeLeaseManifests());foreach($records as$record){$t->same(1,$record->attempt());$t->same(3,$record->revision());}
})->tag('panel','operations','pdo','cross-process','race','fencing')->maxMillis(30000);

test('bounded change metadata reports retained gaps future resets and never stores operation payloads',static function(Context $t):void{
	$fixture=dp_panel_pdo_operations_fixture($t,'changes',['table_prefix'=>'op_changes','change_retention'=>8]);$store=$fixture['store'];$store->installSchema();for($i=1;$i<=6;$i++){$id='change-'.$i;$store->create(dp_panel_pdo_operation_record($id,['idempotency_key'=>'secret-key-'.$i,'payload'=>['secret'=>'payload-'.$i]]));$store->delete($id);}
	$t->same(12,$store->cursor());$fresh=$store->changesSince(0,2);$t->same(2,count($fresh['changes']));$t->isFalse($fresh['reset_required']);$t->isTrue($fresh['oldest_cursor']>1);$stale=$store->changesSince(1,100);$t->isTrue($stale['reset_required']);$t->same('enumerate_all',$stale['snapshot']['resync']);$t->same([],$stale['changes']);$future=$store->changesSince(99,10);$t->isTrue($future['reset_required']);$t->same(12,$future['cursor']);$current=$store->changesSince(12,10);$t->isFalse($current['reset_required']);$t->same([],$current['changes']);
	$raw=(string)$fixture['pdo']->query('SELECT GROUP_CONCAT(event_type || operation_id || COALESCE(worker, \'\')) FROM op_changes_changes')->fetchColumn();$t->notContains('secret-key',$raw);$t->notContains('payload-',$raw);$t->same(['cursor','type','operation_id','occurred_at'],array_keys($fresh['changes'][0]));
})->tag('panel','operations','pdo','change-feed','retention','privacy')->maxMillis(7000);

test('pdo store fails closed on missing or drifted schemas corruption lock contention and caller transactions',static function(Context $t):void{
	$missing=dp_panel_pdo_operations_fixture($t,'missing',['table_prefix'=>'op_missing']);$error=dp_panel_pdo_operation_error($t,static fn()=>$missing['store']->get('x'),'schema_required');$t->isFalse($error->retryable());
	$broken=dp_panel_pdo_operations_fixture($t,'broken',['table_prefix'=>'op_broken']);$broken['pdo']->exec('CREATE TABLE op_broken_meta (singleton INTEGER PRIMARY KEY)');dp_panel_pdo_operation_error($t,static fn()=>$broken['store']->installSchema(),'migration_failed');
	$drift=dp_panel_pdo_operations_fixture($t,'drift',['table_prefix'=>'op_drift']);$drift['store']->installSchema();$drift['pdo']->exec('UPDATE op_drift_meta SET schema_version = 9');dp_panel_pdo_operation_error($t,static fn()=>$drift['store']->get('x'),'schema_incompatible');dp_panel_pdo_operation_error($t,static fn()=>$drift['store']->installSchema(),'schema_incompatible');
	$nested=dp_panel_pdo_operations_fixture($t,'nested',['table_prefix'=>'op_nested']);$nested['store']->installSchema();$nested['pdo']->beginTransaction();$conflict=dp_panel_pdo_operation_error($t,static fn()=>$nested['store']->all(),'transaction_conflict');$t->isTrue($conflict->retryable());dp_panel_pdo_operation_error($t,static fn()=>$nested['store']->installSchema(),'transaction_conflict');$nested['pdo']->rollBack();
	$locked=dp_panel_pdo_operations_fixture($t,'locked',['table_prefix'=>'op_locked','transaction_retries'=>1,'retry_delay_microseconds'=>1]);$locked['store']->installSchema();$locker=dp_panel_pdo_operations_connection($locked['path'],0);$blockedPdo=dp_panel_pdo_operations_connection($locked['path'],0);$blocked=new PanelPdoLeasedOperationStore($blockedPdo,['table_prefix'=>'op_locked','transaction_retries'=>1,'retry_delay_microseconds'=>1]);$locker->exec('BEGIN IMMEDIATE');$unavailable=dp_panel_pdo_operation_error($t,static fn()=>$blocked->create(dp_panel_pdo_operation_record('blocked')),'storage_unavailable');$t->isTrue($unavailable->retryable());$locker->exec('ROLLBACK');
	$corrupt=dp_panel_pdo_operations_fixture($t,'corrupt',['table_prefix'=>'op_corrupt']);$corrupt['store']->installSchema();$corrupt['store']->create(dp_panel_pdo_operation_record('corrupt-record',['idempotency_key'=>'corrupt-key']));$corrupt['pdo']->exec('UPDATE op_corrupt_operations SET record_bytes = record_bytes + 1');dp_panel_pdo_operation_error($t,static fn()=>$corrupt['store']->get('corrupt-record'),'storage_corrupt');$corrupt['pdo']->exec('UPDATE op_corrupt_operations SET record_bytes = length(record_json), operation_status = \'running\'');dp_panel_pdo_operation_error($t,static fn()=>$corrupt['store']->get('corrupt-record'),'storage_corrupt');
	$oversize=dp_panel_pdo_operations_fixture($t,'oversize',['table_prefix'=>'op_oversize','maximum_record_bytes'=>4096]);$oversize['store']->installSchema();dp_panel_pdo_operation_error($t,static fn()=>$oversize['store']->create(dp_panel_pdo_operation_record('too-large',['payload'=>str_repeat('x',5000)])),'record_too_large');
})->tag('panel','operations','pdo','fail-closed','corruption','locking')->maxMillis(10000);

test('pdo store validates configuration clocks token factories record encoding and fence exhaustion',static function(Context $t):void{
	$t->throws(static fn()=>PanelPdoLeasedOperationStore::schemaStatementsFor('oracle'),InvalidArgumentException::class);$t->throws(static fn()=>PanelPdoLeasedOperationStore::schemaStatementsFor('sqlite','bad-prefix'),InvalidArgumentException::class);$t->throws(static fn()=>PanelPdoLeasedOperationStore::dialectPlanFor('sqlsrv'),InvalidArgumentException::class);
	$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);foreach([['unknown'=>1],['table_prefix'=>'1bad'],['maximum_record_bytes'=>1],['change_retention'=>7],['transaction_retries'=>11],['retry_delay_microseconds'=>100001]]as$options){$t->throws(static fn()=>new PanelPdoLeasedOperationStore($pdo,$options),InvalidArgumentException::class);}$silent=new PDO('sqlite::memory:');$silent->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_SILENT);$t->throws(static fn()=>new PanelPdoLeasedOperationStore($silent),InvalidArgumentException::class);
	$t->throws(static fn()=>new PanelOperationStorageException('Bad Code','bad'),InvalidArgumentException::class);$typed=new PanelOperationStorageException('typed_failure','Typed',true);$t->same('typed_failure',$typed->errorCode());$t->isTrue($typed->retryable());
	$duplicate=new PDOException('UNIQUE constraint failed',23000);$t->isTrue($t->nonPublic(new PanelPdoLeasedOperationStore($pdo,['table_prefix'=>'op_duplicate_probe']))->invoke('duplicate',$duplicate));
	$badClock=new PanelPdoLeasedOperationStore($pdo,['table_prefix'=>'op_bad_clock'],static fn():string=>'not-a-time');$badClock->installSchema();$t->throws(static fn()=>$badClock->currentTime(),UnexpectedValueException::class);$integerClock=new PanelPdoLeasedOperationStore($pdo,['table_prefix'=>'op_integer_clock'],static fn():int=>0);$integerClock->installSchema();$t->same('1970-01-01T00:00:00+00:00',$integerClock->currentTime());$dateClock=new PanelPdoLeasedOperationStore($pdo,['table_prefix'=>'op_date_clock'],static fn():DateTimeImmutable=>new DateTimeImmutable('2026-01-01T00:00:00-05:00'));$dateClock->installSchema();$t->same('2026-01-01T05:00:00+00:00',$dateClock->currentTime());
	foreach([static fn():array=>[],static fn():string=>'short',static fn():string=>str_repeat('x',513),static fn():string=>str_repeat('x',31)."\0"]as$index=>$factory){$fixture=dp_panel_pdo_operations_fixture($t,'bad-token-'.$index,['table_prefix'=>'op_bad_token_'.$index]);$store=new PanelPdoLeasedOperationStore($fixture['pdo'],['table_prefix'=>'op_bad_token_'.$index],$fixture['clock'],$factory);$store->installSchema();$t->throws(static fn()=>$store->acquireLease('missing'),UnexpectedValueException::class);}
	$fence=dp_panel_pdo_operations_fixture($t,'fence',['table_prefix'=>'op_fence']);$fence['store']->installSchema();$fence['store']->create(dp_panel_pdo_operation_record('fence-job'));$fence['pdo']->exec('UPDATE op_fence_operations SET fence = '.PHP_INT_MAX);dp_panel_pdo_operation_error($t,static fn()=>$fence['store']->acquireLease('fence-job'),'fence_exhausted');
	$invalid=dp_panel_pdo_operation_record('invalid-json');$data=$invalid->jsonSerialize();$handle=fopen('php://memory','r');$data['payload']=$handle;$t->nonPublic($invalid)->writeProperty('data',$data);$encoding=dp_panel_pdo_operations_fixture($t,'encoding',['table_prefix'=>'op_encoding']);$encoding['store']->installSchema();dp_panel_pdo_operation_error($t,static fn()=>$encoding['store']->create($invalid),'record_invalid');fclose($handle);
})->tag('panel','operations','pdo','validation','exact-coverage')->maxMillis(10000);
