<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

use Dataphyre\Panel\PanelAtomicMigrationStore;
use Dataphyre\Panel\PanelAdapterConformanceCatalog;
use Dataphyre\Panel\PanelAdapterConformanceRunner;
use Dataphyre\Panel\PanelMigrationBatch;
use Dataphyre\Panel\PanelMigrationConflict;
use Dataphyre\Panel\PanelMigrationContext;
use Dataphyre\Panel\PanelMigrationDefinition;
use Dataphyre\Panel\PanelMigrationIntegrity;
use Dataphyre\Panel\PanelMigrationLease;
use Dataphyre\Panel\PanelMigrationLeaseLost;
use Dataphyre\Panel\PanelMigrationPlan;
use Dataphyre\Panel\PanelMigrationPlanner;
use Dataphyre\Panel\PanelMigrationRegistry;
use Dataphyre\Panel\PanelMigrationReport;
use Dataphyre\Panel\PanelMigrationRunner;
use Dataphyre\Panel\PanelMigrationSnapshot;
use Dataphyre\Panel\PanelMigrationStalePlan;
use Dataphyre\Panel\PanelMigrationState;
use Dataphyre\Panel\PanelMigrationVersion;
use Dataphyre\Panel\PanelPlatform;
use Dataphyre\Test\Context;
use function Dataphyre\Test\test;

require_once __DIR__.'/panel_test_harness_helpers.php';
dp_panel_unit_test_bootstrap();

function dp_panel_migration_version(string $semantic,int $schema):PanelMigrationVersion{return PanelMigrationVersion::make($semantic,$schema);}

/** @return array{0:PanelAtomicMigrationStore,1:Closure,2:Closure,3:string} */
function dp_panel_migration_store(Context $t,string $name):array{
	$now='2026-07-14T12:00:00+00:00';$token=0;$run=0;
	$clock=static function()use(&$now):string{return$now;};
	$advance=static function(int $seconds)use(&$now):void{$now=(new DateTimeImmutable($now))->modify('+'.$seconds.' seconds')->format(DATE_ATOM);};
	$tokens=static function()use(&$token):string{$token++;return str_pad('migration-token-'.$token,64,'x');};
	$runs=static function()use(&$run):string{$run++;return'migration-run-'.$run;};
	$directory=$t->tempDirectory('panel-migrations-'.$name);
	return[new PanelAtomicMigrationStore($directory,64,$clock,$tokens,$runs),$advance,$clock,$directory];
}

/** @return array{0:PanelMigrationRegistry,1:PanelMigrationDefinition,2:PanelMigrationDefinition} */
function dp_panel_migration_registry():array{
	$first=PanelMigrationDefinition::make('orders.normalize','orders',dp_panel_migration_version('1.0.0',1),dp_panel_migration_version('1.1.0',2),static function(PanelMigrationContext $context):PanelMigrationBatch{
		$data=$context->data();$items=is_array($data['items']??null)?$data['items']:[];$offset=(int)($context->cursor()??0);$end=min(count($items),$offset+$context->limit());
		for($index=$offset;$index<$end;$index++){$items[$index]['normalized']=true;}$data['items']=$items;$checkpoint=['password'=>'batch-secret','offset'=>$end];
		return$end<count($items)?PanelMigrationBatch::more($data,$end,$end-$offset,$checkpoint):PanelMigrationBatch::complete($data,$end-$offset,$checkpoint);
	},['batch_size'=>2,'capabilities'=>['orders.write'],'preflight'=>static fn(PanelMigrationContext $context):array=>['ok'=>isset($context->data()['items']),'issues'=>['items missing']],'down'=>static function(PanelMigrationContext $context):PanelMigrationBatch{$data=$context->data();foreach(is_array($data['items']??null)?$data['items']:[]as$index=>$item){unset($item['normalized']);$data['items'][$index]=$item;}return PanelMigrationBatch::complete($data,count($data['items']??[]));}]);
	$second=PanelMigrationDefinition::make('orders.index','orders',dp_panel_migration_version('1.1.0',2),dp_panel_migration_version('2.0.0',3),static function(PanelMigrationContext $context):PanelMigrationBatch{$data=$context->data();$data['index']=array_column($data['items']??[],'id');return PanelMigrationBatch::complete($data,count($data['index']));},['dependencies'=>['orders.normalize'],'batch_size'=>10,'capabilities'=>['orders.write'],'down'=>static function(PanelMigrationContext $context):PanelMigrationBatch{$data=$context->data();unset($data['index']);return PanelMigrationBatch::complete($data,1);}]);
	return[new PanelMigrationRegistry([$first,$second]),$first,$second];
}

test('migration value objects enforce versions integrity redaction and safe manifests',static function(Context $t):void{
	$v1=dp_panel_migration_version('1.0.0',1);$v2=dp_panel_migration_version('1.1.0-beta.1+build.2',2);
	$t->same('1.0.0',$v1->semantic());$t->same(1,$v1->schema());$t->isTrue($v1->before($v2));$t->same(-1,$v1->compare($v2));$t->isTrue($v1->equals(PanelMigrationVersion::fromArray($v1->jsonSerialize())));$t->same('1.0.0@1',(string)$v1);
	$t->throws(static fn()=>dp_panel_migration_version('1.0',1),InvalidArgumentException::class);$t->throws(static fn()=>dp_panel_migration_version('01.0.0',1),InvalidArgumentException::class);$t->throws(static fn()=>dp_panel_migration_version('1.0.0',-1),InvalidArgumentException::class);
	$t->isFalse(dp_panel_migration_version('1.0.0',5)->before(dp_panel_migration_version('2.0.0',4)));
	$digest=PanelMigrationIntegrity::digest(['b'=>2,'a'=>1]);$t->same($digest,PanelMigrationIntegrity::digest(['a'=>1,'b'=>2]));$t->same(null,PanelMigrationIntegrity::tenant(''));$t->same('tenant-1',PanelMigrationIntegrity::tenant('tenant-1'));$t->throws(static fn()=>PanelMigrationIntegrity::identifier('bad id'),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationIntegrity::canonicalJson(new stdClass()),InvalidArgumentException::class);
	$redacted=PanelMigrationIntegrity::redact(['password'=>'open','nested'=>['api_key'=>'key','message'=>'token=abc normal']]);$t->same('[REDACTED]',$redacted['password']);$t->same('[REDACTED]',$redacted['nested']['api_key']);$t->contains('token=[REDACTED]',$redacted['nested']['message']);
	$state=PanelMigrationState::make('orders','tenant-1',$v1,['secret'=>'state-only'],['base'],4);$t->same('orders',$state->scope());$t->same('tenant-1',$state->tenant());$t->same(['secret'=>'state-only'],$state->data());$t->same(['base'],$state->applied());$t->same(4,$state->revision());$t->same($state->digest(),PanelMigrationState::fromStored($state->stored())->digest());$t->notContains('state-only',json_encode($state,JSON_THROW_ON_ERROR));
	$evolved=$state->evolved($v2,['done'=>true],['base','next']);$t->same(5,$evolved->revision());$t->throws(static fn()=>PanelMigrationState::make('orders',null,$v1,[],[],-1),InvalidArgumentException::class);$stored=$state->stored();$stored['digest']=str_repeat('0',64);$t->throws(static fn()=>PanelMigrationState::fromStored($stored),RuntimeException::class);unset($stored['digest']);$t->throws(static fn()=>PanelMigrationState::fromStored($stored),RuntimeException::class);
	$context=new PanelMigrationContext('orders','tenant-1','orders.normalize','up',['rows'=>[]],3,25,['secret'=>'value'],true,['id'=>'actor']);$t->same('orders',$context->scope());$t->same('tenant-1',$context->tenant());$t->same('orders.normalize',$context->migrationId());$t->same('up',$context->direction());$t->same(['rows'=>[]],$context->data());$t->same(3,$context->cursor());$t->same(25,$context->limit());$t->isTrue($context->dryRun());$t->same(['id'=>'actor'],$context->actor());$t->same('[REDACTED]',$context->jsonSerialize()['checkpoint']['secret']);
	$t->throws(static fn()=>new PanelMigrationContext('orders',null,'migration','sideways',[],null,1,[],false,null),InvalidArgumentException::class);$t->throws(static fn()=>new PanelMigrationContext('orders',null,'migration','up',[],null,0,[],false,null),InvalidArgumentException::class);
	$batch=PanelMigrationBatch::more(['row'=>1],'next',1,['token'=>'unsafe'],['password'=>'unsafe']);$t->isFalse($batch->done());$t->same('next',$batch->nextCursor());$t->same(1,$batch->processed());$t->same(['row'=>1],$batch->data());$t->same('[REDACTED]',$batch->jsonSerialize()['checkpoint']['token']);$t->same('[REDACTED]',$batch->jsonSerialize()['compensation']['password']);$t->isTrue(PanelMigrationBatch::complete([],0)->done());$t->throws(static fn()=>PanelMigrationBatch::more([],'',1),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationBatch::complete([],-1),InvalidArgumentException::class);
})->tag('panel','migrations','values','security')->maxMillis(3000);

test('migration definitions registry and planner enforce a single dependency-safe version chain',static function(Context $t):void{
	[$registry,$first,$second]=dp_panel_migration_registry();$state=PanelMigrationState::make('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[]]);$planner=new PanelMigrationPlanner($registry);$plan=$planner->plan($state,dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');
	$t->same($registry,$planner->registry());$t->same(['orders.normalize','orders.index'],$plan->migrationIds());$t->same(['orders.write'],$plan->capabilities());$t->same('orders',$plan->scope());$t->same('tenant-a',$plan->tenant());$t->isTrue($plan->source()->equals($state->version()));$t->same('2.0.0',$plan->target()->semantic());$t->same($registry->digest(),$plan->registryDigest());$t->same($state->revision(),$plan->stateRevision());$t->same($state->digest(),$plan->stateDigest());$t->same('panel-migration:'.$plan->digest(),$plan->idempotencyKey());$t->same('2026-07-14T12:00:00+00:00',$plan->createdAt());
	$t->isTrue($registry->has('orders.normalize'));$t->same($first,$registry->get('orders.normalize'));$t->same(2,count($registry->all('orders')));$t->same(0,count($registry->all('other')));$t->same(2,$registry->jsonSerialize()['count']);$t->throws(static fn()=>$registry->get('missing'),OutOfBoundsException::class);$t->throws(static fn()=>$registry->register($first),LogicException::class);$registry->register($first,true);
	$t->same('optional',$first->tenantMode());$t->isTrue($first->supportsTenant(null));$t->isTrue($first->supportsTenant('tenant'));$t->isTrue($first->reversible());$t->isTrue($first->hasPreflight());$t->isTrue($first->idempotent());$t->same(null,$first->deprecatedBy());$t->same(null,$first->deprecationGuidance());$t->same(2,$first->batchSize());$t->same(['orders.write'],$first->capabilities());$t->same(['orders.normalize'],$second->dependencies());$t->same($first->digest(),PanelMigrationIntegrity::digest($first->jsonSerialize()));
	$shared=PanelMigrationDefinition::make('shared.only','shared',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()),['tenant_mode'=>'shared']);$required=PanelMigrationDefinition::make('tenant.only','tenant',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()),['tenant_mode'=>'required']);$t->isTrue($shared->supportsTenant(null));$t->isFalse($shared->supportsTenant('tenant'));$t->isFalse($required->supportsTenant(null));$t->isTrue($required->supportsTenant('tenant'));
	$deprecated=PanelMigrationDefinition::make('old.edge','old',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()),['deprecated_by'=>'new.edge','deprecation_guidance'=>'Replace this edge before 3.0.']);$t->same('new.edge',$deprecated->deprecatedBy());$t->contains('Replace',$deprecated->deprecationGuidance()??'');
	$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',$v=dp_panel_migration_version('1.0.0',1),$v,static fn()=>null),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('1.0.0',5),dp_panel_migration_version('2.0.0',4),static fn()=>null),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['tenant_mode'=>'bad']),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['dependencies'=>'bad']),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['deprecated_by'=>'next']),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['batch_size'=>0]),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['down'=>'invalid']),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['idempotent'=>'yes']),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationDefinition::make('bad','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null,['deprecated_by'=>'bad','deprecation_guidance'=>'self']),InvalidArgumentException::class);
	$wrong=PanelMigrationDefinition::make('wrong','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn()=>null);$ctx=new PanelMigrationContext('x',null,'wrong','up',[],null,1,[],false,null);$t->throws(static fn()=>$wrong->migrate($ctx),UnexpectedValueException::class);$t->throws(static fn()=>$wrong->compensate($ctx),LogicException::class);$t->isTrue($wrong->inspect($ctx));
	$gap=new PanelMigrationPlanner(new PanelMigrationRegistry());$t->throws(static fn()=>$gap->plan(PanelMigrationState::make('x',null,dp_panel_migration_version('0.0.0',0)),dp_panel_migration_version('1.0.0',1)),LogicException::class);
	$edge=static fn(string $id):PanelMigrationDefinition=>PanelMigrationDefinition::make($id,'x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()));$ambiguous=new PanelMigrationPlanner(new PanelMigrationRegistry([$edge('x.a'),$edge('x.b')]));$t->throws(static fn()=>$ambiguous->plan(PanelMigrationState::make('x',null,dp_panel_migration_version('0.0.0',0)),dp_panel_migration_version('1.0.0',1)),LogicException::class);
	$missing=PanelMigrationDefinition::make('x.edge','x',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()),['dependencies'=>['x.missing']]);$t->throws(static fn()=>(new PanelMigrationPlanner(new PanelMigrationRegistry([$missing])))->plan(PanelMigrationState::make('x',null,dp_panel_migration_version('0.0.0',0)),dp_panel_migration_version('1.0.0',1)),LogicException::class);
	$t->throws(static fn()=>PanelMigrationPlan::make($state,$state->version(),[],$registry->digest()),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationPlan::make($state,dp_panel_migration_version('2.0.0',3),[],'bad'),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationPlan::make($state,dp_panel_migration_version('2.0.0',3),['bad'],$registry->digest()),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationPlan::make($state,dp_panel_migration_version('2.0.0',3),[$first,$second],$registry->digest(),'bad-time-['),InvalidArgumentException::class);$t->throws(static fn()=>PanelMigrationPlan::make($state,dp_panel_migration_version('2.0.0',3),[$first],$registry->digest()),InvalidArgumentException::class);
})->tag('panel','migrations','planner','registry')->maxMillis(3000);

test('atomic migration runner dry-runs batches resumes idempotently and never leaks state or bearer proofs',static function(Context $t):void{
	[$store,,,$directory]=dp_panel_migration_store($t,'execute');[$registry]=dp_panel_migration_registry();$seed=$store->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[['id'=>1],['id'=>2],['id'=>3],['id'=>4],['id'=>5]],'password'=>'state-secret']);$authorizations=[];$runner=new PanelMigrationRunner($store,$registry,static function(string $ability,mixed $actor,array $context)use(&$authorizations):bool{$authorizations[]=$ability;return$actor==='admin'&&isset($context['plan']);});
	$plan=$runner->plan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');$t->same($store,$runner->store());$t->same($registry,$runner->registry());$t->same($registry,$runner->planner()->registry());
	$blocked=$runner->preflight($plan,'guest',[]);$t->same('blocked',$blocked->status());$t->isTrue($blocked->terminal());$t->isFalse($blocked->successful());$t->contains('Missing migration capabilities',json_encode($blocked,JSON_THROW_ON_ERROR));$t->contains('not authorized',json_encode($blocked,JSON_THROW_ON_ERROR));
	$dry=$runner->execute($plan,'admin',['orders.write'],'worker-a',true);$t->same('preflight',$dry->status());$t->same($seed->digest(),$store->state('orders','tenant-a')->digest());
	$partial=$runner->execute($plan,'admin',['orders.write'],'worker-a',false,1);$t->same('running',$partial->status());$t->same(1,$partial->jsonSerialize()['batch_count']);$t->same(1,$partial->jsonSerialize()['checkpoint_count']);$runId=$partial->runId();$t->isTrue(is_string($runId));$snapshot=$store->snapshot((string)$runId);$t->isTrue($snapshot instanceof PanelMigrationSnapshot);$t->same($seed->digest(),$snapshot?->stateDigest());$t->same($runId,$snapshot?->runId());$t->notContains('state-secret',json_encode($snapshot,JSON_THROW_ON_ERROR));
	$complete=$runner->resume($plan,'admin',['orders.write'],'worker-b',100);$t->same('completed',$complete->status());$t->isTrue($complete->successful());$t->isTrue($complete->terminal());$t->same(2,$complete->jsonSerialize()['step_index']);$t->same(4,$complete->jsonSerialize()['batch_count']);$t->same(10,$complete->jsonSerialize()['processed']);$t->same(1,$complete->jsonSerialize()['resumes']);$final=$store->state('orders','tenant-a');$t->same('2.0.0',$final->version()->semantic());$t->same([1,2,3,4,5],$final->data()['index']);$t->isTrue($final->data()['items'][4]['normalized']);$t->same(['orders.index','orders.normalize'],$final->applied());
	$json=json_encode($complete,JSON_THROW_ON_ERROR);$t->notContains('batch-secret',$json);$t->notContains('state-secret',$json);$t->contains('[REDACTED]',$json);$t->same($runId,$store->reportByPlan($plan->digest())?->runId());$t->same($runId,$store->report((string)$runId)?->runId());$t->same(null,$store->report('missing-run'));$t->same(null,$store->reportByPlan('bad'));
	$replayed=$runner->execute($plan,'admin',['orders.write'],'worker-c');$t->same('completed',$replayed->status());$t->same($runId,$replayed->runId());$t->isTrue(count($store->changesSince(0,100)['changes'])>0);$manifest=$store->manifest();$t->isTrue($manifest['capabilities']['atomic_batches']);$t->isTrue($manifest['capabilities']['backup_snapshots']);$t->same(0,$manifest['active_leases']);$t->same($manifest,$store->jsonSerialize());$t->isTrue(count($authorizations)>=4);$store->seed('orders','tenant-a',$final->version(),$final->data(),$final->applied());$t->same('blocked',$runner->preflight($plan,'admin',['orders.write'])->status());
	$raw='';foreach(glob($directory.DIRECTORY_SEPARATOR.'*.json')?:[]as$file){$raw.=(string)file_get_contents($file);}$t->notContains('migration-token-',$raw);
})->tag('panel','migrations','runner','resume','security')->maxMillis(7000);

test('migration rollback compensates reversible batches and snapshot-restores irreversible work',static function(Context $t):void{
	[$store]=dp_panel_migration_store($t,'rollback');[$registry]=dp_panel_migration_registry();$store->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[['id'=>1],['id'=>2]]]);$untrusted=new PanelMigrationRunner($store,$registry);$plan=$untrusted->plan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');$t->same('blocked',$untrusted->preflight($plan,null,['orders.write'])->status());$t->same('blocked',$untrusted->execute($plan,null,['orders.write'])->status());$t->isFalse($untrusted->trustedExecution());$t->isFalse($untrusted->manifest()['authorization']['configured']);$t->isTrue($untrusted->manifest()['authorization']['default_deny']);$runner=$untrusted->allowTrustedExecution();$t->isFalse($runner===$untrusted);$t->isTrue($runner->trustedExecution());$t->isTrue($runner->manifest()['authorization']['trusted_execution']);$completed=$runner->execute($plan,null,['orders.write']);$t->same('completed',$completed->status());$t->same('blocked',$untrusted->rollback($plan,null,['orders.write'])->status());$t->same('blocked',$runner->rollback($plan,null,['bad grant'])->status());$rolling=$runner->rollback($plan,null,['orders.write'],maxBatches:1);$t->same('rolling_back',$rolling->status());$t->same(0,$rolling->jsonSerialize()['rollback_index']);$rolled=$runner->rollback($plan,null,['orders.write']);$t->same('rolled_back',$rolled->status());$t->isTrue($rolled->successful());$t->same('compensation',$rolled->jsonSerialize()['rollback_mode']);$restored=$store->state('orders','tenant-a');$t->same('1.0.0',$restored->version()->semantic());$t->same([['id'=>1],['id'=>2]],$restored->data()['items']);$t->same([],$restored->applied());
	[$fallbackStore]=dp_panel_migration_store($t,'rollback-fallback');$irreversible=PanelMigrationDefinition::make('settings.breaking','settings',dp_panel_migration_version('0.0.0',0),dp_panel_migration_version('1.0.0',1),static function(PanelMigrationContext $context):PanelMigrationBatch{$data=$context->data();$data['changed']=true;return PanelMigrationBatch::complete($data,1);});$fallbackRegistry=new PanelMigrationRegistry([$irreversible]);$fallbackStore->seed('settings',null,dp_panel_migration_version('0.0.0',0),['original'=>true]);$fallbackRunner=(new PanelMigrationRunner($fallbackStore,$fallbackRegistry))->allowTrustedExecution();$fallbackPlan=$fallbackRunner->plan('settings',null,dp_panel_migration_version('1.0.0',1),'2026-07-14T12:00:00Z');$fallbackRunner->execute($fallbackPlan);$blocked=$fallbackRunner->rollback($fallbackPlan,null,[],owner:'rollback',snapshotFallback:false);$t->same('failed',$blocked->status());$fallback=$fallbackRunner->rollback($fallbackPlan);$t->same('rolled_back',$fallback->status());$t->same('snapshot_restore',$fallback->jsonSerialize()['rollback_mode']);$t->same(['original'=>true],$fallbackStore->state('settings')->data());
})->tag('panel','migrations','rollback','backup')->maxMillis(7000);

test('migration store rejects stale plans and stale fences and recovers expired executions',static function(Context $t):void{
	[$store,$advance]=dp_panel_migration_store($t,'recovery');[$registry,$definition]=dp_panel_migration_registry();$store->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[['id'=>1]]]);$runner=(new PanelMigrationRunner($store,$registry))->allowTrustedExecution();$plan=$runner->plan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');
	$lease=$store->acquire('orders','tenant-a','worker-a',5);$t->isTrue($lease instanceof PanelMigrationLease);$leaseManifest=$lease->jsonSerialize();$t->same($lease->tokenFingerprint(),$leaseManifest['token_fingerprint']);$t->notContains($lease->token(),json_encode($leaseManifest,JSON_THROW_ON_ERROR));$t->same(null,$store->acquire('orders','tenant-a','worker-b',5));$t->throws(static fn()=>$store->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),[]),PanelMigrationConflict::class);$begun=$store->begin($lease,$plan,'actor');$t->same('running',$begun->status());$contended=$runner->execute($plan,null,['orders.write'],'worker-b');$t->same('blocked',$contended->status());$t->contains('Another worker owns the migration scope lease',json_encode($contended,JSON_THROW_ON_ERROR));$t->throws(static fn()=>$store->complete($lease,(string)$begun->runId(),$plan),PanelMigrationConflict::class);
	$advance(6);$recovered=$store->recoverExpired();$t->same(1,count($recovered));$t->same('paused',$recovered[0]->status());$t->throws(static fn()=>$store->renew($lease),PanelMigrationLeaseLost::class);$t->same([],$store->recoverExpired());
	$newLease=$store->acquire('orders','tenant-a','worker-b',5);$t->same(2,$newLease?->fence());$resumed=$store->begin($newLease,$plan,'actor');$t->same(1,$resumed->jsonSerialize()['resumes']);$store->release($newLease);
	[$staleStore]=dp_panel_migration_store($t,'stale');$staleStore->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[]]);$staleRunner=new PanelMigrationRunner($staleStore,$registry);$stalePlan=$staleRunner->plan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');$staleStore->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[['id'=>2]]]);$t->same('blocked',$staleRunner->preflight($stalePlan,null,['orders.write'])->status());$staleLease=$staleStore->acquire('orders','tenant-a','stale-worker',5);$t->throws(static fn()=>$staleStore->begin($staleLease,$stalePlan),PanelMigrationStalePlan::class);$t->same($stalePlan->digest(),(new PanelMigrationStalePlan($stalePlan->digest()))->planDigest());$t->same($staleLease?->scopeKey(),(new PanelMigrationLeaseLost((string)$staleLease?->scopeKey()))->scopeKey());
	$forged=PanelMigrationLease::make('orders','tenant-a','stale-worker',str_repeat('f',64),$staleLease->fence(),$staleLease->acquiredAt(),$staleLease->expiresAt());$t->throws(static fn()=>$staleStore->release($forged),PanelMigrationLeaseLost::class);$staleStore->release($staleLease);
	$invalidTokens=new PanelAtomicMigrationStore($t->tempDirectory('panel-migrations-invalid-token'),8,static fn():string=>'2026-07-14T12:00:00Z',static fn():string=>'short');$t->throws(static fn()=>$invalidTokens->acquire('x',null),UnexpectedValueException::class);$invalidClock=new PanelAtomicMigrationStore($t->tempDirectory('panel-migrations-invalid-clock'),8,static fn():string=>'not-a-time');$t->throws(static fn()=>$invalidClock->acquire('x',null),UnexpectedValueException::class);
	$t->throws(static fn()=>$runner->execute($plan,null,['orders.write'],maxBatches:0),InvalidArgumentException::class);
})->tag('panel','migrations','leases','recovery','stale-plan')->maxMillis(7000);

test('migration adapter conformance and optional platform domain expose the production lifecycle truthfully',static function(Context $t):void{
	[$store]=dp_panel_migration_store($t,'conformance');$report=(new PanelAdapterConformanceRunner())->run(PanelAdapterConformanceCatalog::migrationStore(),$store,['allow_destructive'=>true,'scope'=>'migration_conformance']);$t->isTrue($report->passed());$t->same(1,$report->summary()['passed']);$t->same(0,$report->summary()['failed']);
	[$registry,$first]=dp_panel_migration_registry();$disabled=['operations'=>false,'distributed_operations'=>false,'data'=>false,'workflows'=>false,'automation'=>false,'authentication'=>false,'notifications'=>false,'media'=>false,'localization'=>false,'preferences'=>false,'collaboration'=>false,'relations'=>false,'security'=>false,'development'=>false,'extensions'=>false,'platform'=>false];$platform=PanelPlatform::defaults(['state_root'=>$t->tempDirectory('panel-platform-migrations'),'migrations'=>['definitions'=>$registry->all(),'snapshot_retention'=>16,'authorize'=>static fn():bool=>true]]+$disabled);$t->isTrue($platform->manifest()->available('migrations'));$t->isTrue($platform->manifest()->configured('migrations'));$t->isTrue($platform->manifest()->ready('migrations'));$t->same($platform->migrationStore(),$platform->migrationRunner()->store());$t->same($platform->migrationRegistry(),$platform->migrationRunner()->registry());$t->isTrue(in_array('migrations',$platform->jsonSerialize()['metadata']['enabled_domains'],true));
	$platform->migrationStore()->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[]]);$plan=$platform->migrationPlan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');$t->same(['orders.normalize','orders.index'],$plan->migrationIds());$replacement=PanelMigrationDefinition::make('orders.normalize','orders',dp_panel_migration_version('1.0.0',1),dp_panel_migration_version('1.1.0',2),static fn(PanelMigrationContext $context):PanelMigrationBatch=>PanelMigrationBatch::complete($context->data()));$platform->registerMigration($replacement,true);$t->same($replacement,$platform->migrationRegistry()->get('orders.normalize'));
	$without=PanelPlatform::defaults(['state_root'=>$t->tempDirectory('panel-platform-without-migrations')]+$disabled);$t->isFalse($without->has('migrations.store'));$t->isFalse($without->manifest()->configured('migrations'));$denied=PanelPlatform::defaults(['state_root'=>$t->tempDirectory('panel-platform-denied-migrations'),'migrations'=>['definitions'=>$registry->all()]]+$disabled);$denied->migrationStore()->seed('orders','tenant-a',dp_panel_migration_version('1.0.0',1),['items'=>[]]);$deniedPlan=$denied->migrationPlan('orders','tenant-a',dp_panel_migration_version('2.0.0',3),'2026-07-14T12:00:00Z');$t->same('blocked',$denied->migrationRunner()->preflight($deniedPlan,'system',['orders.write'])->status());$t->isFalse($denied->migrationRunner()->manifest()['authorization']['configured']);$t->throws(static fn()=>PanelPlatform::defaults(['state_root'=>$t->tempDirectory('panel-platform-invalid-migrations'),'migrations'=>['definitions'=>['bad']]]+$disabled),InvalidArgumentException::class);
})->tag('panel','migrations','platform','conformance')->maxMillis(10000);
