<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Governed release rings, health gates, rollback, and deterministic feature flags. */
final class PanelReleaseControlPlane implements \JsonSerializable {
	private readonly PanelAtomicSnapshotStore $store;private readonly \Closure $clock;/** @var array<string,string> */private array $keys;
	/** @param array<string,string> $trustedKeys */public function __construct(string $root,array $trustedKeys,private readonly PanelPolicyControlPlane $policy,?callable $clock=null,int $retention=2048){if($trustedKeys===[]){throw new \InvalidArgumentException('Release control plane requires trust keys.');}foreach($trustedKeys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'release key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Release trust keys require at least 32 bytes.');}$this->keys[$id]=$key;}$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');$initial=['schema'=>'panel_release_control_plane','version'=>1,'sequence'=>0,'artifacts'=>[],'rings'=>[],'deployments'=>[],'flags'=>[],'receipts'=>[]];$this->store=new PanelAtomicSnapshotStore($root,'panel.release-control.v1',$initial,max(8,$retention));$this->assertState($this->store->payload());}
	public function register(PanelReleaseArtifact $artifact,PanelPolicyRequest|array $request):self {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.artifact.register');if(!$artifact->verify($this->keys)){throw new \LogicException('Release artifact signature is not trusted.');}$this->store->transaction(function(array &$state)use($artifact):void{if(isset($state['artifacts'][$artifact->id()])){throw new \LogicException('Release artifact id is already registered.');}$state['artifacts'][$artifact->id()]=$artifact->jsonSerialize();},'release.artifact.registered',['artifact_id'=>$artifact->id()]);return$this;}
	/** @param list<array<string,mixed>> $healthGates */public function ring(string $name,int $order,int $trafficBasisPoints,array $healthGates,PanelPolicyRequest|array $request):self {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.ring.configure');$name=PanelOperationsGuard::name($name,'release ring');if($order<0||$order>1000||$trafficBasisPoints<0||$trafficBasisPoints>10000){throw new \InvalidArgumentException('Release ring order or traffic allocation is invalid.');}$gates=[];foreach($healthGates as$gate){if(!is_array($gate)){throw new \InvalidArgumentException('Release health gates must be maps.');}$operator=(string)($gate['operator']??'gte');if(!in_array($operator,['gt','gte','lt','lte','eq'],true)||!is_int($gate['threshold']??null)&&!is_float($gate['threshold']??null)){throw new \InvalidArgumentException('Release health gate is invalid.');}$gates[]=['metric'=>PanelOperationsGuard::name((string)($gate['metric']??''),'release health metric'),'operator'=>$operator,'threshold'=>PanelOperationsGuard::finite($gate['threshold'],'release health threshold')];}$this->store->transaction(function(array &$state)use($name,$order,$trafficBasisPoints,$gates):void{$state['rings'][$name]=['name'=>$name,'order'=>$order,'traffic_basis_points'=>$trafficBasisPoints,'health_gates'=>$gates,'paused'=>false];uasort($state['rings'],static fn(array $a,array $b):int=>[$a['order'],$a['name']]<=>[$b['order'],$b['name']]);},'release.ring.configured',['ring'=>$name]);return$this;}
	/** @param array<string,int|float> $health */public function deploy(string $artifactId,string $ring,array $health,PanelPolicyRequest|array $request,string $idempotencyKey):array {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.deploy');$artifactId=PanelOperationsGuard::name($artifactId,'release artifact id');$ring=PanelOperationsGuard::name($ring,'release ring');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(['artifact'=>$artifactId,'ring'=>$ring,'health'=>$health,'request'=>$request->fingerprint()]);return$this->store->transaction(function(array &$state)use($artifactId,$ring,$health,$key,$fingerprint,$request):array{$existing=$state['receipts'][$key]??null;if(is_array($existing)){if(!hash_equals($existing['fingerprint'],$fingerprint)){throw new \LogicException('Release idempotency key conflict.');}return array_replace($existing['deployment'],['replayed'=>true]);}if(!isset($state['artifacts'][$artifactId],$state['rings'][$ring])){throw new \OutOfBoundsException('Release artifact or ring is not registered.');}$definition=$state['rings'][$ring];if($definition['paused']){throw new \LogicException('Release ring is paused.');}$gates=$this->gates($definition['health_gates'],$health);$state['sequence']++;$deployment=['id'=>'deploy_'.substr(hash('sha256',$artifactId.'|'.$ring.'|'.$state['sequence']),0,40),'sequence'=>$state['sequence'],'artifact_id'=>$artifactId,'ring'=>$ring,'status'=>$gates['passed']?'active':'blocked','health'=>$gates,'actor_hash'=>hash('sha256',$request->actorId()),'occurred_at'=>$this->now(),'replayed'=>false];$state['deployments'][]=$deployment;$state['receipts'][$key]=['fingerprint'=>$fingerprint,'deployment'=>$deployment];return$deployment;},'release.deployed',['artifact_id'=>$artifactId,'ring'=>$ring])['result'];}

	/**
	 * Schedules a deployment for an execution engine without claiming that the
	 * artifact is active before a host adapter has actually activated it.
	 *
	 * @param array<string,int|float> $health
	 * @return array<string,mixed>
	 */
	public function schedule(string $artifactId,string $ring,array $health,PanelPolicyRequest|array $request,string $idempotencyKey):array {
		$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.execute.schedule');
		$artifactId=PanelOperationsGuard::name($artifactId,'release artifact id');$ring=PanelOperationsGuard::name($ring,'release ring');$key=$this->idempotency($idempotencyKey);
		$health=$this->health($health);$fingerprint=PanelOperationsGuard::digest(['operation'=>'schedule','artifact'=>$artifactId,'ring'=>$ring,'health'=>$health,'request'=>$request->fingerprint()]);
		return$this->store->transaction(function(array &$state)use($artifactId,$ring,$health,$key,$fingerprint,$request):array{
			$existing=$state['receipts'][$key]??null;if(is_array($existing)){if(!hash_equals((string)($existing['fingerprint']??''),$fingerprint)){throw new \LogicException('Release idempotency key conflict.');}return array_replace($existing['deployment'],['replayed'=>true]);}
			if(!isset($state['artifacts'][$artifactId],$state['rings'][$ring])){throw new \OutOfBoundsException('Release artifact or ring is not registered.');}$definition=$state['rings'][$ring];if(($definition['paused']??false)===true){throw new \LogicException('Release ring is paused.');}
			$gates=$this->gates($definition['health_gates'],$health);$state['sequence']++;$now=$this->now();$status=$gates['passed']?'approved':'blocked';
			$deployment=['id'=>'deploy_'.substr(hash('sha256','scheduled|'.$artifactId.'|'.$ring.'|'.$state['sequence']),0,40),'sequence'=>$state['sequence'],'last_sequence'=>$state['sequence'],'artifact_id'=>$artifactId,'ring'=>$ring,'status'=>$status,'health'=>$gates,'actor_hash'=>hash('sha256',$request->actorId()),'occurred_at'=>$now,'updated_at'=>$now,'execution_managed'=>true,'history'=>[['sequence'=>$state['sequence'],'from'=>null,'to'=>$status,'occurred_at'=>$now,'evidence_digest'=>PanelOperationsGuard::digest(['health'=>$gates])]],'replayed'=>false];
			$state['deployments'][]=$deployment;$state['receipts'][$key]=['fingerprint'=>$fingerprint,'deployment'=>$deployment];return$deployment;
		},'release.execution.scheduled',['artifact_id'=>$artifactId,'ring'=>$ring])['result'];
	}

	/**
	 * Commits one fenced execution lifecycle transition. Adapter payloads are
	 * represented only by a digest and optional bounded code/summary.
	 *
	 * @param array<string,mixed> $evidence
	 * @return array<string,mixed>
	 */
	public function transition(string $deploymentId,string $status,array $evidence,PanelPolicyRequest|array $request,string $idempotencyKey,?string $expectedStatus=null):array {
		$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.execution.transition');
		$deploymentId=PanelOperationsGuard::identifier($deploymentId,'release deployment id',190);$status=strtolower(trim($status));$valid=['approved','blocked','executing','active','failed','rolling_back','rolled_back','rollback_failed'];if(!in_array($status,$valid,true)){throw new \InvalidArgumentException('Release execution status is invalid.');}
		if($expectedStatus!==null){$expectedStatus=strtolower(trim($expectedStatus));if(!in_array($expectedStatus,$valid,true)){throw new \InvalidArgumentException('Expected release execution status is invalid.');}}
		$key=$this->idempotency($idempotencyKey);$projection=$this->transitionEvidence($evidence);$fingerprint=PanelOperationsGuard::digest(['operation'=>'transition','deployment_id'=>$deploymentId,'status'=>$status,'expected_status'=>$expectedStatus,'evidence'=>$projection]);
		return$this->store->transaction(function(array &$state)use($deploymentId,$status,$expectedStatus,$key,$fingerprint,$projection):array{
			$existing=$state['receipts'][$key]??null;if(is_array($existing)){if(!hash_equals((string)($existing['fingerprint']??''),$fingerprint)){throw new \LogicException('Release idempotency key conflict.');}return array_replace($existing['deployment'],['replayed'=>true]);}
			$index=$this->deploymentIndex($state,$deploymentId);$deployment=$state['deployments'][$index];if(($deployment['execution_managed']??false)!==true){throw new \LogicException('Legacy release deployments cannot be execution transitioned.');}$current=(string)$deployment['status'];if($expectedStatus!==null&&!hash_equals($expectedStatus,$current)){throw new \LogicException('Release execution status changed before transition.');}
			$allowed=['approved'=>['executing'],'executing'=>['active','failed','rolling_back'],'failed'=>['rolling_back'],'active'=>['rolling_back'],'rolling_back'=>['rolled_back','rollback_failed'],'blocked'=>[],'rolled_back'=>[],'rollback_failed'=>[]];
			if($current!==$status&&!in_array($status,$allowed[$current]??[],true)){throw new \LogicException('Release execution transition is invalid.');}
			if($current!==$status){$state['sequence']++;$now=$this->now();$deployment['status']=$status;$deployment['last_sequence']=$state['sequence'];$deployment['updated_at']=$now;$deployment['history'][]=['sequence'=>$state['sequence'],'from'=>$current,'to'=>$status,'occurred_at'=>$now]+$projection;$state['deployments'][$index]=$deployment;}
			$state['receipts'][$key]=['fingerprint'=>$fingerprint,'deployment'=>$deployment];return$deployment;
		},'release.execution.transitioned',['deployment_id'=>$deploymentId,'status'=>$status])['result'];
	}

	public function artifact(string $artifactId):PanelReleaseArtifact {$artifactId=PanelOperationsGuard::name($artifactId,'release artifact id');$payload=$this->store->payload()['artifacts'][$artifactId]??null;if(!is_array($payload)){throw new \OutOfBoundsException('Release artifact is not registered.');}return PanelReleaseArtifact::hydrate($payload);}
	public function policy():PanelPolicyControlPlane{return$this->policy;}
	/** @return array<string,mixed> */public function deployment(string $deploymentId):array {$state=$this->store->payload();return$state['deployments'][$this->deploymentIndex($state,PanelOperationsGuard::identifier($deploymentId,'release deployment id',190))];}
	/** @return list<array<string,mixed>> */public function deployments(int $limit=100):array {$limit=max(1,min(1000,$limit));$items=$this->store->payload()['deployments'];return array_values(array_slice($items,-$limit));}
	/** @param array<string,int|float> $health */public function promote(string $artifactId,string $fromRing,array $health,PanelPolicyRequest|array $request,string $idempotencyKey):array {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.promote');$artifactId=PanelOperationsGuard::name($artifactId,'release artifact id');$fromRing=PanelOperationsGuard::name($fromRing,'release ring');$state=$this->store->payload();$this->assertState($state);$rings=array_values($state['rings']);$fromIndex=null;foreach($rings as$index=>$ring){if($ring['name']===$fromRing){$fromIndex=$index;break;}}if($fromIndex===null||!isset($rings[$fromIndex+1])){throw new \OutOfBoundsException('Release has no next promotion ring.');}$active=array_values(array_filter($state['deployments'],static fn(array $deployment):bool=>$deployment['artifact_id']===$artifactId&&$deployment['ring']===$fromRing&&$deployment['status']==='active'));if($active===[]){throw new \LogicException('Release is not active in the source ring.');}return$this->deploy($artifactId,$rings[$fromIndex+1]['name'],$health,$request,$idempotencyKey);}
	public function rollback(string $ring,PanelPolicyRequest|array $request,string $idempotencyKey):array {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.rollback');$ring=PanelOperationsGuard::name($ring,'release ring');$key=$this->idempotency($idempotencyKey);$fingerprint=PanelOperationsGuard::digest(['operation'=>'rollback','ring'=>$ring,'request'=>$request->fingerprint()]);return$this->store->transaction(function(array &$state)use($ring,$request,$key,$fingerprint):array{$existing=$state['receipts'][$key]??null;if(is_array($existing)){if(!hash_equals((string)($existing['fingerprint']??''),$fingerprint)){throw new \LogicException('Release idempotency key conflict.');}return array_replace($existing['deployment'],['replayed'=>true]);}$active=array_values(array_filter($state['deployments'],static fn(array $deployment):bool=>$deployment['ring']===$ring&&$deployment['status']==='active'));if(count($active)<2){throw new \LogicException('Release ring has no prior active deployment to restore.');}$current=array_pop($active);$previous=array_pop($active);$state['sequence']++;$deployment=['id'=>'rollback_'.substr(hash('sha256',$ring.'|'.$state['sequence']),0,40),'sequence'=>$state['sequence'],'artifact_id'=>$previous['artifact_id'],'ring'=>$ring,'status'=>'active','health'=>['passed'=>true,'gates'=>[]],'actor_hash'=>hash('sha256',$request->actorId()),'occurred_at'=>$this->now(),'rollback_of'=>$current['id'],'replayed'=>false];$state['deployments'][]=$deployment;$state['receipts'][$key]=['fingerprint'=>$fingerprint,'deployment'=>$deployment];return$deployment;},'release.rolled_back',['ring'=>$ring])['result'];}
	public function pause(string $ring,bool $paused,PanelPolicyRequest|array $request):self {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.ring.pause');$ring=PanelOperationsGuard::name($ring,'release ring');$this->store->transaction(function(array &$state)use($ring,$paused):void{if(!isset($state['rings'][$ring])){throw new \OutOfBoundsException('Release ring is not registered.');}$state['rings'][$ring]['paused']=$paused;},'release.ring.pause',['ring'=>$ring,'paused'=>$paused]);return$this;}
	/** @param array<string,int> $variants @param array<string,mixed> $targeting */public function flag(string $name,array $variants,array $targeting,PanelPolicyRequest|array $request):self {$request=$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);$this->authorize($request,'release.flag.configure');$name=PanelOperationsGuard::name($name,'feature flag');$weights=[];$sum=0;foreach($variants as$variant=>$weight){$variant=PanelOperationsGuard::name((string)$variant,'feature variant');$weight=(int)$weight;if($weight<0||$weight>10000){throw new \InvalidArgumentException('Feature variant weight is invalid.');}$weights[$variant]=$weight;$sum+=$weight;}if($weights===[]||$sum!==10000){throw new \InvalidArgumentException('Feature flag weights must total 10000 basis points.');}$definition=['name'=>$name,'variants'=>$weights,'targeting'=>PanelOperationsGuard::safeMetadata($targeting,256),'revision'=>1];$this->store->transaction(function(array &$state)use($name,$definition):void{$definition['revision']=(int)($state['flags'][$name]['revision']??0)+1;$state['flags'][$name]=$definition;},'release.flag.configured',['flag'=>$name]);return$this;}
	/** @param array<string,mixed> $context */public function evaluateFlag(string $name,string|int $subjectId,array $context=[]):string {$name=PanelOperationsGuard::name($name,'feature flag');$subjectId=PanelOperationsGuard::identifier($subjectId,'feature subject id');$flag=$this->store->payload()['flags'][$name]??null;if(!is_array($flag)){throw new \OutOfBoundsException('Feature flag is not registered.');}foreach($flag['targeting']as$key=>$expected){if(PanelOperationsGuard::valueAt($context,(string)$key)!==$expected){return array_key_first($flag['variants']);}}$bucket=hexdec(substr(hash('sha256',$name.'|'.$subjectId.'|'.$flag['revision']),0,8))%10000;$cursor=0;foreach($flag['variants']as$variant=>$weight){$cursor+=$weight;if($bucket<$cursor){return$variant;}}return array_key_last($flag['variants']);}
	public function jsonSerialize():array{$state=$this->store->payload();$statuses=[];$recent=[];foreach($state['deployments']as$deployment){if(!is_array($deployment)){continue;}$status=(string)($deployment['status']??'unknown');$statuses[$status]=($statuses[$status]??0)+1;$recent[]=$this->deploymentProjection($deployment);}ksort($statuses,SORT_STRING);$recent=array_slice($recent,-25);$artifacts=[];foreach($state['artifacts']as$id=>$payload){if(!is_array($payload)){continue;}$artifacts[]=['id'=>(string)$id,'version'=>(string)($payload['version']??''),'digest'=>(string)($payload['digest']??''),'created_at'=>(string)($payload['created_at']??''),'key_id'=>(string)($payload['key_id']??''),'bound_digest_count'=>count((array)($payload['digests']??[])),'sbom_component_count'=>count((array)($payload['sbom']??[]))];}return PanelManifestContract::stamp(['type'=>'panel_release_control_plane_manifest','version'=>1,'sequence'=>$state['sequence'],'artifact_count'=>count($state['artifacts']),'artifacts'=>$artifacts,'rings'=>$state['rings'],'deployment_count'=>count($state['deployments']),'deployment_statuses'=>$statuses,'recent_deployments'=>$recent,'flags'=>$state['flags'],'trusted_key_ids'=>array_keys($this->keys),'policy_revision'=>$this->policy->revision(),'capabilities'=>['signed_artifacts'=>true,'sbom'=>true,'provenance'=>true,'release_rings'=>true,'health_gates'=>true,'promotion'=>true,'rollback'=>true,'pause'=>true,'feature_flags'=>true,'deterministic_targeting'=>true,'idempotency'=>true,'atomic_persistence'=>true,'execution_scheduling'=>true,'explicit_activation_commit'=>true,'append_only_transition_history'=>true,'evidence_redaction'=>true]]);}
	private function authorize(PanelPolicyRequest $request,string $ability):void {$attributes=$request->jsonSerialize();$attributes['ability']=$ability;$decision=$this->policy->evaluate(PanelPolicyRequest::from($attributes));$decision->assertAllowed();}
	/** @param list<array<string,mixed>> $definitions @param array<string,int|float> $health @return array<string,mixed> */private function gates(array $definitions,array $health):array {$health=$this->health($health);$results=[];$passed=true;foreach($definitions as$gate){$actual=$health[$gate['metric']]??null;$ok=(is_int($actual)||is_float($actual))&&match($gate['operator']){'gt'=>$actual>$gate['threshold'],'gte'=>$actual>=$gate['threshold'],'lt'=>$actual<$gate['threshold'],'lte'=>$actual<=$gate['threshold'],'eq'=>$actual===$gate['threshold'],default=>false};$results[]=$gate+['actual'=>$actual,'passed'=>$ok];$passed=$passed&&$ok;}return['passed'=>$passed,'gates'=>$results];}
	/** @param array<string,int|float> $health @return array<string,int|float> */private function health(array $health):array {$normalized=[];foreach($health as$name=>$value){$name=PanelOperationsGuard::name((string)$name,'release health metric');if(!is_int($value)&&!is_float($value)){throw new \InvalidArgumentException('Release health measurements must be numeric.');}$normalized[$name]=PanelOperationsGuard::finite($value,'release health measurement');}ksort($normalized,SORT_STRING);return$normalized;}
	/** @param array<string,mixed> $evidence @return array<string,mixed> */private function transitionEvidence(array $evidence):array {$evidence=PanelOperationsGuard::safeMetadata($evidence,128);$projection=['evidence_digest'=>PanelOperationsGuard::digest($evidence),'evidence_redacted'=>true];foreach(['code','summary']as$key){if(isset($evidence[$key])&&is_scalar($evidence[$key])){$value=trim((string)$evidence[$key]);if($value!==''){$projection[$key]=PanelOperationsGuard::label($value,'release transition '.$key,$key==='code'?128:512);}}}return$projection;}
	/** @param array<string,mixed> $state */private function deploymentIndex(array $state,string $deploymentId):int {foreach($state['deployments']??[]as$index=>$deployment){if(is_array($deployment)&&($deployment['id']??null)===$deploymentId){return(int)$index;}}throw new \OutOfBoundsException('Release deployment is not registered.');}
	/** @param array<string,mixed> $deployment @return array<string,mixed> */private function deploymentProjection(array $deployment):array {return['id'=>(string)($deployment['id']??''),'sequence'=>(int)($deployment['sequence']??0),'last_sequence'=>(int)($deployment['last_sequence']??$deployment['sequence']??0),'artifact_id'=>(string)($deployment['artifact_id']??''),'ring'=>(string)($deployment['ring']??''),'status'=>(string)($deployment['status']??'unknown'),'health_passed'=>(bool)($deployment['health']['passed']??false),'execution_managed'=>(bool)($deployment['execution_managed']??false),'transition_count'=>count((array)($deployment['history']??[])),'occurred_at'=>(string)($deployment['occurred_at']??''),'updated_at'=>(string)($deployment['updated_at']??$deployment['occurred_at']??''),'rollback_of'=>isset($deployment['rollback_of'])?(string)$deployment['rollback_of']:null];}
	/** @param array<string,mixed> $state */private function assertState(array $state):void {if(($state['schema']??null)!=='panel_release_control_plane'||($state['version']??null)!==1||!is_int($state['sequence']??null)||$state['sequence']<0||!is_array($state['artifacts']??null)||!is_array($state['rings']??null)||!is_array($state['deployments']??null)||!is_array($state['flags']??null)||!is_array($state['receipts']??null)){throw new \UnexpectedValueException('Release control-plane state is invalid.');}foreach($state['artifacts']as$id=>$payload){if(!is_string($id)||!is_array($payload)){throw new \UnexpectedValueException('Stored release artifact entry is invalid.');}$artifact=PanelReleaseArtifact::hydrate($payload);if($artifact->id()!==$id||!$artifact->verify($this->keys)){throw new \UnexpectedValueException('Stored release artifact is untrusted.');}}foreach($state['deployments']as$deployment){if(!is_array($deployment)||!is_string($deployment['id']??null)||!is_int($deployment['sequence']??null)||$deployment['sequence']<1||$deployment['sequence']>$state['sequence']||!is_string($deployment['artifact_id']??null)||!isset($state['artifacts'][$deployment['artifact_id']])||!is_string($deployment['ring']??null)||!isset($state['rings'][$deployment['ring']])||!is_string($deployment['status']??null)||!is_array($deployment['health']??null)||!is_string($deployment['actor_hash']??null)||preg_match('/^[a-f0-9]{64}$/D',$deployment['actor_hash'])!==1||!is_string($deployment['occurred_at']??null)){throw new \UnexpectedValueException('Stored release deployment is invalid.');}if(($deployment['execution_managed']??false)===true&&(!is_int($deployment['last_sequence']??null)||!is_string($deployment['updated_at']??null)||!is_array($deployment['history']??null))){throw new \UnexpectedValueException('Stored managed release deployment is invalid.');}}}
	private function idempotency(string $key):string {$key=trim($key);if($key===''||strlen($key)>256){throw new \InvalidArgumentException('Release idempotency key is invalid.');}return hash('sha256',$key);}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Release clock must return an instant.');}return PanelOperationsGuard::instant($value);}
}
