<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Signed release unit binding code, domain, policy, dependencies, SBOM, and provenance. */
final class PanelReleaseArtifact implements \JsonSerializable {
	private readonly string $digest;
	/** @param array<string,string> $digests @param list<array<string,mixed>> $sbom @param array<string,mixed> $provenance */private function __construct(private readonly string $id,private readonly string $version,private readonly array $digests,private readonly array $sbom,private readonly array $provenance,private readonly string $createdAt,private readonly string $keyId,private readonly string $signature){PanelOperationsGuard::name($id,'release artifact id');if($version===''||strlen($version)>64||preg_match('/^[0-9A-Za-z][0-9A-Za-z.+_-]*$/D',$version)!==1){throw new \InvalidArgumentException('Release artifact version is invalid.');}if($digests===[]){throw new \InvalidArgumentException('Release artifacts require at least one bound digest.');}foreach($digests as$name=>$digest){PanelOperationsGuard::name((string)$name,'release digest name');if(!is_string($digest)||preg_match('/^[a-f0-9]{64}$/D',$digest)!==1){throw new \InvalidArgumentException('Release artifact digest is invalid.');}}if(count($sbom)>10000){throw new \LengthException('Release SBOM exceeds its component limit.');}foreach($sbom as$component){if(!is_array($component)){throw new \InvalidArgumentException('Release SBOM components must be maps.');}PanelOperationsGuard::label((string)($component['name']??''),'SBOM component name',512);PanelOperationsGuard::label((string)($component['version']??'unknown'),'SBOM component version',256);}PanelOperationsGuard::safeMetadata($provenance,512);if(PanelOperationsGuard::instant($createdAt)!==$createdAt){throw new \InvalidArgumentException('Release creation instant must be canonical UTC.');}PanelOperationsGuard::name($keyId,'release key id');if(preg_match('/^[a-f0-9]{64}$/D',$signature)!==1){throw new \InvalidArgumentException('Release signature is invalid.');}$this->digest=PanelOperationsGuard::digest($this->unsigned());}
	/** @param array<string,string> $digests @param list<array<string,mixed>> $sbom @param array<string,mixed> $provenance */public static function sign(string $id,string $version,array $digests,array $sbom,array $provenance,string|int|\DateTimeInterface $createdAt,string $keyId,string $key):self {if(strlen($key)<32){throw new \InvalidArgumentException('Release signing keys require at least 32 bytes.');}$createdAt=PanelOperationsGuard::instant($createdAt);$keyId=PanelOperationsGuard::name($keyId,'release key id');$prototype=['id'=>PanelOperationsGuard::name($id,'release artifact id'),'version'=>$version,'digests'=>PanelOperationsGuard::canonical($digests),'sbom'=>PanelOperationsGuard::canonical($sbom),'provenance'=>PanelOperationsGuard::safeMetadata($provenance,512),'created_at'=>$createdAt,'key_id'=>$keyId];$digest=PanelOperationsGuard::digest($prototype);return new self($prototype['id'],$version,$prototype['digests'],$prototype['sbom'],$prototype['provenance'],$createdAt,$keyId,hash_hmac('sha256',$digest,$key));}
	public function id():string{return$this->id;}public function version():string{return$this->version;}public function digest():string{return$this->digest;}public function keyId():string{return$this->keyId;}/** @return array<string,string> */public function digests():array{return$this->digests;}
	/** @param array<string,string> $keys */public function verify(array $keys):bool {$key=$keys[$this->keyId]??null;return is_string($key)&&strlen($key)>=32&&hash_equals($this->signature,hash_hmac('sha256',$this->digest,$key));}
	/** @param array<string,mixed> $payload */public static function hydrate(array $payload):self {$expected=['type','schema_version','api_version','id','version','digests','sbom','provenance','created_at','key_id','digest','signature'];$keys=array_keys($payload);sort($keys,SORT_STRING);sort($expected,SORT_STRING);if($keys!==$expected||$payload['type']!=='panel_release_artifact'||!is_string($payload['id'])||!is_string($payload['version'])||!is_array($payload['digests'])||!is_array($payload['sbom'])||!is_array($payload['provenance'])||!is_string($payload['created_at'])||!is_string($payload['key_id'])||!is_string($payload['digest'])||!is_string($payload['signature'])){throw new \UnexpectedValueException('Stored release artifact shape is invalid.');}$artifact=new self($payload['id'],$payload['version'],$payload['digests'],$payload['sbom'],$payload['provenance'],$payload['created_at'],$payload['key_id'],$payload['signature']);if(!hash_equals($artifact->digest(),$payload['digest'])){throw new \UnexpectedValueException('Stored release artifact digest is invalid.');}return$artifact;}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_release_artifact']+$this->unsigned()+['digest'=>$this->digest,'signature'=>$this->signature]);}
	/** @return array<string,mixed> */private function unsigned():array{return['id'=>$this->id,'version'=>$this->version,'digests'=>$this->digests,'sbom'=>$this->sbom,'provenance'=>$this->provenance,'created_at'=>$this->createdAt,'key_id'=>$this->keyId];}
}
