<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Immutable security, provenance, compatibility, and permission review artifact. */
final class PanelMarketplaceReview implements \JsonSerializable {
	/** @param list<array<string,mixed>> $findings @param list<string> $permissions @param array<string,mixed> $sandbox */public function __construct(private readonly string $packageId,private readonly string $packageVersion,private readonly string $packageDigest,private readonly string $status,private readonly int $riskScore,private readonly array $findings,private readonly array $permissions,private readonly array $sandbox,private readonly string $reviewedAt,private readonly int $requiredApprovals,private readonly array $approvers=[]){PanelOperationsGuard::name($packageId,'marketplace package id');if($packageVersion===''||strlen($packageVersion)>64){throw new \InvalidArgumentException('Marketplace package version is invalid.');}if(preg_match('/^[a-f0-9]{64}$/D',$packageDigest)!==1||!in_array($status,['candidate','quarantined','rejected','approved'],true)||$riskScore<0||$riskScore>100||$requiredApprovals<0||$requiredApprovals>16){throw new \InvalidArgumentException('Marketplace review digest, status, risk, or approvals are invalid.');}foreach($findings as$finding){if(!is_array($finding)||!isset($finding['code'],$finding['severity'],$finding['message'])){throw new \InvalidArgumentException('Marketplace findings are invalid.');}}PanelOperationsGuard::abilityPatterns($permissions,'marketplace permission',2048);PanelOperationsGuard::safeMetadata($sandbox,256);if(PanelOperationsGuard::instant($reviewedAt)!==$reviewedAt){throw new \InvalidArgumentException('Marketplace review instant must be canonical UTC.');}foreach($approvers as$approver){PanelOperationsGuard::identifier((string)$approver,'marketplace approver id');}}
	public function packageId():string{return$this->packageId;}public function packageVersion():string{return$this->packageVersion;}public function packageDigest():string{return$this->packageDigest;}public function status():string{return$this->status;}public function riskScore():int{return$this->riskScore;}public function requiredApprovals():int{return$this->requiredApprovals;}/** @return list<string> */public function permissions():array{return$this->permissions;}/** @return list<array<string,mixed>> */public function findings():array{return$this->findings;}/** @return array<string,mixed> */public function sandbox():array{return$this->sandbox;}/** @return list<string> */public function approvers():array{return$this->approvers;}
	/** @param list<string> $approvers */public function approve(array $approvers):self {$approvers=PanelOperationsGuard::identifiers($approvers,'marketplace approver id');if($this->status!=='candidate'||count($approvers)<$this->requiredApprovals){throw new \LogicException('Marketplace review is not eligible for approval.');}return new self($this->packageId,$this->packageVersion,$this->packageDigest,'approved',$this->riskScore,$this->findings,$this->permissions,$this->sandbox,$this->reviewedAt,$this->requiredApprovals,$approvers);}
	public function fingerprint():string{return PanelOperationsGuard::digest($this->values());}public function jsonSerialize():array{return PanelManifestContract::stamp($this->values()+['fingerprint'=>$this->fingerprint()]);}
	/** @return array<string,mixed> */private function values():array{return['type'=>'panel_marketplace_review_manifest','version'=>1,'package_id'=>$this->packageId,'package_version'=>$this->packageVersion,'package_digest'=>$this->packageDigest,'status'=>$this->status,'risk_score'=>$this->riskScore,'findings'=>$this->findings,'permissions'=>$this->permissions,'sandbox'=>$this->sandbox,'reviewed_at'=>$this->reviewedAt,'required_approvals'=>$this->requiredApprovals,'approvers'=>$this->approvers];}
}
