#!/usr/bin/env node
'use strict';

const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');

const cwd=process.cwd();
const MAX_JSON_BYTES=16*1024*1024;

function parseArgs(argv){
	const parsed={allowNoSandbox:false,allowOrigins:[],baseUrl:'',browser:'',capabilities:'',contracts:[],headed:false,help:false,list:false,manifest:'',php:process.env.PHP_BINARY||'php',profiles:[],report:'',reportOnly:false};
	for(let index=0;index<argv.length;index++){
		const argument=String(argv[index]);
		const value=()=>{const equals=argument.indexOf('=');if(equals!==-1){return argument.slice(equals+1);}index++;return String(argv[index]||'');};
		if(argument==='--help'||argument==='-h'){parsed.help=true;}
		else if(argument==='--headed'){parsed.headed=true;}
		else if(argument==='--list'){parsed.list=true;}
		else if(argument==='--report-only'){parsed.reportOnly=true;}
		else if(argument==='--allow-no-sandbox'){parsed.allowNoSandbox=true;}
		else if(argument==='--base-url'||argument.startsWith('--base-url=')){parsed.baseUrl=value();}
		else if(argument==='--browser'||argument.startsWith('--browser=')){parsed.browser=value();}
		else if(argument==='--manifest'||argument.startsWith('--manifest=')){parsed.manifest=value();}
		else if(argument==='--report'||argument.startsWith('--report=')){parsed.report=value();}
		else if(argument==='--capabilities'||argument.startsWith('--capabilities=')){parsed.capabilities=value();}
		else if(argument==='--php'||argument.startsWith('--php=')){parsed.php=value();}
		else if(argument==='--allow-origin'||argument.startsWith('--allow-origin=')){parsed.allowOrigins.push(...split(value()));}
		else if(argument==='--contract'||argument.startsWith('--contract=')){parsed.contracts.push(...split(value()));}
		else if(argument==='--profile'||argument.startsWith('--profile=')){parsed.profiles.push(...split(value()));}
		else {throw new Error('Unknown argument: '+argument);}
	}
	parsed.contracts=Array.from(new Set(parsed.contracts));
	parsed.profiles=Array.from(new Set(parsed.profiles));
	parsed.allowOrigins=Array.from(new Set(parsed.allowOrigins));
	return parsed;
}

function split(value){return String(value).split(',').map(item=>item.trim()).filter(Boolean);}
function absolute(value){return path.resolve(cwd,String(value));}
function ensureDirectory(directory){fs.mkdirSync(directory,{recursive:true});}
function readJson(file){const size=fs.statSync(file).size;assert(size<=MAX_JSON_BYTES,'Inclusive quality JSON exceeds its '+MAX_JSON_BYTES+' byte budget.');return JSON.parse(fs.readFileSync(file,'utf8'));}
function writeJsonAtomic(file,payload){ensureDirectory(path.dirname(file));const temporary=file+'.tmp-'+process.pid+'-'+Date.now();fs.writeFileSync(temporary,JSON.stringify(payload,null,2)+'\n');try{fs.renameSync(temporary,file);}catch(error){if(fs.existsSync(file)){fs.unlinkSync(file);}fs.renameSync(temporary,file);}}
function assert(condition,message){if(!condition){throw new Error(message);}}

function printHelp(){
	console.log([
		'Dataphyre Panel inclusive-quality browser runner',
		'',
		'Usage: node panel_inclusive_quality_regression.js --manifest matrix.json --base-url http://127.0.0.1:8098 --report report.json',
		'',
		'  --manifest <path>      PanelInclusiveQualityMatrix JSON generated by the PHP developer CLI.',
		'  --base-url <url>       Origin used to resolve root-relative manifest targets.',
		'  --browser <path>       Chrome or Edge executable.',
		'  --report <path>        Artifact-backed browser evidence report.',
		'  --capabilities <path>  Optional standalone capability report output.',
		'  --php <path>          PHP executable used to authenticate the matrix digest.',
		'  --allow-origin <csv>  Explicit additional HTTP(S) target/redirect origins.',
		'  --allow-no-sandbox    Explicitly disable Chromium sandboxing and report it.',
		'  --contract <csv>       Select contract ids.',
		'  --profile <csv>        Select locale profile ids.',
		'  --list                 Print selected browser case ids without launching a browser.',
		'  --headed               Show the controlled browser.',
		'  --report-only           Preserve a zero exit code when assertions fail.',
	].join('\n'));
}

function validId(value,maximum=127){return typeof value==='string'&&value.length>0&&value.length<=maximum&&/^[a-z][a-z0-9_.-]*$/.test(value);}

function secureTarget(value){
	assert(typeof value==='string'&&value.length>0&&value.length<=2048,'Browser target must be bounded text.');
	assert(!/[\u0000-\u0020\u007f\\]/.test(value)&&!value.startsWith('#')&&!value.startsWith('//'),'Browser target contains an ambiguous or unsafe URL form.');
	if(value.startsWith('/')){return value;}
	let parsed;try{parsed=new URL(value);}catch(error){throw new Error('Browser target must be root-relative or absolute HTTP(S).');}
	assert(['http:','https:'].includes(parsed.protocol)&&!parsed.username&&!parsed.password,'Browser target must use credential-free HTTP(S).');
	return parsed.toString();
}

function validateManifest(manifest){
	assert(manifest&&manifest.type==='panel_inclusive_quality_matrix','Manifest type must be panel_inclusive_quality_matrix.');
	assert(manifest.version===1,'Manifest version must be 1.');
	assert(typeof manifest.digest==='string'&&/^[a-f0-9]{64}$/.test(manifest.digest),'Manifest requires a SHA-256 digest.');
	assert(validId(manifest.name,64),'Manifest requires a stable bounded name.');
	secureTarget(manifest.url);
	assert(Array.isArray(manifest.profiles)&&manifest.profiles.length>0&&manifest.profiles.length<=32,'Manifest locale profiles exceed their bounds.');
	assert(Array.isArray(manifest.contracts)&&manifest.contracts.length>0&&manifest.contracts.length<=64,'Manifest contracts exceed their bounds.');
	assert(Number.isInteger(manifest.case_count)&&manifest.case_count>0&&manifest.case_count<=2048,'Manifest case count exceeds its bounds.');
	assert(Array.isArray(manifest.browser_manifests)&&manifest.browser_manifests.length>0&&manifest.browser_manifests.length<=manifest.case_count,'Manifest has no browser cases or exceeds its case count.');
	const profileIds=new Set();for(const profile of manifest.profiles){assert(profile&&validId(profile.id)&&!profileIds.has(profile.id),'Manifest locale profile ids must be unique and stable.');profileIds.add(profile.id);}
	const contractIds=new Set();for(const contract of manifest.contracts){assert(contract&&validId(contract.id)&&!contractIds.has(contract.id),'Manifest contract ids must be unique and stable.');contractIds.add(contract.id);}
	const caseIds=new Set();
	for(const item of manifest.browser_manifests){
		assert(item&&item.type==='panel_browser_regression_manifest'&&item.version===1,'Browser manifest has an unsupported type or version.');
		assert(validId(item.name,383)&&!caseIds.has(item.name),'Browser manifest case ids must be unique and stable.');caseIds.add(item.name);
		secureTarget(item.url);
		assert(Array.isArray(item.interactions)&&item.interactions.length<=32,'Browser manifest interactions exceed their bounds.');
		assert(item.meta?.quality_case_id===item.name,'Browser manifest case identity mismatch.');
		assert(item.meta?.quality_matrix_digest===manifest.digest,'Browser manifest matrix digest mismatch.');
		assert(item.meta?.quality_contract?.execution==='browser','Non-browser contract leaked into browser manifests.');
		assert(profileIds.has(item.meta?.quality_profile?.id),'Browser manifest references an unknown locale profile.');
		assert(contractIds.has(item.meta?.quality_contract?.id),'Browser manifest references an unknown contract.');
		if(item.meta?.quality_contract?.domain==='assistive_technology'){
			assert(item.meta.quality_contract.automation==='automated_proxy'&&Array.isArray(item.meta.quality_contract.does_not_prove)&&item.meta.quality_contract.does_not_prove.length>0,'Browser assistive-technology contracts must be bounded proxies.');
		}
	}
	return manifest;
}

function validateWithPhp(config,manifestPath,manifest){
	const result=spawnSync(config.php,[path.join(cwd,'dev','tools','panel_developer.php'),'inclusive-quality-validate','--matrix='+manifestPath],{cwd,encoding:'utf8',maxBuffer:MAX_JSON_BYTES,shell:false,windowsHide:true});
	assert(!result.error&&result.status===0,'PHP rejected the inclusive-quality matrix: '+String(result.stderr||result.error||result.stdout).slice(-2000));
	let validation;try{validation=JSON.parse(String(result.stdout||''));}catch(error){throw new Error('PHP matrix validator returned invalid JSON.');}
	authenticateBrowserCases(manifest,validation);
}

function authenticateBrowserCases(manifest,validation){
	assert(validation&&validation.type==='panel_inclusive_quality_validation'&&validation.version===1&&validation.valid===true,'PHP matrix validator returned an unsupported validation envelope.');
	assert(validation.name===manifest.name&&validation.digest===manifest.digest&&validation.case_count===manifest.case_count&&validation.browser_case_count===manifest.browser_manifests.length,'PHP matrix validator did not authenticate the manifest identity, digest, and counts.');
	assert(Array.isArray(validation.browser_cases)&&validation.browser_cases.length===manifest.browser_manifests.length,'PHP matrix validator did not return the canonical browser case set.');
	const profiles=new Map(manifest.profiles.map(item=>[item.id,item]));const contracts=new Map(manifest.contracts.map(item=>[item.id,item]));
	const canonical=new Map();
	for(const item of validation.browser_cases){
		assert(item&&validId(item.case_id,383)&&validId(item.profile_id)&&validId(item.contract_id),'PHP matrix validator returned an invalid browser case mapping.');
		assert(profiles.has(item.profile_id)&&contracts.has(item.contract_id),'PHP matrix validator returned unknown canonical case ids.');
		assert(!canonical.has(item.case_id),'PHP matrix validator returned duplicate browser case ids.');
		canonical.set(item.case_id,{profile_id:item.profile_id,contract_id:item.contract_id,url:secureTarget(item.url),profile:profiles.get(item.profile_id),contract:contracts.get(item.contract_id)});
	}
	for(const item of manifest.browser_manifests){
		const expected=canonical.get(item.name);
		assert(expected,'Browser manifest case set differs from the PHP-authenticated matrix.');
		assert(item.meta?.quality_profile?.id===expected.profile_id&&item.meta?.quality_contract?.id===expected.contract_id&&secureTarget(item.url)===expected.url&&canonicalJson(item.meta.quality_profile)===canonicalJson(expected.profile)&&canonicalJson(item.meta.quality_contract)===canonicalJson(expected.contract),'Browser manifest case mapping differs from the PHP-authenticated matrix.');
		canonical.delete(item.name);
	}
	assert(canonical.size===0,'Browser manifest omitted PHP-authenticated cases.');
	return manifest;
}

function canonicalJson(value){
	const normalize=item=>Array.isArray(item)?item.map(normalize):(item&&typeof item==='object'?Object.keys(item).sort().reduce((out,key)=>{out[key]=normalize(item[key]);return out;},{}):item);
	return JSON.stringify(normalize(value));
}

function selectCases(manifest,contracts=[],profiles=[]){
	const contractSet=new Set(contracts);const profileSet=new Set(profiles);
	return manifest.browser_manifests.filter(item=>(contractSet.size===0||contractSet.has(item.meta.quality_contract.id))&&(profileSet.size===0||profileSet.has(item.meta.quality_profile.id)));
}

function findPuppeteer(){
	for(const candidate of [path.join(cwd,'.tmp','puppeteer-check','node_modules','puppeteer-core'),path.join(cwd,'.tmp','node_modules','puppeteer-core'),path.join(__dirname,'node_modules','puppeteer-core')]){
		if(fs.existsSync(candidate)){return require(candidate);}
	}
	throw new Error('Unable to find puppeteer-core.');
}

function findBrowser(configured=''){
	const candidates=[configured,process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',path.join(process.env.LOCALAPPDATA||'','Google/Chrome/Application/chrome.exe'),path.join(process.env.PROGRAMFILES||'','Microsoft/Edge/Application/msedge.exe'),'/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean);
	const executable=candidates.find(candidate=>fs.existsSync(candidate));
	if(!executable){throw new Error('Unable to find Chrome or Edge.');}
	return executable;
}

function capability(status,source,version=null){return{status,execution:'browser',source,version};}

function baseCapabilities(browserVersion){
	const source='puppeteer-chromium';
	return{
		'browser.accessibility_tree':capability('available',source,browserVersion),
		'browser.coarse_pointer':capability('available',source,browserVersion),
		'browser.composition_events':capability('available',source,browserVersion),
		'browser.dom':capability('available',source,browserVersion),
		'browser.forced_colors':capability('declared',source,browserVersion),
		'browser.javascript_intl':capability('available',source,browserVersion),
		'browser.keyboard':capability('available',source,browserVersion),
		'browser.reduced_motion':capability('declared',source,browserVersion),
		'browser.touch':capability('available',source,browserVersion),
		'browser.zoom_reflow':capability('available','css-viewport-reflow-proxy',browserVersion),
	};
}

function allowedOrigins(baseUrl,extra=[]){
	const origins=new Set();
	if(baseUrl){const parsed=new URL(secureTarget(baseUrl));origins.add(parsed.origin);}
	for(const value of extra){const parsed=new URL(secureTarget(value));assert(parsed.origin===parsed.toString().replace(/\/$/,''),'--allow-origin values must contain an origin only.');origins.add(parsed.origin);}
	return origins;
}

function targetUrl(item,baseUrl,extraOrigins=[]){
	const target=secureTarget(String(item.url||''));const origins=allowedOrigins(baseUrl,extraOrigins);
	const resolved=target.startsWith('/')?new URL(target,new URL(baseUrl).origin):new URL(target);
	assert(origins.has(resolved.origin),'Browser target origin is not the base origin or an explicit allowlist entry.');
	return resolved.toString();
}

function navigationAllowed(url,baseUrl,extraOrigins=[]){
	try{const parsed=new URL(secureTarget(String(url||'')),new URL(baseUrl).origin);return allowedOrigins(baseUrl,extraOrigins).has(parsed.origin);}
	catch(error){return false;}
}

async function installMainFrameNavigationPolicy(page,baseUrl,extraOrigins=[]){
	const blocked=[];
	await page.setRequestInterception(true);
	const handler=request=>{
		const mainNavigation=request.isNavigationRequest()&&request.frame()===page.mainFrame();
		if(mainNavigation&&!navigationAllowed(request.url(),baseUrl,extraOrigins)){
			blocked.push(request.url());
			void request.abort('blockedbyclient').catch(()=>{});
			return;
		}
		void request.continue().catch(()=>{});
	};
	page.on('request',handler);
	return{blocked,dispose:async()=>{page.off('request',handler);await page.setRequestInterception(false);}};
}

async function mediaCapability(page,name,value){
	const feature={name,value};
	try{await page.emulateMediaFeatures([feature]);return{supported:true,source:'puppeteer-emulate-media'};}
	catch(puppeteerError){
		try{const session=await page.createCDPSession();await session.send('Emulation.setEmulatedMedia',{media:'',features:[feature]});return{supported:true,source:'chromium-cdp'};}
		catch(protocolError){return{supported:false,source:'unavailable',error:String(protocolError?.message||puppeteerError?.message||protocolError||puppeteerError)};}
	}
}

async function prepareEnvironment(page,profile,contract,capabilities){
	const settings=contract.settings||{};
	const touch=settings.mobile===true||settings.pointer==='touch'||settings.pointer==='coarse';
	const zoom=Number(settings.zoom||100)/100;
	const width=/^zoom_(?:200|300|400)$/.test(contract.id)?Math.max(320,Math.round(1280/zoom)):1280;
	await page.setViewport({width,height:800,deviceScaleFactor:1,isMobile:touch,hasTouch:touch});
	await page.emulateTimezone(profile.timezone);
	await page.setExtraHTTPHeaders({'Accept-Language':profile.locale});
	await page.evaluateOnNewDocument(environment=>{
		try{Object.defineProperty(navigator,'language',{configurable:true,get:()=>environment.locale});Object.defineProperty(navigator,'languages',{configurable:true,get:()=>[environment.locale]});}catch(error){}
	},profile);
	if(contract.id==='forced_colors'){
		const result=await mediaCapability(page,'forced-colors','active');
		capabilities['browser.forced_colors']=capability(result.supported?'available':'unavailable',result.source,result.error||null);
	}
	if(contract.id==='reduced_motion'){
		const result=await mediaCapability(page,'prefers-reduced-motion','reduce');
		capabilities['browser.reduced_motion']=capability(result.supported?'available':'unavailable',result.source,result.error||null);
	}
}

async function applyPageEnvironment(page,profile){
	await page.evaluate(environment=>{document.documentElement.lang=environment.locale;document.documentElement.dir=environment.direction;if(document.body){document.body.dir=environment.direction;}},profile);
}

function flattenAccessibility(node,output=[]){if(!node){return output;}output.push(node);for(const child of node.children||[]){flattenAccessibility(child,output);}return output;}

const probes={
	async locale_intl(page,profile){
		const value=await page.evaluate(profile=>{
			const number=new Intl.NumberFormat(profile.locale,{numberingSystem:profile.numbering_system}).format(1234567.89);
			const dateFormatter=new Intl.DateTimeFormat(profile.locale,{timeZone:profile.timezone,calendar:profile.calendar,numberingSystem:profile.numbering_system,dateStyle:'full',timeStyle:'short'});
			const date=dateFormatter.format(new Date('2026-07-14T12:34:56Z'));
			const dateOptions=dateFormatter.resolvedOptions();
			const numberOptions=new Intl.NumberFormat(profile.locale,{numberingSystem:profile.numbering_system}).resolvedOptions();
			const plural=new Intl.PluralRules(profile.locale).resolvedOptions().pluralCategories;
			const canonicalTimezone=new Intl.DateTimeFormat('en',{timeZone:profile.timezone}).resolvedOptions().timeZone;
			return{number,date,dateOptions,numberOptions,plural,canonicalTimezone,lang:document.documentElement.lang,direction:getComputedStyle(document.documentElement).direction};
		},profile);
		const checks=[value.number.length>0,value.date.length>0,value.dateOptions.timeZone===value.canonicalTimezone,value.dateOptions.calendar===profile.calendar,value.numberOptions.numberingSystem===profile.numbering_system,profile.plural_categories.every(category=>value.plural.includes(category)),value.lang===profile.locale,value.direction===profile.direction];
		checks.forEach((check,index)=>assert(check,'Locale Intl assertion '+(index+1)+' failed for '+profile.id+'.'));
		return checks.length;
	},
	async long_text_reflow(page,profile){
		const result=await page.evaluate(profile=>{
			const targets=Array.from(document.querySelectorAll('button,a,label,h1,h2,h3,[role="button"]')).filter(element=>element.children.length===0&&element.textContent.trim()).slice(0,24);
			const originals=targets.map(element=>element.textContent);
			const suffix=' localized content'.repeat(Math.max(1,Math.ceil(profile.long_text_factor*3)));
			targets.forEach(element=>{element.textContent=element.textContent+suffix;});
			const overflow=Math.max(0,document.documentElement.scrollWidth-document.documentElement.clientWidth);
			const escaped=targets.filter(element=>{const box=element.getBoundingClientRect();return box.right>document.documentElement.clientWidth+2||box.left<-2;}).length;
			targets.forEach((element,index)=>{element.textContent=originals[index];});
			return{targets:targets.length,overflow,escaped};
		},profile);
		assert(result.targets>0,'Long-text probe found no visible text targets.');assert(result.overflow<=2,'Long-text expansion created document overflow.');assert(result.escaped===0,'Long-text expansion escaped the viewport.');return 3;
	},
	async pseudo_locale_reflow(page,profile){
		assert(profile.pseudo_locale===true,'Pseudo-locale contract ran against a production locale.');
		const result=await page.evaluate(profile=>{const sample=document.createElement('div');sample.setAttribute('role','status');sample.dir=profile.direction;sample.style.cssText='position:fixed;inset-inline:8px;bottom:8px;max-width:calc(100vw - 16px);overflow-wrap:anywhere';sample.textContent=profile.direction==='rtl'?'\u202e[!!! \u0627\u0644\u0646\u0635 \u0627\u0644\u0645\u062d\u0644\u064a \u0627\u0644\u0645\u0648\u0633\u0639 !!!]\u202c':'[!!! \u013d\u014f\u0107\u00e1\u013a\u00ed\u017e\u00e9\u018c \u0119\u0153\u0192\u00e5\u00f1\u018c\u00e9\u018c \u0167\u0119\u03c7\u0167 !!!]';document.body.append(sample);const box=sample.getBoundingClientRect();const direction=getComputedStyle(sample).direction;const codepoints=Array.from(sample.textContent).map(character=>character.codePointAt(0));sample.remove();return{inside:box.left>=0&&box.right<=innerWidth,direction,codepoints};},profile);
		assert(result.inside,'Pseudo-locale sample escaped the viewport.');assert(result.direction===profile.direction,'Pseudo-locale direction was not applied.');assert(result.codepoints.some(value=>value>127),'Pseudo-locale sample lost its non-ASCII code points.');return 3;
	},
	async keyboard_only(page){
		const focus=[];for(let index=0;index<16;index++){await page.keyboard.press('Tab');focus.push(await page.evaluate(()=>{const active=document.activeElement;const style=active?getComputedStyle(active):null;return{tag:active?.tagName||'',visible:!!active&&active!==document.body&&active.getBoundingClientRect().width>0,outline:style?.outlineStyle!=='none'||style?.boxShadow!=='none'};}));}
		const visible=focus.filter(item=>item.visible);assert(visible.length>=3,'Keyboard traversal reached fewer than three visible controls.');assert(visible.some(item=>item.outline),'Keyboard traversal exposed no visible focus treatment.');await page.keyboard.press('Escape');return visible.length+2;
	},
	async switch_keyboard_proxy(page){
		await page.keyboard.press('Tab');const first=await page.evaluate(()=>document.activeElement&&document.activeElement!==document.body?document.activeElement.tagName:null);await page.keyboard.press('Tab');const second=await page.evaluate(()=>document.activeElement&&document.activeElement!==document.body?document.activeElement.tagName:null);assert(first!==null&&second!==null,'Sequential focus proxy could not reach two controls.');await page.keyboard.press('Escape');return 3;
	},
	async screen_reader_semantics_proxy(page){
		const snapshot=await page.accessibility.snapshot({interestingOnly:false});const nodes=flattenAccessibility(snapshot);assert(nodes.length>10,'Accessibility tree is unexpectedly empty.');assert(nodes.some(node=>node.role==='heading'&&node.name),'Accessibility tree has no named heading.');assert(nodes.some(node=>['main','navigation'].includes(node.role)),'Accessibility tree has no main or navigation landmark.');assert(nodes.filter(node=>['button','link','textbox','combobox'].includes(node.role)).every(node=>String(node.name||'').trim()!==''),'Accessibility tree contains unnamed interactive controls.');return 4;
	},
	async voice_control_names_proxy(page){
		const result=await page.evaluate(()=>{const elements=Array.from(document.querySelectorAll('button,a[href],input:not([type="hidden"]),select,textarea,[role="button"],[role="link"]')).filter(element=>{const style=getComputedStyle(element);const box=element.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&box.width>0&&box.height>0;});const name=element=>(element.getAttribute('aria-label')||element.getAttribute('title')||element.labels?.[0]?.textContent||element.textContent||element.getAttribute('placeholder')||'').trim();const names=elements.map(name);return{total:elements.length,unnamed:names.filter(value=>!value).length,duplicates:names.filter((value,index)=>value&&names.indexOf(value)!==index).length};});assert(result.total>0,'Voice-name proxy found no controls.');assert(result.unnamed===0,'Voice-name proxy found unnamed controls.');return 2;
	},
	async forced_colors(page){const active=await page.evaluate(()=>matchMedia('(forced-colors: active)').matches);assert(active,'Forced-colors media query is not active.');await page.keyboard.press('Tab');const visible=await page.evaluate(()=>{const active=document.activeElement;const style=active?getComputedStyle(active):null;return !!active&&active!==document.body&&(style.outlineStyle!=='none'||style.boxShadow!=='none'||style.borderStyle!=='none');});assert(visible,'Forced-colors focus is not visibly represented.');return 2;},
	async zoom_200(page){return probes.zoom_contract(page,2);},
	async zoom_300(page){return probes.zoom_contract(page,3);},
	async zoom_400(page){return probes.zoom_contract(page,4);},
	async zoom_contract(page,scale){const result=await page.evaluate(()=>({overflow:Math.max(0,document.documentElement.scrollWidth-document.documentElement.clientWidth),main:!!document.querySelector('main.dp-panel'),width:document.documentElement.clientWidth}));assert(result.main,'Zoom-reflow proxy could not find Panel main content.');assert(Math.abs(result.width-Math.max(320,Math.round(1280/scale)))<=1,'Zoom-reflow proxy resolved an unexpected CSS viewport.');assert(result.overflow<=2,'Zoom-reflow proxy at '+scale+'x created document overflow.');return 3;},
	async reduced_motion(page){const result=await page.evaluate(()=>{const long=Array.from(document.querySelectorAll('.dp-panel,.dp-panel *')).map(element=>{const style=getComputedStyle(element);return{element,animation:parseFloat(style.animationDuration),transition:parseFloat(style.transitionDuration),selector:element.tagName.toLowerCase()+'.'+Array.from(element.classList).join('.')};}).filter(item=>item.animation>0.1||item.transition>0.1);return{active:matchMedia('(prefers-reduced-motion: reduce)').matches,long:long.length,samples:long.slice(0,5).map(item=>({selector:item.selector,animation:item.animation,transition:item.transition}))};});assert(result.active,'Reduced-motion preference is not active.');assert(result.long===0,'Reduced-motion mode retained long CSS motion inside Panel: '+JSON.stringify(result.samples));return 2;},
	async touch(page){const result=await page.evaluate(()=>({points:navigator.maxTouchPoints,constructible:typeof TouchEvent==='function'}));assert(result.points>0,'Touch emulation exposes no touch points.');assert(result.constructible,'TouchEvent is unavailable.');return 2;},
	async coarse_pointer(page){const result=await page.evaluate(()=>({coarse:matchMedia('(pointer: coarse)').matches,points:navigator.maxTouchPoints}));assert(result.coarse,'Coarse pointer media query is not active.');assert(result.points>0,'Coarse pointer emulation exposes no touch points.');return 2;},
	async ime_composition(page){const result=await page.evaluate(()=>{const input=document.querySelector('input:not([type="hidden"]),textarea');if(!input){return{missing:true};}const events=[];for(const type of ['compositionstart','compositionupdate','compositionend','input']){input.addEventListener(type,event=>events.push({type:event.type,data:event.data||'',composing:event.isComposing===true}),{once:true});}const first='\u6771';const composed='\u6771\u4eac';input.focus();input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));input.dispatchEvent(new CompositionEvent('compositionupdate',{bubbles:true,data:first}));input.value=composed;input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:composed}));input.dispatchEvent(new InputEvent('input',{bubbles:true,data:composed,inputType:'insertCompositionText',isComposing:false}));return{value:input.value,codepoints:Array.from(input.value).map(character=>character.codePointAt(0)),events};});assert(!result.missing,'IME proxy found no text control.');assert(result.value==='\u6771\u4eac','IME proxy did not preserve composed text.');assert(result.codepoints.join(',')==='26481,20140','IME proxy preserved the wrong Unicode code points.');assert(result.events.map(item=>item.type).join(',')==='compositionstart,compositionupdate,compositionend,input','IME proxy emitted the wrong event sequence.');return 4;},
	async virtual_cursor_semantics_proxy(page){const snapshot=await page.accessibility.snapshot({interestingOnly:false});const nodes=flattenAccessibility(snapshot);const readable=nodes.filter(node=>String(node.name||'').trim()!==''&&['heading','link','button','StaticText','textbox','combobox'].includes(node.role));assert(readable.length>=5,'Virtual-cursor proxy found too little readable structure.');assert(readable.some(node=>node.role==='heading'),'Virtual-cursor proxy found no heading.');assert(readable.some(node=>['link','button'].includes(node.role)),'Virtual-cursor proxy found no actionable control.');return 3;},
};

function missingCapabilities(contract,capabilities){return(contract.required_capabilities||[]).filter(id=>capabilities[id]?.status!=='available'||capabilities[id]?.execution!=='browser');}

async function executeCase(browser,item,baseUrl,extraOrigins,capabilities,reportPath,browserVersion){
	const profile=item.meta.quality_profile;const contract=item.meta.quality_contract;const page=await browser.newPage();const started=Date.now();let status='passed';let assertions=0;let notes=null;let navigationPolicy=null;
	try{
		await prepareEnvironment(page,profile,contract,capabilities);
		const target=targetUrl(item,baseUrl,extraOrigins);navigationPolicy=await installMainFrameNavigationPolicy(page,baseUrl,extraOrigins);
		let response;
		try{response=await page.goto(target,{waitUntil:'domcontentloaded',timeout:30000});}
		catch(error){if(navigationPolicy.blocked.length){throw new Error('Blocked non-allowlisted main-frame navigation before contact: '+navigationPolicy.blocked.join(', '));}throw error;}
		assert(navigationPolicy.blocked.length===0,'Blocked non-allowlisted main-frame navigation before contact.');
		assert(response&&response.ok(),'Panel target returned HTTP '+String(response?.status()||'no response')+'.');
		assert(navigationAllowed(response.url(),baseUrl,extraOrigins),'Panel target redirected to a non-allowlisted origin.');
		await applyPageEnvironment(page,profile);
		const unavailable=missingCapabilities(contract,capabilities);
		if(unavailable.length){status='blocked';notes='Unavailable capabilities: '+unavailable.join(', ');}
		else{const probe=probes[contract.id];assert(typeof probe==='function','No browser probe implements contract '+contract.id+'.');assertions=await probe(page,profile,contract);assert(Number.isInteger(assertions)&&assertions>0,'Probe returned no assertions.');}
	}catch(error){status='failed';notes=String(error?.stack||error).slice(0,2000);assertions=Math.max(assertions,1);}
	finally{if(navigationPolicy){await navigationPolicy.dispose();}await page.close();}
	const executed=status==='passed'||status==='failed';
	return{case_id:item.name,status,execution:'browser',executor:executed?'Chromium '+browserVersion:null,artifact:executed?reportPath:null,assertions:executed?assertions:0,duration_ms:executed?Date.now()-started:0,capabilities:executed?Array.from(new Set(contract.required_capabilities||[])).sort():[],notes,observed_at:executed?new Date().toISOString():null,matrix_digest:item.meta.quality_matrix_digest};
}

async function run(config){
	const manifestPath=absolute(config.manifest);const manifest=validateManifest(readJson(manifestPath));validateWithPhp(config,manifestPath,manifest);const cases=selectCases(manifest,config.contracts,config.profiles);
	assert(cases.length>0,'No browser cases matched the requested selection.');
	if(config.list){for(const item of cases){console.log(item.name);}return{exitCode:0};}
	assert(config.report,'--report is required for an executed browser run.');
	allowedOrigins(config.baseUrl,config.allowOrigins);
	const reportPath=absolute(config.report);const puppeteer=findPuppeteer();const launchArguments=['--disable-dev-shm-usage'];if(config.allowNoSandbox){launchArguments.push('--no-sandbox');}const browser=await puppeteer.launch({executablePath:findBrowser(config.browser),headless:!config.headed,args:launchArguments});
	let browserVersion='unknown';let capabilities={};const evidence=[];
	try{browserVersion=await browser.version();capabilities=baseCapabilities(browserVersion);for(const item of cases){evidence.push(await executeCase(browser,item,config.baseUrl,config.allowOrigins,capabilities,reportPath,browserVersion));}}
	finally{await browser.close();}
	const failed=evidence.filter(item=>item.status==='failed');const blocked=evidence.filter(item=>item.status==='blocked');const passed=evidence.filter(item=>item.status==='passed');
	const capabilityPayload={type:'panel_quality_capability_report',version:1,capabilities};
	const report={type:'panel_inclusive_quality_browser_report',version:1,matrix:{name:manifest.name,digest:manifest.digest},browser:browserVersion,ok:failed.length===0&&blocked.length===0,security:{sandbox_disabled:config.allowNoSandbox,allowed_origins:Array.from(allowedOrigins(config.baseUrl,config.allowOrigins)).sort(),main_frame_navigation_policy:'pre_request_same_origin_allowlist',subresource_origin_policy:'page_policy_not_enforced'},selection:{contracts:config.contracts,profiles:config.profiles},summary:{total:evidence.length,passed:passed.length,failed:failed.length,blocked:blocked.length},capabilities:capabilityPayload,evidence};
	writeJsonAtomic(reportPath,report);if(config.capabilities){writeJsonAtomic(absolute(config.capabilities),capabilityPayload);}
	console.log(JSON.stringify({report:reportPath,ok:report.ok,...report.summary}));
	return{exitCode:report.ok||config.reportOnly?0:1,report};
}

async function main(){const args=parseArgs(process.argv.slice(2));if(args.help){printHelp();return 0;}assert(args.manifest,'--manifest is required.');const result=await run(args);return result.exitCode;}

if(require.main===module){main().then(code=>{process.exitCode=code;}).catch(error=>{console.error(error?.stack||String(error));process.exitCode=2;});}

module.exports={authenticateBrowserCases,baseCapabilities,installMainFrameNavigationPolicy,navigationAllowed,parseArgs,readJson,selectCases,targetUrl,validateManifest};
