<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Bounded operator intent; raw instructions are deliberately excluded from evidence. */
final class PanelOperatorTask implements \JsonSerializable {
	private readonly string $id;private readonly string $actorId;private readonly ?string $tenantId;private readonly string $instruction;private readonly string $risk;private readonly string $classification;private readonly ?string $residency;/** @var list<string> */private readonly array $allowedTools;/** @var list<string> */private readonly array $requiredCapabilities;private readonly int $maxOutputTokens;private readonly int $maxCostMicros;private readonly bool $dryRun;/** @var array<string,mixed> */private readonly array $context;private readonly ?string $deadlineAt;private readonly int $inputTokens;
	/** @param list<string> $allowedTools @param list<string> $requiredCapabilities @param array<string,mixed> $context */
	public function __construct(string $id,string $actorId,?string $tenantId,string $instruction,string $risk='medium',string $classification='internal',?string $residency=null,array $allowedTools=[],array $requiredCapabilities=['text'],int $maxOutputTokens=2048,int $maxCostMicros=0,bool $dryRun=true,array $context=[],?string $deadlineAt=null){
		$this->id=PanelOperationsGuard::identifier($id,'operator task id');$this->actorId=PanelOperationsGuard::identifier($actorId,'operator actor id');$this->tenantId=$tenantId!==null?PanelOperationsGuard::identifier($tenantId,'operator tenant id'):null;$instruction=trim($instruction);if($instruction===''||strlen($instruction)>131072||str_contains($instruction,"\0")){throw new \InvalidArgumentException('Operator instruction is invalid.');}$this->instruction=$instruction;$risk=strtolower(trim($risk));if(!in_array($risk,['low','medium','high','critical'],true)){throw new \InvalidArgumentException('Operator task risk is invalid.');}$this->risk=$risk;$this->classification=PanelOperationsGuard::name($classification,'operator classification');$this->residency=$residency!==null?PanelOperationsGuard::name($residency,'operator residency'):null;$this->allowedTools=PanelOperationsGuard::names($allowedTools,'operator tool',128,1024);$this->requiredCapabilities=PanelOperationsGuard::names($requiredCapabilities,'operator capability');if($maxOutputTokens<1||$maxOutputTokens>1048576||$maxCostMicros<0){throw new \InvalidArgumentException('Operator task output or cost budget is invalid.');}$this->maxOutputTokens=$maxOutputTokens;$this->maxCostMicros=$maxCostMicros;$this->dryRun=$dryRun;$this->context=PanelOperationsGuard::safeMetadata($context,1024);$this->deadlineAt=$deadlineAt!==null?PanelOperationsGuard::instant($deadlineAt):null;$this->inputTokens=max(1,(int)ceil(strlen($instruction)/4));
	}
	/** @param array<string,mixed> $task */ public static function from(array $task):self{return new self(PanelOperationsGuard::identifier((string)($task['id']??''),'operator task id'),PanelOperationsGuard::identifier((string)($task['actor_id']??''),'operator actor id'),isset($task['tenant_id'])?PanelOperationsGuard::identifier((string)$task['tenant_id'],'operator tenant id'):null,(string)($task['instruction']??''),in_array(($risk=strtolower((string)($task['risk']??'medium'))),['low','medium','high','critical'],true)?$risk:'medium',PanelOperationsGuard::name((string)($task['classification']??'internal'),'operator classification'),isset($task['residency'])?PanelOperationsGuard::name((string)$task['residency'],'operator residency'):null,PanelOperationsGuard::names(is_array($task['allowed_tools']??null)?$task['allowed_tools']:[],'operator tool',128,1024),PanelOperationsGuard::names(is_array($task['required_capabilities']??null)?$task['required_capabilities']:['text'],'operator capability'),(int)($task['max_output_tokens']??2048),max(0,(int)($task['max_cost_micros']??0)),($task['dry_run']??true)!==false,PanelOperationsGuard::safeMetadata(is_array($task['context']??null)?$task['context']:[],1024),isset($task['deadline_at'])?PanelOperationsGuard::instant(is_int($task['deadline_at'])?$task['deadline_at']:(string)$task['deadline_at']):null);}
	public function id():string{return$this->id;}public function actorId():string{return$this->actorId;}public function tenantId():?string{return$this->tenantId;}public function instruction():string{return$this->instruction;}public function risk():string{return$this->risk;}public function classification():string{return$this->classification;}public function residency():?string{return$this->residency;}public function inputTokens():int{return$this->inputTokens;}public function maxOutputTokens():int{return$this->maxOutputTokens;}public function maxCostMicros():int{return$this->maxCostMicros;}public function dryRun():bool{return$this->dryRun;}public function deadlineAt():?string{return$this->deadlineAt;}/** @return list<string> */public function allowedTools():array{return$this->allowedTools;}/** @return list<string> */public function requiredCapabilities():array{return$this->requiredCapabilities;}/** @return array<string,mixed> */public function context():array{return$this->context;}
	public function allowsTool(string $tool):bool{return$this->allowedTools!==[]&&in_array($tool,$this->allowedTools,true);}
	public function policyRequest(string $ability='operator.plan'):PanelPolicyRequest{return new PanelPolicyRequest($this->actorId,$ability,$this->tenantId,'operator_task',$this->id,$this->risk,[],[],['classification'=>$this->classification,'residency'=>$this->residency,'dry_run'=>$this->dryRun,'max_cost_micros'=>$this->maxCostMicros,'allowed_tools'=>$this->allowedTools]+$this->context);}
	public function fingerprint():string{return PanelOperationsGuard::digest($this->evidence());}
	/** @return array<string,mixed> */public function evidence():array{return['id'=>$this->id,'actor_id'=>$this->actorId,'tenant_id'=>$this->tenantId,'instruction_hash'=>hash('sha256',$this->instruction),'instruction_bytes'=>strlen($this->instruction),'risk'=>$this->risk,'classification'=>$this->classification,'residency'=>$this->residency,'allowed_tools'=>$this->allowedTools,'required_capabilities'=>$this->requiredCapabilities,'input_tokens'=>$this->inputTokens,'max_output_tokens'=>$this->maxOutputTokens,'max_cost_micros'=>$this->maxCostMicros,'dry_run'=>$this->dryRun,'context'=>$this->context,'deadline_at'=>$this->deadlineAt];}
	public function jsonSerialize():array{return['type'=>'panel_operator_task']+$this->evidence()+['fingerprint'=>$this->fingerprint(),'raw_instruction_exposed'=>false];}
}
