<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Governed AI operator: policy, routing, structured plans, evals, approvals, budgets, and evidence. */
final class PanelOperatorRuntime implements \JsonSerializable {
	/** @var array<string,\Closure> */ private array $evaluators=[];
	/** @var array<string,string> */ private array $approvalKeys=[];
	private readonly ?\Closure $executor;
	/** @param array<string,mixed> $toolManifest @param array<string,callable> $evaluators @param array<string,string> $approvalKeys */
	public function __construct(private readonly PanelOperatorRouter $router,private readonly PanelPolicyControlPlane $policy,private readonly array $toolManifest,array $evaluators=[],?callable $executor=null,array $approvalKeys=[]){PanelOperationsGuard::object($toolManifest,'operator tool manifest',4096);foreach($toolManifest as$name=>$definition){PanelOperationsGuard::name((string)$name,'operator tool name');if(!is_array($definition)){throw new \InvalidArgumentException('Operator tool manifests must be object-like maps.');}}foreach($evaluators as$name=>$evaluator){$this->evaluators[PanelOperationsGuard::name((string)$name,'operator evaluator name')]=\Closure::fromCallable($evaluator);}foreach($approvalKeys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'operator approval key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Operator approval keys require at least 32 bytes.');}$this->approvalKeys[$id]=$key;}$this->executor=$executor!==null?\Closure::fromCallable($executor):null;}

	public function plan(PanelOperatorTask|array $task):PanelOperatorRun {$task=$task instanceof PanelOperatorTask?$task:PanelOperatorTask::from($task);$decision=$this->policy->evaluate($task->policyRequest());if(!$decision->allowed()){return new PanelOperatorRun($task,$decision,'denied');}try{$model=$this->router->route($task,$decision->obligations());}catch(\Throwable $error){return new PanelOperatorRun($task,$decision,'routing_failed',null,null,[],null,$this->message($error));}try{$raw=$this->router->adapter($model->id())->propose($task,$model,$this->allowedTools($task));$proposal=$raw instanceof PanelOperatorProposal?$raw:PanelOperatorProposal::from($task,$model,$raw);$this->assertProposal($task,$model,$proposal,$decision);}catch(\Throwable $error){return new PanelOperatorRun($task,$decision,'model_failed',$model,null,[],null,$this->message($error));}$evaluations=$this->evaluate($task,$proposal,$decision);foreach($evaluations as$evaluation){if(!$evaluation->passed()){return new PanelOperatorRun($task,$decision,'evaluation_failed',$model,$proposal,$evaluations);}}$status=$decision->requiresApproval()?'awaiting_approval':($decision->confirmationRequired()?'awaiting_confirmation':'planned');return new PanelOperatorRun($task,$decision,$status,$model,$proposal,$evaluations);}

	/** @param list<PanelOperatorApproval> $approvals */
	public function execute(PanelOperatorRun $run,array $approvals=[],bool $confirmed=false):PanelOperatorRun {if(!$run->executable()){throw new \LogicException('Operator run is not executable.');}$proposal=$run->proposal();if(!$proposal instanceof PanelOperatorProposal){throw new \LogicException('Operator run has no proposal.');}$fresh=$this->policy->evaluate($run->task()->policyRequest('operator.execute'));if(!$fresh->allowed()){return new PanelOperatorRun($run->task(),$fresh,'denied',$run->model(),$proposal,$run->evaluations());}if($fresh->revision()!==$run->decision()->revision()){return$run->withStatus('execution_failed',null,'Policy changed after planning; the task must be replanned.');}$plannedModel=$run->model();try{$currentModel=$plannedModel!==null?$this->router->model($plannedModel->id()):null;}catch(\Throwable){$currentModel=null;}if($plannedModel===null||$currentModel===null||!hash_equals($plannedModel->fingerprint(),$currentModel->fingerprint())||!$currentModel->supports($run->task())){return$run->withStatus('execution_failed',null,'Model deployment changed after planning; the task must be replanned.');}$obligations=$this->merge($run->decision()->obligations(),$fresh->obligations());$required=max((int)($obligations['approval_count']??0),$run->decision()->approvalCount());$approvers=[];foreach($approvals as$approval){if(!$approval instanceof PanelOperatorApproval||!$approval->verify($this->approvalKeys,$run->approvalTarget())){continue;}$approvers[$approval->approverId()]=true;}if(($obligations['separation_of_duties']??false)===true){unset($approvers[$run->task()->actorId()]);}if(count($approvers)<$required){return $run->withStatus('awaiting_approval');}if(($obligations['confirmation']??false)===true&&!$confirmed){return$run->withStatus('awaiting_confirmation');}if($this->executor===null){return$run->withStatus('execution_failed',null,'Operator execution adapter is not configured.');}try{$output=($this->executor)($proposal,$run->task(),$currentModel,$obligations,$this);return$run->withStatus('completed',PanelSensitiveDataSanitizer::sanitize($output));}catch(\Throwable $error){return$run->withStatus('execution_failed',null,$this->message($error));}}

	public function router():PanelOperatorRouter{return$this->router;}public function policy():PanelPolicyControlPlane{return$this->policy;}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_operator_runtime_manifest','version'=>1,'router'=>$this->router->jsonSerialize(),'policy_revision'=>$this->policy->revision(),'tool_count'=>count($this->toolManifest),'evaluator_names'=>array_keys($this->evaluators),'approval_key_ids'=>array_keys($this->approvalKeys),'executor_configured'=>$this->executor!==null,'capabilities'=>['deny_by_default'=>true,'model_routing'=>true,'residency'=>true,'classification'=>true,'cost_budgets'=>true,'structured_plans'=>true,'tool_allowlists'=>true,'secret_rejection'=>true,'evaluations'=>true,'signed_approvals'=>true,'separation_of_duties'=>true,'confirmation'=>true,'dry_run'=>true,'sanitized_evidence'=>true]]);}

	/** @return array<string,mixed> */private function allowedTools(PanelOperatorTask $task):array {$result=[];foreach($task->allowedTools()as$name){if(!isset($this->toolManifest[$name])){throw new \LogicException('Operator task references an unregistered tool.');}$result[$name]=$this->toolManifest[$name];}return$result;}
	private function assertProposal(PanelOperatorTask $task,PanelOperatorModel $model,PanelOperatorProposal $proposal,PanelPolicyDecision $decision):void {if(!hash_equals($proposal->taskFingerprint(),$task->fingerprint())||$proposal->modelId()!==$model->id()){throw new \LogicException('Operator proposal is not bound to the selected task and model.');}foreach($proposal->steps()as$step){if(!$task->allowsTool((string)$step['tool'])||!isset($this->toolManifest[$step['tool']])){throw new \LogicException('Operator proposal requested a tool outside its allowlist.');}}if($proposal->outputTokens()>$task->maxOutputTokens()){throw new \LogicException('Operator proposal exceeds its output token budget.');}$limit=$task->maxCostMicros();$policyLimit=max(0,(int)($decision->obligations()['max_cost_micros']??0));if($policyLimit>0){$limit=$limit>0?min($limit,$policyLimit):$policyLimit;}if($limit>0&&$proposal->estimatedCostMicros()>$limit){throw new \LogicException('Operator proposal exceeds its cost budget.');}}
	/** @return list<PanelOperatorEvaluation> */private function evaluate(PanelOperatorTask $task,PanelOperatorProposal $proposal,PanelPolicyDecision $decision):array {$evaluations=[PanelOperatorEvaluation::pass('structure','Proposal shape and bindings are valid.'),$proposal->steps()===[]?PanelOperatorEvaluation::fail('actionability','Proposal contains no executable steps.'):PanelOperatorEvaluation::pass('actionability','Proposal contains executable steps.'),PanelOperatorEvaluation::pass('budget','Proposal is within the governed token and cost budgets.')];$required=is_array($decision->obligations()['required_evaluators']??null)?$decision->obligations()['required_evaluators']:array_keys($this->evaluators);foreach($required as$name){$name=PanelOperationsGuard::name((string)$name,'operator evaluator name');$evaluator=$this->evaluators[$name]??null;if(!$evaluator){$evaluations[]=PanelOperatorEvaluation::fail($name,'Required evaluator is not configured.');continue;}try{$result=$evaluator($task,$proposal,$decision,$this);if($result instanceof PanelOperatorEvaluation){$evaluations[]=$result;}elseif($result===true){$evaluations[]=PanelOperatorEvaluation::pass($name);}elseif(is_array($result)){$evaluations[]=new PanelOperatorEvaluation($name,($result['passed']??false)===true,PanelOperationsGuard::label((string)($result['message']??'Evaluator returned a result.'),'operator evaluation message',2048),PanelOperationsGuard::safeMetadata(is_array($result['evidence']??null)?$result['evidence']:[],256));}else{$evaluations[]=PanelOperatorEvaluation::fail($name);}}catch(\Throwable){$evaluations[]=PanelOperatorEvaluation::fail($name,'Evaluator failed closed.');}}return$evaluations;}
	/** @param array<string,mixed> $first @param array<string,mixed> $second @return array<string,mixed> */private function merge(array $first,array $second):array {foreach($second as$key=>$value){if(in_array($key,['approval_count','mfa_level'],true)){$first[$key]=max((int)($first[$key]??0),(int)$value);}elseif(in_array($key,['confirmation','separation_of_duties','dry_run'],true)){$first[$key]=($first[$key]??false)===true||$value===true;}else{$first[$key]=$value;}}return$first;}
	private function message(\Throwable $error):string {$type=(new \ReflectionClass($error))->getShortName();return'Operator boundary failed closed ('.$type.').';}
}
