<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Governed model deployment descriptor used by the deterministic router. */
final class PanelOperatorModel implements \JsonSerializable {
	private readonly string $id;private readonly string $provider;private readonly string $model;/** @var list<string> */private readonly array $capabilities;/** @var list<string> */private readonly array $regions;/** @var list<string> */private readonly array $classifications;private readonly int $contextWindow;private readonly int $maxOutputTokens;private readonly int $inputMicrosPerMillion;private readonly int $outputMicrosPerMillion;private readonly int $latencyRank;private readonly string $health;
	/** @param list<string> $capabilities @param list<string> $regions @param list<string> $classifications */
	public function __construct(string $id,string $provider,string $model,array $capabilities,array $regions,array $classifications,int $contextWindow,int $maxOutputTokens,int $inputMicrosPerMillion,int $outputMicrosPerMillion,int $latencyRank=50,string $health='ready'){
		$this->id=PanelOperationsGuard::name($id,'operator model id');$this->provider=PanelOperationsGuard::name($provider,'operator model provider');$this->model=PanelOperationsGuard::label($model,'operator model name',256);if($capabilities===[]||$regions===[]||$classifications===[]){throw new \InvalidArgumentException('Operator models require capabilities, regions, and classifications.');}$this->capabilities=PanelOperationsGuard::names($capabilities,'model capability');$this->regions=PanelOperationsGuard::names($regions,'model region');$this->classifications=PanelOperationsGuard::names($classifications,'model classification');$health=strtolower(trim($health));if($contextWindow<1024||$maxOutputTokens<1||$maxOutputTokens>$contextWindow||$inputMicrosPerMillion<0||$outputMicrosPerMillion<0||$latencyRank<0||$latencyRank>100||!in_array($health,['ready','degraded','unavailable'],true)){throw new \InvalidArgumentException('Operator model capacity, cost, latency, or health is invalid.');}$this->contextWindow=$contextWindow;$this->maxOutputTokens=$maxOutputTokens;$this->inputMicrosPerMillion=$inputMicrosPerMillion;$this->outputMicrosPerMillion=$outputMicrosPerMillion;$this->latencyRank=$latencyRank;$this->health=$health;
	}
	/** @param array<string,mixed> $definition */ public static function from(string $id,array $definition):self{return new self(PanelOperationsGuard::name($id,'operator model id'),PanelOperationsGuard::name((string)($definition['provider']??''),'operator model provider'),PanelOperationsGuard::label((string)($definition['model']??$id),'operator model name',256),PanelOperationsGuard::names(is_array($definition['capabilities']??null)?$definition['capabilities']:['text'],'model capability'),PanelOperationsGuard::names(is_array($definition['regions']??null)?$definition['regions']:['global'],'model region'),PanelOperationsGuard::names(is_array($definition['classifications']??null)?$definition['classifications']:['public'],'model classification'),(int)($definition['context_window']??8192),(int)($definition['max_output_tokens']??2048),max(0,(int)($definition['input_micros_per_million']??0)),max(0,(int)($definition['output_micros_per_million']??0)),max(0,min(100,(int)($definition['latency_rank']??50))),in_array(($health=(string)($definition['health']??'ready')),['ready','degraded','unavailable'],true)?$health:'unavailable');}
	public function id():string{return$this->id;}public function provider():string{return$this->provider;}public function model():string{return$this->model;}public function contextWindow():int{return$this->contextWindow;}public function maxOutputTokens():int{return$this->maxOutputTokens;}public function latencyRank():int{return$this->latencyRank;}public function health():string{return$this->health;}/** @return list<string> */public function capabilities():array{return$this->capabilities;}/** @return list<string> */public function regions():array{return$this->regions;}/** @return list<string> */public function classifications():array{return$this->classifications;}
	public function supports(PanelOperatorTask $task):bool{return$this->health!=='unavailable'&&$task->inputTokens()+$task->maxOutputTokens()<=$this->contextWindow&&$task->maxOutputTokens()<=$this->maxOutputTokens&&array_diff($task->requiredCapabilities(),$this->capabilities)===[]&&in_array($task->classification(),$this->classifications,true)&&($task->residency()===null||in_array($task->residency(),$this->regions,true));}
	public function estimatedCost(int $inputTokens,int $outputTokens):int{return(int)ceil((max(0,$inputTokens)*$this->inputMicrosPerMillion+max(0,$outputTokens)*$this->outputMicrosPerMillion)/1000000);}
	public function fingerprint():string{return PanelOperationsGuard::digest($this->values());}
	public function jsonSerialize():array{return$this->values()+['fingerprint'=>$this->fingerprint()];}
	/** @return array<string,mixed> */private function values():array{return['type'=>'panel_operator_model','id'=>$this->id,'provider'=>$this->provider,'model'=>$this->model,'capabilities'=>$this->capabilities,'regions'=>$this->regions,'classifications'=>$this->classifications,'context_window'=>$this->contextWindow,'max_output_tokens'=>$this->maxOutputTokens,'input_micros_per_million'=>$this->inputMicrosPerMillion,'output_micros_per_million'=>$this->outputMicrosPerMillion,'latency_rank'=>$this->latencyRank,'health'=>$this->health];}
}
