<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Atomic local reference adapter with snapshots, leases, fencing, and resumable checkpoints. */
final class PanelAtomicMigrationStore implements PanelMigrationStore {
	private PanelAtomicSnapshotStore $state;private \Closure $clock;private \Closure $tokenFactory;private \Closure $runFactory;
	public function __construct(string $directory,int $retain=512,?callable $clock=null,?callable $tokenFactory=null,?callable $runFactory=null){
		$this->state=new PanelAtomicSnapshotStore($directory,'dataphyre.panel.migrations.v1',['states'=>[],'leases'=>[],'fences'=>[],'runs'=>[],'snapshots'=>[],'idempotency'=>[]],$retain);
		$this->clock=\Closure::fromCallable($clock??static fn():string=>gmdate(DATE_ATOM));$this->tokenFactory=\Closure::fromCallable($tokenFactory??static fn():string=>bin2hex(random_bytes(32)));$this->runFactory=\Closure::fromCallable($runFactory??static fn():string=>'migration-'.bin2hex(random_bytes(12)));
	}

	public function state(string $scope,?string $tenant=null):PanelMigrationState{$scope=PanelMigrationIntegrity::identifier($scope,'scope');$tenant=PanelMigrationIntegrity::tenant($tenant);$payload=$this->payload();return$this->stateFromPayload($payload,$scope,$tenant);}

	/** Local-adapter bootstrap/import API. Rejects replacement while execution is leased. @param array<string,mixed> $data @param list<string> $applied */
	public function seed(string $scope,?string $tenant,PanelMigrationVersion $version,array $data=[],array $applied=[]):PanelMigrationState {
		$scope=PanelMigrationIntegrity::identifier($scope,'scope');$tenant=PanelMigrationIntegrity::tenant($tenant);$key=$this->scopeKey($scope,$tenant);
		$transaction=$this->state->transaction(function(array &$payload)use($scope,$tenant,$key,$version,$data,$applied):PanelMigrationState{$this->normalize($payload);if(isset($payload['leases'][$key])){throw new PanelMigrationConflict('Cannot seed Panel migration state while its scope is leased.');}$current=$this->stateFromPayload($payload,$scope,$tenant);$next=PanelMigrationState::make($scope,$tenant,$version,$data,$applied,$current->revision()+1);$payload['states'][$key]=$next->stored();return$next;},'migration.state_seeded',['scope'=>$scope,'tenant'=>$tenant]);return$transaction['result'];
	}

	public function acquire(string $scope,?string $tenant,string $owner='migration-worker',int $ttlSeconds=60):?PanelMigrationLease {
		$this->recoverExpired(1000);$scope=PanelMigrationIntegrity::identifier($scope,'scope');$tenant=PanelMigrationIntegrity::tenant($tenant);$owner=PanelMigrationIntegrity::identifier($owner,'lease owner');$ttl=$this->ttl($ttlSeconds);$token=($this->tokenFactory)();
		if(!is_string($token)||strlen($token)<32||strlen($token)>512||str_contains($token,"\0")){throw new \UnexpectedValueException('Panel migration lease token factory returned an unsafe bearer proof.');}
		$key=$this->scopeKey($scope,$tenant);$now=$this->now();$expires=$this->plusSeconds($now,$ttl);
		$transaction=$this->state->transaction(function(array &$payload)use($scope,$tenant,$owner,$token,$key,$now,$expires):?PanelMigrationLease{$this->normalize($payload);if(isset($payload['leases'][$key])){return null;}$fence=max(0,(int)($payload['fences'][$key]??0))+1;$lease=PanelMigrationLease::make($scope,$tenant,$owner,$token,$fence,$now,$expires);$payload['fences'][$key]=$fence;$payload['leases'][$key]=$this->leaseState($lease);return$lease;},'migration.lease_acquired',['scope'=>$scope,'tenant'=>$tenant,'owner'=>$owner]);return$transaction['result'];
	}

	public function renew(PanelMigrationLease $lease,int $ttlSeconds=60):PanelMigrationLease {
		$now=$this->now();$expires=$this->plusSeconds($now,$this->ttl($ttlSeconds));$transaction=$this->state->transaction(function(array &$payload)use($lease,$now,$expires):PanelMigrationLease{$this->normalize($payload);$state=$this->validateLease($payload,$lease,$now);$state['renewed_at']=$now;$state['expires_at']=$expires;$payload['leases'][$lease->scopeKey()]=$state;return$lease->renewed($now,$expires);},'migration.lease_renewed',['scope'=>$lease->scope(),'tenant'=>$lease->tenant(),'fence'=>$lease->fence()]);return$transaction['result'];
	}

	public function begin(PanelMigrationLease $lease,PanelMigrationPlan $plan,mixed $actor=null):PanelMigrationReport {
		$now=$this->now();$transaction=$this->state->transaction(function(array &$payload)use($lease,$plan,$actor,$now):PanelMigrationReport{
			$this->normalize($payload);$this->validateLease($payload,$lease,$now);$this->assertPlanScope($lease,$plan);$key=$lease->scopeKey();$state=$this->stateFromPayload($payload,$lease->scope(),$lease->tenant());$idempotency=$plan->idempotencyKey();$existing=$payload['idempotency'][$idempotency]??null;
			if(is_string($existing)&&isset($payload['runs'][$existing])&&is_array($payload['runs'][$existing])){$run=&$payload['runs'][$existing];if(($run['status']??null)==='rolled_back'){unset($payload['idempotency'][$idempotency]);}else{$this->assertRunState($run,$state,$plan);if(($run['status']??null)==='completed'){return$this->reportFromRun($run);}if(!in_array($run['status']??null,['running','paused','failed'],true)){throw new PanelMigrationConflict('Panel migration run cannot be resumed from its current lifecycle state.');}$run['status']='running';$run['resumes']=max(0,(int)($run['resumes']??0))+1;$run['updated_at']=$now;$run['errors']=[];return$this->reportFromRun($run);}}
			if($state->revision()!==$plan->stateRevision()||!hash_equals($state->digest(),$plan->stateDigest())||!$state->version()->equals($plan->source())){throw new PanelMigrationStalePlan($plan->digest());}
			$runId=$this->newRunId($payload);$snapshotId=$runId.'.backup';$payload['snapshots'][$snapshotId]=['id'=>$snapshotId,'run_id'=>$runId,'scope'=>$plan->scope(),'tenant'=>$plan->tenant(),'revision'=>$state->revision(),'state_digest'=>$state->digest(),'created_at'=>$now,'state'=>$state->stored()];
			$run=['run_id'=>$runId,'plan_digest'=>$plan->digest(),'idempotency_key'=>$idempotency,'scope'=>$plan->scope(),'tenant'=>$plan->tenant(),'source'=>$plan->source()->jsonSerialize(),'target'=>$plan->target()->jsonSerialize(),'steps'=>$plan->steps(),'status'=>'running','step_index'=>0,'rollback_index'=>null,'checkpoints'=>[],'batch_count'=>0,'processed'=>0,'receipts'=>[],'errors'=>[],'resumes'=>0,'snapshot_id'=>$snapshotId,'expected_revision'=>$state->revision(),'expected_digest'=>$state->digest(),'actor_fingerprint'=>substr(PanelMigrationIntegrity::digest(PanelMigrationIntegrity::redact($actor)),0,16),'started_at'=>$now,'updated_at'=>$now,'completed_at'=>null,'rollback_mode'=>null];$payload['runs'][$runId]=$run;$payload['idempotency'][$idempotency]=$runId;return$this->reportFromRun($run);
		},'migration.run_begun',['scope'=>$plan->scope(),'tenant'=>$plan->tenant(),'plan_digest'=>$plan->digest()]);return$transaction['result'];
	}

	public function applyBatch(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan,PanelMigrationDefinition $definition,mixed $actor=null):PanelMigrationReport {
		return$this->batch($lease,$runId,$plan,$definition,$actor,false);
	}

	public function beginRollback(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan):PanelMigrationReport {
		$runId=PanelMigrationIntegrity::identifier($runId,'run id');$now=$this->now();$transaction=$this->state->transaction(function(array &$payload)use($lease,$runId,$plan,$now):PanelMigrationReport{$this->normalize($payload);$this->validateLease($payload,$lease,$now);$run=&$this->requiredRun($payload,$runId);$this->assertRunPlan($run,$plan);$state=$this->stateFromPayload($payload,$lease->scope(),$lease->tenant());$this->assertRunState($run,$state,$plan);if(($run['status']??null)==='rolled_back'){return$this->reportFromRun($run);}if(!is_int($run['rollback_index']??null)){$step=max(0,(int)($run['step_index']??0));$steps=$plan->steps();$current=$steps[$step]??null;$hasPartial=is_array($current)&&isset($run['checkpoints']['up:'.(string)$current['id']]);$run['rollback_index']=$hasPartial?$step:$step-1;}$run['status']='rolling_back';$run['updated_at']=$now;return$this->reportFromRun($run);},'migration.rollback_begun',['run_id'=>$runId,'plan_digest'=>$plan->digest()]);return$transaction['result'];
	}

	public function applyCompensation(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan,PanelMigrationDefinition $definition,mixed $actor=null):PanelMigrationReport {
		return$this->batch($lease,$runId,$plan,$definition,$actor,true);
	}

	public function complete(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan):PanelMigrationReport {
		return$this->finish($lease,$runId,$plan,false);
	}
	public function completeRollback(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan):PanelMigrationReport {
		return$this->finish($lease,$runId,$plan,true);
	}

	public function fail(PanelMigrationLease $lease,string $runId,\Throwable $error):PanelMigrationReport {
		$runId=PanelMigrationIntegrity::identifier($runId,'run id');$now=$this->now();$transaction=$this->state->transaction(function(array &$payload)use($lease,$runId,$error,$now):PanelMigrationReport{$this->normalize($payload);$this->validateLease($payload,$lease,$now);$run=&$this->requiredRun($payload,$runId);if(in_array($run['status']??null,['completed','rolled_back'],true)){throw new PanelMigrationConflict('A terminal Panel migration run cannot be failed.');}$run['status']='failed';$run['errors']=[PanelMigrationIntegrity::redact($error)];$run['updated_at']=$now;return$this->reportFromRun($run);},'migration.run_failed',['run_id'=>$runId]);return$transaction['result'];
	}

	public function restoreSnapshot(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan):PanelMigrationReport {
		$runId=PanelMigrationIntegrity::identifier($runId,'run id');$now=$this->now();$transaction=$this->state->transaction(function(array &$payload)use($lease,$runId,$plan,$now):PanelMigrationReport{$this->normalize($payload);$this->validateLease($payload,$lease,$now);$run=&$this->requiredRun($payload,$runId);$this->assertRunPlan($run,$plan);$snapshot=$payload['snapshots'][(string)($run['snapshot_id']??'')]??null;if(!is_array($snapshot)||!is_array($snapshot['state']??null)){throw new PanelMigrationConflict('Panel migration backup snapshot is unavailable.');}$backup=PanelMigrationState::fromStored($snapshot['state']);if(!hash_equals((string)($snapshot['state_digest']??''),$backup->digest())){throw new PanelMigrationConflict('Panel migration backup snapshot failed integrity verification.');}$current=$this->stateFromPayload($payload,$lease->scope(),$lease->tenant());$restored=PanelMigrationState::make($backup->scope(),$backup->tenant(),$backup->version(),$backup->data(),$backup->applied(),$current->revision()+1);$payload['states'][$lease->scopeKey()]=$restored->stored();$run['expected_revision']=$restored->revision();$run['expected_digest']=$restored->digest();$run['status']='rolled_back';$run['rollback_mode']='snapshot_restore';$run['completed_at']=$now;$run['updated_at']=$now;return$this->reportFromRun($run);},'migration.snapshot_restored',['run_id'=>$runId,'plan_digest'=>$plan->digest()]);return$transaction['result'];
	}

	public function release(PanelMigrationLease $lease):void {$now=$this->now();$this->state->transaction(function(array &$payload)use($lease,$now):void{$this->normalize($payload);$this->validateLease($payload,$lease,$now);unset($payload['leases'][$lease->scopeKey()]);},'migration.lease_released',['scope'=>$lease->scope(),'tenant'=>$lease->tenant(),'fence'=>$lease->fence()]);}

	public function recoverExpired(int $limit=100):array {
		$limit=max(1,min(10000,$limit));$now=$this->now();$payload=$this->payload();$expired=[];foreach($payload['leases']as$key=>$state){if(is_array($state)&&strcmp((string)($state['expires_at']??''),$now)<=0){$expired[]=(string)$key;}}sort($expired,SORT_STRING);$reports=[];
		foreach(array_slice($expired,0,$limit)as$key){$transaction=$this->state->transaction(function(array &$payload)use($key,$now):array{$this->normalize($payload);$lease=$payload['leases'][$key]??null;if(!is_array($lease)||strcmp((string)($lease['expires_at']??''),$now)>0){return[];}unset($payload['leases'][$key]);$changed=[];foreach($payload['runs']as$runId=>&$run){if(is_array($run)&&$this->scopeKey((string)($run['scope']??''),isset($run['tenant'])?(string)$run['tenant']:null)===$key&&in_array($run['status']??null,['running','rolling_back'],true)){$run['status']='paused';$run['updated_at']=$now;$run['errors']=[['type'=>'lease_expired','message'=>'Execution paused after its exclusive lease expired.']];$changed[]=$this->reportFromRun($run);}}unset($run);return$changed;},'migration.lease_recovered',['scope_key'=>$key]);$reports=array_merge($reports,$transaction['result']);}
		return$reports;
	}

	public function report(string $runId):?PanelMigrationReport{$runId=PanelMigrationIntegrity::identifier($runId,'run id');$payload=$this->payload();$run=$payload['runs'][$runId]??null;return is_array($run)?$this->reportFromRun($run):null;}
	public function reportByPlan(string $planDigest):?PanelMigrationReport {if(preg_match('/^[a-f0-9]{64}$/D',$planDigest)!==1){return null;}$payload=$this->payload();foreach($payload['runs']as$run){if(is_array($run)&&($run['plan_digest']??null)===$planDigest){return$this->reportFromRun($run);}}return null;}
	public function snapshot(string $runId):?PanelMigrationSnapshot {$runId=PanelMigrationIntegrity::identifier($runId,'run id');$payload=$this->payload();$run=$payload['runs'][$runId]??null;$snapshot=is_array($run)?($payload['snapshots'][(string)($run['snapshot_id']??'')]??null):null;return is_array($snapshot)?$this->snapshotFromArray($snapshot):null;}
	/** @return array<string,mixed> */ public function changesSince(int $cursor=0,int $limit=100):array{return$this->state->changesSince($cursor,$limit);}
	/** @return array<string,mixed> */ public function manifest():array{$payload=$this->payload();$now=$this->now();$active=0;foreach($payload['leases']as$lease){if(is_array($lease)&&strcmp((string)($lease['expires_at']??''),$now)>0){$active++;}}return['type'=>'panel_atomic_migration_store','manifest_version'=>1,'state_schema_version'=>1,'scopes'=>count($payload['states']),'runs'=>count($payload['runs']),'snapshots'=>count($payload['snapshots']),'active_leases'=>$active,'cursor'=>$this->state->cursor(),'capabilities'=>['atomic_batches'=>true,'cross_process_lock'=>true,'exclusive_leases'=>true,'fencing'=>true,'lease_recovery'=>true,'resumable_checkpoints'=>true,'idempotency'=>true,'integrity_digests'=>true,'backup_snapshots'=>true,'compensation'=>true,'snapshot_restore'=>true,'change_feed'=>true,'raw_tokens_at_rest'=>false]];}
	/** @return array<string,mixed> */ public function jsonSerialize():array{return$this->manifest();}

	private function batch(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan,PanelMigrationDefinition $definition,mixed $actor,bool $rollback):PanelMigrationReport {
		$runId=PanelMigrationIntegrity::identifier($runId,'run id');$now=$this->now();$event=$rollback?'migration.compensation_batch':'migration.batch';
		$transaction=$this->state->transaction(function(array &$payload)use($lease,$runId,$plan,$definition,$actor,$rollback,$now):PanelMigrationReport{
			$this->normalize($payload);$this->validateLease($payload,$lease,$now);$run=&$this->requiredRun($payload,$runId);$this->assertRunPlan($run,$plan);$requiredStatus=$rollback?'rolling_back':'running';if(($run['status']??null)!==$requiredStatus){throw new PanelMigrationConflict("Panel migration run is not {$requiredStatus}.");}$state=$this->stateFromPayload($payload,$lease->scope(),$lease->tenant());$this->assertRunState($run,$state,$plan);
			$index=$rollback?(int)($run['rollback_index']??-1):(int)($run['step_index']??0);$step=$plan->steps()[$index]??null;if(!is_array($step)||(string)($step['id']??'')!==$definition->id()||!hash_equals((string)($step['definition_digest']??''),$definition->digest())){throw new PanelMigrationConflict('Panel migration definition does not match the current planned step.');}
			$checkpointKey=($rollback?'down:':'up:').$definition->id();$stored=is_array($run['checkpoints'][$checkpointKey]??null)?$run['checkpoints'][$checkpointKey]:[];$context=new PanelMigrationContext($plan->scope(),$plan->tenant(),$definition->id(),$rollback?'down':'up',$state->data(),$stored['cursor']??null,$definition->batchSize(),is_array($stored['checkpoint']??null)?$stored['checkpoint']:[],false,$actor);$batch=$rollback?$definition->compensate($context):$definition->migrate($context);if($batch->processed()>$definition->batchSize()){throw new \UnexpectedValueException('Panel migration handler exceeded its declared batch size.');}
			$applied=$state->applied();$version=$state->version();if($batch->done()){if($rollback){$version=$definition->from();$applied=array_values(array_filter($applied,static fn(string $id):bool=>$id!==$definition->id()));$run['rollback_index']=$index-1;}else{$version=$definition->to();if(!in_array($definition->id(),$applied,true)){$applied[]=$definition->id();sort($applied,SORT_STRING);}$run['step_index']=$index+1;}unset($run['checkpoints'][$checkpointKey]);}else{$run['checkpoints'][$checkpointKey]=['cursor'=>$batch->nextCursor(),'checkpoint'=>PanelMigrationIntegrity::redact($batch->checkpoint()),'processed'=>max(0,(int)($stored['processed']??0))+$batch->processed()];}
			$next=$state->evolved($version,$batch->data(),$applied);$payload['states'][$lease->scopeKey()]=$next->stored();$run['expected_revision']=$next->revision();$run['expected_digest']=$next->digest();$run['batch_count']=max(0,(int)($run['batch_count']??0))+1;$run['processed']=max(0,(int)($run['processed']??0))+$batch->processed();$run['updated_at']=$now;$receipt=['migration_id'=>$definition->id(),'direction'=>$rollback?'down':'up','batch'=>$batch->jsonSerialize(),'state_revision'=>$next->revision(),'state_digest'=>$next->digest(),'occurred_at'=>$now];$run['receipts'][]=PanelMigrationIntegrity::redact($receipt);if(count($run['receipts'])>2000){$run['receipts']=array_slice($run['receipts'],-2000);}return$this->reportFromRun($run);
		},$event,['run_id'=>$runId,'migration_id'=>$definition->id(),'direction'=>$rollback?'down':'up']);return$transaction['result'];
	}

	private function finish(PanelMigrationLease $lease,string $runId,PanelMigrationPlan $plan,bool $rollback):PanelMigrationReport {
		$runId=PanelMigrationIntegrity::identifier($runId,'run id');$now=$this->now();$transaction=$this->state->transaction(function(array &$payload)use($lease,$runId,$plan,$rollback,$now):PanelMigrationReport{$this->normalize($payload);$this->validateLease($payload,$lease,$now);$run=&$this->requiredRun($payload,$runId);$this->assertRunPlan($run,$plan);$state=$this->stateFromPayload($payload,$lease->scope(),$lease->tenant());$this->assertRunState($run,$state,$plan);if($rollback){if((int)($run['rollback_index']??-1)>=0||!$state->version()->equals($plan->source())){throw new PanelMigrationConflict('Panel migration compensation is not complete.');}$run['status']='rolled_back';$run['rollback_mode']='compensation';}else{if((int)($run['step_index']??0)!==count($plan->steps())||!$state->version()->equals($plan->target())){throw new PanelMigrationConflict('Panel migration plan is not fully applied.');}$run['status']='completed';}$run['completed_at']=$now;$run['updated_at']=$now;return$this->reportFromRun($run);},$rollback?'migration.rollback_completed':'migration.run_completed',['run_id'=>$runId,'plan_digest'=>$plan->digest()]);return$transaction['result'];
	}

	/** @return array<string,mixed> */ private function payload():array{$payload=$this->state->payload();$this->normalize($payload);return$payload;}
	/** @param array<string,mixed> $payload */ private function normalize(array &$payload):void{foreach(['states','leases','fences','runs','snapshots','idempotency']as$key){if(!isset($payload[$key])){$payload[$key]=[];}if(!is_array($payload[$key])){throw new \RuntimeException("Panel migration store has an invalid {$key} map.");}}}
	/** @param array<string,mixed> $payload */ private function stateFromPayload(array $payload,string $scope,?string $tenant):PanelMigrationState{$key=$this->scopeKey($scope,$tenant);$stored=$payload['states'][$key]??null;return is_array($stored)?PanelMigrationState::fromStored($stored):PanelMigrationState::make($scope,$tenant,PanelMigrationVersion::make('0.0.0',0));}
	private function scopeKey(string $scope,?string $tenant):string{return PanelMigrationIntegrity::identifier($scope,'scope').'|'.(PanelMigrationIntegrity::tenant($tenant)??'*');}
	/** @param array<string,mixed> $payload @return array<string,mixed> */ private function validateLease(array $payload,PanelMigrationLease $lease,string $now):array{$state=$payload['leases'][$lease->scopeKey()]??null;if(!is_array($state)){throw new PanelMigrationLeaseLost($lease->scopeKey());}$valid=(string)($state['owner']??'')===$lease->owner()&&(int)($state['fence']??0)===$lease->fence()&&isset($state['token_hash'])&&hash_equals((string)$state['token_hash'],hash('sha256',$lease->token()));if(!$valid){throw new PanelMigrationLeaseLost($lease->scopeKey(),'Panel migration lease was superseded.');}if(strcmp((string)($state['expires_at']??''),$now)<=0){throw new PanelMigrationLeaseLost($lease->scopeKey(),'Panel migration lease expired.');}return$state;}
	/** @return array<string,mixed> */ private function leaseState(PanelMigrationLease $lease):array{return['scope'=>$lease->scope(),'tenant'=>$lease->tenant(),'owner'=>$lease->owner(),'token_hash'=>hash('sha256',$lease->token()),'fence'=>$lease->fence(),'acquired_at'=>$lease->acquiredAt(),'renewed_at'=>$lease->renewedAt(),'expires_at'=>$lease->expiresAt()];}
	/** @param array<string,mixed> $payload @return array<string,mixed> */ private function &requiredRun(array &$payload,string $runId):array{if(!isset($payload['runs'][$runId])||!is_array($payload['runs'][$runId])){throw new \OutOfBoundsException("Panel migration run '{$runId}' does not exist.");}return$payload['runs'][$runId];}
	/** @param array<string,mixed> $run */ private function assertRunPlan(array $run,PanelMigrationPlan $plan):void{if(!hash_equals((string)($run['plan_digest']??''),$plan->digest())){throw new PanelMigrationStalePlan($plan->digest(),'Panel migration run belongs to a different plan.');}}
	private function assertPlanScope(PanelMigrationLease $lease,PanelMigrationPlan $plan):void{if($lease->scope()!==$plan->scope()||$lease->tenant()!==$plan->tenant()){throw new PanelMigrationConflict('Panel migration plan and lease scopes do not match.');}}
	/** @param array<string,mixed> $run */ private function assertRunState(array $run,PanelMigrationState $state,PanelMigrationPlan $plan):void{$this->assertRunPlan($run,$plan);if((int)($run['expected_revision']??-1)!==$state->revision()||!hash_equals((string)($run['expected_digest']??''),$state->digest())){throw new PanelMigrationStalePlan($plan->digest(),'Panel migration state changed after the last checkpoint.');}}
	/** @param array<string,mixed> $run */ private function reportFromRun(array $run):PanelMigrationReport{$snapshotId=(string)($run['snapshot_id']??'');return PanelMigrationReport::make(['run_id'=>$run['run_id']??null,'plan_digest'=>$run['plan_digest']??null,'idempotency_key'=>$run['idempotency_key']??null,'scope'=>$run['scope']??null,'tenant'=>$run['tenant']??null,'source'=>$run['source']??null,'target'=>$run['target']??null,'status'=>$run['status']??'failed','step_index'=>(int)($run['step_index']??0),'total_steps'=>count(is_array($run['steps']??null)?$run['steps']:[]),'rollback_index'=>$run['rollback_index']??null,'batch_count'=>(int)($run['batch_count']??0),'processed'=>(int)($run['processed']??0),'checkpoint_count'=>count(is_array($run['checkpoints']??null)?$run['checkpoints']:[]),'state_revision'=>(int)($run['expected_revision']??0),'state_digest'=>$run['expected_digest']??null,'receipts'=>$run['receipts']??[],'errors'=>$run['errors']??[],'resumes'=>(int)($run['resumes']??0),'snapshot_id'=>$snapshotId,'actor_fingerprint'=>$run['actor_fingerprint']??null,'rollback_mode'=>$run['rollback_mode']??null,'started_at'=>$run['started_at']??null,'updated_at'=>$run['updated_at']??null,'completed_at'=>$run['completed_at']??null]);}
	/** @param array<string,mixed> $snapshot */ private function snapshotFromArray(array $snapshot):PanelMigrationSnapshot{return new PanelMigrationSnapshot((string)($snapshot['id']??''),(string)($snapshot['run_id']??''),(string)($snapshot['scope']??''),isset($snapshot['tenant'])?(string)$snapshot['tenant']:null,(int)($snapshot['revision']??-1),(string)($snapshot['state_digest']??''),(string)($snapshot['created_at']??''));}
	/** @param array<string,mixed> $payload */ private function newRunId(array $payload):string{for($attempt=0;$attempt<10;$attempt++){$value=($this->runFactory)();if(!is_string($value)){throw new \UnexpectedValueException('Panel migration run id factory must return a string.');}$id=PanelMigrationIntegrity::identifier($value,'run id');if(!isset($payload['runs'][$id])){return$id;}}throw new PanelMigrationConflict('Panel migration run id factory could not produce a unique id.');}
	private function now():string{$value=($this->clock)();try{if($value instanceof \DateTimeInterface){$date=\DateTimeImmutable::createFromInterface($value);}elseif(is_int($value)){$date=new \DateTimeImmutable('@'.$value);}else{$date=new \DateTimeImmutable((string)$value);}return$date->setTimezone(new \DateTimeZone('UTC'))->format(DATE_ATOM);}catch(\Throwable){throw new \UnexpectedValueException('Panel migration clock returned an invalid time.');}}
	private function ttl(int $seconds):int{return max(5,min(3600,$seconds));}private function plusSeconds(string $time,int $seconds):string{return(new \DateTimeImmutable($time))->modify('+'.$seconds.' seconds')->format(DATE_ATOM);}
}
