<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** In-process branch/commit/review/three-way-merge layer above durable Studio revisions. */
final class PanelStudioBranchManager implements \JsonSerializable {
	/** @var array<string,array<string,mixed>> */private array $documents=[];private readonly ?\Closure $authorizer;private readonly \Closure $clock;
	public function __construct(?callable $authorizer=null,?callable $clock=null,private readonly int $requiredApprovals=1){if($requiredApprovals<0||$requiredApprovals>16){throw new \InvalidArgumentException('Studio merge approval quorum is invalid.');}$this->authorizer=$authorizer!==null?\Closure::fromCallable($authorizer):null;$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');}
	public function initialize(PanelStudioDocument $document,PanelStudioDefinition $definition,string|int $actorId):self {$actorId=PanelOperationsGuard::identifier($actorId,'Studio branch actor');$this->authorize('studio.branch.initialize',['tenant_id'=>$document->tenantId(),'document_id'=>$document->id(),'actor_id'=>$actorId]);$key=$this->key($document->tenantId(),$document->id());if(isset($this->documents[$key])){throw new \LogicException('Studio branch workspace is already initialized.');}$this->documents[$key]=['document'=>$document->jsonSerialize(),'branches'=>['main'=>$this->branchState($definition,$definition,0,$actorId,'Initialize main branch.')],'revision'=>1];return$this;}
	public function branch(string $tenantId,string $documentId,string $branch,string $from,string|int $actorId):self {$actorId=PanelOperationsGuard::identifier($actorId,'Studio branch actor');$branch=PanelOperationsGuard::name($branch,'Studio branch');$from=PanelOperationsGuard::name($from,'Studio source branch');if($branch==='main'){throw new \InvalidArgumentException('Studio main branch cannot be recreated.');}$this->authorize('studio.branch.create',compact('tenantId','documentId','branch','from','actorId'));$workspace=&$this->workspace($tenantId,$documentId);if(isset($workspace['branches'][$branch])||!isset($workspace['branches'][$from])){throw new \LogicException('Studio branch already exists or its source is missing.');}$source=$workspace['branches'][$from];$definition=PanelStudioDefinition::from($source['head']);$workspace['branches'][$branch]=$this->branchState($definition,$definition,0,$actorId,'Branch from '.$from.'.');$workspace['branches'][$branch]['parent']=$from;$workspace['revision']++;ksort($workspace['branches'],SORT_STRING);return$this;}
	public function commit(string $tenantId,string $documentId,string $branch,PanelStudioDefinition $definition,string $expectedHash,string|int $actorId,string $message):array {$actorId=PanelOperationsGuard::identifier($actorId,'Studio branch actor');$branch=PanelOperationsGuard::name($branch,'Studio branch');$message=PanelOperationsGuard::label($message,'Studio commit message',1024);if(preg_match('/^[a-f0-9]{64}$/D',$expectedHash)!==1){throw new \InvalidArgumentException('Studio expected head hash is invalid.');}$this->authorize('studio.branch.commit',compact('tenantId','documentId','branch','actorId'));$workspace=&$this->workspace($tenantId,$documentId);$state=$workspace['branches'][$branch]??null;if(!is_array($state)){throw new \OutOfBoundsException('Studio branch does not exist.');}$current=PanelStudioDefinition::from($state['head']);if(!hash_equals($current->hash(),$expectedHash)){throw new \LogicException('Studio branch head changed; rebase or merge before committing.');}if(hash_equals($definition->hash(),$current->hash())){throw new \LogicException('Studio commit contains no changes.');}$state['version']++;$commit=['id'=>'commit_'.substr(hash('sha256',$branch.'|'.$definition->hash().'|'.$state['version']),0,40),'version'=>$state['version'],'parent_hash'=>$current->hash(),'definition_hash'=>$definition->hash(),'definition'=>$definition->root(),'actor_hash'=>hash('sha256',$actorId),'message'=>$message,'created_at'=>$this->now()];$state['head']=$definition->root();$state['commits'][]=$commit;$workspace['branches'][$branch]=$state;$workspace['revision']++;return$commit;}
	/** @param list<string> $approvers */public function merge(string $tenantId,string $documentId,string $source,string $target,string $strategy,string|int $actorId,array $approvers=[]):PanelStudioMergeResult {$source=PanelOperationsGuard::name($source,'Studio source branch');$target=PanelOperationsGuard::name($target,'Studio target branch');if($source===$target||!in_array($strategy,['manual','ours','theirs'],true)){throw new \InvalidArgumentException('Studio merge branches or strategy are invalid.');}$actorId=PanelOperationsGuard::identifier($actorId,'Studio merge actor');$approvers=PanelOperationsGuard::identifiers($approvers,'Studio merge approver id');$independent=array_values(array_diff($approvers,[$actorId]));if(count($independent)<$this->requiredApprovals){throw new \LogicException('Studio merge requires independent review quorum.');}$this->authorize('studio.branch.merge',compact('tenantId','documentId','source','target','strategy','actorId'));$workspace=&$this->workspace($tenantId,$documentId);$sourceState=$workspace['branches'][$source]??null;$targetState=$workspace['branches'][$target]??null;if(!is_array($sourceState)||!is_array($targetState)){throw new \OutOfBoundsException('Studio merge branch does not exist.');}$base=$sourceState['base'];$sourceRoot=$sourceState['head'];$targetRoot=$targetState['head'];$conflicts=[];$merged=$this->threeWay($base,$sourceRoot,$targetRoot,'root',$conflicts,$strategy);$sourceDefinition=PanelStudioDefinition::from($sourceRoot);$targetDefinition=PanelStudioDefinition::from($targetRoot);$baseDefinition=PanelStudioDefinition::from($base);if($conflicts!==[]&&$strategy==='manual'){return new PanelStudioMergeResult($source,$target,$baseDefinition->hash(),$sourceDefinition->hash(),$targetDefinition->hash(),null,$conflicts,$strategy,$independent);}$definition=PanelStudioDefinition::from($merged);if(!hash_equals($definition->hash(),$targetDefinition->hash())){$targetState['version']++;$targetState['head']=$definition->root();$targetState['commits'][]=['id'=>'merge_'.substr(hash('sha256',$source.'|'.$target.'|'.$definition->hash().'|'.$targetState['version']),0,40),'version'=>$targetState['version'],'parent_hash'=>$targetDefinition->hash(),'definition_hash'=>$definition->hash(),'definition'=>$definition->root(),'actor_hash'=>hash('sha256',$actorId),'message'=>'Merge '.$source.' into '.$target.'.','created_at'=>$this->now(),'source_branch'=>$source,'source_hash'=>$sourceDefinition->hash(),'approver_hashes'=>array_map(static fn(string $approver):string=>hash('sha256',$approver),$independent)];$targetState['base']=$definition->root();$workspace['branches'][$target]=$targetState;$workspace['branches'][$source]['base']=$definition->root();$workspace['revision']++;}return new PanelStudioMergeResult($source,$target,$baseDefinition->hash(),$sourceDefinition->hash(),$targetDefinition->hash(),$definition,$conflicts,$strategy,$independent);}
	public function head(string $tenantId,string $documentId,string $branch='main'):PanelStudioDefinition {$branch=PanelOperationsGuard::name($branch,'Studio branch');$workspace=$this->workspaceValue($tenantId,$documentId);$state=$workspace['branches'][$branch]??null;if(!is_array($state)){throw new \OutOfBoundsException('Studio branch does not exist.');}return PanelStudioDefinition::from($state['head']);}
	/** @return list<array<string,mixed>> */public function branches(string $tenantId,string $documentId):array {$workspace=$this->workspaceValue($tenantId,$documentId);$result=[];foreach($workspace['branches']as$name=>$state){$result[]=['name'=>$name,'parent'=>$state['parent']??null,'version'=>$state['version'],'head_hash'=>PanelStudioDefinition::from($state['head'])->hash(),'base_hash'=>PanelStudioDefinition::from($state['base'])->hash(),'commit_count'=>count($state['commits'])];}return$result;}
	/** @return array<string,mixed> */public function checkpoint():array{return['type'=>'panel_studio_branch_checkpoint','version'=>1,'documents'=>$this->documents,'required_approvals'=>$this->requiredApprovals,'fingerprint'=>PanelOperationsGuard::digest($this->documents)];}
	/** @param array<string,mixed> $checkpoint */public function restore(array $checkpoint):self {if(($checkpoint['type']??null)!=='panel_studio_branch_checkpoint'||($checkpoint['version']??null)!==1||($checkpoint['required_approvals']??null)!==$this->requiredApprovals||!is_array($checkpoint['documents']??null)||!is_string($checkpoint['fingerprint']??null)||!hash_equals($checkpoint['fingerprint'],PanelOperationsGuard::digest($checkpoint['documents']))){throw new \UnexpectedValueException('Studio branch checkpoint is invalid.');}foreach($checkpoint['documents']as$workspace){if(!is_array($workspace)||!is_array($workspace['document']??null)||!is_array($workspace['branches']??null)){throw new \UnexpectedValueException('Studio branch workspace checkpoint is invalid.');}foreach($workspace['branches']as$state){PanelStudioDefinition::from($state['base']);PanelStudioDefinition::from($state['head']);}}$this->documents=$checkpoint['documents'];return$this;}
	public function jsonSerialize():array {$branches=0;$commits=0;foreach($this->documents as$workspace){$branches+=count($workspace['branches']);foreach($workspace['branches']as$branch){$commits+=count($branch['commits']);}}return PanelManifestContract::stamp(['type'=>'panel_studio_branch_manager_manifest','version'=>1,'workspace_count'=>count($this->documents),'branch_count'=>$branches,'commit_count'=>$commits,'required_approvals'=>$this->requiredApprovals,'default_deny'=>$this->authorizer===null,'capabilities'=>['branches'=>true,'optimistic_commits'=>true,'three_way_merge'=>true,'path_conflicts'=>true,'manual_resolution'=>true,'ours_theirs_resolution'=>true,'independent_review'=>true,'checkpoints'=>true]]);}
	/** @return array<string,mixed> */private function branchState(PanelStudioDefinition $base,PanelStudioDefinition $head,int $version,string $actorId,string $message):array{return['base'=>$base->root(),'head'=>$head->root(),'version'=>$version,'parent'=>null,'commits'=>[['id'=>'commit_'.substr(hash('sha256',$head->hash().'|'.$version),0,40),'version'=>$version,'parent_hash'=>null,'definition_hash'=>$head->hash(),'definition'=>$head->root(),'actor_hash'=>hash('sha256',$actorId),'message'=>$message,'created_at'=>$this->now()]]];}
	/** @return array<string,mixed> */private function &workspace(string $tenantId,string $documentId):array {$key=$this->key($tenantId,$documentId);if(!isset($this->documents[$key])){throw new \OutOfBoundsException('Studio branch workspace is not initialized.');}return$this->documents[$key];}
	/** @return array<string,mixed> */private function workspaceValue(string $tenantId,string $documentId):array {$key=$this->key($tenantId,$documentId);if(!isset($this->documents[$key])){throw new \OutOfBoundsException('Studio branch workspace is not initialized.');}return$this->documents[$key];}
	private function key(string $tenantId,string $documentId):string {PanelStudioDocument::scope($tenantId,'tenant');PanelStudioDocument::scope($documentId,'document');return$tenantId.':'.$documentId;}
	private function threeWay(mixed $base,mixed $source,mixed $target,string $path,array &$conflicts,string $strategy):mixed {if($this->valueDigest($source)===$this->valueDigest($target)){return$source;}if($this->valueDigest($source)===$this->valueDigest($base)){return$target;}if($this->valueDigest($target)===$this->valueDigest($base)){return$source;}if(is_array($base)&&is_array($source)&&is_array($target)&&!array_is_list($base)&&!array_is_list($source)&&!array_is_list($target)){$result=[];$keys=array_unique(array_merge(array_keys($base),array_keys($source),array_keys($target)));sort($keys,SORT_STRING);$missing=new \stdClass();foreach($keys as$key){$value=$this->threeWay($base[$key]??$missing,$source[$key]??$missing,$target[$key]??$missing,$path.'.'.$key,$conflicts,$strategy);if(!$value instanceof \stdClass){$result[$key]=$value;}}return$result;}$conflicts[]=['path'=>$path,'base_digest'=>$this->valueDigest($base),'source_digest'=>$this->valueDigest($source),'target_digest'=>$this->valueDigest($target)];return$strategy==='theirs'?$source:$target;}
	private function valueDigest(mixed $value):string {return PanelOperationsGuard::digest($value instanceof \stdClass?['missing'=>true]:$value);}
	/** @param array<string,mixed> $context */private function authorize(string $ability,array $context):void {if($this->authorizer===null){throw new \LogicException('Studio branch authorization is not configured.');}try{$result=($this->authorizer)($ability,$context,$this);$allowed=$result===true||($result instanceof PanelPolicyDecision&&$result->allowed())||($result instanceof PanelSecurityDecision&&$result->allowed());}catch(\Throwable $error){throw new \LogicException('Studio branch authorization failed closed.',0,$error);}if(!$allowed){throw new \LogicException('Studio branch operation is not authorized.');}}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Studio branch clock must return an instant.');}return PanelOperationsGuard::instant($value);}
}
