<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2025 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
return [
	'default_disk'=>'local',
	'disks'=>[
		'local'=>[
			'driver'=>'local',
			'root'=>ROOTPATH['dataphyre'].'storage',
			'url'=>null,
			'signing_key'=>'',
			'max_bytes'=>104857600,
			'allowed_extensions'=>[],
			'allowed_mime_types'=>[],
			'encryption'=>[
				'enabled'=>false,
				'key'=>'base64:REPLACE_WITH_32_RANDOM_BYTES_ENCODED_ONCE',
			],
		],
		'testing'=>[
			'driver'=>'memory',
			'prefix'=>'tests',
		],
		'vestra'=>[
			'driver'=>'vestra',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-vestra-manifest.json',
			'tenant'=>'shopiro-store-content',
		],
		'vestra_s3'=>[
			'driver'=>'s3',
			'endpoint'=>'https://vestra.example.com/s3',
			'bucket'=>'store-content',
			'region'=>'auto',
			'access_key'=>'',
			'secret_key'=>'',
			'style'=>'path',
			'public_url'=>null,
		],
		's3'=>[
			'driver'=>'s3',
			'endpoint'=>'https://s3.amazonaws.com',
			'bucket'=>'your-bucket',
			'region'=>'us-east-1',
			'access_key'=>'',
			'secret_key'=>'',
			'style'=>'path',
			'public_url'=>null,
			'max_bytes'=>0,
			'allowed_extensions'=>[],
			'allowed_mime_types'=>[],
		],
		'r2'=>[
			'driver'=>'r2',
			'endpoint'=>'https://ACCOUNT_ID.r2.cloudflarestorage.com',
			'bucket'=>'your-bucket',
			'region'=>'auto',
			'access_key'=>'',
			'secret_key'=>'',
			'style'=>'path',
			'public_url'=>'https://cdn.example.com',
		],
		'mirror'=>[
			'driver'=>'mirror',
			'read'=>'local',
			'writes'=>['local', 's3'],
		],
		'tenant_media'=>[
			'driver'=>'scoped',
			'disk'=>'local',
			'prefix'=>'tenants/example/media',
		],
		'public_assets_readonly'=>[
			'driver'=>'readonly',
			'disk'=>'local',
		],
		'tenant_uploads_limited'=>[
			'driver'=>'quota',
			'disk'=>'tenant_media',
			'max_bytes'=>10737418240,
			'max_objects'=>100000,
		],
		'resilient_media'=>[
			'driver'=>'failover',
			'reads'=>['s3', 'local'],
			'write'=>'s3',
		],
		'hot_media'=>[
			'driver'=>'cached',
			'disk'=>'s3',
			'cache'=>'local',
			'prefix'=>'_dataphyre_cache/media',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-hot-media.json',
			'ttl'=>300,
			'write_through'=>true,
		],
		'compressed_exports'=>[
			'driver'=>'compressed',
			'disk'=>'s3',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-compressed-exports.json',
			'level'=>6,
			'min_bytes'=>1024,
			'skip_extensions'=>['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'mp4', 'pdf'],
		],
		'retained_records'=>[
			'driver'=>'retention',
			'disk'=>'versioned_documents',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-retention-records.json',
			'retain_for'=>'7 years',
			'legal_hold'=>false,
		],
		'temporary_exports'=>[
			'driver'=>'lifecycle',
			'disk'=>'compressed_exports',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-lifecycle-exports.json',
			'rules'=>[
				['prefix'=>'exports/tmp', 'delete_after'=>'24 hours'],
				['prefix'=>'exports/monthly', 'delete_after'=>'18 months', 'extensions'=>['csv', 'json']],
			],
		],
		'scanned_uploads'=>[
			'driver'=>'scanned',
			'disk'=>'tenant_uploads_limited',
			'quarantine_disk'=>'local',
			'quarantine_prefix'=>'_dataphyre_quarantine/uploads',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-scan-uploads.json',
			'scanner_command'=>'clamscan --no-summary {file}',
			'require_scanner'=>false,
			'deny_patterns'=>[],
		],
		'tagged_media'=>[
			'driver'=>'tagged',
			'disk'=>'scanned_uploads',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-tags-media.json',
		],
		'evented_media'=>[
			'driver'=>'evented',
			'disk'=>'tagged_media',
			'log'=>ROOTPATH['dataphyre'].'logs/storage-events.jsonl',
			'listeners'=>[],
		],
		'policy_media'=>[
			'driver'=>'policy',
			'disk'=>'evented_media',
			'default_allow'=>true,
			'rules'=>[
				['effect'=>'deny', 'actions'=>['delete', 'write'], 'prefix'=>'protected'],
				['effect'=>'deny', 'actions'=>['write'], 'prefix'=>'uploads', 'extensions'=>['php', 'phtml', 'phar']],
			],
		],
		'throttled_media'=>[
			'driver'=>'rate_limited',
			'disk'=>'policy_media',
			'state'=>ROOTPATH['dataphyre'].'cache/storage-rate-limits-media.json',
			'limits'=>[
				'write'=>['limit'=>120, 'window'=>'1 minute'],
				'temporary_url'=>['limit'=>600, 'window'=>'1 minute'],
			],
		],
		'versioned_documents'=>[
			'driver'=>'versioned',
			'disk'=>'local',
			'prefix'=>'_dataphyre_versions/documents',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-versions.json',
			'keep'=>25,
		],
		'deduplicated_media'=>[
			'driver'=>'deduplicated',
			'disk'=>'local',
			'prefix'=>'_dataphyre_blobs/media',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-deduplicated-media.json',
			'algorithm'=>'sha256',
		],
		'verified_documents'=>[
			'driver'=>'integrity',
			'disk'=>'versioned_documents',
			'manifest'=>ROOTPATH['dataphyre'].'cache/storage-integrity.json',
			'algorithm'=>'sha256',
		],
		'audited_documents'=>[
			'driver'=>'audit',
			'disk'=>'verified_documents',
			'log'=>ROOTPATH['dataphyre'].'logs/storage-audit.jsonl',
		],
	],
];
