<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/**
 * Durable signal -> proposal -> approval -> command -> outcome feedback loop.
 *
 * Command inputs, proposer identities, idempotency keys, and approval
 * attestations are encrypted at rest. Public projections contain only bounded
 * summaries and one-way identity hashes.
 */
final class PanelClosedLoopIntelligence implements \JsonSerializable {
	private readonly PanelAtomicSnapshotStore $store;
	private readonly \Closure $clock;
	/** @var array<string,string> */private readonly array $keys;
	/** @var array<string,int> */private readonly array $approvalThresholds;

	/**
	 * @param array<string,string> $trustedKeys
	 * @param array<string,int> $approvalThresholds
	 */
	public function __construct(
		string $root,
		private readonly PanelCommandFabric $fabric,
		private readonly PanelPolicyControlPlane $policy,
		private readonly PanelCommandPayloadCodec $codec,
		array $trustedKeys,
		private readonly string $currentKeyId,
		array $approvalThresholds=[],
		?callable $clock=null,
		private readonly int $snapshotRetention=2048,
		private readonly int $approvalTtlSeconds=3600,
		private readonly int $dispatchStaleSeconds=300,
		private readonly int $maximumEntries=10000,
	){
		if($fabric->policy()!==$policy){throw new \InvalidArgumentException('Closed-loop intelligence and command fabric must share one policy control plane.');}
		$keys=[];foreach($trustedKeys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'intelligence trust key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Intelligence trust keys require at least 32 bytes.');}$keys[$id]=$key;}
		if(!isset($keys[$currentKeyId])){throw new \InvalidArgumentException('The current intelligence trust key is unavailable.');}$this->keys=$keys;
		$defaults=['low'=>0,'medium'=>1,'high'=>2,'critical'=>2];$thresholds=[];foreach($defaults as$risk=>$default){$value=$approvalThresholds[$risk]??$default;if(!is_int($value)||$value<0||$value>16){throw new \InvalidArgumentException('Intelligence approval thresholds must be integers between zero and sixteen.');}$thresholds[$risk]=$value;}if(array_diff(array_keys($approvalThresholds),array_keys($defaults))!==[]){throw new \InvalidArgumentException('Intelligence approval threshold risk is invalid.');}$this->approvalThresholds=$thresholds;
		if($snapshotRetention<8||$approvalTtlSeconds<60||$approvalTtlSeconds>604800||$dispatchStaleSeconds<0||$dispatchStaleSeconds>604800||$maximumEntries<100||$maximumEntries>1000000){throw new \InvalidArgumentException('Closed-loop intelligence retention or timing bounds are invalid.');}
		$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');
		$initial=$this->signedState(['schema'=>'panel_closed_loop_intelligence','version'=>1,'revision'=>0,'signals'=>[],'proposals'=>[],'feedback'=>[],'idempotency'=>['proposals'=>[],'feedback'=>[]]]);
		$this->store=new PanelAtomicSnapshotStore($root,'panel.closed-loop-intelligence.v1',$initial,$snapshotRetention);
		$this->verifyIntegrity();
	}

	public function fabric():PanelCommandFabric{return$this->fabric;}
	public function policy():PanelPolicyControlPlane{return$this->policy;}
	public function store():PanelAtomicSnapshotStore{return$this->store;}

	/** @param array<string,mixed> $evidence */
	public function issueSignal(string $kind,string $tenantId,string $source,string $subjectType,string|int $subjectId,string $summary,string $severity,int $confidenceBasisPoints,array $evidence=[],string|int|\DateTimeInterface|null $observedAt=null,int $ttlSeconds=900):PanelIntelligenceSignal {
		if($ttlSeconds<30||$ttlSeconds>604800){throw new \InvalidArgumentException('Intelligence signal TTL is invalid.');}$observedAt=PanelOperationsGuard::instant($observedAt??$this->now());$expiresAt=$this->after($observedAt,$ttlSeconds);return PanelIntelligenceSignal::sign($kind,$tenantId,$source,$subjectType,$subjectId,$summary,$severity,$confidenceBasisPoints,$evidence,$observedAt,$expiresAt,$this->currentKeyId,$this->keys[$this->currentKeyId]);
	}

	public function recordSignal(PanelIntelligenceSignal $signal,PanelPolicyRequest|array $request):PanelIntelligenceSignal {
		$request=$this->request($request);$this->assertTenant($request,$signal->tenantId());$this->authorize($request,'intelligence.signal.record',$signal->tenantId(),'intelligence_signal',$signal->id(),$this->riskForSeverity($signal->severity()),['kind'=>$signal->kind(),'source'=>$signal->source(),'severity'=>$signal->severity(),'confidence_basis_points'=>$signal->confidenceBasisPoints()]);
		if(!$signal->verify($this->keys,$this->now())||!$signal->hasEvidencePayload()){throw new \LogicException('Intelligence signal is expired, future-dated, untrusted, or missing its evidence payload.');}
		$stored=['manifest'=>$signal->jsonSerialize(),'sealed'=>$this->codec->seal(['evidence'=>$signal->evidence()],$this->signalContext($signal))];
		$result=$this->mutate(function(array &$state)use($signal,$stored):array{$existing=$state['signals'][$signal->id()]??null;if(is_array($existing)){if(!hash_equals($this->storedSignal($existing)->digest(),$signal->digest())){throw new \LogicException('Intelligence signal identity conflict.');}return$existing;}if(count($state['signals'])>=$this->maximumEntries){throw new \LengthException('Intelligence signal retention limit is reached.');}$state['signals'][$signal->id()]=$stored;ksort($state['signals'],SORT_STRING);return$state['signals'][$signal->id()];},'intelligence.signal.recorded',['signal_id'=>$signal->id(),'tenant_id'=>$signal->tenantId(),'kind'=>$signal->kind()]);return$this->storedSignal($result);
	}

	/** @param array<string,mixed> $evidence */
	public function observe(string $kind,string $tenantId,string $source,string $subjectType,string|int $subjectId,string $summary,string $severity,int $confidenceBasisPoints,PanelPolicyRequest|array $request,array $evidence=[],string|int|\DateTimeInterface|null $observedAt=null,int $ttlSeconds=900):PanelIntelligenceSignal {return$this->recordSignal($this->issueSignal($kind,$tenantId,$source,$subjectType,$subjectId,$summary,$severity,$confidenceBasisPoints,$evidence,$observedAt,$ttlSeconds),$request);}

	/** @param array<string,mixed> $input */
	public function propose(string $signalId,string $command,string $ability,array $input,string $risk,string $reason,PanelPolicyRequest|array $request,string $idempotencyKey,int $requestedApprovals=0,?int $expectedRevision=null):PanelIntelligenceProposal {
		$request=$this->request($request);$signal=$this->signal($signalId);$this->assertTenant($request,$signal->tenantId());$risk=strtolower(trim($risk));if(!isset($this->approvalThresholds[$risk])||$requestedApprovals<0||$requestedApprovals>16||($expectedRevision!==null&&$expectedRevision<0)){throw new \InvalidArgumentException('Intelligence proposal risk, approval count, or expected revision is invalid.');}$command=PanelOperationsGuard::name($command,'intelligence proposal command',160);PanelOperationsGuard::abilityPatterns([$ability],'intelligence proposal ability');$input=PanelOperationsGuard::object($input,'intelligence proposal input',4096);PanelOperationsGuard::canonical($input);$reason=PanelOperationsGuard::label($reason,'intelligence proposal reason',2048);$idempotencyHash=$this->idempotency($signal->tenantId(),$request->actorId(),$idempotencyKey,'proposal');
		$decision=$this->authorize($request,'intelligence.proposal.create',$signal->tenantId(),'intelligence_signal',$signal->id(),$risk,['signal_kind'=>$signal->kind(),'signal_severity'=>$signal->severity(),'command'=>$command,'command_ability'=>$ability]);$required=max($requestedApprovals,$this->approvalThresholds[$risk],$decision->approvalCount());$inputDigest=PanelOperationsGuard::digest($input);$fingerprint=PanelOperationsGuard::digest(['signal_id'=>$signal->id(),'signal_digest'=>$signal->digest(),'command'=>$command,'ability'=>$ability,'input_digest'=>$inputDigest,'risk'=>$risk,'reason'=>$reason,'required_approvals'=>$required,'expected_revision'=>$expectedRevision]);
		$state=$this->state();$known=$state['idempotency']['proposals'][$idempotencyHash]??null;if(is_array($known)){if(!hash_equals((string)($known['fingerprint']??''),$fingerprint)){throw new \LogicException('Intelligence proposal idempotency key conflict.');}return$this->proposal((string)$known['id']);}
		if(!$signal->verify($this->keys,$this->now())){throw new \LogicException('Intelligence signal expired before a new proposal could be created.');}
		$id='proposal_'.substr(hash('sha256',$idempotencyHash."\0".$fingerprint),0,40);$createdAt=$this->now();$proposal=PanelIntelligenceProposal::create($id,$signal,hash('sha256',$request->actorId()),$command,$ability,$inputDigest,$risk,$reason,$required,$createdAt);$sealed=$this->codec->seal(['input'=>$input,'proposer_id'=>$request->actorId(),'expected_revision'=>$expectedRevision],$this->proposalContext($proposal));
		$result=$this->mutate(function(array &$state)use($proposal,$sealed,$idempotencyHash,$fingerprint):array{$known=$state['idempotency']['proposals'][$idempotencyHash]??null;if(is_array($known)){if(!hash_equals((string)($known['fingerprint']??''),$fingerprint)){throw new \LogicException('Intelligence proposal idempotency key conflict.');}return$state['proposals'][(string)$known['id']]['manifest'];}if(count($state['proposals'])>=$this->maximumEntries){throw new \LengthException('Intelligence proposal retention limit is reached.');}$state['proposals'][$proposal->id()]=['manifest'=>$proposal->jsonSerialize(),'sealed'=>$sealed,'idempotency_hash'=>$idempotencyHash,'fingerprint'=>$fingerprint,'approvals'=>[],'dispatch'=>null,'feedback_ids'=>[]];$state['idempotency']['proposals'][$idempotencyHash]=['id'=>$proposal->id(),'fingerprint'=>$fingerprint];ksort($state['proposals'],SORT_STRING);ksort($state['idempotency']['proposals'],SORT_STRING);return$proposal->jsonSerialize();},'intelligence.proposal.created',['proposal_id'=>$proposal->id(),'signal_id'=>$signal->id(),'tenant_id'=>$signal->tenantId(),'command'=>$command,'risk'=>$risk]);return PanelIntelligenceProposal::hydrate($result);
	}

	public function approve(string $proposalId,PanelPolicyRequest|array $request,?int $ttlSeconds=null):PanelIntelligenceApproval {
		$request=$this->request($request);$proposal=$this->proposal($proposalId);$this->assertTenant($request,$proposal->tenantId());$this->authorize($request,'intelligence.proposal.approve',$proposal->tenantId(),'intelligence_proposal',$proposal->id(),$proposal->risk(),['command'=>$proposal->command(),'signal_id'=>$proposal->signalId()]);if($proposal->terminal()||$proposal->status()==='dispatching'){throw new \LogicException('Intelligence proposal can no longer be approved.');}$private=$this->proposalPrivate($proposal);if(hash_equals((string)$private['proposer_id'],$request->actorId())){throw new \LogicException('Intelligence proposal authors cannot approve their own proposal.');}$ttl=$ttlSeconds??$this->approvalTtlSeconds;if($ttl<60||$ttl>604800){throw new \InvalidArgumentException('Intelligence approval TTL is invalid.');}$now=$this->now();$approval=PanelIntelligenceApproval::sign($proposal,$request->actorId(),$now,$this->after($now,$ttl),$this->currentKeyId,$this->keys[$this->currentKeyId]);$hash=$approval->approverHash();
		$stored=['manifest'=>$approval->jsonSerialize(),'sealed'=>$this->codec->seal(['approver_id'=>$approval->approverId()],$this->approvalContext($approval))];
		$result=$this->mutate(function(array &$state)use($proposal,$approval,$hash,$stored):array{$entry=&$this->proposalEntry($state,$proposal->id());$current=PanelIntelligenceProposal::hydrate($entry['manifest']);if($current->revision()!==$proposal->revision()){throw new \LogicException('Intelligence proposal changed before approval could be committed.');}if($current->terminal()||$current->status()==='dispatching'){throw new \LogicException('Intelligence proposal can no longer be approved.');}$existing=$entry['approvals'][$hash]??null;if(is_array($existing)){try{$known=$this->storedApproval($current,$existing);if($known->verify($this->keys,$current,$this->now())){return$existing;}}catch(\Throwable){}}$entry['approvals'][$hash]=$stored;ksort($entry['approvals'],SORT_STRING);$hashes=array_keys($entry['approvals']);$status=count($hashes)>=$current->requiredApprovals()?'ready':'awaiting_approval';$entry['manifest']=$current->evolve($status,$hashes,$current->revision()+1,$current->dispatchAttempts(),$current->feedbackCount(),$this->now(),$current->receipt(),$current->rejection())->jsonSerialize();return$entry['approvals'][$hash];},'intelligence.proposal.approved',['proposal_id'=>$proposal->id(),'tenant_id'=>$proposal->tenantId(),'approver_hash'=>$hash]);return$this->storedApproval($this->proposal($proposal->id()),$result);
	}

	public function reject(string $proposalId,string $reason,PanelPolicyRequest|array $request):PanelIntelligenceProposal {
		$request=$this->request($request);$proposal=$this->proposal($proposalId);$this->assertTenant($request,$proposal->tenantId());$this->authorize($request,'intelligence.proposal.reject',$proposal->tenantId(),'intelligence_proposal',$proposal->id(),$proposal->risk(),['command'=>$proposal->command(),'signal_id'=>$proposal->signalId()]);$reason=PanelOperationsGuard::label($reason,'intelligence rejection reason',1024);
		$result=$this->mutate(function(array &$state)use($proposal,$request,$reason):array{$entry=&$this->proposalEntry($state,$proposal->id());$current=PanelIntelligenceProposal::hydrate($entry['manifest']);if($current->revision()!==$proposal->revision()){throw new \LogicException('Intelligence proposal changed before rejection could be committed.');}if($current->terminal()||$current->status()==='dispatching'){throw new \LogicException('Intelligence proposal can no longer be rejected.');}$rejection=['reason'=>$reason,'actor_hash'=>hash('sha256',$request->actorId()),'rejected_at'=>$this->now()];$entry['manifest']=$current->evolve('rejected',$current->approverHashes(),$current->revision()+1,$current->dispatchAttempts(),$current->feedbackCount(),$this->now(),null,$rejection)->jsonSerialize();return$entry['manifest'];},'intelligence.proposal.rejected',['proposal_id'=>$proposal->id(),'tenant_id'=>$proposal->tenantId()]);return PanelIntelligenceProposal::hydrate($result);
	}

	public function dispatch(string $proposalId,PanelPolicyRequest|array $request,bool $confirmed=false,?int $expectedProposalRevision=null,?int $staleAfterSeconds=null):PanelCommandReceipt {
		$request=$this->request($request);$proposal=$this->proposal($proposalId);$this->assertTenant($request,$proposal->tenantId());$decision=$this->authorize($request,'intelligence.proposal.dispatch',$proposal->tenantId(),'intelligence_proposal',$proposal->id(),$proposal->risk(),['command'=>$proposal->command(),'command_ability'=>$proposal->ability(),'signal_id'=>$proposal->signalId()]);
		if($proposal->status()==='rejected'){throw new \LogicException('Rejected intelligence proposal cannot be dispatched.');}
		if(in_array($proposal->status(),['succeeded','failed','denied'],true)){return$this->terminalReceipt($proposal);}
		$stale=$staleAfterSeconds??$this->dispatchStaleSeconds;if($stale<0||$stale>604800){throw new \InvalidArgumentException('Intelligence dispatch stale threshold is invalid.');}
		if($proposal->status()==='dispatching'){$command=$this->reclaimDispatch($proposal,$stale);return$this->executeAndFinalize($proposal->id(),$command,$stale);}
		if($expectedProposalRevision!==null&&$expectedProposalRevision!==$proposal->revision()){throw new \LogicException('Intelligence proposal revision conflict.');}
		$signal=$this->signal($proposal->signalId());if(!$signal->verify($this->keys,$this->now())){throw new \LogicException('Intelligence proposal signal expired before dispatch.');}$private=$this->proposalPrivate($proposal);$valid=$this->validApprovals($proposal);$separation=($decision->obligations()['separation_of_duties']??false)===true;$required=max($proposal->requiredApprovals(),$decision->approvalCount(),$separation?1:0);if(count($valid)<$required){throw new \LogicException('Intelligence proposal does not have enough current independent approvals.');}if($decision->confirmationRequired()&&!$confirmed){throw new \LogicException('Intelligence proposal dispatch requires explicit confirmation.');}if($separation&&isset($valid[$request->actorId()])){throw new \LogicException('Intelligence proposal dispatcher cannot be one of its approvers.');}
		$metadata=['closed_loop_intelligence'=>true,'intelligence_proposal_id'=>$proposal->id(),'intelligence_signal_id'=>$signal->id(),'intelligence_signal_kind'=>$signal->kind(),'confirmed'=>$confirmed,'mfa_level'=>max(0,(int)($request->context()['mfa_level']??0)),'dry_run'=>($request->context()['dry_run']??false)===true,'cost_micros'=>max(0,(int)($request->context()['cost_micros']??0))];
		$command=new PanelCommandEnvelope($proposal->command(),$proposal->ability(),$proposal->tenantId(),$request->actorId(),'intelligence:'.$proposal->id(),$private['input'],$proposal->risk(),$request->roles(),$request->permissions(),$proposal->id(),$signal->id(),$private['expected_revision'],$metadata,$this->now());
		if($valid!==[]){$expiry=min(array_map(static fn(PanelIntelligenceApproval $approval):string=>$approval->expiresAt(),array_values($valid)));$attestation=PanelCommandApprovalAttestation::sign($command->executionTarget(),'intelligence',$proposal->id(),array_keys($valid),$this->now(),$expiry,$this->currentKeyId,$this->keys[$this->currentKeyId]);$command=$command->withEvidence(['approval_attestation'=>$attestation->jsonSerialize()]);}
		$targetDecision=$this->fabric->decisionFor($command)->assertAllowed();$targetObligations=$this->fabric->obligationVerifier()->verify($command,$targetDecision);if(!$targetObligations->satisfied()){throw new \LogicException('Intelligence command policy obligations are not satisfied.');}
		$bundle=$this->codec->seal(['manifest'=>$command->jsonSerialize(),'sealed'=>$command->sealedPayload()],$this->dispatchContext($proposal->id(),$command->fingerprint()));
		$this->mutate(function(array &$state)use($proposal,$command,$bundle):void{$entry=&$this->proposalEntry($state,$proposal->id());$current=PanelIntelligenceProposal::hydrate($entry['manifest']);if($current->revision()!==$proposal->revision()||!in_array($current->status(),['ready','awaiting_approval'],true)){throw new \LogicException('Intelligence proposal changed before dispatch could be claimed.');}$entry['dispatch']=['command_fingerprint'=>$command->fingerprint(),'idempotency_hash'=>$command->idempotencyHash(),'sealed'=>$bundle,'claimed_at'=>$this->now(),'attempts'=>1];$entry['manifest']=$current->evolve('dispatching',$current->approverHashes(),$current->revision()+1,$current->dispatchAttempts()+1,$current->feedbackCount(),$this->now(),null,null)->jsonSerialize();},'intelligence.proposal.dispatch_claimed',['proposal_id'=>$proposal->id(),'tenant_id'=>$proposal->tenantId(),'command'=>$proposal->command()]);return$this->executeAndFinalize($proposal->id(),$command);
	}

	/** @return array{resumed:list<array<string,mixed>>,errors:array<string,string>} */
	public function recoverStale(PanelPolicyRequest|array $request,?int $staleAfterSeconds=null,int $limit=100):array {
		$request=$this->request($request);$tenantId=$request->tenantId();if($tenantId===null){throw new \LogicException('Intelligence recovery requires an explicit tenant boundary.');}$stale=$staleAfterSeconds??$this->dispatchStaleSeconds;if($stale<0||$stale>604800){throw new \InvalidArgumentException('Intelligence recovery stale threshold is invalid.');}$limit=max(1,min(1000,$limit));$state=$this->state();$candidates=[];foreach($state['proposals']as$id=>$entry){if(!is_array($entry)||!is_array($entry['manifest']??null)){continue;}$proposal=PanelIntelligenceProposal::hydrate($entry['manifest']);if($proposal->tenantId()===$tenantId&&$proposal->status()==='dispatching'&&$this->isStale((string)($entry['dispatch']['claimed_at']??''),$stale)){$candidates[$id]=$proposal;}}uasort($candidates,static fn(PanelIntelligenceProposal $left,PanelIntelligenceProposal $right):int=>[$left->updatedAt(),$left->id()]<=>[$right->updatedAt(),$right->id()]);$resumed=[];$errors=[];foreach(array_slice($candidates,0,$limit,true)as$id=>$proposal){try{$this->authorize($request,'intelligence.proposal.recover',$proposal->tenantId(),'intelligence_proposal',$proposal->id(),$proposal->risk(),['command'=>$proposal->command()]);$command=$this->reclaimDispatch($proposal,$stale);$resumed[]=$this->receiptSummary($this->executeAndFinalize($proposal->id(),$command,$stale));}catch(\Throwable){$errors[(string)$id]='Intelligence proposal recovery failed closed.';}}return['resumed'=>$resumed,'errors'=>$errors];
	}

	/** @param array<string,mixed> $evidence */
	public function recordFeedback(string $proposalId,string $outcome,int $effectivenessBasisPoints,array $evidence,PanelPolicyRequest|array $request,string $idempotencyKey):PanelIntelligenceFeedback {
		$request=$this->request($request);$proposal=$this->proposal($proposalId);$this->assertTenant($request,$proposal->tenantId());if(!in_array($proposal->status(),['succeeded','failed','denied'],true)){throw new \LogicException('Intelligence feedback requires a completed command proposal.');}$this->authorize($request,'intelligence.feedback.record',$proposal->tenantId(),'intelligence_proposal',$proposal->id(),'low',['command'=>$proposal->command(),'command_status'=>$proposal->status(),'outcome'=>$outcome]);$outcome=strtolower(trim($outcome));if(!in_array($outcome,PanelIntelligenceFeedback::OUTCOMES,true)||$effectivenessBasisPoints<0||$effectivenessBasisPoints>10000){throw new \InvalidArgumentException('Intelligence feedback outcome or effectiveness is invalid.');}$evidence=PanelOperationsGuard::safeMetadata($evidence,256);$idempotencyHash=$this->idempotency($proposal->tenantId(),$request->actorId(),$idempotencyKey,'feedback');$fingerprint=PanelOperationsGuard::digest(['proposal_id'=>$proposal->id(),'outcome'=>$outcome,'effectiveness_basis_points'=>$effectivenessBasisPoints,'evidence_digest'=>PanelOperationsGuard::digest($evidence)]);$state=$this->state();$known=$state['idempotency']['feedback'][$idempotencyHash]??null;if(is_array($known)){if(!hash_equals((string)($known['fingerprint']??''),$fingerprint)){throw new \LogicException('Intelligence feedback idempotency key conflict.');}return$this->storedFeedback($state['feedback'][(string)$known['id']]);}$id='feedback_'.substr(hash('sha256',$idempotencyHash."\0".$fingerprint),0,40);$feedback=PanelIntelligenceFeedback::sign($id,$proposal,$outcome,$effectivenessBasisPoints,$evidence,$request->actorId(),$this->now(),$this->currentKeyId,$this->keys[$this->currentKeyId]);$stored=['manifest'=>$feedback->jsonSerialize(),'sealed'=>$this->codec->seal(['evidence'=>$feedback->evidence()],$this->feedbackContext($feedback))];
		$result=$this->mutate(function(array &$state)use($proposal,$feedback,$idempotencyHash,$fingerprint,$stored):array{$known=$state['idempotency']['feedback'][$idempotencyHash]??null;if(is_array($known)){if(!hash_equals((string)($known['fingerprint']??''),$fingerprint)){throw new \LogicException('Intelligence feedback idempotency key conflict.');}return$state['feedback'][(string)$known['id']];}if(count($state['feedback'])>=$this->maximumEntries){throw new \LengthException('Intelligence feedback retention limit is reached.');}$entry=&$this->proposalEntry($state,$proposal->id());$current=PanelIntelligenceProposal::hydrate($entry['manifest']);if(!in_array($current->status(),['succeeded','failed','denied'],true)){throw new \LogicException('Intelligence proposal is no longer eligible for feedback.');}$state['feedback'][$feedback->id()]=$stored;$entry['feedback_ids'][]=$feedback->id();$entry['feedback_ids']=array_values(array_unique($entry['feedback_ids']));sort($entry['feedback_ids'],SORT_STRING);$entry['manifest']=$current->evolve($current->status(),$current->approverHashes(),$current->revision()+1,$current->dispatchAttempts(),count($entry['feedback_ids']),$this->now(),$current->receipt(),$current->rejection())->jsonSerialize();$state['idempotency']['feedback'][$idempotencyHash]=['id'=>$feedback->id(),'fingerprint'=>$fingerprint];ksort($state['feedback'],SORT_STRING);ksort($state['idempotency']['feedback'],SORT_STRING);return$state['feedback'][$feedback->id()];},'intelligence.feedback.recorded',['feedback_id'=>$feedback->id(),'proposal_id'=>$proposal->id(),'tenant_id'=>$proposal->tenantId(),'outcome'=>$outcome]);return$this->storedFeedback($result);
	}

	public function signal(string $id):PanelIntelligenceSignal {$id=PanelOperationsGuard::identifier($id,'intelligence signal id',190);$payload=$this->state()['signals'][$id]??null;if(!is_array($payload)){throw new \OutOfBoundsException('Intelligence signal does not exist.');}return$this->storedSignal($payload);}
	public function proposal(string $id):PanelIntelligenceProposal {$id=PanelOperationsGuard::identifier($id,'intelligence proposal id',190);$entry=$this->state()['proposals'][$id]??null;if(!is_array($entry)||!is_array($entry['manifest']??null)){throw new \OutOfBoundsException('Intelligence proposal does not exist.');}return PanelIntelligenceProposal::hydrate($entry['manifest']);}
	/** @return list<PanelIntelligenceProposal> */public function proposals(?string $tenantId=null,?string $status=null,int $limit=100):array {if($tenantId!==null){$tenantId=PanelOperationsGuard::identifier($tenantId,'intelligence proposal tenant');}if($status!==null&&!in_array($status,PanelIntelligenceProposal::STATUSES,true)){throw new \InvalidArgumentException('Intelligence proposal status filter is invalid.');}$limit=max(1,min(1000,$limit));$items=[];foreach($this->state()['proposals']as$entry){if(!is_array($entry)||!is_array($entry['manifest']??null)){continue;}$proposal=PanelIntelligenceProposal::hydrate($entry['manifest']);if(($tenantId===null||$proposal->tenantId()===$tenantId)&&($status===null||$proposal->status()===$status)){$items[]=$proposal;}}usort($items,static fn(PanelIntelligenceProposal $left,PanelIntelligenceProposal $right):int=>[$right->updatedAt(),$right->id()]<=>[$left->updatedAt(),$left->id()]);return array_slice($items,0,$limit);}
	/** @return list<PanelIntelligenceSignal> */public function signals(?string $tenantId=null,?string $kind=null,int $limit=100):array {if($tenantId!==null){$tenantId=PanelOperationsGuard::identifier($tenantId,'intelligence signal tenant');}if($kind!==null&&!in_array($kind,PanelIntelligenceSignal::KINDS,true)){throw new \InvalidArgumentException('Intelligence signal kind filter is invalid.');}$items=[];foreach($this->state()['signals']as$payload){$signal=$this->storedSignal($payload);if(($tenantId===null||$signal->tenantId()===$tenantId)&&($kind===null||$signal->kind()===$kind)){$items[]=$signal;}}usort($items,static fn(PanelIntelligenceSignal $left,PanelIntelligenceSignal $right):int=>[$right->observedAt(),$right->id()]<=>[$left->observedAt(),$left->id()]);return array_slice($items,0,max(1,min(1000,$limit)));}
	/** @return list<PanelIntelligenceFeedback> */public function feedback(?string $tenantId=null,?string $proposalId=null,int $limit=100):array {if($tenantId!==null){$tenantId=PanelOperationsGuard::identifier($tenantId,'intelligence feedback tenant');}if($proposalId!==null){$proposalId=PanelOperationsGuard::identifier($proposalId,'intelligence feedback proposal id',190);}$items=[];foreach($this->state()['feedback']as$payload){$item=$this->storedFeedback($payload);if(($tenantId===null||$item->tenantId()===$tenantId)&&($proposalId===null||$item->proposalId()===$proposalId)){$items[]=$item;}}usort($items,static fn(PanelIntelligenceFeedback $left,PanelIntelligenceFeedback $right):int=>[$right->observedAt(),$right->id()]<=>[$left->observedAt(),$left->id()]);return array_slice($items,0,max(1,min(1000,$limit)));}

	/** @return array<string,mixed> */
	public function effectiveness(?string $tenantId=null):array {
		if($tenantId!==null){$tenantId=PanelOperationsGuard::identifier($tenantId,'intelligence effectiveness tenant');}$feedback=[];foreach($this->state()['feedback']as$payload){$item=$this->storedFeedback($payload);if($tenantId===null||$item->tenantId()===$tenantId){$feedback[]=$item;}}$outcomes=array_fill_keys(PanelIntelligenceFeedback::OUTCOMES,0);$byCommand=[];$total=0;foreach($feedback as$item){$outcomes[$item->outcome()]++;$total+=$item->effectivenessBasisPoints();$bucket=$byCommand[$item->command()]??['count'=>0,'total'=>0,'positive'=>0,'negative'=>0];$bucket['count']++;$bucket['total']+=$item->effectivenessBasisPoints();$bucket[$item->outcome()]=($bucket[$item->outcome()]??0)+1;$byCommand[$item->command()]=$bucket;}foreach($byCommand as$command=>$bucket){$byCommand[$command]=['count'=>$bucket['count'],'average_effectiveness_basis_points'=>$bucket['count']>0?(int)round($bucket['total']/$bucket['count']):0,'positive'=>$bucket['positive']??0,'negative'=>$bucket['negative']??0];}ksort($byCommand,SORT_STRING);return PanelManifestContract::stamp(['type'=>'panel_intelligence_effectiveness_manifest','version'=>1,'tenant_id'=>$tenantId,'feedback_count'=>count($feedback),'average_effectiveness_basis_points'=>$feedback!==[]?(int)round($total/count($feedback)):0,'outcomes'=>$outcomes,'commands'=>$byCommand,'evidence_payloads_exposed'=>false]);
	}

	/** @return array<string,mixed> */public function changesSince(int $cursor=0,int $limit=100):array{return$this->store->changesSince($cursor,$limit);}

	/** @return array<string,mixed> */
	public function verifyIntegrity():array {$state=$this->state(false);$this->assertState($state);$fabric=$this->fabric->verifyIntegrity();return['ok'=>true,'revision'=>$state['revision'],'signals'=>count($state['signals']),'proposals'=>count($state['proposals']),'feedback'=>count($state['feedback']),'fabric_revision'=>$fabric['revision'],'fabric_sequence'=>$fabric['sequence']];}

	public function jsonSerialize():array {$state=$this->state();$statuses=array_fill_keys(PanelIntelligenceProposal::STATUSES,0);foreach($state['proposals']as$entry){$proposal=PanelIntelligenceProposal::hydrate($entry['manifest']);$statuses[$proposal->status()]++;}return PanelManifestContract::stamp(['type'=>'panel_closed_loop_intelligence_manifest','version'=>1,'revision'=>$state['revision'],'cursor'=>$this->store->cursor(),'signal_count'=>count($state['signals']),'proposal_count'=>count($state['proposals']),'proposal_statuses'=>$statuses,'feedback_count'=>count($state['feedback']),'effectiveness'=>$this->effectiveness(),'approval_thresholds'=>$this->approvalThresholds,'trusted_key_ids'=>array_keys($this->keys),'current_key_id'=>$this->currentKeyId,'policy_revision'=>$this->policy->revision(),'maximum_entries'=>$this->maximumEntries,'capabilities'=>['signed_expiring_signals'=>true,'governed_command_proposals'=>true,'independent_signed_approvals'=>true,'separation_of_duties'=>true,'encrypted_inputs'=>true,'encrypted_authority_evidence'=>true,'command_fabric_dispatch'=>true,'exact_idempotency'=>true,'optimistic_revisions'=>true,'crash_recovery'=>true,'outcome_attribution'=>true,'signed_feedback'=>true,'effectiveness_measurement'=>true,'key_rotation'=>true],'security'=>['default_deny'=>true,'state_hmac'=>true,'raw_inputs_serialized'=>false,'raw_idempotency_serialized'=>false,'proposer_identity_serialized'=>false,'approval_signatures_in_public_manifest'=>false,'command_policy_revalidated'=>true]]);}

	private function executeAndFinalize(string $proposalId,PanelCommandEnvelope $command,?int $resumeStaleAfterSeconds=null):PanelCommandReceipt {$fabricState=$this->fabric->store()->payload();$fabricEntry=$fabricState['commands'][$command->idempotencyHash()]??null;$receipt=$resumeStaleAfterSeconds!==null&&is_array($fabricEntry)&&($fabricEntry['status']??null)==='executing'?$this->fabric->resume($command->idempotencyHash(),$resumeStaleAfterSeconds):$this->fabric->dispatch($command);$summary=$this->receiptSummary($receipt);$this->mutate(function(array &$state)use($proposalId,$command,$summary):void{$entry=&$this->proposalEntry($state,$proposalId);$current=PanelIntelligenceProposal::hydrate($entry['manifest']);$dispatch=$entry['dispatch']??null;if(!is_array($dispatch)||!hash_equals((string)($dispatch['command_fingerprint']??''),$command->fingerprint())){throw new \UnexpectedValueException('Intelligence dispatch claim no longer matches its command.');}if(in_array($current->status(),['succeeded','failed','denied'],true)){if(!hash_equals((string)($current->receipt()['digest']??''),(string)$summary['digest'])){throw new \UnexpectedValueException('Intelligence proposal terminal receipt conflict.');}return;}if($current->status()!=='dispatching'){throw new \LogicException('Intelligence proposal is no longer dispatching.');}$entry['manifest']=$current->evolve($summary['status'],$current->approverHashes(),$current->revision()+1,$current->dispatchAttempts(),$current->feedbackCount(),$this->now(),$summary,null)->jsonSerialize();},'intelligence.proposal.dispatched',['proposal_id'=>$proposalId,'tenant_id'=>$command->tenantId(),'command'=>$command->command(),'status'=>$receipt->status(),'receipt_id'=>$receipt->id()]);return$receipt;}

	private function terminalReceipt(PanelIntelligenceProposal $proposal):PanelCommandReceipt {$state=$this->state();$entry=$state['proposals'][$proposal->id()]??null;if(!is_array($entry)||!is_array($entry['dispatch']??null)){throw new \UnexpectedValueException('Terminal intelligence proposal is missing dispatch evidence.');}$command=$this->dispatchCommand($proposal->id(),$entry['dispatch']);$receipt=$this->fabric->dispatch($command);$summary=$this->receiptSummary($receipt);if(!hash_equals((string)($proposal->receipt()['digest']??''),(string)$summary['digest'])){throw new \UnexpectedValueException('Terminal intelligence proposal receipt does not match the command fabric.');}return$receipt;}

	private function reclaimDispatch(PanelIntelligenceProposal $proposal,int $staleAfterSeconds):PanelCommandEnvelope {$state=$this->state();$entry=$state['proposals'][$proposal->id()]??null;if(!is_array($entry)||!is_array($entry['dispatch']??null)){throw new \UnexpectedValueException('Dispatching intelligence proposal is missing its exact command.');}$dispatch=$entry['dispatch'];if(!$this->isStale((string)($dispatch['claimed_at']??''),$staleAfterSeconds)){throw new \LogicException('Intelligence proposal dispatch is not stale enough to recover.');}$command=$this->dispatchCommand($proposal->id(),$dispatch);$this->mutate(function(array &$state)use($proposal,$command):void{$entry=&$this->proposalEntry($state,$proposal->id());$current=PanelIntelligenceProposal::hydrate($entry['manifest']);if($current->status()!=='dispatching'||!is_array($entry['dispatch'])||!hash_equals((string)$entry['dispatch']['command_fingerprint'],$command->fingerprint())){throw new \LogicException('Intelligence proposal dispatch claim changed before recovery.');}$entry['dispatch']['claimed_at']=$this->now();$entry['dispatch']['attempts']=(int)$entry['dispatch']['attempts']+1;$entry['manifest']=$current->evolve('dispatching',$current->approverHashes(),$current->revision()+1,$current->dispatchAttempts()+1,$current->feedbackCount(),$this->now(),null,null)->jsonSerialize();},'intelligence.proposal.dispatch_reclaimed',['proposal_id'=>$proposal->id(),'tenant_id'=>$proposal->tenantId(),'command'=>$proposal->command()]);return$command;}

	/** @return array<string,PanelIntelligenceApproval> */private function validApprovals(PanelIntelligenceProposal $proposal):array {$entry=$this->state()['proposals'][$proposal->id()]??null;if(!is_array($entry)){throw new \OutOfBoundsException('Intelligence proposal does not exist.');}$private=$this->proposalPrivate($proposal,$entry);$valid=[];foreach($entry['approvals']??[]as$payload){if(!is_array($payload)){continue;}try{$approval=$this->storedApproval($proposal,$payload);if($approval->verify($this->keys,$proposal,$this->now())&&!hash_equals($approval->approverId(),(string)$private['proposer_id'])){$valid[$approval->approverId()]=$approval;}}catch(\Throwable){}}ksort($valid,SORT_STRING);return$valid;}
	/** @param array<string,mixed> $entry */private function storedSignal(array $entry):PanelIntelligenceSignal {if(!is_array($entry['manifest']??null)||!is_array($entry['sealed']??null)){throw new \UnexpectedValueException('Stored intelligence signal payload is invalid.');}$public=PanelIntelligenceSignal::hydrate($entry['manifest']);$private=$this->codec->open($entry['sealed'],$this->signalContext($public));if(!is_array($private['evidence']??null)){throw new \UnexpectedValueException('Stored intelligence signal evidence is invalid.');}return PanelIntelligenceSignal::hydrate($entry['manifest'],$private['evidence']);}
	/** @param array<string,mixed> $entry */private function storedApproval(PanelIntelligenceProposal $proposal,array $entry):PanelIntelligenceApproval {if(!is_array($entry['manifest']??null)||!is_array($entry['sealed']??null)){throw new \UnexpectedValueException('Stored intelligence approval payload is invalid.');}$public=PanelIntelligenceApproval::hydrate($entry['manifest']);$private=$this->codec->open($entry['sealed'],$this->approvalContext($public));if(!is_string($private['approver_id']??null)){throw new \UnexpectedValueException('Stored intelligence approval identity is invalid.');}$approval=PanelIntelligenceApproval::hydrate($entry['manifest'],$private['approver_id']);if(!$approval->verifyStored($this->keys,$proposal)){throw new \UnexpectedValueException('Stored intelligence approval is untrusted.');}return$approval;}
	/** @param array<string,mixed> $entry */private function storedFeedback(array $entry):PanelIntelligenceFeedback {if(!is_array($entry['manifest']??null)||!is_array($entry['sealed']??null)){throw new \UnexpectedValueException('Stored intelligence feedback payload is invalid.');}$public=PanelIntelligenceFeedback::hydrate($entry['manifest']);$private=$this->codec->open($entry['sealed'],$this->feedbackContext($public));if(!is_array($private['evidence']??null)){throw new \UnexpectedValueException('Stored intelligence feedback evidence is invalid.');}return PanelIntelligenceFeedback::hydrate($entry['manifest'],$private['evidence']);}

	/** @param array<string,mixed>|null $entry @return array{input:array<string,mixed>,proposer_id:string,expected_revision:?int} */private function proposalPrivate(PanelIntelligenceProposal $proposal,?array $entry=null):array {$entry??=$this->state()['proposals'][$proposal->id()]??null;if(!is_array($entry)||!is_array($entry['sealed']??null)){throw new \UnexpectedValueException('Intelligence proposal encrypted payload is unavailable.');}$private=$this->codec->open($entry['sealed'],$this->proposalContext($proposal));if(!is_array($private['input']??null)||!is_string($private['proposer_id']??null)||(!is_int($private['expected_revision']??null)&&($private['expected_revision']??null)!==null)||!hash_equals(PanelOperationsGuard::digest($private['input']),$proposal->inputDigest())||!hash_equals(hash('sha256',$private['proposer_id']),$proposal->proposerHash())){throw new \UnexpectedValueException('Intelligence proposal encrypted payload is invalid.');}return['input'=>$private['input'],'proposer_id'=>$private['proposer_id'],'expected_revision'=>$private['expected_revision']];}

	/** @param array<string,mixed> $dispatch */private function dispatchCommand(string $proposalId,array $dispatch):PanelCommandEnvelope {$fingerprint=(string)($dispatch['command_fingerprint']??'');if(preg_match('/^[a-f0-9]{64}$/D',$fingerprint)!==1||!is_array($dispatch['sealed']??null)){throw new \UnexpectedValueException('Intelligence dispatch payload is invalid.');}$bundle=$this->codec->open($dispatch['sealed'],$this->dispatchContext($proposalId,$fingerprint));if(!is_array($bundle['manifest']??null)||!is_array($bundle['sealed']??null)){throw new \UnexpectedValueException('Intelligence dispatch command bundle is invalid.');}$command=PanelCommandEnvelope::hydrate($bundle['manifest'],$bundle['sealed']);if(!hash_equals($command->fingerprint(),$fingerprint)||!hash_equals($command->idempotencyHash(),(string)($dispatch['idempotency_hash']??''))){throw new \UnexpectedValueException('Intelligence dispatch command integrity check failed.');}return$command;}

	/** @return array<string,mixed> */private function receiptSummary(PanelCommandReceipt $receipt):array {$metadata=$receipt->metadata();return['id'=>$receipt->id(),'status'=>$receipt->status(),'ok'=>$receipt->ok(),'event_count'=>count($receipt->eventIds()),'completed_at'=>$receipt->completedAt(),'error_code'=>isset($metadata['error_code'])?(string)$metadata['error_code']:null,'digest'=>$receipt->digest(),'result_digest'=>PanelOperationsGuard::digest($receipt->result())];}

	/** @return array<string,mixed> */private function state(bool $assert=true):array {$state=$this->store->payload();if($assert){$this->assertState($state);}return$state;}
	/** @return mixed */private function mutate(callable $mutation,string $type,array $event=[]):mixed {$transaction=$this->store->transaction(function(array &$state)use($mutation){$this->assertState($state);$result=$mutation($state);$state['revision']++;$state=$this->signedState($state);return$result;},$type,PanelOperationsGuard::safeMetadata($event,64));return$transaction['result'];}

	/** @param array<string,mixed> $state */private function assertState(array $state):void {
		if(($state['schema']??null)!=='panel_closed_loop_intelligence'||($state['version']??null)!==1||!is_int($state['revision']??null)||$state['revision']<0||!is_array($state['signals']??null)||!is_array($state['proposals']??null)||!is_array($state['feedback']??null)||!is_array($state['idempotency']['proposals']??null)||!is_array($state['idempotency']['feedback']??null)||!is_array($state['integrity']??null)){throw new \UnexpectedValueException('Closed-loop intelligence state shape is invalid.');}$this->verifyStateSignature($state);if(count($state['signals'])>$this->maximumEntries||count($state['proposals'])>$this->maximumEntries||count($state['feedback'])>$this->maximumEntries){throw new \UnexpectedValueException('Closed-loop intelligence state exceeds its configured bound.');}
		foreach($state['signals']as$id=>$payload){if(!is_string($id)||!is_array($payload)){throw new \UnexpectedValueException('Stored intelligence signal entry is invalid.');}$signal=$this->storedSignal($payload);if($signal->id()!==$id||!$signal->verifyStored($this->keys)){throw new \UnexpectedValueException('Stored intelligence signal is untrusted.');}}
		$this->fabric->verifyIntegrity();$fabricState=$this->fabric->store()->payload();
		foreach($state['proposals']as$id=>$entry){if(!is_string($id)||!is_array($entry)||!is_array($entry['manifest']??null)||!is_array($entry['sealed']??null)||!is_string($entry['idempotency_hash']??null)||!is_string($entry['fingerprint']??null)||!is_array($entry['approvals']??null)||(!is_array($entry['dispatch']??null)&&($entry['dispatch']??null)!==null)||!is_array($entry['feedback_ids']??null)){throw new \UnexpectedValueException('Stored intelligence proposal entry is invalid.');}$proposal=PanelIntelligenceProposal::hydrate($entry['manifest']);if($proposal->id()!==$id||!isset($state['signals'][$proposal->signalId()])||!hash_equals($this->storedSignal($state['signals'][$proposal->signalId()])->digest(),$proposal->signalDigest())){throw new \UnexpectedValueException('Stored intelligence proposal signal binding is invalid.');}$this->proposalPrivate($proposal,$entry);$approvalHashes=[];foreach($entry['approvals']as$hash=>$payload){if(!is_string($hash)||!is_array($payload)){throw new \UnexpectedValueException('Stored intelligence approval entry is invalid.');}$approval=$this->storedApproval($proposal,$payload);if(!hash_equals($hash,$approval->approverHash())||!$approval->verifyStored($this->keys,$proposal)){throw new \UnexpectedValueException('Stored intelligence approval is untrusted.');}$approvalHashes[]=$hash;}sort($approvalHashes,SORT_STRING);if($approvalHashes!==$proposal->approverHashes()){throw new \UnexpectedValueException('Stored intelligence proposal approval projection is invalid.');}
			if(is_array($entry['dispatch'])){$command=$this->dispatchCommand($proposal->id(),$entry['dispatch']);if($command->tenantId()!==$proposal->tenantId()||$command->command()!==$proposal->command()||$command->ability()!==$proposal->ability()||!hash_equals(PanelOperationsGuard::digest($command->input()),$proposal->inputDigest())||$command->correlationId()!==$proposal->id()||$command->causationId()!==$proposal->signalId()){throw new \UnexpectedValueException('Stored intelligence dispatch target is invalid.');}if(in_array($proposal->status(),['succeeded','failed','denied'],true)){$receiptPayload=$fabricState['receipts'][$command->idempotencyHash()]??null;if(!is_array($receiptPayload)){throw new \UnexpectedValueException('Completed intelligence proposal has no command-fabric receipt.');}$receipt=PanelCommandReceipt::hydrate($receiptPayload);if(!hash_equals($receipt->commandFingerprint(),$command->fingerprint())||!hash_equals((string)($proposal->receipt()['digest']??''),$receipt->digest())||$proposal->status()!==$receipt->status()){throw new \UnexpectedValueException('Completed intelligence proposal receipt binding is invalid.');}}elseif($proposal->status()!=='dispatching'){throw new \UnexpectedValueException('Intelligence proposal has dispatch evidence in an invalid state.');}}
			foreach($entry['feedback_ids']as$feedbackId){if(!is_string($feedbackId)||!is_array($state['feedback'][$feedbackId]??null)){throw new \UnexpectedValueException('Intelligence proposal feedback reference is invalid.');}$feedback=$this->storedFeedback($state['feedback'][$feedbackId]);if($feedback->proposalId()!==$proposal->id()){throw new \UnexpectedValueException('Intelligence feedback proposal binding is invalid.');}}if(count($entry['feedback_ids'])!==$proposal->feedbackCount()){throw new \UnexpectedValueException('Intelligence proposal feedback count is invalid.');}}
		foreach($state['feedback']as$id=>$payload){if(!is_string($id)||!is_array($payload)){throw new \UnexpectedValueException('Stored intelligence feedback entry is invalid.');}$feedback=$this->storedFeedback($payload);if($feedback->id()!==$id||!$feedback->verify($this->keys)||!isset($state['proposals'][$feedback->proposalId()])){throw new \UnexpectedValueException('Stored intelligence feedback is untrusted.');}}
		foreach(['proposals','feedback']as$kind){foreach($state['idempotency'][$kind]as$hash=>$index){if(!is_string($hash)||preg_match('/^[a-f0-9]{64}$/D',$hash)!==1||!is_array($index)||!is_string($index['id']??null)||!is_string($index['fingerprint']??null)||preg_match('/^[a-f0-9]{64}$/D',$index['fingerprint'])!==1){throw new \UnexpectedValueException('Intelligence idempotency index is invalid.');}$target=$kind==='proposals'?$state['proposals'][$index['id']]??null:$state['feedback'][$index['id']]??null;if(!is_array($target)){throw new \UnexpectedValueException('Intelligence idempotency index target is missing.');}if($kind==='proposals'&&(!hash_equals((string)$target['idempotency_hash'],$hash)||!hash_equals((string)$target['fingerprint'],$index['fingerprint']))){throw new \UnexpectedValueException('Intelligence proposal idempotency index is inconsistent.');}}}
	}

	/** @param array<string,mixed> $state @return array<string,mixed> */private function signedState(array $state):array {unset($state['integrity']);$digest=PanelOperationsGuard::digest($state);$state['integrity']=['key_id'=>$this->currentKeyId,'digest'=>$digest,'signature'=>hash_hmac('sha256',$digest,$this->keys[$this->currentKeyId])];return$state;}
	/** @param array<string,mixed> $state */private function verifyStateSignature(array $state):void {$integrity=$state['integrity'];if(!is_string($integrity['key_id']??null)||!is_string($integrity['digest']??null)||!is_string($integrity['signature']??null)){throw new \UnexpectedValueException('Closed-loop intelligence state signature is invalid.');}$key=$this->keys[$integrity['key_id']]??null;$unsigned=$state;unset($unsigned['integrity']);$digest=PanelOperationsGuard::digest($unsigned);if(!is_string($key)||strlen($key)<32||!hash_equals($digest,$integrity['digest'])||!hash_equals($integrity['signature'],hash_hmac('sha256',$digest,$key))){throw new \UnexpectedValueException('Closed-loop intelligence state signature is untrusted.');}}

	/** @return array<string,mixed> */private function &proposalEntry(array &$state,string $id):array {if(!isset($state['proposals'][$id])||!is_array($state['proposals'][$id])){throw new \OutOfBoundsException('Intelligence proposal does not exist.');}return$state['proposals'][$id];}
	private function signalContext(PanelIntelligenceSignal $signal):string{return'intelligence.signal.'.$signal->id().'.'.$signal->digest();}
	private function approvalContext(PanelIntelligenceApproval $approval):string{return'intelligence.approval.'.$approval->digest();}
	private function feedbackContext(PanelIntelligenceFeedback $feedback):string{return'intelligence.feedback.'.$feedback->digest();}
	private function proposalContext(PanelIntelligenceProposal $proposal):string{return'intelligence.proposal.'.$proposal->id().'.'.$proposal->approvalTarget();}
	private function dispatchContext(string $proposalId,string $fingerprint):string{return'intelligence.dispatch.'.$proposalId.'.'.$fingerprint;}
	private function idempotency(string $tenantId,string $actorId,string $key,string $purpose):string {$key=trim($key);if($key===''||strlen($key)>512||str_contains($key,"\0")){throw new \InvalidArgumentException('Intelligence idempotency key is invalid.');}return hash('sha256',$purpose."\0".$tenantId."\0".$actorId."\0".$key);}
	private function request(PanelPolicyRequest|array $request):PanelPolicyRequest{return$request instanceof PanelPolicyRequest?$request:PanelPolicyRequest::from($request);}
	private function assertTenant(PanelPolicyRequest $request,string $tenantId):void {if($request->tenantId()===null||!hash_equals($request->tenantId(),$tenantId)){throw new \LogicException('Intelligence operation tenant does not match the trusted policy request.');}}
	/** @param array<string,mixed> $context */private function authorize(PanelPolicyRequest $request,string $ability,string $tenantId,string $resourceType,string $resourceId,string $risk,array $context=[]):PanelPolicyDecision {$decision=$this->policy->evaluate(new PanelPolicyRequest($request->actorId(),$ability,$tenantId,$resourceType,$resourceId,$risk,$request->roles(),$request->permissions(),array_replace($request->context(),PanelOperationsGuard::safeMetadata($context,128)),$this->now()));return$decision->assertAllowed();}
	private function riskForSeverity(string $severity):string{return match($severity){'critical'=>'critical','high'=>'high','medium'=>'medium',default=>'low'};}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Intelligence clock must return an instant.');}return PanelOperationsGuard::instant($value);}
	private function after(string $instant,int $seconds):string{return PanelOperationsGuard::instant((new \DateTimeImmutable($instant))->modify('+'.$seconds.' seconds'));}
	private function isStale(string $instant,int $seconds):bool {try{return(new \DateTimeImmutable($instant))->getTimestamp()<=(new \DateTimeImmutable($this->now()))->getTimestamp()-$seconds;}catch(\Throwable){throw new \UnexpectedValueException('Intelligence dispatch claim timestamp is invalid.');}}
}
