<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Portable semantic metric definition and deterministic in-memory evaluator. */
final class PanelSemanticMetric implements \JsonSerializable {
	public const AGGREGATIONS=['count','sum','average','minimum','maximum','distinct_count','ratio'];
	/** @param list<string> $dimensions @param array<string,mixed> $filter @param array<string,mixed> $numeratorFilter @param array<string,mixed> $denominatorFilter @param array<string,mixed> $metadata */
	public function __construct(private readonly string $id,private readonly string $label,private readonly string $entity,private readonly string $aggregation='count',private readonly ?string $field=null,private readonly array $dimensions=[],private readonly array $filter=[],private readonly array $numeratorFilter=[],private readonly array $denominatorFilter=[],private readonly array $metadata=[]){PanelOperationsGuard::name($id,'semantic metric id');PanelOperationsGuard::label($label,'semantic metric label');PanelOperationsGuard::name($entity,'semantic metric entity');if(!in_array($aggregation,self::AGGREGATIONS,true)){throw new \InvalidArgumentException('Semantic metric aggregation is invalid.');}if($field!==null){PanelOperationsGuard::name($field,'semantic metric field');}if(!in_array($aggregation,['count','ratio'],true)&&$field===null){throw new \InvalidArgumentException('Semantic aggregation requires a value field.');}PanelOperationsGuard::names($dimensions,'semantic dimension');foreach([$filter,$numeratorFilter,$denominatorFilter]as$predicate){self::validateFilter($predicate);}PanelOperationsGuard::safeMetadata($metadata,256);}
	/** @param array<string,mixed> $definition */ public static function from(string $id,array $definition):self{return new self(PanelOperationsGuard::name($id,'semantic metric id'),PanelOperationsGuard::label((string)($definition['label']??ucwords(str_replace('_',' ',$id))),'semantic metric label'),PanelOperationsGuard::name((string)($definition['entity']??''),'semantic metric entity'),in_array(($aggregation=strtolower((string)($definition['aggregation']??'count'))),self::AGGREGATIONS,true)?$aggregation:'count',isset($definition['field'])&&trim((string)$definition['field'])!==''?PanelOperationsGuard::name((string)$definition['field'],'semantic metric field'):null,PanelOperationsGuard::names(is_array($definition['dimensions']??null)?$definition['dimensions']:[],'semantic dimension'),PanelOperationsGuard::canonical(is_array($definition['filter']??null)?$definition['filter']:[]),PanelOperationsGuard::canonical(is_array($definition['numerator_filter']??null)?$definition['numerator_filter']:[]),PanelOperationsGuard::canonical(is_array($definition['denominator_filter']??null)?$definition['denominator_filter']:[]),PanelOperationsGuard::safeMetadata(is_array($definition['metadata']??null)?$definition['metadata']:[],256));}
	public function id():string{return$this->id;}public function label():string{return$this->label;}public function entity():string{return$this->entity;}public function aggregation():string{return$this->aggregation;}public function field():?string{return$this->field;}/** @return list<string> */public function dimensions():array{return$this->dimensions;}
	/** @return array<string,mixed> */public function filter():array{return$this->filter;}/** @return array<string,mixed> */public function numeratorFilter():array{return$this->numeratorFilter;}/** @return array<string,mixed> */public function denominatorFilter():array{return$this->denominatorFilter;}/** @return array<string,mixed> */public function metadata():array{return$this->metadata;}
	/** @param list<array<string,mixed>> $rows @param list<string> $groupBy @return list<array<string,mixed>> */
	public function evaluate(array $rows,array $groupBy=[]):array {$groupBy=$groupBy===[]?$this->dimensions:PanelOperationsGuard::names($groupBy,'semantic group dimension');if(array_diff($groupBy,$this->dimensions)!==[]){throw new \InvalidArgumentException('Semantic query requested an undeclared dimension.');}$groups=[];foreach($rows as$row){if(!is_array($row)||!self::matches($row,$this->filter)){continue;}$dimensions=[];foreach($groupBy as$dimension){$dimensions[$dimension]=PanelOperationsGuard::valueAt($row,$dimension);}$key=PanelOperationsGuard::digest($dimensions);$groups[$key]??=['dimensions'=>$dimensions,'rows'=>[]];$groups[$key]['rows'][]=$row;}if($groups===[]&&$groupBy===[]){$groups['all']=['dimensions'=>[],'rows'=>[]];}$result=[];foreach($groups as$group){$values=[];if($this->field!==null){foreach($group['rows']as$row){$value=PanelOperationsGuard::valueAt($row,$this->field);if($value!==null){$values[]=$value;}}}$value=match($this->aggregation){'count'=>count($group['rows']),'sum'=>array_sum(array_map('floatval',$values)),'average'=>$values===[]?null:array_sum(array_map('floatval',$values))/count($values),'minimum'=>$values===[]?null:min($values),'maximum'=>$values===[]?null:max($values),'distinct_count'=>count(array_unique(array_map(static fn(mixed $value):string=>PanelOperationsGuard::json($value),$values))),'ratio'=>$this->ratio($group['rows'])};$result[]=['metric'=>$this->id,'dimensions'=>$group['dimensions'],'value'=>$value,'row_count'=>count($group['rows'])];}usort($result,static fn(array $a,array $b):int=>PanelOperationsGuard::json($a['dimensions'])<=>PanelOperationsGuard::json($b['dimensions']));return$result;}
	public function fingerprint():string{return PanelOperationsGuard::digest($this->values());}public function jsonSerialize():array{return PanelManifestContract::stamp($this->values()+['fingerprint'=>$this->fingerprint()]);}
	/** @return array<string,mixed> */private function values():array{return['type'=>'panel_semantic_metric_manifest','version'=>1,'id'=>$this->id,'label'=>$this->label,'entity'=>$this->entity,'aggregation'=>$this->aggregation,'field'=>$this->field,'dimensions'=>$this->dimensions,'filter'=>$this->filter,'numerator_filter'=>$this->numeratorFilter,'denominator_filter'=>$this->denominatorFilter,'metadata'=>$this->metadata];}
	/** @param list<array<string,mixed>> $rows */private function ratio(array $rows):?float {$denominator=count(array_filter($rows,fn(array $row):bool=>self::matches($row,$this->denominatorFilter)));if($denominator===0){return null;}$numerator=count(array_filter($rows,fn(array $row):bool=>self::matches($row,$this->numeratorFilter)));return$numerator/$denominator;}
	/** @param array<string,mixed> $filter */private static function validateFilter(array $filter):void {if(count($filter)>128){throw new \LengthException('Semantic metric filter exceeds its item limit.');}foreach($filter as$path=>$expected){if(!is_string($path)||$path===''||preg_match('/^[a-zA-Z0-9_.-]+$/D',$path)!==1){throw new \InvalidArgumentException('Semantic metric filter path is invalid.');}PanelOperationsGuard::canonical($expected);}}
	/** @param array<string,mixed> $row @param array<string,mixed> $filter */private static function matches(array $row,array $filter):bool {foreach($filter as$path=>$expected){$actual=PanelOperationsGuard::valueAt($row,$path,new \stdClass());if(is_array($expected)){if(!in_array($actual,$expected,true)){return false;}}elseif($actual!==$expected){return false;}}return true;}
}
