<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Field-level data, metric, policy, command, and surface lineage graph. */
final class PanelLineageGraph implements PanelCheckpointableService,\JsonSerializable {
	/** @var array<string,array<string,mixed>> */private array $nodes=[];/** @var array<string,array<string,mixed>> */private array $edges=[];private int $revision=0;
	/** @param array<string,mixed> $metadata */public function node(string $id,string $kind,string $label,array $metadata=[],bool $replace=false):self {$id=PanelOperationsGuard::identifier($id,'lineage node id',192);$kind=PanelOperationsGuard::name($kind,'lineage node kind');$label=PanelOperationsGuard::label($label,'lineage node label',512);if(!$replace&&isset($this->nodes[$id])){throw new \LogicException('Lineage node is already registered.');}$this->nodes[$id]=['id'=>$id,'kind'=>$kind,'label'=>$label,'metadata'=>PanelOperationsGuard::safeMetadata($metadata,256)];ksort($this->nodes,SORT_STRING);$this->revision++;return$this;}
	/** @param array<string,mixed> $metadata */public function edge(string $from,string $to,string $kind='derives',array $metadata=[],bool $replace=false):self {$from=PanelOperationsGuard::identifier($from,'lineage source id',192);$to=PanelOperationsGuard::identifier($to,'lineage target id',192);if($from===$to){throw new \InvalidArgumentException('Lineage self-edges are not allowed.');}if(!isset($this->nodes[$from],$this->nodes[$to])){throw new \OutOfBoundsException('Lineage edge endpoints must be registered first.');}$kind=PanelOperationsGuard::name($kind,'lineage edge kind');$key=hash('sha256',$from.'|'.$kind.'|'.$to);if(isset($this->edges[$key])&&!$replace){throw new \LogicException('Lineage edge is already registered.');}$previous=$this->edges[$key]??null;$this->edges[$key]=['from'=>$from,'to'=>$to,'kind'=>$kind,'metadata'=>PanelOperationsGuard::safeMetadata($metadata,256)];ksort($this->edges,SORT_STRING);if(in_array($kind,['derives','transforms','aggregates'],true)&&$this->pathExists($to,$from,['derives','transforms','aggregates'])){if(is_array($previous)){$this->edges[$key]=$previous;}else{unset($this->edges[$key]);}throw new \LogicException('Derivation lineage must remain acyclic.');}$this->revision++;return$this;}
	public function forgetPrefix(string $prefix):self {$prefix=PanelOperationsGuard::identifier($prefix,'lineage namespace',192);$changed=false;foreach($this->edges as$key=>$edge){if(str_starts_with((string)$edge['from'],$prefix)||str_starts_with((string)$edge['to'],$prefix)){unset($this->edges[$key]);$changed=true;}}foreach(array_keys($this->nodes)as$id){if(str_starts_with($id,$prefix)){unset($this->nodes[$id]);$changed=true;}}if($changed){$this->revision++;}return$this;}
	public function has(string $id):bool{return isset($this->nodes[$id]);}/** @return array<string,mixed> */public function get(string $id):array{if(!isset($this->nodes[$id])){throw new \OutOfBoundsException('Lineage node is not registered.');}return$this->nodes[$id];}
	/** @param list<string> $kinds @return list<array<string,mixed>> */public function upstream(string $id,int $depth=32,array $kinds=[]):array{return$this->traverse($id,'in',$depth,$kinds);}/** @param list<string> $kinds @return list<array<string,mixed>> */public function downstream(string $id,int $depth=32,array $kinds=[]):array{return$this->traverse($id,'out',$depth,$kinds);}
	/** @return array<string,mixed> */public function impact(string $id):array {$downstream=$this->downstream($id,64);$byKind=[];foreach($downstream as$node){$byKind[$node['kind']]=($byKind[$node['kind']]??0)+1;}ksort($byKind,SORT_STRING);return['source'=>$this->get($id),'affected_count'=>count($downstream),'affected_by_kind'=>$byKind,'affected'=>$downstream];}
	public static function fromCompilation(PanelDomainCompilation $compilation):self {$graph=new self();$source=$compilation->artifact('source');if(!is_array($source)){throw new \UnexpectedValueException('Domain compilation source is invalid.');}foreach($source['entities']??[]as$entity=>$definition){$entityId='entity:'.$entity;$graph->node($entityId,'entity',(string)$definition['label']);foreach($definition['fields']as$field=>$fieldDefinition){$fieldId='field:'.$entity.'.'.$field;$graph->node($fieldId,'field',(string)$fieldDefinition['label'],['classification'=>$fieldDefinition['classification']])->edge($fieldId,$entityId,'belongs_to');}}foreach($source['metrics']??[]as$name=>$metric){$metricId='metric:'.$name;$graph->node($metricId,'metric',(string)$metric['label']);$entity=(string)$metric['entity'];if(($metric['field']??'')!==''){$graph->edge('field:'.$entity.'.'.$metric['field'],$metricId,'aggregates');}foreach($metric['dimensions']as$dimension){$graph->edge('field:'.$entity.'.'.$dimension,$metricId,'groups');}}foreach($source['commands']??[]as$name=>$command){$commandId='command:'.$name;$graph->node($commandId,'command',(string)$command['label'])->edge($commandId,'entity:'.$command['entity'],'mutates');}foreach($source['surfaces']??[]as$name=>$surface){$surfaceId='surface:'.$name;$graph->node($surfaceId,'surface',(string)$surface['label']);if(($surface['entity']??'')!==''){$graph->edge('entity:'.$surface['entity'],$surfaceId,'renders');}}return$graph;}
	public function revision():int{return$this->revision;}public function fingerprint():string{return PanelOperationsGuard::digest(['nodes'=>$this->nodes,'edges'=>$this->edges]);}public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_lineage_graph_manifest','version'=>1,'revision'=>$this->revision,'fingerprint'=>$this->fingerprint(),'nodes'=>$this->nodes,'edges'=>array_values($this->edges),'capabilities'=>['field_level'=>true,'impact_analysis'=>true,'upstream_downstream'=>true,'cycle_guarded_derivations'=>true,'domain_compilation_import'=>true]]);}
	public function checkpointType():string{return'panel_lineage_graph_v1';}/** @return array<string,mixed> */public function checkpoint():array{return['nodes'=>$this->nodes,'edges'=>$this->edges,'revision'=>$this->revision,'digest'=>PanelOperationsGuard::digest(['nodes'=>$this->nodes,'edges'=>$this->edges,'revision'=>$this->revision])];}/** @param array<string,mixed> $checkpoint */public function restore(array $checkpoint):self {if(array_keys($checkpoint)!==['nodes','edges','revision','digest']||!is_array($checkpoint['nodes']??null)||!is_array($checkpoint['edges']??null)||!is_int($checkpoint['revision']??null)||$checkpoint['revision']<0||!is_string($checkpoint['digest']??null)||!hash_equals($checkpoint['digest'],PanelOperationsGuard::digest(['nodes'=>$checkpoint['nodes'],'edges'=>$checkpoint['edges'],'revision'=>$checkpoint['revision']]))){throw new \InvalidArgumentException('Lineage graph checkpoint is invalid.');}$probe=new self();foreach($checkpoint['nodes']as$id=>$node){if(!is_string($id)||!is_array($node)||array_keys($node)!==['id','kind','label','metadata']||$node['id']!==$id){throw new \InvalidArgumentException('Lineage graph checkpoint node is invalid.');}$probe->node($id,(string)$node['kind'],(string)$node['label'],is_array($node['metadata'])?$node['metadata']:[]);}foreach($checkpoint['edges']as$key=>$edge){if(!is_string($key)||!is_array($edge)||array_keys($edge)!==['from','to','kind','metadata']||$key!==hash('sha256',(string)$edge['from'].'|'.(string)$edge['kind'].'|'.(string)$edge['to'])){throw new \InvalidArgumentException('Lineage graph checkpoint edge is invalid.');}$probe->edge((string)$edge['from'],(string)$edge['to'],(string)$edge['kind'],is_array($edge['metadata'])?$edge['metadata']:[]);}$this->nodes=$checkpoint['nodes'];$this->edges=$checkpoint['edges'];$this->revision=$checkpoint['revision'];return$this;}
	/** @param list<string> $kinds @return list<array<string,mixed>> */private function traverse(string $id,string $direction,int $depth,array $kinds):array {$id=PanelOperationsGuard::identifier($id,'lineage node id',192);if(!isset($this->nodes[$id])){throw new \OutOfBoundsException('Lineage node is not registered.');}$depth=max(1,min(64,$depth));$kinds=$kinds===[]?[]:PanelOperationsGuard::names($kinds,'lineage edge kind');$seen=[$id=>true];$frontier=[$id];$result=[];for($level=0;$level<$depth&&$frontier!==[];$level++){$next=[];foreach($frontier as$current){foreach($this->edges as$edge){if($kinds!==[]&&!in_array($edge['kind'],$kinds,true)){continue;}$candidate=$direction==='out'&&$edge['from']===$current?$edge['to']:($direction==='in'&&$edge['to']===$current?$edge['from']:null);if($candidate===null||isset($seen[$candidate])){continue;}$seen[$candidate]=true;$next[]=$candidate;$result[]=$this->nodes[$candidate]+['depth'=>$level+1];}}$frontier=$next;}usort($result,static fn(array $a,array $b):int=>[$a['depth'],$a['id']]<=>[$b['depth'],$b['id']]);return$result;}
	/** @param list<string> $kinds */private function pathExists(string $from,string $to,array $kinds):bool {$queue=[$from];$seen=[];while($queue!==[]){$current=array_shift($queue);if($current===$to){return true;}if(isset($seen[$current])){continue;}$seen[$current]=true;foreach($this->edges as$edge){if($edge['from']===$current&&in_array($edge['kind'],$kinds,true)){$queue[]=$edge['to'];}}}return false;}
}
