<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Bounded deterministic semantic fallback over host-provided rows. */
final class PanelArraySemanticBackend implements PanelSemanticBackend,\JsonSerializable {
	private readonly \Closure $provider;private readonly ?\Closure $authorize;private readonly string $name;private readonly ?string $tenantField;private readonly bool $requireTenant;private readonly int $maxRows;private readonly bool $snapshotConsistent;
	/** @param array<string,mixed> $options */
	public function __construct(callable $provider,array $options=[]){
		$unknown=array_values(array_diff(array_keys($options),['name','authorize','tenant_field','require_tenant','max_rows','snapshot_consistent']));if($unknown!==[]){throw new \InvalidArgumentException('Unknown array semantic backend option: '.(string)$unknown[0]);}
		$this->provider=\Closure::fromCallable($provider);if(array_key_exists('authorize',$options)&&!is_callable($options['authorize'])){throw new \InvalidArgumentException('Array semantic authorization must be callable.');}$this->authorize=isset($options['authorize'])?\Closure::fromCallable($options['authorize']):null;
		$this->name=PanelOperationsGuard::name((string)($options['name']??'semantic_array'),'semantic backend');$tenant=array_key_exists('tenant_field',$options)?$options['tenant_field']:'tenant_id';if($tenant!==null&&!is_string($tenant)){throw new \InvalidArgumentException('Array semantic tenant_field must be a string or null.');}$this->tenantField=$tenant===null?null:PanelQueryPath::make($tenant)->value();$require=$options['require_tenant']??($this->tenantField!==null);if(!is_bool($require)||($require&&$this->tenantField===null)){throw new \InvalidArgumentException('Array semantic require_tenant needs a tenant field.');}$this->requireTenant=$require;
		$max=$options['max_rows']??100000;if(!is_int($max)||$max<1||$max>1000000){throw new \InvalidArgumentException('Array semantic max_rows must be between 1 and 1000000.');}$this->maxRows=$max;$snapshot=$options['snapshot_consistent']??true;if(!is_bool($snapshot)){throw new \InvalidArgumentException('Array semantic snapshot_consistent must be boolean.');}$this->snapshotConsistent=$snapshot;
	}
	public function name():string{return$this->name;}/** @return array<string,mixed> */public function capabilities():array{return['type'=>'panel_semantic_backend_capabilities','version'=>1,'backend'=>$this->name,'entities'=>'provider_defined','aggregations'=>PanelSemanticMetric::AGGREGATIONS,'typed_filters'=>true,'relations'=>true,'group_by'=>true,'multi_metric'=>true,'pushdown'=>false,'snapshot_consistent'=>$this->snapshotConsistent,'tenant'=>$this->tenantField!==null,'authorization'=>$this->authorize!==null,'max_rows'=>$this->maxRows,'max_groups'=>10000];}
	/** @return list<string> */public function unsupported(PanelSemanticExecutionPlan $plan):array{$missing=[];$query=$plan->query();if($this->authorize===null){$missing[]='authorization';}if($query->tenantKey()!==null&&$this->tenantField===null){$missing[]='tenant';}if($query->consistency()==='snapshot'&&!$this->snapshotConsistent){$missing[]='snapshot_consistency';}return$missing;}
	public function execute(PanelSemanticExecutionPlan $plan):PanelSemanticQueryResult{
		$missing=$this->unsupported($plan);if($missing!==[]){throw new PanelSemanticUnsupported($missing);}$query=$plan->query();if($this->requireTenant&&$query->tenantKey()===null){throw new PanelSemanticException('semantic_tenant_required','The semantic query requires an explicit tenant.',403);}
		try{$provided=($this->provider)($plan->entity(),$query,$plan);}catch(\Throwable $error){throw new PanelSemanticException('semantic_source_unavailable','The semantic row provider is unavailable.',503,true,$error);}if(!is_iterable($provided)){throw new PanelSemanticException('semantic_source_invalid','The semantic row provider returned an invalid result.',503,false);}
		$rows=[];foreach($provided as$row){if($row instanceof \JsonSerializable){$row=$row->jsonSerialize();}elseif(is_object($row)){$row=get_object_vars($row);}if(!is_array($row)||array_is_list($row)){throw new PanelSemanticException('semantic_source_invalid','The semantic row provider returned an invalid row.',503,false);}if(count($rows)>=$this->maxRows){throw new PanelSemanticException('semantic_row_limit','The semantic fallback row limit was exceeded.',422,false);}
			if($this->tenantField!==null){[$exists,$tenant]=$this->value($row,$this->tenantField);if(!$exists||($query->tenantKey()!==null&&(string)$tenant!==(string)$query->tenantKey())){continue;}}
			try{$decision=($this->authorize)($row,$query->authorizationMetadata(),$query->tenantKey(),$query,$plan);}catch(\Throwable $error){throw new PanelSemanticException('semantic_authorization_failed','Semantic row authorization failed.',403,false,$error);}if($decision===false||$decision===null){continue;}if($decision===true){}elseif(is_array($decision)&&!array_is_list($decision)){$row=$decision;}else{throw new PanelSemanticException('semantic_authorization_invalid','Semantic row authorization returned an invalid decision.',403,false);}if(!PanelQueryExpressionEvaluator::matches($row,$query->filter())){continue;}$rows[]=$row;}
		$groups=[];$defaults=[];foreach($plan->metrics()as$id=>$metric){$defaults[$id]=in_array($metric->aggregation(),['count','sum','distinct_count'],true)?0:null;foreach($metric->evaluate($rows,$query->dimensions())as$result){$key=PanelOperationsGuard::digest($result['dimensions']);$groups[$key]??=['dimensions'=>$result['dimensions'],'metrics'=>[]];$groups[$key]['metrics'][$id]=$result['value'];}}
		foreach($groups as&$group){$group['metrics']=array_replace($defaults,$group['metrics']);ksort($group['metrics'],SORT_STRING);}unset($group);$resultRows=array_values($groups);$this->sort($resultRows,$query);$total=count($resultRows);$page=array_slice($resultRows,$query->offset(),$query->limit());
		return new PanelSemanticQueryResult($plan,$page,$total,$this->name,false,$this->snapshotConsistent,['rows_scanned'=>count($rows),'groups'=>$total,'aggregation_pushdown'=>false,'filter_pushdown'=>false,'fallback'=>false]);
	}
	/** @param list<array{dimensions:array<string,mixed>,metrics:array<string,mixed>}> $rows */private function sort(array &$rows,PanelSemanticQuery $query):void{$sorts=$query->sorts();if($sorts===[]){$sorts=array_map(static fn(string $dimension):PanelSemanticSort=>PanelSemanticSort::asc($dimension),$query->dimensions());}usort($rows,function(array $left,array $right)use($sorts):int{foreach($sorts as$sort){$a=array_key_exists($sort->target(),$left['dimensions'])?$left['dimensions'][$sort->target()]:$left['metrics'][$sort->target()];$b=array_key_exists($sort->target(),$right['dimensions'])?$right['dimensions'][$sort->target()]:$right['metrics'][$sort->target()];$explicitNull=$a===null||$b===null;$comparison=$this->compare($a,$b,$sort->nulls());if($comparison!==0){return!$explicitNull&&$sort->direction()==='desc'?-$comparison:$comparison;}}return PanelOperationsGuard::json($left['dimensions'])<=>PanelOperationsGuard::json($right['dimensions']);});}
	private function compare(mixed $a,mixed $b,string $nulls):int{if($a===null||$b===null){if($a===$b){return 0;}return$a===null?($nulls==='first'?-1:1):($nulls==='first'?1:-1);}if(is_numeric($a)&&is_numeric($b)){return(float)$a<=>(float)$b;}return strnatcasecmp((string)$a,(string)$b);}
	/** @param array<string,mixed> $row @return array{bool,mixed} */private function value(array $row,string $path):array{$current=$row;foreach(explode('.',$path)as$segment){if(!is_array($current)||!array_key_exists($segment,$current)){return[false,null];}$current=$current[$segment];}return[true,$current];}
	/** @return array<string,mixed> */public function jsonSerialize():array{return['type'=>'panel_array_semantic_backend_manifest','version'=>1,'name'=>$this->name,'capabilities'=>$this->capabilities(),'provider_serialized'=>false,'authorization_callback_serialized'=>false,'default_deny'=>$this->authorize===null];}
}
