<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Production semantic pushdown over an allowlisted SQL schema. */
final class PanelSqlSemanticBackend implements PanelSemanticBackend,\JsonSerializable {
	private readonly string $name;private readonly string $entity;private readonly string $driver;private readonly ?\Closure $authorize;private readonly bool $snapshotConsistent;private readonly int $maxGroups;/** @var array<string,mixed> */private readonly array $executorManifest;
	/** @param array<string,mixed> $options */
	public function __construct(private readonly PanelSqlExecutor $executor,private readonly PanelSqlSchema $schema,string $entity,array $options=[]){
		$unknown=array_values(array_diff(array_keys($options),['name','authorize','snapshot_consistent','max_groups']));if($unknown!==[]){throw new \InvalidArgumentException('Unknown SQL semantic backend option: '.(string)$unknown[0]);}
		$this->entity=PanelOperationsGuard::name($entity,'semantic entity');$this->name=PanelOperationsGuard::name((string)($options['name']??'semantic_sql'),'semantic backend');if(array_key_exists('authorize',$options)&&!is_callable($options['authorize'])){throw new \InvalidArgumentException('SQL semantic authorization must be callable.');}$this->authorize=isset($options['authorize'])?\Closure::fromCallable($options['authorize']):null;
		$snapshot=$options['snapshot_consistent']??false;if(!is_bool($snapshot)){throw new \InvalidArgumentException('SQL semantic snapshot_consistent must be boolean.');}$this->snapshotConsistent=$snapshot;$max=$options['max_groups']??100000;if(!is_int($max)||$max<1||$max>1000000){throw new \InvalidArgumentException('SQL semantic max_groups must be between 1 and 1000000.');}$this->maxGroups=$max;
		try{$driver=strtolower(trim($executor->driver()));$manifest=PanelSearchSanitizer::value($executor->manifest());}catch(\Throwable $error){throw new \InvalidArgumentException('SQL semantic executor inspection failed.',0,$error);}if(!in_array($driver,['mysql','pgsql','sqlite'],true)){throw new \InvalidArgumentException('SQL semantic executor driver is unsupported.');}if(!is_array($manifest)||($manifest!==[]&&array_is_list($manifest))){throw new \InvalidArgumentException('SQL semantic executor manifest is invalid.');}$this->driver=$driver;$this->executorManifest=$manifest;
	}
	/** @param array<string,mixed> $options */public static function usingPdo(\PDO $pdo,PanelSqlSchema $schema,string $entity,array $options=[]):self{return new self(new PanelPdoSqlExecutor($pdo),$schema,$entity,$options);}
	public function name():string{return$this->name;}/** @return array<string,mixed> */public function capabilities():array{return['type'=>'panel_semantic_backend_capabilities','version'=>1,'backend'=>$this->name,'adapter'=>'sql','driver'=>$this->driver,'entities'=>[$this->entity],'aggregations'=>PanelSemanticMetric::AGGREGATIONS,'typed_filters'=>true,'relations'=>false,'group_by'=>true,'multi_metric'=>true,'pushdown'=>true,'filter_pushdown'=>true,'aggregation_pushdown'=>true,'pagination_pushdown'=>true,'snapshot_consistent'=>$this->snapshotConsistent,'tenant'=>$this->schema->tenantField()!==null,'authorization'=>$this->authorize!==null,'max_groups'=>$this->maxGroups,'values_parameterized'=>true];}
	/** @return list<string> */public function unsupported(PanelSemanticExecutionPlan $plan):array{$missing=[];if($plan->entity()!==$this->entity){$missing[]='entity:'.$plan->entity();}if($this->authorize===null){$missing[]='authorization';}foreach($plan->requiredFields()as$field){if(!$this->schema->hasField($field)){$missing[]='field:'.$field;}}$query=$plan->query();if($query->tenantKey()!==null&&$this->schema->tenantField()===null){$missing[]='tenant';}if($query->filter()!==null&&$this->hasRelation($query->filter())){$missing[]='relations';}if($query->consistency()==='snapshot'&&!$this->snapshotConsistent){$missing[]='snapshot_consistency';}return array_values(array_unique($missing));}
	public function execute(PanelSemanticExecutionPlan $plan):PanelSemanticQueryResult{
		$missing=$this->unsupported($plan);if($missing!==[]){throw new PanelSemanticUnsupported($missing);}$query=$plan->query();if($this->schema->requiresTenant()&&$query->tenantKey()===null){throw new PanelSemanticException('semantic_tenant_required','The semantic SQL query requires an explicit tenant.',403,false);}$scope=$this->authorizationScope($plan);
		try{$compiled=(new PanelSqlSemanticCompiler($this->schema,$this->driver))->compile($plan,$scope);$total=1;if($compiled->countSql()!==null){$value=$this->executor->scalar($compiled->countSql(),$compiled->countParameters());$total=$this->integer($value);if($total>$this->maxGroups){throw new PanelSemanticException('semantic_group_limit','The semantic query exceeds the configured group limit.',422,false);}}$raw=$this->executor->rows($compiled->dataSql(),$compiled->dataParameters());}
		catch(PanelSemanticException $error){throw$error;}catch(PanelSemanticUnsupported $error){throw$error;}catch(\Throwable $error){throw new PanelSemanticException('semantic_storage_unavailable','The semantic SQL backend is unavailable.',503,true,$error);}
		if(count($raw)>$query->limit()){throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL backend violated its row bound.',503,false);}$rows=[];foreach($raw as$row){if(!is_array($row)||array_is_list($row)){throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL backend returned an invalid row.',503,false);}$dimensions=[];foreach($compiled->dimensionAliases()as$field=>$alias){if(!array_key_exists($alias,$row)){throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL projection is incomplete.',503,false);}$dimensions[$field]=$row[$alias];}$metrics=[];foreach($compiled->metricAliases()as$id=>$alias){if(!array_key_exists($alias,$row)){throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL projection is incomplete.',503,false);}$metrics[$id]=$this->metricValue($row[$alias],$plan->metrics()[$id]->aggregation());}ksort($metrics,SORT_STRING);$rows[]=['dimensions'=>$dimensions,'metrics'=>$metrics];}
		return new PanelSemanticQueryResult($plan,$rows,$total,$this->name,true,$this->snapshotConsistent,['driver'=>$this->driver,'compiled_fingerprint'=>$compiled->fingerprint(),'queries'=>$compiled->countSql()===null?1:2,'aggregation_pushdown'=>true,'filter_pushdown'=>true,'pagination_pushdown'=>true,'sql_serialized'=>false,'parameters_serialized'=>false]);
	}
	private function authorizationScope(PanelSemanticExecutionPlan $plan):?PanelQueryExpression{if($this->authorize===null){throw new PanelSemanticException('semantic_authorization_required','The semantic SQL backend has no authorizer.',403,false);}try{$decision=($this->authorize)($plan->query()->authorizationMetadata(),$plan->query()->tenantKey(),$plan->query(),$plan,$this->schema);}catch(\Throwable $error){throw new PanelSemanticException('semantic_authorization_failed','Semantic SQL authorization failed.',403,false,$error);}if($decision===true){return null;}if($decision instanceof PanelQueryExpression){if($this->hasRelation($decision)){throw new PanelSemanticException('semantic_authorization_invalid','Semantic SQL authorization cannot introduce relation scopes.',403,false);}foreach($decision->fields()as$field){if(!$this->schema->hasField($field)){throw new PanelSemanticException('semantic_authorization_invalid','Semantic SQL authorization referenced an unknown field.',403,false);}}return$decision;}if($decision===false||$decision===null){throw new PanelSemanticException('semantic_access_denied','The semantic query is not authorized.',403,false);}throw new PanelSemanticException('semantic_authorization_invalid','Semantic SQL authorization returned an invalid decision.',403,false);}
	private function hasRelation(PanelQueryExpression $expression):bool{if($expression instanceof PanelQueryRelation){return true;}if($expression instanceof PanelQueryGroup){foreach($expression->children()as$child){if($this->hasRelation($child)){return true;}}}return false;}
	private function integer(mixed $value):int{if(is_int($value)){$number=$value;}elseif(is_string($value)&&preg_match('/^(0|[1-9][0-9]*)$/D',$value)===1&&strlen($value)<=strlen((string)PHP_INT_MAX)){$number=(int)$value;if((string)$number!==$value){throw new \UnexpectedValueException();}}else{throw new \UnexpectedValueException();}if($number<0){throw new \UnexpectedValueException();}return$number;}
	private function metricValue(mixed $value,string $aggregation):mixed{if($value===null){return null;}if(in_array($aggregation,['count','distinct_count'],true)){return$this->integer($value);}if(in_array($aggregation,['sum','average','ratio'],true)){if(!is_numeric($value)){throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL backend returned a non-numeric metric.',503,false);}return str_contains((string)$value,'.')?(float)$value:(int)$value;}if(is_scalar($value)){return$value;}throw new PanelSemanticException('semantic_storage_invalid','The semantic SQL backend returned a non-scalar metric.',503,false);}
	/** @return array<string,mixed> */public function jsonSerialize():array{return['type'=>'panel_sql_semantic_backend_manifest','version'=>1,'name'=>$this->name,'entity'=>$this->entity,'schema_name'=>$this->schema->name(),'schema_fingerprint'=>$this->schema->fingerprint(),'executor'=>$this->executorManifest,'capabilities'=>$this->capabilities(),'authorization'=>['configured'=>$this->authorize!==null,'fail_closed'=>true,'callback_serialized'=>false],'security'=>['raw_sql_accepted'=>false,'identifiers_allowlisted'=>true,'values_parameterized'=>true,'sql_serialized'=>false,'parameters_serialized'=>false,'authority_serialized'=>false]];}
}
