<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2025 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre;

/**
 * Wraps a form-scoped CSRF token.
 *
 * CsrfToken lazily reads and caches the token generated by the core runtime for
 * one form name, can force a refresh, validates submitted tokens through the core
 * CSRF verifier, and can render a safe hidden input for server-rendered forms.
 */
final class CsrfToken implements \JsonSerializable {

	private ?string $token=null;

	/**
	 * Stores the form scope for token generation and validation.
	 *
	 * @param string $formName Form scope used by the core CSRF runtime.
	 */
	private function __construct(
		private readonly string $formName
	){}

	/**
	 * Creates a CSRF token wrapper for a form scope.
	 *
	 * @param string $formName Form scope used by the core CSRF runtime.
	 * @return self Token wrapper for the normalized form name.
	 */
	public static function for(string $formName): self {
		return new self(trim($formName));
	}

	/**
	 * Returns the form scope for this token.
	 *
	 * @return string Form name passed to core CSRF helpers.
	 */
	public function formName(): string {
		return $this->formName;
	}

	/**
	 * Returns the current token value, generating it lazily when needed.
	 *
	 * The value is cached on the wrapper so repeated rendering calls during the
	 * same response emit the same token.
	 *
	 * @return string CSRF token value, or an empty string when the core helper returns a non-string.
	 */
	public function value(): string {
		if($this->token===null){
			$value=\dataphyre\core::csrf($this->formName);
			$this->token=is_string($value) ? $value : '';
		}
		return $this->token;
	}

	/**
	 * Clears the cached token value.
	 *
	 *
	 */
	public function refresh(): self {
		$this->token=null;
		return $this;
	}

	/**
	 * Validates a submitted token through the core CSRF verifier.
	 *
	 * @param mixed $token Submitted token value.
	 * @return bool True when the core verifier accepts the token for this form.
	 */
	public function validate(#[\SensitiveParameter] mixed $token): bool {
		return \dataphyre\core::csrf($this->formName, $token)===true;
	}

	/**
	 * Compares a submitted token with the current cached/generated token.
	 *
	 * This is a timing-safe local comparison and does not rotate or otherwise
	 * mutate core CSRF state.
	 *
	 * @param mixed $token Submitted token value.
	 * @return bool True when the submitted token exactly matches the current value.
	 */
	public function equals(#[\SensitiveParameter] mixed $token): bool {
		$value=$this->value();
		return is_string($token) && $value!=='' && hash_equals($value, $token);
	}

	/**
	 * Renders a hidden form field containing the CSRF token.
	 *
	 * Field name and token value are escaped for HTML attribute context.
	 *
	 * @param string $fieldName Hidden input name, defaulting to `csrf` when empty.
	 * @return string HTML hidden input.
	 */
	public function hiddenField(string $fieldName='csrf'): string {
		$fieldName=trim($fieldName);
		if($fieldName===''){
			$fieldName='csrf';
		}
		return '<input type="hidden" name="'.htmlspecialchars($fieldName, ENT_QUOTES, 'UTF-8').'" value="'.htmlspecialchars($this->value(), ENT_QUOTES, 'UTF-8').'">';
	}

	/**
	 * Returns the form scope and lazily generated token value.
	 *
	 * This exposes CSRF material for callers that intentionally embed tokens in a
	 * JSON response or diagnostic structure. Avoid logging this array.
	 *
	 * @return array{form_name: string, token: string}
	 */
	public function toArray(): array {
		return [
			'form_name'=>$this->formName,
			'token'=>$this->value(),
		];
	}

	/**
	 * Serializes the token wrapper for JSON responses.
	 *
	 * @return array{form_name: string, token: string}
	 */
	public function jsonSerialize(): array {
		return $this->toArray();
	}

	/**
	 * Returns the token value as the string representation.
	 *
	 * String casting exposes the same sensitive token returned by value().
	 *
	 * @return string CSRF token value.
	 */
	public function __toString(): string {
		return $this->value();
	}
}
