<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

trait PanelRendererAssetsDataSurfaceCss {
	private static function dataSurfaceCss(): string {
		return <<<'CSS'
.dp-panel .dp-data-surface{--dp-data-surface-gap:clamp(10px,1.4cqi,16px);--dp-data-surface-border:var(--dp-border,#cbd5e1);--dp-data-surface-bg:var(--dp-surface,#fff);--dp-data-surface-muted:var(--dp-text_muted,#64748b);container-name:dp-data-surface;container-type:inline-size;min-inline-size:0;max-inline-size:100%;border:1px solid var(--dp-data-surface-border);border-radius:var(--dp-radius,14px);background:var(--dp-data-surface-bg);color:var(--dp-text,#0f172a);isolation:isolate}
.dp-panel .dp-data-surface[aria-busy="true"]{cursor:progress}.dp-panel .dp-data-surface__header{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--dp-data-surface-gap);padding:clamp(14px,2cqi,22px);border-block-end:1px solid var(--dp-data-surface-border)}
.dp-panel .dp-data-surface__header h2{margin:0;font-size:clamp(1rem,2.5cqi,1.25rem);font-weight:700;line-height:1.25}.dp-panel .dp-data-surface__description,.dp-panel .dp-data-surface__status{margin:.35rem 0 0;color:var(--dp-data-surface-muted);font-size:.875rem;line-height:1.45}.dp-panel .dp-data-surface__status{flex:0 1 auto;max-inline-size:34ch;text-align:end}
.dp-panel .dp-data-surface__viewport{min-inline-size:0}.dp-panel .dp-data-surface__spacer{display:block;min-block-size:0;pointer-events:none}.dp-panel .dp-data-surface__table-shell{min-inline-size:0;max-inline-size:100%}.dp-panel .dp-data-surface__table{inline-size:100%;max-inline-size:100%;border-collapse:collapse;table-layout:fixed}
.dp-panel .dp-data-surface__table caption{position:absolute;inline-size:1px;block-size:1px;margin:-1px;padding:0;border:0;overflow:hidden;clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap}
.dp-panel .dp-data-surface__table :is(th,td){min-inline-size:0;padding:clamp(10px,1.5cqi,15px);border-block-end:1px solid var(--dp-data-surface-border);text-align:start;vertical-align:top;overflow-wrap:anywhere}.dp-panel .dp-data-surface__table th{color:var(--dp-data-surface-muted);font-size:.75rem;font-weight:750;letter-spacing:.035em;text-transform:uppercase}.dp-panel .dp-data-surface__table tbody tr:last-child td{border-block-end:0}
.dp-panel .dp-data-surface__items{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,17rem),1fr));gap:var(--dp-data-surface-gap);margin:0;padding:var(--dp-data-surface-gap);list-style:none}.dp-panel .dp-data-surface--list .dp-data-surface__items,.dp-panel .dp-data-surface--timeline .dp-data-surface__items,.dp-panel .dp-data-surface--calendar .dp-data-surface__items{grid-template-columns:minmax(0,1fr)}
.dp-panel .dp-data-surface__item{min-inline-size:0;border:1px solid var(--dp-data-surface-border);border-radius:var(--dp-radius,10px);background:color-mix(in srgb,var(--dp-data-surface-bg) 94%,currentColor 6%)}.dp-panel .dp-data-surface__item article{display:flex;align-items:flex-start;gap:12px;min-inline-size:0;padding:clamp(12px,1.7cqi,18px)}.dp-panel .dp-data-surface__item-body{min-inline-size:0;flex:1}.dp-panel .dp-data-surface__item h3{margin:0;font-size:.975rem;line-height:1.3;overflow-wrap:anywhere}.dp-panel .dp-data-surface__item p{margin:.45rem 0 0;color:var(--dp-data-surface-muted);font-size:.875rem;line-height:1.45;overflow-wrap:anywhere}.dp-panel .dp-data-surface__item time{display:block;margin-block-start:.4rem;color:var(--dp-data-surface-muted);font-size:.8rem}.dp-panel .dp-data-surface__item footer{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-block-start:.75rem;color:var(--dp-data-surface-muted);font-size:.8rem}.dp-panel .dp-data-surface__image{inline-size:clamp(54px,8cqi,84px);aspect-ratio:1;flex:none;object-fit:cover;border-radius:8px;background:color-mix(in srgb,currentColor 8%,transparent)}.dp-panel .dp-data-surface__badge{display:inline-flex;align-items:center;min-block-size:24px;padding-inline:9px;border:1px solid currentColor;border-radius:999px;font-weight:700}
.dp-panel .dp-data-surface--gallery .dp-data-surface__items{grid-template-columns:repeat(auto-fit,minmax(min(100%,12rem),1fr))}.dp-panel .dp-data-surface--gallery .dp-data-surface__item article{display:block}.dp-panel .dp-data-surface--gallery .dp-data-surface__image{inline-size:100%;aspect-ratio:4/3;margin-block-end:12px}.dp-panel .dp-data-surface--timeline .dp-data-surface__item{border-inline-start:3px solid var(--dp-primary-600,#2563eb)}
.dp-panel .dp-data-canvas__table-shell{min-inline-size:0;max-inline-size:100%;overflow:clip}.dp-panel .dp-data-canvas__table{inline-size:100%;max-inline-size:100%;border-collapse:collapse;table-layout:fixed}.dp-panel .dp-data-canvas__table :is(th,td){min-inline-size:0;padding:clamp(8px,1.25cqi,13px);border-block-end:1px solid var(--dp-data-surface-border);border-inline-end:1px solid color-mix(in srgb,var(--dp-data-surface-border) 72%,transparent);text-align:start;vertical-align:middle;overflow-wrap:anywhere}.dp-panel .dp-data-canvas__table :is(th,td):last-child{border-inline-end:0}.dp-panel .dp-data-canvas__table thead th{background:color-mix(in srgb,var(--dp-data-surface-bg) 88%,var(--dp-primary-600,#2563eb) 12%);color:var(--dp-data-surface-muted);font-size:.72rem;font-weight:780;letter-spacing:.035em;text-transform:uppercase}.dp-panel .dp-data-canvas__table tbody tr:last-child :is(th,td){border-block-end:0}.dp-panel .dp-data-canvas__row-number{inline-size:3.5rem;color:var(--dp-data-surface-muted);font-variant-numeric:tabular-nums}.dp-panel .dp-data-canvas__spreadsheet [data-frozen="true"]{background:color-mix(in srgb,var(--dp-data-surface-bg) 94%,var(--dp-primary-600,#2563eb) 6%)}
.dp-panel .dp-data-canvas__matrix-cell{padding:4px;background:color-mix(in srgb,var(--dp-primary-600,#2563eb) calc(var(--dp-data-canvas-intensity,0)*32%),var(--dp-data-surface-bg))}.dp-panel .dp-data-canvas__matrix-value{display:grid;gap:2px;min-block-size:58px;padding:8px;border-radius:8px}.dp-panel .dp-data-canvas__matrix-value strong{font-variant-numeric:tabular-nums}.dp-panel .dp-data-canvas__matrix-value>span{color:var(--dp-data-surface-muted);font-size:.72rem}
.dp-panel .dp-data-canvas__tree,.dp-panel .dp-data-canvas__graph-edges,.dp-panel .dp-data-canvas__gantt{display:grid;gap:0;margin:0;padding:0;list-style:none}.dp-panel .dp-data-canvas__tree-node{display:grid;grid-template-columns:18px minmax(0,1fr);gap:9px;min-inline-size:0;margin-inline-start:min(calc(var(--dp-data-tree-depth,0)*clamp(12px,2.4cqi,28px)),45%);padding:12px clamp(12px,1.8cqi,18px);border-block-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-canvas__tree-node:last-child{border-block-end:0}.dp-panel .dp-data-canvas__tree-branch{position:relative;align-self:stretch;border-inline-start:2px solid color-mix(in srgb,var(--dp-primary-600,#2563eb) 62%,var(--dp-data-surface-border))}.dp-panel .dp-data-canvas__tree-branch::after{position:absolute;inset-block-start:12px;inset-inline-start:0;inline-size:10px;border-block-start:2px solid currentColor;content:""}.dp-panel .dp-data-canvas__tree-node>div{display:grid;gap:3px;min-inline-size:0}.dp-panel .dp-data-canvas__tree-node :is(span,small){color:var(--dp-data-surface-muted);overflow-wrap:anywhere}
.dp-panel .dp-data-canvas__graph{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(min(100%,17rem),.7fr);min-inline-size:0}.dp-panel .dp-data-canvas__graph-stage{position:relative;min-block-size:clamp(290px,46cqi,560px);overflow:clip;background:radial-gradient(circle at center,color-mix(in srgb,var(--dp-primary-600,#2563eb) 8%,transparent),transparent 68%),linear-gradient(color-mix(in srgb,var(--dp-data-surface-border) 32%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--dp-data-surface-border) 32%,transparent) 1px,transparent 1px);background-size:auto,32px 32px,32px 32px;border-inline-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-canvas__graph-stage svg{position:absolute;inset:4%;inline-size:92%;block-size:92%;overflow:visible}.dp-panel .dp-data-canvas__graph-stage line{stroke:color-mix(in srgb,var(--dp-primary-600,#2563eb) 55%,var(--dp-data-surface-border));stroke-width:1.2}.dp-panel .dp-data-canvas__graph-node{position:absolute;inset-inline-start:clamp(42px,var(--dp-canvas-x),calc(100% - 42px));inset-block-start:clamp(34px,var(--dp-canvas-y),calc(100% - 34px));display:grid;min-inline-size:76px;max-inline-size:130px;padding:7px 9px;border:1px solid var(--dp-primary-600,#2563eb);border-radius:9px;background:var(--dp-data-surface-bg);text-align:center;transform:translate(-50%,-50%);box-shadow:0 7px 18px color-mix(in srgb,var(--dp-text,#0f172a) 14%,transparent)}.dp-panel .dp-data-canvas__graph-node strong{font-size:.78rem;overflow-wrap:anywhere}.dp-panel .dp-data-canvas__graph-node small{color:var(--dp-data-surface-muted);font-size:.68rem}.dp-panel .dp-data-canvas__graph-edges{align-content:start;max-block-size:560px;overflow-block:auto}.dp-panel .dp-data-canvas__graph-edge{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:8px;padding:11px 13px;border-block-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-canvas__graph-edge .dp-data-canvas__drill{grid-column:2}
.dp-panel .dp-data-canvas__gantt-task{display:grid;grid-template-columns:minmax(10rem,26%) minmax(0,1fr) auto;align-items:center;gap:clamp(10px,1.8cqi,18px);padding:12px clamp(12px,1.8cqi,18px);border-block-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-canvas__gantt-task:last-child{border-block-end:0}.dp-panel .dp-data-canvas__gantt-label{display:grid;gap:3px;min-inline-size:0}.dp-panel .dp-data-canvas__gantt-label>span{color:var(--dp-data-surface-muted);font-size:.72rem;overflow-wrap:anywhere}.dp-panel .dp-data-canvas__gantt-track{position:relative;block-size:22px;border:1px solid var(--dp-data-surface-border);border-radius:999px;background:color-mix(in srgb,var(--dp-data-surface-bg) 88%,currentColor 12%);overflow:clip}.dp-panel .dp-data-canvas__gantt-track>span{position:absolute;inset-block:3px;inset-inline-start:var(--dp-gantt-left);inline-size:max(4px,var(--dp-gantt-width));border-radius:999px;background:linear-gradient(90deg,var(--dp-primary-600,#2563eb) var(--dp-gantt-progress),color-mix(in srgb,var(--dp-primary-600,#2563eb) 34%,var(--dp-data-surface-bg)) var(--dp-gantt-progress))}
.dp-panel .dp-data-canvas__map,.dp-panel .dp-data-canvas__freeform{position:relative;min-inline-size:0;min-block-size:clamp(320px,54cqi,680px);overflow:clip;background-color:color-mix(in srgb,var(--dp-data-surface-bg) 94%,var(--dp-primary-600,#2563eb) 6%)}.dp-panel .dp-data-canvas__map{background-image:linear-gradient(color-mix(in srgb,var(--dp-data-surface-border) 45%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--dp-data-surface-border) 45%,transparent) 1px,transparent 1px),radial-gradient(ellipse at 30% 45%,color-mix(in srgb,var(--dp-primary-600,#2563eb) 12%,transparent),transparent 34%),radial-gradient(ellipse at 68% 62%,color-mix(in srgb,var(--dp-primary-600,#2563eb) 10%,transparent),transparent 31%);background-size:10% 10%,10% 10%,auto,auto}.dp-panel .dp-data-canvas__map-point{position:absolute;inset-inline-start:clamp(64px,var(--dp-canvas-x),calc(100% - 64px));inset-block-start:clamp(48px,var(--dp-canvas-y),calc(100% - 48px));display:grid;justify-items:center;max-inline-size:132px;padding:8px;border:1px solid var(--dp-data-surface-border);border-radius:9px;background:var(--dp-data-surface-bg);text-align:center;transform:translate(-50%,-50%)}.dp-panel .dp-data-canvas__map-pin{inline-size:13px;block-size:13px;border:3px solid var(--dp-data-surface-bg);border-radius:50%;background:var(--dp-primary-600,#2563eb);box-shadow:0 0 0 2px var(--dp-primary-600,#2563eb)}.dp-panel .dp-data-canvas__map-point strong{font-size:.76rem;overflow-wrap:anywhere}.dp-panel .dp-data-canvas__map-point small{color:var(--dp-data-surface-muted);font-size:.66rem}.dp-panel .dp-data-canvas__freeform{background-image:linear-gradient(color-mix(in srgb,var(--dp-data-surface-border) 36%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--dp-data-surface-border) 36%,transparent) 1px,transparent 1px);background-size:24px 24px}.dp-panel .dp-data-canvas__freeform-item{position:absolute;inset-inline-start:var(--dp-canvas-x);inset-block-start:var(--dp-canvas-y);inline-size:max(72px,var(--dp-canvas-width));block-size:max(52px,var(--dp-canvas-height));display:grid;align-content:start;gap:4px;min-inline-size:0;min-block-size:0;padding:10px;border:1px solid var(--dp-primary-600,#2563eb);border-radius:9px;background:color-mix(in srgb,var(--dp-data-surface-bg) 93%,var(--dp-primary-600,#2563eb) 7%);overflow:clip}.dp-panel .dp-data-canvas__freeform-item :is(strong,span){overflow-wrap:anywhere}.dp-panel .dp-data-canvas__freeform-item span{color:var(--dp-data-surface-muted);font-size:.75rem}
.dp-panel .dp-data-canvas__drill{display:inline-flex;align-items:center;inline-size:max-content;max-inline-size:100%;margin-block-start:4px;color:var(--dp-primary-600,#2563eb);font-size:.75rem;font-weight:700}.dp-panel .dp-data-surface [data-dp-data-canvas-select]{cursor:pointer}.dp-panel .dp-data-surface [data-dp-data-canvas-select][aria-selected="true"]{outline:3px solid var(--dp-primary-600,#2563eb);outline-offset:-3px;background-color:color-mix(in srgb,var(--dp-primary-600,#2563eb) 14%,var(--dp-data-surface-bg))}
.dp-panel .dp-data-surface .dp-data-surface__empty{padding:clamp(22px,5cqi,48px);text-align:center;color:var(--dp-data-surface-muted)}.dp-panel .dp-data-surface__controls{display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:12px clamp(14px,2cqi,22px);border-block-start:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-surface__controls[hidden]{display:none}.dp-panel .dp-data-surface__controls button{min-block-size:42px}.dp-panel .dp-data-surface :where([data-dp-data-surface-item]):focus-visible{outline:3px solid var(--dp-primary-600,#2563eb);outline-offset:-3px}
@container dp-data-surface (max-width:600px){.dp-panel .dp-data-surface__header{display:block}.dp-panel .dp-data-surface__status{max-inline-size:none;text-align:start}.dp-panel .dp-data-surface__table,.dp-panel .dp-data-surface__table :is(thead,tbody,tr,th,td){display:block;inline-size:100%}.dp-panel .dp-data-surface__table thead{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}.dp-panel .dp-data-surface__table tbody{display:grid;gap:10px;padding:10px}.dp-panel .dp-data-surface__table tbody tr{border:1px solid var(--dp-data-surface-border);border-radius:10px}.dp-panel .dp-data-surface__table td{display:grid;grid-template-columns:minmax(7rem,38%) minmax(0,1fr);gap:10px;border-block-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-surface__table td::before{content:attr(data-label);color:var(--dp-data-surface-muted);font-size:.72rem;font-weight:750;letter-spacing:.03em;text-transform:uppercase}.dp-panel .dp-data-surface__table tr td:last-child{border-block-end:0}.dp-panel .dp-data-surface__items{grid-template-columns:minmax(0,1fr)}.dp-panel .dp-data-surface__controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.dp-panel .dp-data-surface__controls button{inline-size:100%;min-inline-size:0;padding-inline:6px}}
@container dp-data-surface (max-width:600px){.dp-panel .dp-data-canvas__table,.dp-panel .dp-data-canvas__table :is(thead,tbody,tr,th,td){display:block;inline-size:100%}.dp-panel .dp-data-canvas__table thead{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}.dp-panel .dp-data-canvas__table tbody{display:grid;gap:10px;padding:10px}.dp-panel .dp-data-canvas__table tbody tr{border:1px solid var(--dp-data-surface-border);border-radius:10px;overflow:clip}.dp-panel .dp-data-canvas__table tbody tr>th{background:color-mix(in srgb,var(--dp-data-surface-bg) 88%,var(--dp-primary-600,#2563eb) 12%)}.dp-panel .dp-data-canvas__table td{display:grid;grid-template-columns:minmax(6.5rem,34%) minmax(0,1fr);gap:10px;border-inline-end:0}.dp-panel .dp-data-canvas__table td::before{content:attr(data-label);align-self:center;color:var(--dp-data-surface-muted);font-size:.7rem;font-weight:750;letter-spacing:.03em;text-transform:uppercase}.dp-panel .dp-data-canvas__matrix-cell{padding:5px}.dp-panel .dp-data-canvas__matrix-value{min-block-size:50px}.dp-panel .dp-data-canvas__row-number{inline-size:auto}.dp-panel .dp-data-canvas__graph{grid-template-columns:minmax(0,1fr)}.dp-panel .dp-data-canvas__graph-stage{min-block-size:340px;border-inline-end:0;border-block-end:1px solid var(--dp-data-surface-border)}.dp-panel .dp-data-canvas__graph-edges{max-block-size:none}.dp-panel .dp-data-canvas__gantt-task{grid-template-columns:minmax(0,1fr);gap:8px}.dp-panel .dp-data-canvas__tree-node{margin-inline-start:min(calc(var(--dp-data-tree-depth,0)*12px),30%)}.dp-panel .dp-data-canvas__map,.dp-panel .dp-data-canvas__freeform{position:static;display:grid;gap:10px;min-block-size:0;padding:10px;background-image:none}.dp-panel .dp-data-canvas__map-point,.dp-panel .dp-data-canvas__freeform-item{position:static;inset:auto;inline-size:100%;block-size:auto;min-block-size:54px;max-inline-size:none;justify-items:start;text-align:start;transform:none}.dp-panel .dp-data-canvas__map-point{grid-template-columns:auto minmax(0,1fr);align-items:center}.dp-panel .dp-data-canvas__map-point :is(small,.dp-data-canvas__drill){grid-column:2}.dp-panel .dp-data-canvas__freeform-item{overflow:visible}}
[dir="rtl"] .dp-panel .dp-data-surface__status{text-align:start}[dir="rtl"] .dp-panel .dp-data-surface--timeline .dp-data-surface__item{border-inline-start-width:3px;border-inline-end-width:1px}
@media(forced-colors:active){.dp-panel .dp-data-surface,.dp-panel .dp-data-surface :where(.dp-data-surface__item,.dp-data-surface__table td,.dp-data-surface__table th,.dp-data-canvas__table td,.dp-data-canvas__table th,.dp-data-canvas__tree-node,.dp-data-canvas__graph-node,.dp-data-canvas__graph-edge,.dp-data-canvas__gantt-task,.dp-data-canvas__map-point,.dp-data-canvas__freeform-item){border-color:CanvasText;background:Canvas;color:CanvasText;forced-color-adjust:auto}.dp-panel .dp-data-surface :where([data-dp-data-surface-item]):focus-visible,.dp-panel .dp-data-surface [data-dp-data-canvas-select][aria-selected="true"]{outline-color:Highlight}.dp-panel .dp-data-canvas__graph-stage line{stroke:CanvasText}}
@media print{.dp-panel .dp-data-surface .dp-data-surface__controls,.dp-panel .dp-data-surface .dp-data-surface__spacer{display:none}.dp-panel .dp-data-surface{break-inside:avoid;border-color:#111}.dp-panel :is(.dp-data-surface__table,.dp-data-canvas__table){table-layout:auto}.dp-panel :is(.dp-data-canvas__map,.dp-data-canvas__freeform){position:static;display:grid;gap:8px;min-block-size:0;background:none}.dp-panel :is(.dp-data-canvas__map-point,.dp-data-canvas__freeform-item){position:static;inset:auto;inline-size:auto;block-size:auto;transform:none}.dp-panel .dp-data-canvas__graph{grid-template-columns:1fr}.dp-panel .dp-data-canvas__graph-stage{min-block-size:320px;border-inline-end:0}}
CSS;
	}
}
