<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/**
 * Emits the browser runtime script used by generated Panel pages.
 *
 * The script coordinates client-side panel interactions that are configured by
 * server-rendered DOM attributes and JSON payloads.
 */
trait PanelRendererAssetsScripts {
	/**
	 * Returns the browser runtime script for generated Panel interactions.
	 *
	 * The script manages localization lookup, live refresh, partial rendering,
	 * modal flows, command palette behavior, table affordances, uploads, and other
	 * client-side state transitions. Dynamic data is supplied through generated DOM
	 * attributes and JSON script tags rather than interpolated into this string.
	 *
	 * @return string JavaScript source emitted into the panel asset bundle.
	 */
	private static function script(): string {
		return <<<'JS'
var dpPanelLocalizationCache=null;
/**
 * Loads the generated Panel localization payload once for the browser runtime.
 *
 * The payload is read from the server-rendered JSON script tag and cached for
 * the lifetime of the page. Malformed or missing JSON fails closed to an empty
 * translation map so generated UI controls can continue operating.
 *
 * @returns {{translations: Object}} Localization state keyed by translation id.
 */
function dpPanelLocalization(){
	if(dpPanelLocalizationCache){return dpPanelLocalizationCache;}
	var node=document.querySelector("script[data-dp-panel-localization]");
	if(!node){
		dpPanelLocalizationCache={translations:{}};
		return dpPanelLocalizationCache;
	}
	try{
		dpPanelLocalizationCache=JSON.parse(node.textContent||"{}")||{};
	}catch(error){
		dpPanelLocalizationCache={translations:{}};
	}
	if(!dpPanelLocalizationCache.translations||typeof dpPanelLocalizationCache.translations!=="object"){
		dpPanelLocalizationCache.translations={};
	}
	return dpPanelLocalizationCache;
}
/**
 * Resolves a localized Panel string and applies token replacement.
 *
 * Tokens support both `{name}` and `:name` placeholders because server-rendered
 * strings and legacy client snippets use both forms. Missing translations fall
 * back to the supplied fallback or the key itself.
 *
 * @param {string} key Translation identifier.
 * @param {string} fallback Default text when no translation is registered.
 * @param {Object<string, *>} tokens Replacement values for placeholders.
 * @returns {string} Localized text safe for textContent assignment.
 */
function dpPanelText(key,fallback,tokens){
	var translations=dpPanelLocalization().translations||{};
	var value=Object.prototype.hasOwnProperty.call(translations,key) ? translations[key] : fallback;
	value=String(value===undefined||value===null ? key : value);
	if(tokens&&typeof tokens==="object"){
		Object.keys(tokens).forEach(function(token){
			var replacement=String(tokens[token]===undefined||tokens[token]===null ? "" : tokens[token]);
			value=value.split("{"+token+"}").join(replacement).split(":"+token).join(replacement);
		});
	}
	return value;
}
/**
 * Reads the current submitted value for a field name.
 *
 * Checkbox and radio groups are reduced to the checked value, while other
 * controls return the first matching control value. This mirrors the dependency
 * resolver used by server-side field visibility and required-state checks.
 *
 * @param {string} name Form control name to read.
 * @returns {string} Current value or an empty string when no value is selected.
 */
function dpPanelFieldValue(name){
	var inputs=document.querySelectorAll("[name=\""+name+"\"]");
	if(!inputs.length){return "";}
	var first=inputs[0];
	if(first.type==="checkbox"){
		for(var index=0;index<inputs.length;index++){
			if(inputs[index].checked){return inputs[index].value||"1";}
		}
		return "";
	}
	if(first.type==="radio"){
		for(var radio=0;radio<inputs.length;radio++){
			if(inputs[radio].checked){return inputs[radio].value||"";}
		}
		return "";
	}
	return first.value||"";
}
/**
 * Parses a dependency condition payload from a data attribute.
 *
 * Invalid JSON is ignored rather than surfaced to users because the dependency
 * payload is generated by the server and should not break unrelated controls.
 *
 * @param {string} value JSON dependency map.
 * @returns {Object<string, *>} Parsed dependency map.
 */
function dpPanelParseDependency(value){
	if(!value){return {};}
	try{return JSON.parse(value)||{};}catch(error){return {};}
}
dpPanelListen(document,"click",function(event){
	var toggle=event.target&&event.target.closest ? event.target.closest("[data-dp-panel-group-toggle]") : null;
	if(!toggle){return;}
	var target=toggle.getAttribute("data-dp-panel-group-target")||"";
	if(!target){return;}
	var expanded=toggle.getAttribute("aria-expanded")!=="false";
	var next=!expanded;
	toggle.setAttribute("aria-expanded",next?"true":"false");
	var header=toggle.closest(".dp-panel-table-group-row");
	if(header){header.classList.toggle("dp-panel-table-group-row-collapsed",!next);}
	document.querySelectorAll("[data-dp-panel-group-child=\""+target.replace(/"/g,"\\\"")+"\"]").forEach(function(row){
		row.hidden=!next;
	});
});
/**
 * Evaluates a single dependency condition against a submitted value.
 *
 * Array expectations model membership checks, boolean expectations use HTML
 * form truth semantics, and scalar expectations compare by string value to
 * align with submitted form payloads.
 *
 * @param {*} actual Current submitted value.
 * @param {*} expected Expected condition value from field metadata.
 * @returns {boolean} Whether the dependency condition matches.
 */
function dpPanelConditionMatches(actual,expected){
	if(Array.isArray(expected)){
		return expected.map(String).indexOf(String(actual))!==-1;
	}
	if(expected===true){
		return !!actual&&actual!=="0"&&actual!=="false";
	}
	if(expected===false){
		return !actual||actual==="0"||actual==="false";
	}
	return String(actual)===String(expected);
}
/**
 * Evaluates a dependency map using `when` or `unless` mode.
 *
 * @param {Object<string, *>} conditions Field-name to expected-value map.
 * @param {string} mode Dependency mode, either `when` or `unless`.
 * @returns {boolean} Whether all conditions pass for the requested mode.
 */
function dpPanelConditionsMatch(conditions,mode){
	var matched=true;
	Object.keys(conditions).forEach(function(name){
		var hit=dpPanelConditionMatches(dpPanelFieldValue(name),conditions[name]);
		if(mode==="unless"){hit=!hit;}
		if(!hit){matched=false;}
	});
	return matched;
}
/**
 * Returns the interactive controls owned by a Panel field wrapper.
 *
 * @param {Element} field Field wrapper element.
 * @returns {NodeListOf<Element>} Input, select, and textarea controls.
 */
function dpPanelFieldControls(field){
	return field.querySelectorAll("input,select,textarea");
}
/**
 * Applies native required validation only to submitted field controls.
 *
 * @param {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} input Control to update.
 * @param {boolean} required Whether the owning field is visible and required.
 * @returns {void}
 */
function dpPanelSetFieldControlRequired(input,required){
	var name=typeof input.name==="string" ? input.name.trim() : "";
	var searchableAuxiliary=!!(input.hasAttribute&&input.hasAttribute("data-dp-panel-searchable-select-input"));
	var participates=input.type!=="hidden"&&name!==""&&!searchableAuxiliary;
	input.required=participates&&required;
	input.setAttribute("aria-required",participates&&required ? "true" : "false");
}
/**
 * Recomputes client-side field visibility and required state from dependencies.
 *
 * The function mutates only DOM state: field visibility classes, disabled flags,
 * `required`, and ARIA metadata. Server validation remains authoritative, but
 * this keeps the browser experience aligned with the same dependency contract.
 *
 * @returns {void}
 */
function dpPanelRefreshDependencies(){
	document.querySelectorAll("[data-dp-panel-visible-when],[data-dp-panel-hidden-when],[data-dp-panel-required-when],[data-dp-panel-required-unless]").forEach(function(field){
		var visible=true;
		var visibleWhen=dpPanelParseDependency(field.dataset.dpPanelVisibleWhen);
		var hiddenWhen=dpPanelParseDependency(field.dataset.dpPanelHiddenWhen);
		var requiredWhen=dpPanelParseDependency(field.dataset.dpPanelRequiredWhen);
		var requiredUnless=dpPanelParseDependency(field.dataset.dpPanelRequiredUnless);
		if(Object.keys(visibleWhen).length&&!dpPanelConditionsMatch(visibleWhen,"when")){
			visible=false;
		}
		if(Object.keys(hiddenWhen).length&&dpPanelConditionsMatch(hiddenWhen,"when")){
			visible=false;
		}
		var required=Object.keys(requiredWhen).length&&dpPanelConditionsMatch(requiredWhen,"when");
		if(Object.keys(requiredUnless).length){
			required=required||dpPanelConditionsMatch(requiredUnless,"unless");
		}
		field.classList.toggle("dp-panel-field-hidden",!visible);
		field.classList.toggle("dp-panel-field-required",required);
		dpPanelFieldControls(field).forEach(function(input){
			input.disabled=!visible;
			dpPanelSetFieldControlRequired(input,visible&&required);
		});
	});
}
var dpPanelReactiveTimers={};
/**
 * Normalizes a form control name into the base Panel field name.
 *
 * @param {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} input Source control.
 * @returns {string} Field name without array suffixes or nested bracket paths.
 */
function dpPanelReactiveFieldName(input){
	var name=(input&&input.name)||"";
	if(!name){return "";}
	return name.replace(/\[\]$/,"").split("[")[0];
}
/**
 * Escapes a value for use in a CSS selector.
 *
 * The native `CSS.escape` implementation is preferred when available; the
 * fallback only covers the quote and slash characters used by generated field
 * selectors in this runtime.
 *
 * @param {string} value Raw selector value.
 * @returns {string} Escaped selector fragment.
 */
function dpPanelCssEscape(value){
	if(window.CSS&&typeof CSS.escape==="function"){return CSS.escape(value);}
	return String(value).replace(/["\\]/g,"\\$&");
}
/**
 * Checks whether a reactive field depends on a source field.
 *
 * @param {Element} field Candidate dependent field wrapper.
 * @param {string} name Source field name.
 * @returns {boolean} Whether the field should refresh after the source changes.
 */
function dpPanelReactiveDependsOn(field,name){
	if(!name){return true;}
	var depends=dpPanelParseDependency(field.dataset.dpPanelDependsOn);
	if(Array.isArray(depends)){return depends.map(String).indexOf(String(name))!==-1;}
	if(depends&&typeof depends==="object"){return Object.keys(depends).indexOf(String(name))!==-1;}
	return false;
}
/**
 * Resolves the endpoint used for reactive field requests.
 *
 * @param {HTMLFormElement} form Panel form carrying optional reactive URL metadata.
 * @returns {URL} Absolute URL for same-origin reactive POST requests.
 */
function dpPanelReactiveUrl(form){
	var raw=form.dataset.dpPanelReactiveUrl||window.location.href;
	return new URL(raw,window.location.href);
}
/**
 * Collects fields whose state may change after a source control update.
 *
 * The target set includes dynamic options, server-side state updates, explicit
 * dependencies, and optionally the source field itself for validation refreshes.
 *
 * @param {HTMLFormElement} form Panel form containing field wrappers.
 * @param {string} sourceName Normalized source field name.
 * @param {boolean} includeSource Whether to include the source field in the target set.
 * @returns {Element[]} Field wrappers eligible for reactive state refresh.
 */
function dpPanelReactiveStateTargets(form,sourceName,includeSource){
	return Array.prototype.slice.call(form.querySelectorAll("[data-dp-panel-field-name]")).filter(function(field){
		var fieldName=field.dataset.dpPanelFieldName||"";
		if(includeSource&&fieldName===sourceName){return true;}
		if(field.dataset.dpPanelDynamicOptions==="1"&&dpPanelReactiveDependsOn(field,sourceName)){return true;}
		if(field.dataset.dpPanelStateUpdates==="1"&&(fieldName===sourceName||dpPanelReactiveDependsOn(field,sourceName))){return true;}
		return (field.hasAttribute("data-dp-panel-visible-when")||field.hasAttribute("data-dp-panel-hidden-when")||field.hasAttribute("data-dp-panel-required-when")||field.hasAttribute("data-dp-panel-required-unless"))&&dpPanelReactiveDependsOn(field,sourceName);
	});
}
/**
 * Applies validation messages to a field wrapper.
 *
 * Existing generated errors are removed before new errors are appended, and ARIA
 * invalid state is synchronized across every control in the field.
 *
 * @param {Element} field Field wrapper.
 * @param {string[]} errors Validation messages returned by the server.
 * @returns {void}
 */
function dpPanelApplyFieldErrors(field,errors){
	field.querySelectorAll(":scope > .dp-panel-error").forEach(function(error){error.remove();});
	field.classList.toggle("dp-panel-field-invalid",Array.isArray(errors)&&errors.length>0);
	dpPanelFieldControls(field).forEach(function(input){
		input.setAttribute("aria-invalid",Array.isArray(errors)&&errors.length>0 ? "true" : "false");
	});
	if(!Array.isArray(errors)||!errors.length){return;}
	errors.forEach(function(message){
		var item=document.createElement("small");
		item.className="dp-panel-error";
		item.textContent=String(message||"");
		field.appendChild(item);
	});
}
/**
 * Applies server-provided help text to a field wrapper.
 *
 * Dynamic help reuses an existing static help element when available so layout
 * position stays stable across refreshes.
 *
 * @param {Element} field Field wrapper.
 * @param {Object<string, *>} state Reactive field state payload.
 * @returns {void}
 */
function dpPanelApplyFieldHelp(field,state){
	if(!("help" in state)){return;}
	var help=field.querySelector(":scope > .dp-panel-help[data-dp-panel-dynamic-help]");
	var staticHelp=field.querySelector(":scope > .dp-panel-help:not([data-dp-panel-dynamic-help])");
	if(!help&&staticHelp){help=staticHelp;help.dataset.dpPanelDynamicHelp="1";}
	var text=state.help===null||state.help===undefined ? "" : String(state.help);
	if(!text){
		if(help){help.remove();}
		return;
	}
	if(!help){
		help=document.createElement("small");
		help.className="dp-panel-help";
		help.dataset.dpPanelDynamicHelp="1";
		var firstError=field.querySelector(":scope > .dp-panel-error");
		field.insertBefore(help,firstError||null);
	}
	help.textContent=text;
}
/**
 * Applies a server-provided placeholder to text-like controls in a field.
 *
 * @param {Element} field Field wrapper.
 * @param {Object<string, *>} state Reactive field state payload.
 * @returns {void}
 */
function dpPanelApplyFieldPlaceholder(field,state){
	if(!("placeholder" in state)){return;}
	var value=state.placeholder===null||state.placeholder===undefined ? "" : String(state.placeholder);
	dpPanelFieldControls(field).forEach(function(input){
		if(input.type==="hidden"||input.type==="checkbox"||input.type==="radio"||input.tagName==="SELECT"){return;}
		if(value===""){input.removeAttribute("placeholder");}
		else{input.setAttribute("placeholder",value);}
	});
}
/**
 * Applies a server-authoritative value to field controls when allowed.
 *
 * Focused editable controls are not overwritten unless `force_value` is true,
 * protecting in-progress typing while still allowing state callbacks to update
 * hidden, checkbox, radio, select, and unfocused controls.
 *
 * @param {Element} field Field wrapper.
 * @param {Object<string, *>} state Reactive field state payload.
 * @returns {void}
 */
function dpPanelApplyFieldValue(field,state){
	if(state.value_from_server!==true||!("value" in state)){return;}
	var controls=dpPanelFieldControls(field);
	if(!controls.length){return;}
	var active=document.activeElement;
	if(state.force_value!==true&&active&&field.contains(active)&&!active.readOnly&&active.type!=="hidden"){
		return;
	}
	var value=String(state.value===null||state.value===undefined ? "" : state.value);
	var changed=false;
	controls.forEach(function(input){
		if(input.type==="hidden"){return;}
		if(input.type==="checkbox"){
			var checked=value==="1"||value==="true"||value===input.value;
			if(input.checked!==checked){input.checked=checked;changed=true;}
			return;
		}
		if(input.type==="radio"){
			var next=input.value===value;
			if(input.checked!==next){input.checked=next;changed=true;}
			return;
		}
		if(input.tagName==="SELECT"){
			var hasOption=Array.prototype.some.call(input.options,function(option){return option.value===value;});
			if(hasOption&&input.value!==value){input.value=value;changed=true;}
			return;
		}
		if(input.value!==value){input.value=value;changed=true;}
	});
	if(changed&&state.propagate===true){
		controls.forEach(function(input){input.dispatchEvent(new Event("change",{bubbles:true}));});
	}
}
/**
 * Applies a complete server reactive-state payload to one field.
 *
 * The mutation covers visibility, required and readonly flags, dynamic options,
 * server-provided values, help, placeholders, validation errors, and freshness
 * metadata. The payload is trusted only for this rendered form instance.
 *
 * @param {HTMLFormElement} form Panel form that owns the field.
 * @param {Element} field Field wrapper to mutate.
 * @param {Object<string, *>} state Server reactive-state payload for the field.
 * @param {boolean} applyErrors Whether validation errors should be rendered.
 * @returns {void}
 */
function dpPanelApplyFieldState(form,field,state,applyErrors){
	if(!field||!state){return;}
	var visible=state.visible!==false;
	var required=state.required===true;
	var readonly=state.readonly===true;
	field.classList.toggle("dp-panel-field-hidden",!visible);
	field.classList.toggle("dp-panel-field-required",visible&&required);
	dpPanelFieldControls(field).forEach(function(input){
		input.disabled=!visible;
		dpPanelSetFieldControlRequired(input,visible&&required);
		if(input.tagName!=="SELECT"&&input.type!=="checkbox"&&input.type!=="radio"&&input.type!=="file"){input.readOnly=readonly;}
		input.setAttribute("aria-readonly",readonly ? "true" : "false");
	});
	if(state.dynamic_options===true&&typeof state.options_html==="string"){
		var fieldName=field.dataset.dpPanelFieldName||state.name||"";
		var select=fieldName!=="" ? field.querySelector("select[name='"+dpPanelCssEscape(fieldName)+"']") : field.querySelector("select");
		if(select){
			var previous=select.value;
			select.innerHTML=state.options_html;
			if(Array.prototype.some.call(select.options,function(option){return option.value===previous;})){
				select.value=previous;
			}
			else if(state.value!==undefined&&Array.prototype.some.call(select.options,function(option){return option.value===String(state.value);})){
				select.value=String(state.value);
			}
		}
	}
	dpPanelApplyFieldValue(field,state);
	dpPanelApplyFieldHelp(field,state);
	dpPanelApplyFieldPlaceholder(field,state);
	if(applyErrors===true&&state.validated===true){
		dpPanelApplyFieldErrors(field,state.errors||[]);
	}
	field.dataset.dpPanelReactiveState="fresh";
}
/**
 * Requests server-side reactive state for fields affected by an input change.
 *
 * The request posts the full current form state, optionally asks the server to
 * validate the source field, and applies only payload entries returned for the
 * current form. Failures mark targets as errored without interrupting typing.
 *
 * @param {Element} input Source control that changed.
 * @param {boolean} validate Whether the refresh should include field validation.
 * @returns {void}
 */
function dpPanelRefreshReactiveState(input,validate){
	if(!window.fetch||!window.FormData){return;}
	var form=input.closest("form.dp-panel-form");
	if(!form){return;}
	var sourceName=dpPanelReactiveFieldName(input);
	var targets=dpPanelReactiveStateTargets(form,sourceName,validate===true);
	if(!targets.length){return;}
	var key="state_"+(sourceName||"_all");
	var sourceField=input.closest("[data-dp-panel-field-name]");
	var delay=validate===true ? 0 : parseInt((sourceField&&sourceField.dataset.dpPanelDebounceMs)||"120",10)||0;
	clearTimeout(dpPanelReactiveTimers[key]);
	dpPanelReactiveTimers[key]=setTimeout(function(){
		var body=new FormData(form);
		body.append("__panel_partial","field_state");
		if(validate===true){
			body.append("__panel_validate","field");
			body.append("__panel_validate_field",sourceName);
		}
		targets.forEach(function(field){field.classList.add("dp-panel-field-reactive-loading");});
		fetch(dpPanelReactiveUrl(form),{
			method:"POST",
			body:body,
			credentials:"same-origin",
			headers:{"Accept":"application/json","X-Requested-With":"DataphyrePanelFieldState"}
		}).then(function(response){
			if(!response.ok){throw new Error("field_state_failed");}
			return response.json();
		}).then(function(payload){
			var states=payload&&payload.fields ? payload.fields : {};
			var applyErrors=payload&&payload.validated===true;
			var applied={};
			targets.forEach(function(field){
				var fieldName=field.dataset.dpPanelFieldName||"";
				if(states[fieldName]){
					dpPanelApplyFieldState(form,field,states[fieldName],applyErrors);
					applied[fieldName]=true;
				}
			});
			Object.keys(states).forEach(function(fieldName){
				if(applied[fieldName]){return;}
				var state=states[fieldName]||{};
				if(state.value_from_server!==true&&state.state_updates!==true&&state.dynamic_options!==true){return;}
				var field=form.querySelector("[data-dp-panel-field-name='"+dpPanelCssEscape(fieldName)+"']");
				if(field){dpPanelApplyFieldState(form,field,state,applyErrors);}
			});
			if(typeof dpPanelRefreshPanelUi==="function"){dpPanelRefreshPanelUi();}
		}).catch(function(){
			targets.forEach(function(field){field.dataset.dpPanelReactiveState="error";});
		}).finally(function(){
			targets.forEach(function(field){field.classList.remove("dp-panel-field-reactive-loading");});
		});
	},delay);
}
dpPanelListen(document,"input",function(event){
	var control=event.target.closest("input,select,textarea");
	if(!control||!control.closest("form.dp-panel-form")){return;}
	dpPanelRefreshDependencies();
	dpPanelRefreshReactiveState(control,false);
});
dpPanelListen(document,"change",function(event){
	var control=event.target.closest("input,select,textarea");
	if(!control||!control.closest("form.dp-panel-form")){return;}
	dpPanelRefreshDependencies();
	dpPanelRefreshReactiveState(control,false);
});
dpPanelListen(document,"focusout",function(event){
	var control=event.target.closest("input,select,textarea");
	if(!control||!control.closest("form.dp-panel-form")||!control.closest("[data-dp-panel-live='1']")){return;}
	dpPanelRefreshReactiveState(control,true);
});
dpPanelListen(document,"click",function(event){
	var button=event.target.closest("[data-confirm]");
	if(button&&button.dataset.confirm&&!button.dataset.dpPanelActionModal){
		if(button.dataset.dpPanelConfirmed==="1"){
			delete button.dataset.dpPanelConfirmed;
		}
		else {
			event.preventDefault();
			if(typeof dpPanelConfirmAction==="function"&&button.closest(".dp-panel")){
				dpPanelConfirmAction(button);
				return false;
			}
			if(!confirm(button.dataset.confirm)){
				return false;
			}
		}
	}
	var toggle=event.target.closest("[data-dp-panel-select-all]");
	if(toggle){
		var table=toggle.closest("table");
		(table?table:document).querySelectorAll("input[name='selected[]']").forEach(function(input){
			input.checked=toggle.checked;
		});
		dpPanelUpdateBulkSelection();
	}
	var clearSelection=event.target.closest("[data-dp-panel-clear-selection]");
	if(clearSelection){
		event.preventDefault();
		dpPanelSelectionInputs(dpPanelSelectionScopeForBar(clearSelection.closest(".dp-panel-bulk-bar"))).forEach(function(input){
			input.checked=false;
		});
		dpPanelLastSelectionInput=null;
		dpPanelUpdateBulkSelection();
	}
	var saveView=event.target.closest("[data-dp-panel-save-view]");
	if(saveView){
		event.preventDefault();
		dpPanelSaveCurrentView();
	}
	var removeSavedView=event.target.closest("[data-dp-panel-remove-saved-view]");
	if(removeSavedView){
		event.preventDefault();
		dpPanelForgetCurrentSavedView();
	}
	var exportSavedViews=event.target.closest("[data-dp-panel-export-saved-views]");
	if(exportSavedViews){
		event.preventDefault();
		dpPanelExportSavedViews();
	}
	var importSavedViews=event.target.closest("[data-dp-panel-import-saved-views]");
	if(importSavedViews){
		event.preventDefault();
		dpPanelImportSavedViews();
	}
	var exportWorkspace=event.target.closest("[data-dp-panel-export-workspace]");
	if(exportWorkspace){
		event.preventDefault();
		dpPanelExportWorkspaceSnapshot();
	}
	var importWorkspace=event.target.closest("[data-dp-panel-import-workspace]");
	if(importWorkspace){
		event.preventDefault();
		dpPanelImportWorkspaceSnapshot();
	}
});
var dpPanelLastSelectionInput=null;
dpPanelListen(document,"click",function(event){
	var input=event.target.closest("input[name='selected[]']");
	if(!input){return;}
	var table=input.closest("table");
	if(event.shiftKey&&dpPanelLastSelectionInput&&table&&dpPanelLastSelectionInput.closest("table")===table){
		var inputs=dpPanelSelectionInputs(table);
		var from=inputs.indexOf(dpPanelLastSelectionInput);
		var to=inputs.indexOf(input);
		if(from!==-1&&to!==-1){
			var start=Math.min(from,to);
			var end=Math.max(from,to);
			for(var index=start;index<=end;index++){
				inputs[index].checked=input.checked;
			}
		}
	}
	dpPanelLastSelectionInput=input;
	dpPanelUpdateBulkSelection();
});
dpPanelListen(document,"toggle",function(event){
	var details=event.target;
	if(details&&details.matches&&details.matches(".dp-panel-row-more")){
		dpPanelPrepareRowActionMenu(details);
	}
	if(details&&details.matches&&details.matches(".dp-panel-action-group")){
		dpPanelPrepareActionGroupMenu(details);
		requestAnimationFrame(function(){
			if(details.open){dpPanelPlaceActionGroupMenu(details);}
			var row=details.closest(".dp-panel-row-more");
			if(row&&row.open){dpPanelPlaceRowActionMenu(row);}
		});
	}
	if(details&&details.matches&&details.matches(".dp-panel-horizontal-group")){
		dpPanelPrepareHorizontalMenu(details);
		dpPanelSyncHorizontalMenuChrome(details);
		if(details.open){requestAnimationFrame(function(){dpPanelPlaceHorizontalMenu(details);});}
	}
	if(!details||!details.matches||!details.matches(".dp-panel-horizontal-group[open],.dp-panel-row-more[open],.dp-panel-column-picker[open],.dp-panel-action-group[open],.dp-panel-saved-view-menu[open]")){return;}
	document.querySelectorAll(".dp-panel-horizontal-group[open],.dp-panel-row-more[open],.dp-panel-column-picker[open],.dp-panel-action-group[open],.dp-panel-saved-view-menu[open]").forEach(function(other){
		if(other!==details&&!other.contains(details)&&!details.contains(other)){
			other.removeAttribute("open");
			if(other.matches(".dp-panel-horizontal-group")){dpPanelSyncHorizontalMenuChrome(other);}
		}
	});
	if(details.matches(".dp-panel-row-more[open]")){
		requestAnimationFrame(function(){dpPanelPlaceRowActionMenu(details);});
	}
	if(details.matches(".dp-panel-horizontal-group[open]")){
		requestAnimationFrame(function(){dpPanelPlaceHorizontalMenu(details);});
	}
},true);
/**
 * Closes floating Panel disclosure surfaces except an optional active surface.
 *
 * The helper keeps unrelated horizontal menus, row action menus, column
 * pickers, action groups, and saved-view menus mutually exclusive while
 * preserving the active disclosure's open ancestor chain.
 *
 * @param {HTMLDetailsElement|null} except Disclosure element that should stay open.
 * @returns {void}
 */
function dpPanelCloseTransientPanels(except){
	document.querySelectorAll(".dp-panel-horizontal-group[open],.dp-panel-row-more[open],.dp-panel-column-picker[open],.dp-panel-action-group[open],.dp-panel-saved-view-menu[open]").forEach(function(details){
		if(except&&(details===except||details.contains(except)||except.contains(details))){return;}
		details.removeAttribute("open");
		if(details.matches(".dp-panel-row-more")){dpPanelPrepareRowActionMenu(details);}
		if(details.matches(".dp-panel-action-group")){dpPanelPrepareActionGroupMenu(details);}
		if(details.matches(".dp-panel-horizontal-group")){dpPanelPrepareHorizontalMenu(details);dpPanelSyncHorizontalMenuChrome(details);}
	});
}
/**
 * Applies ARIA menu wiring to a horizontal navigation disclosure.
 *
 * @param {HTMLDetailsElement} details Horizontal navigation details element.
 * @returns {void}
 */
function dpPanelPrepareHorizontalMenu(details){
	if(!details){return;}
	var summary=details.querySelector(":scope>summary");
	var menu=details.querySelector(":scope>div");
	if(!summary||!menu){return;}
	if(!menu.id){menu.id="dp-panel-horizontal-menu-"+Math.random().toString(36).slice(2,10);}
	summary.setAttribute("aria-haspopup","menu");
	summary.setAttribute("aria-controls",menu.id);
	summary.setAttribute("aria-expanded",details.open?"true":"false");
	menu.setAttribute("role","menu");
}
/**
 * Synchronizes horizontal navigation chrome with its open-menu state.
 *
 * @param {HTMLDetailsElement|null} details Horizontal menu or descendant context.
 * @returns {void}
 */
function dpPanelSyncHorizontalMenuChrome(details){
	var nav=details&&details.closest ? details.closest(".dp-panel-horizontal-nav") : null;
	if(!nav){return;}
	var open=!!nav.querySelector(".dp-panel-horizontal-group[open]");
	nav.classList.toggle("dp-panel-horizontal-nav-menu-open",open);
	var track=nav.querySelector(".dp-panel-horizontal-track");
	if(track){track.classList.toggle("dp-panel-horizontal-track-menu-open",open);}
}
/**
 * Places an open horizontal navigation menu within the viewport.
 *
 * Menu coordinates are stored as CSS custom properties because the stylesheet
 * owns the final fixed-position layout. Width and height are clamped to avoid
 * clipping on small screens.
 *
 * @param {HTMLDetailsElement} details Open horizontal menu details element.
 * @returns {void}
 */
function dpPanelPlaceHorizontalMenu(details){
	if(!details||!details.open){return;}
	var summary=details.querySelector(":scope>summary");
	var menu=details.querySelector(":scope>div");
	if(!summary||!menu){return;}
	var rect=summary.getBoundingClientRect();
	var anchor=details.closest(".dp-panel-horizontal-nav");
	var anchorRect=anchor ? anchor.getBoundingClientRect() : {left:0, top:0};
	var viewportWidth=window.innerWidth||document.documentElement.clientWidth||0;
	var viewportHeight=window.innerHeight||document.documentElement.clientHeight||0;
	var preferredWidth=Math.min(360,Math.max(280,viewportWidth-20));
	var measured=Math.max(preferredWidth,Math.min(420,menu.scrollWidth||preferredWidth));
	var width=Math.min(measured,viewportWidth-20);
	var viewportLeft=Math.min(Math.max(10,rect.left),Math.max(10,viewportWidth-width-10));
	var viewportTop=Math.min((anchorRect.bottom||rect.bottom),Math.max(10,viewportHeight-120));
	var maxHeight=Math.max(180,viewportHeight-viewportTop-12);
	var left=viewportLeft;
	var top=viewportTop;
	details.style.setProperty("--dp-horizontal-menu-left",left+"px");
	details.style.setProperty("--dp-horizontal-menu-top",top+"px");
	details.style.setProperty("--dp-horizontal-menu-width",width+"px");
	details.style.setProperty("--dp-horizontal-menu-max-height",maxHeight+"px");
}
/**
 * Repositions every currently open horizontal navigation menu.
 *
 * @returns {void}
 */
function dpPanelPlaceOpenHorizontalMenus(){
	document.querySelectorAll(".dp-panel-horizontal-group[open]").forEach(dpPanelPlaceHorizontalMenu);
}
/**
 * Centers the active horizontal navigation item on narrow screens.
 *
 * @returns {void}
 */
function dpPanelScrollActiveHorizontalNavigationIntoView(){
	if(!window.matchMedia||!window.matchMedia("(max-width: 720px)").matches){return;}
	document.querySelectorAll(".dp-panel-horizontal-track").forEach(function(track){
		var active=track.querySelector(".dp-panel-horizontal-link.active,.dp-panel-horizontal-group.active>summary");
		if(!active){return;}
		setTimeout(function(){
			try{
				var trackRect=track.getBoundingClientRect();
				var activeRect=active.getBoundingClientRect();
				var next=track.scrollLeft+(activeRect.left-trackRect.left)-(trackRect.width-activeRect.width)/2;
				track.scrollTo({left:Math.max(0,next),behavior:"smooth"});
			}
			catch(error){
				try{active.scrollIntoView({block:"nearest",inline:"center",behavior:"smooth"});}
				catch(innerError){active.scrollIntoView(false);}
			}
		},80);
	});
}
/**
 * Returns focusable row action controls, excluding structural menu chrome.
 *
 * @param {Element|null} menu Row action menu element.
 * @returns {Element[]} Focusable action controls.
 */
function dpPanelRowActionMenuItems(menu){
	if(!menu){return [];}
	return dpPanelFocusable(menu).filter(function(item){
		return !item.closest(".dp-panel-row-more-menu header,.dp-panel-action-menu");
	});
}
/**
 * Applies ARIA menu wiring to a row action disclosure.
 *
 * @param {HTMLDetailsElement} details Row action details element.
 * @returns {void}
 */
function dpPanelPrepareRowActionMenu(details){
	if(!details){return;}
	var summary=details.querySelector(":scope>summary");
	var menu=details.querySelector(".dp-panel-row-more-menu");
	if(!summary||!menu){return;}
	if(!menu.id){
		menu.id="dp-panel-row-menu-"+Math.random().toString(36).slice(2,10);
	}
	if(!details.open){menu.querySelectorAll(".dp-panel-action-group[open]").forEach(function(group){group.open=false;dpPanelPrepareActionGroupMenu(group);});}
	summary.setAttribute("aria-haspopup","menu");
	summary.setAttribute("aria-controls",menu.id);
	summary.setAttribute("aria-expanded",details.open?"true":"false");
	menu.setAttribute("role","menu");
	dpPanelRowActionMenuItems(menu).forEach(function(item){
		item.setAttribute("role","menuitem");
		if(!item.hasAttribute("tabindex")){item.setAttribute("tabindex","-1");}
	});
}
/**
 * Prepares all row action menus currently rendered in the Panel.
 *
 * @returns {void}
 */
function dpPanelPrepareRowActionMenus(){
	document.querySelectorAll(".dp-panel-row-more").forEach(dpPanelPrepareRowActionMenu);
}
/**
 * Focuses a row action item by wrapped index.
 *
 * @param {HTMLDetailsElement} details Row action details element.
 * @param {number} index Desired item index, wrapped within the menu item count.
 * @returns {boolean} Whether focus moved to an item.
 */
function dpPanelFocusRowActionMenuItem(details,index){
	var items=dpPanelRowActionMenuItems(details?details.querySelector(".dp-panel-row-more-menu"):null);
	if(!items.length){return false;}
	var next=((index%items.length)+items.length)%items.length;
	items[next].focus({preventScroll:true});
	return true;
}
/**
 * Moves focus within the current row action menu.
 *
 * @param {Element} current Currently focused menu item.
 * @param {number} delta Relative movement direction.
 * @returns {boolean} Whether focus moved to another item.
 */
function dpPanelMoveRowActionMenuFocus(current,delta){
	var details=current.closest(".dp-panel-row-more");
	var items=dpPanelRowActionMenuItems(details?details.querySelector(".dp-panel-row-more-menu"):null);
	var index=items.indexOf(current);
	if(index===-1){index=0;}
	return dpPanelFocusRowActionMenuItem(details,index+delta);
}
/**
 * Positions an open row action menu as a viewport-aware floating surface.
 *
 * Placement is corrected after measurement to account for transformed ancestors
 * or stylesheet constraints, then exposed through CSS custom properties.
 *
 * @param {HTMLDetailsElement} details Open row action details element.
 * @returns {void}
 */
function dpPanelPlaceRowActionMenu(details){
	if(!details||!details.open){return;}
	var summary=details.querySelector("summary");
	var menu=details.querySelector(".dp-panel-row-more-menu");
	if(!summary||!menu){return;}
	details.classList.add("dp-panel-row-more-floating");
	var rect=summary.getBoundingClientRect();
	var width=Math.min(innerWidth-24,menu.lastElementChild.childElementCount>4?340:230);
	menu.style.setProperty("--dp-row-menu-width",width+"px");
	var height=Math.min(menu.scrollHeight||menu.offsetHeight||260,innerHeight-24);
	var left=Math.min(innerWidth-width-12,Math.max(12,rect.right-width));
	var top=rect.bottom+8;
	if(top+height>innerHeight-12){
		top=Math.max(12,rect.top-height-8);
		details.classList.add("dp-panel-row-more-above");
	}
	else {
		details.classList.remove("dp-panel-row-more-above");
	}
	menu.style.setProperty("--dp-row-menu-left",left+"px");
	menu.style.setProperty("--dp-row-menu-top",top+"px");
	menu.style.setProperty("--dp-row-menu-max-height",Math.max(180,innerHeight-top-12)+"px");
	var actual=menu.getBoundingClientRect();
	var offsetLeft=actual.left-left;
	var offsetTop=actual.top-top;
	if(Math.abs(offsetLeft)>1||Math.abs(offsetTop)>1){
		left-=offsetLeft;
		top-=offsetTop;
		menu.style.setProperty("--dp-row-menu-left",left+"px");
		menu.style.setProperty("--dp-row-menu-top",top+"px");
		menu.style.setProperty("--dp-row-menu-max-height",Math.max(180,innerHeight-top-12)+"px");
	}
}
/**
 * Repositions every open row action menu after scrolling or resizing.
 *
 * @returns {void}
 */
function dpPanelRefreshOpenRowActionMenus(){
	document.querySelectorAll(".dp-panel-row-more[open]").forEach(dpPanelPlaceRowActionMenu);
}
/**
 * Returns focusable action-group controls, excluding section labels.
 *
 * @param {Element|null} menu Action group menu element.
 * @returns {Element[]} Focusable menu controls.
 */
function dpPanelActionGroupMenuItems(menu){
	if(!menu){return [];}
	return dpPanelFocusable(menu).filter(function(item){
		return !item.closest(".dp-panel-action-menu-section");
	});
}
/**
 * Applies ARIA menu wiring to an action group disclosure.
 *
 * @param {HTMLDetailsElement} details Action group details element.
 * @returns {void}
 */
function dpPanelPrepareActionGroupMenu(details){
	if(!details){return;}
	var summary=details.querySelector(":scope>summary");
	var menu=details.querySelector(":scope>.dp-panel-action-menu");
	if(!summary||!menu){return;}
	if(!menu.id){
		menu.id="dp-panel-action-menu-"+Math.random().toString(36).slice(2,10);
	}
	summary.setAttribute("aria-haspopup","menu");
	summary.setAttribute("aria-controls",menu.id);
	summary.setAttribute("aria-expanded",details.open?"true":"false");
	menu.setAttribute("role","menu");
	dpPanelActionGroupMenuItems(menu).forEach(function(item){
		item.setAttribute("role","menuitem");
		if(!item.hasAttribute("tabindex")){item.setAttribute("tabindex","-1");}
	});
}
/**
 * Reads the requested menu alignment for an action group.
 *
 * @param {HTMLDetailsElement} details Action group details element.
 * @returns {string} `start`, `center`, or `end`.
 */
function dpPanelActionGroupAlignment(details){
	if(details.classList.contains("dp-panel-action-group-align-start")){return "start";}
	if(details.classList.contains("dp-panel-action-group-align-center")){return "center";}
	return "end";
}
/**
 * Positions an open action-group menu unless it is nested inside another surface.
 *
 * Nested menus keep stylesheet-local positioning so row menus and modal surfaces
 * can own their stacking context. Top-level menus use viewport coordinates via
 * CSS custom properties.
 *
 * @param {HTMLDetailsElement} details Open action group details element.
 * @returns {void}
 */
function dpPanelPlaceActionGroupMenu(details){
	if(!details||!details.open){return;}
	var summary=details.querySelector(":scope>summary");
	var menu=details.querySelector(":scope>.dp-panel-action-menu");
	if(!summary||!menu){return;}
	var viewportWidth=window.innerWidth||document.documentElement.clientWidth||0;
	var viewportHeight=window.innerHeight||document.documentElement.clientHeight||0;
	var fitStaticMenu=function(){
		if(window.getComputedStyle(menu).position!=="static"){return false;}
		menu.style.removeProperty("--dp-action-menu-left");
		menu.style.removeProperty("--dp-action-menu-top");
		menu.style.removeProperty("--dp-action-menu-width");
		menu.style.removeProperty("--dp-action-menu-max-height");
		var staticRect=menu.getBoundingClientRect();
		menu.style.maxHeight=Math.max(120,viewportHeight-staticRect.top-12)+"px";
		menu.style.overflowY="auto";
		return true;
	};
	if(details.closest(".dp-panel-row-more-menu,.dp-panel-modal-surface,.dp-panel-modal-body")){
		details.classList.remove("dp-panel-action-group-floating","dp-panel-action-group-above");
		menu.style.removeProperty("--dp-action-menu-left");
		menu.style.removeProperty("--dp-action-menu-top");
		menu.style.removeProperty("--dp-action-menu-width");
		menu.style.removeProperty("--dp-action-menu-max-height");
		fitStaticMenu();
		return;
	}
	details.classList.add("dp-panel-action-group-floating");
	if(fitStaticMenu()){return;}
	menu.style.removeProperty("max-height");
	menu.style.removeProperty("overflow-y");
	var rect=summary.getBoundingClientRect();
	var width=Math.max(220,Math.min(menu.scrollWidth||menu.offsetWidth||260,viewportWidth-24));
	var align=dpPanelActionGroupAlignment(details);
	var left=align==="start" ? rect.left : (align==="center" ? rect.left+(rect.width/2)-(width/2) : rect.right-width);
	left=Math.min(viewportWidth-width-12,Math.max(12,left));
	var measuredHeight=Math.min(menu.scrollHeight||menu.offsetHeight||280,viewportHeight-24);
	var top=rect.bottom+8;
	if(top+measuredHeight>viewportHeight-12&&rect.top>measuredHeight+20){
		top=Math.max(12,rect.top-measuredHeight-8);
		details.classList.add("dp-panel-action-group-above");
	}
	else {
		details.classList.remove("dp-panel-action-group-above");
		top=Math.min(top,Math.max(12,viewportHeight-120));
	}
	menu.style.setProperty("--dp-action-menu-left",left+"px");
	menu.style.setProperty("--dp-action-menu-top",top+"px");
	menu.style.setProperty("--dp-action-menu-width",width+"px");
	menu.style.setProperty("--dp-action-menu-max-height",Math.max(180,viewportHeight-top-12)+"px");
	var actual=menu.getBoundingClientRect();
	var offsetLeft=actual.left-left;
	var offsetTop=actual.top-top;
	if(Math.abs(offsetLeft)>1||Math.abs(offsetTop)>1){
		left-=offsetLeft;
		top-=offsetTop;
		menu.style.setProperty("--dp-action-menu-left",left+"px");
		menu.style.setProperty("--dp-action-menu-top",top+"px");
		menu.style.setProperty("--dp-action-menu-max-height",Math.max(180,viewportHeight-top-12)+"px");
	}
}
/**
 * Repositions every open action-group menu after scrolling or resizing.
 *
 * @returns {void}
 */
function dpPanelRefreshOpenActionGroupMenus(){
	document.querySelectorAll(".dp-panel-action-group[open]").forEach(dpPanelPlaceActionGroupMenu);
}
/**
 * Focuses an action-group menu item by wrapped index.
 *
 * @param {HTMLDetailsElement} details Action group details element.
 * @param {number} index Desired item index, wrapped within the menu item count.
 * @returns {boolean} Whether focus moved to an item.
 */
function dpPanelFocusActionGroupMenuItem(details,index){
	var items=dpPanelActionGroupMenuItems(details?details.querySelector(":scope>.dp-panel-action-menu"):null);
	if(!items.length){return false;}
	var next=((index%items.length)+items.length)%items.length;
	items[next].focus({preventScroll:true});
	return true;
}
/**
 * Moves focus within the current action-group menu.
 *
 * @param {Element} current Currently focused menu item.
 * @param {number} delta Relative movement direction.
 * @returns {boolean} Whether focus moved to another item.
 */
function dpPanelMoveActionGroupMenuFocus(current,delta){
	var details=current.closest(".dp-panel-action-group");
	var items=dpPanelActionGroupMenuItems(details?details.querySelector(":scope>.dp-panel-action-menu"):null);
	var index=items.indexOf(current);
	if(index===-1){index=0;}
	return dpPanelFocusActionGroupMenuItem(details,index+delta);
}
/**
 * Opens an action group from keyboard interaction and focuses an initial item.
 *
 * @param {HTMLDetailsElement} details Action group details element.
 * @param {number} index Initial item index.
 * @returns {void}
 */
function dpPanelOpenActionGroupFromKeyboard(details,index){
	if(!details){return;}
	details.open=true;
	dpPanelPrepareActionGroupMenu(details);
	dpPanelCloseTransientPanels(details);
	requestAnimationFrame(function(){
		dpPanelPlaceActionGroupMenu(details);
		dpPanelFocusActionGroupMenuItem(details,index);
	});
}
dpPanelListen(document,"keydown",function(event){
	var summary=event.target&&event.target.closest ? event.target.closest(".dp-panel-row-more>summary") : null;
	if(summary){
		var details=summary.closest(".dp-panel-row-more");
		if(event.key==="ArrowDown"){
			event.preventDefault();
			details.open=true;
			dpPanelPrepareRowActionMenu(details);
			dpPanelCloseTransientPanels(details);
			requestAnimationFrame(function(){
				dpPanelPlaceRowActionMenu(details);
				dpPanelFocusRowActionMenuItem(details,0);
			});
			return;
		}
		if(event.key==="ArrowUp"){
			event.preventDefault();
			details.open=true;
			dpPanelPrepareRowActionMenu(details);
			dpPanelCloseTransientPanels(details);
			requestAnimationFrame(function(){
				dpPanelPlaceRowActionMenu(details);
				dpPanelFocusRowActionMenuItem(details,-1);
			});
			return;
		}
	}
	var actionSummary=event.target&&event.target.closest ? event.target.closest(".dp-panel-action-group>summary") : null;
	if(actionSummary){
		var actionDetails=actionSummary.closest(".dp-panel-action-group");
		if(event.key==="ArrowDown"){
			event.preventDefault();
			dpPanelOpenActionGroupFromKeyboard(actionDetails,0);
			return;
		}
		if(event.key==="ArrowUp"){
			event.preventDefault();
			dpPanelOpenActionGroupFromKeyboard(actionDetails,-1);
			return;
		}
	}
	var actionMenu=event.target&&event.target.closest ? event.target.closest(".dp-panel-action-menu") : null;
	if(actionMenu){
		var actionActive=event.target;
		var actionMenuDetails=actionMenu.closest(".dp-panel-action-group");
		if(event.key==="Escape"){
			event.preventDefault();
			if(actionMenuDetails){
				actionMenuDetails.removeAttribute("open");
				dpPanelPrepareActionGroupMenu(actionMenuDetails);
				var actionTrigger=actionMenuDetails.querySelector(":scope>summary");
				if(actionTrigger){actionTrigger.focus({preventScroll:true});}
			}
			return;
		}
		if(event.key==="ArrowDown"){
			event.preventDefault();
			dpPanelMoveActionGroupMenuFocus(actionActive,1);
			return;
		}
		if(event.key==="ArrowUp"){
			event.preventDefault();
			dpPanelMoveActionGroupMenuFocus(actionActive,-1);
			return;
		}
		if(event.key==="Home"){
			event.preventDefault();
			dpPanelFocusActionGroupMenuItem(actionMenuDetails,0);
			return;
		}
		if(event.key==="End"){
			event.preventDefault();
			dpPanelFocusActionGroupMenuItem(actionMenuDetails,-1);
			return;
		}
		if(event.key==="Tab"&&actionMenuDetails){
			setTimeout(function(){actionMenuDetails.removeAttribute("open");dpPanelPrepareActionGroupMenu(actionMenuDetails);},0);
		}
		return;
	}
	var menu=event.target&&event.target.closest ? event.target.closest(".dp-panel-row-more-menu") : null;
	if(!menu){return;}
	var active=event.target;
	var details=menu.closest(".dp-panel-row-more");
	if(event.key==="Escape"){
		event.preventDefault();
		if(details){
			details.removeAttribute("open");
			dpPanelPrepareRowActionMenu(details);
			var trigger=details.querySelector(":scope>summary");
			if(trigger){trigger.focus({preventScroll:true});}
		}
		return;
	}
	if(event.key==="ArrowDown"){
		event.preventDefault();
		dpPanelMoveRowActionMenuFocus(active,1);
		return;
	}
	if(event.key==="ArrowUp"){
		event.preventDefault();
		dpPanelMoveRowActionMenuFocus(active,-1);
		return;
	}
	if(event.key==="Home"){
		event.preventDefault();
		dpPanelFocusRowActionMenuItem(details,0);
		return;
	}
	if(event.key==="End"){
		event.preventDefault();
		dpPanelFocusRowActionMenuItem(details,-1);
		return;
	}
	if(event.key==="Tab"&&details){
		setTimeout(function(){details.removeAttribute("open");dpPanelPrepareRowActionMenu(details);},0);
	}
});
dpPanelListen(document,"click",function(event){
	var rowMoreSummary=event.target&&event.target.closest ? event.target.closest(".dp-panel-row-more>summary") : null;
	if(rowMoreSummary&&rowMoreSummary.closest(".dp-panel")){
		event.preventDefault();
		event.stopImmediatePropagation();
		var rowMore=rowMoreSummary.closest(".dp-panel-row-more");
		var openRowMore=rowMore&&!rowMore.open;
		if(!rowMore){return;}
		if(openRowMore){
			rowMore.open=true;
			dpPanelPrepareRowActionMenu(rowMore);
			dpPanelCloseTransientPanels(rowMore);
			requestAnimationFrame(function(){
				dpPanelPlaceRowActionMenu(rowMore);
				dpPanelPrepareRowActionMenu(rowMore);
			});
		}
		else {
			rowMore.removeAttribute("open");
			dpPanelPrepareRowActionMenu(rowMore);
		}
		return;
	}
	var actionGroupSummary=event.target&&event.target.closest ? event.target.closest(".dp-panel-action-group>summary") : null;
	if(actionGroupSummary&&actionGroupSummary.closest(".dp-panel")){
		event.preventDefault();
		event.stopImmediatePropagation();
		var actionGroup=actionGroupSummary.closest(".dp-panel-action-group");
		var openActionGroup=actionGroup&&!actionGroup.open;
		if(!actionGroup){return;}
		if(openActionGroup){
			actionGroup.open=true;
			dpPanelPrepareActionGroupMenu(actionGroup);
			dpPanelCloseTransientPanels(actionGroup);
		}
		else {
			actionGroup.removeAttribute("open");
			dpPanelPrepareActionGroupMenu(actionGroup);
		}
		return;
	}
	var openTransient=event.target.closest(".dp-panel-horizontal-group[open],.dp-panel-row-more[open],.dp-panel-column-picker[open],.dp-panel-action-group[open],.dp-panel-saved-view-menu[open]");
	if(openTransient){return;}
	dpPanelCloseTransientPanels(null);
});
dpPanelListen(window,"resize",function(){dpPanelRefreshOpenRowActionMenus();dpPanelRefreshOpenActionGroupMenus();dpPanelPlaceOpenHorizontalMenus();});
dpPanelListen(window,"scroll",function(){dpPanelRefreshOpenRowActionMenus();dpPanelRefreshOpenActionGroupMenus();dpPanelPlaceOpenHorizontalMenus();},true);
/**
 * Determines whether a keyboard event target is an editable control.
 *
 * @param {Element|null} target Event target candidate.
 * @returns {boolean} Whether global shortcuts should ignore the event.
 */
function dpPanelIsTypingTarget(target){
	return !!target&&!!target.closest("input,select,textarea,[contenteditable='true']");
}
/**
 * Collects visible focusable descendants from a container.
 *
 * @param {Element|null} container Search root.
 * @returns {Element[]} Visible focusable elements in DOM order.
 */
function dpPanelFocusable(container){
	if(!container){return [];}
	return Array.prototype.slice.call(container.querySelectorAll("a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex]:not([tabindex='-1'])")).filter(function(element){
		return dpPanelCommandElementVisible(element);
	});
}
/**
 * Keeps Tab focus cycling inside a modal or floating surface.
 *
 * @param {Element} container Focus trap root.
 * @param {KeyboardEvent} event Keydown event.
 * @returns {boolean} Whether the event was handled.
 */
function dpPanelTrapFocus(container,event){
	if(event.key!=="Tab"){return false;}
	var items=dpPanelFocusable(container);
	if(!items.length){return false;}
	var first=items[0];
	var last=items[items.length-1];
	if(event.shiftKey&&document.activeElement===first){
		event.preventDefault();
		last.focus();
		return true;
	}
	if(!event.shiftKey&&document.activeElement===last){
		event.preventDefault();
		first.focus();
		return true;
	}
	return false;
}
/**
 * Focuses the primary table or global search input.
 *
 * @param {boolean} preferGlobal Whether to prefer the global search control.
 * @returns {boolean} Whether a search input was focused.
 */
function dpPanelFocusSearch(preferGlobal){
	var selector=preferGlobal?"[data-dp-panel-global-search-input]":"[data-dp-panel-search-input]";
	var input=document.querySelector(selector)||document.querySelector("[data-dp-panel-search-input]");
	if(!input){return false;}
	input.focus();
	if(typeof input.select==="function"){input.select();}
	return true;
}
/**
 * Focuses the sidebar navigation search input when present.
 *
 * @returns {boolean} Whether the sidebar search input was focused.
 */
function dpPanelFocusSidebarSearch(){
	var input=document.querySelector("[data-dp-panel-sidebar-search]");
	if(!input){return false;}
	input.focus();
	if(typeof input.select==="function"){input.select();}
	return true;
}
/**
 * Opens the filter modal for the current view or reports that none exists.
 *
 * @returns {void}
 */
function dpPanelToggleFilters(){
	var trigger=document.querySelector("[data-dp-panel-filter-modal]");
	if(!trigger){dpPanelToast(dpPanelText("client.no_filters","No filters on this view"),"warning");return;}
	if(typeof dpPanelOpenFilterModal==="function"){dpPanelOpenFilterModal(trigger);}
	else {trigger.click();}
}
/**
 * Opens the column picker and focuses its search or trigger control.
 *
 * @returns {void}
 */
function dpPanelOpenColumnPicker(){
	var picker=document.querySelector(".dp-panel-column-picker");
	if(!picker){dpPanelToast(dpPanelText("client.no_columns","No column controls on this view"),"warning");return;}
	picker.open=true;
	dpPanelCloseTransientPanels(picker);
	var input=picker.querySelector("[data-dp-panel-column-search]");
	if(input){input.focus();input.select();}
	else {
		var summary=picker.querySelector("summary");
		if(summary){summary.focus();}
	}
}
/**
 * Returns the shared toast root, creating it on first use.
 *
 * @returns {HTMLDivElement} Toast container with polite live-region semantics.
 */
function dpPanelToastRoot(){
	var root=document.querySelector(".dp-panel-toast-root");
	if(root){return root;}
	root=document.createElement("div");
	root.className="dp-panel-toast-root";
	root.setAttribute("aria-live","polite");
	root.setAttribute("aria-atomic","false");
	document.body.appendChild(root);
	return root;
}
/**
 * Extracts display text from a notification payload.
 *
 * @param {string|Object<string, *>|null} notification Notification object or raw text.
 * @returns {string} Human-facing notification text.
 */
function dpPanelNotificationText(notification){
	if(!notification){return "";}
	if(typeof notification==="string"){return notification;}
	var title=notification.title?String(notification.title):"";
	var message=notification.message?String(notification.message):"";
	return title&&message ? title+": "+message : (message||title);
}
/**
 * Renders a transient or persistent Panel toast notification.
 *
 * Notification objects may provide type, tone, icon, title, message, action URL,
 * action label, duration, and persistence metadata. Text is escaped before it is
 * inserted into generated markup.
 *
 * @param {string|Object<string, *>} notification Notification payload or text.
 * @param {string} tone Fallback tone for raw text notifications.
 * @returns {void}
 */
function dpPanelToast(notification,tone){
	var object=notification&&typeof notification==="object"&&!Array.isArray(notification) ? notification : null;
	var message=object ? dpPanelNotificationText(object) : String(notification||"");
	if(!message){return;}
	var root=dpPanelToastRoot();
	var toast=document.createElement("div");
	var type=String((object?(object.type||object.tone):tone)||"info").toLowerCase().replace(/[^a-z_]/g,"")||"info";
	toast.className="dp-panel-toast dp-panel-toast-"+type;
	var icon=object&&object.icon?String(object.icon):type.slice(0,2).toUpperCase();
	var title=object&&object.title?String(object.title):"";
	var body=object&&object.message?String(object.message):message;
	var actionUrl=object&&(object.action_url||object.url)?String(object.action_url||object.url):"";
	var actionLabel=object&&object.action_label?String(object.action_label):"Open";
	var persistent=object&&object.persistent===true;
	var duration=object&&object.duration_ms!==undefined&&object.duration_ms!==null ? parseInt(object.duration_ms,10) : 4200;
	if(!isFinite(duration)){duration=4200;}
	var progress=!persistent&&duration>0 ? "<span class=\"dp-panel-toast-progress\" style=\"animation-duration:"+Math.max(1200,duration)+"ms\"></span>" : "";
	toast.innerHTML="<span class=\"dp-panel-toast-icon\" aria-hidden=\"true\">"+dpPanelEscape(icon)+"</span><span class=\"dp-panel-toast-copy\">"+(title?"<strong>"+dpPanelEscape(title)+"</strong>":"")+"<span>"+dpPanelEscape(body)+"</span></span>"+progress;
	if(actionUrl){
		var action=document.createElement("a");
		action.href=actionUrl;
		action.textContent=actionLabel;
		toast.appendChild(action);
	}
	var close=document.createElement("button");
	close.type="button";
	close.setAttribute("aria-label","Dismiss notification");
	close.innerHTML="&times;";
	close.addEventListener("click",function(){
		toast.classList.remove("show");
		setTimeout(function(){toast.remove();},220);
	});
	toast.appendChild(close);
	root.appendChild(toast);
	requestAnimationFrame(function(){toast.classList.add("show");});
	if(!persistent&&duration>0){
		setTimeout(function(){
			toast.classList.remove("show");
			setTimeout(function(){toast.remove();},220);
		},Math.max(1200,duration));
	}
}
/**
 * Returns visible row-selection checkboxes within a scope.
 *
 * @param {Document|Element|Object} scope Search scope, or document by default.
 * @returns {HTMLInputElement[]} Selectable row checkboxes.
 */
function dpPanelSelectionInputs(scope){
	return Array.prototype.slice.call((scope||document).querySelectorAll("input[name='selected[]']")).filter(function(input){
		return !input.disabled&&dpPanelCommandElementVisible(input);
	});
}
/**
 * Resolves the table scope used by keyboard selection commands.
 *
 * @returns {Document|Element} Active table shell, focused table, bulk form, or document.
 */
function dpPanelSelectionScope(){
	var active=document.activeElement&&document.activeElement.closest ? document.activeElement.closest(".dp-panel-table-shell,.dp-panel-table") : null;
	if(active){return active;}
	var focused=document.querySelector(".dp-panel-row-focused");
	if(focused){return focused.closest(".dp-panel-table")||focused.closest(".dp-panel-table-shell")||document;}
	return document.querySelector(".dp-panel-table-shell")||document.querySelector(".dp-panel-bulk-form")||document;
}
/**
 * Resolves row-selection scope for a bulk action bar.
 *
 * Form-associated controls may live outside the table, so this helper can return
 * a query facade that limits checkbox reads to inputs bound to the same form id.
 *
 * @param {Element|null} bar Bulk action bar element.
 * @returns {Document|Element|Object} Scope object with `querySelectorAll`.
 */
function dpPanelSelectionScopeForBar(bar){
	if(!bar){return document;}
	var formId="";
	var action=bar.querySelector("[form]");
	if(action){formId=action.getAttribute("form")||"";}
	if(formId){
		return {
			querySelectorAll:function(selector){
				if(selector==="input[name='selected[]']"){
					return document.querySelectorAll("input[name='selected[]'][form='"+formId+"']");
				}
				return document.querySelectorAll(selector);
			}
		};
	}
	var previous=bar.previousElementSibling;
	while(previous){
		if(previous.matches&&previous.matches("[data-dp-panel-table-shell]")){return previous;}
		previous=previous.previousElementSibling;
	}
	return document;
}
/**
 * Sets checked state for a group of row-selection inputs.
 *
 * @param {HTMLInputElement[]} inputs Selection checkboxes.
 * @param {boolean} checked Desired checked state.
 * @returns {void}
 */
function dpPanelSetSelection(inputs,checked){
	inputs.forEach(function(input){input.checked=checked;});
	dpPanelUpdateBulkSelection();
}
/**
 * Selects every visible row in the active selection scope.
 *
 * @returns {void}
 */
function dpPanelSelectVisibleRows(){
	var inputs=dpPanelSelectionInputs(dpPanelSelectionScope());
	if(!inputs.length){dpPanelToast(dpPanelText("client.no_selectable_rows","No selectable rows here"),"warning");return;}
	dpPanelSetSelection(inputs,true);
	dpPanelToast(inputs.length===1 ? dpPanelText("client.row_selected","1 row selected") : dpPanelText("client.rows_selected","{count} rows selected",{count:inputs.length}),"success");
}
/**
 * Inverts visible row selection in the active selection scope.
 *
 * @returns {void}
 */
function dpPanelInvertVisibleRows(){
	var inputs=dpPanelSelectionInputs(dpPanelSelectionScope());
	if(!inputs.length){dpPanelToast(dpPanelText("client.no_selectable_rows","No selectable rows here"),"warning");return;}
	inputs.forEach(function(input){input.checked=!input.checked;});
	dpPanelUpdateBulkSelection();
	dpPanelToast(dpPanelText("client.selection_inverted","Selection inverted"),"success");
}
/**
 * Clears selected visible rows in the active selection scope.
 *
 * @returns {void}
 */
function dpPanelClearSelectedRows(){
	var inputs=dpPanelSelectionInputs(dpPanelSelectionScope()).filter(function(input){return input.checked;});
	if(!inputs.length){dpPanelToast(dpPanelText("client.no_selected_rows","No selected rows to clear"),"warning");return;}
	dpPanelSetSelection(inputs,false);
	dpPanelToast(dpPanelText("client.selection_cleared","Selection cleared"),"success");
}
/**
 * Builds a selection summary for command palette and bulk action feedback.
 *
 * @returns {{count: number, total: number, label: string, search: string}} Selection summary payload.
 */
function dpPanelSelectionSummary(){
	var scope=dpPanelSelectionScope();
	var all=dpPanelSelectionInputs(scope);
	var selected=all.filter(function(input){return input.checked;});
	var count=selected.length;
	var total=all.length;
	var label=count===1 ? dpPanelText("client.selected_record","1 selected record") : dpPanelText("client.selected_records","{count} selected records",{count:count});
	if(total>0){
		label+=dpPanelText("client.visible_suffix"," of {total} visible",{total:total});
	}
	return {count:count,total:total,label:label,search:count+" selected "+total+" visible selection rows records"};
}
var dpPanelCommandLastFocus=null;
/**
 * Returns the singleton command palette root, creating its dialog shell on demand.
 *
 * The shell is client-owned UI inserted outside the server-rendered Panel body.
 * It carries combobox/listbox semantics and closes when the overlay itself is
 * clicked, while command contents are rebuilt each time the palette opens.
 *
 * @returns {HTMLDivElement} Command palette overlay root.
 */
JS;
	}

}
