[global]
daemonize = no
error_log = /var/log/dataphyre/php-fpm-error.log
log_level = warning
process_control_timeout = 5s

[dataphyre-web]
listen = /run/dataphyre/web/php-fpm.sock
listen.mode = 0600
pm = static
pm.max_children = 8
pm.max_requests = 500
request_terminate_timeout = 300s
request_terminate_timeout_track_finished = yes
clear_env = yes
catch_workers_output = yes
decorate_workers_output = no
security.limit_extensions = .php
php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_flag[expose_php] = off
php_admin_value[user_ini.filename] =
php_admin_value[auto_prepend_file] = /opt/dataphyre/runtime/modules/core/kernel/application_runtime_fpm_environment.php
php_admin_value[auto_append_file] =
php_admin_value[opcache.validate_timestamps] = 0
php_admin_value[opcache.file_update_protection] = 0
