/*************************************************************************
 * Dataphyre Panel local-first browser runtime
 * Copyright (c) 2026 Shopiro Ltd. — SPDX-License-Identifier: MIT
 */
(function(global){
"use strict";

var VERSION=1,DB_VERSION=1,PREFIX="dataphyre:panel-local-first:",ACTIVE_REQUEST="active",SYNC_TAG="dataphyre-panel-local-first";
var STORE_NAMES=["meta","keys","documents","queue","requests","receipts","conflicts"];
var PRIVATE=new WeakMap(),encoder=new TextEncoder(),decoder=new TextDecoder();

function LocalFirstError(code,message,retryable){this.name="PanelLocalFirstError";this.code=code;this.message=message;this.retryable=retryable===true;if(Error.captureStackTrace){Error.captureStackTrace(this,LocalFirstError);}}
LocalFirstError.prototype=Object.create(Error.prototype);LocalFirstError.prototype.constructor=LocalFirstError;
function fail(code,message,retryable){throw new LocalFirstError(code,message,retryable);}
function plain(value){if(value===null||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype){throw new TypeError("Expected an object-like map.");}return value;}
function token(value,label,max){if(typeof value!=="string"||value.length<1||value.length>max||/[\u0000-\u001f\u007f]/.test(value)){throw new TypeError(label+" is invalid.");}return value;}
function identifier(value,label,max){value=token(String(value),label,max||128);if(!/^[A-Za-z0-9][A-Za-z0-9_.:@-]*$/.test(value)){throw new TypeError(label+" is invalid.");}return value;}
function name(value,label,max){value=token(String(value),label,max||96).trim().toLowerCase();if(!/^[a-z][a-z0-9_.-]*$/.test(value)){throw new TypeError(label+" is invalid.");}return value;}
function path(value){value=token(String(value),"Sync field path",256).trim();if(!/^[A-Za-z][A-Za-z0-9_-]*(?:\.[A-Za-z][A-Za-z0-9_-]*)*$/.test(value)){throw new TypeError("Sync field path is invalid.");}return value;}
function integer(value,label,min,max){value=Number(value);if(!Number.isSafeInteger(value)||value<min||value>max){throw new TypeError(label+" is outside its safe bound.");}return value;}
function bytesCompare(left,right){var a=encoder.encode(left),b=encoder.encode(right),length=Math.min(a.length,b.length);for(var i=0;i<length;i++){if(a[i]!==b[i]){return a[i]-b[i];}}return a.length-b.length;}
function canonical(value,depth,state){depth=depth||0;state=state||{items:0};if(depth>32||++state.items>20000){throw new TypeError("Local-first value exceeds its structural bound.");}if(value===null||typeof value==="string"||typeof value==="boolean"){if(typeof value==="string"&&encoder.encode(value).byteLength>262144){throw new TypeError("Local-first string exceeds its byte bound.");}return value;}if(typeof value==="number"){if(!Number.isFinite(value)){throw new TypeError("Local-first number is invalid.");}return Object.is(value,-0)?0:value;}if(Array.isArray(value)){if(value.length>4096){throw new TypeError("Local-first array exceeds its item bound.");}return value.map(function(item){return canonical(item,depth+1,state);});}plain(value);var keys=Object.keys(value).sort(bytesCompare),result={};if(keys.length>4096){throw new TypeError("Local-first object exceeds its item bound.");}keys.forEach(function(key){if(key.length===0||encoder.encode(key).byteLength>512){throw new TypeError("Local-first object key is invalid.");}result[key]=canonical(value[key],depth+1,state);});return result;}
function digestCanonical(value,depth,state){depth=depth||0;state=state||{items:0};if(depth>32||++state.items>20000){throw new TypeError("Local-first digest value exceeds its structural bound.");}if(typeof value==="number"){if(!Number.isFinite(value)){throw new TypeError("Local-first numbers must be finite.");}value=Object.is(value,-0)?0:value;var buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setFloat64(0,value,false);return{"@panel_number_f64":hex(new Uint8Array(buffer))};}if(value===null||typeof value==="string"||typeof value==="boolean"){return value;}if(Array.isArray(value)){return value.map(function(item){return digestCanonical(item,depth+1,state);});}plain(value);var result={};Object.keys(value).sort(bytesCompare).forEach(function(key){result[key]=digestCanonical(value[key],depth+1,state);});return result;}
function canonicalJson(value){return JSON.stringify(canonical(value));}
function digestJson(value){return JSON.stringify(canonical(digestCanonical(value)));}
function hex(value){return Array.prototype.map.call(value,function(byte){return byte.toString(16).padStart(2,"0");}).join("");}
function unhex(value){if(typeof value!=="string"||value.length%2!==0||!/^[a-f0-9]+$/.test(value)){throw new TypeError("Hex value is invalid.");}var output=new Uint8Array(value.length/2);for(var i=0;i<output.length;i++){output[i]=parseInt(value.slice(i*2,i*2+2),16);}return output;}
function base64Url(value){var bytes=value instanceof Uint8Array?value:new Uint8Array(value),binary="";for(var i=0;i<bytes.length;i+=32768){binary+=String.fromCharCode.apply(null,bytes.subarray(i,i+32768));}return global.btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function fromBase64Url(value,max){if(typeof value!=="string"||value.length===0||value.length>(max*2+16)||!/^[A-Za-z0-9_-]+$/.test(value)){throw new TypeError("Base64url value is invalid.");}var source=value.replace(/-/g,"+").replace(/_/g,"/");source+="=".repeat((4-source.length%4)%4);var binary=global.atob(source),bytes=new Uint8Array(binary.length);if(bytes.length>max){throw new TypeError("Base64url value exceeds its bound.");}for(var i=0;i<binary.length;i++){bytes[i]=binary.charCodeAt(i);}if(base64Url(bytes)!==value){throw new TypeError("Base64url value is not canonical.");}return bytes;}
function randomToken(size){var bytes=new Uint8Array(size);global.crypto.getRandomValues(bytes);return base64Url(bytes);}
function instant(value){var date=value instanceof Date?value:new Date(value===undefined?Date.now():value);if(!Number.isFinite(date.getTime())){throw new TypeError("Instant is invalid.");}return date.toISOString().replace(/\.(\d{3})Z$/,function(unused,milliseconds){return"."+milliseconds+"000Z";});}
function safeText(value,label,max){if(typeof value!=="string"||value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value)){throw new TypeError(label+" is invalid.");}return value;}
async function sha256(value){return hex(new Uint8Array(await global.crypto.subtle.digest("SHA-256",typeof value==="string"?encoder.encode(value):value)));}
function clone(value){return JSON.parse(JSON.stringify(value));}
function freeze(value){if(value===null||typeof value!=="object"||Object.isFrozen(value)){return value;}Object.keys(value).forEach(function(key){freeze(value[key]);});return Object.freeze(value);}
function credentialQueryName(value){var parts=String(value).replace(/([a-z0-9])([A-Z])/g,"$1_$2").toLowerCase().split(/[^a-z0-9]+/).filter(Boolean),compact=parts.join("");return parts.some(function(part){return ["auth","key","sig","ticket"].indexOf(part)>=0;})||/token|intent|authorization|credential|secret|apikey|accesskey|password|passwd|sessionid|sessionkey|csrf|xsrf|jwt|signature|cookie|bearer|privatekey|clientsecret|refreshtoken/.test(compact);}
function safeEndpoint(value,allowOrigins){var base=global.location&&global.location.href?global.location.href:"https://panel.invalid/",url;try{url=new URL(token(value,"Local-first endpoint",2048),base);}catch(error){throw new TypeError("Local-first endpoint is invalid.");}if(!/^https?:$/.test(url.protocol)||url.username||url.password||url.hash){throw new TypeError("Local-first endpoint is unsafe.");}url.searchParams.forEach(function(unused,key){if(credentialQueryName(key)){throw new TypeError("Local-first endpoint query cannot carry credentials.");}});var origin=global.location&&global.location.origin?global.location.origin:new URL(base).origin;if(url.origin!==origin&&(allowOrigins||[]).indexOf(url.origin)<0){throw new TypeError("Cross-origin local-first endpoints require an exact allowlist.");}if(origin.indexOf("https://")===0&&url.protocol!=="https:"){throw new TypeError("Local-first endpoint cannot downgrade HTTPS.");}return url.href;}
function eventTarget(){return typeof global.EventTarget==="function"?new global.EventTarget():{listeners:{},addEventListener:function(type,fn){(this.listeners[type]||(this.listeners[type]=[])).push(fn);},removeEventListener:function(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(function(item){return item!==fn;});},dispatchEvent:function(event){(this.listeners[event.type]||[]).slice().forEach(function(fn){fn(event);});return true;}};}
function customEvent(type,detail){if(typeof global.CustomEvent==="function"){return new global.CustomEvent(type,{detail:detail});}return{type:type,detail:detail};}

function requestValue(request){return new Promise(function(resolve,reject){request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error||new Error("IndexedDB request failed."));};});}
function transactionDone(transaction){return new Promise(function(resolve,reject){transaction.oncomplete=function(){resolve();};transaction.onerror=transaction.onabort=function(){reject(transaction.error||new Error("IndexedDB transaction failed."));};});}
function openDatabase(nameValue){return new Promise(function(resolve,reject){var request=global.indexedDB.open(nameValue,DB_VERSION);request.onupgradeneeded=function(){var db=request.result;STORE_NAMES.forEach(function(store){if(!db.objectStoreNames.contains(store)){db.createObjectStore(store,{keyPath:"id"});}});};request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error||new Error("IndexedDB open failed."));};request.onblocked=function(){reject(new LocalFirstError("database_blocked","Local-first storage upgrade is blocked by another tab.",true));};});}
async function dbGet(db,store,id){var transaction=db.transaction(store,"readonly"),done=transactionDone(transaction),value=await requestValue(transaction.objectStore(store).get(id));await done;return value||null;}
async function dbPut(db,store,value){var transaction=db.transaction(store,"readwrite");transaction.objectStore(store).put(value);await transactionDone(transaction);return value;}
async function dbDelete(db,store,id){var transaction=db.transaction(store,"readwrite");transaction.objectStore(store).delete(id);await transactionDone(transaction);}
async function dbAll(db,store){var transaction=db.transaction(store,"readonly"),done=transactionDone(transaction),values=await requestValue(transaction.objectStore(store).getAll());await done;return values;}
async function metaGet(db,id,fallback){var record=await dbGet(db,"meta",id);return record?record.value:fallback;}
async function metaPut(db,id,value){await dbPut(db,"meta",{id:id,value:value});return value;}

async function ensureEncryptionKey(db){var stored=await dbGet(db,"keys","data");if(stored&&stored.value){return stored.value;}var key=await global.crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);await dbPut(db,"keys",{id:"data",value:key});return key;}
async function ensureDevice(db){var privateRecord=await dbGet(db,"keys","device_private"),publicKey=await metaGet(db,"device_public",null),deviceId=await metaGet(db,"device_id",null);if(privateRecord&&privateRecord.value&&typeof publicKey==="string"&&typeof deviceId==="string"){return{privateKey:privateRecord.value,publicKey:publicKey,deviceId:deviceId};}var generated=await global.crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),pkcs8=await global.crypto.subtle.exportKey("pkcs8",generated.privateKey),spki=await global.crypto.subtle.exportKey("spki",generated.publicKey),privateKey=await global.crypto.subtle.importKey("pkcs8",pkcs8,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);new Uint8Array(pkcs8).fill(0);publicKey=base64Url(spki);deviceId="device_"+randomToken(18);await dbPut(db,"keys",{id:"device_private",value:privateKey});await metaPut(db,"device_public",publicKey);await metaPut(db,"device_id",deviceId);return{privateKey:privateKey,publicKey:publicKey,deviceId:deviceId};}
function aad(state,store,id){return encoder.encode(PREFIX+VERSION+":"+state.dbName+":"+store+":"+id);}
async function seal(state,store,id,value){var iv=new Uint8Array(12);global.crypto.getRandomValues(iv);var encoded=encoder.encode(canonicalJson(value)),cipher=await global.crypto.subtle.encrypt({name:"AES-GCM",iv:iv,additionalData:aad(state,store,id),tagLength:128},state.encryptionKey,encoded);return{version:1,algorithm:"A256GCM",iv:base64Url(iv),ciphertext:base64Url(cipher)};}
async function unseal(state,store,id,payload){if(!payload||payload.version!==1||payload.algorithm!=="A256GCM"){fail("storage_corrupt","Encrypted local-first record is invalid.",false);}try{var clear=await global.crypto.subtle.decrypt({name:"AES-GCM",iv:fromBase64Url(payload.iv,12),additionalData:aad(state,store,id),tagLength:128},state.encryptionKey,fromBase64Url(payload.ciphertext,4194304));return canonical(JSON.parse(decoder.decode(clear)));}catch(error){fail("storage_integrity_failed","Encrypted local-first record failed integrity verification.",false);}}
async function encryptedPut(state,store,id,value,extra){var record=Object.assign({id:id,sealed:await seal(state,store,id,value)},extra||{});return dbPut(state.db,store,record);}
async function encryptedGet(state,store,id){var record=await dbGet(state.db,store,id);return record?unseal(state,store,id,record.sealed):null;}
async function encryptedAll(state,store){var records=await dbAll(state.db,store),values=[];for(var i=0;i<records.length;i++){values.push({record:records[i],value:await unseal(state,store,records[i].id,records[i].sealed)});}return values;}

function credentialUnsigned(value){return{actor_id:value.actor_id,tenant_id:value.tenant_id,device_id:value.device_id,public_key:value.public_key,public_key_fingerprint:value.public_key_fingerprint,sources:value.sources,abilities:value.abilities,issued_at:value.issued_at,expires_at:value.expires_at,key_id:value.key_id};}
async function credentialFingerprint(value){return sha256(canonicalJson(Object.assign(credentialUnsigned(value),{signature:value.signature})));}
async function validateCredential(value,device,options){plain(value);if(value.type!=="panel_local_first_device_credential"||value.version!==1||value.schema_version!==1||value.api_version!==1||typeof value.credential_id!=="string"||!/^lfc_[a-f0-9]{48}$/.test(value.credential_id)||value.device_id!==device.deviceId||value.public_key!==device.publicKey||!Array.isArray(value.sources)||!Array.isArray(value.abilities)||value.abilities.length===0||typeof value.signature!=="string"){fail("credential_invalid","Local-first device credential is invalid.",false);}identifier(value.actor_id,"Credential actor",128);if(value.tenant_id!==null){identifier(value.tenant_id,"Credential tenant",128);}value.sources=Array.from(new Set(value.sources.map(function(source){return name(source,"Credential source",96);}))).sort();value.abilities=Array.from(new Set(value.abilities.map(function(ability){return name(ability,"Credential ability",96);}))).sort();if(options.actorId&&String(options.actorId)!==value.actor_id||options.tenantProvided&&(options.tenantId===null?null:String(options.tenantId))!==value.tenant_id){fail("credential_scope_mismatch","Local-first credential scope does not match the host scope.",false);}if(new Date(value.expires_at).getTime()<=Date.now()){fail("credential_expired","Local-first device credential has expired.",false);}var publicFingerprint=await sha256(fromBase64Url(value.public_key,2048));if(publicFingerprint!==value.public_key_fingerprint){fail("credential_invalid","Local-first credential public-key fingerprint is invalid.",false);}var identityDigest=await sha256(canonicalJson(credentialUnsigned(value))),expected="lfc_"+identityDigest.slice(0,48);if(expected!==value.credential_id){fail("credential_invalid","Local-first credential identity is invalid.",false);}return freeze(clone(value));}
async function ensureCredential(db,device,options){var candidate=options.credential||await metaGet(db,"credential",null);if(candidate&&new Date(candidate.expires_at).getTime()<=Date.now()&&typeof options.registerDevice==="function"){candidate=null;}if(!candidate){if(typeof options.registerDevice!=="function"){fail("credential_required","A host-issued local-first device credential is required.",false);}candidate=await options.registerDevice(freeze({type:"panel_local_first_device_registration",version:1,device_id:device.deviceId,public_key:device.publicKey,public_key_fingerprint:await sha256(fromBase64Url(device.publicKey,2048))}));}candidate=await validateCredential(clone(candidate),device,options);await metaPut(db,"credential",candidate);return candidate;}
async function importResponseKeys(db,input){if(input!==undefined){plain(input);var ids=Object.keys(input);if(ids.length>16){throw new TypeError("Too many local-first response keys.");}for(var i=0;i<ids.length;i++){var id=name(ids[i],"Response key id",96),raw=fromBase64Url(input[ids[i]],128);if(raw.length<32){throw new TypeError("Local-first response keys require at least 32 bytes.");}var key=await global.crypto.subtle.importKey("raw",raw,{name:"HMAC",hash:"SHA-256"},false,["verify"]);raw.fill(0);await dbPut(db,"keys",{id:"response:"+id,value:key});}}}
async function responseKey(db,id){var record=await dbGet(db,"keys","response:"+name(id,"Response key id",96));return record&&record.value?record.value:null;}

function normalizeOptions(input){input=Object.assign({},input||{});if(!global.crypto||!global.crypto.subtle||!global.indexedDB||typeof global.fetch!=="function"){fail("unsupported_runtime","Local-first operation requires WebCrypto, IndexedDB, and fetch.",false);}var dbName=token(input.dbName||"dataphyre_panel_local_first","Local-first database name",128);if(!/^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(dbName)){throw new TypeError("Local-first database name is invalid.");}var allowOrigins=Array.isArray(input.allowOrigins)?input.allowOrigins.map(function(origin){return new URL(origin).origin;}):[];var endpoint=safeEndpoint(input.endpoint,allowOrigins),tenantProvided=Object.prototype.hasOwnProperty.call(input,"tenantId");return{dbName:dbName,endpoint:endpoint,allowOrigins:allowOrigins,credential:input.credential,registerDevice:input.registerDevice,responseKeys:input.responseKeys,actorId:input.actorId,tenantId:tenantProvided?input.tenantId:undefined,tenantProvided:tenantProvided,autoSync:input.autoSync!==false,headless:input.headless===true,fetcher:typeof input.fetcher==="function"?input.fetcher:global.fetch.bind(global),headers:normalizeHeaders(input.headers),serviceWorkerUrl:input.serviceWorkerUrl?token(input.serviceWorkerUrl,"Service-worker URL",2048):null,maxMutationBatch:integer(input.maxMutationBatch===undefined?100:input.maxMutationBatch,"Mutation batch size",1,100),maxDocumentBatch:integer(input.maxDocumentBatch===undefined?128:input.maxDocumentBatch,"Document batch size",1,128),requestTimeout:integer(input.requestTimeout===undefined?30000:input.requestTimeout,"Request timeout",1000,120000)};}
function normalizeHeaders(input){if(input===undefined){return{};}plain(input);var output={};Object.keys(input).forEach(function(key){if(!/^[A-Za-z0-9-]{1,96}$/.test(key)||credentialQueryName(key)){throw new TypeError("Local-first header is invalid.");}var value=token(String(input[key]),"Local-first header value",4096);output[key]=value;});return output;}
function sourceActor(credential){return credential.actor_id+"@"+credential.device_id;}
function stateOf(client){var state=PRIVATE.get(client);if(!state){throw new TypeError("Local-first client is unavailable.");}return state;}
function emit(client,type,detail){var state=stateOf(client),payload=freeze(canonical(Object.assign({type:type,at:instant()},detail||{})));state.events.dispatchEvent(customEvent(type,payload));if(global.document&&typeof global.document.dispatchEvent==="function"){global.document.dispatchEvent(customEvent("dataphyre:panel-local-first",payload));}if(state.channel){state.channel.postMessage({type:"state",source:state.instanceId});}}
async function counts(state){var queue=await dbAll(state.db,"queue"),documents=await encryptedAll(state,"documents"),conflicts=await dbAll(state.db,"conflicts");return{queued:queue.filter(function(row){return row.status!=="blocked";}).length,blocked:queue.filter(function(row){return row.status==="blocked";}).length,dirty_documents:documents.filter(function(item){return item.value.pending_operations&&item.value.pending_operations.length;}).length,open_conflicts:conflicts.filter(function(row){return row.status!=="resolved";}).length};}
async function refreshStatus(client){var state=stateOf(client),totals=await counts(state);state.status=Object.assign({},state.status,totals,{online:!global.navigator||global.navigator.onLine!==false});return freeze(Object.assign({},state.status));}

function emptyDocument(id){return{id:id,clock:{},fields:{},conflicts:[],revision:0,base_clock:{},pending_operations:[]};}
function normalizeOperation(operation){plain(operation);var kind=operation.op===undefined?"set":String(operation.op);if(kind!=="set"&&kind!=="delete"){throw new TypeError("Sync operation must be set or delete.");}var normalized={op:kind,path:path(operation.path)};if(kind==="set"){if(!Object.prototype.hasOwnProperty.call(operation,"value")){normalized.value=null;}else{normalized.value=canonical(operation.value);}}return normalized;}
function applyOperations(documentValue,actor,operations,track){var document=clone(documentValue),clock=Object.assign({},document.clock),fields=Object.assign({},document.fields);operations=operations.map(normalizeOperation);if(operations.length<1||operations.length>512){throw new TypeError("Sync changes require 1-512 operations.");}operations.forEach(function(operation){clock[actor]=(clock[actor]||0)+1;fields[operation.path]={value:operation.op==="delete"?null:operation.value,clock:Object.assign({},clock),actor:actor,tombstone:operation.op==="delete"};});document.clock=canonical(clock);document.fields=canonical(fields);document.revision=integer((document.revision||0)+1,"Document revision",0,Number.MAX_SAFE_INTEGER);if(track){document.pending_operations=(document.pending_operations||[]).concat(operations);if(document.pending_operations.length>4096){throw new TypeError("Offline document queue exceeds 4096 operations.");}}return document;}
function materialize(documentValue){var output={};Object.keys(documentValue.fields||{}).sort(bytesCompare).forEach(function(fieldPath){var register=documentValue.fields[fieldPath];if(register.tombstone){return;}var segments=fieldPath.split("."),cursor=output;segments.forEach(function(segment,index){if(index===segments.length-1){cursor[segment]=clone(register.value);}else{if(!cursor[segment]||typeof cursor[segment]!=="object"||Array.isArray(cursor[segment])){cursor[segment]={};}cursor=cursor[segment];}});});return output;}
function normalizeMutation(source,input){source=name(source,"Mutation source",96);plain(input);var operation=String(input.operation||"").toLowerCase();if(["create","update","upsert","delete"].indexOf(operation)<0){throw new TypeError("Mutation operation is invalid.");}var key=typeof input.key==="number"?integer(input.key,"Mutation key",-Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER):token(String(input.key),"Mutation key",512),values=operation==="delete"?{}:canonical(plain(input.values||{})),expected=input.expected_revision===undefined?null:input.expected_revision;if(expected!==null){expected=integer(expected,"Expected revision",0,Number.MAX_SAFE_INTEGER);}if((operation==="update"||operation==="delete")&&expected===null){throw new TypeError("Update and delete mutations require an expected revision.");}if(operation==="create"&&expected!==null){throw new TypeError("Create mutations cannot carry an expected revision.");}return{source:source,mutation:{operation:operation,key:key,values:values,idempotency_key:input.idempotency_key?token(input.idempotency_key,"Idempotency key",512):"offline_"+randomToken(24),metadata:canonical(plain(input.metadata||{})),expected_revision:expected,reason:input.reason===undefined?"":safeText(String(input.reason),"Mutation reason",1000),return_record:input.return_record!==false}};}

async function buildMutationWork(state){var records=await encryptedAll(state,"queue"),pending=records.filter(function(item){return item.record.status!=="blocked";}).sort(function(a,b){return String(a.record.created_at).localeCompare(String(b.record.created_at));});if(!pending.length){return null;}var source=pending[0].value.source,selected=pending.filter(function(item){return item.value.source===source;}).slice(0,state.options.maxMutationBatch);return{kind:"mutation_batch",payload:{type:"panel_local_first_mutation_batch",version:1,source:source,atomic:true,mutations:selected.map(function(item){return item.value.mutation;})},refs:selected.map(function(item){return{id:item.record.id};})};}
async function buildDocumentWork(state){var records=await encryptedAll(state,"documents"),selected=records.filter(function(item){return(item.value.pending_operations||[]).length>0;}).sort(function(a,b){return a.value.id.localeCompare(b.value.id);}).slice(0,state.options.maxDocumentBatch);if(!selected.length){return null;}return{kind:"document_sync",payload:{type:"panel_local_first_document_batch",version:1,changes:selected.map(function(item){return{document_id:item.value.id,base_clock:item.value.base_clock||{},operations:item.value.pending_operations.slice(0,512)};})},refs:selected.map(function(item){return{id:item.record.id,document_id:item.value.id,count:Math.min(512,item.value.pending_operations.length)};})};}
async function makeRequest(state,work){var sequence=integer((await metaGet(state.db,"sequence",0))+1,"Request sequence",1,Number.MAX_SAFE_INTEGER),issuedAt=instant(),nonce=randomToken(24),credential=state.credential,credentialDigest=await credentialFingerprint(credential),unsigned={credential_id:credential.credential_id,credential_fingerprint:credentialDigest,sequence:sequence,issued_at:issuedAt,nonce:nonce,kind:work.kind,payload:work.payload},digest=await sha256(digestJson(unsigned)),signature=base64Url(await global.crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},state.privateKey,encoder.encode(digest)));var request={type:"panel_local_first_request",schema_version:1,api_version:1,version:1,credential:credential,credential_id:credential.credential_id,credential_fingerprint:credentialDigest,sequence:sequence,issued_at:issuedAt,nonce:nonce,kind:work.kind,payload:work.payload,digest:digest,signature:signature};return{request:request,kind:work.kind,refs:work.refs,attempts:0,created_at:issuedAt};}
async function activeRequest(state){return encryptedGet(state,"requests",ACTIVE_REQUEST);}
async function ensureActiveRequest(state){var active=await activeRequest(state);if(active){return active;}var work=await buildMutationWork(state)||await buildDocumentWork(state);if(!work){return null;}active=await makeRequest(state,work);await encryptedPut(state,"requests",ACTIVE_REQUEST,active);return active;}
async function verifyResponse(state,active,response){plain(response);if(response.type!=="panel_local_first_response"||response.version!==1||response.schema_version!==1||response.api_version!==1||response.request_digest!==active.request.digest||response.sequence!==active.request.sequence||["ok","partial","conflict","rejected","error"].indexOf(response.status)<0||typeof response.key_id!=="string"||typeof response.digest!=="string"||typeof response.signature!=="string"){fail("response_invalid","Local-first response does not match its request.",true);}var unsigned={request_digest:response.request_digest,sequence:response.sequence,status:response.status,body:response.body,issued_at:response.issued_at,key_id:response.key_id},digest=await sha256(digestJson(unsigned));if(digest!==response.digest){fail("response_digest_invalid","Local-first response digest is invalid.",true);}var key=await responseKey(state.db,response.key_id);if(!key){fail("response_key_unknown","Local-first response key is not trusted.",true);}var valid=await global.crypto.subtle.verify("HMAC",key,unhex(response.signature),encoder.encode(response.digest));if(!valid){fail("response_signature_invalid","Local-first response signature is invalid.",true);}return canonical(response);}
function authoritativeDocument(payload){plain(payload);if(payload.type!=="panel_sync_document"||payload.version!==1||typeof payload.id!=="string"||!payload.clock||!payload.fields||!Array.isArray(payload.conflicts)){fail("response_document_invalid","Local-first response contains an invalid document.",false);}return{id:identifier(payload.id,"Sync document id",128),clock:canonical(payload.clock),fields:canonical(payload.fields),conflicts:canonical(payload.conflicts),revision:integer(payload.revision,"Document revision",0,Number.MAX_SAFE_INTEGER),base_clock:canonical(payload.clock),pending_operations:[]};}
async function recordConflicts(state,documentValue){var conflicts=documentValue.conflicts||[];for(var i=0;i<conflicts.length;i++){var conflict=canonical(conflicts[i]),id=await sha256(canonicalJson({document_id:documentValue.id,conflict:conflict})),existing=await dbGet(state.db,"conflicts",id);if(!existing){await encryptedPut(state,"conflicts",id,{id:id,document_id:documentValue.id,path:conflict.path,winner:conflict.winner,resolved_by:conflict.resolved_by,created_at:instant()},{status:"open",document_hash:await sha256(documentValue.id)});}}}
async function applyAccepted(state,active,response){if(active.kind==="mutation_batch"){for(var i=0;i<active.refs.length;i++){await dbDelete(state.db,"queue",active.refs[i].id);}}else{var authoritative={};(response.body.documents||[]).forEach(function(payload){authoritative[payload.id]=authoritativeDocument(payload);});for(var j=0;j<active.refs.length;j++){var ref=active.refs[j],current=await encryptedGet(state,"documents",ref.id),server=authoritative[ref.document_id];if(!current||!server){fail("response_document_missing","Local-first response omitted an accepted document.",true);}var tail=(current.pending_operations||[]).slice(ref.count);if(tail.length){server.base_clock=clone(server.clock);server=applyOperations(server,state.sourceActor,tail,true);}await encryptedPut(state,"documents",ref.id,server,{dirty:tail.length>0,document_hash:await sha256(server.id)});await recordConflicts(state,server);}}await metaPut(state.db,"sequence",response.sequence);await encryptedPut(state,"receipts",response.digest,{response:response,received_at:instant()});await dbDelete(state.db,"requests",ACTIVE_REQUEST);}
async function blockActive(state,active,response){var code=response.body&&response.body.error&&typeof response.body.error.code==="string"?response.body.error.code:"request_rejected";if(active.kind==="mutation_batch"){for(var i=0;i<active.refs.length;i++){var record=await dbGet(state.db,"queue",active.refs[i].id);if(record){record.status="blocked";record.error_code=code;await dbPut(state.db,"queue",record);}}}await dbDelete(state.db,"requests",ACTIVE_REQUEST);}
async function transmit(client,active){var state=stateOf(client),controller=new AbortController(),timer=global.setTimeout(function(){controller.abort();},state.options.requestTimeout),response,textValue,payload;try{var headers=Object.assign({"Accept":"application/json","Content-Type":"application/json"},state.options.headers);response=await state.options.fetcher(state.options.endpoint,{method:"POST",headers:headers,credentials:"same-origin",cache:"no-store",redirect:"error",referrerPolicy:"same-origin",body:JSON.stringify(active.request),signal:controller.signal});textValue=await response.text();if(encoder.encode(textValue).byteLength>4194304){fail("response_too_large","Local-first response exceeds 4 MiB.",true);}try{payload=JSON.parse(textValue);}catch(error){fail("response_json_invalid","Local-first response is not valid JSON.",true);}payload=await verifyResponse(state,active,payload);var committed=payload.status==="ok"||payload.status==="partial"||payload.status==="conflict"&&payload.body&&Array.isArray(payload.body.documents);if(committed){await applyAccepted(state,active,payload);state.status.last_error=null;emit(client,payload.status==="conflict"?"conflict":"synced",{sequence:payload.sequence,status:payload.status,request_digest:payload.request_digest});return true;}var retryable=!!(payload.body&&payload.body.error&&payload.body.error.retryable);if(retryable){active.attempts=integer((active.attempts||0)+1,"Request attempts",0,100000);await encryptedPut(state,"requests",ACTIVE_REQUEST,active);state.status.last_error=payload.body.error.code||"retryable_error";emit(client,"retry",{code:state.status.last_error,attempts:active.attempts});return false;}await blockActive(state,active,payload);state.status.last_error=payload.body&&payload.body.error?payload.body.error.code:"request_rejected";emit(client,"blocked",{code:state.status.last_error});return false;}catch(error){var safe=error instanceof LocalFirstError?error:new LocalFirstError(error&&error.name==="AbortError"?"request_timeout":"network_error",error&&error.name==="AbortError"?"Local-first synchronization timed out.":"Local-first synchronization failed.",true);active.attempts=integer((active.attempts||0)+1,"Request attempts",0,100000);await encryptedPut(state,"requests",ACTIVE_REQUEST,active);state.status.last_error=safe.code;emit(client,"retry",{code:safe.code,attempts:active.attempts});return false;}finally{global.clearTimeout(timer);}}

async function acquireFallbackLease(state){var transaction=state.db.transaction("meta","readwrite"),done=transactionDone(transaction),store=transaction.objectStore("meta"),record=await requestValue(store.get("sync_lease")),now=Date.now();if(record&&record.value&&record.value.expires>now&&record.value.owner!==state.instanceId){transaction.abort();try{await done;}catch(error){}return false;}store.put({id:"sync_lease",value:{owner:state.instanceId,expires:now+45000}});await done;return true;}
async function releaseFallbackLease(state){var record=await metaGet(state.db,"sync_lease",null);if(record&&record.owner===state.instanceId){await metaPut(state.db,"sync_lease",{owner:"",expires:0});}}
async function withSyncLock(state,callback){if(global.navigator&&global.navigator.locks&&typeof global.navigator.locks.request==="function"){return global.navigator.locks.request(PREFIX+state.dbName,{mode:"exclusive",ifAvailable:true},function(lock){return lock?callback():false;});}if(!await acquireFallbackLease(state)){return false;}try{return await callback();}finally{await releaseFallbackLease(state);}}
function schedule(client,delay){var state=stateOf(client);if(state.stopped||!state.options.autoSync){return;}if(state.timer){global.clearTimeout(state.timer);}state.timer=global.setTimeout(function(){state.timer=null;client.sync().catch(function(){});},delay===undefined?50:delay);}

function Client(state){PRIVATE.set(this,state);}
Client.prototype.addEventListener=function(type,listener,options){stateOf(this).events.addEventListener(type,listener,options);return this;};Client.prototype.removeEventListener=function(type,listener,options){stateOf(this).events.removeEventListener(type,listener,options);return this;};
Client.prototype.status=async function(){return refreshStatus(this);};
Client.prototype.queueMutation=async function(source,input){var state=stateOf(this);if(state.stopped){fail("client_stopped","Local-first client is stopped.",false);}var normalized=normalizeMutation(source,input);if(state.credential.sources.indexOf(normalized.source)<0||state.credential.abilities.indexOf("mutate")<0){fail("credential_scope_mismatch","Local-first credential does not grant this mutation source.",false);}var id="mutation_"+randomToken(18),created=instant();await encryptedPut(state,"queue",id,normalized,{status:"pending",created_at:created});emit(this,"queued",{kind:"mutation",queue_id:id,source:normalized.source});await scheduleBackground(this);schedule(this);return freeze({id:id,idempotency_key:normalized.mutation.idempotency_key,queued_at:created});};
Client.prototype.unblockMutation=async function(id){var state=stateOf(this),record=await dbGet(state.db,"queue",token(id,"Queue id",128));if(!record){return false;}record.status="pending";delete record.error_code;await dbPut(state.db,"queue",record);schedule(this);return true;};
Client.prototype.discardMutation=async function(id){var state=stateOf(this);await dbDelete(state.db,"queue",token(id,"Queue id",128));emit(this,"discarded",{kind:"mutation",queue_id:id});return true;};
Client.prototype.change=async function(documentId,operations){var state=stateOf(this);if(state.credential.abilities.indexOf("sync")<0){fail("credential_scope_mismatch","Local-first credential does not grant document synchronization.",false);}documentId=identifier(documentId,"Sync document id",128);var storageId=await sha256("document:"+documentId),documentValue=await encryptedGet(state,"documents",storageId)||emptyDocument(documentId);if(!(documentValue.pending_operations||[]).length){documentValue.base_clock=clone(documentValue.clock||{});}documentValue=applyOperations(documentValue,state.sourceActor,operations,true);await encryptedPut(state,"documents",storageId,documentValue,{dirty:true,document_hash:await sha256(documentId)});emit(this,"changed",{document_id:documentId,revision:documentValue.revision,pending_operations:documentValue.pending_operations.length});await scheduleBackground(this);schedule(this);return freeze({id:documentId,revision:documentValue.revision,clock:clone(documentValue.clock),value:materialize(documentValue),pending_operations:documentValue.pending_operations.length});};
Client.prototype.document=async function(documentId){var state=stateOf(this);documentId=identifier(documentId,"Sync document id",128);var documentValue=await encryptedGet(state,"documents",await sha256("document:"+documentId));return documentValue?freeze({id:documentValue.id,revision:documentValue.revision,clock:clone(documentValue.clock),value:materialize(documentValue),conflicts:clone(documentValue.conflicts||[]),pending_operations:(documentValue.pending_operations||[]).length}):null;};
Client.prototype.conflicts=async function(){var state=stateOf(this),records=await encryptedAll(state,"conflicts");return freeze(records.map(function(item){return Object.assign({},item.value,{status:item.record.status});}).sort(function(a,b){return String(a.created_at).localeCompare(String(b.created_at));}));};
Client.prototype.resolveConflict=async function(conflictId,value){var state=stateOf(this),id=token(conflictId,"Conflict id",128),record=await dbGet(state.db,"conflicts",id);if(!record){return false;}var conflict=await unseal(state,"conflicts",id,record.sealed);await this.change(conflict.document_id,[{op:"set",path:conflict.path,value:value}]);record.status="resolved";record.resolved_at=instant();await dbPut(state.db,"conflicts",record);emit(this,"conflict-resolved",{conflict_id:id,document_id:conflict.document_id,path:conflict.path});return true;};
Client.prototype.sync=async function(){var client=this,state=stateOf(client);if(state.stopped){return false;}if(state.syncPromise){return state.syncPromise;}state.syncPromise=withSyncLock(state,async function(){if(global.navigator&&global.navigator.onLine===false){state.status.online=false;emit(client,"offline",{});return false;}state.status.syncing=true;emit(client,"syncing",{});try{var progressed=false;for(var cycle=0;cycle<32;cycle++){var active=await ensureActiveRequest(state);if(!active){break;}if(!await transmit(client,active)){break;}progressed=true;}return progressed;}finally{state.status.syncing=false;var settled=await refreshStatus(client);emit(client,"settled",{queued:settled.queued,dirty_documents:settled.dirty_documents,open_conflicts:settled.open_conflicts});}}).finally(function(){state.syncPromise=null;});return state.syncPromise;};
Client.prototype.bindStatus=function(root){var client=this,state=stateOf(client),documentValue=root&&root.querySelectorAll?root:global.document;if(!documentValue){return function(){};}var render=async function(){var status=await client.status(),nodes=documentValue.querySelectorAll("[data-dp-local-first-status]");nodes.forEach(function(node){var label=status.syncing?"Syncing":status.online?(status.queued||status.dirty_documents?"Changes pending":"Up to date"):"Offline";node.textContent=label;node.setAttribute("data-status",status.syncing?"syncing":status.online?"online":"offline");node.setAttribute("data-queued",String(status.queued+status.dirty_documents));node.setAttribute("data-conflicts",String(status.open_conflicts));if(!node.hasAttribute("aria-live")){node.setAttribute("aria-live","polite");}});};var listener=function(){render().catch(function(){});},types=["queued","changed","synced","settled","offline","conflict"];types.forEach(function(type){state.events.addEventListener(type,listener);});render().catch(function(){});return function(){types.forEach(function(type){state.events.removeEventListener(type,listener);});};};
Client.prototype.bindConflictCenter=function(container,options){var client=this;options=options||{};if(!container||typeof container.replaceChildren!=="function"||!global.document){throw new TypeError("Conflict center requires a DOM container.");}var render=async function(){var conflicts=(await client.conflicts()).filter(function(item){return item.status!=="resolved";}),fragment=global.document.createDocumentFragment();if(!conflicts.length){var empty=global.document.createElement("p");empty.textContent=options.emptyLabel||"No unresolved offline conflicts.";empty.className="dp-panel-local-first-conflict-empty";fragment.appendChild(empty);}conflicts.forEach(function(conflict){var article=global.document.createElement("article"),title=global.document.createElement("h3"),copy=global.document.createElement("p"),button=global.document.createElement("button");article.className="dp-panel-local-first-conflict";article.dataset.conflictId=conflict.id;title.textContent=conflict.document_id+" · "+conflict.path;copy.textContent="Concurrent edits were detected. Deterministic winner: "+String(conflict.winner||"unknown")+".";button.type="button";button.textContent=options.resolveLabel||"Resolve";button.addEventListener("click",async function(){if(typeof options.valueFor!=="function"){return;}button.disabled=true;try{var value=await options.valueFor(conflict);await client.resolveConflict(conflict.id,value);await render();}finally{button.disabled=false;}});article.append(title,copy,button);fragment.appendChild(article);});container.replaceChildren(fragment);container.setAttribute("aria-live","polite");};render().catch(function(){});var state=stateOf(client),listener=function(){render().catch(function(){});};state.events.addEventListener("conflict",listener);state.events.addEventListener("conflict-resolved",listener);return function(){state.events.removeEventListener("conflict",listener);state.events.removeEventListener("conflict-resolved",listener);};};
Client.prototype.stop=async function(){var state=stateOf(this);state.stopped=true;if(state.timer){global.clearTimeout(state.timer);}emit(this,"stopped",{});if(state.channel){state.channel.close();state.channel=null;}if(global.removeEventListener){global.removeEventListener("online",state.online);global.removeEventListener("offline",state.offline);}state.db.close();};

async function scheduleBackground(client){var state=stateOf(client);if(!global.navigator||!global.navigator.serviceWorker||typeof global.navigator.serviceWorker.getRegistration!=="function"){return false;}try{var registration=await global.navigator.serviceWorker.getRegistration();if(!registration){return false;}var worker=registration.active||registration.waiting;if(worker){worker.postMessage({type:"dp-panel-local-first-register",db_name:state.dbName,endpoint:state.options.endpoint});}if(registration.sync&&typeof registration.sync.register==="function"){await registration.sync.register(SYNC_TAG);}return true;}catch(error){return false;}}
async function registerServiceWorker(client){var state=stateOf(client),url=state.options.serviceWorkerUrl;if(!url||!global.navigator||!global.navigator.serviceWorker){return null;}url=safeEndpoint(url,state.options.allowOrigins);var registration=await global.navigator.serviceWorker.register(url);await global.navigator.serviceWorker.ready;await scheduleBackground(client);return registration;}

async function open(input){var options=normalizeOptions(input),db=await openDatabase(options.dbName),encryptionKey=await ensureEncryptionKey(db),device=await ensureDevice(db);await importResponseKeys(db,options.responseKeys);var credential=await ensureCredential(db,device,options),state={db:db,dbName:options.dbName,options:options,encryptionKey:encryptionKey,privateKey:device.privateKey,credential:credential,sourceActor:sourceActor(credential),instanceId:randomToken(12),events:eventTarget(),channel:null,status:{online:!global.navigator||global.navigator.onLine!==false,syncing:false,queued:0,blocked:0,dirty_documents:0,open_conflicts:0,last_error:null},syncPromise:null,timer:null,stopped:false,online:null,offline:null};await metaPut(db,"runtime_config",{dbName:options.dbName,endpoint:options.endpoint});var client=new Client(state);if(typeof global.BroadcastChannel==="function"){state.channel=new global.BroadcastChannel(PREFIX+options.dbName);state.channel.onmessage=function(event){if(event.data&&event.data.source!==state.instanceId){schedule(client,100);}};}state.online=function(){state.status.online=true;emit(client,"online",{});schedule(client,0);};state.offline=function(){state.status.online=false;emit(client,"offline",{});};if(global.addEventListener){global.addEventListener("online",state.online);global.addEventListener("offline",state.offline);}await refreshStatus(client);if(!options.headless){await registerServiceWorker(client);}if(options.autoSync){schedule(client,0);}return client;}

function workerRegistry(scope){return new Promise(function(resolve,reject){var request=scope.indexedDB.open("dataphyre_panel_local_first_worker",1);request.onupgradeneeded=function(){if(!request.result.objectStoreNames.contains("clients")){request.result.createObjectStore("clients",{keyPath:"db_name"});}};request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error);};});}
async function workerPut(scope,value){var db=await workerRegistry(scope),transaction=db.transaction("clients","readwrite");transaction.objectStore("clients").put(value);await transactionDone(transaction);db.close();}
async function workerAll(scope){var db=await workerRegistry(scope),transaction=db.transaction("clients","readonly"),done=transactionDone(transaction),values=await requestValue(transaction.objectStore("clients").getAll());await done;db.close();return values;}
async function workerSync(scope){var clients=await workerAll(scope);for(var i=0;i<clients.length;i++){try{var endpoint=safeEndpoint(clients[i].endpoint,[]),client=await open({dbName:clients[i].db_name,endpoint:endpoint,headless:true,autoSync:false});await client.sync();await client.stop();}catch(error){}}}
function installServiceWorker(scope){if(!scope||typeof scope.addEventListener!=="function"){throw new TypeError("A service-worker global scope is required.");}scope.addEventListener("install",function(event){event.waitUntil(scope.skipWaiting());});scope.addEventListener("activate",function(event){event.waitUntil(scope.clients.claim());});scope.addEventListener("message",function(event){var data=event.data;if(!data||data.type!=="dp-panel-local-first-register"){return;}event.waitUntil((async function(){var endpoint=safeEndpoint(data.endpoint,[]);await workerPut(scope,{db_name:token(data.db_name,"Local-first database name",128),endpoint:endpoint});})());});scope.addEventListener("sync",function(event){if(event.tag===SYNC_TAG){event.waitUntil(workerSync(scope));}});scope.addEventListener("periodicsync",function(event){if(event.tag===SYNC_TAG){event.waitUntil(workerSync(scope));}});return true;}

function manifest(){return freeze({type:"panel_local_first_client_runtime",version:VERSION,storage:"indexeddb",at_rest_encryption:"aes_256_gcm",device_signatures:"ecdsa_p256",response_authentication:"hmac_sha256",canonical_numbers:"ieee754_big_endian",service_worker:true,background_sync:true,web_locks:true,indexeddb_fenced_fallback:true,broadcast_channel:true,mutation_queue:true,crdt_operation_branches:true,vector_clocks:true,conflict_center:true,exact_request_replay:true,signed_response_before_dequeue:true,host_projected_scope:true,raw_server_keys_persisted:false,non_extractable_keys:true,local_storage:false,html_evaluation:false});}
global.DataphyrePanelLocalFirst=freeze({version:VERSION,open:open,manifest:manifest,canonicalJson:canonicalJson,canonicalDigest:function(value){return sha256(digestJson(value));},installServiceWorker:installServiceWorker,Error:LocalFirstError});
if(typeof module!=="undefined"&&module.exports){module.exports=global.DataphyrePanelLocalFirst;}
})(typeof globalThis!=="undefined"?globalThis:this);
