<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Deterministic process-local replay ledger for tests and single-worker hosts. */
final class PanelInMemoryLocalFirstReplayStore implements PanelLocalFirstReplayStore,\JsonSerializable {
	/** @var array<string,array<int,array{request_digest:string,lease_token:?string,lease_expires_at:int,response:?PanelLocalFirstResponse}>> */private array $records=[];
	public function claim(string $credentialId,int $sequence,string $requestDigest,string|int|\DateTimeInterface $now,int $leaseSeconds=30):PanelLocalFirstReplayClaim{$credentialId=self::id($credentialId);self::sequence($sequence);self::digest($requestDigest);if($leaseSeconds<1||$leaseSeconds>300){throw new \InvalidArgumentException('Local-first replay leases must be 1-300 seconds.');}$instant=PanelOperationsGuard::instant($now);$epoch=strtotime($instant);$existing=$this->records[$credentialId][$sequence]??null;if(is_array($existing)){if(!hash_equals($existing['request_digest'],$requestDigest)){throw new \LogicException('Local-first request sequence was rebound.');}if($existing['response'] instanceof PanelLocalFirstResponse){return PanelLocalFirstReplayClaim::replay($credentialId,$sequence,$requestDigest,$existing['response']);}if($existing['lease_expires_at']>$epoch){throw new PanelLocalFirstReplayException('request_in_flight','The local-first request is already being processed.',true);}$token=bin2hex(random_bytes(32));$expires=$epoch+$leaseSeconds;$this->records[$credentialId][$sequence]['lease_token']=$token;$this->records[$credentialId][$sequence]['lease_expires_at']=$expires;return PanelLocalFirstReplayClaim::acquired($credentialId,$sequence,$requestDigest,$token,PanelOperationsGuard::instant($expires));}
		$rows=$this->records[$credentialId]??[];if($rows!==[]){$latest=max(array_keys($rows));$last=$rows[$latest];if(!$last['response'] instanceof PanelLocalFirstResponse){throw new PanelLocalFirstReplayException('prior_request_in_flight','A prior local-first request is still being processed.',true);}if($sequence!==$latest+1){throw new \LogicException('Local-first request sequence is not contiguous.');}}elseif($sequence!==1){throw new \LogicException('Local-first request sequence is not contiguous.');}$token=bin2hex(random_bytes(32));$expires=$epoch+$leaseSeconds;$this->records[$credentialId][$sequence]=['request_digest'=>$requestDigest,'lease_token'=>$token,'lease_expires_at'=>$expires,'response'=>null];ksort($this->records[$credentialId],SORT_NUMERIC);return PanelLocalFirstReplayClaim::acquired($credentialId,$sequence,$requestDigest,$token,PanelOperationsGuard::instant($expires));}
	public function complete(PanelLocalFirstReplayClaim $claim,PanelLocalFirstResponse $response):void{if(!$claim->acquiredLease()||$response->sequence()!==$claim->sequence()||!hash_equals($response->requestDigest(),$claim->requestDigest())){throw new \InvalidArgumentException('Local-first replay completion does not match its claim.');}$record=$this->records[$claim->credentialId()][$claim->sequence()]??null;if(!is_array($record)||$record['response']!==null||!is_string($record['lease_token'])||!hash_equals($record['lease_token'],(string)$claim->leaseToken())||!hash_equals($record['request_digest'],$claim->requestDigest())){throw new PanelLocalFirstReplayException('lease_lost','The local-first replay lease was lost.',true);}$this->records[$claim->credentialId()][$claim->sequence()]=['request_digest'=>$claim->requestDigest(),'lease_token'=>null,'lease_expires_at'=>0,'response'=>$response];}
	public function abandon(PanelLocalFirstReplayClaim $claim):void{if(!$claim->acquiredLease()){return;}$record=$this->records[$claim->credentialId()][$claim->sequence()]??null;if(is_array($record)&&$record['response']===null&&is_string($record['lease_token'])&&hash_equals($record['lease_token'],(string)$claim->leaseToken())){unset($this->records[$claim->credentialId()][$claim->sequence()]);if($this->records[$claim->credentialId()]===[]){unset($this->records[$claim->credentialId()]);}}}
	public function response(string $credentialId,int $sequence):?PanelLocalFirstResponse{$credentialId=self::id($credentialId);self::sequence($sequence);$response=$this->records[$credentialId][$sequence]['response']??null;return$response instanceof PanelLocalFirstResponse?$response:null;}
	public function latestSequence(string $credentialId):int{$credentialId=self::id($credentialId);$latest=0;foreach($this->records[$credentialId]??[]as$sequence=>$record){if($record['response'] instanceof PanelLocalFirstResponse){$latest=max($latest,$sequence);}}return$latest;}
	public function jsonSerialize():array{$credentials=[];foreach($this->records as$id=>$records){$completed=0;$pending=0;foreach($records as$record){$record['response'] instanceof PanelLocalFirstResponse?$completed++:$pending++;}$credentials[hash('sha256',$id)]=['latest_sequence'=>$this->latestSequence($id),'response_count'=>$completed,'pending_count'=>$pending];}ksort($credentials,SORT_STRING);return PanelManifestContract::stamp(['type'=>'panel_local_first_replay_store_manifest','version'=>2,'driver'=>'memory','credential_count'=>count($credentials),'credentials'=>$credentials,'capabilities'=>['exact_response_replay'=>true,'contiguous_sequences'=>true,'fenced_leases'=>true,'expired_lease_takeover'=>true,'process_local'=>true,'durable'=>false]]);}
	private static function id(string $value):string{if(preg_match('/^lfc_[a-f0-9]{48}$/D',$value)!==1){throw new \InvalidArgumentException('Local-first credential id is invalid.');}return$value;}
	private static function sequence(int $value):void{if($value<1){throw new \InvalidArgumentException('Local-first replay sequence must be positive.');}}private static function digest(string $value):void{if(preg_match('/^[a-f0-9]{64}$/D',$value)!==1){throw new \InvalidArgumentException('Local-first request digest is invalid.');}}
}
