<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Offline-capable replica with signed batches, vector merge, conflicts, and replay guards. */
final class PanelLocalReplica implements \JsonSerializable {
	/** @var array<string,PanelSyncDocument> */private array $documents=[];/** @var array<string,int> */private array $received=[];/** @var array<string,string> */private array $receivedDigests=[];/** @var array<string,array<string,mixed>> */private array $receivedResults=[];/** @var array<string,string> */private array $keys;private int $sequence=0;private readonly ?\Closure $authorizer;private readonly \Closure $clock;
	/** @param array<string,string> $keys */public function __construct(private readonly string $actorId,array $keys,private readonly string $currentKeyId,?callable $authorizer=null,?callable $clock=null){PanelOperationsGuard::identifier($actorId,'local replica actor');if($keys===[]){throw new \InvalidArgumentException('Local replicas require sync keys.');}foreach($keys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'sync key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Sync keys require at least 32 bytes.');}$this->keys[$id]=$key;}if(!isset($this->keys[$currentKeyId])){throw new \InvalidArgumentException('Current sync key is not trusted.');}$this->authorizer=$authorizer!==null?\Closure::fromCallable($authorizer):null;$this->clock=$clock!==null?\Closure::fromCallable($clock):static fn():string=>gmdate('c');}
	/** @param list<array<string,mixed>> $operations */public function change(string $documentId,array $operations):PanelSyncDocument {$this->authorize('sync.local.change',['document_id'=>$documentId,'operation_count'=>count($operations)]);$document=$this->documents[$documentId]??PanelSyncDocument::empty($documentId);$document=$document->apply($this->actorId,$operations);$this->documents[$documentId]=$document;ksort($this->documents,SORT_STRING);return$document;}
	public function document(string $documentId):?PanelSyncDocument {$documentId=PanelOperationsGuard::identifier($documentId,'sync document id');return$this->documents[$documentId]??null;}
	/** @param list<string> $documentIds */public function envelope(array $documentIds=[]):PanelSyncEnvelope {$this->authorize('sync.envelope.create',['document_ids'=>$documentIds]);$documents=$documentIds===[]?array_values($this->documents):array_map(function(string $id):PanelSyncDocument{$document=$this->document($id);if(!$document){throw new \OutOfBoundsException('Sync document is not present on this replica.');}return$document;},PanelOperationsGuard::identifiers($documentIds,'sync document id'));if($documents===[]){throw new \LogicException('Sync envelope cannot be empty.');}$this->sequence++;return PanelSyncEnvelope::sign($this->actorId,$this->sequence,$this->now(),$documents,$this->currentKeyId,$this->keys[$this->currentKeyId]);}
	/** @return array<string,mixed> */public function merge(PanelSyncEnvelope $envelope):array{return$this->mergeEnvelope($envelope,false);}
	/** Exact-idempotent variant for fenced transport recovery after a response-loss crash. @return array<string,mixed> */public function mergeIdempotently(PanelSyncEnvelope $envelope):array{return$this->mergeEnvelope($envelope,true);}
	/** @return array<string,mixed> */private function mergeEnvelope(PanelSyncEnvelope $envelope,bool $idempotent):array {$this->authorize('sync.envelope.merge',['source_actor'=>$envelope->sourceActor(),'sequence'=>$envelope->sequence(),'idempotent'=>$idempotent]);if(!$envelope->verify($this->keys)){throw new \LogicException('Sync envelope signature is not trusted.');}$actor=$envelope->sourceActor();$last=(int)($this->received[$actor]??0);if($envelope->sequence()===$last&&$idempotent&&isset($this->receivedDigests[$actor],$this->receivedResults[$actor])&&hash_equals($this->receivedDigests[$actor],$envelope->digest())){return array_replace($this->receivedResults[$actor],['replayed'=>true]);}if($envelope->sequence()<=$last){throw new \LogicException('Sync envelope replay was rejected.');}$merged=[];$conflicts=0;foreach($envelope->documents()as$remote){$local=$this->documents[$remote->id()]??PanelSyncDocument::empty($remote->id());$before=count($local->conflicts());$next=$local->merge($remote);$this->documents[$remote->id()]=$next;$merged[]=$remote->id();$conflicts+=max(0,count($next->conflicts())-$before);}$result=['source_actor'=>$actor,'sequence'=>$envelope->sequence(),'documents'=>$merged,'new_conflicts'=>$conflicts,'envelope_digest'=>$envelope->digest(),'replayed'=>false];$this->received[$actor]=$envelope->sequence();$this->receivedDigests[$actor]=$envelope->digest();$this->receivedResults[$actor]=$result;ksort($this->documents,SORT_STRING);ksort($this->received,SORT_STRING);ksort($this->receivedDigests,SORT_STRING);ksort($this->receivedResults,SORT_STRING);return$result;}
	/** @return array<string,mixed> */public function checkpoint():array{return['type'=>'panel_local_replica_checkpoint','version'=>2,'actor_id'=>$this->actorId,'sequence'=>$this->sequence,'received'=>$this->received,'received_digests'=>$this->receivedDigests,'received_results'=>$this->receivedResults,'documents'=>array_map(static fn(PanelSyncDocument $document):array=>$document->jsonSerialize(),$this->documents)];}
	/** @param array<string,mixed> $checkpoint */public function restore(array $checkpoint):self {$version=$checkpoint['version']??null;if(($checkpoint['type']??null)!=='panel_local_replica_checkpoint'||!in_array($version,[1,2],true)||($checkpoint['actor_id']??null)!==$this->actorId||!is_int($checkpoint['sequence']??null)||$checkpoint['sequence']<0||!is_array($checkpoint['received']??null)||!is_array($checkpoint['documents']??null)||($version===2&&(!is_array($checkpoint['received_digests']??null)||!is_array($checkpoint['received_results']??null)))){throw new \UnexpectedValueException('Local replica checkpoint is invalid.');}$documents=[];foreach($checkpoint['documents']as$id=>$payload){if(!is_string($id)||!is_array($payload)){throw new \UnexpectedValueException('Local replica checkpoint document is invalid.');}$document=PanelSyncDocument::restore($payload);if($document->id()!==$id){throw new \UnexpectedValueException('Local replica checkpoint document id is invalid.');}$documents[$id]=$document;}$received=[];$digests=[];$results=[];foreach($checkpoint['received']as$actor=>$sequence){$actor=PanelOperationsGuard::identifier((string)$actor,'sync source actor');if(!is_int($sequence)||$sequence<0){throw new \UnexpectedValueException('Local replica replay cursor is invalid.');}$received[$actor]=$sequence;if($version===2){$digest=$checkpoint['received_digests'][$actor]??null;$result=$checkpoint['received_results'][$actor]??null;if(!is_string($digest)||preg_match('/^[a-f0-9]{64}$/D',$digest)!==1||!is_array($result)||($result['source_actor']??null)!==$actor||($result['sequence']??null)!==$sequence||($result['envelope_digest']??null)!==$digest||($result['replayed']??null)!==false){throw new \UnexpectedValueException('Local replica replay evidence is invalid.');}$digests[$actor]=$digest;$results[$actor]=PanelOperationsGuard::canonical($result);}}if($version===2&&(count($checkpoint['received_digests'])!==count($received)||count($checkpoint['received_results'])!==count($received))){throw new \UnexpectedValueException('Local replica replay evidence is invalid.');}$this->documents=$documents;$this->received=$received;$this->receivedDigests=$digests;$this->receivedResults=$results;$this->sequence=$checkpoint['sequence'];ksort($this->documents,SORT_STRING);ksort($this->received,SORT_STRING);ksort($this->receivedDigests,SORT_STRING);ksort($this->receivedResults,SORT_STRING);return$this;}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_local_replica_manifest','version'=>2,'actor_id'=>$this->actorId,'sequence'=>$this->sequence,'document_count'=>count($this->documents),'received_cursors'=>$this->received,'key_ids'=>array_keys($this->keys),'current_key_id'=>$this->currentKeyId,'default_deny'=>$this->authorizer===null,'capabilities'=>['offline_changes'=>true,'vector_clocks'=>true,'field_register_crdt'=>true,'tombstones'=>true,'deterministic_conflict_resolution'=>true,'conflict_evidence'=>true,'signed_batches'=>true,'replay_protection'=>true,'exact_transport_replay'=>true,'browser_runtime_asset'=>true,'encrypted_indexeddb_queue'=>true,'service_worker_sync'=>true,'checkpoints'=>true]]);}
	/** @param array<string,mixed> $context */private function authorize(string $ability,array $context):void {if($this->authorizer===null){throw new \LogicException('Local replica authorization is not configured.');}try{$result=($this->authorizer)($ability,$context,$this);$allowed=$result===true||($result instanceof PanelPolicyDecision&&$result->allowed())||($result instanceof PanelSecurityDecision&&$result->allowed());}catch(\Throwable $error){throw new \LogicException('Local replica authorization failed closed.',0,$error);}if(!$allowed){throw new \LogicException('Local replica operation is not authorized.');}}
	private function now():string {$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Local replica clock must return an instant.');}return PanelOperationsGuard::instant($value);}
}
