<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Fail-closed bridge from browser-local work into scoped mutation and CRDT planes. */
final class PanelLocalFirstGateway implements \JsonSerializable {
	/** @var array<string,string> */private readonly array $credentialKeys;/** @var array<string,string> */private readonly array $responseKeys;/** @var array<string,string> */private readonly array $syncKeys;private readonly \Closure $replicaResolver;private readonly \Closure $authorizer;private readonly ?\Closure $scopeResolver;private readonly \Closure $clock;
	/** @param array<string,string> $credentialKeys @param array<string,string> $responseKeys @param array<string,string> $syncKeys */
	public function __construct(private readonly PanelDataSourceRegistry $sources,callable $replicaResolver,array $credentialKeys,array $responseKeys,private readonly string $currentResponseKeyId,array $syncKeys,private readonly string $currentSyncKeyId,private readonly PanelLocalFirstReplayStore $replayStore,callable $authorizer,?callable $scopeResolver=null,?callable $clock=null,private readonly int $maximumClockSkewSeconds=300){
		$this->credentialKeys=self::keys($credentialKeys,'credential');$this->responseKeys=self::keys($responseKeys,'response');$this->syncKeys=self::keys($syncKeys,'sync');if(!isset($this->responseKeys[$currentResponseKeyId])||!isset($this->syncKeys[$currentSyncKeyId])){throw new \InvalidArgumentException('Current local-first response or sync key is not trusted.');}if($maximumClockSkewSeconds<0||$maximumClockSkewSeconds>3600){throw new \InvalidArgumentException('Local-first clock skew must be between 0 and 3600 seconds.');}$this->replicaResolver=\Closure::fromCallable($replicaResolver);$this->authorizer=\Closure::fromCallable($authorizer);$this->scopeResolver=$scopeResolver===null?null:\Closure::fromCallable($scopeResolver);$this->clock=$clock===null?static fn():string=>gmdate('c'):\Closure::fromCallable($clock);
	}

	public function handle(PanelLocalFirstRequest $request):PanelLocalFirstResponse{
		$now=$this->now();$credential=$request->credential();if(!$credential->verify($this->credentialKeys,$now)){throw new \LogicException('Local-first device credential is not trusted.');}if(!$request->verifyDeviceSignature()){throw new \LogicException('Local-first request device signature is invalid.');}$delta=abs(strtotime($now)-strtotime($request->issuedAt()));if($delta>$this->maximumClockSkewSeconds){throw new \LogicException('Local-first request is outside the accepted clock window.');}
		$ability=$request->kind()==='mutation_batch'?'mutate':'sync';if(!$credential->allows($ability)){throw new \LogicException('Local-first credential does not grant this operation.');}$this->authorize('local_first.'.$ability,['credential_id'=>$credential->credentialId(),'actor_id'=>$credential->actorId(),'tenant_id'=>$credential->tenantId(),'device_id'=>$credential->deviceId(),'request_digest'=>$request->digest(),'sequence'=>$request->sequence()]);
		try{$claim=$this->replayStore->claim($credential->credentialId(),$request->sequence(),$request->digest(),$now);}catch(PanelLocalFirstReplayException $error){return$this->respond($request,'error',['error'=>['code'=>$error->publicCode(),'retryable'=>$error->retryable()]],$now);}if(!$claim->acquiredLease()){$stored=$claim->response();if(!$stored instanceof PanelLocalFirstResponse){throw new \UnexpectedValueException('Local-first replay claim omitted its completed response.');}return$stored;}
		try{[$status,$body]=$request->kind()==='mutation_batch'?$this->mutate($request):$this->synchronize($request);$response=$this->respond($request,$status,$body,$now);$this->replayStore->complete($claim,$response);return$response;}
		catch(PanelDataMutationConflict $error){$this->replayStore->abandon($claim);return$this->respond($request,'conflict',['error'=>['code'=>'mutation_conflict','retryable'=>true,'details'=>$error->jsonSerialize()]],$now);}
		catch(PanelDataMutationAccessDenied|PanelDataMutationUnsupported $error){$this->replayStore->abandon($claim);return$this->respond($request,'rejected',['error'=>['code'=>'mutation_rejected','retryable'=>false,'details'=>$error->jsonSerialize()]],$now);}
		catch(\InvalidArgumentException|\OutOfBoundsException|\LogicException $error){$this->replayStore->abandon($claim);return$this->respond($request,'rejected',['error'=>['code'=>'local_first_request_rejected','retryable'=>false]],$now);}
		catch(PanelLocalFirstReplayException $error){throw$error;}
		catch(\Throwable){$this->replayStore->abandon($claim);return$this->respond($request,'error',['error'=>['code'=>'local_first_backend_failure','retryable'=>true]],$now);}
	}

	/** @return array{string,array<string,mixed>} */private function mutate(PanelLocalFirstRequest $request):array{
		$payload=$request->payload();self::shape($payload,['type','version','source','atomic','mutations'],'local-first mutation batch');if(($payload['type']??null)!=='panel_local_first_mutation_batch'||($payload['version']??null)!==1||!is_string($payload['source']??null)||!is_bool($payload['atomic']??null)||!is_array($payload['mutations']??null)||!array_is_list($payload['mutations'])||$payload['mutations']===[]||count($payload['mutations'])>100){throw new \InvalidArgumentException('Local-first mutation batch is invalid.');}$source=PanelOperationsGuard::name($payload['source'],'local-first source');$credential=$request->credential();if(!$credential->allowsSource($source)){throw new \LogicException('Local-first credential does not grant this data source.');}$scope=$this->scope($request);$mutations=[];
		foreach($payload['mutations']as$item){if(!is_array($item)){throw new \InvalidArgumentException('Local-first mutation entry is invalid.');}self::shape($item,['operation','key','values','idempotency_key','metadata','expected_revision','reason','return_record'],'local-first mutation entry');if(!is_string($item['operation']??null)||(!is_string($item['key']??null)&&!is_int($item['key']??null))||!is_array($item['values']??null)||!is_string($item['idempotency_key']??null)||!is_array($item['metadata']??null)||(!is_int($item['expected_revision']??null)&&($item['expected_revision']??null)!==null)||!is_string($item['reason']??null)||!is_bool($item['return_record']??null)){throw new \InvalidArgumentException('Local-first mutation entry is invalid.');}$options=['idempotency_key'=>$item['idempotency_key'],'actor_id'=>$scope['actor_id'],'tenant'=>$scope['tenant'],'authorization'=>$scope['authorization'],'metadata'=>$item['metadata'],'expected_revision'=>$item['expected_revision'],'reason'=>$item['reason'],'return_record'=>$item['return_record']];$mutations[]=PanelDataMutation::make($item['operation'],$item['key'],$item['values'],$options);}
		$result=$this->sources->mutateBatch($source,new PanelDataMutationBatch($mutations,$payload['atomic']));return['ok',['result'=>$result->jsonSerialize()]];
	}

	/** @return array{string,array<string,mixed>} */private function synchronize(PanelLocalFirstRequest $request):array{
		$payload=$request->payload();self::shape($payload,['type','version','changes'],'local-first document batch');if(($payload['type']??null)!=='panel_local_first_document_batch'||($payload['version']??null)!==1||!is_array($payload['changes']??null)||!array_is_list($payload['changes'])||$payload['changes']===[]||count($payload['changes'])>128){throw new \InvalidArgumentException('Local-first document batch is invalid.');}$credential=$request->credential();$replica=($this->replicaResolver)($credential->actorId(),$credential,$request);if(!$replica instanceof PanelLocalReplica){throw new \UnexpectedValueException('Local-first replica resolver returned an invalid replica.');}$branches=[];$ids=[];
		foreach($payload['changes']as$change){if(!is_array($change)){throw new \InvalidArgumentException('Local-first document change is invalid.');}self::shape($change,['document_id','base_clock','operations'],'local-first document change');if(!is_string($change['document_id']??null)||!is_array($change['base_clock']??null)||!is_array($change['operations']??null)||!array_is_list($change['operations'])){throw new \InvalidArgumentException('Local-first document change is invalid.');}$id=PanelOperationsGuard::identifier($change['document_id'],'sync document id');if(isset($ids[$id])){throw new \InvalidArgumentException('Local-first document batches cannot repeat a document.');}$ids[$id]=true;$current=$replica->document($id);$serverClock=$current?->clock()??[];foreach($change['base_clock']as$actor=>$counter){PanelOperationsGuard::identifier((string)$actor,'sync actor id');if(!is_int($counter)||$counter<0||$counter>(int)($serverClock[$actor]??0)){throw new \LogicException('Local-first document base clock is not server-observed.');}}$branches[]=PanelSyncDocument::branch($id,$change['base_clock'],$credential->sourceActor(),$change['operations']);}
		$envelope=PanelSyncEnvelope::sign($credential->sourceActor(),$request->sequence(),$request->issuedAt(),$branches,$this->currentSyncKeyId,$this->syncKeys[$this->currentSyncKeyId]);$merge=$replica->mergeIdempotently($envelope);$documents=[];$conflicts=0;foreach(array_keys($ids)as$id){$document=$replica->document($id);if($document){$documents[]=$document->jsonSerialize();$conflicts+=count($document->conflicts());}}return[$merge['new_conflicts']>0?'conflict':'ok',['merge'=>$merge,'documents'=>$documents,'conflict_count'=>$conflicts]];
	}

	/** @return array{actor_id:string,tenant:?string,authorization:array<string,mixed>} */private function scope(PanelLocalFirstRequest $request):array{$credential=$request->credential();$scope=['actor_id'=>$credential->actorId(),'tenant'=>$credential->tenantId(),'authorization'=>[]];if($this->scopeResolver!==null){try{$resolved=($this->scopeResolver)($credential,$request);}catch(\Throwable $error){throw new \LogicException('Local-first scope resolution failed closed.',0,$error);}if(!is_array($resolved)||array_keys($resolved)!==['actor_id','tenant','authorization']||!is_array($resolved['authorization']??null)){throw new \UnexpectedValueException('Local-first scope resolver returned an invalid scope.');}$scope=$resolved;}if((string)$scope['actor_id']!==$credential->actorId()||$scope['tenant']!==$credential->tenantId()){throw new \LogicException('Local-first scope resolver cannot widen credential identity.');}return['actor_id'=>$credential->actorId(),'tenant'=>$credential->tenantId(),'authorization'=>PanelOperationsGuard::safeMetadata($scope['authorization'])];}
	/** @param array<string,mixed> $body */private function respond(PanelLocalFirstRequest $request,string $status,array $body,string $now):PanelLocalFirstResponse{return PanelLocalFirstResponse::sign($request->digest(),$request->sequence(),$status,$body,$now,$this->currentResponseKeyId,$this->responseKeys[$this->currentResponseKeyId]);}
	/** @param array<string,mixed> $context */private function authorize(string $ability,array $context):void{try{$result=($this->authorizer)($ability,$context,$this);$allowed=$result===true||($result instanceof PanelPolicyDecision&&$result->allowed())||($result instanceof PanelSecurityDecision&&$result->allowed());}catch(\Throwable $error){throw new \LogicException('Local-first gateway authorization failed closed.',0,$error);}if(!$allowed){throw new \LogicException('Local-first gateway operation is not authorized.');}}
	private function now():string{$value=($this->clock)();if(!$value instanceof \DateTimeInterface&&!is_string($value)&&!is_int($value)){throw new \UnexpectedValueException('Local-first gateway clock must return an instant.');}return PanelOperationsGuard::instant($value);}
	/** @param array<string,mixed> $value @param list<string> $keys */private static function shape(array $value,array $keys,string $label):void{$actual=array_keys($value);sort($actual,SORT_STRING);sort($keys,SORT_STRING);if($actual!==$keys){throw new \InvalidArgumentException(ucfirst($label).' shape is invalid.');}}
	/** @param array<string,string> $keys @return array<string,string> */private static function keys(array $keys,string $label):array{if($keys===[]||count($keys)>16){throw new \InvalidArgumentException('Local-first '.$label.' keys are invalid.');}$result=[];foreach($keys as$id=>$key){$id=PanelOperationsGuard::name((string)$id,'local-first '.$label.' key id');if(!is_string($key)||strlen($key)<32){throw new \InvalidArgumentException('Local-first '.$label.' keys require at least 32 bytes.');}$result[$id]=$key;}ksort($result,SORT_STRING);return$result;}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_local_first_gateway_manifest','version'=>1,'credential_key_ids'=>array_keys($this->credentialKeys),'response_key_ids'=>array_keys($this->responseKeys),'sync_key_ids'=>array_keys($this->syncKeys),'current_response_key_id'=>$this->currentResponseKeyId,'current_sync_key_id'=>$this->currentSyncKeyId,'maximum_clock_skew_seconds'=>$this->maximumClockSkewSeconds,'default_deny'=>false,'capabilities'=>['device_attestation'=>true,'p256_request_signatures'=>true,'signed_responses'=>true,'exact_replay'=>true,'contiguous_sequences'=>true,'host_projected_scope'=>true,'mutation_plane'=>true,'crdt_operation_batches'=>true,'client_authored_registers_rejected'=>true,'conflict_evidence'=>true,'secret_keys_serialized'=>false]]);}
}
