<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Field-register CRDT with vector clocks, tombstones, and explicit conflict evidence. */
final class PanelSyncDocument implements \JsonSerializable {
	/** @param array<string,int> $clock @param array<string,array<string,mixed>> $fields @param list<array<string,mixed>> $conflicts */private function __construct(private readonly string $id,private readonly array $clock,private readonly array $fields,private readonly array $conflicts,private readonly int $revision){PanelOperationsGuard::identifier($id,'sync document id');foreach($clock as$actor=>$counter){PanelOperationsGuard::identifier((string)$actor,'sync actor id');if(!is_int($counter)||$counter<0){throw new \InvalidArgumentException('Sync vector clock is invalid.');}}foreach($fields as$path=>$register){self::path((string)$path);self::register($register);}if($revision<0||count($conflicts)>1000){throw new \InvalidArgumentException('Sync document revision or conflict budget is invalid.');}}
	public static function empty(string $id):self{return new self(PanelOperationsGuard::identifier($id,'sync document id'),[],[],[],0);}
	/** Builds a device branch from a server-observed vector without accepting client-authored registers. @param array<string,int> $baseClock @param list<array<string,mixed>> $operations */
	public static function branch(string $id,array $baseClock,string|int $actorId,array $operations):self{return(new self(PanelOperationsGuard::identifier($id,'sync document id'),self::normalizeClock($baseClock),[],[],0))->apply($actorId,$operations);}
	/** @param array<string,mixed> $payload */public static function restore(array $payload):self {$expected=['type','version','id','clock','fields','conflicts','revision','fingerprint'];$keys=array_keys($payload);sort($keys,SORT_STRING);sort($expected,SORT_STRING);if($keys!==$expected||$payload['type']!=='panel_sync_document'||$payload['version']!==1||!is_string($payload['id'])||!is_array($payload['clock'])||!is_array($payload['fields'])||!is_array($payload['conflicts'])||!is_int($payload['revision'])||!is_string($payload['fingerprint'])){throw new \UnexpectedValueException('Stored sync document shape is invalid.');}$document=new self($payload['id'],$payload['clock'],$payload['fields'],$payload['conflicts'],$payload['revision']);if(!hash_equals($document->fingerprint(),$payload['fingerprint'])){throw new \UnexpectedValueException('Stored sync document fingerprint is invalid.');}return$document;}
	/** @param list<array<string,mixed>> $operations */public function apply(string|int $actorId,array $operations):self {$actorId=PanelOperationsGuard::identifier($actorId,'sync actor id');if($operations===[]||count($operations)>512){throw new \InvalidArgumentException('Sync changes require 1 to 512 operations.');}$clock=$this->clock;$fields=$this->fields;foreach($operations as$operation){if(!is_array($operation)){throw new \InvalidArgumentException('Sync operations must be maps.');}$kind=(string)($operation['op']??'set');if(!in_array($kind,['set','delete'],true)){throw new \InvalidArgumentException('Sync operation is invalid.');}$path=self::path((string)($operation['path']??''));$clock[$actorId]=(int)($clock[$actorId]??0)+1;$fields[$path]=['value'=>$kind==='delete'?null:PanelOperationsGuard::canonical($operation['value']??null),'clock'=>$clock,'actor'=>$actorId,'tombstone'=>$kind==='delete'];}ksort($clock,SORT_STRING);ksort($fields,SORT_STRING);return new self($this->id,$clock,$fields,$this->conflicts,$this->revision+1);}
	public function merge(self $remote):self {if($remote->id!==$this->id){throw new \InvalidArgumentException('Sync documents must have matching ids.');}$clock=$this->clock;foreach($remote->clock as$actor=>$counter){$clock[$actor]=max((int)($clock[$actor]??0),$counter);}ksort($clock,SORT_STRING);$fields=$this->fields;$conflicts=$this->conflicts;foreach($remote->fields as$path=>$incoming){$current=$fields[$path]??null;if(!is_array($current)){$fields[$path]=$incoming;continue;}$relation=self::compareClocks($current['clock'],$incoming['clock']);if($relation==='before'){$fields[$path]=$incoming;continue;}if($relation!=='concurrent'||PanelOperationsGuard::digest($current)===PanelOperationsGuard::digest($incoming)){continue;}$currentStamp=[max($current['clock']?:[0]),$current['actor'],PanelOperationsGuard::digest($current)];$incomingStamp=[max($incoming['clock']?:[0]),$incoming['actor'],PanelOperationsGuard::digest($incoming)];$winner=$incomingStamp>$currentStamp?'remote':'local';if($winner==='remote'){$fields[$path]=$incoming;}$conflicts[]=['path'=>$path,'local_digest'=>PanelOperationsGuard::digest($current),'remote_digest'=>PanelOperationsGuard::digest($incoming),'winner'=>$winner,'resolved_by'=>'deterministic_lww_register'];}if(count($conflicts)>1000){$conflicts=array_slice($conflicts,-1000);}ksort($fields,SORT_STRING);return new self($this->id,$clock,$fields,array_values($conflicts),max($this->revision,$remote->revision)+1);}
	public function id():string{return$this->id;}public function revision():int{return$this->revision;}/** @return array<string,int> */public function clock():array{return$this->clock;}/** @return list<array<string,mixed>> */public function conflicts():array{return$this->conflicts;}
	public function get(string $path,mixed $default=null):mixed {$path=self::path($path);$register=$this->fields[$path]??null;return!is_array($register)||$register['tombstone']?$default:$register['value'];}
	/** @return array<string,mixed> */public function materialize():array {$result=[];foreach($this->fields as$path=>$register){if($register['tombstone']){continue;}$segments=explode('.',$path);$cursor=&$result;foreach($segments as$index=>$segment){if($index===count($segments)-1){$cursor[$segment]=$register['value'];}else{$cursor[$segment]??=[];if(!is_array($cursor[$segment])){$cursor[$segment]=[];}$cursor=&$cursor[$segment];}}unset($cursor);}return$result;}
	public function fingerprint():string{return PanelOperationsGuard::digest($this->values());}public function jsonSerialize():array{return$this->values()+['fingerprint'=>$this->fingerprint()];}
	/** @return array<string,mixed> */private function values():array{return['type'=>'panel_sync_document','version'=>1,'id'=>$this->id,'clock'=>$this->clock,'fields'=>$this->fields,'conflicts'=>$this->conflicts,'revision'=>$this->revision];}
	private static function path(string $path):string {$path=trim($path);if($path===''||strlen($path)>256||preg_match('/^[a-zA-Z][a-zA-Z0-9_-]*(?:\.[a-zA-Z][a-zA-Z0-9_-]*)*$/D',$path)!==1){throw new \InvalidArgumentException('Sync field path is invalid.');}return$path;}
	/** @param array<string,int> $clock @return array<string,int> */private static function normalizeClock(array $clock):array{if(count($clock)>512){throw new \LengthException('Sync vector clock exceeds its actor limit.');}$result=[];foreach($clock as$actor=>$counter){$actor=PanelOperationsGuard::identifier((string)$actor,'sync actor id');if(!is_int($counter)||$counter<0){throw new \InvalidArgumentException('Sync vector clock is invalid.');}$result[$actor]=$counter;}ksort($result,SORT_STRING);return$result;}
	/** @param array<string,mixed> $register */private static function register(array $register):void {$expected=['value','clock','actor','tombstone'];$keys=array_keys($register);sort($keys,SORT_STRING);sort($expected,SORT_STRING);if($keys!==$expected||!is_array($register['clock'])||!is_string($register['actor'])||!is_bool($register['tombstone'])){throw new \InvalidArgumentException('Sync field register is invalid.');}foreach($register['clock']as$actor=>$counter){PanelOperationsGuard::identifier((string)$actor,'sync actor id');if(!is_int($counter)||$counter<0){throw new \InvalidArgumentException('Sync field vector clock is invalid.');}}PanelOperationsGuard::canonical($register['value']);}
	/** @param array<string,int> $left @param array<string,int> $right */private static function compareClocks(array $left,array $right):string {$actors=array_unique(array_merge(array_keys($left),array_keys($right)));$leftGreater=false;$rightGreater=false;foreach($actors as$actor){$a=(int)($left[$actor]??0);$b=(int)($right[$actor]??0);$leftGreater=$leftGreater||$a>$b;$rightGreater=$rightGreater||$b>$a;}return$leftGreater&&$rightGreater?'concurrent':($rightGreater?'before':($leftGreater?'after':'equal'));}
}
