<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Dataphyre
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

/**
 * Defines Dataphyre MCP tool dispatch.
 */
trait dataphyre_mcp_registry_surfaces {

	/**
	 * Executes a registered Dataphyre MCP tool by name.
	 *
	 * the dispatcher validates the requested name by exhaustive match,
	 * passes normalized argument arrays into read-oriented helper surfaces, and
	 * wraps every tool result as MCP text content containing pretty JSON.
	 */
	private function call_tool(array $params): array {
		$name=(string)($params['name'] ?? '');
		$args=(array)($params['arguments'] ?? []);
		$args=$this->validate_tool_arguments($name, $args);
		$result=match($name){
			'dataphyre_application_info'=>$this->application_info(),
			'dataphyre_application_catalog'=>$this->application_catalog($args),
			'dataphyre_package_metadata_read'=>$this->read_package_metadata($args),
			'dataphyre_api_docs_static_summary'=>$this->api_docs_static_summary($args),
			'dataphyre_source_api_summary'=>$this->source_api_summary($args),
			'dataphyre_list_modules'=>$this->module_list(),
			'dataphyre_module_describe'=>$this->describe_module((string)($args['module'] ?? ''), (int)($args['limit'] ?? 80)),
			'dataphyre_module_dependency_map'=>$this->module_dependency_map((string)($args['module'] ?? ''), (int)($args['limit'] ?? 120)),
			'dataphyre_runtime_version_summary'=>$this->runtime_version_summary($args),
			'dataphyre_module_docs_pack'=>$this->module_docs_pack((string)($args['module'] ?? ''), (int)($args['max_bytes_per_doc'] ?? 40000)),
			'dataphyre_search_docs'=>$this->search_docs((string)($args['query'] ?? ''), (int)($args['limit'] ?? 12)),
			'dataphyre_read_doc'=>$this->read_doc((string)($args['path'] ?? '')),
			'dataphyre_docs_chunks_export'=>$this->export_docs_chunks($args),
			'dataphyre_docs_index_plan'=>$this->docs_index_plan($args),
			'dataphyre_embeddings_readiness_plan'=>$this->embeddings_readiness_plan($args),
			'dataphyre_remote_docs_readiness_plan'=>$this->remote_docs_readiness_plan($args),
			'dataphyre_datadoc_static_summary'=>$this->datadoc_static_summary(),
			'dataphyre_datadoc_runtime_readiness_plan'=>$this->datadoc_runtime_readiness_plan($args),
			'dataphyre_list_routes'=>$this->list_route_artifacts((int)($args['limit'] ?? 30)),
			'dataphyre_route_manifest_read'=>$this->read_route_manifest($args),
			'dataphyre_route_url_preview'=>$this->preview_route_url($args),
			'dataphyre_route_match_preview'=>$this->preview_route_match($args),
			'dataphyre_route_source_static_summary'=>$this->route_source_static_summary($args),
			'dataphyre_route_source_ambiguity_report'=>$this->route_source_ambiguity_report($args),
			'dataphyre_route_runtime_provenance_plan'=>$this->route_runtime_provenance_plan($args),
			'dataphyre_controller_source_summary'=>$this->controller_source_summary($args),
			'dataphyre_middleware_source_summary'=>$this->middleware_source_summary($args),
			'dataphyre_mvc_config_static_summary'=>$this->mvc_config_static_summary(),
			'dataphyre_mvc_route_cache_summary'=>$this->mvc_route_cache_summary(),
			'dataphyre_list_config_keys'=>$this->list_config_keys((string)($args['scope'] ?? '')),
			'dataphyre_config_shape_read'=>$this->read_config_shape($args),
			'dataphyre_config_value_preview'=>$this->config_value_preview($args),
			'dataphyre_storage_config_summary'=>$this->storage_config_summary($args),
			'dataphyre_storage_driver_catalog'=>$this->storage_driver_catalog(),
			'dataphyre_sql_tables_list'=>$this->list_sql_tables($args),
			'dataphyre_sql_schema_read'=>$this->read_sql_schema($args),
			'dataphyre_sql_clusters_list'=>$this->list_sql_clusters((string)($args['config_path'] ?? '')),
			'dataphyre_sql_query_plan'=>$this->sql_query_plan($args),
			'dataphyre_sql_query_runner_contract'=>$this->sql_query_runner_contract(),
			'dataphyre_sql_runtime_readiness_plan'=>$this->sql_runtime_readiness_plan($args),
			'dataphyre_tracelog_artifacts_list'=>$this->list_tracelog_artifacts($args),
			'dataphyre_tracelog_read'=>$this->read_tracelog_artifact($args),
			'dataphyre_tracelog_search'=>$this->search_tracelog_artifacts($args),
			'dataphyre_diagnostics_last_error'=>$this->diagnostics_last_error($args),
			'dataphyre_browser_diagnostics_readiness_plan'=>$this->browser_diagnostics_readiness_plan($args),
			'dataphyre_flightdeck_surfaces_list'=>$this->list_flightdeck_surfaces($args),
			'dataphyre_unit_tests_list'=>$this->list_unit_test_manifests($args),
			'dataphyre_unit_test_manifest_read'=>$this->read_unit_test_manifest($args),
			'dataphyre_agent_context_generate'=>$this->generate_agent_context($args),
			'dataphyre_scaffold_plan_generate'=>$this->generate_scaffold_plan($args),
			'dataphyre_app_builder_plan_generate'=>$this->generate_app_builder_plan($args),
			'dataphyre_api_scaffold_plan'=>$this->api_scaffold_plan($args),
			'dataphyre_api_recipe_catalog'=>$this->api_recipe_catalog($args),
			'dataphyre_api_cache_static_summary'=>$this->api_cache_static_summary(),
			'dataphyre_openapi_static_contract_summary'=>$this->open_api_static_contract_summary(),
			'dataphyre_openapi_runtime_readiness_plan'=>$this->open_api_runtime_readiness_plan($args),
			'dataphyre_panel_scaffold_catalog'=>$this->panel_scaffold_catalog(),
			'dataphyre_panel_package_manifest_summary'=>$this->panel_package_manifest_summary(),
			'dataphyre_panel_theme_manifest_summary'=>$this->panel_theme_manifest_summary(),
			'dataphyre_panel_documentation_catalog_summary'=>$this->panel_documentation_catalog_summary(),
			'dataphyre_panel_media_manifest_summary'=>$this->panel_media_manifest_summary(),
			'dataphyre_task_pack_generate'=>$this->generate_task_pack($args),
			'dataphyre_apply_audit_plan'=>$this->apply_audit_plan($args),
			'dataphyre_apply_runtime_readiness_plan'=>$this->apply_runtime_readiness_plan($args),
			'dataphyre_run_panel_regression'=>$this->run_panel_regression($args),
			'dataphyre_run_panel_field_catalog_check'=>$this->run_panel_field_catalog_check(),
			'dataphyre_browser_regression_manifest_summary'=>$this->browser_regression_manifest_summary(),
			'dataphyre_verification_surface_catalog'=>$this->verification_surface_catalog($args),
			'dataphyre_php_lint'=>$this->php_lint((array)($args['paths'] ?? [])),
			'dataphyre_release_check'=>$this->run_release_check(),
			'dataphyre_release_triage_summary'=>$this->release_triage_summary(),
			'dataphyre_release_fix_plan'=>$this->release_fix_plan($args),
			'dataphyre_mcp_manifest_export'=>$this->mcp_manifest_export($args),
			'dataphyre_prompt_pack_export'=>$this->prompt_pack_export($args),
			'dataphyre_mcp_prompt_catalog'=>$this->mcp_prompt_catalog($args),
			'dataphyre_mcp_skill_catalog'=>$this->mcp_skill_catalog($args),
			'dataphyre_mcp_skill_manifest_export'=>$this->mcp_skill_manifest_export($args),
			'dataphyre_mcp_skill_registration_audit'=>$this->mcp_skill_registration_audit($args),
			'dataphyre_mcp_skill_pack_export'=>$this->mcp_skill_pack_export($args),
			'dataphyre_mcp_skill_install_plan'=>$this->mcp_skill_install_plan($args),
			'dataphyre_mcp_skill_file_install_plan'=>$this->mcp_skill_file_install_plan($args),
			'dataphyre_mcp_client_config_summary'=>$this->mcp_client_config_summary($args),
			'dataphyre_mcp_client_install_checklist'=>$this->mcp_client_install_checklist($args),
			'dataphyre_mcp_client_config_install_plan'=>$this->mcp_client_config_install_plan($args),
			'dataphyre_mcp_smoke_test_export'=>$this->mcp_smoke_test_export($args),
			'dataphyre_mcp_client_onboarding_pack'=>$this->mcp_client_onboarding_pack($args),
			'dataphyre_mcp_client_troubleshoot'=>$this->mcp_client_troubleshoot($args),
			'dataphyre_mcp_client_compatibility_matrix'=>$this->mcp_client_compatibility_matrix($args),
			'dataphyre_mcp_client_config_audit'=>$this->mcp_client_config_audit($args),
			'dataphyre_mcp_safety_boundary_report'=>$this->mcp_safety_boundary_report(),
			'dataphyre_mcp_status_board'=>$this->mcp_status_board(),
			'dataphyre_mcp_enterprise_adoption_audit'=>$this->mcp_enterprise_adoption_audit($args),
			'dataphyre_mcp_capability_matrix'=>$this->mcp_capability_matrix(),
			'dataphyre_mcp_release_notes_generate'=>$this->mcp_release_notes_generate($args),
			'dataphyre_mcp_surface_changelog'=>$this->mcp_surface_changelog($args),
			'dataphyre_mcp_tool_call_examples_export'=>$this->mcp_tool_call_examples_export($args),
			'dataphyre_mcp_workflow_playbook_export'=>$this->mcp_workflow_playbook_export($args),
			'dataphyre_mcp_workflow_readiness_audit'=>$this->mcp_workflow_readiness_audit($args),
			'dataphyre_mcp_workflow_session_export'=>$this->mcp_workflow_session_export($args),
			'dataphyre_mcp_workflow_transcript_schema_export'=>$this->mcp_workflow_transcript_schema_export($args),
			'dataphyre_mcp_workflow_state_schema_export'=>$this->mcp_workflow_state_schema_export($args),
			'dataphyre_mcp_workflow_state_audit'=>$this->mcp_workflow_state_audit($args),
			'dataphyre_mcp_workflow_state_summary_export'=>$this->mcp_workflow_state_summary_export($args),
			'dataphyre_mcp_workflow_state_transition_export'=>$this->mcp_workflow_state_transition_export($args),
			'dataphyre_mcp_workflow_state_sync_pack_export'=>$this->mcp_workflow_state_sync_pack_export($args),
			'dataphyre_mcp_workflow_state_timeline_export'=>$this->mcp_workflow_state_timeline_export($args),
			'dataphyre_mcp_workflow_state_resume_brief_export'=>$this->mcp_workflow_state_resume_brief_export($args),
			'dataphyre_mcp_workflow_transcript_audit'=>$this->mcp_workflow_transcript_audit($args),
			'dataphyre_mcp_workflow_transcript_summary_export'=>$this->mcp_workflow_transcript_summary_export($args),
			'dataphyre_mcp_workflow_checkpoint_export'=>$this->mcp_workflow_checkpoint_export($args),
			'dataphyre_mcp_workflow_handoff_pack_export'=>$this->mcp_workflow_handoff_pack_export($args),
			'dataphyre_mcp_workflow_catalog'=>$this->mcp_workflow_catalog(),
			'dataphyre_mcp_workflow_lifecycle_export'=>$this->mcp_workflow_lifecycle_export($args),
			'dataphyre_mcp_workflow_next_action_export'=>$this->mcp_workflow_next_action_export($args),
			'dataphyre_mcp_workflow_recommend'=>$this->mcp_workflow_recommend($args),
			'dataphyre_mcp_workflow_recommendation_handoff_export'=>$this->mcp_workflow_recommendation_handoff_export($args),
			'dataphyre_mcp_task_start_pack_export'=>$this->mcp_task_start_pack_export($args),
			'dataphyre_mcp_agent_brief_export'=>$this->mcp_agent_brief_export($args),
			'dataphyre_mcp_tool_finder'=>$this->mcp_tool_finder($args),
			'dataphyre_mcp_resource_finder'=>$this->mcp_resource_finder($args),
			'dataphyre_mcp_docs_coverage_report'=>$this->mcp_docs_coverage_report(),
			'dataphyre_mcp_readiness_report'=>$this->mcp_readiness_report(),
			'dataphyre_mcp_live_validate'=>$this->mcp_live_validate(),
			'dataphyre_mcp_verify_all'=>$this->mcp_verify_all(),
			'dataphyre_mcp_doctor'=>$this->mcp_doctor(),
			default=>throw new InvalidArgumentException('Unknown Dataphyre tool: '.$name),
		};
		return ['content'=>[['type'=>'text', 'text'=>$this->json($result)]]];
	}
}
