<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Dataphyre
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

/**
 * Defines MCP workflow transcript, checkpoint, and handoff surfaces.
 */
trait dataphyre_mcp_client_workflow_transcript_surfaces {

	/**
	 * Exports the schema for workflow transcript records.
	 *
	 * @param array{workflow?:'feature'|'routes'|'sql'|'diagnostics'|'client'|'release'|'generic'|string} $args Schema export options.
	 * @return array Transcript schema payload.
	 */
	private function mcp_workflow_transcript_schema_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		return [
			'export_type'=>'dataphyre_mcp_workflow_transcript_schema_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>$workflow,
			'protocol'=>'2025-11-25',
			'purpose'=>'Describe how MCP clients should capture request/response transcripts for Dataphyre workflow sessions without leaking secrets or app-local details.',
			'schema'=>[
				'transcript_id'=>'string stable client-generated id',
				'workflow'=>'feature|routes|sql|diagnostics|client|release|generic',
				'created_at'=>'ISO-8601 timestamp generated by the client',
				'client'=>[
					'name'=>'string',
					'version'=>'string',
					'transport'=>'stdio',
				],
				'server'=>[
					'name'=>'dataphyre-mcp',
					'protocol'=>'2025-11-25',
				],
				'steps'=>[
					[
						'order'=>'integer',
						'request'=>[
							'method'=>'initialize|tools/list|resources/read|prompts/get|tools/call',
							'tool'=>'optional tools/call name',
							'arguments'=>'redacted object',
						],
						'response'=>[
							'ok'=>'boolean',
							'error_code'=>'optional integer',
							'error_message'=>'optional redacted string',
							'content_summary'=>'short redacted summary',
							'result_keys'=>'array of top-level result keys',
						],
						'redactions'=>'array of redaction labels applied by the client',
					],
				],
				'final_status'=>'passed|failed|partial|not_run',
				'follow_up_tools'=>'array of suggested Dataphyre MCP tools',
				'max_summary_steps'=>'optional integer, default 20, hard cap 50 for summary/checkpoint exports',
				'step_window'=>'summary/checkpoint metadata with policy, limit, hard_cap, total_steps, returned_steps, omitted_steps, and truncated',
			],
			'required_redactions'=>[
				'passwords, tokens, cookies, private keys, Authorization headers, and connection strings',
				'raw config secret values and environment variable values',
				'product-local absolute paths unless the user explicitly needs local debugging context',
				'database names or credentials returned by non-Dataphyre tooling',
				'large trace buffers; keep bounded snippets or summaries only',
			],
			'step_summary_rules'=>[
				'Record method, tool name, status, and top-level result keys for every message.',
				'For tools/call responses, parse content[0].text as JSON when possible and summarize shape instead of copying full payloads.',
				'Keep SQL transcripts to planner output and schema names; do not add executed database results.',
				'Keep diagnostics transcripts redacted and bounded to short symptom summaries.',
				'Attach readiness and session export metadata when the transcript came from Dataphyre workflow helpers.',
			],
			'example_transcript'=>[
				'transcript_id'=>'client-generated-id',
				'workflow'=>$workflow,
				'created_at'=>'2026-01-01T00:00:00Z',
				'client'=>['name'=>'example-client', 'version'=>'1.0.0', 'transport'=>'stdio'],
				'server'=>['name'=>'dataphyre-mcp', 'protocol'=>'2025-11-25'],
				'steps'=>[
					[
						'order'=>1,
						'request'=>['method'=>'initialize', 'arguments'=>[]],
						'response'=>['ok'=>true, 'content_summary'=>'Server initialized.', 'result_keys'=>['protocolVersion', 'serverInfo', 'capabilities']],
						'redactions'=>[],
					],
					[
						'order'=>2,
						'request'=>['method'=>'tools/call', 'tool'=>'dataphyre_mcp_workflow_readiness_audit', 'arguments'=>['workflow'=>$workflow]],
						'response'=>['ok'=>true, 'content_summary'=>'Workflow readiness returned ready status and no missing registered tools.', 'result_keys'=>['audit_type', 'all_ready', 'workflow_audits']],
						'redactions'=>[],
					],
				],
				'final_status'=>'passed',
				'follow_up_tools'=>['dataphyre_mcp_workflow_readiness_audit'],
			],
			'validation_tools'=>[
				'dataphyre_mcp_workflow_session_export',
				'dataphyre_mcp_workflow_readiness_audit',
				'dataphyre_mcp_safety_boundary_report',
			],
			'validation_tool_boundaries'=>$this->mcp_workflow_tool_boundaries([
				'dataphyre_mcp_workflow_session_export',
				'dataphyre_mcp_workflow_readiness_audit',
				'dataphyre_mcp_safety_boundary_report',
			]),
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_transcript_schema'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_transcript_schema'),
			'tool_audience_boundaries'=>$this->mcp_current_tool_audience_boundaries(),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_transcript_schema'),
			'usage_notes'=>[
				'This schema is for client-side transcript capture; the MCP server does not store transcripts.',
				'Prefer summaries and result keys over full response bodies when sharing transcript context with agents.',
				'Keep transcripts generic when they are destined for shared Dataphyre docs or fixtures.',
				'Use dataphyre_mcp_verify_all only before MCP/release-surface workflow claims.',
			],
		];
	}

	/**
	 * Keeps normal workflow tool queues focused on application progress.
	 *
	 * @param array<int,mixed> $tools Tool-like labels from client-owned state or transcripts.
	 * @return array<int,string> Application-first workflow tools, excluding aggregate MCP release validation.
	 */
	private function mcp_workflow_app_tools(array $tools): array {
		return array_values(array_unique(array_filter(array_map(static fn(mixed $tool): string => (string)$tool, $tools), static fn(string $tool): bool => $tool!=='' && $tool!=='dataphyre_mcp_verify_all')));
	}

	/**
	 * Describes workflow helper tool proof boundaries for compact handoff lists.
	 *
	 * @param array<int,mixed> $tools Workflow helper tool names.
	 * @return array<string,array<string,mixed>> Tool-name keyed boundary metadata.
	 */
	private function mcp_workflow_tool_boundaries(array $tools): array {
		$catalog=[
			'dataphyre_mcp_workflow_session_export'=>[
				'audience_scope'=>'client_workflow_capture',
				'purpose'=>'Export an example or client-owned MCP workflow session; it does not prove application behavior.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_workflow_readiness_audit'=>[
				'audience_scope'=>'workflow_metadata_readiness',
				'purpose'=>'Check registered workflow helper availability and missing-tool metadata before a workflow run.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_safety_boundary_report'=>[
				'audience_scope'=>'mcp_safety_metadata',
				'purpose'=>'Inspect MCP safety boundaries and intentionally denied surfaces without executing application behavior.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_workflow_transcript_schema_export'=>[
				'audience_scope'=>'client_workflow_capture',
				'purpose'=>'Describe the client-owned transcript shape and redaction rules for workflow handoffs.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_workflow_state_audit'=>[
				'audience_scope'=>'client_workflow_state',
				'purpose'=>'Audit client-owned workflow state shape, redaction, and resume safety.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_workflow_state_schema_export'=>[
				'audience_scope'=>'client_workflow_state',
				'purpose'=>'Describe the client-owned workflow state shape for resumable handoffs.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_workflow_next_action_export'=>[
				'audience_scope'=>'workflow_navigation',
				'purpose'=>'Select the next MCP planning or verification surface without replacing focused app/module checks.',
				'not_app_behavior_proof'=>true,
			],
			'dataphyre_mcp_live_validate'=>[
				'audience_scope'=>'local_client_setup_not_app_behavior',
				'purpose'=>'Validate local MCP server wiring and core tool registration after setup or client failures.',
				'not_app_behavior_proof'=>true,
				'not_required_for'=>['ordinary application behavior proof', 'focused app/module verification'],
			],
			'dataphyre_mcp_verify_all'=>[
				'audience_scope'=>'publication_validation_not_ordinary_app_work',
				'purpose'=>'Run aggregate MCP/source-checkout validation only for MCP/release-surface workflow claims.',
				'not_app_behavior_proof'=>true,
				'not_required_for'=>['ordinary application behavior proof', 'focused app/module verification'],
			],
		];
		$boundaries=[];
		foreach($tools as $tool){
			$tool_name=(string)$tool;
			if(isset($catalog[$tool_name])){
				$boundaries[$tool_name]=$catalog[$tool_name];
			}
		}
		return $boundaries;
	}

	/**

	 * Audits transcript entries for workflow completeness and risk signals.
	 *
	 * @param array<string,mixed> $args Transcript entries and audit options.
	 * @return array Transcript audit payload.
	 */
	private function mcp_workflow_transcript_audit(array $args): array {
		$expected_workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($expected_workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$expected_workflow='generic';
		}
		$transcript=[];
		$parse_error='';
		if(isset($args['transcript']) && is_array($args['transcript'])){
			$transcript=$args['transcript'];
		}
		elseif(trim((string)($args['transcript_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['transcript_json'], true);
			if(is_array($decoded)){
				$transcript=$decoded;
			}
			else{
				$parse_error='transcript_json could not be decoded as an object.';
			}
		}
		$findings=[];
		$warnings=[];
		if($transcript===[]){
			$findings[]=['severity'=>'error', 'code'=>'missing_transcript', 'message'=>'Provide transcript as an object or transcript_json as a JSON object.'];
		}
		$workflow=(string)($transcript['workflow'] ?? '');
		if($expected_workflow!=='generic' && $workflow!=='' && $workflow!==$expected_workflow){
			$findings[]=['severity'=>'warning', 'code'=>'workflow_mismatch', 'message'=>'Transcript workflow does not match the expected workflow argument.'];
		}
		if($workflow==='' && $transcript!==[]){
			$findings[]=['severity'=>'warning', 'code'=>'missing_workflow', 'message'=>'Transcript should include a workflow label.'];
		}
		foreach(['transcript_id', 'created_at', 'client', 'server', 'steps', 'final_status'] as $field){
			if(!array_key_exists($field, $transcript)){
				$findings[]=['severity'=>'warning', 'code'=>'missing_'.$field, 'message'=>'Transcript is missing '.$field.'.'];
			}
		}
		$steps=is_array($transcript['steps'] ?? null) ? $transcript['steps'] : [];
		if($steps===[]){
			$findings[]=['severity'=>'error', 'code'=>'missing_steps', 'message'=>'Transcript should include at least one captured step.'];
		}
		$allowed_statuses=['passed', 'failed', 'partial', 'not_run'];
		$final_status=(string)($transcript['final_status'] ?? '');
		if($final_status!=='' && !in_array($final_status, $allowed_statuses, true)){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_final_status', 'message'=>'final_status should be one of passed, failed, partial, or not_run.'];
		}
		$tool_names=array_map(static fn(array $tool): string => (string)($tool['name'] ?? ''), $this->list_tools()['tools']);
		$unknown_tools=[];
		$missing_summaries=0;
		$missing_result_keys=0;
		foreach($steps as $index=>$step){
			if(!is_array($step)){
				$findings[]=['severity'=>'warning', 'code'=>'invalid_step', 'message'=>'Step '.($index+1).' is not an object.'];
				continue;
			}
			$request=is_array($step['request'] ?? null) ? $step['request'] : [];
			$response=is_array($step['response'] ?? null) ? $step['response'] : [];
			$method=(string)($request['method'] ?? '');
			$tool=(string)($request['tool'] ?? '');
			if($method==='tools/call' && $tool!=='' && !in_array($tool, $tool_names, true)){
				$unknown_tools[]=$tool;
			}
			if(trim((string)($response['content_summary'] ?? ''))===''){
				$missing_summaries++;
			}
			if(!array_key_exists('result_keys', $response)){
				$missing_result_keys++;
			}
		}
		if($unknown_tools!==[]){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_tools', 'message'=>'Transcript references tools that are not registered.', 'tools'=>array_values(array_unique($unknown_tools))];
		}
		if($missing_summaries>0){
			$findings[]=['severity'=>'warning', 'code'=>'missing_content_summaries', 'message'=>$missing_summaries.' transcript step(s) are missing response.content_summary.'];
		}
		if($missing_result_keys>0){
			$findings[]=['severity'=>'info', 'code'=>'missing_result_keys', 'message'=>$missing_result_keys.' transcript step(s) are missing response.result_keys.'];
		}
		$sensitive_key=$this->mcp_sensitive_assignment_key_pattern();
		$secret_patterns=[
			'secret_assignment'=>'/\b(?:'.$sensitive_key.')\b\s*(?:=>|:|=)\s*["\']?[^"\'\s\[\{]+/i',
			'bearer_token'=>'/Bearer\s+[A-Za-z0-9._~+\/=-]{12,}/i',
			'connection_string'=>'/\b(?:mysql|pgsql|postgres|redis|mongodb):\/\/[^"\s]+/i',
			'absolute_windows_path'=>'/[A-Za-z]:(?:\\\\|\/)[^"\n\r]+/',
			'signed_url_parameter'=>'/\b(?:X-Amz-Signature|X-Amz-Credential|X-Amz-Security-Token|AWSAccessKeyId|Signature|Expires|sig|signature|passkey|totp|access_token|id_token|refresh_token|plan|plan_id|planId|subscription_id|subscriptionId|entitlement_id|entitlementId)=([^\s&#"\'<>]+)/i',
			'scoped_identifier'=>'/\b(?:tenant|tenant_id|tenantId|product|product_id|productId|customer|customer_id|customerId|account|account_id|accountId)\b\s*(?::|=|=>)\s*["\']?[^\s<>"\'\[\{]+/i',
		];
		$audit_step_limit=50;
		if(count($steps)>$audit_step_limit){
			$findings[]=[
				'severity'=>'error',
				'code'=>'transcript_too_large_for_full_audit',
				'message'=>'Transcript has more steps than the audit hard cap; summarize or split the client-owned transcript before sharing.',
				'step_count'=>count($steps),
				'hard_cap'=>$audit_step_limit,
			];
		}
		$audit_payload=$transcript;
		if(isset($audit_payload['steps']) && is_array($audit_payload['steps'])){
			$audit_payload['steps']=array_slice($audit_payload['steps'], 0, $audit_step_limit);
		}
		$serialized=json_encode($audit_payload, JSON_UNESCAPED_SLASHES) ?: '';
		foreach($secret_patterns as $code=>$pattern){
			if(preg_match($pattern, $serialized)===1){
				$warnings[]=$code;
			}
		}
		if($warnings!==[]){
			$findings[]=['severity'=>'error', 'code'=>'redaction_risk', 'message'=>'Transcript contains secret-looking or machine-local content that should be redacted before sharing.', 'signals'=>array_values(array_unique($warnings))];
		}
		if($parse_error!==''){
			$findings[]=['severity'=>'error', 'code'=>'parse_error', 'message'=>$parse_error];
		}
		$error_count=count(array_filter($findings, static fn(array $finding): bool => ($finding['severity'] ?? '')==='error'));
		$warning_count=count(array_filter($findings, static fn(array $finding): bool => ($finding['severity'] ?? '')==='warning'));
		return [
			'audit_type'=>'dataphyre_mcp_workflow_transcript_audit',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>$workflow!=='' ? $workflow : $expected_workflow,
			'expected_workflow'=>$expected_workflow,
			'protocol'=>'2025-11-25',
			'passed'=>$error_count===0,
			'error_count'=>$error_count,
			'warning_count'=>$warning_count,
			'step_count'=>count($steps),
			'findings'=>$findings,
			'redaction_signals'=>array_values(array_unique($warnings)),
			'follow_up_tools'=>[
				'dataphyre_mcp_workflow_transcript_schema_export',
				'dataphyre_mcp_safety_boundary_report',
				'dataphyre_mcp_workflow_session_export',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_transcript_audit'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_transcript_audit'),
			'usage_notes'=>[
				'This audit inspects the provided transcript shape only; it does not execute, store, or replay MCP messages.',
				'Fix error findings before sharing transcript context with agents or committing fixtures.',
				'Use content summaries and result keys instead of full response bodies when possible.',
			],
		];
	}

	/**
	 * Summarizes transcript entries into a compact workflow narrative.
	 *
	 * @param array<string,mixed> $args Transcript entries and summary options.
	 * @return array Transcript summary payload.
	 */
	private function mcp_workflow_transcript_summary_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		$transcript=[];
		if(isset($args['transcript']) && is_array($args['transcript'])){
			$transcript=$args['transcript'];
		}
		elseif(trim((string)($args['transcript_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['transcript_json'], true);
			if(is_array($decoded)){
				$transcript=$decoded;
			}
		}
		$audit=$this->mcp_workflow_transcript_audit([
			'workflow'=>$workflow,
			'transcript'=>$transcript,
			'transcript_json'=>$args['transcript_json'] ?? '',
		]);
		$steps=is_array($transcript['steps'] ?? null) ? $transcript['steps'] : [];
		$step_summary_limit=$this->mcp_workflow_summary_step_limit($args);
		$step_summaries=[];
		$total_step_count=0;
		$completed_step_count=0;
		$failed_step_count=0;
		foreach($steps as $index=>$step){
			if(!is_array($step)){
				continue;
			}
			$request=is_array($step['request'] ?? null) ? $step['request'] : [];
			$response=is_array($step['response'] ?? null) ? $step['response'] : [];
			$total_step_count++;
			if(array_key_exists('ok', $response)){
				if((bool)$response['ok']){
					$completed_step_count++;
				}
				else{
					$failed_step_count++;
				}
			}
			if(count($step_summaries)>=$step_summary_limit){
				continue;
			}
			$step_summaries[]=[
				'order'=>(int)($step['order'] ?? ($index+1)),
				'method'=>(string)($request['method'] ?? ''),
				'tool'=>(string)($request['tool'] ?? ''),
				'ok'=>array_key_exists('ok', $response) ? (bool)$response['ok'] : null,
				'content_summary'=>$this->redact_sensitive_text(substr((string)($response['content_summary'] ?? ''), 0, 600)),
				'result_keys'=>array_values(array_slice(is_array($response['result_keys'] ?? null) ? $response['result_keys'] : [], 0, 20)),
				'redaction_count'=>count(is_array($step['redactions'] ?? null) ? $step['redactions'] : []),
			];
		}
		$unknown_step_count=max(0, $total_step_count-$completed_step_count-$failed_step_count);
		$omitted_step_count=max(0, $total_step_count-count($step_summaries));
		$step_window=$this->mcp_workflow_step_window($total_step_count, count($step_summaries), $step_summary_limit);
		return [
			'export_type'=>'dataphyre_mcp_workflow_transcript_summary_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($audit['workflow'] ?? $workflow),
			'protocol'=>'2025-11-25',
			'transcript_id'=>$this->mcp_safe_handoff_label($transcript['transcript_id'] ?? ''),
			'final_status'=>(string)($transcript['final_status'] ?? ''),
			'audit_passed'=>$audit['passed'] ?? false,
			'audit_error_count'=>$audit['error_count'] ?? 0,
			'audit_warning_count'=>$audit['warning_count'] ?? 0,
			'step_count'=>$total_step_count,
			'completed_step_count'=>$completed_step_count,
			'failed_step_count'=>$failed_step_count,
			'unknown_step_count'=>$unknown_step_count,
			'step_summary_count'=>count($step_summaries),
			'step_summary_limit'=>$step_summary_limit,
			'omitted_step_count'=>$omitted_step_count,
			'step_window'=>$step_window,
			'step_summaries'=>$step_summaries,
			'findings'=>$audit['findings'] ?? [],
			'agent_handoff'=>[
				'status_line'=>'Workflow '.((string)($audit['workflow'] ?? $workflow)).' transcript '.(((bool)($audit['passed'] ?? false)) ? 'passed audit' : 'needs review').'.',
				'safe_to_share'=>($audit['passed'] ?? false)===true,
				'next_tools'=>($audit['passed'] ?? false)===true
					? $this->mcp_workflow_app_tools(array_merge(is_array($transcript['follow_up_tools'] ?? null) ? $transcript['follow_up_tools'] : [], ['dataphyre_mcp_workflow_readiness_audit']))
					: ['dataphyre_mcp_workflow_transcript_schema_export', 'dataphyre_mcp_safety_boundary_report'],
				'next_tool_boundaries'=>$this->mcp_workflow_tool_boundaries(($audit['passed'] ?? false)===true
					? $this->mcp_workflow_app_tools(array_merge(is_array($transcript['follow_up_tools'] ?? null) ? $transcript['follow_up_tools'] : [], ['dataphyre_mcp_workflow_readiness_audit']))
					: ['dataphyre_mcp_workflow_transcript_schema_export', 'dataphyre_mcp_safety_boundary_report']),
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_transcript_summary'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_transcript_summary'),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_transcript_summary'),
			'usage_notes'=>[
				'This summary is derived from client-provided transcript metadata; it does not replay or verify the original MCP responses.',
				'Share step summaries, result keys, and audit findings instead of full response bodies.',
				'If audit_passed is false, fix transcript redaction or shape issues before using the handoff with agents.',
				'Use publication_validation only for MCP/release-surface workflow claims.',
			],
		];
	}

	/**
	 * Exports a workflow checkpoint suitable for later resumption.
	 *
	 * @param array<string,mixed> $args Workflow state, transcript, and checkpoint options.
	 * @return array Workflow checkpoint payload.
	 */
	private function mcp_workflow_checkpoint_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		$transcript=[];
		if(isset($args['transcript']) && is_array($args['transcript'])){
			$transcript=$args['transcript'];
		}
		elseif(trim((string)($args['transcript_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['transcript_json'], true);
			if(is_array($decoded)){
				$transcript=$decoded;
			}
		}
		$summary=$this->mcp_workflow_transcript_summary_export([
			'workflow'=>$workflow,
			'transcript'=>$transcript,
			'transcript_json'=>$args['transcript_json'] ?? '',
			'max_summary_steps'=>$args['max_summary_steps'] ?? null,
		]);
		$steps=is_array($summary['step_summaries'] ?? null) ? $summary['step_summaries'] : [];
		$total_steps=(int)($summary['step_count'] ?? count($steps));
		$completed=(int)($summary['completed_step_count'] ?? count(array_filter($steps, static fn(array $step): bool => ($step['ok'] ?? null)===true)));
		$failed=(int)($summary['failed_step_count'] ?? count(array_filter($steps, static fn(array $step): bool => ($step['ok'] ?? null)===false)));
		$unknown=(int)($summary['unknown_step_count'] ?? max(0, $total_steps-$completed-$failed));
		$final_status=(string)($summary['final_status'] ?? '');
		$checkpoint_status=($summary['audit_passed'] ?? false)===true && $failed===0 ? 'healthy' : 'needs_review';
		if($total_steps===0){
			$checkpoint_status='empty';
		}
		elseif($final_status==='failed' || $failed>0){
			$checkpoint_status='blocked';
		}
		return [
			'export_type'=>'dataphyre_mcp_workflow_checkpoint_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($summary['workflow'] ?? $workflow),
			'protocol'=>'2025-11-25',
			'task'=>$this->mcp_safe_handoff_label(trim((string)($args['task'] ?? '')), 500),
			'transcript_id'=>$this->mcp_safe_handoff_label($summary['transcript_id'] ?? ''),
			'final_status'=>$final_status,
			'checkpoint_status'=>$checkpoint_status,
			'safe_to_share'=>($summary['agent_handoff']['safe_to_share'] ?? false)===true,
			'audit'=>[
				'passed'=>$summary['audit_passed'] ?? false,
				'error_count'=>$summary['audit_error_count'] ?? 0,
				'warning_count'=>$summary['audit_warning_count'] ?? 0,
				'findings'=>$summary['findings'] ?? [],
			],
			'progress'=>[
				'total_steps'=>$total_steps,
				'completed_steps'=>$completed,
				'failed_steps'=>$failed,
				'unknown_steps'=>$unknown,
				'returned_step_checkpoints'=>count($steps),
				'step_checkpoint_limit'=>(int)($summary['step_summary_limit'] ?? count($steps)),
				'omitted_step_count'=>(int)($summary['omitted_step_count'] ?? 0),
				'step_window'=>$summary['step_window'] ?? [],
			],
			'step_checkpoints'=>array_values(array_map(static fn(array $step): array => [
				'order'=>$step['order'] ?? 0,
				'method'=>$step['method'] ?? '',
				'tool'=>$step['tool'] ?? '',
				'ok'=>$step['ok'] ?? null,
				'result_keys'=>$step['result_keys'] ?? [],
				'redaction_count'=>$step['redaction_count'] ?? 0,
			], $steps)),
			'next_tools'=>$summary['agent_handoff']['next_tools'] ?? [],
			'next_tool_boundaries'=>$this->mcp_workflow_tool_boundaries(is_array($summary['agent_handoff']['next_tools'] ?? null) ? $summary['agent_handoff']['next_tools'] : []),
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_checkpoint'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_checkpoint'),
			'tool_audience_boundaries'=>$this->mcp_current_tool_audience_boundaries(),
			'continuity_policy'=>$this->mcp_workflow_continuity_policy('workflow_checkpoint'),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_checkpoint'),
			'recommended_next_actions'=>$checkpoint_status==='healthy'
				? ['Share this checkpoint with the next agent instead of raw transcript bodies.', 'Use focused application or module verification for app workflow results; use publication validation only for MCP/release-surface claims.']
				: ['Fix transcript audit findings before sharing.', 'Use dataphyre_mcp_workflow_transcript_schema_export to rebuild the capture shape.', 'Use dataphyre_mcp_safety_boundary_report before exposing diagnostic details.'],
			'usage_notes'=>[
				'This checkpoint summarizes client-provided transcript metadata only; it does not execute or replay MCP messages.',
				'Use checkpoint progress for human or agent handoff, and keep raw response bodies out of shared context.',
				'When checkpoint_status is blocked or needs_review, prefer audit findings over guessing from incomplete transcript data.',
			],
		];
	}

	/**
	 * Returns the transcript summary window size requested by the caller.
	 *
	 * @param array<string,mixed> $args Tool arguments.
	 * @return int Window size, default 20 and hard capped at 50.
	 */
	private function mcp_workflow_summary_step_limit(array $args): int {
		$limit=(int)($args['max_summary_steps'] ?? 20);
		if($limit<1){
			$limit=20;
		}
		return min($limit, 50);
	}

	/**
	 * Builds deterministic transcript step-window metadata.
	 *
	 * @param int $total_steps Total valid transcript steps.
	 * @param int $returned_steps Returned step summaries/checkpoints.
	 * @param int $limit Active summary limit.
	 * @return array<string,mixed> Step window metadata.
	 */
	private function mcp_workflow_step_window(int $total_steps, int $returned_steps, int $limit): array {
		$omitted=max(0, $total_steps-$returned_steps);
		return [
			'policy'=>'first_n_preserve_order',
			'limit'=>$limit,
			'hard_cap'=>50,
			'total_steps'=>$total_steps,
			'returned_steps'=>$returned_steps,
			'omitted_steps'=>$omitted,
			'truncated'=>$omitted>0,
		];
	}

	/**
	 * Builds a handoff pack for transferring workflow context to another agent or client.
	 *
	 * @param array<string,mixed> $args Workflow state, transcript, and handoff options.
	 * @return array Workflow handoff pack payload.
	 */
	private function mcp_workflow_handoff_pack_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'client')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release'], true)){
			$workflow='client';
		}
		$include_frames=($args['include_frames'] ?? true)!==false;
		$playbook=$this->mcp_workflow_playbook_export(['workflow'=>$workflow]);
		$readiness=$this->mcp_workflow_readiness_audit(['workflow'=>$workflow]);
		$session=$this->mcp_workflow_session_export(['workflow'=>$workflow, 'include_frames'=>$include_frames]);
		$schema=$this->mcp_workflow_transcript_schema_export(['workflow'=>$workflow]);
		return [
			'export_type'=>'dataphyre_mcp_workflow_handoff_pack_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>$workflow,
			'protocol'=>'2025-11-25',
			'transport'=>'stdio',
			'ready_to_run'=>($readiness['all_ready'] ?? false)===true,
			'include_frames'=>$include_frames,
			'playbook'=>$playbook,
			'readiness'=>$readiness,
			'session'=>$session,
			'transcript_schema'=>[
				'workflow'=>$schema['workflow'] ?? $workflow,
				'schema'=>$schema['schema'] ?? [],
				'required_redactions'=>$schema['required_redactions'] ?? [],
				'step_summary_rules'=>$schema['step_summary_rules'] ?? [],
			],
			'pre_run_checklist'=>[
				'Confirm ready_to_run is true before sending workflow messages.',
				'Send session_messages in order to the stdio server; do not send this pack itself as an MCP frame.',
				'Replace placeholder arguments with earlier step outputs before dependent calls.',
				'Capture responses using transcript_schema, then audit and summarize with transcript tools.',
			],
			'post_run_tools'=>[
				'dataphyre_mcp_workflow_transcript_audit',
				'dataphyre_mcp_workflow_transcript_summary_export',
				'dataphyre_mcp_safety_boundary_report',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_handoff_pack'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_handoff_pack'),
			'tool_audience_boundaries'=>$this->mcp_current_tool_audience_boundaries(),
			'continuity_policy'=>$this->mcp_workflow_continuity_policy('workflow_handoff_pack'),
			'usage_notes'=>[
				'This handoff pack is pre-run guidance only; it does not execute or store workflow messages.',
				'The pack is generic and should not be edited to include product-local paths in shared docs or fixtures.',
				'Use focused application or module verification for app workflow results; use dataphyre_mcp_verify_all only for MCP/release-surface workflow claims.',
			],
		];
	}


}
