<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Dataphyre
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

/**
 * Defines MCP workflow state, transition, sync, timeline, and resume surfaces.
 */
trait dataphyre_mcp_client_workflow_state_surfaces {

	/**
	 * Exports the schema for persisted workflow state records.
	 *
	 * @param array{workflow?:'feature'|'routes'|'sql'|'diagnostics'|'client'|'release'|'generic'|string} $args Schema export options.
	 * @return array Workflow state schema payload.
	 */
	private function mcp_workflow_state_schema_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_schema_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>$workflow,
			'protocol'=>'2025-11-25',
			'purpose'=>'Describe a client-owned state envelope for carrying Dataphyre MCP workflow progress across agent turns without server persistence.',
			'schema'=>[
				'state_id'=>'string stable client-generated id',
				'workflow'=>'feature|routes|sql|diagnostics|client|release|generic',
				'task'=>'short redacted task text',
				'created_at'=>'ISO-8601 timestamp generated by the client',
				'updated_at'=>'ISO-8601 timestamp generated by the client',
				'client'=>['name'=>'string', 'version'=>'string', 'transport'=>'stdio'],
				'selected_workflow'=>['name'=>'string', 'score'=>'integer', 'ready'=>'boolean'],
				'current_phase'=>'start|choose_workflow|pre_run_handoff|client_run|capture|audit|checkpoint|handoff_summary|verify|done',
				'last_decision'=>'start_workflow|review_transcript|fix_blocked_transcript|summarize_or_verify|done',
				'last_tool'=>'last MCP tool name suggested or called by the client',
				'transcript_ref'=>'client-local transcript id or empty string',
				'checkpoint_ref'=>'client-local checkpoint id or empty string',
				'checkpoint_status'=>'empty|healthy|needs_review|blocked|unknown',
				'pending_tools'=>'array of MCP tool names the client expects to call next',
				'completed_tools'=>'array of MCP tool names already summarized by the client',
				'findings'=>'array of redacted audit/checkpoint findings',
				'notes'=>'array of short redacted client notes',
			],
			'allowed_phases'=>['start', 'choose_workflow', 'pre_run_handoff', 'client_run', 'capture', 'audit', 'checkpoint', 'handoff_summary', 'verify', 'done'],
			'allowed_decisions'=>['start_workflow', 'review_transcript', 'fix_blocked_transcript', 'summarize_or_verify', 'done'],
			'required_redactions'=>[
				'Do not store secrets, credentials, cookies, private keys, Authorization headers, or connection strings in workflow state.',
				'Use client-local ids or relative references instead of product-local absolute paths.',
				'Store summaries, result keys, and checkpoint ids rather than raw MCP response bodies.',
			],
			'recommended_tools'=>[
				'start'=>'dataphyre_mcp_task_start_pack_export',
				'lifecycle'=>'dataphyre_mcp_workflow_lifecycle_export',
				'next_action'=>'dataphyre_mcp_workflow_next_action_export',
				'checkpoint'=>'dataphyre_mcp_workflow_checkpoint_export',
				'summary'=>'dataphyre_mcp_workflow_transcript_summary_export',
				'verify'=>'focused_application_or_module_verification',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_schema'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_schema'),
			'tool_audience_boundaries'=>$this->mcp_current_tool_audience_boundaries(),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_state_schema'),
			'example_state'=>[
				'state_id'=>'client-state-id',
				'workflow'=>$workflow,
				'task'=>'redacted task text',
				'created_at'=>'2026-01-01T00:00:00Z',
				'updated_at'=>'2026-01-01T00:05:00Z',
				'client'=>['name'=>'example-client', 'version'=>'1.0.0', 'transport'=>'stdio'],
				'selected_workflow'=>['name'=>$workflow, 'score'=>1, 'ready'=>true],
				'current_phase'=>'checkpoint',
				'last_decision'=>'summarize_or_verify',
				'last_tool'=>'dataphyre_mcp_workflow_checkpoint_export',
				'transcript_ref'=>'client-transcript-id',
				'checkpoint_ref'=>'client-checkpoint-id',
				'checkpoint_status'=>'healthy',
				'pending_tools'=>['dataphyre_mcp_workflow_transcript_summary_export'],
				'completed_tools'=>['dataphyre_mcp_task_start_pack_export', 'dataphyre_mcp_workflow_handoff_pack_export'],
				'findings'=>[],
				'notes'=>['State is client-owned and safe to share after redaction review.'],
			],
			'usage_notes'=>[
				'This schema is for client-owned state only; Dataphyre MCP does not persist workflow state.',
				'Keep state compact enough to pass between agent turns without raw transcripts.',
				'Use dataphyre_mcp_workflow_next_action_export to choose the next state transition.',
				'Use focused application/module verification for application behavior; use publication_validation only for MCP/release-surface claims.',
			],
		];
	}

	/**
	 * Audits a workflow state payload for structure, phase, and handoff risks.
	 *
	 * @param array<string,mixed> $args Workflow state and audit options.
	 * @return array Workflow state audit payload.
	 */
	private function mcp_workflow_state_audit(array $args): array {
		$expected_workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($expected_workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$expected_workflow='generic';
		}
		$state=[];
		$parse_error='';
		if(isset($args['state']) && is_array($args['state'])){
			$state=$args['state'];
		}
		elseif(trim((string)($args['state_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['state_json'], true);
			if(is_array($decoded)){
				$state=$decoded;
			}
			else{
				$parse_error='state_json could not be decoded as an object.';
			}
		}
		$findings=[];
		$warnings=[];
		if($state===[]){
			$findings[]=['severity'=>'error', 'code'=>'missing_state', 'message'=>'Provide state as an object or state_json as a JSON object.'];
		}
		$workflow=(string)($state['workflow'] ?? '');
		if($expected_workflow!=='generic' && $workflow!=='' && $workflow!==$expected_workflow){
			$findings[]=['severity'=>'warning', 'code'=>'workflow_mismatch', 'message'=>'Workflow state does not match the expected workflow argument.'];
		}
		if($workflow==='' && $state!==[]){
			$findings[]=['severity'=>'warning', 'code'=>'missing_workflow', 'message'=>'Workflow state should include a workflow label.'];
		}
		foreach(['state_id', 'workflow', 'task', 'created_at', 'updated_at', 'client', 'current_phase', 'last_decision', 'pending_tools', 'completed_tools'] as $field){
			if(!array_key_exists($field, $state)){
				$findings[]=['severity'=>'warning', 'code'=>'missing_'.$field, 'message'=>'Workflow state is missing '.$field.'.'];
			}
		}
		$allowed_phases=['start', 'choose_workflow', 'pre_run_handoff', 'client_run', 'capture', 'audit', 'checkpoint', 'handoff_summary', 'verify', 'done'];
		$current_phase=(string)($state['current_phase'] ?? '');
		if($current_phase!=='' && !in_array($current_phase, $allowed_phases, true)){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_current_phase', 'message'=>'current_phase should be one of the exported state schema phases.'];
		}
		$allowed_decisions=['start_workflow', 'review_transcript', 'fix_blocked_transcript', 'summarize_or_verify', 'done'];
		$last_decision=(string)($state['last_decision'] ?? '');
		if($last_decision!=='' && !in_array($last_decision, $allowed_decisions, true)){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_last_decision', 'message'=>'last_decision should be one of the exported state schema decisions.'];
		}
		$allowed_checkpoint_statuses=['', 'empty', 'healthy', 'needs_review', 'blocked', 'unknown'];
		$checkpoint_status=(string)($state['checkpoint_status'] ?? '');
		if(!in_array($checkpoint_status, $allowed_checkpoint_statuses, true)){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_checkpoint_status', 'message'=>'checkpoint_status should be empty, healthy, needs_review, blocked, or unknown.'];
		}
		$tool_names=array_map(static fn(array $tool): string => (string)($tool['name'] ?? ''), $this->list_tools()['tools']);
		$tool_refs=[];
		foreach(['last_tool', 'pending_tools', 'completed_tools'] as $field){
			$value=$state[$field] ?? null;
			if(is_string($value) && $value!==''){
				$tool_refs[]=$value;
			}
			elseif(is_array($value)){
				foreach($value as $tool){
					if(is_string($tool) && $tool!==''){
						$tool_refs[]=$tool;
					}
				}
			}
			elseif(array_key_exists($field, $state) && $value!==null){
				$findings[]=['severity'=>'warning', 'code'=>'invalid_'.$field, 'message'=>$field.' should be a string or array of tool names.'];
			}
		}
		$unknown_tools=array_values(array_unique(array_filter($tool_refs, static fn(string $tool): bool => !in_array($tool, $tool_names, true))));
		if($unknown_tools!==[]){
			$findings[]=['severity'=>'warning', 'code'=>'unknown_tools', 'message'=>'Workflow state references tools that are not registered.', 'tools'=>$unknown_tools];
		}
		foreach(['pending_tools', 'completed_tools', 'findings', 'notes'] as $field){
			if(array_key_exists($field, $state) && !is_array($state[$field])){
				$findings[]=['severity'=>'warning', 'code'=>'invalid_'.$field, 'message'=>$field.' should be an array.'];
			}
		}
		$serialized=json_encode($state, JSON_UNESCAPED_SLASHES) ?: '';
		$sensitive_key=$this->mcp_sensitive_assignment_key_pattern();
		$secret_patterns=[
			'secret_assignment'=>'/\b(?:'.$sensitive_key.')\b\s*(?:=>|:|=)\s*["\']?[^"\'\s\[\{]+/i',
			'bearer_token'=>'/Bearer\s+[A-Za-z0-9._~+\/=-]{12,}/i',
			'connection_string'=>'/\b(?:mysql|pgsql|postgres|redis|mongodb):\/\/[^"\s]+/i',
			'absolute_windows_path'=>'/[A-Za-z]:(?:\\\\|\/)[^"\n\r]+/',
			'signed_url_parameter'=>'/\b(?:X-Amz-Signature|X-Amz-Credential|X-Amz-Security-Token|AWSAccessKeyId|Signature|Expires|sig|signature|passkey|totp|access_token|id_token|refresh_token)=([^\s&#"\'<>]+)/i',
			'scoped_identifier'=>'/\b(?:tenant|tenant_id|tenantId|product|product_id|productId|customer|customer_id|customerId|account|account_id|accountId)\b\s*(?::|=|=>)\s*["\']?[^\s<>"\'\[\{]+/i',
		];
		foreach($secret_patterns as $code=>$pattern){
			if(preg_match($pattern, $serialized)===1){
				$warnings[]=$code;
			}
		}
		if($warnings!==[]){
			$findings[]=['severity'=>'error', 'code'=>'redaction_risk', 'message'=>'Workflow state contains secret-looking or machine-local content that should be redacted before sharing.', 'signals'=>array_values(array_unique($warnings))];
		}
		if($parse_error!==''){
			$findings[]=['severity'=>'error', 'code'=>'parse_error', 'message'=>$parse_error];
		}
		$error_count=count(array_filter($findings, static fn(array $finding): bool => ($finding['severity'] ?? '')==='error'));
		$warning_count=count(array_filter($findings, static fn(array $finding): bool => ($finding['severity'] ?? '')==='warning'));
		return [
			'audit_type'=>'dataphyre_mcp_workflow_state_audit',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>$workflow!=='' ? $workflow : $expected_workflow,
			'expected_workflow'=>$expected_workflow,
			'protocol'=>'2025-11-25',
			'passed'=>$error_count===0,
			'error_count'=>$error_count,
			'warning_count'=>$warning_count,
			'state_id'=>$this->mcp_safe_handoff_label($state['state_id'] ?? ''),
			'current_phase'=>$current_phase,
			'last_decision'=>$last_decision,
			'pending_tool_count'=>count(is_array($state['pending_tools'] ?? null) ? $state['pending_tools'] : []),
			'completed_tool_count'=>count(is_array($state['completed_tools'] ?? null) ? $state['completed_tools'] : []),
			'findings'=>$findings,
			'redaction_signals'=>array_values(array_unique($warnings)),
			'follow_up_tools'=>[
				'dataphyre_mcp_workflow_state_schema_export',
				'dataphyre_mcp_workflow_next_action_export',
				'dataphyre_mcp_safety_boundary_report',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_audit'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_audit'),
			'usage_notes'=>[
				'This audit inspects the provided client-owned state shape only; it does not persist, mutate, or resume state.',
				'Fix error findings before sharing workflow state across agents or storing it in fixtures.',
				'Use checkpoint and transcript references rather than raw response bodies or machine-local paths.',
			],
		];
	}

	/**
	 * Builds a compact summary from a workflow state payload.
	 *
	 * @param array<string,mixed> $args Workflow state and summary options.
	 * @return array Workflow state summary payload.
	 */
	private function mcp_workflow_state_summary_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		$state=[];
		if(isset($args['state']) && is_array($args['state'])){
			$state=$args['state'];
		}
		elseif(trim((string)($args['state_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['state_json'], true);
			if(is_array($decoded)){
				$state=$decoded;
			}
		}
		$audit=$this->mcp_workflow_state_audit([
			'workflow'=>$workflow,
			'state'=>$state,
			'state_json'=>$args['state_json'] ?? '',
		]);
		$pending_tools=array_values(array_slice($this->mcp_workflow_app_tools(is_array($state['pending_tools'] ?? null) ? $state['pending_tools'] : []), 0, 12));
		$completed_tools=array_values(array_slice(is_array($state['completed_tools'] ?? null) ? $state['completed_tools'] : [], 0, 12));
		$notes=[];
		foreach(array_slice(is_array($state['notes'] ?? null) ? $state['notes'] : [], 0, 6) as $note){
			$notes[]=$this->redact_sensitive_text(substr((string)$note, 0, 300));
		}
		$findings=[];
		foreach(array_slice(is_array($state['findings'] ?? null) ? $state['findings'] : [], 0, 8) as $finding){
			$findings[]=$this->redact_sensitive_text(substr(is_array($finding) ? json_encode($finding, JSON_UNESCAPED_SLASHES) : (string)$finding, 0, 500));
		}
		$audit_passed=($audit['passed'] ?? false)===true;
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_summary_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($audit['workflow'] ?? $workflow),
			'protocol'=>'2025-11-25',
			'state_id'=>$this->mcp_safe_handoff_label($state['state_id'] ?? ''),
			'task_summary'=>$this->mcp_safe_handoff_label($state['task'] ?? '', 500),
			'current_phase'=>(string)($audit['current_phase'] ?? ''),
			'last_decision'=>(string)($audit['last_decision'] ?? ''),
			'checkpoint_status'=>(string)($state['checkpoint_status'] ?? ''),
			'transcript_ref'=>$this->mcp_safe_handoff_label($state['transcript_ref'] ?? ''),
			'checkpoint_ref'=>$this->mcp_safe_handoff_label($state['checkpoint_ref'] ?? ''),
			'audit_passed'=>$audit_passed,
			'audit_error_count'=>(int)($audit['error_count'] ?? 0),
			'audit_warning_count'=>(int)($audit['warning_count'] ?? 0),
			'pending_tools'=>$pending_tools,
			'completed_tools'=>$completed_tools,
			'pending_tool_count'=>count($pending_tools),
			'completed_tool_count'=>count(is_array($state['completed_tools'] ?? null) ? $state['completed_tools'] : []),
			'state_findings'=>$findings,
			'notes'=>$notes,
			'audit_findings'=>$audit['findings'] ?? [],
			'agent_handoff'=>[
				'status_line'=>'Workflow '.((string)($audit['workflow'] ?? $workflow)).' state '.($audit_passed ? 'passed audit' : 'needs review').'.',
				'safe_to_share'=>$audit_passed,
				'next_tools'=>$audit_passed
					? $this->mcp_workflow_app_tools(array_merge($pending_tools, ['dataphyre_mcp_workflow_next_action_export']))
					: ['dataphyre_mcp_workflow_state_audit', 'dataphyre_mcp_workflow_state_schema_export', 'dataphyre_mcp_safety_boundary_report'],
				'next_tool_boundaries'=>$this->mcp_workflow_tool_boundaries($audit_passed
					? $this->mcp_workflow_app_tools(array_merge($pending_tools, ['dataphyre_mcp_workflow_next_action_export']))
					: ['dataphyre_mcp_workflow_state_audit', 'dataphyre_mcp_workflow_state_schema_export', 'dataphyre_mcp_safety_boundary_report']),
				'copy_safe_resume'=>[
					'status'=>'copy_safe_resume_ready',
					'fields'=>['workflow', 'state_id', 'task_summary', 'current_phase', 'last_decision', 'checkpoint_status', 'pending_tools', 'completed_tools', 'state_findings', 'notes', 'next_tools'],
					'use'=>'Copy these summary fields for agent handoff; keep raw workflow state and transcripts client-owned.',
					'not_included'=>['raw state JSON', 'raw transcript bodies', 'raw response bodies', 'secrets', 'tenant/customer identifiers', 'machine-local absolute paths'],
				],
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_summary'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_summary'),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_state_summary'),
			'usage_notes'=>[
				'This summary is derived from client-provided workflow state; it does not persist, mutate, or resume server state.',
				'Share this summary instead of raw state when handing progress to another agent.',
				'If audit_passed is false, fix state shape or redaction issues before using the handoff.',
				'Use publication_validation only for MCP/release-surface workflow claims.',
			],
		];
	}

	/**
	 * Describes a workflow state transition between lifecycle phases.
	 *
	 * @param array<string,mixed> $args Current state and requested transition.
	 * @return array Workflow transition payload.
	 */
	private function mcp_workflow_state_transition_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		$state=[];
		if(isset($args['state']) && is_array($args['state'])){
			$state=$args['state'];
		}
		elseif(trim((string)($args['state_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['state_json'], true);
			if(is_array($decoded)){
				$state=$decoded;
			}
		}
		$summary=$this->mcp_workflow_state_summary_export([
			'workflow'=>$workflow,
			'state'=>$state,
			'state_json'=>$args['state_json'] ?? '',
		]);
		$next=$this->mcp_workflow_next_action_export([
			'task'=>$args['task'] ?? ($state['task'] ?? ''),
			'workflow'=>$workflow,
			'state'=>$state,
			'state_json'=>$args['state_json'] ?? '',
		]);
		$decision=(string)($next['decision'] ?? 'start_workflow');
		$recommended_tool=(string)($next['recommended_tool'] ?? 'dataphyre_mcp_task_start_pack_export');
		$phase_map=[
			'start_workflow'=>'pre_run_handoff',
			'review_transcript'=>'audit',
			'fix_blocked_transcript'=>'audit',
			'summarize_or_verify'=>'verify',
			'done'=>'done',
		];
		$next_phase=$phase_map[$decision] ?? 'choose_workflow';
		if($recommended_tool==='dataphyre_mcp_workflow_state_summary_export'){
			$next_phase='handoff_summary';
		}
		$current_pending=$this->mcp_workflow_app_tools(is_array($state['pending_tools'] ?? null) ? $state['pending_tools'] : []);
		$current_completed=is_array($state['completed_tools'] ?? null) ? $state['completed_tools'] : [];
		$last_tool=(string)($state['last_tool'] ?? '');
		if($last_tool!=='' && !in_array($last_tool, $current_completed, true)){
			$current_completed[]=$last_tool;
		}
		$pending_tools=$this->mcp_workflow_app_tools(array_merge([$recommended_tool], $current_pending));
		$completed_tools=array_values(array_unique(array_filter($current_completed, static fn(string $tool): bool => $tool!=='')));
		$patch=[
			'workflow'=>(string)($summary['workflow'] ?? $workflow),
			'current_phase'=>$next_phase,
			'last_decision'=>$decision,
			'last_tool'=>$recommended_tool,
			'pending_tools'=>array_values(array_slice($pending_tools, 0, 12)),
			'completed_tools'=>array_values(array_slice($completed_tools, 0, 12)),
			'checkpoint_status'=>(string)($summary['checkpoint_status'] ?? ($state['checkpoint_status'] ?? 'unknown')),
		];
		if(trim((string)($state['task'] ?? ''))==='' && trim((string)($args['task'] ?? ''))!==''){
			$patch['task']=$this->redact_sensitive_text(substr((string)$args['task'], 0, 500));
		}
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_transition_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($summary['workflow'] ?? $workflow),
			'protocol'=>'2025-11-25',
			'state_id'=>$this->mcp_safe_handoff_label($state['state_id'] ?? ''),
			'audit_passed'=>($summary['audit_passed'] ?? false)===true,
			'current_phase'=>(string)($summary['current_phase'] ?? ''),
			'next_phase'=>$next_phase,
			'decision'=>$decision,
			'recommended_tool'=>$recommended_tool,
			'suggested_patch'=>$patch,
			'next_action'=>$next,
			'summary'=>[
				'task_summary'=>$summary['task_summary'] ?? '',
				'checkpoint_status'=>$summary['checkpoint_status'] ?? '',
				'pending_tool_count'=>$summary['pending_tool_count'] ?? 0,
				'completed_tool_count'=>$summary['completed_tool_count'] ?? 0,
				'audit_error_count'=>$summary['audit_error_count'] ?? 0,
				'audit_warning_count'=>$summary['audit_warning_count'] ?? 0,
			],
			'apply_policy'=>[
				'This is a suggested client-side patch only; the MCP server does not store or mutate workflow state.',
				'Clients should merge suggested_patch into their own state after reviewing audit_passed and audit findings.',
				'Clients should set updated_at themselves with their own clock and should not store secrets or raw response bodies.',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_transition'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_transition'),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_state_transition'),
			'follow_up_tools'=>[
				$recommended_tool,
				'dataphyre_mcp_workflow_state_transition_export',
				'dataphyre_mcp_workflow_state_audit',
				'dataphyre_mcp_workflow_state_summary_export',
			],
		];
	}

	/**
	 * Exports a synchronization pack for sharing workflow state across clients.
	 *
	 * @param array<string,mixed> $args Workflow state and synchronization options.
	 * @return array Workflow state sync pack payload.
	 */
	private function mcp_workflow_state_sync_pack_export(array $args): array {
		$workflow=strtolower(trim((string)($args['workflow'] ?? 'generic')));
		if(!in_array($workflow, ['feature', 'routes', 'sql', 'diagnostics', 'client', 'release', 'generic'], true)){
			$workflow='generic';
		}
		$state=[];
		if(isset($args['state']) && is_array($args['state'])){
			$state=$args['state'];
		}
		elseif(trim((string)($args['state_json'] ?? ''))!==''){
			$decoded=json_decode((string)$args['state_json'], true);
			if(is_array($decoded)){
				$state=$decoded;
			}
		}
		$base_args=[
			'workflow'=>$workflow,
			'state'=>$state,
			'state_json'=>$args['state_json'] ?? '',
			'task'=>$args['task'] ?? ($state['task'] ?? ''),
		];
		$schema=$this->mcp_workflow_state_schema_export(['workflow'=>$workflow]);
		$audit=$this->mcp_workflow_state_audit($base_args);
		$summary=$this->mcp_workflow_state_summary_export($base_args);
		$transition=$this->mcp_workflow_state_transition_export($base_args);
		$next=$this->mcp_workflow_next_action_export($base_args);
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_sync_pack_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($summary['workflow'] ?? $workflow),
			'protocol'=>'2025-11-25',
			'state_id'=>$this->mcp_safe_handoff_label($state['state_id'] ?? ''),
			'audit_passed'=>($audit['passed'] ?? false)===true,
			'current_phase'=>(string)($summary['current_phase'] ?? ''),
			'next_phase'=>(string)($transition['next_phase'] ?? ''),
			'decision'=>(string)($next['decision'] ?? ''),
			'recommended_tool'=>(string)($next['recommended_tool'] ?? ''),
			'schema'=>[
				'allowed_phases'=>$schema['allowed_phases'] ?? [],
				'allowed_decisions'=>$schema['allowed_decisions'] ?? [],
				'required_redactions'=>$schema['required_redactions'] ?? [],
				'recommended_tools'=>$schema['recommended_tools'] ?? [],
			],
			'audit'=>$audit,
			'summary'=>$summary,
			'transition'=>$transition,
			'next_action'=>$next,
			'client_apply_order'=>[
				'Review audit.passed and audit.findings.',
				'Use summary.agent_handoff for agent-to-agent context when audit_passed is true.',
				'Merge transition.suggested_patch into client-owned state only after review.',
				'Set updated_at with the client clock and keep raw responses out of state.',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_sync_pack'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_sync_pack'),
			'publication_validation'=>$this->mcp_publication_validation_contract('workflow_state_sync_pack'),
			'usage_notes'=>[
				'This sync pack is a read-only bundle; the MCP server does not persist, mutate, or resume workflow state.',
				'Use the pack when handing state across agents or client turns without sharing raw transcripts.',
				'If audit_passed is false, fix state shape or redaction issues before applying the suggested patch.',
				'Use publication_validation only for MCP/release-surface workflow claims.',
			],
		];
	}

	/**
	 * Converts workflow state history into a timeline payload.
	 *
	 * @param array<string,mixed> $args Workflow state and timeline options.
	 * @return array Workflow state timeline payload.
	 */
	private function mcp_workflow_state_timeline_export(array $args): array {
		$sync=$this->mcp_workflow_state_sync_pack_export($args);
		$allowed_phases=is_array($sync['schema']['allowed_phases'] ?? null) ? $sync['schema']['allowed_phases'] : [];
		$current_phase=(string)($sync['current_phase'] ?? '');
		$next_phase=(string)($sync['next_phase'] ?? '');
		$timeline=[];
		foreach($allowed_phases as $index=>$phase){
			$phase=(string)$phase;
			$status='pending';
			if($phase===$current_phase){
				$status='current';
			}
			elseif($phase===$next_phase){
				$status='next';
			}
			elseif($current_phase!=='' && array_search($phase, $allowed_phases, true)<array_search($current_phase, $allowed_phases, true)){
				$status='completed_or_skipped';
			}
			$timeline[]=[
				'order'=>$index+1,
				'phase'=>$phase,
				'status'=>$status,
				'tool'=>$this->mcp_workflow_phase_tool($phase),
			];
		}
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_timeline_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($sync['workflow'] ?? 'generic'),
			'protocol'=>'2025-11-25',
			'state_id'=>$this->mcp_safe_handoff_label($sync['state_id'] ?? ''),
			'audit_passed'=>($sync['audit_passed'] ?? false)===true,
			'current_phase'=>$current_phase,
			'next_phase'=>$next_phase,
			'decision'=>(string)($sync['decision'] ?? ''),
			'recommended_tool'=>(string)($sync['recommended_tool'] ?? ''),
			'timeline'=>$timeline,
			'current'=>[
				'phase'=>$current_phase,
				'checkpoint_status'=>$sync['summary']['checkpoint_status'] ?? '',
				'audit_error_count'=>$sync['summary']['audit_error_count'] ?? 0,
				'audit_warning_count'=>$sync['summary']['audit_warning_count'] ?? 0,
			],
			'next'=>[
				'phase'=>$next_phase,
				'tool'=>$sync['recommended_tool'] ?? '',
				'patch'=>$sync['transition']['suggested_patch'] ?? [],
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_timeline'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_timeline'),
			'usage_notes'=>[
				'This timeline is derived from client-owned state and sync-pack guidance; it does not persist or mutate state.',
				'Use current and next for quick agent continuity, and use the sync pack when the full audit or patch detail is needed.',
				'Completed_or_skipped phases are inferred from phase order, not from server-side history.',
			],
		];
	}

	/**
	 * Builds a resume brief from workflow state for handoff or continuation.
	 *
	 * @param array<string,mixed> $args Workflow state and resume options.
	 * @return array Resume brief payload.
	 */
	private function mcp_workflow_state_resume_brief_export(array $args): array {
		$timeline=$this->mcp_workflow_state_timeline_export($args);
		$sync=$this->mcp_workflow_state_sync_pack_export($args);
		$summary=is_array($sync['summary'] ?? null) ? $sync['summary'] : [];
		$transition=is_array($sync['transition'] ?? null) ? $sync['transition'] : [];
		$next_action=is_array($sync['next_action'] ?? null) ? $sync['next_action'] : [];
		$handoff=is_array($summary['agent_handoff'] ?? null) ? $summary['agent_handoff'] : [];
		return [
			'export_type'=>'dataphyre_mcp_workflow_state_resume_brief_export',
			'write_policy'=>'read_only',
			'execution'=>'not_executed',
			'workflow'=>(string)($sync['workflow'] ?? 'generic'),
			'protocol'=>'2025-11-25',
			'state_id'=>$this->mcp_safe_handoff_label($sync['state_id'] ?? ''),
			'audit_passed'=>($sync['audit_passed'] ?? false)===true,
			'status_line'=>(string)($handoff['status_line'] ?? ('Workflow '.((string)($sync['workflow'] ?? 'generic')).' state needs review.')),
			'task_summary'=>(string)($summary['task_summary'] ?? ''),
			'current'=>[
				'phase'=>$timeline['current_phase'] ?? '',
				'checkpoint_status'=>$timeline['current']['checkpoint_status'] ?? '',
				'audit_error_count'=>$timeline['current']['audit_error_count'] ?? 0,
				'audit_warning_count'=>$timeline['current']['audit_warning_count'] ?? 0,
			],
			'next'=>[
				'phase'=>$timeline['next_phase'] ?? '',
				'decision'=>$timeline['decision'] ?? '',
				'tool'=>$timeline['recommended_tool'] ?? '',
				'arguments'=>$next_action['recommended_arguments'] ?? [],
			],
			'progress'=>[
				'pending_tools'=>$summary['pending_tools'] ?? [],
				'completed_tools'=>$summary['completed_tools'] ?? [],
				'timeline'=>array_values(array_filter($timeline['timeline'] ?? [], static fn(array $entry): bool => in_array($entry['status'] ?? '', ['completed_or_skipped', 'current', 'next'], true))),
			],
			'copy_safe_resume'=>[
				'status'=>'copy_safe_resume_ready',
				'owner'=>'consuming_application',
				'fields'=>['status_line', 'task_summary', 'current', 'next.tool', 'next.arguments', 'progress.pending_tools', 'progress.completed_tools', 'client_patch'],
				'next_action'=>'Start with next.tool and next.arguments when audit_passed is true.',
				'not_included'=>['raw workflow state JSON', 'raw transcript bodies', 'raw response bodies', 'secrets', 'tenant/customer identifiers', 'machine-local absolute paths', 'Dataphyre hot-path benchmark output'],
				'use'=>'Paste this object or its fields into an agent handoff; keep full workflow state client-owned and fetchable only when needed.',
			],
			'client_patch'=>$transition['suggested_patch'] ?? [],
			'resume_instructions'=>[
				'Start with next.tool and next.arguments when audit_passed is true.',
				'If audit_passed is false, inspect dataphyre_mcp_workflow_state_audit before continuing.',
				'Apply client_patch only to client-owned state after review; the MCP server has not stored or applied it.',
				'Use focused application or module verification for app workflow results; use publication validation only for MCP/release-surface claims.',
			],
			'application_agent_operating_contract'=>$this->mcp_application_agent_operating_contract('workflow_state_resume_brief'),
			'ordinary_app_work'=>$this->mcp_ordinary_app_work_contract('workflow_state_resume_brief'),
			'tool_audience_boundaries'=>$this->mcp_current_tool_audience_boundaries(),
			'continuity_policy'=>$this->mcp_workflow_continuity_policy('workflow_state_resume_brief'),
			'links'=>[
				'sync_pack'=>'dataphyre_mcp_workflow_state_sync_pack_export',
				'timeline'=>'dataphyre_mcp_workflow_state_timeline_export',
				'audit'=>'dataphyre_mcp_workflow_state_audit',
				'next_action'=>'dataphyre_mcp_workflow_next_action_export',
			],
		];
	}

	/**
	 * Builds compact workflow-continuity guidance for resume and handoff payloads.
	 *
	 * @param string $surface MCP surface embedding the policy.
	 * @return array<string,mixed> Workflow continuity policy.
	 */
	private function mcp_workflow_continuity_policy(string $surface): array {
		return [
			'surface'=>$surface,
			'default'=>'resume_from_summary_not_raw_payloads',
			'state'=>'Use audited client-owned state, checkpoints, step summaries, result keys, and next.tool/next.arguments before opening full transcripts.',
			'copy_safe_resume'=>'Use copy_safe_resume.status=copy_safe_resume_ready for agent handoffs; share summary fields and next.tool/next.arguments instead of raw state or transcript bodies.',
			'app_work'=>'Continue ordinary app work through app-builder or focused inspection first; keep behavior in app-owned code, config, callbacks, dialbacks, plugins, MCP metadata, or application-owned adapters.',
			'diagnostics'=>'Share diagnostic_summary.copy_safe_evidence for Tracelog/error findings instead of raw logs or unredacted snippets.',
			'verification'=>'Use focused application or module verification for app behavior; reserve publication validation for MCP/release-surface claims.',
			'not_default'=>[
				'raw transcript bodies',
				'raw full logs',
				'dataphyre_mcp_verify_all',
				'Dataphyre project-wide release validation',
				'Dataphyre hot-path benchmarks',
				'Dataphyre runtime-internal edits to make one application work',
			],
			'details'=>[
				'agent_workload_policy'=>'dataphyre_mcp_readiness_report.agent_workload_policy',
				'diagnostic_handoff_policy'=>'dataphyre_mcp_readiness_report.diagnostic_handoff_policy',
				'tool_audience_boundaries'=>'dataphyre_mcp_readiness_report.tool_audience_boundaries',
			],
		];
	}

	/**
	 * Selects the most relevant MCP tool for a workflow phase.
	 *
	 * @param string $phase Workflow phase name.
	 * @return string MCP tool name.
	 */
	private function mcp_workflow_phase_tool(string $phase): string {
		return match($phase){
			'start'=>'dataphyre_mcp_task_start_pack_export',
			'choose_workflow'=>'dataphyre_mcp_workflow_recommend',
			'pre_run_handoff'=>'dataphyre_mcp_workflow_handoff_pack_export',
			'client_run'=>'dataphyre_mcp_workflow_session_export',
			'capture'=>'dataphyre_mcp_workflow_transcript_schema_export',
			'audit'=>'dataphyre_mcp_workflow_transcript_audit',
			'checkpoint'=>'dataphyre_mcp_workflow_checkpoint_export',
			'handoff_summary'=>'dataphyre_mcp_workflow_state_summary_export',
			'verify'=>'focused_application_or_module_verification',
			'done'=>'dataphyre_mcp_workflow_state_sync_pack_export',
			default=>'dataphyre_mcp_workflow_next_action_export',
		};
	}

}
