<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Signed append-only event in the fabric's tenant-aware hash chain. */
final class PanelEventEnvelope implements \JsonSerializable {
	private readonly string $digest;
	/** @param array<string,mixed> $payload @param array<string,mixed> $metadata */private function __construct(private readonly string $id,private readonly int $sequence,private readonly string $type,private readonly string $aggregateType,private readonly string $aggregateId,private readonly string $tenantId,private readonly string $actorId,private readonly string $commandFingerprint,private readonly ?string $correlationId,private readonly ?string $causationId,private readonly array $payload,private readonly array $metadata,private readonly string $occurredAt,private readonly string $previousHash,private readonly string $keyId,private readonly string $signature){PanelOperationsGuard::identifier($id,'fabric event id');if($sequence<1){throw new \InvalidArgumentException('Fabric event sequence is invalid.');}PanelOperationsGuard::name($type,'fabric event type',160);PanelOperationsGuard::name($aggregateType,'fabric aggregate type');PanelOperationsGuard::identifier($aggregateId,'fabric aggregate id');PanelOperationsGuard::identifier($tenantId,'fabric event tenant');PanelOperationsGuard::identifier($actorId,'fabric event actor');foreach([$commandFingerprint,$previousHash]as$digest){if(preg_match('/^[a-f0-9]{64}$/D',$digest)!==1){throw new \InvalidArgumentException('Fabric event hash is invalid.');}}foreach([$correlationId,$causationId]as$value){if($value!==null){PanelOperationsGuard::identifier($value,'fabric event relation id');}}PanelOperationsGuard::object($payload,'fabric event payload',4096);PanelOperationsGuard::canonical($payload);PanelOperationsGuard::safeMetadata($metadata,512);PanelOperationsGuard::name($keyId,'fabric event key id');if(preg_match('/^[a-f0-9]{64}$/D',$signature)!==1){throw new \InvalidArgumentException('Fabric event signature is invalid.');}$this->digest=PanelOperationsGuard::digest($this->unsigned());}
	public static function sign(int $sequence,PanelEventDraft $draft,PanelCommandEnvelope $command,string $previousHash,string|int|\DateTimeInterface $occurredAt,string $keyId,string $key):self {if(strlen($key)<32){throw new \InvalidArgumentException('Fabric event signing keys require at least 32 bytes.');}$at=PanelOperationsGuard::instant($occurredAt);$id='evt_'.substr(hash('sha256',$command->fingerprint().'|'.$sequence.'|'.$previousHash.'|'.$draft->type()),0,40);$prototype=new self($id,$sequence,$draft->type(),$draft->aggregateType(),$draft->aggregateId(),$command->tenantId(),$command->actorId(),$command->fingerprint(),$command->correlationId(),$command->causationId(),$draft->payload(),$draft->metadata(),$at,$previousHash,$keyId,str_repeat('0',64));return new self($id,$sequence,$draft->type(),$draft->aggregateType(),$draft->aggregateId(),$command->tenantId(),$command->actorId(),$command->fingerprint(),$command->correlationId(),$command->causationId(),$draft->payload(),$draft->metadata(),$at,$previousHash,$keyId,hash_hmac('sha256',$prototype->digest,$key));}
	/** @param array<string,mixed> $payload */public static function hydrate(array $payload):self {$required=['type','schema_version','api_version','version','id','sequence','event_type','aggregate_type','aggregate_id','tenant_id','actor_id','command_fingerprint','correlation_id','causation_id','payload','metadata','occurred_at','previous_hash','digest','key_id','signature'];$keys=array_keys($payload);sort($keys,SORT_STRING);sort($required,SORT_STRING);if($keys!==$required||($payload['type']??null)!=='panel_event_envelope'||($payload['version']??null)!==1||!is_string($payload['id']??null)||!is_int($payload['sequence']??null)||!is_string($payload['event_type']??null)||!is_string($payload['aggregate_type']??null)||!is_string($payload['aggregate_id']??null)||!is_string($payload['tenant_id']??null)||!is_string($payload['actor_id']??null)||!is_string($payload['command_fingerprint']??null)||(!is_string($payload['correlation_id'])&&$payload['correlation_id']!==null)||(!is_string($payload['causation_id'])&&$payload['causation_id']!==null)||!is_array($payload['payload']??null)||!is_array($payload['metadata']??null)||!is_string($payload['occurred_at']??null)||!is_string($payload['previous_hash']??null)||!is_string($payload['digest']??null)||!is_string($payload['key_id']??null)||!is_string($payload['signature']??null)){throw new \UnexpectedValueException('Stored fabric event shape is invalid.');}$self=new self($payload['id'],$payload['sequence'],$payload['event_type'],$payload['aggregate_type'],$payload['aggregate_id'],$payload['tenant_id'],$payload['actor_id'],$payload['command_fingerprint'],$payload['correlation_id'],$payload['causation_id'],$payload['payload'],$payload['metadata'],PanelOperationsGuard::instant($payload['occurred_at']),$payload['previous_hash'],$payload['key_id'],$payload['signature']);if(!hash_equals($self->digest,$payload['digest'])){throw new \UnexpectedValueException('Stored fabric event digest is invalid.');}return$self;}
	/** @param array<string,string> $keys */public function verify(array $keys):bool {$key=$keys[$this->keyId]??null;return is_string($key)&&strlen($key)>=32&&hash_equals($this->signature,hash_hmac('sha256',$this->digest,$key));}
	public function id():string{return$this->id;}public function sequence():int{return$this->sequence;}public function eventType():string{return$this->type;}public function aggregateType():string{return$this->aggregateType;}public function aggregateId():string{return$this->aggregateId;}public function tenantId():string{return$this->tenantId;}public function actorId():string{return$this->actorId;}public function commandFingerprint():string{return$this->commandFingerprint;}public function correlationId():?string{return$this->correlationId;}public function causationId():?string{return$this->causationId;}/** @return array<string,mixed> */public function payload():array{return$this->payload;}/** @return array<string,mixed> */public function metadata():array{return$this->metadata;}public function occurredAt():string{return$this->occurredAt;}public function previousHash():string{return$this->previousHash;}public function keyId():string{return$this->keyId;}public function digest():string{return$this->digest;}public function hash():string{return hash('sha256',$this->digest.$this->signature);}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_event_envelope','version'=>1]+$this->unsigned()+['digest'=>$this->digest,'key_id'=>$this->keyId,'signature'=>$this->signature]);}/** @return array<string,mixed> */private function unsigned():array{return['id'=>$this->id,'sequence'=>$this->sequence,'event_type'=>$this->type,'aggregate_type'=>$this->aggregateType,'aggregate_id'=>$this->aggregateId,'tenant_id'=>$this->tenantId,'actor_id'=>$this->actorId,'command_fingerprint'=>$this->commandFingerprint,'correlation_id'=>$this->correlationId,'causation_id'=>$this->causationId,'payload'=>$this->payload,'metadata'=>$this->metadata,'occurred_at'=>$this->occurredAt,'previous_hash'=>$this->previousHash];}
}
