<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);

namespace Dataphyre\Panel;

/** Signed command completion record with replay-safe public output. */
final class PanelCommandReceipt implements \JsonSerializable {
	private readonly string $digest;
	/** @param list<string> $eventIds @param array<string,mixed> $metadata */private function __construct(private readonly string $id,private readonly string $status,private readonly string $commandFingerprint,private readonly string $idempotencyHash,private readonly mixed $result,private readonly ?string $error,private readonly array $eventIds,private readonly array $metadata,private readonly string $completedAt,private readonly string $keyId,private readonly string $signature,private readonly bool $replay=false){PanelOperationsGuard::identifier($id,'command receipt id');if(!in_array($status,['succeeded','failed','denied'],true)){throw new \InvalidArgumentException('Command receipt status is invalid.');}foreach([$commandFingerprint,$idempotencyHash]as$digest){if(preg_match('/^[a-f0-9]{64}$/D',$digest)!==1){throw new \InvalidArgumentException('Command receipt fingerprint is invalid.');}}PanelOperationsGuard::identifiers($eventIds,'command receipt event id',128,4096);if($error!==null){PanelOperationsGuard::label($error,'command receipt error',2048);}PanelOperationsGuard::safeMetadata($metadata,512);PanelOperationsGuard::name($keyId,'command receipt key id');if(preg_match('/^[a-f0-9]{64}$/D',$signature)!==1){throw new \InvalidArgumentException('Command receipt signature is invalid.');}$this->digest=PanelOperationsGuard::digest($this->unsigned());}
	/** @param list<string> $eventIds @param array<string,mixed> $metadata */public static function sign(string $status,PanelCommandEnvelope $command,mixed $result,?string $error,array $eventIds,array $metadata,string|int|\DateTimeInterface $completedAt,string $keyId,string $key):self {if(strlen($key)<32){throw new \InvalidArgumentException('Command receipt signing keys require at least 32 bytes.');}$safe=PanelSensitiveDataSanitizer::sanitize($result,['max_depth'=>16,'max_items'=>1000,'max_string_bytes'=>65536]);$safeError=$error!==null?(string)PanelSensitiveDataSanitizer::sanitize($error,['max_depth'=>2,'max_items'=>4,'max_string_bytes'=>2048]):null;$id='cmd_'.substr($command->fingerprint(),0,40);$prototype=new self($id,$status,$command->fingerprint(),$command->idempotencyHash(),$safe,$safeError,$eventIds,PanelOperationsGuard::safeMetadata($metadata,512),PanelOperationsGuard::instant($completedAt),$keyId,str_repeat('0',64));return new self($id,$status,$command->fingerprint(),$command->idempotencyHash(),$safe,$safeError,$eventIds,$prototype->metadata,$prototype->completedAt,$keyId,hash_hmac('sha256',$prototype->digest,$key));}
	/** @param array<string,mixed> $payload */public static function hydrate(array $payload):self {$required=['type','schema_version','api_version','version','id','status','command_fingerprint','idempotency_hash','result','error','event_ids','metadata','completed_at','digest','key_id','signature','replay'];$keys=array_keys($payload);sort($keys,SORT_STRING);sort($required,SORT_STRING);if($keys!==$required||($payload['type']??null)!=='panel_command_receipt'||($payload['version']??null)!==1||!is_string($payload['id']??null)||!is_string($payload['status']??null)||!is_string($payload['command_fingerprint']??null)||!is_string($payload['idempotency_hash']??null)||(!is_string($payload['error'])&&$payload['error']!==null)||!is_array($payload['event_ids']??null)||!is_array($payload['metadata']??null)||!is_string($payload['completed_at']??null)||!is_string($payload['digest']??null)||!is_string($payload['key_id']??null)||!is_string($payload['signature']??null)||!is_bool($payload['replay']??null)){throw new \UnexpectedValueException('Stored command receipt shape is invalid.');}$self=new self($payload['id'],$payload['status'],$payload['command_fingerprint'],$payload['idempotency_hash'],$payload['result'],$payload['error'],$payload['event_ids'],$payload['metadata'],PanelOperationsGuard::instant($payload['completed_at']),$payload['key_id'],$payload['signature'],$payload['replay']);if(!hash_equals($self->digest,$payload['digest'])){throw new \UnexpectedValueException('Stored command receipt digest is invalid.');}return$self;}
	/** @param array<string,string> $keys */public function verify(array $keys):bool {$key=$keys[$this->keyId]??null;return is_string($key)&&strlen($key)>=32&&hash_equals($this->signature,hash_hmac('sha256',$this->digest,$key));}
	public function asReplay():self{return new self($this->id,$this->status,$this->commandFingerprint,$this->idempotencyHash,$this->result,$this->error,$this->eventIds,$this->metadata,$this->completedAt,$this->keyId,$this->signature,true);}public function id():string{return$this->id;}public function ok():bool{return$this->status==='succeeded';}public function status():string{return$this->status;}public function commandFingerprint():string{return$this->commandFingerprint;}public function idempotencyHash():string{return$this->idempotencyHash;}public function result():mixed{return$this->result;}public function error():?string{return$this->error;}/** @return list<string> */public function eventIds():array{return$this->eventIds;}/** @return array<string,mixed> */public function metadata():array{return$this->metadata;}public function completedAt():string{return$this->completedAt;}public function keyId():string{return$this->keyId;}public function replay():bool{return$this->replay;}public function digest():string{return$this->digest;}
	public function jsonSerialize():array{return PanelManifestContract::stamp(['type'=>'panel_command_receipt','version'=>1]+$this->unsigned()+['digest'=>$this->digest,'key_id'=>$this->keyId,'signature'=>$this->signature,'replay'=>$this->replay]);}/** @return array<string,mixed> */private function unsigned():array{return['id'=>$this->id,'status'=>$this->status,'command_fingerprint'=>$this->commandFingerprint,'idempotency_hash'=>$this->idempotencyHash,'result'=>$this->result,'error'=>$this->error,'event_ids'=>$this->eventIds,'metadata'=>$this->metadata,'completed_at'=>$this->completedAt];}
}
