<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Instance-owned, fail-safe telemetry lifecycle and correlation runtime. */
final class PanelTelemetryHub implements \JsonSerializable {
	/** @var list<PanelTelemetryContext> */ private array $scope=[]; /** @var array<string,int> */ private array $emitted=[]; private int $dropped=0; private int $exportFailures=0; private int $flushFailures=0; private int $activeSpans=0; private ?string $lastFailureType=null; private \Closure $clock; private ?\Closure $idFactory;
	public function __construct(private readonly PanelTelemetryExporter $exporter,?PanelDeterministicTelemetrySampler $sampler=null,?PanelTelemetryPropagator $propagator=null,?callable $clock=null,?callable $idFactory=null){$this->sampler=$sampler??new PanelDeterministicTelemetrySampler();$this->propagator=$propagator??new PanelTelemetryPropagator();$this->clock=$clock===null?static fn():float=>microtime(true):\Closure::fromCallable($clock);$this->idFactory=$idFactory===null?null:\Closure::fromCallable($idFactory);}
	private PanelDeterministicTelemetrySampler $sampler; private PanelTelemetryPropagator $propagator;
	public function exporter():PanelTelemetryExporter{return$this->exporter;} public function sampler():PanelDeterministicTelemetrySampler{return$this->sampler;} public function propagator():PanelTelemetryPropagator{return$this->propagator;} public function current():?PanelTelemetryContext{return$this->scope===[]?null:$this->scope[array_key_last($this->scope)];}
	/** @param array<mixed,mixed> $headers */ public function extract(array $headers):?PanelTelemetryContext{return$this->propagator->extract($headers);} /** @param array<mixed,mixed> $headers @return array<string,string> */ public function inject(PanelTelemetryContext $context,array $headers=[]):array{return$this->propagator->inject($context,$headers);}
	public function context(string $name='panel.telemetry'):PanelTelemetryContext{$current=$this->current();if($current instanceof PanelTelemetryContext){return$current;}$traceId=$this->id(16);return PanelTelemetryContext::root($this->sampler->sample($traceId,$name),[],'',$traceId,$this->id(8));}
	/** @param array<string,mixed> $attributes */ public function startTrace(string $name,array $attributes=[],?PanelTelemetryContext $parent=null,string $kind='internal'):PanelTelemetrySpan{return$this->start(PanelTelemetrySignal::TRACE,$name,$attributes,$parent,$kind);}
	/** @param array<string,mixed> $attributes */ public function startSpan(string $name,array $attributes=[],?PanelTelemetryContext $parent=null,string $kind='internal'):PanelTelemetrySpan{return$this->start(PanelTelemetrySignal::SPAN,$name,$attributes,$parent,$kind);}
	public function activate(PanelTelemetryContext $context,callable $callback):mixed{$this->scope[]=$context;try{return$callback();}finally{array_pop($this->scope);}}
	/** @param array<string,mixed> $attributes */ public function trace(string $name,callable $callback,array $attributes=[],?PanelTelemetryContext $parent=null,string $kind='internal'):mixed{$span=$this->startTrace($name,$attributes,$parent,$kind);return$span->activate(function()use($callback,$span):mixed{try{$result=$callback($span);$span->end();return$result;}catch(\Throwable $error){$span->fail($error);throw$error;}});}
	/** @param array<string,mixed> $attributes */ public function event(string $name,array $attributes=[],?PanelTelemetryContext $context=null,string $severity='info'):void{$context=$context??$this->context($name);$this->emit(PanelTelemetrySignal::event($name,$context,$this->now(),$attributes,$severity));}
	/** @param array<string,mixed> $attributes */ public function measurement(string $name,int|float $value,string $unit='1',array $attributes=[],?PanelTelemetryContext $context=null):void{$context=$context??$this->context($name);$this->emit(PanelTelemetrySignal::measurement($name,$context,$this->now(),$value,$unit,$attributes));}
	/** @param array<string,mixed> $attributes */ public function finishSpan(PanelTelemetrySpan $span,string $status,array $attributes,\Throwable|string|null $error):void{$endedAt=$this->now();$signal=$span->signal()===PanelTelemetrySignal::TRACE?PanelTelemetrySignal::trace($span->name(),$span->context(),$span->startedAt(),$endedAt,$status,$attributes,$error,$span->parentSpanId(),$span->kind()):PanelTelemetrySignal::span($span->name(),$span->context(),$span->startedAt(),$endedAt,$status,$attributes,$error,$span->parentSpanId(),$span->kind());$this->activeSpans=max(0,$this->activeSpans-1);$this->emit($signal);}
	public function emit(PanelTelemetrySignal $signal):void{if(!$signal->context()->sampled()){$this->dropped++;return;}try{$this->exporter->export($signal);$this->emitted[$signal->signal()]=($this->emitted[$signal->signal()]??0)+1;}catch(\Throwable $error){$this->exportFailures++;$this->lastFailureType=$error::class;}}
	public function flush():bool{try{$this->exporter->flush();return true;}catch(\Throwable $error){$this->flushFailures++;$this->lastFailureType=$error::class;return false;}}
	public function manifest():array{try{$exporter=PanelSensitiveDataSanitizer::sanitize($this->exporter->manifest(),['max_depth'=>8,'max_items'=>128,'max_string_bytes'=>512]);if(!is_array($exporter)){$exporter=['type'=>$this->exporter::class];}}catch(\Throwable){$exporter=['type'=>$this->exporter::class,'manifest'=>'failed'];}$emitted=$this->emitted;ksort($emitted);return['type'=>'panel_telemetry_hub','schema_version'=>1,'contracts'=>['trace'=>1,'span'=>1,'event'=>1,'measurement'=>1],'propagation'=>$this->propagator,'sampling'=>$this->sampler,'exporter'=>$exporter,'counters'=>['emitted'=>$emitted,'dropped'=>$this->dropped,'export_failures'=>$this->exportFailures,'flush_failures'=>$this->flushFailures,'active_spans'=>$this->activeSpans],'last_failure_type'=>$this->lastFailureType];}
	public function jsonSerialize():array{return$this->manifest();}
	/** @param array<string,mixed> $attributes */ private function start(string $signal,string $name,array $attributes,?PanelTelemetryContext $parent,string $kind):PanelTelemetrySpan{$parent=$parent??$this->current();$parentSpan=$parent?->spanId();if($parent instanceof PanelTelemetryContext){$context=$parent->child($this->id(8));}else{$traceId=$this->id(16);$context=PanelTelemetryContext::root($this->sampler->sample($traceId,$name,$attributes),[],'',$traceId,$this->id(8));}$this->activeSpans++;return new PanelTelemetrySpan($this,$signal,$name,$context,$this->now(),$attributes,$parentSpan,$kind);}
	private function now():float{try{$value=($this->clock)();if(is_int($value)||is_float($value)){$value=(float)$value;if(is_finite($value)&&$value>=0){return$value;}}}catch(\Throwable){}return microtime(true);}
	private function id(int $bytes):string{if($this->idFactory!==null){try{$value=($this->idFactory)($bytes);if(is_string($value)&&strlen($value)===$bytes*2&&preg_match('/^[0-9a-f]+$/D',$value)===1&&trim($value,'0')!==''){return$value;}}catch(\Throwable){}}try{$value=bin2hex(random_bytes($bytes));}catch(\Throwable){$value=substr(hash('sha256',uniqid('panel-telemetry-',true).microtime(true)),0,$bytes*2);}return trim($value,'0')===''?str_repeat('0',$bytes*2-1).'1':$value;}
}
