<?php
declare(strict_types=1);
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
namespace Dataphyre\Panel;

/** Versioned, bounded and recursively sanitized telemetry envelope. */
final class PanelTelemetrySignal implements \JsonSerializable {
	public const VERSION=1; public const TRACE='trace'; public const SPAN='span'; public const EVENT='event'; public const MEASUREMENT='measurement';
	private function __construct(private readonly string $signal,private readonly string $name,private readonly PanelTelemetryContext $context,private readonly string $timestamp,private readonly array $attributes,private readonly array $body){if(!in_array($signal,[self::TRACE,self::SPAN,self::EVENT,self::MEASUREMENT],true)){throw new \InvalidArgumentException('Unsupported Panel telemetry signal.');}}
	/** @param array<string,mixed> $attributes */ public static function trace(string $name,PanelTelemetryContext $context,float $startedAt,float $endedAt,string $status='ok',array $attributes=[],\Throwable|string|null $error=null,?string $parentSpanId=null,string $kind='internal'):self{return self::timed(self::TRACE,$name,$context,$startedAt,$endedAt,$status,$attributes,$error,$parentSpanId,$kind);}
	/** @param array<string,mixed> $attributes */ public static function span(string $name,PanelTelemetryContext $context,float $startedAt,float $endedAt,string $status='ok',array $attributes=[],\Throwable|string|null $error=null,?string $parentSpanId=null,string $kind='internal'):self{return self::timed(self::SPAN,$name,$context,$startedAt,$endedAt,$status,$attributes,$error,$parentSpanId,$kind);}
	/** @param array<string,mixed> $attributes */ public static function event(string $name,PanelTelemetryContext $context,float $at,array $attributes=[],string $severity='info'):self{$severity=Resource::normalizeName($severity);if(!in_array($severity,['debug','info','notice','warning','error','critical'],true)){$severity='info';}return new self(self::EVENT,self::normalizeName($name),$context,self::timestamp($at),self::normalizeAttributes($attributes),['severity'=>$severity]);}
	/** @param array<string,mixed> $attributes */ public static function measurement(string $name,PanelTelemetryContext $context,float $at,int|float $value,string $unit='1',array $attributes=[]):self{if(is_float($value)&&!is_finite($value)){throw new \InvalidArgumentException('Telemetry measurements must be finite.');}$unit=trim($unit);if($unit===''||strlen($unit)>63||preg_match('/^[A-Za-z0-9%._\/-]+$/D',$unit)!==1){throw new \InvalidArgumentException('Telemetry measurement unit is invalid.');}return new self(self::MEASUREMENT,self::normalizeName($name),$context,self::timestamp($at),self::normalizeAttributes($attributes),['value'=>$value,'unit'=>$unit]);}
	public function signal():string{return$this->signal;} public function name():string{return$this->name;} public function context():PanelTelemetryContext{return$this->context;} public function attributes():array{return$this->attributes;} public function body():array{return$this->body;}
	public function jsonSerialize():array{return['type'=>'panel_telemetry_signal','schema_version'=>self::VERSION,'signal'=>$this->signal,'name'=>$this->name,'timestamp'=>$this->timestamp,'context'=>$this->context,'attributes'=>$this->attributes,'body'=>$this->body];}
	/** @param array<string,mixed> $attributes */ private static function timed(string $signal,string $name,PanelTelemetryContext $context,float $startedAt,float $endedAt,string $status,array $attributes,\Throwable|string|null $error,?string $parentSpanId,string $kind):self{if($endedAt<$startedAt){$endedAt=$startedAt;}$status=Resource::normalizeName($status);if(!in_array($status,['unset','ok','error'],true)){$status='unset';}$kind=Resource::normalizeName($kind);if(!in_array($kind,['internal','server','client','producer','consumer'],true)){$kind='internal';}$parentSpanId=is_string($parentSpanId)&&preg_match('/^[0-9a-f]{16}$/D',$parentSpanId)===1&&trim($parentSpanId,'0')!==''?$parentSpanId:null;$body=['start_time'=>self::timestamp($startedAt),'end_time'=>self::timestamp($endedAt),'duration_ms'=>round(max(0,$endedAt-$startedAt)*1000,6),'status'=>$status,'kind'=>$kind,'parent_span_id'=>$parentSpanId];$descriptor=self::error($error);if($descriptor!==null){$body['error']=$descriptor;$body['status']='error';}return new self($signal,self::normalizeName($name),$context,self::timestamp($endedAt),self::normalizeAttributes($attributes),$body);}
	private static function normalizeName(string $name):string{$name=Resource::normalizeName($name);if($name===''){$name='telemetry';}return substr($name,0,128);}
	private static function timestamp(float $time):string{if(!is_finite($time)||$time<0){throw new \InvalidArgumentException('Telemetry timestamp is invalid.');}$seconds=(int)floor($time);$micros=(int)floor(($time-$seconds)*1000000);return gmdate('Y-m-d\TH:i:s',$seconds).sprintf('.%06dZ',$micros);}
	/** @param array<string,mixed> $attributes @return array<string,mixed> */ private static function normalizeAttributes(array $attributes):array{$clean=self::value($attributes,0);$clean=PanelSensitiveDataSanitizer::sanitize($clean,['max_depth'=>8,'max_items'=>64,'max_string_bytes'=>512]);return is_array($clean)?$clean:[];}
	private static function value(mixed $value,int $depth):mixed{if($depth>8){return['type'=>get_debug_type($value),'truncated'=>'depth'];}if($value instanceof \Throwable){return['exception_type'=>$value::class,'exception_code'=>is_int($value->getCode())?$value->getCode():0];}if(is_object($value)){return['type'=>'object','class'=>$value::class];}if(is_resource($value)){return['type'=>'resource','resource_type'=>get_resource_type($value)];}if(is_array($value)){$out=[];$count=0;foreach($value as$key=>$item){if($count++>=64){$out['__truncated_items__']=count($value)-64;break;}$out[$key]=self::value($item,$depth+1);}return$out;}return$value;}
	/** @return array<string,mixed>|null */ private static function error(\Throwable|string|null $error):?array{if($error===null){return null;}$type=$error instanceof \Throwable?$error::class:'RuntimeException';$code=$error instanceof \Throwable&&is_int($error->getCode())?$error->getCode():0;$message=$error instanceof \Throwable?$error->getMessage():$error;$safe=PanelSensitiveDataSanitizer::sanitize($message,['max_depth'=>2,'max_items'=>2,'max_string_bytes'=>1024]);return['type'=>$type,'code'=>$code,'message_fingerprint'=>hash('sha256',is_string($safe)?$safe:'telemetry-error')];}
}
