<?php
/*************************************************************************
 * Dataphyre
 *
 * Copyright (c) 2026 Shopiro Ltd.
 * SPDX-License-Identifier: MIT
 */
declare(strict_types=1);
namespace Dataphyre\Panel;

/** Accessible SSR renderer for the route-free progressive Panel Studio editor. */
final class PanelStudioEditorRenderer implements \JsonSerializable {
	public const VERSION=3;
	private const CATEGORIES=[
		'Page structure'=>['page','form','form_section','show','show_section','tabs','tab'],
		'Data and tables'=>['field','table','column','filters','filter','table_views','table_view','infolist','infolist_entry'],
		'Data canvases'=>['data_surface'],
		'Processes'=>['workflow','workflow_state','workflow_transition'],
		'Actions'=>['toolbar','actions','action'],
		'Navigation'=>['navigation','navigation_group','navigation_item'],
		'Visual summaries'=>['widget_grid','widget','board','board_column'],
	];
	public static function render(PanelStudioEditorSession $session,PanelStudioEditorOptions $options):string{
		$id=$options->editorId();$direction=$options->direction()==='auto'?'':' dir="'.self::e($options->direction()).'"';$validation=$session->validation();$selected=$session->selectedNode();$root=$session->definition()->root();$collaboration=$options->collaborationConnector()?->snapshot($session);
		$model=['contract_version'=>self::VERSION,'definition'=>$root,'schema_registry'=>$session->manager()->registry()->manifest(),'selected_path'=>$session->selectedPath(),'base_revision'=>$session->baseRevision(),'base_hash'=>$session->baseHash(),'dirty'=>$session->dirty(),'conflicted'=>$session->conflicted(),'diagnostics'=>array_map(static fn(PanelStudioDiagnostic $diagnostic):array=>$diagnostic->jsonSerialize(),$session->diagnostics()),'collaboration'=>$collaboration?->model(),'collaboration_transport'=>$options->collaborationTransport()?->browserModel(),'csrf_field'=>$options->csrfName()];
		$modelJson=self::json($model);$definitionJson=self::json($root);$assets=$options->inlineAssets()?PanelStudioEditorAssets::styleTag($options->nonce()):'';
		$html=$assets.'<div id="'.self::e($id).'" class="dp-studio" data-dp-studio-editor data-dp-studio-theme="'.self::e($options->theme()).'" data-dp-studio-zoom="'.self::e($options->zoom()).'" data-dp-studio-reflow="'.self::e($options->reflow()).'" data-dp-studio-dirty="'.($session->dirty()?'true':'false').'" data-dp-studio-selected="'.self::e($session->selectedPath()).'" data-dp-studio-collaboration-live="'.($options->collaborationTransport()?'true':'false').'"'.$direction.'>';
		$html.='<a class="dp-studio-skip" href="#'.self::e($id).'-canvas">Skip to canvas</a>';
		$html.='<form class="dp-studio-command-form" method="post" action="'.self::e($options->actionUrl()).'" data-dp-studio-command-form novalidate>';
		$html.=self::hidden($options->csrfName(),$options->csrfToken()).self::hidden('studio_base_revision',(string)$session->baseRevision()).self::hidden('studio_base_hash',$session->baseHash()).self::hidden('studio_selected_path',$session->selectedPath(),'data-dp-studio-selection-field');
		$html.='<textarea hidden name="studio_definition_json" data-dp-studio-definition-field>'.self::e($definitionJson).'</textarea>';
		$html.=self::hidden('studio_idempotency_key','studio-editor-save-'.$session->baseRevision().'-'.substr($session->definition()->hash(),0,32));
		$html.=self::header($session,$options,$validation);
		$html.=self::mobileNavigation($id);
		$html.='<div class="dp-studio-workspace">';
		$html.=self::palette($session,$selected,$id);
		$html.=self::tree($session,$root,$session->selectedPath(),$root['key'],$id);
		$html.=self::canvas($session,$options,$root,$session->selectedPath(),$root['key']);
		$html.=self::properties($session,$selected,$id);
		$html.='</div>'.($collaboration?self::renderCollaboration($collaboration,$id):'').self::diagnostics($session,$id).'</form>';
		if($session->previewIntent()&&$options->previewUrl()!==''){$html.=self::signedPreview($session->previewIntent(),$options);}
		$html.='<script type="application/json" data-dp-studio-model>'.self::scriptJson($modelJson).'</script><p class="dp-studio-visually-hidden" aria-live="polite" aria-atomic="true" data-dp-studio-status></p></div>';
		if($options->inlineAssets()){$html.=PanelStudioEditorAssets::scriptTag($options->nonce());}
		return$html;
	}
	public static function manifest(?PanelStudioEditorSession $session=null):array{return['type'=>'panel_studio_editor_renderer','version'=>self::VERSION,'surface'=>'route_free_embeddable','assets'=>PanelStudioEditorAssets::manifest(),'session'=>$session?->jsonSerialize(),'contracts'=>['ssr_no_js'=>true,'progressive_enhancement'=>true,'semantic_tree'=>true,'trusted_property_inspector'=>true,'complete_default_kind_palette'=>true,'board_and_infolist_inspector'=>true,'data_surface_inspector'=>true,'workflow_graph_inspector'=>true,'outline_canvas'=>true,'signed_preview_post'=>true,'same_origin_actions'=>true,'collaborative_review_workspace'=>true,'scoped_identity_connector'=>true,'signed_live_collaboration'=>true,'server_rendered_collaboration_deltas'=>true],'accessibility'=>['keyboard_tree'=>true,'keyboard_reorder'=>true,'pointer_drag_reorder'=>true,'focus_preservation'=>true,'live_announcements'=>true,'reduced_motion'=>true,'forced_colors'=>true,'rtl'=>true,'responsive_reflow'=>true]];}
	public function jsonSerialize():array{return self::manifest();}

	private static function header(PanelStudioEditorSession $session,PanelStudioEditorOptions $options,PanelStudioValidation $validation):string{
		$state=$session->conflicted()?'Conflict':($session->dirty()?'Unsaved changes':($session->baseRevision()>0?'Saved revision '.$session->baseRevision():'New document'));
		$html='<header class="dp-studio-header"><div class="dp-studio-heading"><h2>'.self::e($options->title()).'</h2><p>'.self::e($session->document()->title()).'</p><span class="dp-studio-state" data-dp-studio-state>'.self::e($state).'</span></div><div class="dp-studio-actions" aria-label="Editor actions">';
		$html.=self::commandButton('undo','Undo','dp-studio-button',$session->canUndo(),['data-dp-studio-action'=>'undo','data-dp-studio-focus'=>'action:undo']);
		$html.=self::commandButton('redo','Redo','dp-studio-button',$session->canRedo(),['data-dp-studio-action'=>'redo','data-dp-studio-focus'=>'action:redo']);
		$html.=self::commandButton('refresh','Check remote','dp-studio-button',true,['data-dp-studio-submit'=>'refresh']);
		if($session->dirty()||$session->conflicted()){$html.=self::commandButton('discard','Reload remote','dp-studio-button dp-studio-button-danger',$session->baseRevision()>0,['data-dp-studio-submit'=>'discard']);}
		$html.=self::commandButton('preview','Prepare preview','dp-studio-button',!$session->dirty()&&!$session->conflicted()&&$session->baseRevision()>0&&$validation->valid(),['data-dp-studio-submit'=>'preview']);
		$html.=self::commandButton('save','Save draft','dp-studio-button dp-studio-button-primary',!$session->conflicted()&&$validation->valid(),['data-dp-studio-submit'=>'save']);
		return$html.'</div></header>';
	}
	private static function mobileNavigation(string $id):string{
		$html='<nav class="dp-studio-mobile-nav" aria-label="Editor panels">';foreach(['palette'=>'Palette','tree'=>'Tree','canvas'=>'Canvas','properties'=>'Properties']as$key=>$label){$html.='<button type="button" class="dp-studio-button" data-dp-studio-mobile-panel="'.$key.'" aria-controls="'.self::e($id.'-'.$key).'" aria-pressed="'.($key==='canvas'?'true':'false').'">'.$label.'</button>';}return$html.'</nav>';
	}
	private static function palette(PanelStudioEditorSession $session,array $selected,string $id):string{
		$selectedSchema=$session->manager()->registry()->schema((string)$selected['kind']);$html='<section id="'.self::e($id).'-palette" class="dp-studio-pane dp-studio-palette" data-dp-studio-panel="palette" aria-labelledby="'.self::e($id).'-palette-title"><header class="dp-studio-pane-header"><div><h3 id="'.self::e($id).'-palette-title">Palette</h3><p>Add trusted children to the selection.</p></div></header><div class="dp-studio-pane-body dp-studio-scroll-region">';
		foreach(self::CATEGORIES as$category=>$kinds){$html.='<section class="dp-studio-palette-group"><h4>'.self::e($category).'</h4>';foreach($kinds as$kind){if(!in_array($kind,PanelStudioDefinition::KINDS,true)){continue;}$schema=$session->manager()->registry()->schema($kind);$portable=!$schema;$allowed=$schema&&$selectedSchema?->childRule($kind)instanceof PanelStudioChildRule;$reason=$portable?'Portable only':($allowed?'Trusted':'Parent needed');$html.='<button type="submit" name="studio_add_kind" value="'.self::e($kind).'" class="dp-studio-palette-item" data-dp-studio-add="'.self::e($kind).'"'.($allowed?'':' disabled aria-disabled="true"').' title="'.self::e($portable?'This kind remains portable-only and cannot be materialized.':($allowed?'Add to the selected component.':'Select a compatible parent first.')).'"><span>'.self::e(self::label($kind)).'</span><span class="dp-studio-affordance">'.self::e($reason).'</span></button>';}$html.='</section>';}
		return$html.'</div>'.self::hidden('studio_parent',$session->selectedPath()).'</section>';
	}
	private static function tree(PanelStudioEditorSession $session,array $node,string $selected,string $path,string $id):string{
		$inner=self::treeItem($session,$node,$selected,$path,1);
		return'<section id="'.self::e($id).'-tree" class="dp-studio-pane dp-studio-tree" data-dp-studio-panel="tree" aria-labelledby="'.self::e($id).'-tree-title"><header class="dp-studio-pane-header"><div><h3 id="'.self::e($id).'-tree-title">Component tree</h3><p>Alt plus arrow keys reorder.</p></div></header><div class="dp-studio-pane-body dp-studio-scroll-region" data-dp-studio-tree><ol class="dp-studio-tree-list" role="tree" aria-label="Studio component tree">'.$inner.'</ol></div></section>';
	}
	private static function treeItem(PanelStudioEditorSession $session,array $node,string $selected,string $path,int $level):string{
		$label=self::nodeLabel($node);$hasChildren=$node['children']!==[];$html='<li role="none"><div class="dp-studio-tree-row" data-dp-studio-path="'.self::e($path).'" data-dp-studio-selected="'.($path===$selected?'true':'false').'"><button type="submit" name="studio_select" value="'.self::e($path).'" class="dp-studio-tree-select" role="treeitem" aria-level="'.$level.'" aria-selected="'.($path===$selected?'true':'false').'"'.($hasChildren?' aria-expanded="true"':'').' draggable="true" data-dp-studio-treeitem data-dp-studio-action="select" data-dp-studio-path="'.self::e($path).'" data-dp-studio-focus="node:'.self::e($path).'"><span class="dp-studio-tree-kind">'.self::e(substr($node['kind'],0,3)).'</span><span class="dp-studio-tree-text"><strong>'.self::e($label).'</strong><small>'.self::e($node['key']).'</small></span></button><span class="dp-studio-tree-tools">';
		foreach(['up'=>['Up','&#8593;'],'down'=>['Down','&#8595;'],'indent'=>['Indent','&#8627;'],'outdent'=>['Outdent','&#8624;']]as$direction=>[$title,$glyph]){$html.='<button type="submit" name="studio_move" value="'.$direction.':'.self::e($path).'" class="dp-studio-tree-tool" aria-label="'.$title.' '.self::e($node['key']).'" data-dp-studio-action="move" data-dp-studio-direction="'.$direction.'" data-dp-studio-path="'.self::e($path).'" data-dp-studio-focus="move:'.$direction.':'.self::e($path).'">'.$glyph.'</button>';}
		if($level>1){$html.='<button type="submit" name="studio_remove" value="'.self::e($path).'" class="dp-studio-tree-tool dp-studio-button-danger" aria-label="Remove '.self::e($node['key']).'" data-dp-studio-action="remove" data-dp-studio-path="'.self::e($path).'" data-dp-studio-focus="remove:'.self::e($path).'">&times;</button>';}$html.='</span></div>';
		if($hasChildren){$html.='<ol role="group">';foreach($node['children']as$child){$html.=self::treeItem($session,$child,$selected,$path.'/'.$child['key'],$level+1);}$html.='</ol>';}return$html.'</li>';
	}
	private static function canvas(PanelStudioEditorSession $session,PanelStudioEditorOptions $options,array $root,string $selected,string $path):string{
		$html='<section id="'.self::e($options->editorId()).'-canvas" class="dp-studio-pane dp-studio-canvas" data-dp-studio-panel="canvas" aria-labelledby="'.self::e($options->editorId()).'-canvas-title"><header class="dp-studio-pane-header"><div><h3 id="'.self::e($options->editorId()).'-canvas-title">Canvas</h3><p>Structural preview. Signed preview uses trusted materialization.</p></div><div class="dp-studio-canvas-controls"><label>Zoom <select data-dp-studio-zoom-control aria-label="Canvas zoom">';foreach(['75'=>'75%','100'=>'100%','125'=>'125%','fit'=>'Fit']as$value=>$label){$html.='<option value="'.$value.'"'.($options->zoom()===$value?' selected':'').'>'.$label.'</option>';}$html.='</select></label><label>Reflow <select data-dp-studio-reflow-control aria-label="Canvas reflow">';foreach(['desktop'=>'Desktop','tablet'=>'Tablet','mobile'=>'Mobile']as$value=>$label){$html.='<option value="'.$value.'"'.($options->reflow()===$value?' selected':'').'>'.$label.'</option>';}$html.='</select></label></div></header><div class="dp-studio-canvas-viewport" data-dp-studio-canvas><div class="dp-studio-canvas-sheet">'.self::canvasNode($root,$selected,$path).'</div></div></section>';return$html;
	}
	private static function canvasNode(array $node,string $selected,string $path):string{
		$label=self::nodeLabel($node);$html='<article class="dp-studio-canvas-node" data-dp-studio-path="'.self::e($path).'" data-dp-studio-selected="'.($path===$selected?'true':'false').'" tabindex="-1"><button type="submit" name="studio_select" value="'.self::e($path).'" class="dp-studio-canvas-node-header" data-dp-studio-action="select" data-dp-studio-path="'.self::e($path).'" data-dp-studio-focus="canvas:'.self::e($path).'"><strong>'.self::e($label).'</strong><span>'.self::e($node['kind']).'</span></button>';
		if(is_string($node['properties']['description']??null)&&$node['properties']['description']!==''){$html.='<p class="dp-studio-canvas-help">'.self::e($node['properties']['description']).'</p>';}
		if($node['kind']==='field'){$type=(string)($node['properties']['type']??'text');$placeholder=(string)($node['properties']['placeholder']??$label);$html.=$type==='textarea'?'<textarea class="dp-studio-canvas-control" aria-label="'.self::e($label).'" disabled></textarea>':'<input class="dp-studio-canvas-control" type="'.(in_array($type,['number','integer'],true)?'number':'text').'" placeholder="'.self::e($placeholder).'" aria-label="'.self::e($label).'" disabled>';}
		if($node['kind']==='data_surface'){$surface=(string)($node['properties']['surface']??'table');$fields=is_array($node['properties']['fields']??null)?count($node['properties']['fields']):0;$html.='<p class="dp-studio-canvas-help"><strong>'.self::e(ucfirst($surface)).'</strong> · '.$fields.' projected field'.($fields===1?'':'s').'</p>';}
		if($node['kind']==='workflow'){$states=count(array_filter($node['children'],static fn(array $child):bool=>$child['kind']==='workflow_state'));$transitions=count(array_filter($node['children'],static fn(array $child):bool=>$child['kind']==='workflow_transition'));$html.='<p class="dp-studio-canvas-help"><strong>Process graph</strong> · '.$states.' state'.($states===1?'':'s').' · '.$transitions.' transition'.($transitions===1?'':'s').'</p>';}
		if($node['kind']==='workflow_state'){$html.='<p class="dp-studio-canvas-help">'.(($node['properties']['terminal']??false)===true?'Terminal state':((($node['properties']['draft']??false)===true)?'Draft state':'Active state')).'</p>';}
		if($node['kind']==='workflow_transition'){$from=is_array($node['properties']['from_states']??null)?implode(', ',$node['properties']['from_states']):'Not set';$to=(string)($node['properties']['to_state']??'Not set');$html.='<p class="dp-studio-canvas-help">'.self::e($from).' -&gt; '.self::e($to).'</p>';}
		if($node['children']!==[]){$html.='<div class="dp-studio-canvas-children">';foreach($node['children']as$child){$html.=self::canvasNode($child,$selected,$path.'/'.$child['key']);}$html.='</div>';}return$html.'</article>';
	}
	private static function properties(PanelStudioEditorSession $session,array $node,string $id):string{
		$schema=$session->manager()->registry()->schema((string)$node['kind']);$path=$session->selectedPath();$html='<section id="'.self::e($id).'-properties" class="dp-studio-pane dp-studio-properties" data-dp-studio-panel="properties" aria-labelledby="'.self::e($id).'-properties-title"><header class="dp-studio-pane-header"><div><h3 id="'.self::e($id).'-properties-title">Properties</h3><p>'.self::e(self::label((string)$node['kind'])).'</p></div></header><div class="dp-studio-pane-body dp-studio-scroll-region" data-dp-studio-properties>';
		if(!$schema){return$html.'<p class="dp-studio-secret-note">This kind is portable-only. It can be inspected in blueprints but cannot be edited or materialized by the trusted Studio runtime.</p></div></section>';}
		$keyId=$id.'-property-key';$html.='<div class="dp-studio-properties-fields">'.self::propertyField('Component key','<input id="'.self::e($keyId).'" type="text" name="studio_key" value="'.self::e((string)$node['key']).'" pattern="[a-z][a-z0-9_.\\-]{0,127}" required autocomplete="off" data-dp-studio-key data-dp-studio-focus="property:'.self::e($path).':key">',$keyId,'Stable lowercase identity within its parent.');
		foreach($schema->properties()as$index=>$property){if($node['kind']==='field'&&($node['properties']['type']??null)==='password'&&$property->name()==='default'){$html.='<p class="dp-studio-secret-note">Credential defaults are never editable or serialized.</p>';continue;}$html.=self::schemaProperty($property,$node['properties'],$path,$index,$id);}
		$html.='</div><button type="submit" name="studio_action" value="update" class="dp-studio-button dp-studio-only-no-js">Apply properties</button>'.self::hidden('studio_path',$path).'</div></section>';return$html;
	}
	private static function schemaProperty(PanelStudioPropertySchema $property,array $properties,string $path,int|string $index,string $editorId):string{
		$name=$property->name();$manifest=$property->manifest();$exists=array_key_exists($name,$properties);$value=$properties[$name]??null;$id=$editorId.'-property-'.$index;$attributes=' id="'.self::e($id).'" name="studio_properties['.self::e($name).']" data-dp-studio-property-input="'.self::e($name).'" data-dp-studio-property-type="'.self::e($property->type()).'" data-dp-studio-focus="property:'.self::e($path).':'.self::e($name).'"';$control='';
		if($property->type()==='boolean'){$control='<label class="dp-studio-check"><input type="checkbox"'.$attributes.' value="1"'.($value===true?' checked':'').'>'.self::e(self::label($name)).'</label>'.self::hidden('studio_boolean_fields[]',$name);return'<div class="dp-studio-field" data-dp-studio-property="'.self::e($name).'"><span class="dp-studio-visually-hidden">'.self::e(self::label($name)).'</span>'.$control.'<small>'.self::e(self::propertyHelp($manifest)).'</small></div>';}
		if(($manifest['enum']??[])!==[]){$control='<select'.$attributes.' data-dp-studio-encoding="json"><option value="__dp_studio_unset__">'.($property->hasDefault()?'Use schema default':'Not set').'</option>';foreach($manifest['enum']as$option){$encoded=self::json($option);$control.='<option value="'.self::e($encoded).'"'.($exists&&self::json($value)===$encoded?' selected':'').'>'.self::e(is_scalar($option)?(string)$option:self::json($option)).'</option>';}$control.='</select>';}
		elseif(in_array($property->type(),['string_list','number_list','scalar_map'],true)){$control='<textarea'.$attributes.'>'.self::e($exists?json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR):'').'</textarea>';}
		else{$type=in_array($property->type(),['integer','number'],true)?'number':'text';$step=$property->type()==='integer'?' step="1"':($property->type()==='number'?' step="any"':'');$control='<input'.$attributes.' type="'.$type.'"'.$step.' value="'.self::e($exists&&$value!==null?(string)$value:'').'" autocomplete="off">';}
		return self::propertyField(self::label($name),$control,$id,self::propertyHelp($manifest),$name);
	}
	private static function propertyField(string $label,string $control,string $id,string $help,string $name='__key'):string{return'<div class="dp-studio-field" data-dp-studio-property="'.self::e($name).'"><label for="'.self::e($id).'">'.self::e($label).'</label>'.$control.'<small>'.self::e($help).'</small></div>';}
	private static function propertyHelp(array $manifest):string{$values=[(string)$manifest['type']];if($manifest['required']){$values[]='required';}if($manifest['nullable']){$values[]='nullable';}$bounds=$manifest['bounds']??[];if(($bounds['min']??null)!==null){$values[]='minimum '.$bounds['min'];}if(($bounds['max']??null)!==null){$values[]='maximum '.$bounds['max'];}return implode(', ',$values).'.';}
	public static function renderCollaboration(PanelStudioWorkspaceSnapshot $snapshot,string $id):string{
		$current=$snapshot->currentIdentity();$assignment=$snapshot->assignment();$chain=$snapshot->receiptChain();$assignable=array_values(array_filter($snapshot->directory(),static fn(PanelStudioIdentityProfile $profile):bool=>$profile->assignable()));$sectionId=$id.'-collaboration';
		$html='<section id="'.self::e($sectionId).'" class="dp-studio-collaboration" data-dp-studio-collaboration data-dp-studio-collaboration-cursor="'.$snapshot->cursor().'" aria-labelledby="'.self::e($sectionId).'-title"><header class="dp-studio-collaboration-header"><div><h3 id="'.self::e($sectionId).'-title">Review workspace</h3><p>Document-scoped discussion, ownership, and live presence.</p></div><div class="dp-studio-collaboration-current">'.self::identity($current).'<span class="dp-studio-integrity" data-valid="'.($chain['valid']?'true':'false').'">'.($chain['valid']?'Receipt chain verified':'Receipt chain warning').'</span><span class="dp-studio-live-status" data-dp-studio-collaboration-live-status aria-live="polite">Server synchronized</span></div></header>';
		$html.='<div class="dp-studio-collaboration-controls"><div class="dp-studio-collaboration-control"><label for="'.self::e($sectionId).'-assignee">Review owner</label><select id="'.self::e($sectionId).'-assignee" name="studio_collaboration_assignee"><option value="">Choose an active identity</option>';
		foreach($assignable as$profile){$html.='<option value="'.self::e($profile->id()).'"'.($assignment?->id()===$profile->id()?' selected':'').'>'.self::e($profile->displayName()).'</option>';}
		$html.='</select><div class="dp-studio-collaboration-buttons"><button type="submit" name="studio_collaboration_operation" value="assign" class="dp-studio-button"'.($assignable===[]?' disabled aria-disabled="true"':'').'>Assign</button>';
		if($assignment){$html.='<button type="submit" name="studio_collaboration_operation" value="unassign" class="dp-studio-button">Unassign</button>';}
		$html.='</div><p>'.($assignment?'Assigned to '.self::e($assignment->displayName()).'.':'No review owner assigned.').'</p></div>';
		$html.='<div class="dp-studio-collaboration-control"><span class="dp-studio-collaboration-label">Following</span><div class="dp-studio-collaboration-buttons"><button type="submit" name="studio_collaboration_operation" value="'.($snapshot->watching()?'unwatch':'watch').'" class="dp-studio-button">'.($snapshot->watching()?'Stop watching':'Watch document').'</button></div><p>'.count($snapshot->watchers()).' watcher'.(count($snapshot->watchers())===1?'':'s').' · '.count($snapshot->presence()).' present now.</p></div>';
		$html.='<div class="dp-studio-collaboration-control dp-studio-collaboration-new"><label for="'.self::e($sectionId).'-thread-title">Start a review thread</label><input id="'.self::e($sectionId).'-thread-title" type="text" name="studio_collaboration_title" maxlength="500" autocomplete="off" placeholder="What needs a decision?"><button type="submit" name="studio_collaboration_operation" value="create_thread" class="dp-studio-button dp-studio-button-primary">Start thread</button></div></div>';
		if($snapshot->presence()!==[]){$html.='<div class="dp-studio-presence" aria-label="People currently in this document"><span>Present</span>';foreach($snapshot->presence()as$item){$html.=self::identity($item['identity']);}$html.='</div>';}
		$html.='<ol class="dp-studio-thread-list">';
		if($snapshot->threads()===[]){$html.='<li class="dp-studio-collaboration-empty">No review threads yet. Start one without leaving the editor.</li>';}
		foreach($snapshot->threads()as$thread){
			$title=trim((string)$thread['title'])!==''?(string)$thread['title']:'Untitled review';$open=$thread['status']==='open';
			$html.='<li class="dp-studio-thread" data-status="'.self::e((string)$thread['status']).'"><header><div><h4>'.self::e($title).'</h4><p>'.self::identity($thread['created_by']).'<time datetime="'.self::e((string)$thread['updated_at']).'">'.self::e((string)$thread['updated_at']).'</time></p></div><span class="dp-studio-thread-status">'.self::e(ucfirst((string)$thread['status'])).'</span></header>';
			$html.='<ol class="dp-studio-comment-list">';
			if($thread['comments']===[]){$html.='<li class="dp-studio-comment-empty">No comments yet.</li>';}
			foreach($thread['comments']as$comment){$html.='<li class="dp-studio-comment"><div>'.self::identity($comment['author']).'<time datetime="'.self::e((string)$comment['created_at']).'">'.self::e((string)$comment['created_at']).'</time></div><p>'.self::e((string)$comment['body']).'</p></li>';}
			$html.='</ol>';
			if($thread['typing']!==[]){$names=array_map(static fn(PanelStudioIdentityProfile $profile):string=>$profile->displayName(),$thread['typing']);$html.='<p class="dp-studio-typing">'.self::e(implode(', ',$names)).' '.(count($names)===1?'is':'are').' typing.</p>';}
			$html.='<div class="dp-studio-thread-compose"><label class="dp-studio-visually-hidden" for="'.self::e($sectionId.'-comment-'.$thread['id']).'">Comment on '.self::e($title).'</label><textarea id="'.self::e($sectionId.'-comment-'.$thread['id']).'" name="studio_collaboration_comments['.self::e((string)$thread['id']).']" maxlength="10000" placeholder="Add a bounded review comment"></textarea><div class="dp-studio-collaboration-buttons"><button type="submit" name="studio_collaboration_operation" value="comment:'.self::e((string)$thread['id']).'" class="dp-studio-button dp-studio-button-primary">Comment</button><button type="submit" name="studio_collaboration_operation" value="'.($open?'resolve':'reopen').':'.self::e((string)$thread['id']).'" class="dp-studio-button">'.($open?'Resolve':'Reopen').'</button></div></div></li>';
		}
		return$html.'</ol></section>';
	}
	private static function identity(PanelStudioIdentityProfile $profile):string{return'<span class="dp-studio-identity" data-status="'.self::e($profile->status()).'"><span class="dp-studio-identity-avatar" aria-hidden="true">'.self::e($profile->initials()).'</span><span>'.self::e($profile->displayName()).'</span></span>';}
	private static function diagnostics(PanelStudioEditorSession $session,string $id):string{
		$diagnostics=$session->diagnostics();$html='<section class="dp-studio-diagnostics" aria-labelledby="'.self::e($id).'-diagnostics-title"><h3 id="'.self::e($id).'-diagnostics-title">Validation diagnostics</h3><ul data-dp-studio-diagnostics-list>';
		if($diagnostics===[]){$html.='<li class="dp-studio-diagnostic" data-severity="info"><code>valid</code><span>No trusted-schema diagnostics.</span></li>';}
		foreach($diagnostics as$diagnostic){$html.='<li class="dp-studio-diagnostic" data-severity="'.self::e($diagnostic->severity()).'"><code>'.self::e($diagnostic->path()).'</code><span>'.self::e($diagnostic->message()).'</span></li>';}
		return$html.'</ul><p class="dp-studio-status" data-dp-studio-status-visible>'.($session->conflicted()?'Reload the remote revision before saving.':'Changes are checked against the active trusted registry.').'</p></section>';
	}
	private static function signedPreview(PanelStudioPreviewIntent $intent,PanelStudioEditorOptions $options):string{return'<form class="dp-studio-signed-preview" method="post" action="'.self::e($options->previewUrl()).'" target="_blank">'.self::hidden($options->csrfName(),$options->csrfToken()).self::hidden('studio_preview_token',$intent->token()).'<p>Preview expires at '.self::e(gmdate('Y-m-d H:i:s T',$intent->expiresAt())).'.</p><button type="submit" class="dp-studio-button dp-studio-button-primary">Open signed preview</button></form>';}
	private static function commandButton(string $value,string $label,string $class,bool $enabled,array $attributes=[]):string{$html='<button type="submit" name="studio_action" value="'.self::e($value).'" class="'.self::e($class).'"';foreach($attributes as$name=>$attribute){$html.=' '.self::e($name).'="'.self::e($attribute).'"';}if(!$enabled){$html.=' disabled aria-disabled="true"';}return$html.'>'.self::e($label).'</button>';}
	private static function hidden(string $name,string $value,string $attributes=''):string{return'<input type="hidden" name="'.self::e($name).'" value="'.self::e($value).'"'.($attributes!==''?' '.$attributes:'').'>';}
	private static function nodeLabel(array $node):string{$label=$node['properties']['label']??null;return is_string($label)&&trim($label)!==''?$label:self::label((string)$node['key']);}
	private static function label(string $value):string{return ucwords(str_replace(['_','-'],' ',$value));}
	private static function json(mixed $value):string{return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);}
	private static function scriptJson(string $json):string{return str_replace(['<','>','&'],['\\u003C','\\u003E','\\u0026'],$json);}
	private static function e(string $value):string{return htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
